### ISSUE TITLE
Undoing changes to the filesystem

### ISSUE THREAD

**Issue by martinklepsch** [ranger/ranger#10]
I don't know if this is especially hard to implement or something but it'd be nice to have basic undo functionality.

**Comment by aureooms** [comment]
I think this is related: How would I configure ranger to use trash ([trash-cli](https://github.com/andreafrancia/trash-cli)) everytime it wants to use `rm`?

@nitrix Just to put my two cents here, I sometimes delete stuff by mistake because I am too tired. Moving to another folder can also be much faster than doing a `rm -rf`.

**Comment by toonn** [comment]
@aureooms, you can edit all the keybindings in `rc.conf` that use `delete` or `rm` if that's used anywhere. *Or* you could try to redefine the `:delete` command in `commands.py` and implement it using `trash-cli`.

**Comment by aureooms** [comment]
@toonn I am looking at the code right now and it looks a bit more complicated than I expected.

For instance, there are many references to destructive commands.
```
$ ag --hidden --ignore .git 'os\.remove|os\.removedirs|os\.rmdir|shutil\.rmtree' ranger
ranger/core/actions.py:1236:                        shutil.rmtree(f.path)
ranger/core/actions.py:1241:                        os.remove(f.path)
ranger/config/commands.py:852:            os.remove(cf.path)
ranger/ext/vcs/git.py:121:            os.rmdir(self.path)
ranger/ext/vcs/bzr.py:106:            os.rmdir(self.path)
ranger/ext/vcs/hg.py:114:            os.rmdir(self.path)
ranger/ext/shutil_generatorized.py:210:    path, exc_info) where func is os.listdir, os.remove, or os.rmdir;
ranger/ext/shutil_generatorized.py:245:                os.remove(fullname)
ranger/ext/shutil_generatorized.py:247:                onerror(os.remove, fullname, sys.exc_info())
ranger/ext/shutil_generatorized.py:249:        os.rmdir(path)
ranger/ext/shutil_generatorized.py:251:        onerror(os.rmdir, path, sys.exc_info())
```

It seems that patching all this code to use `trash-cli` instead would not be very future-proof.

On the other hand, looking at the keybindings, it seems there is some redraw logic in those functions, not just the `rm` command. Changing those does not seem future-proof either.

Maybe this comment deserves its own issue.

**Comment by toonn** [comment]
Doubt any of those are relevant. What I was saying is you implement your own custom commands in `~/.config/ranger/commands.py` (It's a configuration file.) And then you can rebind some keys in `rc.conf` to use *those* commands rather than `:delete` or `:shell rm` etc.
