### ISSUE TITLE
--copy-config option requires an argument

### ISSUE THREAD

**Issue by kirkins** [ranger/ranger#1002]
Trying to follow the README:

> For configuration, check the files in ranger/config/ or copy the default config to ~/.config/ranger with ranger --copy-config.

But when I run the command I get back:

> ranger: error: --copy-config option requires an argument

#### ISSUE TYPE

- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version: Ubuntu 16.04
- Terminal emulator and version: GNU bash, version 4.3.48(1)-release 
- Python version: Python 2.7.12 
- Ranger version/commit: ranger-stable 1.7.1
- Locale: English (?)

#### EXPECTED BEHAVIOR

I'm expecting the command to work with no argument as shown in the README.

#### CURRENT BEHAVIOR

I get back a message saying I need an argument.

#### CONTEXT

I'm just interested in looking at the default config.

#### STEPS TO REPRODUCE

1. 
2. 
3. 
4. 
5. 

#### TRACEBACK

```

```

**Comment by Vifon** [comment]
The README follows it with:

> See ranger --help for a description of that switch.

It shows the available arguments to `--copy-config`. That being said, README indeed could make it a bit clearer.
