### ISSUE TITLE
Memry leak while previewing images

### ISSUE THREAD

**Issue by Ybalrid** [ranger/ranger#1008]
It seems that browsing folders containing images and displaying them inside the terminal with the w3m renderer consume more and more memory until ranger is quited

(this may be an issue with the w3m image renderer itself, and not ranger. But I really doubt it, as browsing website with a lot of images with w3m itself doesn't consume as much memory.

I haven't took the time to look at the code yet, so I may be wrong...)

#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version: Arch Linux 64bit (lattest updates installed. It's a rolling release)
- Terminal emulator and version:  termite v13
- Python version:  3.6.3
- Ranger version/commit:  stable 
- Locale: en_US.UTF8

#### EXPECTED BEHAVIOR
Previewing images should not increase the memory consumption that much, and the memory used by one image.

#### CURRENT BEHAVIOR
Browsing through large colleciton of (e.g.) Jpeg files.

Displaying 25 images (jpeg files around 2.5MB each) makes the ram usage jump by 1 GB.
Apparently this memory is used by w3mimgdisplay

#### CONTEXT
I was just trying out the functionality of previewing image while browsing folders of jpeg pictures

#### POSSIBLE SOLUTIONS
What it looks like to me (I haven't looked at the code yet), ranger is allocating resources for managing the images via w3mimgdisplay, but it's not destroying them when you switch to the next.

I'm a C/C++ guy, not a Python guy, and I haven't attempted to look at the code yet.

#### STEPS TO REPRODUCE
1. Configure ranger to use image preview like explained [on this page](https://github.com/ranger/ranger/wiki/Image-Previews)
2. Open Ranger
3. Navigate to a folder containing pictures
4. Look at them one by one
5. Open a program that allow you to display your memory usage (e.g: htop; watch free -h)

(off topic: I discovered this program recently, and I'm really enjoying it!)

**Comment by Vifon** [comment]
It was already fixed in #978 and should not happen again in the current devel version. There was no "stable" release yet since then.

And yes, it's mostly a problem with w3m itself, we only have a workaround.

> (off topic: I discovered this program recently, and I'm really enjoying it!)

That's awesome to hear! If you have any questions, come over to our IRC channel.
