### ISSUE TITLE
Dual pane display for different directories (side by side)

### ISSUE THREAD

**Issue by cibinmathew** [ranger/ranger#1011]
#### ISSUE TYPE

- Improvement/feature request

#### EXPECTED BEHAVIOR

Dual pane display (different directories on left and right) similar to tabs but stacked side by side.

#### CURRENT BEHAVIOR

Current feature of having multiple **tabs** can be laid out side by side instead of stacking
Use ranger as a single directory explorer with 3 level as well as dual directory explorer with 1/2/3 level visibility.

#### CONTEXT

make ranger a dual pane file explorer like multi commander/Directory opus/xyplorer

#### POSSIBLE SOLUTIONS

This can have option to open highlighted item in other view.
Also it can have a status bar indication to differentiate active view from the inactive view.

**Comment by hut** [comment]
This feature already exists. :) Open a couple of tabs, then press `~`

**Comment by cibinmathew** [comment]
thanks @hut for the info.
