### ISSUE TITLE
How I can unfilter (reset filter) in the current view?

### ISSUE THREAD

**Issue by id777** [ranger/ranger#1014]
There is command in rc.conf: `alias filter scout -prt`

It's awesome, but I can't understand how I can reset filter and get the original view of the current directory. Actually it will be nice to reset filter by ESC (it any filter was set before).

**Comment by hut** [comment]
With `:filter`, as described in the man page ;)

**Comment by id777** [comment]
@hut  Thanks, I know :)
But can I bind :filter (without parameters) option to some key, so I can quickly reset filter by just pressing a key?

**Comment by hut** [comment]
Yes, with `:map X filter` :)

**Comment by id777** [comment]
Thanks! Indeed, it works
