### ISSUE TITLE
command to go to the location of a symlink

### ISSUE THREAD

**Issue by eMPee584** [ranger/ranger#1024]
Some chaining of cd $(execute_command, realpath + basename) I presume. Would this be possible "impromptu", without defining a new command? It would of course be a useful command as well..

**Comment by kutsan** [comment]
Like default `gL` does?

```
map gL cd -r %f
```

**Comment by eMPee584** [comment]
yeah exactly like that :laughing:

**Comment by kutsan** [comment]
@eMPee584 By the way, you don't need to redefine this, it's already default if you did so.
