### ISSUE TITLE
Ranger crashes when I'm trying to run it

### ISSUE THREAD

**Issue by malamut2014** [ranger/ranger#1030]
#### Runtime Environment

- Operating system and version: Gentoo Stable 
- Terminal emulator and version: urxvt 9.21
- Python version: 3.5.4
- Ranger version/commit: 1.9.0_beta5 
- Locale: ru_RU.UTF-8

#### Current Behavior
Trying to run ranger. and I get this: https://imgur.com/a/yawjX
When doing `:r !ranger` in vim: https://imgur.com/a/0yhUP
#### Expected Behavior
That's obvious.
#### Context

Tried to recompile python, ncurses, changing locale to en_US.UTF-8, nothing helps
#### Possible Solutions
Idk
#### Steps to reproduce
I just tried to run ranger, I don't know

#### Traceback
[?1049h[1;24r[m(B[4l[?7h=>Traceback (most recent call last):
  File "./ranger.py", line 36, in <module>
    sys.exit(ranger.main())  # pylint: disable=no-member
  File "/home/malamut2014/ranger-1.9.0b6/ranger/core/main.py", line 226, in main
    fm.ui.destroy()
  File "/home/malamut2014/ranger-1.9.0b6/ranger/gui/ui.py", line 188, in destroy
    self.suspend()
  File "/home/malamut2014/ranger-1.9.0b6/ranger/gui/ui.py", line 140, in suspend
    curses.nocbreak()
_curses.error: nocbreak() returned ERR

**Comment by hut** [comment]
1. it's a really bad idea to run ranger with `:r !ranger`. Can you try `:!ranger` instead?
2. the output of the first image is incomplete. Can you please run `ranger > output.txt` and send me the text file?

**Comment by malamut2014** [comment]
1. https://imgur.com/a/4DAOm
2. [output.txt](https://github.com/ranger/ranger/files/1647609/output.txt)

**Comment by malamut2014** [comment]
I think the problem can be in my gentoo installation, after switching to 17.1 profiles not only ranger stopped working, but also wal and some other python apps. I can try reinstalling the system, I think it could help.

**Comment by malamut2014** [comment]
![ranger](https://user-images.githubusercontent.com/9732705/35448610-abfbf460-02b2-11e8-88e1-baf6ccd09fe8.png)
Nothing really changed after system reinstall.

**Comment by malamut2014** [comment]
Switched to Funtoo, Gentoo fork. At first it was working, in chroot with only system base, but after xorg installation it crashes the same way.

**Comment by malamut2014** [comment]
Recompiled python and re-emerged ranger from master git branch, it works.

**Comment by toonn** [comment]
Thank you for reporting back, appreciate it : )
