### ISSUE TITLE
Cannot start ranger when tmux is not installed | ranger tries to execute binaries without checking for existance and crashes

### ISSUE THREAD

**Issue by mox-mox** [ranger/ranger#1042]
#### Runtime Environment

- Operating system and version: Current Archlinux
- Terminal emulator and version: Linux console or urxvt, does not matter
- Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
- Ranger version/commit: ranger-stable 1.9.0 and/or 14adeb9cfc1d95bda6895883fe70a50a08165589 (tried both)
- Locale: de_DE.utf-8

#### Current Behavior
Cannot start ranger if `tmux` is not installed.

#### Expected Behavior
Obvious

#### Possible Solutions
I think this may be related to ranger trying to run an executable without checking for its existence. Therefore the solution will probably be to check for the existence of the tmux binary before execution.
#### Steps to reproduce
1. uninstall `tmux`
2. try to start ranger

#### Traceback
```
loading...Traceback (most recent call last):
 File "/usr/bin/ranger", line 36, in <module>
 sys.exit(ranger.main()) # pylint: disable=no-member
 File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 226, in main
 fm.ui.destroy()
 File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 184, in destroy
 check_output(['tmux', 'set-window-option', '-u', 'automatic-rename'])
 File "/usr/lib/python3.6/site-packages/ranger/ext/spawn.py", line 35, in check_output
 process = Popen(popenargs, stderr=fd_devnull, **kwargs)
 File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
 restore_signals, start_new_session)
 File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
 raise child_exception_type(errno_num, err_msg, err_filename)
 FileNotFoundError: [Errno 2] No such file or directory: 'tmux': 'tmux'
 Ranger: Install /usr/local/bin/r.shell to allow macro expansion in command line.
```
p.S.: Ranger is really, really cool!

**Comment by toonn** [comment]
Ranger doesn't depend on tmux. I just verified that I can't reproduce this.
I suspect you have `set update_tmux_title true` in your `rc.conf`.
However, I do think people'd prefer this behaviour by default so I'll add some checks.

**Comment by mox-mox** [comment]
Hi, thanks for the quick reply. Yes `set update_tmux_title true` was the issue.
