### ISSUE TITLE
Not handling deleted parent directory elegantly

### ISSUE THREAD

**Issue by jimw567** [ranger/ranger#1052]
#### Runtime Environment

ranger version: ranger-master 1.9.0
Python version: 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
Locale: None.None

#### Current Behavior
* Start ranger from a directory
* From inside ranger, deleted the parent directory
* Exit ranger
* Start ranger again
* It shows the error below
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Traceback (most recent call last):
  File "/github/ranger/ranger.py", line 36, in <module>
    sys.exit(ranger.main())  # pylint: disable=no-member
  File "/github/ranger/ranger/core/main.py", line 99, in main
    paths = [os.environ.get('PWD', os.getcwd())]
OSError: [Errno 2] No such file or directory

#### Expected Behavior
Just a suggestion: if the parent directory doesn't exist any more, maybe start from the home directory instead just thrown an OS error.

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Traceback (most recent call last):
  File "/github/ranger/ranger.py", line 36, in <module>
    sys.exit(ranger.main())  # pylint: disable=no-member
  File "/github/ranger/ranger/core/main.py", line 99, in main
    paths = [os.environ.get('PWD', os.getcwd())]
OSError: [Errno 2] No such file or directory
```

**Comment by toonn** [comment]
Another possibility is opening in the closest ancestor directory that still exists.

**Comment by palikar** [comment]
@jimw567 I assume this could be closed.
