### ISSUE TITLE
Suggest to disable default Ctrl+d keyboard binding

### ISSUE THREAD

**Issue by kuznetsss** [ranger/ranger#1060]
It seems to be dangerous because Ctrl-d is a hotkey for closing terminal session.
My often ranger usecase is:
* Open ranger.
* Move to wanted directory.
* Switch to shell using S.
* Work in shell.
* Use Ctrl-d to get back to ranger.
In the last step sometimes one may delete useful files.

So I suggest to disable Ctrl-d as delete by default.

**Comment by hut** [comment]
Ctrl+d does not delete files in ranger. Perhaps it used to be like this in the past, and you're still using old configuration files? Try updating/removing your `~/.config/ranger/rc.conf`

**Comment by kuznetsss** [comment]
Thanks for your answer.
Yes, you right. I am sorry for my inattention.
