### ISSUE TITLE
Files not opening unless program is specified

### ISSUE THREAD

**Issue by lrr68** [ranger/ranger#1064]
#### Runtime Environment

- Operating system and version: Arch linux x86_64
- Terminal emulator and version:  Urxvt 
- Python version: 3.6.4
- Ranger version/commit: stable 1.9.0
- Locale: en-us.UTF-8

#### Current Behavior
Whenver i press the key 'l' which would simply open the file i had selected the screen flashes and returns to ranger. When i quit the program the following message is on screen:
/bin/sh: --: command not found

i found that this happens only when a file should open within the terminal. Pdf files for example open just fine but files i edit in the terminal do not open unless i use the open-with command
#### Expected Behavior
The 'l' key should open the file
#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```

```

**Comment by toonn** [comment]
Did you customize `rifle.conf`? What are the values of `VISUAL` and `EDITOR` in your shell?
When you say "should open within the terminal," do you mean it should be executed like a script?

**Comment by lrr68** [comment]
I did not customize rifle.conf, i just updated my system.
My VISUAL is set to "vim"
My EDITOR is set to "vim"
When i say should open within the terminal i mean it should open with vim
or some other terminal application. Not some application that opens outside
of terminal like firefox or mupdf.
Em 8 de fev de 2018 08:03, "Toon Nolten" <notifications@github.com>
escreveu:

Did you customize rifle.conf? What are the values of VISUAL and EDITOR in
your shell?
When you say "should open within the terminal," do you mean it should be
executed like a script?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ranger/ranger/issues/1064#issuecomment-364062259>, or mute
the thread

**Comment by toonn** [comment]
Could you remove your `rifle.conf`? You may have old configs hanging around from before the update. `rc.conf` and `commands.py` as well for good measure if you haven't customized them. If you have customized your configuration you can test with `ranger --clean` that'll make ranger ignore your config for a single run.

**Comment by lrr68** [comment]
Removing rifle.conf worked instantly. Thank you very much. Sorry to bother
with such simple problem but i am new here and could not find a solution

2018-02-09 8:02 GMT-02:00 Toon Nolten <notifications@github.com>:

**Comment by toonn** [comment]
No problem, glad to help. For slightly faster support on simple questions you can always visit `#ranger` on `chat.freenode.net`.
