### ISSUE TITLE
failed to preview any files

### ISSUE THREAD

**Issue by roife** [ranger/ranger#1072]
#### Runtime Environment

- Operating system and version: macOS 10.13.3
- Terminal emulator and version: macOS built-in terminal
- Python version: 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
- Ranger version/commit: ranger-stable 1.9.0
- Locale: None.None

#### Current Behavior
It can't preview any file though I have typed commands below
`ranger --copy-config=all  `

Here's screenshot
<img width="1508" alt="screen shot 2018-02-14 at 00 10 29" src="https://user-images.githubusercontent.com/17700217/36160265-aea2f098-111b-11e8-8507-ac864106d6c0.png">

**Comment by hollandan** [comment]
I'm having a similar issue.

Runtime Environment

Operating system and version: macOS 10.12.6
Terminal emulator and version: iTerm 3.1.5.beta.2
ranger version: ranger-stable 1.9.0
Python version: 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
Locale: None.None

No previews work if this line is in rc.conf:

set use_preview_script true

One thing I notice is that when I select an image, this error shows ini red in the lower left hand corner of the screen:

must be string, not None

If I set this in rc.conf:

set use_preview_script false

Then, I can at least see previews of text files.

**Comment by roife** [comment]
@hollandan 
After I set `set use_preview_script false` in `rc.config` I can preview texts as well.

**Comment by toonn** [comment]
Check that all the settings are right. `set use_preview_script true` enables previews in general. `set preview_script` needs a path pointing to the included `scope.sh` or a custom preview script. `set preview_images true` specifically enables image previews. `set preview_images_method w3m` lets you choose the preview method, w3m is the most generally applicable but (probably) less reliable than the other methods.

**Comment by roife** [comment]
@toonn I have had get all settings right, but it just didn't work. After setting `set use_preview_script false` in `rc.config`,it works for text files. By the way, I tested it on OS X 10.11.6, and it didn't work as well.

**Comment by toonn** [comment]
@roife could you try whether `ranger --clean` works? Set all the settings I mentioned from inside that ranger, for example: `:set use_preview_script true`.

**Comment by roife** [comment]
@toonn I have tried `ranger --clean` and settings you mentioned, but it didn't work. However, when I `use set use_preview_script false` instead of `use set use_preview_script true`, it did work for text files.

**Comment by roife** [comment]
@toonn I found it quite strange that after I commented on the third line `set -o noclobber -o noglob -o nounset -o pipefail` in `scope.sh`, it worked for codes with syntax highlighting.

**Comment by hollandan** [comment]
Can confirm, I also get syntax highlighting if I comment out that line.

I ran ranger --debug; is the following useful?


$ ranger --debug
ranger version: ranger-stable 1.9.0
Python version: 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
Locale: None.None
Current file: '/Users/dan/Pictures/2f7f1570f1b47bb5e49580da1927a5fd.jpg'

Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.9.0/libexec/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/local/Cellar/ranger/1.9.0/libexec/ranger/core/fm.py", line 394, in loop
    ui.draw_images()
  File "/usr/local/Cellar/ranger/1.9.0/libexec/ranger/gui/ui.py", line 402, in draw_images
    self.browser.columns[-1].draw_image()
  File "/usr/local/Cellar/ranger/1.9.0/libexec/ranger/gui/widgets/pager.py", line 115, in draw_image
    self.fm.notify(ex, bad=True)
  File "/usr/local/Cellar/ranger/1.9.0/libexec/ranger/core/actions.py", line 165, in notify
    raise obj
TypeError: must be string, not None

**Comment by DarkAce65** [comment]
I've been having this issue on a Mac (macOS v10.12.5) as well. My Linux machine displays text previews just fine.

I did some digging and found that `scope.sh` broke first on the `FILE_EXTENSION_LOWER="${FILE_EXTENSION,,}"` because I have bash v3.2 which doesn't support lowercasing via the double comma.

Once I fixed that, it started breaking on the call to `highlight` [here](https://github.com/ranger/ranger/blob/324e5af2e7ec0a825305dc6a03c95efa3682869a/ranger/data/scope.sh#L144). Installed highlight and was able to see file previews again.

**Comment by toonn** [comment]
@DarkAce65 fascinating, that double-comma's been in there for a year. `highlight` shouldn't be required. I don't have it installed and it's not a problem. Silly question maybe but MacOS didn't downgrade bash or anything, did it?

**Comment by DarkAce65** [comment]
Yeah, it seems strange that the double-comma hasn't been reported for that long. Also, I'm still not quite sure why `highlight` causes `scope.sh` to break. I don't have it installed on my Linux machine either. I can look into it a bit more in a couple hours.

With regard to the bash version, everything I've read online says that Apple ships bash 3.x with all versions of MacOS for licensing reasons.

**Comment by toonn** [comment]
I assume ranger catches and ignores those errors. Everything in `scope.sh` should probably be guarded for existence though. I don't expect it to but does dropping the `--force` flag change anything?

**Comment by DarkAce65** [comment]
Ah looking at it again, I think `scope.sh` is built in such a way that it takes advantage of `&&`. So it fully expects to throw `highlight: command not found` and then doesn't execute the `exit 5` after the `&&`. So it falls through and hits the `exit 2` which is expected for plain text output.

**Comment by DarkAce65** [comment]
I would assume you're not supposed to run `scope.sh` on its own, so you would likely never see its output. Though I'm curious as to why it didn't work initially.

**Comment by toonn** [comment]
Ah, yes. Good point. No one says you shouldn't run it on its own. Not sure why the magic doesn't hold up when run standalone though.

**Comment by DarkAce65** [comment]
Side note: I believe commenting out that line with `pipefail` allowed execution to continue when `FILE_EXTENSION_LOWER` couldn't be set via the double-commas which was why you saw previews then.

@roife @hollandan Do you guys mind posting your `bash --version`?
If you're not running bash 4.x, could you also try replacing `FILE_EXTENSION_LOWER="${$FILE_EXTENSION,,}"` with `FILE_EXTENSION_LOWER=$(echo "$FILE_EXTENSION" | tr '[:upper:]' '[:lower:]')` and see if that works?

**Comment by hollandan** [comment]
I'm running:
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)

I'm doing this, which works, and is essentially what you suggested.

FILE_EXTENSION_LOWER="$(echo ${FILE_EXTENSION} | tr '[A-Z]' '[a-z]')"

**Comment by roife** [comment]
`GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)`
It works after replacing.

**Comment by hollandan** [comment]
Sorry, I wasn't clear in my previous message.

This has fixed text previews. I still cannot see image previews.

I still get this error when an image is selected in Ranger:

must be string, not None

**Comment by toonn** [comment]
@hollandan could you open a new issue on this and refer to it in a new comment from here? This issue was non-specific about the type of previews, image previews are a special case.

**Comment by hollandan** [comment]
FYI, 

Adding this to my .bashrc fixed the problem:

`export TERM=xterm-256color`
