### ISSUE TITLE
Is there a way to toggle a file's "hidden" (dotfile/non-dotfile) state?

### ISSUE THREAD

**Issue by krompus** [ranger/ranger#1081]
This is hard to describe; I'm not referring to showing and hiding dotfiles, like what `zh` does; I mean, is there a way to toggle whether the selected files have a `.` (dot) in front of them?

The quickest way I've found is to `I` and then either type `.` `<CR>` to convert the file to a dotfile, or `I` `<Del>` <CR> to convert a dotfile to a file. Works well, and it's not too much work, but it might be nice to just have a way to toggle it. Also, this doesn't work for a selection of multiple files.

Kind of like how https://github.com/tpope/vim-commentary works; `gcc` to toggle whether a line or selection is commented or not (if it turns out it's possible, I might just use that same mapping, although it's kind of at odds with ranger's default `g` functionality).

**Comment by toonn** [comment]
Don't think it's possible in ranger per se. Also sounds like a pretty rare use-case so I'm not sure we'd include it in ranger. You could easily write a bash script that does this and bind that or write some python and bind `eval your_python_code`. Wouldn't be hard to have it work on all selected files. I'll leave this open to see if this is something many people want though.

**Comment by ReneFroger** [comment]
This is something I would like!

**Comment by krompus** [comment]
> dotify

lol, great name!

**Comment by toonn** [comment]
@krompus, @ReneFroger, if we add this script to the wiki, can we close this issue?

**Comment by toonn** [comment]
[On the wiki now.](https://github.com/ranger/ranger/wiki/Keybindings#toggle-visibility-of-files)
