### ISSUE TITLE
Ranger crashes when selecting a rdp file

### ISSUE THREAD

**Issue by UnicodeAlt255** [ranger/ranger#1082]
#### Runtime Environment

- Operating system and version: Arch Linux x86-64, updated as of 2/17/2018
- Terminal emulator and version: konsole 17.12.2 and termite v13
- Python version: 3.6.4
- Ranger version/commit: af0ef6a233744121307fba3b11089f05e9369782
- Locale: en_US.UTF-8

#### Current Behavior
Selecting a file named `Default.rdp` causes ranger to crash.

#### Expected Behavior
Ranger should not crash.

#### Context

I was simply browsing my Documents folder and  it happened to have a file called `Default.rdp`. When my selection reached that file `Default.rdp`, ranger crashed and gave me a message to report the traceback.

#### Possible Solutions
When I open up `Default.rdp` in emacs or kate, it appears normal. However, `cat` shows that there are two strange characters in the beginning of the file, which may be causing the crash.

#### Steps to reproduce
1. run ranger
2. select `Default.rdp`

#### Traceback

```
ranger version: ranger-stable 1.9.0
Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
Locale: en_US.UTF-8
Current file: '/home/daniel/Documents/Default.rdp'

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/usr/lib/python3.6/site-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

```
#### Output  of `cat Default.rdp`:
```
��screen mode id:i:2
use multimon:i:0
desktopwidth:i:1920
desktopheight:i:1080
session bpp:i:32
winposstr:s:0,1,1920,0,2720,600
compression:i:1
keyboardhook:i:2
audiocapturemode:i:0
videoplaybackmode:i:1
connection type:i:7
networkautodetect:i:1
bandwidthautodetect:i:1
displayconnectionbar:i:1
enableworkspacereconnect:i:0
disable wallpaper:i:0
allow font smoothing:i:0
allow desktop composition:i:0
disable full window drag:i:1
disable menu anims:i:1
disable themes:i:0
disable cursor setting:i:0
bitmapcachepersistenable:i:1
full address:s:192.168.1.16
audiomode:i:0
redirectprinters:i:1
redirectcomports:i:0
redirectsmartcards:i:1
redirectclipboard:i:1
redirectposdevices:i:0
autoreconnection enabled:i:1
authentication level:i:2
prompt for credentials:i:0
negotiate security layer:i:1
remoteapplicationmode:i:0
alternate shell:s:
shell working directory:s:
gatewayhostname:s:
gatewayusagemethod:i:4
gatewaycredentialssource:i:4
gatewayprofileusagemethod:i:0
promptcredentialonce:i:0
gatewaybrokeringtype:i:0
use redirection server name:i:0
rdgiskdcproxy:i:0
kdcproxyname:s:
```

Here is the file in a zip:
[Default.rdp.zip](https://github.com/ranger/ranger/files/1734363/Default.rdp.zip)

**Comment by toonn** [comment]
Thank you for reporting this and providing a file to test with. It sounds similar to #1045. Could you try the "solution" there?

**Comment by UnicodeAlt255** [comment]
I deleted `scope.sh`, but that didn't change anything. I then did `ranger --copy-config=scope`, but that didn't fix the issue either. I continue to experience the same crash and traceback whenever my selection goes over to `Default.rdp`.

**Comment by freakin-c** [comment]
I have the same issue as described here and the suggested solutions of #1045 didn't work:
I didn't have a scope.sh at all; copying the default one didn't help.

The report of @UnicodeAlt255 exactly describes the behaviour I experience, the context and the strange `cat`ted symbols (maybe different ones). Also the traceback itself match up exactly.

**Crash Report**

ranger version: ranger-stable 1.9.0
Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
Locale: de_DE.UTF-8
Current file: '/home/in/googlecontacts.csv'

*traceback skipped (duplicate)*

**`uname --kernel-name --kernel-release --kernel-version --machine --operating-system`**

Linux 4.15.3-1-ARCH #1 SMP PREEMPT Mon Feb 12 23:01:17 UTC 2018 x86_64 GNU/Linux

The attaced file is a shortend and obscured version of the original, prducing the same issue.

** `cat a-test.csv`**

ÿþName,Given Name,Additional Name,Family Name,Yomi Name,Given Name Yomi,Additional Name Yomi,Family Name Yomi,Name Prefix,Name Suffix,Initials,Nickname,Short Name,Maiden Name,Birthday,Gender,Location,Billing Information,Directory Server,Mileage,Occupation,Hobby,Sensitivity,Priority,Subject,Notes,Group Membership,E-mail 1 - Type,E-mail 1 - Value,Phone 1 - Type,Phone 1 - Value,Phone 2 - Type,Phone 2 - Value,Address 1 - Type,Address 1 - Formatted,Address 1 - Street,Address 1 - City,Address 1 - PO Box,Address 1 - Region,Address 1 - Postal Code,Address 1 - Country,Address 1 - Extended Address,Organization 1 - Type,Organization 1 - Name,Organization 1 - Yomi Name,Organization 1 - Title,Organization 1 - Department,Organization 1 - Symbol,Organization 1 - Location,Organization 1 - Job Description
?,?,,,,,,,,,,,,,,,,,,,,,,,,,* My Contacts,,,Mobile,+123456789,,,,,,,,,,,,,,,,,,,
,,,,,,,,,,,,,,,,,,,,,,,,,,,* ,'fullname@domain.de',,,,,,,,,,,,,,,,,,,,,
Full Name,Full,,Name,,,,,,,,,,,,,,,,,,,,,,,,* ,fullname@domain.de,,,,,,,,,,,,,,,,,,,,,

** `cat a-test.csv | less `**
piping the above output into pager less produces:

```
<FF><FE>N^@a^@m^@e^@,^@G^@i^@v^@e^@n^@ ^@N^@a^@m^@e^@,^@A^@d^@d^@i^@t^@i^@o^@n^@a^@l^@ ^@N^@a^@m^@e^@,^@F^@a^@m^@i^@l^@y^@ ^@N^@a^@m^@e^@,^@Y^@o^@m^@i^@ ^@N^@a^@m^@e^@,^@G^@i^@v^@e^@n^@ ^@N^@a^@m^@e^@ ^@Y^@o^@m^@i^@,^@A^@d^@d^@i^@t^@i^@o^@n^@a^@l^@ ^@N^@a^@m^@e^@ ^@Y^@o^@m^@i^@,^@F^@a^@m^@i^@l^@y^@ ^@N^@a^@m^@e^@ ^@Y^@o^@m^@i^@,^@N^@a^@m^@e^@ ^@P^@r^@e^@f^@i^@x^@,^@N^@a^@m^@e^@ ^@S^@u^@f^@f^@i^@x^@,^@I^@n^@i^@t^@i^@a^@l^@s^@,^@N^@i^@c^@k^@n^@a^@m^@e^@,^@S^@h^@o^@r^@t^@ ^@N^@a^@m^@e^@,^@M^@a^@i^@d^@e^@n^@ ^@N^@a^@m^@e^@,^@B^@i^@r^@t^@h^@d^@a^@y^@,^@G^@e^@n^@d^@e^@r^@,^@L^@o^@c^@a^@t^@i^@o^@n^@,^@B^@i^@l^@l^@i^@n^@g^@ ^@I^@n^@f^@o^@r^@m^@a^@t^@i^@o^@n^@,^@D^@i^@r^@e^@c^@t^@o^@r^@y^@ ^@S^@e^@r^@v^@e^@r^@,^@M^@i^@l^@e^@a^@g^@e^@,^@O^@c^@c^@u^@p^@a^@t^@i^@o^@n^@,^@H^@o^@b^@b^@y^@,^@S^@e^@n^@s^@i^@t^@i^@v^@i^@t^@y^@,^@P^@r^@i^@o^@r^@i^@t^@y^@,^@S^@u^@b^@j^@e^@c^@t^@,^@N^@o^@t^@e^@s^@,^@G^@r^@o^@u^@p^@ ^@M^@e^@m^@b^@e^@r^@s^@h^@i^@p^@,^@E^@-^@m^@a^@i^@l^@ ^@1^@ ^@-^@ ^@T^@y^@p^@e^@,^@E^@-^@m^@a^@i^@l^@ ^@1^@ ^@-^@ ^@V^@a^@l^@u^@e^@,^@P^@h^@o^@n^@e^@ ^@1^@ ^@-^@ ^@T^@y^@p^@e^@,^@P^@h^@o^@n^@e^@ ^@1^@ ^@-^@ ^@V^@a^@l^@u^@e^@,^@P^@h^@o^@n^@e^@ ^@2^@ ^@-^@ ^@T^@y^@p^@e^@,^@P^@h^@o^@n^@e^@ ^@2^@ ^@-^@ ^@V^@a^@l^@u^@e^@,^@A^@d^@d^@r^@e^@s^@s^@ ^@1^@ ^@-^@ ^@T^@y^@p^@e^@,^@A^@d^@d^@r^@e^@s^@s^@ ^@1^@ ^@-^@ ^@F^@o^@r^@m^@a^@t^@t^@e^@d^@,^@A^@d^@d^@r^@e^@s^@s^@ ^@1^@ ^@-^@ ^@S^@t^@r^@e^@e^@t^@,^@A^@d^@d^@r^@e^@s^@s^@ ^@1^@ ^@-^@ ^@C^@i^@t^@y^@,^@A^@d^@d^@r^@e^@s^@s^@ ^@1^@ ^@-^@ ^@P^@O^@ ^@B^@o^@x^@,^@A^@d^@d^@r^@e^@s^@s^@ ^@1^@ ^@-^@ ^@R^@e^@g^@i^@o^@n^@,^@A^@d^@d^@r^@e^@s^@s^@ ^@1^@ ^@-^@ ^@P^@o^@s^@t^@a^@l^@ ^@C^@o^@d^@e^@,^@A^@d^@d^@r^@e^@s^@s^@ ^@1^@ ^@-^@ ^@C^@o^@u^@n^@t^@r^@y^@,^@A^@d^@d^@r^@e^@s^@s^@ ^@1^@ ^@-^@ ^@E^@x^@t^@e^@n^@d^@e^@d^@ ^@A^@d^@d^@r^@e^@s^@s^@,^@O^@r^@g^@a^@n^@i^@z^@a^@t^@i^@o^@n^@ ^@1^@ ^@-^@ ^@T^@y^@p^@e^@,^@O^@r^@g^@a^@n^@i^@z^@a^@t^@i^@o^@n^@ ^@1^@ ^@-^@ ^@N^@a^@m^@e^@,^@O^@r^@g^@a^@n^@i^@z^@a^@t^@i^@o^@n^@ ^@1^@ ^@-^@ ^@Y^@o^@m^@i^@ ^@N^@a^@m^@e^@,^@O^@r^@g^@a^@n^@i^@z^@a^@t^@i^@o^@n^@ ^@1^@ ^@-^@ ^@T^@i^@t^@l^@e^@,^@O^@r^@g^@a^@n^@i^@z^@a^@t^@i^@o^@n^@ ^@1^@ ^@-^@ ^@D^@e^@p^@a^@r^@t^@m^@e^@n^@t^@,^@O^@r^@g^@a^@n^@i^@z^@a^@t^@i^@o^@n^@ ^@1^@ ^@-^@ ^@S^@y^@m^@b^@o^@l^@,^@O^@r^@g^@a^@n^@i^@z^@a^@t^@i^@o^@n^@ ^@1^@ ^@-^@ ^@L^@o^@c^@a^@t^@i^@o^@n^@,^@O^@r^@g^@a^@n^@i^@z^@a^@t^@i^@o^@n^@ ^@1^@ ^@-^@ ^@J^@o^@b^@ ^@D^@e^@s^@c^@r^@i^@p^@t^@i^@o^@n^@^M^@
^@?^@,^@?^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@*^@ ^@M^@y^@ ^@C^@o^@n^@t^@a^@c^@t^@s^@,^@,^@,^@M^@o^@b^@i^@l^@e^@,^@+^@1^@2^@3^@4^@5^@6^@7^@8^@9^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@^M^@
^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@*^@ ^@,^@'^@f^@u^@l^@l^@n^@a^@m^@e^@@^@d^@o^@m^@a^@i^@n^@.^@d^@e^@'^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@^M^@
^@F^@u^@l^@l^@ ^@N^@a^@m^@e^@,^@F^@u^@l^@l^@,^@,^@N^@a^@m^@e^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@*^@ ^@,^@f^@u^@l^@l^@n^@a^@m^@e^@@^@d^@o^@m^@a^@i^@n^@.^@d^@e^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@,^@^M^@
^@
```

[googlecontacts.csv.tar.gz](https://github.com/ranger/ranger/files/1736318/googlecontacts.csv.tar.gz)

Given this output I guess the file is just broken. But anyways thank you for taking this into account!

**Comment by Wormstalker** [comment]
Looks like I have(had) a similar problem, Ranger crashed when it tried to preview a .jpg or a .odt file, it there were no issues previewing a .py file for example. Now i deleted the scope.sh, good thing is ranger doesnt crash anymore, bad thing is that it doesnt show previews of the files anymore. 
 

Terminal is URXVT, OS is Manjaro I3, 4.14.19-1.

`ranger version: ranger-stable 1.9.0
Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
Locale: de_DE.UTF-8
Current file: '/home/michel/Bilder/Camera Roll/Handy/DSC_0001.JPG'

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File `"/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py",` line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/usr/lib/python3.6/site-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character`

**Comment by toonn** [comment]
@Wormstalker if a new `scope.sh` helped then your issue is unrelated to the current one. It's strange that it's still necessary though, maybe you still have `set preview_script ~/.config/ranger/scope.sh` in your `rc.conf`?

**Comment by Wormstalker** [comment]
You were right,  `set preview_script ~/.config/ranger/scope.sh` was set in the rc.conf. So I commented it out, deleted the scope.sh again, and the previews still working as expected. 
So thanks for the quick help.
