### ISSUE TITLE
<c-h> show hidden file doesn't work in ranger in konsole and xterm 

### ISSUE THREAD

**Issue by kyawthusoe3142** [ranger/ranger#1083]
#### Runtime Environment

- Operating system and version: Arch Linux latest as of now
- Terminal emulator and version: konsole 17.2.2 and xterm
- Python version: Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
- Ranger version/commit: ranger version: ranger-stable 1.9.0
- Locale: Locale: en_US.UTF-8

#### Current Behavior
https://bugs.kde.org/show_bug.cgi?id=390666
I reported it to KDE thinking it's the problem. I asked for advice concerning this bug in KDE irc.
I type cat in konsole and press c-h, it worked and show ^H.
I type stty -a in konsole and there's ^H nowhere.
I open emacs in konsole with -nw option. I can use c-h fine.
I tried it in tty2. ranger is fine in there. c-h works in tty2
I type echo $TERM in konsole and tty2.
In konsole, it's xterm-256color. In tty2, it's just linux.
It relieved me that there's no problem in KDE.
#### Expected Behavior
https://bugs.kde.org/show_bug.cgi?id=390666
#### Steps to reproduce
1. open ranger in xterm or konsole,
2. type c-h which is to show hidden file
3. doesn't show hidden file, zh work, other combination of ctrl works in ranger

#### Traceback

```

```

**Comment by yinflying** [comment]
Just replace the map` <c-h>` with `<bs>` in `~/.config/ranger/rc.conf` .
The reason you should ref the issue:
[https://github.com/ranger/ranger/issues/559](https://github.com/ranger/ranger/issues/559)

**Comment by toonn** [comment]
Note that this only works if `<c-h>` emits `^H` for you. For me it emits `^?` whether I'm in or out of tmux.
