### ISSUE TITLE
ranger does not show previews for text files

### ISSUE THREAD

**Issue by alco** [ranger/ranger#1084]
#### Runtime Environment

- Operating system and version: `macOS Sierra 10.12.6`
- Terminal emulator and version: `Terminal 2.7.3`, `Alacritty 0.1.0 (git commit d0fb4c5) [release build using rustc 1.22.1 (05e2e1c41 2017-11-22)])`
- ranger version: `ranger-stable 1.9.0`
- Python version: `2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]`
- Locale: `None.None`

#### Current Behavior

Preview is not shown for any text file, neither in the 3-rd pane, nor in full screen preview (after pressing `i`):

<img width="1440" alt="screen shot 2018-02-18 at 1 59 52 pm" src="https://user-images.githubusercontent.com/207748/36351574-d89c7d0a-14b4-11e8-8332-478b6e041333.png">
<img width="1440" alt="screen shot 2018-02-18 at 1 59 58 pm" src="https://user-images.githubusercontent.com/207748/36351575-d8cc7bae-14b4-11e8-8b3c-f4b5cb9567d2.png">

As can be seen from the first screenshot, the files are not empty, moreover, they contain text data.

#### Expected Behavior

Previews for text files should be visible.

#### Context

Previews worked fine until a few days ago. I didn't upgrade ranger before it stopped working. I may have removed some installed packages in Homebrew and added ranger's `history` file to my `.gitignore`. I may have accidentally removed some file in ranger's config directory.

Reinstalling ranger doesn't solve the issue.

**Comment by StabbarN** [comment]
Have you read #1072 ?

**Comment by toonn** [comment]
That was caused by a new ranger and an old `scope.sh`. If there was no update recently it would be strange for it to stop working, although maybe you checked out an old version from your git repo.

**Comment by alco** [comment]
I must have run `brew update` which updated `ranger`. So this is a duplicate of https://github.com/ranger/ranger/issues/1072.

Thanks.
