### ISSUE TITLE
slow browsing high latency filesystems

### ISSUE THREAD

**Issue by Lompik** [ranger/ranger#1087]
#### Runtime Environment

- Operating system and version: linux
- Python version: 3.6
- Ranger version/commit: v1.9.0 and a57cf76b
- Locale: UTF-8

#### Current Behavior
Browsing high-latency (>200ms) filesystem is quite slow.
#### Expected Behavior
Smoother browing experience
#### Possible Solutions
It turns out the ```statvfs``` system call is performed for every ```draw``` in order to get the free space. But it can be very slow.

```
#   ranger total run time: 4.153 seconds
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       14    3.171    0.226    3.171    0.226 {built-in method posix.statvfs}
```
The per-call corresponds exactly to the latency of the network (this is a NFS share).

Is there an option to disable the display of free space?

**Comment by toonn** [comment]
Try the following:
- tag the remote directories, for example with @ but can be most any character: "@
- :setintag @ automatically_count_files=false (This will help but may not be dramatic.)
- :setintag @ autoupdate_cumulative_size=false (This is normally the default.)
- :setintag @ display_size_in_main_column=false (Not sure this and the next one will actually avoid calculating the value.)
- :setintag @ display_size_in_status_bar=false

I'm not sure it's possible to avoid the slowdown. There are plans of maybe revamping the remote filesystem handling but that probably won't be for any time soon.

**Comment by Lompik** [comment]
``` display_size_in_main_column``` and ``` display_size_in_status_bar``` applies to current (selected) file size where ```statvfs``` is not called. However it will be called to get the free disk space displayed on the right of the status bar..

**Comment by toonn** [comment]
Ah yes, you're right. Thanks for the PR.
