### ISSUE TITLE
Sort files by modified date; directories by name and located at the top

### ISSUE THREAD

**Issue by vfreefly** [ranger/ranger#1100]
It is possible to sort files in ranger by modified date, but don't sort directories at the same time?
There is option `oc` but it sorting both files and directories:
```
c           chain set sort=ctime;     set sort_reverse=False
```
I want directories to be at the top, sorted alphabetically (default) and then below, files sorted by modified date.

**Comment by toonn** [comment]
I don't think that's currently possible. You could implement your own sorting method of course.

**Comment by vfreefly** [comment]
Thanks for answer!
