### ISSUE TITLE
Typing pL generates a symlink with longer relative path

### ISSUE THREAD

**Issue by ramboman** [ranger/ranger#1105]
#### Runtime Environment

- Operating system and version: Arch Linux (4.15.7-1-hardened)
- Terminal emulator and version: xterm (331)
- Python version: 3.6.4
- Ranger version/commit: [4c9b214](https://github.com/ranger/ranger/commit/4c9b2143d39d09fd286ec79419b00852b5d181ff)
- Locale: en_US.UTF-8

#### Current Behavior

Ranger uses a longer than expected path in symbolic links created by typing `pL` when somewhere in the path there is a symbolic link. Here is an example:

This is an example of directory structure:
```
/tmp
    aaaa_dir
        c_dir
            c_dir
                c_dir
                    a_dir
                        a.txt
                    b_dir
    bbbb_dir -> aaaa_dir
```

Here are the steps to reproduce the problem:
```
$ ranger
:cd /tmp/aaaa_dir/c_dir/c_dir/c_dir/a_dir
# type yy (yank a.txt)
:cd ../b_dir
# type pL
# a.txt -> ../a_dir/a.txt
# This is the correct path in the symlink

# Lets delete the symlink in "b_dir" and redo the process with "bbbb_dir"
:delete a.txt
:cd /tmp/bbbb_dir/c_dir/c_dir/c_dir/a_dir
# Now there is "bbbb_dir" as a symlink along the path
# type yy (yank a.txt)
:cd ../b_dir
# type pL
# a.txt -> ../../../../../bbbb_dir/c_dir/c_dir/c_dir/a_dir/a.txt
# This is a too long relative symlink
```

#### Expected Behavior

```
$ ranger
:cd /tmp/aaaa_dir/c_dir/c_dir/c_dir/a_dir
# type yy (yank a.txt)
:cd ../b_dir
# type pL
# a.txt -> ../a_dir/a.txt
# This is the correct path in the symlink

# Lets delete the symlink in "b_dir" and redo the process with "bbbb_dir"
:delete a.txt
:cd /tmp/bbbb_dir/c_dir/c_dir/c_dir/a_dir
# Now there is "bbbb_dir" as a symlink along the path
# type yy (yank a.txt)
:cd ../b_dir
# type pL
# a.txt -> ../a_dir/a.txt
# Isn't this the expected relative path in the symlink?
```

#### Context

I often use symlinks to create shortcuts to projects borrowed deep in a directory tree to somewhere closer to `$HOME`. With symlinks along the paths used to create the `pL` symlink, this problem arises. The `pL` symlink relative path can become very long.

#### Steps to reproduce

See `Current Behavior`

#### Traceback

```

```

#### Note

This issues seems to be related to this one ([#465](https://github.com/ranger/ranger/issues/465)), but i am not sure, because I don't remember to have experienced this behavior before I updated ranger to 1.9.1. Maybe the problem existed a little bit before 1.9.1.

**Comment by Vifon** [comment]
Thanks a lot for a detailed report! Reproduced and fixed!
