### ISSUE TITLE
Image Preview with urxvt turns background transparent.

### ISSUE THREAD

**Issue by mafrazz** [ranger/ranger#1106]
#### Runtime Environment

- Operating system and version: 4.9.86-1-MANJARO
- Terminal emulator and version: urxvt (rxvt-unicode-pixbuf) v9.22
- Python version: 3.6.4
- Ranger version/commit: ranger-master 1.9.1
- Locale: en_US.UTF-8

#### Current Behavior
Screenshot: https://i.imgur.com/cokB90k.jpg

Not sure if transparent background is intentional.
I tried the option `urxvt-full` and the transparency seems apropried.

#### Steps to reproduce
.Xresources https://gist.github.com/mafrazz/668d9457a2ad3ff6ad513fdf1e24f385
rc.conf https://gist.github.com/mafrazz/376e4d8acd74551b86ac8550b01ca14c
compton.conf https://gist.github.com/mafrazz/0f1f1cd0533d060d3fd3d618efe7a401

**Comment by toonn** [comment]
Do you have transparency enabled? I don't think it's supported with the urxvt image preview method.

**Comment by mafrazz** [comment]
I removed compton and now it's working fine.

Instead of transparency there is a black background, ignoring the terminal's color. But I think it's inevitable, right?

**Comment by toonn** [comment]
Not sure, @Vifon probably knows.

**Comment by akrejczinger** [comment]
I have the same issue on xubuntu14. I don't have compton installed.

**Comment by toonn** [comment]
Do you have transparency enabled on your terminal?

**Comment by akrejczinger** [comment]
> Do you have transparency enabled on your terminal?

No, I have a plain black background usually. When the preview is shown it becomes completely transparent.
I am using tmux by the way, and I noticed that when I have ranger in a split window at the bottom, the picture preview shows in the top right of the whole window, not the split that ranger is running in.
I'm on a different machine now but I will make a screenshot next week.

**Comment by toonn** [comment]
@Vifon, pinging because you're the urxvt image preview expert.

**Comment by akrejczinger** [comment]
# Screenshots

Normal background when a text file is selected:
![scrot2](https://user-images.githubusercontent.com/5542456/37901626-1e88aace-30f2-11e8-8835-aca3de5fc406.png)

Background becomes transparent when viewing an image preview:
![scrot](https://user-images.githubusercontent.com/5542456/37901624-1e6a1d84-30f2-11e8-8a94-cd0ac73f8c7c.png)

The image is in the wrong place when viewing from a tmux split:
![scrot3](https://user-images.githubusercontent.com/5542456/37901627-1ea2a906-30f2-11e8-8e61-1e07741406df.png)

I guess the last problem can be quite hard to fix, but I would like to at least have the background as black.

**Comment by akrejczinger** [comment]
@toonn The positioning is fine when outside tmux, and this is something I can live with.

I'm not on the same machine right now. On my current machine I don't have a compositing manager installed so the background cannot become transparent. The background changes to a slightly darker shade instead. This happens regardless of running in tmux or not, and I think the transparency change happened on the other machine outside of tmux as well.

**Comment by akrejczinger** [comment]
I managed to fix the issue on my machine by setting this line in ~/.Xresources:

```
URxvt.depth: 24
```

This option was set to 32 previously.

**Comment by Streetwalrus** [comment]
I consider this to be a bug in urxvt. The following patch fixes it:
```diff
--- src/rxvtimg.C
+++ src/rxvtimg.C
@@ -770,9 +770,15 @@
 
   if (repeat == RepeatNone)
     {
-      XRenderColor rc = { 0, 0, 0, 0 };
+      rgba bg = GET_R->pix_colors[Color_bg];
+      XRenderColor rc = {
+        (unsigned short)(bg.r * bg.a / 65535),
+        (unsigned short)(bg.g * bg.a / 65535),
+        (unsigned short)(bg.b * bg.a / 65535),
+        GET_R->depth == 32 ? bg.a : 65535
+      };
       XRenderFillRectangle (cc.dpy, PictOpSrc, cc.dst, &rc, 0, 0, w, h);//TODO: split into four fillrectangles
-      XRenderComposite (cc.dpy, PictOpSrc, cc.src, None, cc.dst, 0, 0, 0, 0, x, y, ref->w, ref->h);
+      XRenderComposite (cc.dpy, PictOpOver, cc.src, None, cc.dst, 0, 0, 0, 0, x, y, ref->w, ref->h);
     }
   else
     XRenderComposite (cc.dpy, PictOpSrc, cc.src, None, cc.dst, -x, -y, 0, 0, 0, 0, w, h);
```

If anyone cares: GPLv3+ (like urxvt itself).

**Comment by 1337hax0r** [comment]
@Streetwalrus I'm a bit of a brainlet. How do I apply this patch?

**Comment by Streetwalrus** [comment]
Save it as (for example) `background.patch` at the root of the urxvt source, apply with `patch -Np0 -i background.patch`, then recompile urxvt as normal.

**Comment by ChrispyChris** [comment]
I'm not sure if this was finally worked out or not. I'm using compton as well and viewing images in URxvt. When I preview an image, it changes the brightness of the whole screen (that's how I can best put it) and the preview is out of the borders and transparent. Is there a way to fix this yet?

**Comment by Streetwalrus** [comment]
Yes, compile urxvt with the patch I posted above.

**Comment by Vifon** [comment]
Seems to be resolved, so I'm closing. If it's not the case, please reopen.
