### ISSUE TITLE
Rifle flag t only works with urxvt

### ISSUE THREAD

**Issue by toonn** [ranger/ranger#1108]
Rifle's `flag t` only works with urxvt (because who cares about standards?).
Urxvt passes any arguments after `-e` verbatim, most other terminals consume them as arguments.
Some terminals use `-e`, others use `-x`.

**Comment by toonn** [comment]
Summary
-------

<dl>
  <dt>`-c`</dt>
    <dd>tilda</dd>
  <dt>`-e`</dt>
    <dd>cool-retro-term, gnome-terminal, lilyterm, lxterminal, mate-terminal, pantheon-terminal, st, terminator, terminology, termite, urxvt, xfce4-terminal, xterm</dd>
  <dt>`-x`</dt>
    <dd>gnome-terminal, lilyterm, mate-terminal, terminator, xfce4-terminal</dd>
  <dt>`--command`</dt>
    <dd>lxterminal, mate-terminal, terminator, tilda</dd>
  <dt>`--command=`</dt>
    <dd>gnome-terminal, lxterminal, xfce4-terminal</dd>
  <dt>`--exec`</dt>
    <dd>terminology</dd>
  <dt>`--exec=`</dt>
    <dd>termite</dd>
  <dt>`--execute`</dt>
    <dd>gnome-terminal, lilyterm, mate-terminal, terminator, xfce4-terminal</dd>
  <dt>`--execute=`</dt>
    <dd>pantheon-terminal</dd>
  <dt>other</dt>
    <dd>Mac os is even worse in this regard: [Terminal.app](https://stackoverflow.com/a/28373404), [iterm2](https://gist.github.com/vyder/96891b93f515cb4ac559e9132e1c9086), kitty.app(?).</dd>
</dl>

References
----------

For alacritty: **?**

For cool-retro-term:
> `-e <cmd>`
> Command to execute. This option will catch all following arguments, so use it as the last option.

For gnome-terminal:
> `-e, --command=STRING`
> Execute the argument to this option inside the terminal. 
> `-x, --execute`
> Execute the remainder of the command line inside the terminal.

For guake: No option.

For kitty/kitty.app: **?**

For konsole:
> `-e command`
> Execute command instead of the normal shell.

For lilyterm:
> `-e COMMAND | -x COMMAND | --execute COMMAND`
> Run a command when starting up. Must be the final option.

For lxterminal:
> `-e STRING --command=STRING --command STRING`
> This option specifies the program (and its command line arguments) to be run in the terminal. Except in the --command= form, this must be the last option on the command line.

For mate-terminal:
> `-e, --command`
> Execute the argument to this option inside the terminal
> `-x, --execute`
> Execute the remainder of the command line inside the terminal

For pantheon-terminal:
> `-e, --execute=PATH`
> Execute the specified binary in terminal 

For st/stterm:
> `-e program [ arguments ... ]`
> executes program instead of the shell. If this is used it must be the last option on the command line, as in xterm / rxvt. This option is only intended for compability, and all the remaining arguments are used as a command even without it. 

For terminator:
> `-e, --command`  
> Runs the specified command instead of your default shell or profile specified command", `-x, --execute` "Runs the rest of the command line instead of your default shell or profile specified command.

For terminology:
> `-e, --exec <cmnd>`
> Specify command to execute. Defaults to $SHELL (or passwd shell or /bin/sh) When used along with -S/--split, each argument is used as a command for a split, leaving away the extra arguments. With 3 splits, one vertical, a command on the right, an horizontal split on the left with only a command on the bottom, the following arguments should be used: --split v-h-- -e command1 $SHELL command2

For termite:
> `-e, --exec=COMMAND`
> Tell termite start COMMAND instead of the shell.

For tilda:
> `-c, --command`
> Run a command at startup

For urxvt:
>  `-e command [arguments]`  
> Run the command with its command-line arguments in the urxvt window; also sets the window title and icon name to be the basename of the program being executed if neither -title (-T) nor -n are given on the command line. If this option is used, it must be the last on the command-line. If there is no -e option then the default is to run the program specified by the SHELL environment variable or, failing that, sh(1).
>
> Please note that you must specify a program with arguments. If you want to run shell commands, you have to specify the shell, like this:
>
> urxvt -e sh -c "shell commands"

For xfce4-terminal:
> `−x, −−execute`
> Execute the remainder of the command line inside the terminal
> `−e, −−command=command`
> Execute command inside the terminal

For xterm:
> `-e program [ arguments ... ]`
> This option specifies the program (and its command line arguments) to be run in the xterm window. It also sets the window title and icon name to be the basename of the program being executed if neither -T nor -n are given on the command line. This must be the last option on the command line.

**Comment by fictionic** [comment]
The problem still persists for Termite. The command needs to be all one string, as your Summary indicates. It's being passed as an array.

**Comment by toonn** [comment]
You're right. I didn't actually take it into account in the code and probably did it wrong in `rifle.conf` too. I could've sworn I tested this with termite though.

**Comment by fictionic** [comment]
Anyone have any updates on this? It's super frustrating

**Comment by toonn** [comment]
Not really. I still want to fix this before the next release but it may slip another tbh.
