### ISSUE TITLE
%t macro not working in ranger commands

### ISSUE THREAD

**Issue by marcelmindemann** [ranger/ranger#1114]
#### Runtime Environment

ranger version: ranger-master 1.9.1
Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
Locale: en_US.UTF-8

#### Current Behavior

I tag multiple files in a directory by pressing "t". Then I want to copy these tagged files into the clipboard. I tried the command `:yank %t` and `:copy %t` which both don't copy the tagged files. `:copy` tells me "bad arguments for copy" and `:yank` just gives me the name of the first tagged file in red font, but without an error message. `:bulkrename %t` doesn't rename all the tagged files either. I could not find a command that accepts the %t macro. The only thing that works is `:shell mv %t new_directory`.

#### Expected Behavior
The %t macro should work in all ranger commands.

#### Context
I am trying to tag images that I like without selecting them so that I can move them to a special directory at the end.

**Comment by toonn** [comment]
The help indicates that neither of those commands take the arguments you want them to, `:copy` takes `mode=set|add|remove` and `:yank` takes `name|dir|path` where `|` means either or. I think all macros only work with `:shell`.

I think the closest you can currently get is marking all the tagged files and then `:copy`. I'm not implementing the macros all over the place is a good idea but we do have plans to make tags more useful soon™ (months, not weeks).

**Comment by 0x72** [comment]
Thank you toonn! Seems like I misunderstood the documentation for `:copy` and `:yank`. Do you know a quick way to select all tagged files? Unfortunately, `:select %t` does not work either and manually selecting all tagged files becomes a hassle and is prone to human error for big photo collections.

**Comment by toonn** [comment]
Depending on how you tagged it, with default tag `*`: `:mark_tag`, with other tag for example `t`: `:mark_tag t`.
