### ISSUE TITLE
unmark_tag not working

### ISSUE THREAD

**Issue by 0x72** [ranger/ranger#1115]
#### Runtime Environment
ranger version: ranger-master 1.9.1
Python version: 3.6.4 (default, Jan 5 2018, 02:35:40) [GCC 7.2.1 20171224]
Locale: en_US.UTF-8

#### Current Behavior
I tag multiple files. I then use the command `:unmark_tag`. Nothing happens.

#### Expected Behavior
According to documentation, this command should untag all tagged files:

> :unmark_tag [<tags>]
> Unmark all tags that are tagged with either of the given tags.
> When leaving out the tag argument, all tagged files are unmarked.

**Comment by toonn** [comment]
Seems like this was never implemented. Can't believe you're the first to notice in 5 years.

**Comment by toonn** [comment]
I was actually too quick to judge, still don't understand the magic behind the implementation. The purpose of the commands is not to "tag" files, it's to "mark" or "unmark" "tagged" files.
`:mark_tag []` will mark files tagged with the default tage `*` or whatever tag you specified, `:unmark_tag []` ditto except unmark.
