### ISSUE TITLE
scope.sh problem previewing archives containing many items

### ISSUE THREAD

**Issue by jdietrch** [ranger/ranger#112]
I am running ranger 1.6.0, and have placed the latest scope.sh in ~/.config/ranger/

But I am having a problem previewing certain archive files. Most of them preview just fine, showing a list of the contained files. Some however, show a completely empty preview. For example, this happens with evince-common_3.4.0-3.1_all.deb (which can be retrieved from http://ftp.us.debian.org/debian/pool/main/e/evince/evince-common_3.4.0-3.1_all.deb). It doesn't seem to be a problem with als, because als runs fine on that file when I do it manually on the commandline.

I think this problem might have to do with the number of contained items and thus the length of the output of als.
evince-common_3.4.0-3.1_all.deb is 5M, but it contains over 2700 items.
als evince-common_3.4.0-3.1_all.deb | wc -l
2782

Another file that doesn't preview is gnome-accessibility-themes_3.4.2-2.1_all.deb (which can be retrieved from http://ftp.us.debian.org/debian/pool/main/g/gnome-themes-standard/gnome-accessibility-themes_3.4.2-2.1_all.deb). It is only 1.7M, but contains over 2300 items:
als gnome-accessibility-themes_3.4.2-2.1_all.deb | wc -l
2301

And the problem doesn't seem related to file size. Because a larger deb -- fonts-arphic-ukai_0.2.20080216.2-3_all.deb (which can be retrieved from http://ftp.us.debian.org/debian/pool/main/f/fonts-arphic-ukai/fonts-arphic-ukai_0.2.20080216.2-3_all.deb) -- is 9.8M, but it contains only 49 items and previews just fine.
als fonts-arphic-ukai_0.2.20080216.2-3_all.deb | wc -l
49

Is there something else I should I be doing to get this to work?

If any other information would be helpful, please don't hesitate to ask.

Thank you.

James Dietrich

**Comment by duerrp** [comment]
I ran into a similar issue today, with scope unable to display large source files. I am not very experienced with shell scripting, but I think it's related to scope's `try` and `dump` functions that try to store the output of the archive preview, highlighting etc. in a local variable (of potentially limited size). 

On systems where we can write to /tmp (which is all I personally care about), one can write the results to a temporary file instead. Try to replace `try` / `dump` with the following in your scope.sh:
```
try() { tmp_file=$(mktemp XXXX --tmpdir=/tmp) && $(eval '"$@"' > $tmp_file); }
dump() { /bin/cat $tmp_file && /bin/rm $tmp_file; }
```
and increase the value of `maxln` accordingly.

This is just a quick hack, but if @hut is interested, I can submit a pull request (without abusing `cat` and additional checks if /tmp is writable), but I think there should be a better way (and maybe my intuition about the variable size is wrong - a quick google didn't yield any revealing answers).

**Comment by nfnty** [comment]
Can't reproduce this issue. Request to reopen if you're still experiencing this issue on `master` or the latest release.

**Comment by jdietrch** [comment]
Yes, please reopen this issue.

I just tried again with `master` and the problem still persists for me. I have attached a zip file containing a webm video which is a screencast demonstrating the problem. Notice that `als` runs fine on both .deb files, but one of them shows no preview in ranger.

Is there something I'm not doing right? Or is there any other information I can supply that would be helpful?

[screencast.zip](https://github.com/ranger/ranger/files/730977/screencast.zip)

**Comment by nfnty** [comment]
Test this `scope.sh`: https://gist.githubusercontent.com/nfnty/b8d70c9ab4724ca17df9f429d16f25d7/raw/3526520fe64d6a239add7d0faced1b36f0494ad4/scope.sh

**Comment by jdietrch** [comment]
I removed ~/.config/ranger and used the copy-config=all option. Running ranger with this produces results as seen in the screencast I posted yesterday. After replacing scope.sh with the one referenced above, ranger crashes when previewing evince-common_3.4.0-3.1_all.deb. Full command-line log below:

```
jdietrch@saturn:~/Downloads/m/m/ranger [master]
$ rm -r /home/jdietrch/.config/ranger/
jdietrch@saturn:~/Downloads/m/m/ranger [master]
$ python ranger.py --copy-config=all
creating: /home/jdietrch/.config/ranger/rifle.conf
creating: /home/jdietrch/.config/ranger/commands.py
creating: /home/jdietrch/.config/ranger/commands_full.py
creating: /home/jdietrch/.config/ranger/rc.conf
creating: /home/jdietrch/.config/ranger/scope.sh

> Please note that configuration files may change as ranger evolves.
  It's completely up to you to keep them up to date.

> To stop ranger from loading both the default and your custom rc.conf,
  please set the environment variable RANGER_LOAD_DEFAULT_RC to FALSE.
jdietrch@saturn:~/Downloads/m/m/ranger [master]
$ touch /home/jdietrch/.config/ranger/history
jdietrch@saturn:~/Downloads/m/m/ranger [master]
$ python ranger.py 
jdietrch@saturn:~/Downloads/m/m/ranger [master]
$ cd ~/.config/ranger
jdietrch@saturn:~/.config/ranger
$ rm scope.sh
jdietrch@saturn:~/.config/ranger
$ wget https://gist.githubusercontent.com/nfnty/b8d70c9ab4724ca17df9f429d16f25d7/raw/3526520fe64d6a239add7d0faced1b36f0494ad4/scope.sh
--2017-01-26 08:01:47--  https://gist.githubusercontent.com/nfnty/b8d70c9ab4724ca17df9f429d16f25d7/raw/3526520fe64d6a239add7d0faced1b36f0494ad4/scope.sh
Resolving gist.githubusercontent.com (gist.githubusercontent.com)... 151.101.56.133
Connecting to gist.githubusercontent.com (gist.githubusercontent.com)|151.101.56.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2843 (2.8K) [text/plain]
Saving to: ‘scope.sh’

scope.sh                                    100%[===========================================================================================>]   2.78K  --.-KB/s   in 0s     

2017-01-26 08:01:47 (54.7 MB/s) - ‘scope.sh’ saved [2843/2843]

jdietrch@saturn:~/.config/ranger
$ chmod +x scope.sh
jdietrch@saturn:~/.config/ranger
$ cd -
/home/jdietrch/Downloads/m/m/ranger
jdietrch@saturn:~/Downloads/m/m/ranger [master]
$ python ranger.py 
ranger version: 1.8.1, executed with python 2.7.9
Locale: en_US.UTF-8
Current file: /home/jdietrch/Downloads/m/m/a/evince-common_3.4.0-3.1_all.deb
Traceback (most recent call last):
  File "/home/jdietrch/Downloads/m/m/ranger/ranger/core/main.py", line 166, in main
    fm.loop()
  File "/home/jdietrch/Downloads/m/m/ranger/ranger/core/fm.py", line 360, in loop
    loader.work()
  File "/home/jdietrch/Downloads/m/m/ranger/ranger/core/loader.py", line 410, in work
    next(item.load_generator)
  File "/home/jdietrch/Downloads/m/m/ranger/ranger/core/loader.py", line 170, in generate
    self.process = process = Popen(self.args, **popenargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
jdietrch@saturn:~/Downloads/m/m/ranger [master]
$ 
```

**Comment by nfnty** [comment]
Yeah, you need to change the shebang to something like `#!/bin/bash` depending on where your `bash` binary is located.

**Comment by jdietrch** [comment]
Oops... I didn't think of that. Sorry about that.

The good news is that ranger previews both of those files just fine with that `scope.sh`.

**Comment by nfnty** [comment]
Good to hear, I'll refactor the default `scope.sh`.

**Comment by nfnty** [comment]
@jdietrch Please, test the new refactored `scope.sh`.

**Comment by jdietrch** [comment]
Just tried it, and both of those files preview just fine. Thank you!
