### ISSUE TITLE
Debug information being displayed by default

### ISSUE THREAD

**Issue by vijaygopal1234** [ranger/ranger#1138]
#### Runtime Environment

ranger version: ranger-master 1.9.1

Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]

Locale: en_US.UTF-8

OS: Arch Linux, latest update at the time of post

#### Current Behavior

Displays debug messages while using ranger.

#### Expected Behavior

No text to stdout / stderr.

#### Context

I don't really remember when this bug started happening. I cannot reproduce on my Manjaro machine. **I have a feeling like it might be a problem with my computer, but I'm not sure how I would start on debugging it.**

#### Steps to reproduce
1. Opening ranger
2. Quitting ranger

Then there's a lot of debug information on the screen.

```
INFO:ranger.core.main:ranger version: ranger-master 1.9.1
INFO:ranger.core.main:Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
INFO:ranger.core.main:Locale: en_US.UTF-8
INFO:ranger.core.main:Process ID: 14033
DEBUG:ranger.core.main:cache dir: '/home/vijaymarupudi/.cache/ranger'
DEBUG:ranger.core.main:config dir: '/home/vijaymarupudi/.config/ranger'
DEBUG:ranger.core.main:data dir: '/home/vijaymarupudi/.local/share/ranger'
DEBUG:ranger.core.main:Unable to access plugin directory: /home/vijaymarupudi/.config/ranger/plugins
DEBUG:ranger.core.actions:Sourcing config file '/usr/lib/python3.6/site-packages/ranger/config/rc.conf'
DEBUG:ranger.core.actions:Sourcing config file '/home/vijaymarupudi/.config/ranger/rc.conf'
```

**Comment by toonn** [comment]
Silly question first. You're not launching ranger with the `--debug` flag, right?
Does the same thing happen when you run `ranger --clean`?

**Comment by vijaygopal1234** [comment]
```
> /usr/bin/ranger --clean
INFO:ranger.core.main:ranger version: ranger-master 1.9.1
INFO:ranger.core.main:Python version: 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
INFO:ranger.core.main:Locale: en_US.UTF-8
INFO:ranger.core.main:Process ID: 5648
DEBUG:ranger.core.main:cache dir: '/home/vijaymarupudi/.cache/ranger'
DEBUG:ranger.core.main:config dir: '/home/vijaymarupudi/.config/ranger'
DEBUG:ranger.core.main:data dir: '/home/vijaymarupudi/.local/share/ranger'
DEBUG:ranger.core.actions:Sourcing config file '/usr/lib/python3.6/site-packages/ranger/config/rc.conf'
```

It still happens with `ranger --clean`. I quit ranger after it launched to display the debug text of course.

And I am not launching it with `--debug`, yep :). I'm not very experienced with this stuff so it's entirely possible that it's a silly reason!

**Comment by vijaygopal1234** [comment]
It was some other pip package which was interfering with my python's logging module. Removing everything and then reinstalling the things I needed fixed the issue.

**Comment by gpasqualetti** [comment]
I had the same problem, and I solved uninstalling `vext`

**Comment by vortexnix** [comment]
Having the same issue. How do I identify which python package is enabling the debug logging ?
Thanks.
