### ISSUE TITLE
How to disable special bookmark behaviour?

### ISSUE THREAD

**Issue by Mr-SD** [ranger/ranger#1147]
Whenever I jump to a bookmark, the special bookmark at key ' is set to the last directory in and the `~/.config/ranger/bookmarks` file gets updated to reflect that. As a result of that, every time I use bookmarks in ranger git detects a new change made to my dotfiles even if I haven't modified any of my actual bookmarks. Is there a way to disable this special bookmark behaviour?

**Comment by toonn** [comment]
No way to disable it no. You could change it in the code. Or just git checkout so you get the version of the file git expects.

**Comment by toonn** [comment]
Was too quick, something did pop into my mind. `set save_backtick_bookmark False` in your rc.conf will prevent ranger from saving the `'` bookmark I think because it's just a synonym.

**Comment by Mr-SD** [comment]
Yep, that did the trick altho I had to add that line manually, it wasn't included in my config file for some reason.
