### ISSUE TITLE
about tabs

### ISSUE THREAD

**Issue by hektr** [ranger/ranger#1155]
Tabs named by numbers: 1, 2, 3, etc... If you have 3-4 tabs, you don't know, what is what))) It's not informative. May be, it's possible to add to their number also their directory name? For example, if tab 1 is /home/Downloads then its name will be "1Downloads". It will be more informative. It's not necessary to get whole folder name, you can get only first 5-6 letters... 1Downl~ all the same would be more clear than just 1.

**Comment by toonn** [comment]
Psst, you didn't hear this from me but #1143 allows you to have named tabs : o
That part might not be merged but you can still run the code from the PR if you really want to.

**Comment by vijay609** [comment]
I have been using the following setting to get around this
`
set dirname_in_tabs true
`

**Comment by toonn** [comment]
:+1: @vijay609, didn't even remember that setting.
