### ISSUE TITLE
ValueError: embedded null character

### ISSUE THREAD

**Issue by iasj** [ranger/ranger#1159]
#### Runtime Environment

- Operating system and version: Arch Linux (Rolling  released system)
- Terminal emulator and version:  termite ( version: v13)
- Python version: Python 3.6.4
- Ranger version/commit: ranger-stable 1.9.0
- Locale: en_US.UTF-8

Whenever I have a long list of files (in this case pdfs and epubs) ranger crushes saying `ValueError: embedded null character`, but not all the time, occuring only when I'm pressing `j` to go down.

![ranger](https://user-images.githubusercontent.com/7888397/39417465-be813958-4c2a-11e8-8d71-3ad4cc1d7052.png)

**Comment by iasj** [comment]
Sorry guys, I think I just found the problem. 

I hadn't noticed until now that this problem was happening always in the same folder and is about the same file. 

The file is named as `lista.txt`, but in truth it is a binary file, not a plain text file. I know it is binary by opening it with VIM, that shows all those funny caracters of a binary file.

**Comment by iasj** [comment]
Damn it!

I no longer have the broken file. I'm really sorry for this. I was using ranger to organize my files, so I got rid of nonessential ones.

Sorry about that!

**Comment by toonn** [comment]
@puustina, :+1: Thanks for the confirmation.
