### ISSUE TITLE
Unable to map Alt+SpecialChar

### ISSUE THREAD

**Issue by Ram-Z** [ranger/ranger#116]
I have the following mappings in my rc:

```
map <a-!>     tab_open 1
map <a-@>     tab_open 2
map <a-#>     tab_open 3
map <a-$>     tab_open 4
map <a-%>     tab_open 5
map <a-^>     tab_open 6
map <a-&>     tab_open 7
map <a-*>     tab_open 8
map <a-(>     tab_open 9
```

Unfortunately none of them work.

Note that my keyboard has the number row inverted, ie I have to press shift to get the numbers, else I get the special chars. Pressing Alt+Shift+!, Alt+Shift+@, etc, does switch tabs to 1, 2, etc.

I also tried mapping <a-=>, <a->, etc with no results.

Ranger: ranger-master 1.6.1 (git HEAD at the time of writing)
Urxvt: rxvt-unicode (urxvt) v9.19 - released: 2013-10-27

**Comment by nfnty** [comment]
Continue discussion in #266.
