### ISSUE TITLE
Jump to first file in directory (i.e. skip subdirectories)

### ISSUE THREAD

**Issue by vicmortelmans** [ranger/ranger#1160]
When entering a directory with lots of subdirectories, it would be useful to have a keybinding to jump to the first file in the directory. I find myself scrolling down passed the list of subdirectories quite often, to reach the file list.

Most probably there's already a (combination of) command(s) to do this, that may be bound to a key, but I didn't figure it out yet...

Regards,
Vic

:thumbsup: !!

**Comment by toonn** [comment]
No keybinding for this yet, `<pagedown>, <c-f> and <c-d>` move in bigger steps but there's no specific move to next file.

**Comment by rdrr** [comment]
Perhaps this was added because of the isssue, but there is a command and a keybinding: jump_non which is, in the default rc.conf, bound to ")".

**Comment by toonn** [comment]
@rdrr, hey thanks, didn't notice that command.
@vicmortelmans, does this sufficiently solve your problem? Maybe with the `-w` flag added?

**Comment by vicmortelmans** [comment]
That's exactly what I was looking for! 

Sublime work!!

Regards,
Vic
