### ISSUE TITLE
Installation does not work in macOS High Sierra (10.13.4)

### ISSUE THREAD

**Issue by MBRG** [ranger/ranger#1161]
#### Runtime Environment

- Operating system and version: macOS High Sierre (10.13.4)
- Terminal emulator and version: iterm2; Build 3.1.6
ranger version: ranger-master 1.9.1
Python version: 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
Locale: None.None

#### Current Behavior
I cloned the master branch via git clone and tried to install it using `sudo make install` as well as `sudo python setup.py install --optimize=1 --record=install_log.txt`

In both instances I run into the error
`error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/share': Operation not permitted`

See [install-issues.txt](https://github.com/ranger/ranger/files/1974473/install-issues.txt) for more details.

From what I could find this is due to Apple's "System Integrity Protection" introduced in OS X El Capitan. 

Strangely enough, ranger still will start normally when I now enter the ranger command in my home directory.

#### Steps to reproduce
1. Should be outlined in my description above.

**Comment by toonn** [comment]
I'm not sure what we could do about this. I assume only apple store signed binaries are allowed? Ranger will probably never be an app so that's impossible. How does homebrew get around this?

**Comment by MBRG** [comment]
I'm going to test that

**Comment by MBRG** [comment]
I'm going to test that

**Comment by MBRG** [comment]
Just wanted to update that. I installed again using Homebrew and so far everything seems fine. So I'd say this issue can be closed now.

**Comment by toonn** [comment]
👍 Thanks for reporting back. Good to know.

**Comment by vit1251** [comment]
Update: you should use sudo when pwerform setup install operation. But actually it totally does not provide any sucess story. I install it from trunc from version 1.9.2 and have similar problem:

```
$ ranger
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/ranger", line 35, in <module>
    import ranger  # NOQA pylint: disable=import-self,wrong-import-position
ModuleNotFoundError: No module named 'ranger'
```

It look like maintainer does not use it already or use oldest version precompile version of solution.

**Comment by toonn** [comment]
@vit1251, the original issue reporter was already using sudo for the install commands.

I have no idea what you're trying to say here, "It look like maintainer does not use it already or use oldest version precompile version of solution."
Could you try rephrasing/clarifying this?

**Comment by vit1251** [comment]
@toonn I try to say that look like use source code from __cache__ or using old version *.pyc files. New installation totally does not start properly as you can see on my report below.

**Comment by toonn** [comment]
@vit1251, I suspect the first python on your path is not the right python. Do you have multiple python's installed?

**Comment by vit1251** [comment]
@toonn as you can see by path to library it non standart macOS python (version 2.7). It fresh version install Python 3.7 (on path /Library/Frameworks/Python.framework/Versions/3.7/bin/python3). But actually I always use ```sudo``` and ```python3 setup.py install``` command. And if error is exist this on inside Python.
