### ISSUE TITLE
can't preview MKV format video

### ISSUE THREAD

**Issue by yadex** [ranger/ranger#1163]
after update my Arch Linux,ranger  can't preview MKV format video,but other format such as mp4 flv works well

**Comment by yadex** [comment]
1.9.1,i've updated ranger to 1.9.1 a month ago.

**Comment by yadex** [comment]
change the mkv to mp4 use ffmpeg  or use ffmpegthumbnailer command line can get a preview image

**Comment by toonn** [comment]
Did you maybe remove your `scope.sh`? The video section is commented by default so maybe all you need to do is uncomment those 4 lines.

**Comment by yadex** [comment]
no, i 've been using  ranger   almost a year,naver happened before.

**Comment by toonn** [comment]
And check whether `file --mimetype some.mkv` returns `video/*`.

**Comment by yadex** [comment]
i get an error message: Preview script " doesn't exist.

**Comment by yadex** [comment]
sure, it seem's miss preview script.i try it in my new ArchLinux in virtualbox,there is no error message.

**Comment by toonn** [comment]
Sounds like you don't have a *custom* `scope.sh`. The video preview is disabled by default.
```shell
> ranger --copy-config=scope
> ${VISUAL:-EDITOR} ~/.config/scope.sh  # Uncomment lines 112 through 115
```
You need previews and image previews enabled in your `rc.conf` of course.

**Comment by yadex** [comment]
no no no, i mean it seems lost :set preview_script command

**Comment by toonn** [comment]
Oh, yes. We default to the included `scope.sh` in the new `rc.conf` so you'll have to edit `rc.conf` to customize the `preview_script`.

**Comment by ncoop** [comment]
It's the mime type.

On my Arch system, `file -i` is returning `application/octet-stream` for most of my mkvs. Seems to also affect webms. I believe this started when I updated file 5.32-1 -> 5.33-1. FWIW the bug tracker for file (bugs.gw.com) is down at the moment.

Workaround is to add a case to the `handle_extension` function. This is more efficient than shelling out to file anyways.

**Comment by toonn** [comment]
Thanks @ncoop, ranger itself should be unaffected since it relies on the `mimetypes` python module rather than `file(1)`, `scope.sh` always shells out.

Here's the case you'd want to add to `handle_extension` for convenience:
```bash
        # Video
        mkv|webm)
            # Thumbnail
            ffmpegthumbnailer -i "${FILE_PATH}" -o "${IMAGE_CACHE_PATH}" -s 0 && exit 6
            exit 1;;
```

**Comment by ncoop** [comment]
Thanks @toonn

Another approach for users who don't trust file extensions is to append `--keep-going` and possibly `--raw` to the invocation of  `file` in scope.sh. Then `handle_image` can check if any of the hits are relevant. In these cases, `video/x-matroska` should show up as the second guess.
