### ISSUE TITLE
problems with previewing highlighted cyrillic text

### ISSUE THREAD

**Issue by banderlog** [ranger/ranger#1166]
#### Runtime Environment

- Operating system and version: 4.9.76-gentoo x86_64
- Terminal emulator and version: xterm-331
- Python version: 3.6.3 (default, Mar 28 2018, 14:50:40) [GCC 6.4.0]
- Ranger version/commit: ranger-master 1.9.1
- Locale:  en_US.UTF-8

#### Current Behavior

Both highlighters -- pygmentyzer and highlight, are showing rubbish instead of Cyrillic utf8 text sometimes.

If run them from console, i.e. `highlight -t 4 --out-format=xterm256 --style=pablo --force -- 1.md` all is ok. 
If look on text in rangers preview -- it looks like bad encoding, which sometimes resolves if put or remove extra symbol (e.g., ".") before Cyrillic text.

#### Expected Behavior

Show all utf8 characters correctly, if they are in current console font.

#### Steps to reproduce

look on  files in attached archive in rangers preview
[bug.tar.gz](https://github.com/ranger/ranger/files/1988449/bug.tar.gz)

**Comment by toonn** [comment]
It's strange that just adding a character works. Could the files' encoding be faulty? Otoh if it works on the command line but not in ranger it's probably an ncurses issue.

**Comment by banderlog** [comment]
`cat 1.md | enca -L ru` will output `Universal transformation format 8 bits; UTF-8`

If you run `cat 1.md | iconv -t utf8 > foo.md` and look on it in ranger, it will be the same.

PS: yes, it is not gzipped, mea culpa.

**Comment by banderlog** [comment]
I tried this on ncurses-6.0-r1 and ncurses-6.1-r2, results are the same.

**Comment by hektr** [comment]
everything works good on my debian linux ^_^ May be you have some system misconfiguration

**Comment by banderlog** [comment]
>everything works good on my debian linux ^_^ May be you have some system/locale misconfiguration. Try to enter cyrillic symbols in Xterm to ensure that cyrillic symbols works on your terminal.

As I wrote above, `highlight -t 4 --out-format=xterm256 --style=pablo --force -- 1.md ` produces nice output in the same `x11-terms/xterm-311` terminal with all symbols on places.

**Comment by banderlog** [comment]
The same story for urxvt and other fonts

**Comment by dkiyatkin** [comment]
I reproduce problems with previewing highlighted cyrillic text in konsole (fedora kde), but in xterm its works fine.
