### ISSUE TITLE
The first item of the third column shouldn't be highlighted

### ISSUE THREAD

**Issue by whenov** [ranger/ranger#1167]
I've recently found this tool and it works great for me, thanks for your work!

But I have a suggestion. Currently, when a directory in the second column is focused, the first item of the third column is highlighted. This behavior is unnecessary and counter-intuitive.

**Comment by toonn** [comment]
I disagree, it's really useful. It's not just the first item it's the item you had selected last time you were in the directory.

**Comment by whenov** [comment]
@toonn Could you describe a situation where this is useful?

**Comment by whenov** [comment]
@toonn I think that's the case. Maybe it's because I'm new to ranger, but when I want to move between items with `j`/`k`, I always think I'm controlling the cursor in the third column.

One has to read the manual to know that the contents of current directory is in the second column instead of the third one, and has to spend some time with ranger to get used to this behavior. Because there's no visual difference between the second and the third column.

**Comment by toonn** [comment]
Maybe more flexible borders would help? Borders around just the preview column or the other columns, or just a seperator between the rest and the preview column.

**Comment by whenov** [comment]
@toonn Maybe the second column can be highlighted with bright colors, and the other columns with dim colors?

**Comment by toonn** [comment]
Not sure whether that's already possible through theming. I don't think so but I don't know enough about themes to say for sure.
One setting that's already available that might be less confusing is `set collapse_preview false`.

**Comment by toonn** [comment]
Did you close this because you got used to it? If it's too confusing for new users we'd want to do something about it.

**Comment by whenov** [comment]
I closed it because I thought it might be my own problem since no one else mentioned it?

**Comment by kule** [comment]
Just to add another opinion:

I have no problem with the 3rd column item being highlighted specifically. I definitely found it confusing out-of-the-box having the same style of highlighting in all three columns.  `set draw_borders separators` has improved things a bit for me.

However, it'd be really nice if the 1st/3rd columns could be a differentiated better (e.g. having slightly dimmer font colors or a slightly lighter background color so the middle column is where your eyes are drawn too) - can this be done in the colorschemes already?

**Comment by toonn** [comment]
@kule, I guess you could use `context.main_column` to differentiate, yes.

**Comment by kule** [comment]
@toonn thanks for the pointer

Incase anyone was interested; I copied the default color scheme and adjusted the main_column e.g.

```python
# ~/.config/ranger/colorschemes/[yourschemename].py
# ...
def use(self, context):
  # ...
  if context.main_column:
    bg = 237
    # ...
```

The only limitation is the background color doesn't fill the entire column (it only colors the listed files) but it's a good enough fix for now to help draw my eye to the main column.

**Comment by toonn** [comment]
Fwiw, I don't think the columns have separate background colors, neither do the statusbars.

**Comment by leenapps** [comment]
This post is getting a little old but yes since the next column is not under current control it might do well to have a different rule.
It would be great to have a columnafter and columnbefore color context.

**Comment by mkpaz** [comment]
That's what always stopped me from using Ranger. Highlighting 3rd column is counter-intuitive, because it's not a part of the current path.

**Comment by dylanwright** [comment]
I also found this confusing. Highlighting the third column does serve some purpose as it indicates the last directory that was visited, not simply the first item. 

But being able to set or dim the highlight color on the 1st and 3rd columns would help give more emphasis to the 2nd active column.

The default column ratios (`set column ratios 1 3 4`) also contribute to the issue by making the 3rd column the most prominent due to it being wider. Changing mine to (1,3,1) made a big difference for me.

**Comment by unphased** [comment]
> The default column ratios (`set column ratios 1 3 4`) also contribute to the issue by making the 3rd column the most prominent due to it being wider. Changing mine to (1,3,1) made a big difference for me.

- The syntax is `set column_ratios 1,3,4`, not what you stated. 
- The use of ratios 1,3,1 is a little nonsensical for me as it squishes the hell out of previews. The clear path forward here is to keep the behavior the same, but allow the third (and preferably also the first) column highlights to be settable to a different color/style in order to emphasize that the control is always at the second (middle) column.

**Comment by dylanwright** [comment]
>     * The syntax is `set column_ratios 1,3,4`, not what you stated.

Ah Sorry, I've edited my post to show the correct syntax.

> *The use of ratios 1,3,1 is a little nonsensical for me as it squishes the hell out of previews. 

Personal preference for sure. I prefer the small preview as a tradeoff for clarity. With settable style for highlights in the first and third columns, I wouldn't find it as as necessary to reduce the 3rd col.
