### ISSUE TITLE
Vim paste from clipboard

### ISSUE THREAD

**Issue by tom-adsfund** [ranger/ranger#1168]
Vim is my default editor, and when I move into a file using the right arrow key the + register (system clipboard) is unavailable (doesn't appear in `:registers`, and `"+p` doesn't work).

Am I missing something?

I'm using ranger stable 1.8.1.

**Comment by toonn** [comment]
Does it work when outside of ranger?

**Comment by tom-adsfund** [comment]
Yes, I had isolated it before posting the issue. And I have reset my system and continue to have the same problem. The Ranger-created vim has no access to the system clipboard, normal vim does.

But typing :version in vim does reveal something strange: it is using two different versions.

Ranger's is "[version] 8.0 (exact same compile date) ... huge version without GUI... -xterm-clipboard"
Outside is "[version] 8.0 (exact same compile date) ... huge version with GTK3 GUI (even though this is run from the console (terminator))... +xterm-clipboard"

**Comment by toonn** [comment]
Hmm, did you install vim with something other than your system's package manager? Ranger just calls `vim` so it should start the first vim on the path, the shell does the same though so maybe the `PATH`s differ? Are you launching ranger from the shell or calling `urxvt -e ranger` or something?
