### ISSUE TITLE
hover colors

### ISSUE THREAD

**Issue by hektr** [ranger/ranger#1171]
I think, more contrast between hovered element foreground and background is needed. I think it's needed to set constant color for hovered element background(black is good) or for hovered element background(some light color similar to white). 

I think the first way is better(make hovered element foreground black).
Thanks ^_^

**Comment by toonn** [comment]
Not sure what you mean by hovered? Do you mean the selected file? We already invert fg/bg so for me the foreground of the selection *is* black.

**Comment by hektr** [comment]
Yes, I mean selected file ^_^ Hmm, It's grey on default colorscheme

**Comment by hektr** [comment]
By the way, is it possible to run file in new console tab?

**Comment by toonn** [comment]
I use the default theme. Maybe check your terminal's colors.

Depends on whether you can run a command in a new tab from the command line.

**Comment by hektr** [comment]
Yes, you are right! I've changed color scheme of my terminal emulator. Thanks :+1:

**Comment by toonn** [comment]
No problem, you're welcome : )
