### ISSUE TITLE
NameError: name 're' is not defined

### ISSUE THREAD

**Issue by DSMadCow** [ranger/ranger#1190]
#### Runtime Environment

- Operating system and version: ArchLinux
- Terminal emulator and version: issue is the same on xterm and urxvt
- Python version: 3.6.5-3
- Ranger version/commit: ranger- master 1.9.1-1
- Locale: None.None

#### Current Behavior
Ranger crashes when launched

#### Expected Behavior
For ranger to run

#### Traceback

```
Traceback (most recent call last);
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 120, in main
     load_settings(fm, args.clean)
  File "/home/madcow/.config/ranger/commands.py", line 348, in load_settings
      import commands as commands_custom
  File "/home/madcow/.config/ranger/commands.py", line 348, in <module>
      class setlocal(set_):
  File "/home/madcow/.config/ranger/commands.py", line 353, in setlocal
     PATH_RE = re.compile(r'^\s*path="?(.*?)"?\s*$')
NameError: name 're' is not defined
```

**Comment by Vifon** [comment]
Is your `commands.py` up to date?

**Comment by mhlkan** [comment]
Try do `pip3 install re`

**Comment by toonn** [comment]
@mhlkan, I think the name's not defined because the import's missing not necessarily because the library's not installed. The current `commands.py` imports it so that's why Vifon asked if @DSMadCow's `commands.py` is up to date. If pip installing `re` was a solution then we messed up packaging ranger somewhere.

**Comment by DSMadCow** [comment]
@mhlkan @Vifon , it may be my commands.py, I don't think I have updated that. I will check when I am at home on my system again tonight

**Comment by DSMadCow** [comment]
@Vifon @mhlkan I reloaded my commands.py and that resolved the issue. so this was an outdated config file. 

Thank you.

**Comment by toonn** [comment]
@DSMadCow, if you didn't customize `commands.py` or any of `rc.conf, rifle.conf or scope.sh` you can just remove them. They used to be required, now they're not and if you don't have them then they don't get out of sync when updating.
