### ISSUE TITLE
Navigate folders always filtering

### ISSUE THREAD

**Issue by blahsd** [ranger/ranger#1195]
#### Runtime Environment
- Operating system and version:  macOS 10.13.4
- Terminal emulator and version: iTerm2 
- Python version: 2.7.10
- Ranger version/commit:  ranger-master 1.9.1
- Locale: None.None

#### Current Behavior
Navigating folders filtering their content requires opening a folder, activating the filter by typing `zf`, typing the filter content, `enter` to kill the filter, `enter` to open the found folder, then `zf` to filter again. 

#### Desirable Behavior
Possible to activate the filter permanently so that navigating folders filtering their content would require opening a folder, typing the filter content, `enter` to open the found folder, then again typing the new filter content, etc.

**Comment by toonn** [comment]
I'm not actually completely clear on what you want. There's `f` which'll allow you to filter until there's a unique match, then acts on that match (enter a directory, open a text file in your editor, etc.).

But you could also be talking about a filter that keeps applying as you change directory? There is actually a setting that sorta does this and could be hijacked for this purpose, but it wouldn't be a pretty hack.

**Comment by Vifon** [comment]
I feel `:travel` might do what you want. Try it please and report back.

**Comment by blahsd** [comment]
OHMYGODYES! Thanks. I wasn't aware of the usage of scout, now I can actually make it do anything my heart desires. 
https://thumbs.gfycat.com/SelfishSilentBrownbear-size_restricted.gif
I wanna be your best friend.


Just one thing: it appears that if I `map tr scout -aefiklt` for instance, typing the shortcut `tr` also sends me down a level. Am I using mapping incorrectly? Or is there a way to somehow get :travel with less keypresses? Thanks again

**Comment by Vifon** [comment]
Don't worry, the link is the email notification works properly. :)

I'm closing the issue since it seems resolved.

**Comment by zxti** [comment]
scout and travel seem to only be commands that take some argument.

I'm still looking for the ability to repeatedly enter a directory and just start typing to filter down the list, hit enter to enter the selection, and then type again. Without what @blahsd mentioned - having to enter zf and an extra enter on each level.

Is this possible? I am still looking for this ability. Thank you.

**Comment by zxti** [comment]
Just spotted a more recent issue requesting the same:

https://github.com/ranger/ranger/issues/2723
