### ISSUE TITLE
Image preview doesn't work in urxvt

### ISSUE THREAD

**Issue by mvrozanti** [ranger/ranger#1196]
#### Runtime Environment
Linux Mint 
DE: cinnamon2d
ranger version: ranger-master 1.9.1
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]
Locale: en_US.UTF-8
rxvt-unicode (urxvt) v9.21 - released: 2014-12-31
options: perl,xft,styles,combining,blink,iso14755,unicode3,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,pixbuf,XIM,frills,selectionscrolling,wheel,slipwheel,smart-resize,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm
`echo $TERM` outputs `xterm-256color`
`tput colors` outputs `256`

[.Xdefaults](https://github.com/mvrozanti/mint.files/blob/master/.Xdefaults)
[rc.conf](https://github.com/mvrozanti/mint.files/blob/master/ranger/rc.conf)
[rifle.conf](https://github.com/mvrozanti/mint.files/blob/master/ranger/rifle.conf)

#### Current Behavior
Not displaying anything with `set preview_images_method urxvt` nor `set preview_images_method urxvt-full`, although it kind of works with `set preview_images_method w3m` with black stripes on top of where the image should be. I reckon this must be a problem with `w3m` itself.

#### Context
I'm trying to run `ranger` inside `tmux` inside `urxvt` with transparency enabled. I tried setting the URxvt.depth setting to anything other than 32 but I lose transparency even then it does not work. It actually worked before but I think I edited something I shouldn't and it doesn't work anymore.

I do realize there may not be a way to resize the image with `tmux` but I've seen ranger preview inside tmux with similar configurations.

**Comment by Vifon** [comment]
The transparency in `urxvt` is a known troublemaker for the image previews. Not much we can do about this. Be wary that `tmux` also makes things tricky once you start detaching and reattaching sessions as then the window IDs change.

**Comment by mvrozanti** [comment]
I'm actually willing to change terminal emulator just to make this work; ranger is, and I don't use this word often, awesome

Do you have any suggestions on what to try out @Vifon ?

**Comment by Vifon** [comment]
Not really. I phrased it wrong, the transparency in general will break most of our preview methods one way or another. @toonn Do you know if any of our new preview methods would help?

**Comment by toonn** [comment]
I don't think there's any that are a sure thing, it seems to depend on so many things. We should start a wiki page that has a table of what preview methods work with what features, transparency, tmux, etc.

**Comment by mvrozanti** [comment]
Ok actually got it working in URxvt without tmux but I'm not exactly sure how. Still no luck inside tmux

**Comment by mvrozanti** [comment]
OK I'M ON TO SOMETHING

I just left `bash` for `zsh` and found out about [oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh) and then I found [this plugin for tmux](https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins#tmux) and then I found out they have this variable `ZSH_TMUX_FIXTERM` which makes `ranger` work with `tmux` in `zsh` in `urxvt` (for my versions at least [zsh 5.1.1]).

**Comment by toonn** [comment]
What is the effect of this variable?

**Comment by mvrozanti** [comment]
Not sure, but the answer seems to be in [this file](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/tmux/tmux.plugin.zsh)

**Comment by toonn** [comment]
Hmm, could you try running tmux without zsh (otherwise the env vars may carry over), then running `TERM=screen-256color ranger`? If `ZSH_TMUX_FIXTERM` is really the solution then that should work.

**Comment by mvrozanti** [comment]
It did.

**Comment by toonn** [comment]
Wait, running the command with the env var works but configuring `TERM` in either of those doesn't? Could you check the value of `TERM` if you configure it like that?

**Comment by yedhink** [comment]
i had tearing problems when the images were previewed in urxvt. setting this in my ranger config solved the issue for me  
```
set preview_images true
set draw_borders true
```

**Comment by toonn** [comment]
@yedhink, have you tried setting this: `URxvt.depth: 24`? The `draw_borders` thing is a red herring.

**Comment by mvrozanti** [comment]
@toonn TERM somehow is set to `xterm-256color` along the way

**Comment by toonn** [comment]
@mvrozanti so to recap, w3m previews work in tmux as long as `TERM=screen-256color`?

**Comment by mvrozanti** [comment]
w3m previews kind of worked for me even on alternative TERM values, but always with stripes on the image or some kind of "clearing" effect, if that makes any sense.
