### ISSUE TITLE
Shortcut for deleting a bookmark

### ISSUE THREAD

**Issue by kmyokoyama** [ranger/ranger#1203]
Is there a way of deleting an existing bookmark? I have looked for this feature through all documentation, but I have found none.

Sorry if it is too obvious.

**Comment by Vifon** [comment]
You're looking for `um<any>`, where "<any>" is your bookmark. Hope that helps.

-- 
vifon

**Comment by kmyokoyama** [comment]
@Vifon, that's exactly what I was looking for. Thank you.

I'm closing this issue.
