### ISSUE TITLE
When using relative line number, how can I set the current line to 0?

### ISSUE THREAD

**Issue by cyanted** [ranger/ranger#1205]
When using relative line number, how can I set the current line to 0?
Instead of the absolute line number. BTW, thank you guys developed a such good software! :D

**Comment by Vifon** [comment]
I don't think it's currently possible. Why do you prefer 0 to an actually meaningful number? It should be fairly easy to add, I just want to know why beforehand.

Thanks for the kind words. :)

**Comment by Vifon** [comment]
Either way, for now you can apply this patch by yourself and it should do the trick. Cheers!

```diff
diff --git a/ranger/gui/widgets/browsercolumn.py b/ranger/gui/widgets/browsercolumn.py
index cf322409..a9c0b9d5 100644
--- a/ranger/gui/widgets/browsercolumn.py
+++ b/ranger/gui/widgets/browsercolumn.py
@@ -206,11 +206,6 @@ class BrowserColumn(Pager):  # pylint: disable=too-many-instance-attributes
         line_number = i
         if self.settings.line_numbers == 'relative':
             line_number = abs(selected_i - i)
-            if line_number == 0:
-                if self.settings.one_indexed:
-                    line_number = selected_i + 1
-                else:
-                    line_number = selected_i
         elif self.settings.one_indexed:
             line_number += 1
 ```

**Comment by cyanted** [comment]
@Vifon Thanks! Your patch works perfectly.

Maybe more is for personal preferences, 
I'm using Emacs enabling the line-number-relative,
and it gives option for users to choose how to display current-line, 
just like below, 
```emacs-lisp
(setq-default display-line-numbers-type 'relative)
(setq display-line-numbers-current-absolute nil)
```
so I feel not get used to the absolute one, :D

**Comment by toonn** [comment]
@Vifon, do we want to add a setting for this?

**Comment by Vifon** [comment]
@toonn, Possibly. Personally I think the absolute number is more informative but adding an option won't hurt if some users prefer it this way.

**Comment by toonn** [comment]
Alright, then let's keep this open.

**Comment by Vifon** [comment]
@cyanted Here we go. Use the new `relative_current_zero` option.

**Comment by cyanted** [comment]
@Vifon Got it.Thank you.
 You guys are really efficient! very good :D
