### ISSUE TITLE
Several issues found by coverity scan

### ISSUE THREAD

**Issue by valoq** [ranger/ranger#1206]
#### Runtime Environment

ranger version: v1.9.1
build with python 3.5.3

Running ranger through the static code analyse tool coverity showed a few issues

https://scan.coverity.com/projects/ranger

Since coverity requires a login to access the information about the defects I have attached the issues found as text files.

@hut
You can take over the ownership of the coverity ranger project once you login and request access

[issue1.txt](https://github.com/ranger/ranger/files/2108778/issue1.txt)
[issue2.txt](https://github.com/ranger/ranger/files/2108779/issue2.txt)
[issue3.txt](https://github.com/ranger/ranger/files/2108780/issue3.txt)

**Comment by Vifon** [comment]
Thanks a lot for the scan, @valoq! Could you re-run it? The first two should be fixed now but let's make sure. The third one was a false positive.

**Comment by valoq** [comment]
Thanks for the patches.

Ranger now has a defect density of 0.00 in coverity :)

https://scan.coverity.com/projects/ranger
