### ISSUE TITLE
Disable preview_files (zp) by default

### ISSUE THREAD

**Issue by leewdch** [ranger/ranger#1209]
#### Runtime Environment

- Operating system and version: x86_64 Linux 4.17.2-1-ARCH
- Terminal emulator and version: rxvt-unicode (urxvt) v9.22
- Python version: 3.6.5
- Ranger version/commit: ranger-master 1.9.1
- Locale: en_US.UTF-8

#### Current Behavior
`preview_files` set to `false` doesn't disable file previews when browsing files

#### Context
I want to disable file preview by default to easily browse file on my system and on my network attached devices and enable it when needed using `zp` or `zi`. I tried setting this rule in `rc.conf` but it didn't work:
```
## Disable file preview by default
set preview_files false

# Use one of the supported image preview protocols
set preview_images false
```

**Comment by toonn** [comment]
Did you restart ranger after changing `rc.conf`? I know it may be obvious but I'm just checking. Definitely works for me.

**Comment by leewdch** [comment]
Yeah I did. When I hover on a video file ranger starts loading and a mediainfo preview is generate on the right side

**Comment by Vifon** [comment]
Are all your ranger configs up to date? Did you try running ranger with
--clean and then disabling the previews? Does it work properly?

leewdch <notifications@github.com> writes:

> Yeah I did. When I hover on a video file ranger starts loading and a mediainfo preview is generate on the right side
>
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ranger/ranger/issues/1209#issuecomment-399701562

-- 
Wojciech Siewierski

**Comment by leewdch** [comment]
I found the problem. I added a set preview_files false line but I already have a set preview_files true line by default in my rc.conf. Now previews are correctly disabled
