### ISSUE TITLE
File previews show only one character per line / have newlines after each character

### ISSUE THREAD

**Issue by rolfschr** [ranger/ranger#1210]
Hi,

I run ``./ranger.py`` from the git repo directly and I get file previews that list one character per line only (see screenshot). I have not setup any config file. I have not seen this behaviour on other machines before. I can confirm this behaviour with another user on the same host. Happy to provide further insights.

#### Runtime Environment
```
echo "OS:" ; uname -a ; cat /etc/lsb-release ; echo "\nTerminal:" ; pstree -sA $$ | awk -F "---" '{ print $2 }' | tr -d '\n' ; echo "" ; echo $TERM ; echo $SHELL ; echo $ZSH_VERSION ; echo "\nPython:" ; python --version ; echo "\nRanger:" ; git --no-pager log -1 ; echo "\nLOCALE:"; echo $LC_NAME
OS:
Linux rolf-ThinkPad-T470 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"

Terminal:
mate-terminal
xterm
/bin/zsh
5.4.2

Python:
Python 2.7.15rc1

Ranger:
commit f20dd1b7c38de92796340636aea322893f497aa8 (HEAD -> master, origin/master, origin/HEAD)
Merge: c8613cf8 5eb00772
Author: Wojciech Siewierski
Date:   Mon May 28 13:27:29 2018 +0200

    Merge pull request #1092 from FichteForks/detect_file_encoding
    
    Improve file encoding detection for previews

LOCALE:
en_US.UTF-8
```

#### Current Behavior
File previews show one character per line

#### Expected Behavior
File previews should look similar to any editor opening the file (i.e. new lines only when there is a `\n` character)

#### Context
I try to preview files.

![screenshot at 2018-06-25 09-38-58](https://user-images.githubusercontent.com/1188465/41836629-9cfdaeee-785b-11e8-9b89-269992785728.png)

**Comment by Vifon** [comment]
Try to resize the terminal and see if it will persist. Maybe ranger is getting a wrong terminal size and updating it will fix it.

BTW, I allowed myself to edit out my email address from your message. Let's not make it too easy for the spambots. ;)

**Comment by uygwfd254** [comment]
i have the same problem.
however, setting ```set use_preview_script true``` to ```set use_preview_script false``` in the $HOME/.config/ranger/rc.conf will fix it.

**Comment by toonn** [comment]
Hmm, but plaintext files don't go through the script. What exact commit are you both running?

**Comment by uygwfd254** [comment]
i have the latest version, ranger 1.9.1

**Comment by rolfschr** [comment]
Hi, sorry for the email in the post. Resizing did not change anything. I am running the commit as mentioned above. Simply cloned a couple of days ago.

![ranger2](https://user-images.githubusercontent.com/1188465/41931549-b3a686ce-797e-11e8-97d5-ed832e0009c0.png)
![ranger1](https://user-images.githubusercontent.com/1188465/41931550-b3ca6f62-797e-11e8-8660-441d9cf5a3ee.png)

**Comment by uygwfd254** [comment]
this is weird, when i run ```$ ./ranger.py``` straight from the source, the issue disappear.
but when i run ```$ ranger --clean``` the issue reappear.

**Comment by uygwfd254** [comment]
i have the default value: set preview_script ~/.config/ranger/scope.sh
and
set use_preview_script true

**Comment by toonn** [comment]
@uygwfd254, that's not the default anymore. Might want to update your configs, you only need the files you actually change so you can probably ditch `scope.sh` and maybe `rifle.conf`, maybe diff your `rc.conf` with the new one. I don't understand why it changes for you yet.

@rolfschr, thank you, I can reproduce this in a python without chardet.

**Comment by toonn** [comment]
I'm at a loss as to what's going on though, looking at it it looks like the exact same code path is followed. The string also looks fine so it's just the displaying of the string that goes wrong somehow but that code didn't change in that commit : s

**Comment by b33rcity** [comment]
Having this issue, as well. Just cloned the repo a half hour ago and was rather surprised by this--previously I was running the version available in Fedora's repo. Installed chardet, no change.

**Comment by toonn** [comment]
@b33rcity, did you install `chardet` for the python that's used to run ranger?

**Comment by b33rcity** [comment]
@toonn Yes. Actually, I installed it with both versions of PIP, just to be on the safe side, but it appears Ranger is being run by Py27 (that's the one I had to install pillow to get kitty img preview working).

**Comment by toonn** [comment]
@b33rcity, hmm stranger and stranger. What version of ranger are you running and how did you install it?

**Comment by toonn** [comment]
Maybe chardet needs a locale specified, @b33rcity?

**Comment by toonn** [comment]
@b33rcity, you can find out by running: `:eval import locale; self.fm.notify(locale.getlocale())`.

**Comment by b33rcity** [comment]
Handy, didn't know you could do that. Well, it returned the correct ('en_US', 'UTF-8').

Incidentally, I previewed a pdf today. It displayed as text, rather than an image, and the text was flowed correctly. It's only plain text files that are having this issue.

**Comment by marcopaganini** [comment]
Sorry for reposting on a dead issue, but is this issue really closed? I still see the problem on csv and kml files, for instance.

**Comment by FichteFoll** [comment]
I suggest opening a new issue after you verified you are running a recent version of ranger or the master branch.
