### ISSUE TITLE
Potential issue with Ubuntu 18 LTS? Image Preview not working

### ISSUE THREAD

**Issue by omnesia0rg** [ranger/ranger#1211]
#### Runtime Environment

- Operating system and version: Ubuntu 16 vs 18.04 LTS
- Terminal emulator and version:  Tested on gnome-terminal, urxvt and st
- Python version: 2.7.15rc1
- Ranger version/commit: stable 1.8.1

#### Current Behavior
Image preview not showing on Ubuntu 18 LTS (w3m & feh installed).
config:
```
set preview_images true
set preview_images_method w3m
set open_all_images true
```

Works as expected on another machine running Ubuntu 16 with the same config

**Comment by lainiwa** [comment]
I had the same problem recently. As I found out, the newer version of ranger on ubuntu 18.04 have some breaking changes in scope.sh file. Therefore, i recommend you to do something like
```bash
mv ~/.config/ranger/scope.sh{,.bak}
ranger --copy-config=scope
```
to get it working.

**Comment by omnesia0rg** [comment]
Thank you that fixed it for me as well
