### ISSUE TITLE
Having issues installing Ranger with anaconda python3.6

### ISSUE THREAD

**Issue by JacobEFO** [ranger/ranger#1214]
#### Runtime Environment

- Operating system and version: macOS High Sierra, Version 10.13.5
- Terminal emulator and version: Terminal, Version 2.8.2 (404)
- Python version: Python 3.6.4, Anaconda custom (64-bit)
- Ranger version/commit: 1.9.1
- Locale: I have no idea about this

#### Current Behavior
Whenever I try to do 'make install' in the ranger folder, I get the following error:

https://imgur.com/a/g2XkVNp

#### Expected Behavior
I expect to install ranger using this. However running ranger with 'python2.7 ranger.py' I can succesfully run ranger. My version of python2.7 is 2.7.10 (not installed using anaconda).
This in turn does not work using python3.6 nor python3 (they give the same error as shown in the screenshot).

#### Traceback

```
/anaconda3/bin/python setup.py install '--record=install_log.txt' \
		'--root=/' --optimize=1
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    import ranger
  File "/Users/JEO/Documents/ranger/ranger/__init__.py", line 40, in <module>
    from ranger.core.main import main  # NOQA pylint: disable=wrong-import-position
  File "/Users/JEO/Documents/ranger/ranger/core/main.py", line 22, in <module>
    'Locale: {0}'.format('.'.join(str(s) for s in locale.getlocale())),
  File "/anaconda3/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/anaconda3/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
make: *** [install] Error 1
```

Best regards Jacob

SOLUTION: In Terminal Preferences -> Profiles -> Advanced -> Uncheck "Set locale environment variables on startup"

**Comment by toonn** [comment]
What's the output for `locale` on the command line?

**Comment by JacobEFO** [comment]
If I just type locale I get the following traceback:

```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by toonn** [comment]
Hmm, weird. Locales are usually something like `en_US.UTF-8` instead of just `UTF-8` even on my mac. Could you try unchecking "set locale env vars on startup" in the Terminal.app settings?

**Comment by JacobEFO** [comment]
Wow, that solved it.

I have no idea how, and what difference it makes. Do you know?

**Comment by toonn** [comment]
I think the problem is apple "knowing better," I'm not sure what the point of masking the locale variables is.

**Comment by JacobEFO** [comment]
Stupid Apple. The best part about my MacBook is the terminal, trackpad and cmd+spacebar, the rest is crap ;)

Thank you for your assistance though.

SOLUTION: In Terminal Preferences -> Profiles -> Advanced -> Uncheck "Set locale environment variables on startup"
