### ISSUE TITLE
How can I see shell messages under ranger

### ISSUE THREAD

**Issue by hektr** [ranger/ranger#1215]
For example, if I run some shell command from ranger, how can I see its log/error messages? Is there some command to see shell messages under ranger? Thanks

**Comment by Vifon** [comment]
You can run `:shell -p YOUR COMMAND`. Is that what you're looking for?

**Comment by toonn** [comment]
What I always do is `S` to get a shell, the results of previous commands are usually visible.

**Comment by hektr** [comment]
yes, thanks :+1:
