### ISSUE TITLE
Only one line when previewing text file.

### ISSUE THREAD

**Issue by miusav** [ranger/ranger#1218]
#### Runtime Environment
- Operating system and version: windows 8.1
- Terminal emulator and version: gitbash on windows
ranger version: ranger-master 1.9.1
Python version: 2.7.13 (default, Dec 19 2016, 18:07:51) [GCC 4.8.4]
Locale: None.None

#### Current Behavior
Preview text file, refer to imgulr : https://imgur.com/a/L1w1wAM
but previewing some(not most) file without ext, like this, it works : https://imgur.com/a/5CTz4Oz

#### Expected Behavior
Should simply preview text file, if not display as vim (highlight), at least display without any highlight

#### Context
Can not preview text file.

#### Possible Solutions
I go through closed issues, and seems nobody same as me..

#### Steps to reproduce
Not sure, but I simply clone git and installed. 

#### Traceback
No crash

**Comment by toonn** [comment]
This sounds like #1210 so I'm closing as a duplicate. Stop gap "solution" is to install `chardet` for the python that runs ranger.
