### ISSUE TITLE
what idea stays behind tags?

### ISSUE THREAD

**Issue by hektr** [ranger/ranger#1223]
I can't understand what is tag in ranger(just a file marked with some letter??) and why it can be useful. 
Why don't just select files by space? I just want to understand the general idea :) Thanks!!

**Comment by toonn** [comment]
You can `:mark_tag` so it's useful for files you want to mark a couple times, imagine a complicated shuffling of files back and forth between several dirs or something.

More useful is `:setintag` though. You can use it to disable previews on slow network drives for instance. Or sort specific directories in certain ways. Or display them with different linemodes.

**Comment by hektr** [comment]
thanks :+1:

**Comment by Vifon** [comment]
Additionally they are persistent (unlike marking with space) so I usually mark with them the show episodes I already watched or things like this.
