### ISSUE TITLE
How to use 'open with' to open file

### ISSUE THREAD

**Issue by itgoyo** [ranger/ranger#1230]
#### Runtime Environment

- Operating system and version: Mac OS  10.12.5
- Terminal emulator and version: 
- Python version: 2.7.10
- Ranger version/commit: 1.9.1
- Locale: 

When I use ranger to open media such as movies, there is something wrong. I run`open with vlc`, 
 but it does not work. How can I fix it?

**Comment by toonn** [comment]
It needs to be `:open_with vlc`, just for the record, maybe you figured it out already : )
