### ISSUE TITLE
Ranger used with base-16 shell on arch linux breaks colors

### ISSUE THREAD

**Issue by wirecat** [ranger/ranger#1237]
#### Runtime Environment
- Operating system and version: **Arch Linux 2018-07-22**
- Terminal emulator and version: **sakura 3.6.0**
- Python version: **3.6.6**
- Ranger version/commit: **ranger-master 1.9.1**
- Locale: **en_US.UTF-8**

#### Current Behavior
After opening a text document(or any document it seems), ranger does something that breaks console colors. The first time a document is opened in an application like vim, everything is fine. After that, the colors are all messed up. See attached screenshots.

Using ranger with base16 on Ubuntu 16.04 does not introduce this error. This gives me hope that this may be resolvable.

**Update:** I tested and with a very similar setup on Ubuntu 16.04.1, ranger-stable 1.7.1, and sakura 3.3.4. On ubuntu 16.04 it does indeed work perfectly.

![good](https://user-images.githubusercontent.com/6413154/43055697-f32347b0-8dec-11e8-97ec-d9a4cc049bc6.jpg)

![bad](https://user-images.githubusercontent.com/6413154/43055696-f30d6986-8dec-11e8-9e22-04450ad71a63.jpg)

#### Expected Behavior
Console colors are left intact and everything remains beautiful.

#### Context
This makes ranger difficult to use on my system. It drastically affects vim usability as background colors will clash with foreground after the switch.

#### Possible Solutions
Don't use Arch? :(

#### Steps to reproduce
1. Run arch linux.
2. Use base 16 https://github.com/chriskempson/base16-shell
3. Launch ranger and open a document in your favorite editor

**Comment by wirecat** [comment]
If anyone has any ideas on how to establish root cause, I'm willing to do the leg work.

**Comment by toonn** [comment]
Maybe report this to the sakura project? Even if it's not their bug they're usually more knowledgeable regarding terminal escape sequences and the like.
