### ISSUE TITLE
DON'T open files with RIGHT

### ISSUE THREAD

**Issue by chrishaig14** [ranger/ranger#1245]
How can I make the right arrow NOT open files on my rc.conf? I would like to keep everything default except I don't want to open files with the right arrow. I DO want to open directories with right arrow, and both directories and files with enter. I've looked at my rc.conf file but can't seem to find the right setting to modify...

**Comment by toonn** [comment]
I think this should do what you want, might also want to remap `l` but that's up to you:
```
map <RIGHT> eval self.fm.thistab.enter_dir(self.fm.thisfile)
```

**Comment by chrishaig14** [comment]
It works, thanks!
