### ISSUE TITLE
Should check whether ranger is already running in current terminal

### ISSUE THREAD

**Issue by axper** [ranger/ranger#125]
I have multiple terminals windows open, and it's easy to forget which ones are in ranger's shell mode (`Shift+s`) and which ones are not. 

When starting ranger, it should check whether ranger is already running in current terminal and is in shell mode. If ranager is already running/shell mode, it should exit shell mode and go back to main interface. If ranger is not running, only then it shouls start a new instance.

Right now I end up with dozens of ranger instances in each of my terminals and have to `:q` and `Ctrl+D` out all of them in order to close my terminal window.

**Comment by tbrodbeck** [comment]
would still be great to have this behaviour by default (sorry for warming this old thread up)

**Comment by Vifon** [comment]
We're unlikely to include it at least for two reasons:

1. The current behavior is more versatile.
2. It's non-trivial to gracefully exit the shell process, that is a parent of the ranger process in question (and child of the older one). For this reason it must be done in the shell itself, so it's out of scope of ranger itself.

Cheers!

**Comment by toonn** [comment]
@Vifon, how do you feel about having ranger warn about the ranger level if it's greater than 0? That wouldn't be hard and might help with this?

**Comment by Vifon** [comment]
@toonn, that could work and would be fairly easy to implement. If that would be a simple boolean option in `rc.conf`, maybe even enabling this warning by default would be the right thing to do (see: https://www.gnu.org/software/emacs/manual/html_node/elisp/Disabling-Commands.html).

**Comment by toonn** [comment]
@Vifon, not sure why you linked to "disabled commands" but I agree this should be on by default. It's the new users that'll run into the problem.

**Comment by toonn** [comment]
Cf. #1645

**Comment by Vifon** [comment]
> not sure why you linked to "disabled commands"

@toonn, because it is used to disable potentially confusing behavior by default, even if it's useful in general. A precedent of some kind.
