### ISSUE TITLE
PyPI package out-of-date

### ISSUE THREAD

**Issue by nvllsvm** [ranger/ranger#1258]
The version on [PyPI](https://pypi.org/project/ranger-fm/) is 1.9.0 while the latest is 1.9.1.

**Comment by nvllsvm** [comment]
1.9.2 released today and available on PyPI.

**Comment by toonn** [comment]
Oh, I forgot to correct my error earlier. 1.9.1 was indeed the latest at the time and we just released 1.9.2. Thanks for keeping an eye on this.
