### ISSUE TITLE
'list' object has no attribute 'is_directory'

### ISSUE THREAD

**Issue by freed00m** [ranger/ranger#1269]
@toonn One of the lastest merge broke completely opening files on `master`. 

`'list' object has no attribute 'is_directory'`

Related issues:
https://github.com/ranger/ranger/pull/1178
https://github.com/ranger/ranger/pull/1177

I am not using the repository version as the user mentioned but I use master branch, the fixes did not worked.

**Comment by toonn** [comment]
You're right, I screwed up not once but twice. Let's hope third times the charm : s

**Comment by toonn** [comment]
@freed00m, thank you for the quick report btw. Would've fixed this sooner but I was away. That's what you get for going outside : )
