### ISSUE TITLE
Why running as root disables file previews?

### ISSUE THREAD

**Issue by luciusmagn** [ranger/ranger#1270]
I am not necessarily disagreeing, but I am very curious about the decision why. I don't see it being a dangerous system-catastrophe level feature when ran under root

**Comment by toonn** [comment]
Previews are generated by a shell script. There's no validation at all on this  script. Running random shell scripts as root is too big of a foot gun in our opinion. That's all, really. You can easily enable previews with `zp zf` I believe.

**Comment by luciusmagn** [comment]
Ah alright, makes sense. Thanks for the explanation
