### ISSUE TITLE
copy files to a bookmarked folder doesn't work

### ISSUE THREAD

**Issue by jtourlamain** [ranger/ranger#1277]
#### Runtime Environment

- Operating system and version: Windows 10 running WSL (Ubuntu 16.04.4
- Terminal emulator and version: WSL
- Python version: 2.7.12
- Ranger version/commit: 1.7.1 

#### Current Behavior
copy to a bookmark folder doesn't work.
In rc.conf I added

    map Y`<any> shell cp %%s enter_bookmark %any

#### Expected Behavior
Selected files are copied to the bookmark folder. Ex when pressing "Y`g" the files should be copied to my git bookmarked folder.

#### Context
I could use yy and `g followed by pp, but as I use bookmarks a lot it would save me pressing half of the key strokes

**Comment by toonn** [comment]
Oh, and I think it'd be nice to add ``map Y`<bg> draw_bookmarks``.

**Comment by fullstopslash** [comment]
Just stumbled upon this because I'd like to use ranger to sort through a number of files efficiently. The goal is to move each file from a single folder to various bookmarked folders with just a few keystrokes. I'm not /quite/ following on how to get this fix working.

**Comment by toonn** [comment]
@fullstopslash, ```map Y`<any> shell mv %s %any_path```, should do what you want. (Maybe try with `cp` or `rsync` first to avoid loss of files.

**Comment by fullstopslash** [comment]
Oh splendid! I dig it, but _as is_ it doesn't do the draw_bookmarks bit, is there a way to accomplish this and not rely purely on memory for figuring out what key to press? 

Thanks for the help!

**Comment by toonn** [comment]
Woops, you're right. You can simply add `p'<bg> draw_bookmarks` for now. I just PR'ed a fix.
