### ISSUE TITLE
[Feature Request] Support bat - cat(1) clone with syntax highlighting

### ISSUE THREAD

**Issue by letientai299** [ranger/ranger#1288]
[bat](https://github.com/sharkdp/bat) has git integration when previewing file, which would be a nice compliment for ranger csv aware features. 

![Preview with bat](https://camo.githubusercontent.com/67e44f4a68150325f74b3a46820b7473ff7b91a6/68747470733a2f2f692e696d6775722e636f6d2f326c53573452452e706e67) 
(image from bat project)

**Comment by toonn** [comment]
Support it for previews? I'm not exactly sure what sort of support you're looking for.

**Comment by letientai299** [comment]
Yes. I mean to support bat as the third option for code syntax previewing, together with highlight and pygmentize.

**Comment by toonn** [comment]
Oh, ok. Now I get it. Good request.

**Comment by leiserfg** [comment]
I'm doing 
```sh
        export COLORTERM=screen-256color
        try safepipe bat --color=always  --style="plain,changes"  "$path" && { dump | trim; exit 5; }
```

**Comment by toyboot4e** [comment]
So now we can edit `~/.config/ranger/scope.sh` (the directory may be different) and change the highlithing method with `bat "${FILE_PATH}" --color=always`. 

If you need to enable word wrap: `bat "${FILE_PATH}" --color=always --wrap --terminal-width $WIDTH_VALUE_HERE`. I don't know how to get the proper width and using a hard-coded value for now.

**Comment by toonn** [comment]
`PV_WIDTH` is the width of the preview column in characters.

**Comment by toonn** [comment]
And bat's already part of the default `scope.sh` so I'm gonna close this issue : )
My last comment on #1394 is ominous though o.O : /

**Comment by gennaro-tedesco** [comment]
Is this part of the `scope.sh` on `master`? I see no handling for text types: where exactly is the preview with `bat` taking place?

**Comment by toonn** [comment]
[Here you go.](https://github.com/ranger/ranger/blob/master/ranger/data/scope.sh#L308)

**Comment by gennaro-tedesco** [comment]
Great, thanks (for some reason my `scope.sh` did not have that entry, I have fixed it now!).

**Comment by toonn** [comment]
If you don't customize `scope.sh` it's better not to have it around at all. (Be sure to comment out `set preview_image_script /whatever` in `rc.conf` too if you do this.)

**Comment by thallium** [comment]
the color of highlighting in ranger is different from that in the terminal. I'm using terminator and simply copied that scope.sh mentioned above.

**Comment by toonn** [comment]
@thallium, this could be due to an issue with python's `curses` library. It doesn't support truecolor, while ncurses has for a long time.

**Comment by pexes123** [comment]
`bat` is installed as `batcat` on ubuntu/debian https://github.com/sharkdp/bat?tab=readme-ov-file#on-ubuntu-using-apt
```
            env COLORTERM=8bit batcat --color=always --style="${BAT_STYLE}" \
                -- "${FILE_PATH}" && exit 5
```
solved my problem
