### ISSUE TITLE
ModuleNotFound issue

### ISSUE THREAD

**Issue by lionhead94** [ranger/ranger#1289]
#### Runtime Environment

- Operating system and version: Arch Linux 32
- Terminal emulator and version: xfce4-terminal 0.8.7.4-1.0
- Python version: 3.7.0
- Ranger version/commit: 1.9.1-1.0
- Locale: 

Hi, today I installed ranger on my pc but when I try to launch it, it dies with this python error.
```
Traceback (most recent call last):
  File "/usr/bin/ranger", line 35, in <module>
    import ranger  # NOQA pylint: disable=import-self,wrong-import-position
ModuleNotFoundError: No module named 'ranger'
```
Can it be related to the python version I've installed? Is something I have to fix on my own or it's a known issue that will be fixed in a future update?
I don't have made any customization or edits to the stock installation, it's just a regular install from pacman.

**Comment by toonn** [comment]
This happens when you install ranger then install another python that ranger didn't get installed to. This shouldn't happen when installing both through pacman though, afaik. Could you try reinstalling python, then reinstalling ranger? Since you're running py3.7 you should be aware of #1255.

**Comment by lionhead94** [comment]
Yeah, after posting this I found the ranger-git package in AUR and I installed it. Now it works perfect, but I'll wait for the next update for the regular package in the arch repos. Thank you for your instant reply ;)

**Comment by rhlee** [comment]
I had a conflict with the ranger pip package that I had mistaked installed thinking it was this ranger project. Once I removed it the error went away.

**Comment by toonn** [comment]
@rhlee, ah yes. `ranger` was already taken on PyPI so we had to go with `ranger-fm`.

**Comment by hbak** [comment]
I had an issue where uninstalling the ranger (wrong one, not ranger-fm) package left the folder "Ranger" in site-packages.   Subequent attempts to install ranger-fm would then install into the Ranger folder, causing this issue.  Renaming to "ranger" or  running "rm -rf Ranger" prior to reinstalling ranger-fm finally fixed this for me.

**Comment by toonn** [comment]
That sounds like you're on a case-insensitive filesystem but then the module loading *is* done in a case-sensitive way? Very weird. And I don't think there's anything we can do about this?

Glad you got it resolved though!
