### ISSUE TITLE
Ranger colorschemes displaying low contrast in Urxvt when .Xresources uses the colorized pallette

### ISSUE THREAD

**Issue by minilud** [ranger/ranger#1290]
#### Current Behavior
https://imgur.com/cmhu9xz

I am trying to use this .Xresources:
https://github.com/pjstadig/new.dotfiles/blob/master/.Xresources.solarized.dark

Anyone have any suggestion on how to achieve a greater contrast?

**Comment by toonn** [comment]
If you want to stick with your `.Xresources` you could change the ranger colorscheme. There's a couple included with minor variation `set colorscheme <Tab>` to go through them. There's also the ranger/colorschemes repository. It only has one colorscheme rn but there's another based on `LS_COLORS` in the works (ranger/colorschemes#2). You could also create your own either using the theming as is or the work in #1229.

**Comment by minilud** [comment]
Thanks for the pointers!
