### ISSUE TITLE
[Feature Request] Allow for direct access to the latest command run in the console

### ISSUE THREAD

**Issue by Zaeph** [ranger/ranger#1293]
Hello,

#### RUNTIME ENVIRONMENT

- Operating system and version: Arch Linux x86_64
- Terminal emulator and version: terminator 1.91
- Python version: 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531]
- Ranger version/commit: ranger-master 1.9.1
- Locale: En/GB

#### Feature Suggestion
This is another suggestion in a series of possible enhancements to the `console` in `ranger`, alongside #1285, #1292 and #706.

Following from #1285, in commit 2c3beb6, I’ve attempted to make it easier to access the `console` command history by mapping `Ctrl-p` in the main view to open the `console`, thereby allowing subsequent `Ctrl-p` to go up in the history.

Rather than having `Ctrl-p` merely open the `console`, I would rather have it open the console *and* fill it with the previously-ran command. Otherwise, `Ctrl-p` would only be a glorified `:` or `;`. To that end, we need to run two commands in a succession:
1. `console`
2. `eval fm.ui.console.history_move(-1)`
  Found in the default `rc.conf`:
  https://github.com/ranger/ranger/blob/4974dca6baea741a22381e7744a8e8e86770ed3a/ranger/config/rc.conf#L614

However, by browsing `rc.conf`, I haven’t been able to find a way to have one mapping run two commands in a succession. I was expecting something like this to work:
```
map <C-p> console & eval fm.ui.console.history_move(-1)
```
But it didn’t: the `console` is opened, but the rest of the command from the `&` onwards is passed verbatim. None of the usual ways of linking commands in `bash` such as `&&` and `;` worked either, which in turn lead me to assume that this wasn’t possible.
Two educated guesses:
1. The `console` command is designed to pass all its arguments verbatim, and that there’s no way to coordinate commands in the way that I’d like,
2. Because the command triggers a change of mode from `main` to `console`, the transmission of the second command cannot be properly achieved.

I’d like to know if I’ve overlooked something in `rc.conf` that could make this feature a reality. In the meantime, the patch made in 2c3beb6 is fit for my purpose.

Thank you.

**Comment by toonn** [comment]
Chain is used to chain commands, `chain console; fm.ui...`.

I'm not a huge fan of using `C-p` to open the console. it should do the same thing as `k` or `<Up>`. You're thinking of the console as a shell but really it's like vim's command line `:`. If vim has a keybinding that goes from normal mode to having the previous command on the command line, let's use that. Otherwise we can still discuss. (Note that I have nothing against people personally rebinding `C-p`.)

**Comment by Zaeph** [comment]
Thanks for letting me know about `chain`. The following works as expected
```
map <C-p>  chain console; eval fm.ui.console.history_move(-1)
```
(Note the `eval`, which was missing from your snippet.)

In the `browser` view, `Ctrl-p` does not actually move the point up, and `Ctrl-n` opens a new tab rather than moving the point down. That lead me to think that `Ctrl-p` could be used for opening the console and pre-filling it with the last-ran command, but I completely understand if it’s an odd behaviour for someone used to `vim` from which `ranger` seems to be drawing a lot.
As someone who’s been strictly kept to `emacs` since I transitioned to GNU/Linux, but who’ll happily use `j` and `k` in `less` to move up and down, I always find myself sitting between two stools. However, I’ve never been a big fan of the arrow keys, and there doesn’t seem to be an arrow-less alternative to the option you suggest.

My question to you would then be if there’s a key-binding in `vim` which would open the `console` and pre-fill it with the last-ran command. If there isn’t, we have two options:
- Since `Ctrl-n` is mapped to a non-directional command in the `browser`, we could just as well map `Ctrl-p` to the requested command,
- Drop the feature entirely, and leave it to user preference.

**Comment by Zaeph** [comment]
You’d mentioned `rc_emacs.conf` to me the other day, and I’ve got plans to comb through it and see whether I could improve it. Thanks for suggesting it.
And `vim` indeed has a completely different paradigm than `emacs`, which is why I asked you my question. Based on my limited understanding of `vim`, I guess I was expecting something like `:X` where `X` would be a special character like another `:` and which would fill the console with the previously-ran command.

I’ll write a PR tomorrow for `C-n`, but I’m getting the feeling that `rc.conf` and the manual have had many changes over the year with relics of yore here and there. We could try to comb through it and see what is warranted and what isn’t, but I’d be wary of changing key-bindings towards which people have grown accustomed.

**Comment by toonn** [comment]
Afaik there's only `:[optional prefix]<up/down>` the optional prefiix means you will only get commands that start with that prefix.
Then there's `@:` which just repeats the last command.
And then there's the command window `q:` where you have the full editing/search power of vim to your disposal to select and alter commands from your history.

**Comment by Zaeph** [comment]
Thanks for your answer.
So, it would seem that there’s no straight-forward command in `vim` to open the console and pre-fill it with the previous command, although it offers a two-command way (`:` then `<UP>`).

Since we haven’t found a better use for `Ctrl-p` yet, I’ll submit the PR, and if we come up with a better use for it later, there’s no problem with removing it.
