### ISSUE TITLE
SVN Error

### ISSUE THREAD

**Issue by slackhead** [ranger/ranger#1296]
ranger version: ranger-master 1.9.1 (also tried with a fresh git clone)
Python version: 3.6.5 (default, Aug  9 2018, 08:22:49) [GCC 5.5.0]
Locale: en_GB.UTF-8
Slackware 14.2 64 bit
urxvt 9.22 + Screen version 4.06.02 (GNU) 23-Oct-17
svn --version output:
```
svn, version 1.9.7 (r1800392)
   compiled Aug 10 2017, 15:15:12 on x86_64-slackware-linux-gnu

Copyright (C) 2017 The Apache Software Foundation.
This software consists of contributions made by many people;
see the NOTICE file for more information.
Subversion is open source software, see http://subversion.apache.org/

The following repository access (RA) modules are available:

* ra_svn : Module for accessing a repository using the svn network protocol.
  - with Cyrus SASL authentication
  - handles 'svn' scheme
* ra_local : Module for accessing a repository on local disk.
  - handles 'file' scheme
* ra_serf : Module for accessing a repository via WebDAV protocol using serf.
  - using serf 1.3.8 (compiled with 1.3.8)
  - handles 'http' scheme
  - handles 'https' scheme

The following authentication credential caches are available:

* Plaintext cache in /home/blabla/.subversion
* Gnome Keyring
* GPG-Agent
* KWallet (KDE)
```

Current Behavior:
Entering a SVN directory and running ranger outputs only an error.

Expected Behavior:
It would give similar info to git.

Steps to reproduce:
Create an SVN directory (I tried with MPlayer https://mplayerhq.hu/design7/dload.html):
svn checkout svn://svn.mplayerhq.hu/mplayer/trunk mplayer
cd mplayer
ranger
press W

Traceback:
```
Message Log:
11:12:54 INFO ranger version: ranger-master 1.9.1
11:12:54 INFO Python version: 3.6.5 (default, Aug  9 2018, 08:22:49) [GCC 5.5.0]
11:12:54 INFO Locale: en_GB.UTF-8
11:12:54 INFO Process ID: 27126
11:12:56 ERRO Notification: VCS Exception: View log for more info
11:12:56 ERRO string index out of range
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/ranger/ext/vcs/vcs.py", line 472, in run
    self._queue_process()
  File "/usr/lib64/python3.6/site-packages/ranger/ext/vcs/vcs.py", line 452, in _queue_process
    has_vcschild = self._update_subroots(dirobj.files_all)
  File "/usr/lib64/python3.6/site-packages/ranger/ext/vcs/vcs.py", line 414, in _update_subroots
    if not rootvcs.init_root():
  File "/usr/lib64/python3.6/site-packages/ranger/ext/vcs/vcs.py", line 237, in init_root
    self.obj.vcsstatus = self.data_status_root()
  File "/usr/lib64/python3.6/site-packages/ranger/ext/vcs/svn.py", line 104, in data_status_root
    code = line[0]
IndexError: string index out of range
```

Note: I haven't tried with any other repos as I don't know anyone else using SVN. I will gladly test some others if anyone leaves a link below.

Note2: I tried running ranger -d, but it didn't exit at the error and I had to ctrl-c. I didn't see any more info than the above.

**Comment by toonn** [comment]
@slackhead, could you test @bigbigtor's  fix? In a ranger repo run `git fetch upstream pull/1296/head:bigbigtor-fix` check out that branch and run `ranger.py`.

**Comment by slackhead** [comment]
It's giving me an error that upstream doesn't exist.

**Comment by slackhead** [comment]
OK. I cloned his repo and it seems fine in the mplayer svn now. It is showing a red ! next to the green tick in the status bar though, and I've no idea what that is.  There are no errors in :display_log.__

**Comment by toonn** [comment]
For svn the `!` symbol means deleted. Seems weird to me since how can a file exist if it's deleted? Maybe it means deleted from the current commit or something, i.e. untracked in git terminology?
