### ISSUE TITLE
Alternative color options for tagged directories and files

### ISSUE THREAD

**Issue by spcmd** [ranger/ranger#1301]
#### Runtime Environment
- Operating system and version:  Arch Linux x86_64 
- Terminal emulator and version: urxvt  v9.22
- Python version:  3.6.6 (default, Jun 27 2018, 13:11:40) [GCC 8.1.1 20180531]
- Ranger version/commit: ranger-master 1.9.1
- Locale: en_US.UTF-8

I'd like to use an alternative color for tagged dirs and files. I mean, the dirs are colored blue for me, but if I tag a dir I'd like it to be some other color (bit darker for example). 

See this example picture: https://i.imgur.com/hZpUrhW.png

I know I can set the tag character's color in the colorscheme files but I can't set an alternative color for the tagged "item" itself. I tried `if context.tag_marker and context.directory` but it  doesn't work. The same way I'd like an alternative color option for every other filetype defined in the colorscheme files (media files, text files etc).

Is there a way to achieve this?

**Comment by toonn** [comment]
I think you want to use `context.tagged`, `context.tag_marker` means it's the tag marker itself.

We recently started a colorschemes repo (ranger/colorschemes). It'd be great if you report issues regarding colorschemes there so we build up a knowledge base of issues and solutions in that repo. This should make it easier to find information regarding colorschemes in the future.

**Comment by spcmd** [comment]
Thank you! Indeed `context.tagged` is the solution. There is no `context.tagged` in neither of the 
 colorscheme files, that's why I didn't know about it.

**Comment by toonn** [comment]
I didn't know either. I found it in `ranger/gui/context.py`.
