### ISSUE TITLE
Linewrap on text preview to fit width

### ISSUE THREAD

**Issue by rawzen** [ranger/ranger#1304]
I would to have the option to have text previews wrap the contents of long lines to fit the preview panel width. 

Now it doesn't seem to matter if I use scope.sh (with highlight) or not. Long lines are simply cut off at the right margin.

**Comment by toonn** [comment]
This should already be happening for pdf previews. I'm assuming you mean for regular plaintext files?

**Comment by rawzen** [comment]
Yes, it's plaintext files I wish to see wrapped :-) I'd love to help with
the code but haven't been able to find what's controlling the rendering of
text.

Den tors 27 sep. 2018 10:58Toon Nolten <notifications@github.com> skrev:
