### ISSUE TITLE
Feature: Windows' Explorer-like mode for `search%space`.

### ISSUE THREAD

**Issue by WloHu** [ranger/ranger#1305]
In Windows Explorer I used to go through directories by typing single letter for file or directory and hitting `Enter` when correct item was highlighted.
Compared to ranger' `/words``Enter`[`n`]`Enter` it was way faster to browse because:

- repeated single letter with `Enter` takes 1 less key (which is `/`) in simple cases, when item names have unique 1st letter;
- key sequence for frequently browsed directories is easier to type and memorize because of missing `/` and `Enter` (to submit pattern);
- jumping through filtered items doesn't require additional key `n` but only repeating the same letter used for initial filtering.

The requested feature is new mode which allows such browsing like in:
- Windows Explorer (single letter jumps), **or**
- osu!-like music filtering (dynamic filtering by typed words), which can be compared to all-time active `/` without requirement to submit filtering word with `Enter` (thus dynamic).

Let me know if:
- there is better way of browsing directories,
- this can be made by custom plugin and doesn't require full blown feature update.

I've Googled before posting but search results weren't accurate because "ranger" threw results out of context.

**Comment by toonn** [comment]
Sounds like you're looking for `:travel`, there's also `:find` for a one-shot version of this (more or less).

**Comment by WloHu** [comment]
It looks like `:travel` is equivalent of what I've asked.
- `Tab` is used to travel ambigous results instead repeated character key.
- It doesn't require hitting `Enter` on single matching result.
- Dynamic and fuzzy search.
- It's a separate Vim-like mod.

I'm sure it will be as easy to memorize frequently browsed paths as it is in Windows and because how powerful it is, it gives me more possibilities.

Thanks for help!
