### ISSUE TITLE
No pdf or image preview

### ISSUE THREAD

**Issue by forkbomb9** [ranger/ranger#1306]
#### Runtime Environment

- Operating system and version: Arch Linux up-to-date kernel 4.18.6
- Terminal emulator and version: termite v13
- Python version: 3.7.0 (default, Jul 15 2018, 10:44:58) [GCC 8.1.1 20180531]
- Ranger version/commit: ranger-master 1.9.1
- Locale: en_US.UTF-8

#### Current Behavior
When trying to preview pdf or image files, nothing is displayed and at the status bar is displayed `list index out of range`

#### Expected Behavior
pdf and image preview displayed

#### Context

I tried to start ranger within termite without tmux, and from konsole with and without tmux, and still the same error. Tried the latest master, same. Tried with a master default rc.conf and scope.sh changing only the `set preview_image` to true, and same.

**Comment by toonn** [comment]
You have to enable both `use_preview_script` and `preview_images` and the `preview_images_method` you set has to be available, for w3m that is the `w3m-img` binary.

I seem to remember there's problems with termite and w3m though.

You might also want to update your ranger since 1.9.2 fixes some issues with python 3.7.

**Comment by forkbomb9** [comment]
With `use_preview_script` and `preview_images` set to `true`, `preview_image_method` in `w3m` and `w3m` installed, it says `list index out of range` on Termite and Konsole, ranger 1.9.2 python 3.7

**Comment by toonn** [comment]
It's really weird this happens for pdf previews too. Did you change scope.sh to do image previews of pdfs?

Could you run with `ranger --debug` and report the error? And run `ranger --debug --clean` then `:set preview_images true` and verify the same error happens?

**Comment by forkbomb9** [comment]
```shell
$ ranger --debug                                                                                                                                                                       11:15:37
ranger version: ranger-master 1.9.2
Python version: 3.7.0 (default, Sep 15 2018, 19:13:07) [GCC 8.2.1 20180831]
Locale: en_US.UTF-8
Current file: '/home/forkbomb/android-icon-192x192.png'

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 398, in loop
    ui.draw_images()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 404, in draw_images
    self.browser.columns[-1].draw_image()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/pager.py", line 116, in draw_image
    self.fm.notify(ex, bad=True)
  File "/usr/lib/python3.7/site-packages/ranger/core/actions.py", line 172, in notify
    raise obj
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/pager.py", line 111, in draw_image
    self.wid, self.hei)
  File "/usr/lib/python3.7/site-packages/ranger/ext/img_display.py", line 145, in draw
    input_gen = self._generate_w3m_input(path, start_x, start_y, width, height)
  File "/usr/lib/python3.7/site-packages/ranger/ext/img_display.py", line 192, in _generate_w3m_input                                                                                          
    fontw, fonth = self._get_font_dimensions()
  File "/usr/lib/python3.7/site-packages/ranger/ext/img_display.py", line 134, in _get_font_dimensions                                                                                         
    xpixels, ypixels = int(output[0]), int(output[1])
IndexError: list index out of range

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
$
```
Same with `ranger --debug --clean` and `:set preview_images true`

**Comment by toonn** [comment]
Could you run the following things in a python shell and report the results?

```
import fcntl
import struct
import sys
from subprocess import Popen, PIPE
import termios

struct.unpack("HHHH", fcntl.ioctl(sys.stdout.fileno(), termios.TIOCGWINSZ, struct.pack("HHHH", 0, 0, 0, 0))

Popen(['path/to/w3mimgdisplay', "-test"], stdout=PIPE, universal_newlines=True).communicate()
```

(I might've missed some imports, any errors should point you in the right direction.)

**Comment by forkbomb9** [comment]
Is there any way I can help to fix this?

**Comment by forkbomb9** [comment]
No, the google logo is not shown:
![2018-10-23-174251_grim](https://user-images.githubusercontent.com/33267474/47395194-42bad800-d6eb-11e8-94cd-9fbbb4da99a1.png)

**Comment by toonn** [comment]
Did you check if the `Preview inline images` setting is set to yes? Press `o` in w3m to access the settings.

If it doesn't work with w3m though I'm afraid we won't be able to get it to work with ranger.

**Comment by samerickson** [comment]
I am having similar issues, though when I use ranger in an X11 environment everything works as intended, the issues arise when trying to use Wayland.

**Comment by toonn** [comment]
@samerickson, I wouldn't be surprised if `w3mimgdisplay` makes assumptions about X11. Does it work just in the terminal or with the `w3m` browser?

I suspect your only recourse will be a terminal that supports native image previews, e.g., terminology, kitty or urxvt.

**Comment by samerickson** [comment]
Thanks @toonn. You were entirely right. Switching to Kitty terminal and installing python-pillow works perfectly.
