### ISSUE TITLE
File open and freeze the terminal

### ISSUE THREAD

**Issue by pdanc** [ranger/ranger#1309]
Specs: Debian Stable / xfce-terminal / ranger 1.7

I set Mupdf for open pdf and Viewnior for image files, but when i open a pdf or any image file (jpg or png) ranger stays freeze or somethig that, and i only can return to ranger when i close the app what open the file.

My `rifle.conf` :

ext png = viewnior "$@"
ext pdf = mupdf "$@"

**Comment by pdanc** [comment]
I found the correct mode for do it. With this line you can open many files without freezes ranger (look the comma):

`ext pdf, flag f = mupdf "$@"`

**Comment by toonn** [comment]
Might want to use `mupdf -- "$@"`, read [here](https://unix.stackexchange.com/questions/11376/what-does-double-dash-mean-also-known-as-bare-double-dash) why.
