### ISSUE TITLE
Make open_with always use the `open_with` always open with the `f` flag to avoid hanging

### ISSUE THREAD

**Issue by mrbig033** [ranger/ranger#1310]
#### Runtime Environment

- Operating system and version: MX Linux 17
- Terminal emulator and version: Suckless Terminal 0.8.1
- Python version: 2.7.13 / 3.5.3
- Ranger version/commit: ranger-master 1.9.1
- Locale: US

Ranger will always hang the terminal when I open a file using the `r` key to open the `open_with` dialog. I use `f` to prevent that, but I wish this wasn't necessary, since there's no scenario where I'd want my Ranger instance to get stuck like that.

**Comment by toonn** [comment]
There is though, whenever the command doesn't open a new window you'd lose control over it. You'd have to go figure out the pid and kill it if you want to stop the program for example.

It sounds like you do this often, so why not add rifle rules?
You could achieve this by rebinding `r` though: `map r chain draw_possible_programs; console -p10 open_with  f`, note the double space before `f`.

**Comment by mrbig033** [comment]
Thanks! Your suggestion is working perfectly! May I suggest adding this to the documentation? Or maybe as a comment to rc.conf? This seems useful enough to be more well know. Thanks again! ;)

**Comment by toonn** [comment]
[Here you go.](
https://github.com/ranger/ranger/wiki/Keybindings#always-fork-when-using-open_with)

**Comment by toonn** [comment]
@connbrack, the tab completion code isn't very smart at the moment. Really we should try completing at the cursor but it just takes everything after the command and tries to match it as a prefix to known executables. That doesn't work when there's a space in the string (due to the flag argument).
