### ISSUE TITLE
Kitty image viewer fails - cannot write mode CMYK to PNG

### ISSUE THREAD

**Issue by letientai299** [ranger/ranger#1312]
#### Runtime Environment

- Operating system and version:  macOS High Sierra 10.13.6 17G65 x86_64
- Terminal emulator and version: kitty 0.12.1 created by Kovid Goyal
- Python version: Python 2.7.15
- Ranger version/commit: 8e9451e6 Updated release doc

#### Current Behavior
Fail to load an CMYK mode [image](https://user-images.githubusercontent.com/8386780/45733623-0986d800-bc14-11e8-8c60-460a4f0facbc.jpg)

Log (I don't know why I can't copy using mouse, hence the picture).

![image](https://user-images.githubusercontent.com/8386780/45733835-beb99000-bc14-11e8-9312-a138d69f665d.png)

#### Expected Behavior
The image should load fine.

BTW, it's sad that kitty image feature can't be used within Tmux.

**Comment by kovidgoyal** [comment]
@toonn kitty most definitely binds cmd-c/v on the mac as well. And the white pixel line is a bug that was fixed a while ago, you should update kitty.

**Comment by mark-dawn** [comment]
Whoops, I thought PIL was smart and would autoconvert when saving.
This is an easy fix. I just need to move a line, expect a fix soon.

**Comment by toonn** [comment]
Fixed in #1319.
