### ISSUE TITLE
No image preview in URXVT

### ISSUE THREAD

**Issue by wjgan7** [ranger/ranger#1317]
#### Runtime Environment
- Operating system and version: Ubuntu 18.04.1 LTS
- Terminal emulator and version: rxvt-unicode-256color
- Python version: 2.7.15rc1 (though I also have 3.7 installed)
- Ranger version/commit: ranger stable 1.8.1 (I believe I installed through apt-get)

#### Current Behavior
No image previews in URXVT despite installing w3m, adding `set preview_images true` and `set preview_images_method [urxvt|w3m]` to my rc.conf, and making sure pixbuf is installed. If I run `w3m xkcd.com` images render and if run `urxvt -pixmap some_image.jpg` then the background is set properly. Any idea what the issue might be? I've used this exact same config on a Debian setup before.

For the following picture, I noticed that I did `preview_image_method` by mistake but I've also tried with `preview_images_method`
[https://i.imgur.com/HfZ7TkE.png](https://i.imgur.com/HfZ7TkE.png)

My rc.conf is this
```
set preview_images true
set preview_images_method urxvt
set draw_borders true
```

**Comment by toonn** [comment]
`use_preview_script` is set to a path that exists, right? I think on 1.8.1 you still had to `ranger --copy-config=all`.

**Comment by wjgan7** [comment]
Oh no I hadn't had that set. I reinstalled the latest version of ranger and it works now. Thank you!
