### ISSUE TITLE
author’s public key

### ISSUE THREAD

**Issue by s5unty** [ranger/ranger#1325]
![20181004_185331](https://user-images.githubusercontent.com/50655/46469741-e14bcb80-c806-11e8-95f1-681730421260.png)

#### Current Behavior
> If you want to be sure of the authenticity of the snapshot, please download ranger-stable.tar.gz and its signature, then verify the signature with the author’s public key: huterich.gpg.

```
# gpg --import huterich.gpg 
gpg: key F08CE1E200FB5CDF: public key "huterich <hut@lavabit.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
# gpg --list-keys
/root/.gnupg/pubring.kbx
------------------------
pub   rsa4096 2010-09-13 [SC]
      1E9B36EC051FF6F7FFC969A7F08CE1E200FB5CDF
uid           [ unknown] huterich <hut@lavabit.com>
sub   rsa4096 2010-09-13 [E]
# gpg --verify ranger-stable.tar.gz.sig
gpg: assuming signed data in 'ranger-stable.tar.gz'
gpg: Signature made Mon Sep 10 04:12:55 2018 CST
gpg:                using EDDSA key F6E0408F5D7EB10E7837609D0E7B646BBD8CD4C2
gpg:                issuer "toonn@toonn.io"
gpg: Can't check signature: No public key
# gpg --keyserver keys.gnupg.net --search-keys toonn@toonn.io
gpg: error searching keyserver: No data
gpg: keyserver search failed: No data
```

#### Expected Behavior
> If this prints Good signature from "**AUTHOR**", the signature was verified.

**Comment by toonn** [comment]
I'm sorry, this was my bad. I published the key to keys.gnupg.net just now.

**Comment by s5unty** [comment]
Thanks for quick reply.

**Comment by toonn** [comment]
No problem. Did you manage to verify the signature?

**Comment by schuay** [comment]
Running into this now when packaging for Arch:

```
$ gpg --verify ranger-1.9.2.tar.gz.sig 
gpg: assuming signed data in 'ranger-1.9.2.tar.gz'
gpg: Signature made Sun 09 Sep 2018 10:13:31 PM CEST
gpg:                using EDDSA key F6E0408F5D7EB10E7837609D0E7B646BBD8CD4C2
gpg:                issuer "toonn@toonn.io"
gpg: Can't check signature: No public key

$ gpg --keyserver keys.gnupg.net --search-keys toonn@toonn.io
gpg: data source: http://192.146.137.99:11371
gpg: error searching keyserver: No data
gpg: keyserver search failed: No data
```

I'll wait to update until this is fixed.

**Comment by toonn** [comment]
@schuay, not sure what I can do about this? My key is on one of their servers, the search works for me. Maybe you can try this one specifically, `http://[2001:67c:26b4::98:0]:11371`?

**Comment by schuay** [comment]
Hmm, now it works:

```
$ gpg --search-keys toonn@toonn.io
gpg: data source: https://[2001:67c:26b4::98:0]:443
(1)	toonn <toonn@toonn.io>
	  256 bit EDDSA key 0D63346A5D15D055, created: 2018-02-22, expires: 2019-02-22
```

Let me see what's going on once I get home, maybe the problem is on my workstation.

**Comment by schuay** [comment]
Sorry, never got around to this again. It's been in my TODO list since last Nov. I'll update here when / if something happens.

**Comment by toonn** [comment]
Np, I closed because of inactivity and the issue being mostly resolved anyway. Feel free to ping with updates.
