### ISSUE TITLE
tmux mapping fails on `import shlex; shlex.quote("...")`

### ISSUE THREAD

**Issue by stumash** [ranger/ranger#1335]
#### Runtime Environment

- Operating system and version: Ubuntu 16.04 LTS
- Terminal emulator and version: GNOME Terminal 3.18.3
- Python version: python 3.5.2
- Ranger version/commit: ranger-stable 1.7.1, python 2.7.12
(default, Dec 4 2017, 14:50:18) [GCC 5.4.0 20160609]
- Locale: 
LANG=en_CA.UTF-8
LANGUAGE=en_CA:en
LC_CTYPE="en_CA.UTF-8"
LC_NUMERIC="en_CA.UTF-8"
LC_TIME="en_CA.UTF-8"
LC_COLLATE="en_CA.UTF-8"
LC_MONETARY="en_CA.UTF-8"
LC_MESSAGES="en_CA.UTF-8"
LC_PAPER="en_CA.UTF-8"
LC_NAME="en_CA.UTF-8"
LC_ADDRESS="en_CA.UTF-8"
LC_TELEPHONE="en_CA.UTF-8"
LC_MEASUREMENT="en_CA.UTF-8"
LC_IDENTIFICATION="en_CA.UTF-8"

#### Current Behavior

I put the following in my `rc.conf`
```
map es eval import shlex; fm.run("tmux splitw -h rifle " + shlex.quote(fm.thisfile.basename))
map eS eval import shlex; fm.run("tmux splitw -v rifle " + shlex.quote(fm.thisfile.basename))
map ew eval import shlex; fm.run("tmux new-window rifle " + shlex.quote(fm.thisfile.basename))
```
as per the instructions in the tmux section of the 'useful keybindings' page in the wiki.

when I run the mapping `es`, I get `'module' object has no attribute 'quote'`

#### Expected Behavior

I expect the mapping, when run, to open the highlighted file in a tmux split.

I tried on the current master and had the same problem.

#### Context

trying to use ranger to open a file in a tmux pane-split

#### Steps to reproduce
1. put the mappings I posted above in the `rc.conf` file in `~/.config/ranger` folder
2. run ranger
3. try the mapping (type `es`)

#### Possible Fixes

I expect that it might be possible to fix the problem by updating ranger to use a newer version of python

**Comment by toonn** [comment]
I get this same error when I run ranger with python 2.7.15, which isn't surprising because shlex didn't have the quote function in 2.7.

Run the following inside ranger to see which version of python you're running it with: `:eval import sys; fm.notify(sys.version)`

**Comment by toonn** [comment]
Oh, just noticed you listed two python versions and ranger's using 2.7. That's the reason for the error. You should install ranger with python 3. I'm not sure there's a more recent package for ubuntu lts so I suggest you remove ranger and just run `pip install ranger`, read up on issues with installing things with system pip. (It should be fine™)

Note that any config files you have likely need newer versions. Remove all of `rc.conf, rifle.conf, commands.py, scope.sh` from `~/.config/ranger` **if** you didn't customize them. If you did you'll have to manually merge the changes.

**Comment by stumash** [comment]
Thanks for the reply! It seems I'm just about ready to close the issue.

Not that I'm proud to ask for the hand-holding, but would you be able to tell me *exactly* how to update the python version in ranger?

As i said in my issue, I cloned the ranger repo and used the most recent master commit but had the same problem, so I suspect that there's some kind of way for me to manually update the python version being used by ranger.

**Comment by toonn** [comment]
Like I said, `pip install ranger`, pip is linked to your python version so if you have the right pip you'll get ranger installed for the right python. You could also run it from the repo with `python3 ranger.py` but installing is the way to go unless you're just developing ranger.

If you don't/can't have a python 3 on your system you could use a virtualenv/venv with a python 3 version. Then you can activate the venv, install ranger with pip and all you'll have to do is add the venv's bin directory to your PATH. That way you know you're not messing with your system python.

**Comment by stumash** [comment]
`pip --version`
  `pip 18.1 from /usr/local/lib/python3.5/dist-packages/pip (python 3.5)`
`sudo -H pip3 install ranger`

Then I tried to test import ranger:
```bash
python3
```
```python3
>>> import ranger
Traceback (most recent call last):
  File "<stdin<", line 1, in <module>
ImportError: No module named 'ranger'
```

I then did `sudo apt-get remove ranger`, then `sudo apt-get install ranger`.

`ranger --version`
```
ranger-stable 1.7.1

Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609]
```

So I'm not really sure what's going on here. Sorry for being a bother, I'm kind of stuck :disappointed:

**Comment by stumash** [comment]
Screw it I'm just gonna use the repo. Thanks for your time.

In case someone else comes across this issue and needs help setting up what I did, here's what I did:

```bash
mkdir -p ~/bin/bin
cd ~/bin
git clone <ranger-repo-clone-url>
cd ~/bin/bin
touch ranger && \
    chmod u+x ranger && \
    echo -e "#!/usr/bin/env bash\n\npython3 ~/bin/ranger/ranger.py"
```

Then I went into my `.bashrc` and added at the bottom:

```bash
PATH="~/bin/bin:${PATH}"
export PATH
```

**Comment by toonn** [comment]
You can't import ranger like that. The `apt-get remove` was a step in the right direction. The install was taking a step back in the wrong direction : )
So remove it again, temporarily remove your `~/bin/bin` from your path and do the following:

```
cd /path/to/your/repo
env PYTHON=python3 make install
```

That should be all you need. Feel free to hop into #ranger on chat.freenode.net for more realtime help.

**Comment by stumash** [comment]
ya the `apt-get` stuff that I did seemed stupid.

About doing `import ranger` in python3, I only did it because I saw that in `ranger.py` they do it, but that's python2.7, you're right.

In any case, the stuff that I did with the repo and the .bashrc and "$HOME" **did work**.

However, I undid all that crap and just did the `make` command since that seemed much cleaner.

Thanks again.

**Comment by Vifon** [comment]
> (...) `pip install ranger` (...)

Daily reminder: the PyPI package is called `ranger-fm` as `ranger` is something completely different.

**Comment by stumash** [comment]
thanks so much for that information! I had no clue it was `ranger-fm`!!

just for next time, where is that documented?

**Comment by toonn** [comment]
It's documented on PyPI : > I don't think it's documented anywhere else.
Importing ranger only works when you're in the right directory, i.e. the directory where `ranger.py` *is*. And possibly, although I'm not sure, only from inside `ranger.py` because otherwise you might try importing `ranger.py` instead of the `ranger` module?

**Comment by laggardkernel** [comment]
You can achieve the effect in different ways.

Method No.1: use keybindings in tmux.

```
# inherit current path in new window, pane/split
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
```

Method No.2: use shell command in ranger

```bash
map ev shell tmux split-window -h -c %d
map es shell tmux split-window -v -c %d
map ew shell tmux new-window -c %d
```
