### ISSUE TITLE
Go to file while typing it

### ISSUE THREAD

**Issue by myxo** [ranger/ranger#1337]
In Far I can press Alt key and start typing name of file (I guess mc have simular behaviour). This will move cursor to the file which name I typing. 
I know I can have this (kinda) with
/^Fileprefix<Enter>
But I have to stroke ^ and Enter. Too long =)

Is there a possibility to make something simular in ranger? I think this is not rare use case.

**Comment by toonn** [comment]
Look into the `:find` command and the key binding `f`, this will not just focus the file/directory but use rifle to open it, or enter it, respectively.

**Comment by myxo** [comment]
Great! But can I just focus on file not open it?

**Comment by toonn** [comment]
`:scout -eit` would do find without automatically opening the file. However you need to cancel the command before you can move around again.
The scout flag you're most interested in seems to be `-t` so look at the docs and see if you can piece together exactly what you're looking for. Then you can alias it like is done for find in `rc.conf` or just map it, whatever floats your boat.

**Comment by bluenote10** [comment]
I use `:find` mainly to navigate to directories, and I find the behavior of entering a folder as soon as it matches dangerous. Usually a user has a short sequence of letters in mind which they type without consciously waiting after each keystroke if the match is unique. As a result I often enter a directory and accidentally execute some commands in the directory I enter. For instance if I'm in a folder with the subfolders `tests` and `topology` and my mental shortcut is "topo" to enter the `topology` directory, I would enter it after `to` and execute `po = paste overwrite` in the subfolder -- not quite what I wanted.

I'll give `:scout -eit` a try, but from a UX perspective I would suggest to reconsider the default behavior of `:find`.

@myxo Another useful thing is to use `<TAB>` to cycle through partial matches.

**Comment by toonn** [comment]
@bluenote10, that actually shouldn't be a problem. There's a builtin timeout for this of half a second. So if this is a problem for you you're either a slow typist (; )) or you're running an old version.

**Comment by myxo** [comment]
@toonn @bluenote10 Thanks, that was exactly what I want.
