### ISSUE TITLE
Transposing words and characters at the console

### ISSUE THREAD

**Issue by ghost** [ranger/ranger#1344]
I'm fond of the character and word transposition provided in emacs and some terminal emulators, where usually 'Ctrl-t' switches the characters before and after the cursor, and 'Alt-t' switches the words before and after the cursor. Has anyone considered adding this to console editing in ranger?

**Comment by toonn** [comment]
No so far, no. We'd probably accept the addition if you can implement it clearly. I can't really imagine using these often but if there's good keybinds  left it won't hurt.

**Comment by r-sable** [comment]
Cool, I'll start working on it then.

**Comment by toonn** [comment]
Implemented in 533f412.
