### ISSUE TITLE
[Feature suggestion] Add human friendly display format for dates

### ISSUE THREAD

**Issue by joelostblom** [ranger/ranger#1364]
Thanks for making ranger, it such an efficient file browser!

One thing that I like from file managers such as Nautilus and Thunar is the
option to display dates in a more human friendly format, e.g. "21 Oct" or
"Mon":

![image](https://user-images.githubusercontent.com/4560057/47619040-4bb6fb00-da97-11e8-8a8f-1c25bd9d9fa9.png)

This was really easy to add to ranger thanks to the custom line mode
functionality and I thought it could be nice to have as options in the default
installation also for those that prefer not to write their own linemodes and
for increased discoverability. I think this format facilitates getting a quick
overview compared to the more verbose default date format:

Old style:
![image](https://user-images.githubusercontent.com/4560057/47619016-ff6bbb00-da96-11e8-845c-c499677e64a2.png)

Suggested style:
![image](https://user-images.githubusercontent.com/4560057/47619004-c7647800-da96-11e8-817a-d22514645a5c.png)

Let me know if this is something you are interested in and I can submit a PR.

<details>
<summary>Here is the code for the line mode</summary>

```python
from datetime import datetime
import ranger.api
import ranger.core.linemode


@ranger.api.register_linemode
class MyLinemode(ranger.core.linemode.LinemodeBase):
    name = "human_mtime"

    def filetitle(self, fobj, metadata):
        return fobj.relative_path

    def infostring(self, fobj, metadata):
        if fobj.stat is None:
            return '?'
        file_date = datetime.fromtimestamp(fobj.stat.st_mtime)
        time_diff = datetime.now().date() - file_date.date()
        if time_diff.days > 364:
            return file_date.strftime("%-d %b %Y")
        if time_diff.days > 6:
            return file_date.strftime("%-d %b")
        elif time_diff.days >= 1:
            return file_date.strftime("%a")
        else:
            return file_date.strftime("%H:%M")
```

I also made one for the size and this date format (padded with whitespace
so that the sizes still line up in a column)

```python
from datetime import datetime
import ranger.api
import ranger.core.linemode
from ranger.ext.human_readable import human_readable


@ranger.api.register_linemode
class MyLinemode(ranger.core.linemode.LinemodeBase):
    name = "size_human_mtime"

    def filetitle(self, fobj, metadata):
        return fobj.relative_path

    def infostring(self, fobj, metadata):
        if fobj.stat is None:
            return '?'
        size = human_readable(fobj.size)
        file_date = datetime.fromtimestamp(fobj.stat.st_mtime)
        time_diff = datetime.now().date() - file_date.date()
        if time_diff.days > 364:
            return "%s %11s" % (size, file_date.strftime("%-d %b %Y"))
        if time_diff.days > 6:
            return "%s %11s" % (size, file_date.strftime("%-d %b"))
        elif time_diff.days >= 1:
            return "%s %11s" % (size, file_date.strftime("%a"))
        else:
            return "%s %11s" % (size, file_date.strftime("%H:%M"))
```

If ranger is being used on 31 Dec on a leap year, e.g. 2020, this would display
files modified on Jan 1st the same year as "1 Jan 2020" rather than just "1
Jan". This can be avoided by adding a check for leap years:

```python
        if file_date.year % 4 == 0 and (year % 100 != 0 or year % 400 == 0):
            days_in_year = 365
        else:
            days_in_year = 364
```

But this is to accommodate an even that *might* happen on one day every
4 years... Not sure if it is needed.

Finally a short note that Thunar and Nautilus does not use the exact same human readable date
format. My implementation is closer to the Nautilus style with the main
deviation being that I use the three weekday letter abbreviation instead of
"Yesterday" since I think it looks neater (but willing to change if someone
feels strongly about this).

</details>

**Comment by toonn** [comment]
I like it, if nothing else it should be on the wiki.

@Vifon, what's our policy on including linemodes?

**Comment by dllud** [comment]
This would be a great add to ranger's code base. Way better than the default, which takes too much horizontal space and shows mostly redundant information.

@joelostblom thanks a lot for sharing!

**Comment by Vifon** [comment]
> @Vifon, what's our policy on including linemodes?

Mostly this:  
![](https://i0.kym-cdn.com/photos/images/newsfeed/000/292/573/0c2.jpg)

Thumbs up for the alternative date format but why are you manipulating dates (and leap years!) by hand, @joelostblom?

**Comment by dllud** [comment]
@joelostblom As is, the code crashes on exquisite filesystems that have strange date values. On my case it crashed when browsing an Android phone through MTP:
```python
Current file: '/media/phone'
Traceback (most recent call last):
  […]
  File "/home/dllud/.config/ranger/plugins/size_human_mtime.py", line 17, in infostring
    file_date = datetime.fromtimestamp(fobj.stat.st_mtime)
ValueError: year 4448988 is out of range
```

As a quick fix I surrounded `fromtimestamp` with a try-except:
```python
 try:
    file_date = datetime.fromtimestamp(fobj.stat.st_mtime)
except ValueError:
    return '?'
```

**Comment by toonn** [comment]
Let's at least pass the date through unaltered if parsing fails.

**Comment by joelostblom** [comment]
@toonn @Vifon Thanks for the feedback! Do you want me to submit a PR? If so, should I just append the two linemode classes to `ranger/ranger/core/linemode.py`?

> Thumbs up for the alternative date format but why are you manipulating dates (and leap years!) by hand

@Vifon The answer to that might very well be "because I don't know any better"... =) But just to clarify, what exactly are you referring to? I need the multiple if statements to figure out the age of a file and which date string to pass to `strftime`. Is there a better way of doing this?

@dllud I don't think what you describe is an issue with the linemode I suggested here. The included `mtime` linemode uses the `datetime.fromtimestamp` [in the same way as I do](https://github.com/ranger/ranger/blob/325f41e6a841ab1413020b9d2d86c3922d90f407/ranger/core/linemode.py#L120). Did you try with the included `mtime` linemode without experiencing the error? I tested mounting my phone with `aft-mtp-mount ~/mtp-test` (with the `android-file-transfer` package) and the mtimes showed up as expected with my `human_mtime` linemode.

**Comment by toonn** [comment]
Yes, a PR would be good. Code reviews would be an easier way for vifon to show exactly what he means : )

**Comment by dllud** [comment]
@joelostblom You are right on spot. The included `mtime` also breaks when displaying that directory. I am using `jmtpfs`. The first directory it shows under the mount point, named `Internal storage`, has this strange date value.
I am opening a bug report with `jmtpfs`.
There are already opened issues for ranger that are related: #1020 and #1180

**Comment by rightaway** [comment]
I wouldn't make this the default. It's unexpected and different from `ls` output which people are used to.

If this is offered as an option please include the ability to customize the time style in the config file, just like `ls` takes a very useful `--time-style` argument.

I would be using full ISO date format with seconds and timezone as well. It's important for me to see seconds because if I'm modifying something from an application I want to see if it was changed on this run or the previous one maybe 20 seconds earlier, which I can't tell from ranger right now.

**Comment by toonn** [comment]
@rightaway, this was already merged. Not becoming the default. Not customizable yet either. You could implement your own linemode though, and then possibly contribute it back : )

**Comment by rightaway** [comment]
I can try, could you direct me to where in the code the time is being configured currently and I could try to figure out how to make this linemode.

**Comment by toonn** [comment]
Not sure what you mean by time being configured? I'd suggest looking at the diff of the PR that implemented this to see how to implement a linemode.
