### ISSUE TITLE
Preview not working for text or images

### ISSUE THREAD

**Issue by dabforamerica** [ranger/ranger#1369]
#### Runtime Environment

- Operating system and version: Linux Mint 19
- Terminal emulator and version: XFCE terminal 4
- Python version: 2.7.15rc1 (I think)
- Ranger version/commit: 1.8.1-0.2
- Locale: US.UTF-8

#### Current Behavior
Won't preview text or images
#### Expected Behavior
Previewing text and images
#### Context

I just installed Linux Mint and ranger on my work computer, and I cannot get the preview to work at all! I have checked the settings, purged and reinstalled, and it just won't turn on. 
#### Steps to reproduce
1.  ranger
2.  go to any file and look in the preview area

**Comment by dabforamerica** [comment]
I needed to update python-chardet

**Comment by toonn** [comment]
That's strange because chardet is an optional dependency.
Did you remember to enable previews? `preview_files`, `preview_images`, `use_preview_script`...

**Comment by dabforamerica** [comment]
@toonn I was wrong. I must have done something else that made it start working. Furthermore, only images are now previewed. Text and other text-based files are not being previewed. Any ideas?

**Comment by toonn** [comment]
Hmm, weird. Is `preview_files = True`? Are the files in a weird encoding maybe?
Oh, just noticed you're running 1.8.1, I don't think chardet was an optional dependency back then, not a dependency at all afaik.

**Comment by toonn** [comment]
No idea really. Unless there's something wonky with the encoding or mimetype detection, check the mimetype with `file`, not sure about a tool to get the encoding.

**Comment by Vifon** [comment]
> There's various shortcuts to toggle previews, like zi, so it's easy enough to enable them temporarily for root.

I believe meant <kbd>zp</kbd>, not <kbd>zi</kbd> which toggles the images previews and still needs <kbd>zp</kbd> to work.

**Comment by reallyohwell** [comment]
You are so right. I never needed to use zp when I was non-root. Is there any way to make it remember this setting between invocations? As root, ranger forgets when I quit.
Thanks.

**Comment by toonn** [comment]
Nope. And that's on purpose. If you want to expose yourself to the risk you're big enough to maintain your own patchset for ranger.

**Comment by betheev** [comment]
I just experienced the same problem in a docker container based on Ubuntu 18.04. Installing 'file' solved the problem for me:

`sudo apt install file`

**Comment by toonn** [comment]
I think betheev is onto the real problem here. Closing as solved.
