### ISSUE TITLE
Trying to preview videos crashes ranger

### ISSUE THREAD

**Issue by catzybluphish** [ranger/ranger#1370]
#### Runtime Environment

- Operating system and version: Arch
- Terminal emulator and version: urxvt 9.22
- Python version: 3.7.1
- Ranger version/commit: 1.9.1
- Locale: en_US.UTF-8

#### Current Behavior
When I skim over jpg, png, mp4, etc. files, ranger will crash and output:
![2018-11-04-202629_960x1060_scrot](https://user-images.githubusercontent.com/40843060/47962952-09318780-e070-11e8-9472-9ec214e7762a.png)

#### Expected Behavior
Be able to view video previews but highlighting over said files will crash ranger.
#### Possible solutions
Commenting back the video rule in handle_image fixes crashing but still cannot preview videos.
#### Steps to reproduce
1. Already had w3m installed for image previews that worked.
2. ranger --copy-config=scope to generate scope.sh in ~/.config/ranger
3. Uncommented the video rule in scope.sh shown below
![2018-11-04-203329_960x1060_scrot](https://user-images.githubusercontent.com/40843060/47962993-f075a180-e070-11e8-9ca5-1555c0269092.png)
4. set preview_script ~/.config/ranger/scope.sh
5. Installed ffmpegthumbnailer

**Comment by toonn** [comment]
This was fixed in #1091, it's in the latest release but arch hasn't picked it up yet I believe. You could install ranger-git from the AUR to get the fix. Or use the nix package manager which has 1.9.2 too.
