### ISSUE TITLE
Change bash prompt when using the shell (with "S") inside Ranger

### ISSUE THREAD

**Issue by mrbig033** [ranger/ranger#1374]
I saw this tip a while ago, about how to make the bash prompt change when I'm using it from Ranger, so I can differentiate it from my other sessions/terminal emulators. But I cannot find it again anywhere. Can someone point in me the right direction?

**Comment by nvllsvm** [comment]
The `RANGER_LEVEL` variable is set when in a shell spawned by ranger. You can use its existence to customize your prompt.

Add something like this to your `.bashrc` to prefix your prompt with `[ranger]` when in a ranger-spawned shell.
```
if [ -n "$RANGER_LEVEL" ]; then export PS1="[ranger]$PS1"; fi
```

**Comment by toonn** [comment]
Someone should add this to our wiki.

**Comment by mrbig033** [comment]
It works, thanks! This really should go to the wiki...

**Comment by nvllsvm** [comment]
Added to https://github.com/ranger/ranger/wiki/Common-Changes
