### ISSUE TITLE
Color scheme settings

### ISSUE THREAD

**Issue by nkh** [ranger/ranger#1375]
Hi, I run KDE/Konsole with color scheme "linux color" which had a slight grey background that I like because it lowers the contrast and is easier on the eyes.

This has the unfortunate effect of making selection close to unreadable in ranger. Had I chosen the black background it would look clear and crisp.

I have copied a color scheme in .config/ranger/colorschemes/myscheme.py and in ranger console run "set coloscheme nadim".

I don't get any change, I am probably not changing the right variables; there is no documentation about which one is the selection bar, AFAIK, any tips?

![screenshot_20181115_175839](https://user-images.githubusercontent.com/45409/48569779-ebcbab80-e902-11e8-839f-14e5b3355848.png)

**Comment by toonn** [comment]
I'm pretty sure you can use any color you want, look at the solarized colorscheme for examples.

It's in the works: https://github.com/ranger/colorschemes/pull/2

**Comment by StreetStrider** [comment]
Hello. Is it possible to make ranger aware of light terminal with a single switch? I don't want to invest into building fully-fledged theme for the moment.

Basically, everything looks good except for the right pane, where file contents reside. It has like white-on-white look in a lot of file types if terminal is light themed.

**Comment by Pastells** [comment]
> Hello. Is it possible to make ranger aware of light terminal with a single switch? I don't want to invest into building fully-fledged theme for the moment.
> 
> Basically, everything looks good except for the right pane, where file contents reside. It has like white-on-white look in a lot of file types if terminal is light themed.
> 
> ![изображение](https://github.com/ranger/ranger/assets/2124761/73ea0486-785f-48d3-89a9-3794c07521d0)

Did you figure this out? I'm having the same problem

**Comment by toonn** [comment]
Those colors aren't generated by Ranger. Ranger executes `scope.sh` and that uses one of hilight, pygmentize or bat IIRC. So whichever one of those that your Ranger ends up using would need to do the theme detection.
