### ISSUE TITLE
"preview" is not working for any file type

### ISSUE THREAD

**Issue by GabrielTrettel** [ranger/ranger#1376]
#### Runtime Environment

- Operating system and version: 4.19.1-1-MANJARO  (I3WM)
- Terminal emulator and version: Konsole 18.08.3 and urxvt v9.22
- Python version: 3.7.1
- Ranger version/commit:  (master) 1.9.2
- Locale: pt_BR.UTF-8

#### Current Behavior
In preview window, there is a message when a try to view images and text files 
```
----- File Type Classification -----
```
#### Expected Behavior
Open the correct preview format

#### Context
First of all i tried to run in konsole with w3m, wich failed, so i moved up to urxvt  (rxvt-unicode-pixbuf) to see if things change. But the message keeps as the same. In rc.conf i set preview_images to true.
![ranger](https://user-images.githubusercontent.com/39503038/48656756-764e0100-ea10-11e8-9612-0f3a1e4f7933.png)
The result is equal trying to open images

#### Possible Solutions
Have no idea

#### Steps to reproduce
1. Open ranger
2. Try to preview something 

#### Traceback
Nothing throws errors

**Comment by GabrielTrettel** [comment]
Yes, i have a `scope.sh` by run `ranger --copy-config=scope`yesterday of a recent manual installation by a github clone.

Files are [here](https://gist.github.com/GabrielTrettel/9e715b53ce5cb1a2bf8406de8be4443b)

**Comment by toonn** [comment]
That `--copy-config=scope` is no longer necessary, nor recommended. Your `rc.conf` doesn't use it anyway so I think you can just remove it.

Do you get this on all txt files? Normally those bypass `scope.sh` so this is baffling tbh.

**Comment by GabrielTrettel** [comment]
Ok, scope.sh removed.

I get this error in images and all text/code files, like py, c, cpp, js and so on. But not everything is broken, compressed files show in the preview all your files.

**Comment by toonn** [comment]
Is `w3mimgdisplay` in a non-standard place on your system? Do you not get previews for any `.txt` files?

**Comment by toonn** [comment]
Weirder and weirder. Recent rangers don't need a scope in `.config` and you didn't have one set in `rc.conf`. Are you sure you're running a recent version? What does `ranger --version` report?

**Comment by GabrielTrettel** [comment]
report 
```
ranger version: ranger-master 1.9.2
Python version: 3.7.1 (default, Oct 22 2018, 10:41:28) [GCC 8.2.1 20180831]
Locale: en_US.UTF-8
```

**Comment by Vifon** [comment]
I seem to recall that Manjaro i3wm Edition ships with a really strange ranger config by default. Can you try with the real ranger defaults?

**Comment by toonn** [comment]
Wouldn't `-c` just run the patched configs, @Vifon?

**Comment by Vifon** [comment]
Hopefully not, I think they are patched only in the user's home and possibly /etc

**Comment by GabrielTrettel** [comment]
Running `ranger -c` opens ranger, but broken same as before.

**Comment by Vifon** [comment]
Can you to reproduce it on a LiveUSB?

**Comment by toonn** [comment]
@Vifon, if `--copy-config` leads to messed up `rc.conf` then they patch the configs included with ranger.

**Comment by Vifon** [comment]
Good point.

**Comment by GabrielTrettel** [comment]
Something VERY crazy is happening in my pc.

I ran the latest Manjaro KDE in a live USB, installed ranger (from Arch repository) and w3m, as @Vifon request, and, _voilà,_ everything was working beautifully; code files and images showing their content in the preview as supposed.

After this experiment with Live USB, I switched to my HD and deleted all ranger files manually and reinstalled it from arch repositories and the error message appears again. ABSOLUTELY TRIGGERED

I have no clue how to solve it nor the problem that causes this error, but I have a bet that the problem is with some 3rd party software, not with ranger.

As ranger is a program that I use a lot, probably weekend I will reinstall my system just to have it working back, so thanks for attention and patience :)

**Comment by evanescente-ondine** [comment]
Same exact problem here, with version
ranger version: ranger-master 1.9.2
Python version: 2.7.13 (default, Sep 26 2018, 18:42:22) [GCC 6.3.0 20170516]
Locale: None.None
And debian: Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
I just wiped it and compiled it anew (had version 1.7 before, from debian repository).

**Comment by Vifon** [comment]
Did you wipe the configs as well, @evanescente-ondine?

@GabrielTrettel, could you tar the contents of your ~/.config/ranger and upload them somewhere? Be sure to wipe any sensitive information beforehand. I'd like take a look at it if that's not too much trouble for you.

**Comment by GabrielTrettel** [comment]
@Vifon, sure. [https://up1.secretalgorithm.com/#aP9QFdt6DfCHM6dN9bZA2Q](url)

**Comment by Vifon** [comment]
Thanks! I don't see anything suspicious there. I tried loading this config and it works just fine here. Your assumption seems to be correct: it's something outside of ranger interfering. I'm still curious what it might be but debugging it on your system isn't really viable.

**Comment by Vifon** [comment]
If you're still going to wipe your system, tell us if it helped.

**Comment by GabrielTrettel** [comment]
I think something in the last Manjaro update, that was last week, broke the system. I noticed now that [bumblebee-status](https://github.com/tobi-wan-kenobi/bumblebee-status) is also behaving strange, since when I try to change brightness or volume with scroll's mouse nothing happens. And now when I try to install any program, pacman show this error and the program install correctly. ¯\_(ツ)_/¯

```
ldconfig: File /usr/lib/libmagic.so.1.0.0 is empty, not checked.
ldconfig: File /usr/lib/libkioarchive.so.5.97.0 is empty, not checked.
ldconfig: File /usr/lib/libmolletnetwork5.so.18 is empty, not checked.
ldconfig: File /usr/lib/libkioarchive.so.5 is empty, not checked.
ldconfig: File /usr/lib/libmagic.so is empty, not checked.
ldconfig: File /usr/lib/libmagic.so.1 is empty, not checked.
ldconfig: File /usr/lib/libmolletnetwork5.so.18.08.3 is empty, not checked.
```
So, when I reinstall my OS I will come back to say if it helped. But, if you have any suggestion I can try until there.

**Comment by Vifon** [comment]
So the ol' good dumpster fire. Might be fun to debug but I cannot really suggest anything specific remotely.

**Comment by evanescente-ondine** [comment]
I did purge the configuration, of course.
Here's my own, if that can be of any use: commands.py https://pastebin.com/k42jN15B
commands_full.py https://pastebin.com/YeF5MfwD
rc.conf https://pastebin.com/HcSwtz6p
rifle.conf https://pastebin.com/49yZTC2N
scope.sh https://pastebin.com/HU0NU82r

If that is of any use.

**Comment by toonn** [comment]
This happening on different distros with different python versions but the same ranger versions is worrisome tbh.

@evanescente-ondine, did you update anything but ranger? And do you get different results if you checkout other releases, try `v1.9.1` and `v1.7.2` for example. Actually, doing a git-bisect would be rather helpful, going back all the way to whatever version you had installed previously. Are you interested in doing this?

**Comment by evanescente-ondine** [comment]
> did you update anything but ranger?
Don't know. I'm in to help you, but I don't know how to. I know that my version is buggy, but I have no experience for git. What I see, is that: 1) the last **stable** (from debian repository) version doesn't work (1.7.2), neither that last one from git,
but: w3m -o ext_image_viewer=0 Images.jpg doesn't work either. The terminal gets empty with still w3m being called, I can see that, but apart from the title and "status bar", nothing.
The version of w3m is :
w3m version w3m/0.5.3+git20170102, options lang=en,m17n,image,color,ansi-color,mouse,gpm,menu,cookie,ssl,ssl-verify,external-uri-loader,w3mmailer,nntp,gopher,ipv6,alarm,mark,migemo
Whereas the debian package information is:
apt-cache show w3m-img
Package: w3m-img
Source: w3m
Version: 0.5.3-34+deb9u1
Installed-Size: 165

I suggest you people try with these.

**Comment by toonn** [comment]
@evanescente-ondine, is it only failing for image previews? How about plain text previews, pdf previews, other previews?

**Comment by evanescente-ondine** [comment]
It shows additional informations about archives, preview correctly pdf
(made into text) and text files.

Le mar. 20 nov. 2018 à 17:42, Toon Nolten <notifications@github.com> a
écrit :

**Comment by toonn** [comment]
@evanescente-ondine, ok, then it sounds like you have a completely different issue. If you use urxvt, kitty or terminology, switch to their respective `preview_images_method`. The w3m method is fairly fragile and only works with terminals that are sufficiently like xterm.

**Comment by GabrielTrettel** [comment]
Just for feedback... I reinstalled Manjaro I3 and everything goes back to work. @toonn  and @Vifon, thanks for helping and supporting :)

**Comment by Vifon** [comment]
Still concerning but I'm happy it's working for you now.
