### ISSUE TITLE
rifle type "application/octet-stream" mismatch

### ISSUE THREAD

**Issue by sharethewisdom** [ranger/ranger#1377]
In rifle.conf I have the following rule:
```
env WAYLAND_DISPLAY, !ext exe, mime octet-stream$, has gpg, flag t = () { rifle -f F "$1" } =(gpg -dq "$1")
```

The issue is that it seems that rifle's tests identify ~~a symlink~~ *(edit: certain files)* wrongly as of the mimetype application/octet-stream, for which I can't define an `!ext` exception.

-----

*background:*

I have a tmux setup. Sorry for not making this more minimal as this is irrelevant to the problem.

The above rule decrypts a file to a temporary file using zsh: it opens a pane in the session on the tmux server $USER where the ncurses pinentry program is displayed; then the decrypted file is passed to rifle again. When the process using the file ends, zsh removes the file from memory. This is my `$TERMCMD`:

```
#!/usr/bin/env zsh
# this file is
# TERMCMD=/usr/local/bin/zrangertmux
[[ $1 == -e ]] && shift
# for some reason, rifle does note honor my $SHELL
[[ $1 == /bin/sh ]] && shift && set -- /bin/zsh "$@"
# this is just to prevent multiple panes for some commands
killpane=true
if [[ -n $3 ]]; then
  case "${3#*; }" in
    *tesseract*) lines=2;;
    *ffprobe*)   lines=2;;
    *mpv*)  lines=3;;
    *melt*) lines=7;;
    *make*)    killpane=false; lines=20;;
    *xelatex*) killpane=false; lines=20;;
    *latexmk*) killpane=false; lines=20;;
    *gpg*)     killpane=false; lines=20;;
    *)      lines=12;;
  esac
fi
# kill all panes except the one ranger is running in
$killpane && tmux kill-pane -a -t ranger
tmux -L $USER -f ~/.config/tmux/tmux.conf split-window -c "~${${3%\';*}#*/home/$USER}" -l${lines} "$@"
$killpane && tmux select-pane -l
```

*version information:*

`uname -a`
```
Linux libreboot 4.19.2-arch1-1-ARCH #1 SMP PREEMPT Tue Nov 13 21:16:19 UTC 2018 x86_64 GNU/Linux
```

`ranger --version`
```
ranger version: ranger-master 1.9.1
Python version: 3.7.1 (default, Oct 22 2018, 10:41:28) [GCC 8.2.1 20180831]
Locale: en_US.UTF-8
```

rifle 1.9.1

**Comment by toonn** [comment]
Hmm, not sure what's happening here. The mime type guessed for symlinks is `None` for me.
@Vifon, how about determining mime type using mimetypes, then calling file(1) if that fails?

**Comment by sharethewisdom** [comment]
ok, I may not have been thorough in my findings.

Them being symlinks may be coincidental. It's a little weird. I don't have *arbitrary binary data* in my `.zshrc` file, for example, yet it gets to be
```
$ xdg-mime query filetype ~/.config/zsh/.zshrc
application/octet-stream
```

I'll look into it further.

**Comment by toonn** [comment]
The mimetypes library goes entirely by extension afaik so it won't give the same result as file(1) or xdg-mime for example.

**Comment by Vifon** [comment]
> @Vifon, how about determining mime type using mimetypes, then calling file(1) if that fails?

Sounds fine to me.

**Comment by toonn** [comment]
While this will increase our coverage, I don't think this will solve @sharethewisdom's problem completely though. Files that are misidentified by mimetypes rn, would still be after this change.

**Comment by sharethewisdom** [comment]
never mind, my problem is too localized. I solved it by creating the file `~/.magic` with this content: 
```
0 string # zshrc
!:mime text/x-script.zsh
```
which works fine.

**Comment by toonn** [comment]
If it's solved for you then you can close this. We have ongoing discussion about mime type detection.
Maybe you can use a `#!` string for the detection instead?
