### ISSUE TITLE
Preview json data

### ISSUE THREAD

**Issue by rightaway** [ranger/ranger#1383]
When I'm looking at a .json file or .js whose content is data I get

```
----- File Type Classification -----
JSON data
```

Instead of actually showing a preview. Could `jq` be used as the default previewer since it pretty prints JSON very nicely.

**Comment by Vifon** [comment]
We could also use `python -mjson.tool` since we definitely already have Python. I'll get around to it a bit later.

**Comment by toonn** [comment]
Hmm, what is JSON data? `.js` files are just previewed as plain text for me.

**Comment by rightaway** [comment]
I think `jq` should be included as a check first like the rest of that file which tries various tools, since if someone has that installed are probably using that for json viewing anyway and would prefer that be used.

**Comment by Vifon** [comment]
Very good point, @rightaway.

**Comment by toonn** [comment]
Let's take the rifle approach? Default to jq if it's there, otherwise `json.tool`? Although I might want to turn it off : /, just plain text preview of some `.js` files I have takes aaaaaaages.

**Comment by Vifon** [comment]
We could preview `*.json` with `jq` and `*.js` with `highlight`.

**Comment by toonn** [comment]
`js` isn't considered a programming language yet? And what happened to `json.tool`?

**Comment by friederbluemle** [comment]
Sorry if I missed it, but how do I simply display the contents of a `json` file on the right side of ranger?
Right now, just like OP mentioned, it's just displaying:
```
----- File Type Classification -----
JSON data
```
Which is not very useful.

**Comment by toonn** [comment]
You'll have to run the master branch to get this fix. Also, not have a `scope.sh` in `~/.config/ranger`.

**Comment by Qinusty** [comment]
I'm currently running the master version of ranger (d21f60f2a3c4a15e5b0346d28667409fd920417e), Still seeing this in some circumstances.

This appears to be occuring on smaller json files (200-500 B). I am able to preview a 24.7 K json file.

**Comment by toonn** [comment]
Maybe the mime type's off? What does `file --mime-type jsonfiles` report?

**Comment by friederbluemle** [comment]
Is there any chance we could get a new release from master? I have the latest version of ranger installed `1.9.2`, it's over a year old, and the json viewing problem still exists.. Thanks!

**Comment by rightaway** [comment]
@friederbluemle You can request this in https://github.com/ranger/ranger/issues/1521.

**Comment by Vifon** [comment]
@friederbluemle We're working on it though I cannot give you any timeline at this time.

**Comment by pnchinmay** [comment]
Hey @vifon 
Was this feature released ?

**Comment by toonn** [comment]
This is still only on the master branch. But it's a change to `scope.sh` so you could also download just that file and then change the `preview_script` setting in `rc.conf`.

Running Ranger from the master branch would be appreciated though. More testing is always useful.

**Comment by toonn** [comment]
@pnchinmay, there wouldn't be a mention in `rc.conf`, it would be in `scope.sh`. My instructions would be for using a newer `scope.sh` with an older Ranger.

**Comment by pnchinmay** [comment]
> @pnchinmay, there wouldn't be a mention in `rc.conf`, it would be in `scope.sh`. My instructions would be for using a newer `scope.sh` with an older Ranger.

Yeah
I'm using version 1.9.3, released in 2019 with customized scope.sh.
