### ISSUE TITLE
map directory containing space

### ISSUE THREAD

**Issue by j-degreef** [ranger/ranger#1392]
Hi,

I might be missing something but I'm trying to map a directory with spaces without success : 
example : map gT cd /home/me/my dir with spaces/
It works with bookmark (' /home/me/my dir with spaces/).
I've tried escaping the path, using quotes and double quotes without success.
I've searched the issues but apparently it has not been reported. #146 is talking about space in map command but it's not related to directories...

- Operating system and version: Arch Linux up to date
- Terminal emulator and version: termite v14
- Python version: Python 3.7.1
- Ranger version/commit: master up to date
- Locale: LANG=en_US.utf8

#### Current Behavior
map gT cd /home/me/my dir with spaces/
end up with "Command not found /home/me/my"

#### Expected Behavior
gT changes to /home/me/my dir with spaces/

Thanks for any help.

**Comment by toonn** [comment]
I can't reproduce this, both `:cd ~/dir with spaces` and `map gT cd ~/dir with spaces` work fine for me. Are you sure you didn't use `shell cd`?

**Comment by j-degreef** [comment]
Shame on me, you're right, it's working ok.
I don't know how I manage to create this problem. It would have been better for me to go to sleep instead of testing that night :-/
You can close this one.
Btw, I think I have discovered 2 other problems with "dir with spaces" (with tab_new and shell cp) but this time I'll double check before creating an issue.
