### ISSUE TITLE
Open File in Another Terminal

### ISSUE THREAD

**Issue by Neur1n** [ranger/ranger#1393]
#### Runtime Environment

- Operating system and version: Ubuntu 16.04
- Terminal emulator and version: Bash 4.3.48(1)
- Python version: 3.5
- Ranger version/commit: ranger-master 1.9.2
- Locale: 

#### Current Behavior
When using `:open_with nvim` (i.e. using neovim) the file is opened in the current terminal which "hides" ranger. I know this is normal, but when neovim is invoked by `Super + (type in) nvim`, it pops up as a new terminal.

#### Expected Behavior
So I am wondering if I can open a file with neovim in a new terminal.

#### Context
I have tried to add `has nvim, flag f = gnome-terminal nvim "$@"` to rifle.conf, but all it does is opening a new empty terminal. And I could not find anything useful over the internet. Any help is much appreciated.

**Comment by toonn** [comment]
I think `gnome-terminal -- nvim -- "$@"` might work, otherwise gnome-terminal tries to interpret the command as options. However, if you replace `flag f` with `flag t` and drop the gnome-terminal it might Just Work™, if it doesn't, try setting `TERMCMD=gnome-terminal`.

**Comment by Neur1n** [comment]
Awesome! `gnome-terminal -- nvim -- "$@"` works for me. And using `flag t` also works but invokes XTerm instead. Thanks.

**Comment by toonn** [comment]
Yep, I'm currently rejiggering `flag t` behavior, in the future it will possibly maybe work out of the box somehow if I can hold on to my sanity for long enough.

**Comment by Neur1n** [comment]
Hello, there is a little follow up question: it seems that putting that single `has nvim ...` line in `~/.config/ranger/rifle.conf` is a bad practice. I have read the [configuration files](https://github.com/ranger/ranger/wiki/Official-user-guide#configuration-files) of the wiki, so does it mean that I'd better put some customized key mappings in `rc.conf` but have a full copy of the default `rifle.conf` then change some configurations in it? Thanks.

**Comment by Vifon** [comment]
Now that you mention it, it seems `rifle` doesn't load the global configuration if you have a local one. So yes, you need a full copy.

I'm not sure whether to consider it a bug as the order of rules might get tricky if both config files were read. We should mention it in the manpage more clearly though. Good find!

**Comment by toonn** [comment]
Yeah, that's not a bug. Priority is too hard with multiple configs.

**Comment by DrDonkey** [comment]
I have terminator and vim. Tried to replicate the above but failed.
edited the line to `!mime ^text, label editor, ext xml|json|csv|tex|py|pl|rb|js|sh|php = terminator -e vim "@$"`.
When I use `--` it says invalid arguments for terminator.
As a result I am here for help.

**Comment by toonn** [comment]
@DrDonkey, you might wanna try `$@` instead ; )
Questions like these are better suited to the irc channel, you'd usually get a quicker response.
