### ISSUE TITLE
Is it possible to use ranger key-bindings with any keyboard layout?

### ISSUE THREAD

**Issue by hektr** [ranger/ranger#1398]
For example, now if I switch keyboard to other language, I can't use ranger key-bindings. Is it possible to change this? Thanks

**Comment by Vifon** [comment]
What language is this? Is it using the Latin alphabet?

**Comment by hektr** [comment]
> What language is this? Is it using the Latin alphabet?

no, it's not based on Latin alphabet. It's based on Cyrillic.

**Comment by hektr** [comment]
May be, I can add cyrillic equivalent for latin keys in some file and it will work?

**Comment by Vifon** [comment]
Try and report back whether it worked. :) I don't see any other way as you're clearly not sending the keys ranger expects from its perspective.

**Comment by hektr** [comment]
I can only add `copymap` in rc.conf. But it's not good solution, because I need to write `copymap` for every single key separately. It will add too much extra lines. Is there something like `copymap`, but working with a lot of keys at once??

I'll explain it below.
Now, I should write
`copymap h р`
`copymap j о`
`copymap k л`
`copymap l д`

is there some command for writing it like this `newmap hjkl ролд` ?

**Comment by hektr** [comment]
but, it's handy for mapping multiple languages, I'll do that for arabic and russian ^_^

**Comment by toonn** [comment]
Someone recently developed a plugin for this: https://github.com/mrgoodvin/ranger_keybord
Configuration in the style of `russian-jcukenwin.vim` could work as well and would be accepted into the main repo.
