### ISSUE TITLE
Keep focus on ranger when opening a document

### ISSUE THREAD

**Issue by Ierezell** [ranger/ranger#1400]
#### Runtime Environment
- Operating system and version: -- OS: Arch Linux x86_64
                                -- Kernel Release: 4.19.4-arch1-1-ARCH
                                -- WM: i3
                                -- DE: KDE
- Terminal emulator and version: xterm-termite
- ranger version: ranger 1.9.2
- Python version: 3.7.1 (default, Oct 22 2018, 10:41:28) [GCC 8.2.1 20180831]
- Locale: fr_FR.UTF-8

#### Current Behavior
Focus on new opened file (with any application)

#### Expected Behavior
Open window with new file but keep focus on ranger

#### Possible Solutions
Get some config done in the i3 config but it's just a patch

#### Steps to reproduce
1. open ranger
2. go to some file (pdf with zathura for exemple) 
3. open it pressing "l" on the keyboard

I know it's really small and stupid improvement but could save lots of time. 

Ps : Perhaps i'm just stupid and cannot edit the config to get the desired behaviour.. but at least I will have an answer here

**Comment by toonn** [comment]
Hmm, focus is usually the job of the window manager afaik. I'm not sure how we can hint to "open in background" or similar.

**Comment by Vifon** [comment]
Agreed. You'll need to make your window manager behave like this.

**Comment by toonn** [comment]
@Vifon, so there's no hints we can provide X11 or something? I guess first of all the terminal would have to support passing them from scripts to X.

**Comment by Ierezell** [comment]
Thanks for your answers, I was thinking the same but it worth a try. 
If I fix it correctly I can send a Pull request if you like (i3 and X)

**Comment by Vifon** [comment]
@toonn, I don't know about any hints portable across the window managers. And yes, the terminal would need to support it.

@Ierezell, I believe it might be slightly related to the problem I encountered in my other project, [TrayCalendar](https://github.com/Vifon/TrayCalendar). Take a look at its readme, maybe it'll be helpful.
