### ISSUE TITLE
How to Extract/Compress archive files?

### ISSUE THREAD

**Issue by LinArcX** [ranger/ranger#1402]
#### Runtime Environment

- Operating system and version: Arch
- Terminal emulator and version: Konsole
- Python version: 
- Ranger version/commit: 
- Locale: 

I don't know how to exrtact or compress archive files. i read the manuals, other issues and also ask this question in reddit. but no answer. can anyone clear me how to do that?

**Comment by LinArcX** [comment]
Ok, i find it. but i don't know why its not documented yet. please add it to doc file.
You just hover over an .zip, .rar etc and hit: __1l__.
That's it :) whitout any external commands.

**Comment by toonn** [comment]
I think it would require atool at least. Or maybe the avfs stuff @Vifon played with'd work?
You could always just mark stuff then `:shell zip -rf 'file.zip' %s`, I guess. And you could map that/something like that.

**Comment by LinArcX** [comment]
Thanks @tonttu . i follow the arch wiki documantations and everything is now works.

**Comment by toonn** [comment]
@DrDonkey, TIL, thank you. Apparently vim is actually capable of browsing zip archives, editing files within them (press return on a file to edit and save it as usual with `:w`) and extracting them (press `x` and the highlighted file will be extracted). Check out `:h zip` for the docs.

Or did you want to know how to set it up to not open in vim?

**Comment by AffanIndo** [comment]
For me, **1l** will extract it, **2l** will show "open with" dialogue, and **3l** will open it in Vim. What are these things? why is it not in documentation?

**Comment by toonn** [comment]
Don't understand the question. Do you mean why `1/2/3l` does something? It's just a vim idiom. The number changes the behavior of the `l` movement. In this case opening the file with the according item from the open_with menu you get when you press `r`, So `1l` should be equivalent to `r1`, `2l` == `r2` etc.

**Comment by AffanIndo** [comment]
Oh, alright, now I understand. I see this "tricks" everywhere, but I can't find it on the manual, so I thought it was some undocumented feature or something. After reading your comment, apparently it's written on Rifle section, thanks.

**Comment by Zeioth** [comment]
How can you remap the behavior of l3 to other key?

**Comment by toonn** [comment]
I don't understand the question. Sounds like its more appropriate for the irc channel than the issue tracker though.

**Comment by acampove** [comment]
> Ok, i found it. but i don't know why its not documented yet. please add it to doc. You just hover over an .zip, .rar etc and hit: **1l**. That's it :) whitout any external commands.

Could you please add the answer to the issue whenever you find it so that people like me can also find it?
