### ISSUE TITLE
Access contents of: mtp:/// and trash:/// inside ranger.

### ISSUE THREAD

**Issue by LinArcX** [ranger/ranger#1403]
Hi. i look for an approach to show the contents of: mtp:///, trash://, network:///, etc.. inside ranger not in the terminal. i know we can use gio to access these locations, but you know i want similar functionality that exists in nemo file manager. every time you plug your android device, you can open mtp:/// and access your files. any idea?

**Comment by mbirth** [comment]
Access to MTP can be achieved using mtpfs, jmtpfs or go-mtpfs. There are even scripts [floating around](http://bernaerts.dyndns.org/linux/74-ubuntu/268-ubuntu-automount-any-mtp-device) that allow you to setup automounting of MTP devices.

**Comment by LinArcX** [comment]
Thanks @mbirth . but it does not work. i simple put these two lines in rc.conf:
```
map bm  shell aft-mtp-mount ~/myDevice/                                                                                                          
map bu  shell sudo umount ~/myDevice/ 
````
and its works like a charm. :)
Tip: you have to install android-file-transfer package.
