### ISSUE TITLE
open directories in ranger.

### ISSUE THREAD

**Issue by LinArcX** [ranger/ranger#1411]
Hi. i created these little scripts to nagivate from nemo file manager to terminal emulator:
https://github.com/LinArcX/TmuxFT/blob/master/TmuxFTDir.nemo_action
After switching to ranger as my default file browser, i'm curious how to do the same thing with ranger. imagine, you are in qt-browser IDE. you click the __show containing folder__ button and it search the  [mimeapps.list](https://wiki.archlinux.org/index.php/XDG_MIME_Applications#mimeapps.list)  file to see how you map inode directory.
I want to replace __nemo.desktop__ with a custom script to naviagate automatically between any gui-based application and ranger. My idea is:
1. get the url.
2. use the xdotool(for fake keyboard actions) and wmctrl(to change the focus and find ranger window) 
 and create new tab in ranger.
3. and load that address into this tab.
But i don't know how to run xdotool after ranger open. any idea?

**Comment by toonn** [comment]
Ranger has an api you could probably use for this. It's probably not very well documented though. Either way I think writing a `.desktop` file that executes something like `xterm -e ranger /paths/to/files...` would be much easier.

**Comment by LinArcX** [comment]
Ok. i finnaly find the way:)
Look at the solution:
https://github.com/LinArcX/Blogit/blob/master/Packages/Ranger/ranger.md

**Comment by Hukuta** [comment]
> Ok. i finnaly find the way:)
> Look at the solution:
> https://github.com/LinArcX/Blogit/blob/master/Packages/Ranger/ranger.md

404. Looking for solution.

**Comment by toonn** [comment]
Fwiw, I think they created a .desktop file. You can look at the debian package for an example.

**Comment by Hukuta** [comment]
I went the same way, created a desktop file, tried different options and parameters.  It runs ok directly, but if you use a function from ide, then the terminal is closed immediately after opening.  I was unable to make a working solution on my system.

**Comment by LinArcX** [comment]
### Automatically grap inode/directory and open it in ranger
You should do some tricks :) let's get startd:
1. First you have to install some dependencies: __wmctrl__, __xdotool__ and __xdg-util__.(first for jump between windwos and second to emulate keyboard shortcuts and third for set defalut applications)
2. Create a __.desktop__ file. because inode directory look at this files.and put it in the: __~/.local/share/applications__ directory.(i called it: opener.desktop)
3. Put these lines into that file:
```
[Desktop Entry]

Type=Application
Name=opener
Comment=Open Directory In Ranger
Exec=/usr/bin/opener.sh %U
Icon=utilities-terminal
MimeType=inode/directory;
```
4. You see in the __Exec__ part, you have to specify a shell script(all magic function come in this file!)
5. Create opener.sh in __/usr/bin__ directory and set it as executable.(`chmod +x /usr/bin/opener.sh`)
6. Paste These lines into that:
```
#! /bin/bash

wmctrl -a Ranger; sleep 1 && xdotool key Control_L+n && xdotool key Shift+\: && xdotool type cd ${1} && xdotool key Return
```
7. Now you have to update __inode/directory__ value with help of `xdg-mime` application:
`xdg-mime default opener.desktop inode/directory`
8. Sure evertything setup correctly:
`xdg-mime query default inode/directory`
9. Now you can open directories in everywhere exists option like: "Open folder", "Show containg folder", ...
10. Enjoy the automation :)

**Comment by Hukuta** [comment]
I understand your solution, but unfortunately I cannot support it as acceptable in this context. 
Let's strive to be power users ;-)
