### ISSUE TITLE
[Setting suggestion] Exit to command prompt, but stay in the current directory

### ISSUE THREAD

**Issue by mikkovedru** [ranger/ranger#1414]
1. I am in a command prompt and decide to use Ranger for efficiency (browsing, copying files, whatever)
2. I use Ranger, browse around, do whatever it is I need to do.
3. I don't need Ranger any more and I exit.
4. The command prompt "goes" to the original directory instead of "staying" in the same directory I was in. This is how it feels for a user - there is a clear feeling of lost continuity.

I know that it's possible to implement such a feature by writing an alias to system files ( _alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR"'_ ).

But this is a clunky way to achieve a common functionality. It's way too much work to find the solution and to modify system files (not everyone is capable or brave enough to do) for a feature that feels like should be a part of normal Ranger settings. 

Moreover, I propose that "keep the current directory on exit" setting should be turned on by default. It is how a new user assumes the program will behave, IMO.

**Comment by Vifon** [comment]
It cannot be turned on by default as ranger cannot control your shell directly. There is a trick though: you can source the main ranger file with `. ranger` to achieve exactly this behavior. Does it solve it for you?

**Comment by mikkovedru** [comment]
@Vifon 
I solved the problem by editing my .zshrc file in the way I describe above (I found the solution [here](https://superuser.com/questions/1043806/how-to-exit-the-ranger-file-explorer-back-to-command-prompt-but-keep-the-current)).

Why can't Ranger, as its last command, send the shell command "cd /url/user/closed/ranger/in"? Maybe there are some other ways to achieve this functionality? Unfortunately I am incompetent in Linux programming. :-(

**Comment by toonn** [comment]
Hmm, shouldn't we be able to exec cd, @Vifon?

**Comment by Vifon** [comment]
@mikkovedru Because ranger calling `cd ...` would change the cwd of ranger, not of the parent shell. A child process cannot modify the parents environment this way.

@toonn What do you mean?

**Comment by toonn** [comment]
cd isn't always implemented as a shell built-in, is it? If it's not then a program should be able to signal changing the shell's directory, no?

**Comment by Vifon** [comment]
I don't remember any cases of `cd` not being a built-in.

**Comment by Vifon** [comment]
@toonn From my `cd(1p)` manpage:

```
APPLICATION USAGE
       Since cd affects the current shell execution environment,
       it is always provided as a shell regular built-in. If  it
       is  called  in  a  subshell or separate utility execution
       environment, such as one of the following:

           (cd /tmp)
           nohup cd
           find . −exec cd {} \;

       it does not affect the working directory of the  caller's
       environment.

       The  user must have execute (search) permission in direc‐
       tory in order to change to it.
```

**Comment by Vifon** [comment]
Which is more or less exactly what I said before. I'm closing the issue as ranger already does the best it can in this regard (`. ranger` and the `examples/bash_automatic_cd.sh` script).

**Comment by mikkovedru** [comment]
@Vifon. May I suggest something else, that could improve the situation for new users?

New users like myself don't necessarily understand how the Operation System works and why something obvious is not possible to do. Like in this case ("Why is this software not remembering my location? This should be the default behavior! What, and they don't even have such an option in settings?.."), the blame automatically goes to Ranger and its developers. It's not right, but that's how it often goes.

In addition to "I have a problem and I want to fix it", new users also visit settings to find out what the software can offer (I myself find a lot of cool stuff that I didn't even know I wanted).

To solve both of these problems, my suggestion is to add to setting-file a couple of commented lines about the lack this feature. Something like:
> Do you want your terminal shell to automatically go to the directory the Ranger last 
> visited before being closed? Unfortunately Linux doesn't allow us to implement such feature. 
> Please check this link of how to do it:
> https://superuser.com/questions/1043806/how-to-exit-the-ranger-file-explorer-back-to-command-prompt-but-keep-the-current/

Or instead of the link, a search query can be provided: "Search for 'ranger linux exit prompt keep directory' "

**Comment by toonn** [comment]
Hmm, the settings file really doesn't seem like the appropriate place. Maybe we could add something to the manpage though.

**Comment by Vifon** [comment]
I added it to [our wiki](https://github.com/ranger/ranger/wiki/Integration-with-other-programs#changing-directories) for now.
