### ISSUE TITLE
navigate as you type feature similar to nnn 

### ISSUE THREAD

**Issue by PgLoLo** [ranger/ranger#1429]
In a lot of file managers, there is a very convenient function called "navigate as you type" (in nnn file browser for example) or "search as you type" (in тautilus in Ubuntu prior to version 17.10). I can not find this feature in ranger. I think it can be emulated with search and tab, but it is much better to type as many characters as it is needed to select the desired file and to be able to see, is it enough character right now, at the same time.

Is it possible to turn this feature on in ranger, maybe there is a plugin that will do it?

**Comment by Vifon** [comment]
It can be enabled with a right flag to `:scout` which is also used for the `:search`. Try pressing <kbd>f</kbd>, it should be exactly what you're looking for. Take a look at the available `:scout` flags to customize this behavior.

**Comment by toonn** [comment]
`:travel` also sounds like what you might be looking for. But yes, look into scout it's what backs most of rangers searching and moving commands, pretty damn versatile.

**Comment by PgLoLo** [comment]
@Vifon @toonn Thank you very much, it is exactly what I was looking for. Closing the issue.

**Comment by SRGOM** [comment]
@PgLoLo did you manage to get it working?

**Comment by toonn** [comment]
@SRGOM, `:travel` isn't good enough for you?

**Comment by SRGOM** [comment]
I do `:travel` and my command prompt gets autofilled `:scount aefklst`. I was expecting it to be in travel mode so I can start entering chars to match my dirs. 

WHat should I do after the `:scount ...` command appears?

**Comment by toonn** [comment]
Just type parts of directory names.

**Comment by SRGOM** [comment]
Thanks.

I typed `:travel<CR>` which gave me `:scout aefklst<no space>`. I hit space and then this did what I wanted. Any way I could get a hit `enter` to navigate behavior too?

**Comment by SRGOM** [comment]
`wo<enter>pr<enter>m<enter>s<enter>` 

For some reason when I entered this text, github changed it to `woprms` but I'm probably overreaching my welcome now.

Thanks for the answer

**Comment by toonn** [comment]
You can just start typing after `:travel`, no need for enter. You might want to `map <c-t> console travel%space` or another key combination.

It already works the way you describe it, you type to filter, then you can move with arrow keys and/or press enter whenever.

**Comment by ywpkwon** [comment]
It was good to know about the `:travel`! 

I have one question: It seems `:travel` enters a directory automatically when there is no more matching (of course, also when a user hit `enter` key). Can I remove the automatic enterance behavior and ensure to enter a directory only when user hit `enter` key?

**Comment by toonn** [comment]
Yep, `scout`'s pretty flexible : )
