### ISSUE TITLE
Feature request: do not move the cursor when mark/tag a file

### ISSUE THREAD

**Issue by damage220** [ranger/ranger#1430]
#### Current Behavior
When we hit space (t) the file has been marked (tagged) and the cursor has been moved down. It was annoying when I first tried ranger and since then I still cannot get used to it. I found no option in ranger manual. I found out that `<space>` is mapped to `mark_files toggle=True`. I was thinking there could be some flag but I do not see this command neither in commands_full.py nor the manual. `mark %f` does not work (%f is not expanded). `map <space> chain mark_files; move up=1` fails on last file, and it seems there is no conditions in the commands.

#### Expected Behavior
The cursor remains on the selected file.

#### Possible Solutions
Apparently, it can be solved writing custom python command but it would be better to have an option controlling this behavior. Disable cursor movement by default (executing command) and instead move it down in the mapping using chain is also an option.

**Comment by toonn** [comment]
You can `map <space> mark_files toggle=True movedown=False`.

**Comment by damage220** [comment]
I understand why it can be useful but for me it is not intuitive. I had a feeling that the following file the cursor is on after marking/tagging is also marked/tagged, do not know why.

`movedown=False` works well for both `mark_files` and `tag_toggle` commands, thank you. I supposed there should be some flag controlling this behavior but, as I said, I did not find these commands. In case something similar happen to me in future, is there a place where I can see all commands supported by ranger? I checked `~/.config/ranger/samples/commands_full.py` file and there was no `mark_files`.

**Comment by toonn** [comment]
Not really. Had to look at the source myself. Some of the more fundamental commands are in `ranger/core/actions.py`. I usually grep the codebase for `def command_name`, after grepping for `:command_name` which only works for commands in `commands.py` : )

This might deserve a wiki entry tbh. We also never seem to get around to documenting the `Undocumented commands` found at the bottom of `?c`.

**Comment by damage220** [comment]
I think, the source code of an opensource project is not the last place for looking for solution. I should have checked it. Again, thanks. I hope this parameter will not be cut out later)
