### ISSUE TITLE
Cache directory is not created

### ISSUE THREAD

**Issue by Test-224** [ranger/ranger#1435]
#### Runtime Environment

- Operating system and version: Gentoo Linux (kernel: 4.14.52-gentoo)
- Terminal emulator and version: st 0.8.1
- Python version: 3.6.5 (default, Aug 11 2018, 19: 48: 44) [GCC 7.3.0]
- Ranger version / commit: 1.9.2
- Locale: en_US.UTF-8

#### Current Behavior
Cache directory is not created if `preview_images = False`
`preview_images = True` creates a cache directory only when ranger is started

#### Expected Behavior
Always want to create a cache directory

#### Context

I want to display the image in the archive file, but since the cache directory does not exist, image expansion fails.
You can avoid it by checking the cache directory in `scope.sh`.

**Comment by Vifon** [comment]
Good catch, thanks!
