### ISSUE TITLE
Checksec 

### ISSUE THREAD

**Issue by johnsen32** [ranger/ranger#1439]
Running checksec on ranger shows some missing protection features that should be enabled by default

ranger version 1.9.2

# on arch

COMMAND  PID  RELRO      STACK CANARY       SECCOMP	      NX                 PIE                  FORTIFY
ranger   5347 Full RELRO      No canary found      No Seccomp       NX enabled    PIE enabled     No

# on debian testing

COMMAND  PID  RELRO      STACK CANARY       SECCOMP	      NX                 PIE                  FORTIFY     
ranger   5347 Partial RELRO   Canary found          No Seccomp       NX enabled    No PIE            Yes

On Arch ranger is build with:
python setup.py install --root="${pkgdir}" --optimize=1

Source:
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/ranger

Unless explicably disabled, features like  RELRO, Stack Canary, PIE and Fortify Flags should all be enabled by default. Please make sure that all protection features that can be enabled are set when setup.py is run.

**Comment by johnsen32** [comment]
Running the script (https://github.com/slimm609/checksec.sh) with 
"./checksec --proc ranger" while having ranger running.

You can also run "./checksec --proc-all" to list all processes

**Comment by Vifon** [comment]
I'm pretty sure it checks the security of the Python process, ranger itself doesn't have any binary executables, it's either Python or Bash. You may want to report it to the maintainer of the Python package of your distro.

**Comment by toonn** [comment]
I'm pretty sure a python script has zero ways to affect any of those. Unless you can show us otherwise I'm closing this because of the FUD potential. Feel free to continue the discussion but please don't reopen unless you can show us a way to affect any of these.
