### ISSUE TITLE
Kitty preview does not work / w3m image missaligned 

### ISSUE THREAD

**Issue by ahloiscreamo** [ranger/ranger#1449]
Hi,
I have 2 issues to report, 
the first one is kitty preview method does not work on my system.
I use kitty 0.13.3 latest, when i highlight the jpeg it show warning as 
'kitty preview only work on kitty and outside tmux. Make sure your TERM contains the string "kitty"' 
![screenshot from 2019-01-23 22-35-24](https://user-images.githubusercontent.com/9318372/51615873-dce92100-1f63-11e9-8bb9-44a2e6b7102f.png)

Because i couldn't get it to work, i switch to use w3m which bring me to next problem. 
My second issues is w3m preview is not aligned well with the terminal border,
picture for  reference
![screenshot from 2019-01-23 23-00-00](https://user-images.githubusercontent.com/9318372/51616389-ec1c9e80-1f64-11e9-802e-b486714764be.png)

 

#### Runtime Environment
- Ranger version: ranger 1.9.2
- Python version: 3.7.2 
- Fedora 29
- Terminal emulator and version: Kitty 0.13.3 
- Locale: en_US.UTF-8

**Comment by toonn** [comment]
Ugh, this is probably an issue with how kitty reports its dimensions (if I had to guess). Not sure it can be solved without ruining it for other terminals though : /

What's your `TERM` value?

**Comment by ahloiscreamo** [comment]
I see,
So ,this is some detail on term

```
~
❯ echo $TERM
xterm-256color

~
❯ find /usr/share/terminfo -type f
/usr/share/terminfo/v/vt220
/usr/share/terminfo/v/vte
/usr/share/terminfo/v/vs100
/usr/share/terminfo/v/vt200
/usr/share/terminfo/v/vt100-nav
/usr/share/terminfo/v/vte-256color
/usr/share/terminfo/v/vt100
/usr/share/terminfo/v/vwmterm
/usr/share/terminfo/v/vt100-am
/usr/share/terminfo/v/vt52
/usr/share/terminfo/v/vt102
/usr/share/terminfo/h/hurd
/usr/share/terminfo/n/nxterm
/usr/share/terminfo/n/nsterm
/usr/share/terminfo/E/Eterm
/usr/share/terminfo/E/Eterm-256color
/usr/share/terminfo/E/Eterm-88color
/usr/share/terminfo/E/Eterm-color
/usr/share/terminfo/k/kon2
/usr/share/terminfo/k/konsole
/usr/share/terminfo/k/kon
/usr/share/terminfo/k/konsole-256color
/usr/share/terminfo/t/teraterm
/usr/share/terminfo/t/tmux-256color
/usr/share/terminfo/t/tmux
/usr/share/terminfo/t/teraterm2.3
/usr/share/terminfo/x/xterm-termite
/usr/share/terminfo/x/xterm-xf86-v32
/usr/share/terminfo/x/xterm-kitty
/usr/share/terminfo/x/xterms
/usr/share/terminfo/x/xterm-8bit
/usr/share/terminfo/x/xterm-xf86-v33
/usr/share/terminfo/x/xterm-xf86-v40
/usr/share/terminfo/x/xterm-pcolor
/usr/share/terminfo/x/xterm-sco
/usr/share/terminfo/x/xterm-xf86-v43
/usr/share/terminfo/x/xterm-hp
/usr/share/terminfo/x/xterm-16color
/usr/share/terminfo/x/xterm-x11mouse
/usr/share/terminfo/x/xterm-xf86-v44
/usr/share/terminfo/x/xterm-xfree86
/usr/share/terminfo/x/xterm-vt220
/usr/share/terminfo/x/xterm-color
/usr/share/terminfo/x/xterm-88color
/usr/share/terminfo/x/xterm-24
/usr/share/terminfo/x/xterm-new
/usr/share/terminfo/x/xterm-r6
/usr/share/terminfo/x/xterm-256color
/usr/share/terminfo/x/xterm-r5
/usr/share/terminfo/x/xterm-direct
/usr/share/terminfo/x/xterm-1006
/usr/share/terminfo/x/xterm-old
/usr/share/terminfo/x/xterm-noapp
/usr/share/terminfo/x/xterm-x11hilite
/usr/share/terminfo/x/xterm-1003
/usr/share/terminfo/x/xterm-1005
/usr/share/terminfo/x/xterm-xi
/usr/share/terminfo/x/xterm-x10mouse
/usr/share/terminfo/x/xterm-nic
/usr/share/terminfo/x/xterm-sun
/usr/share/terminfo/x/xterm-utf8
/usr/share/terminfo/x/xterm-vt52
/usr/share/terminfo/x/xterm-bold
/usr/share/terminfo/x/xterm
/usr/share/terminfo/x/xterm-1002
/usr/share/terminfo/x/xterm-basic
/usr/share/terminfo/x/xfce
/usr/share/terminfo/x/xterm-xf86-v333
/usr/share/terminfo/x/xterm-direct2
/usr/share/terminfo/p/putty-256color
/usr/share/terminfo/p/pcansi
/usr/share/terminfo/p/putty
/usr/share/terminfo/w/wsvt25m
/usr/share/terminfo/w/wsvt25
/usr/share/terminfo/A/Apple_Terminal
/usr/share/terminfo/c/cygwin
/usr/share/terminfo/c/cons25
/usr/share/terminfo/e/eterm
/usr/share/terminfo/e/eterm-color
/usr/share/terminfo/m/mlterm
/usr/share/terminfo/m/mach-bold
/usr/share/terminfo/m/mach
/usr/share/terminfo/m/mrxvt
/usr/share/terminfo/m/mach-color
/usr/share/terminfo/m/mach-gnu
/usr/share/terminfo/m/mach-gnu-color
/usr/share/terminfo/d/dumb
/usr/share/terminfo/r/rxvt-xpm
/usr/share/terminfo/r/rxvt-cygwin
/usr/share/terminfo/r/rxvt-88color
/usr/share/terminfo/r/rxvt-16color
/usr/share/terminfo/r/rxvt-unicode-256color
/usr/share/terminfo/r/rxvt-256color
/usr/share/terminfo/r/rxvt-color
/usr/share/terminfo/r/rxvt
/usr/share/terminfo/r/rxvt-cygwin-native
/usr/share/terminfo/r/rxvt-unicode
/usr/share/terminfo/r/rxvt-basic
/usr/share/terminfo/g/gnome-256color
/usr/share/terminfo/g/gnome
/usr/share/terminfo/s/st-meta-256color
/usr/share/terminfo/s/stterm-256color
/usr/share/terminfo/s/screen.xterm-r6
/usr/share/terminfo/s/screen.xterm-256color
/usr/share/terminfo/s/screen
/usr/share/terminfo/s/screen.putty-256color
/usr/share/terminfo/s/screen.mlterm-256color
/usr/share/terminfo/s/screen.Eterm
/usr/share/terminfo/s/sun
/usr/share/terminfo/s/screen-256color
/usr/share/terminfo/s/stterm-16color
/usr/share/terminfo/s/screen-16color
/usr/share/terminfo/s/screen.mlterm
/usr/share/terminfo/s/screen.xterm-xfree86
/usr/share/terminfo/s/st
/usr/share/terminfo/s/sun1
/usr/share/terminfo/s/screen.gnome
/usr/share/terminfo/s/screen.mrxvt
/usr/share/terminfo/s/sun2
/usr/share/terminfo/s/st-256color
/usr/share/terminfo/s/screen.rxvt
/usr/share/terminfo/s/screen.konsole
/usr/share/terminfo/s/st-16color
/usr/share/terminfo/s/screen.vte
/usr/share/terminfo/s/screen.linux
/usr/share/terminfo/s/screen.putty
/usr/share/terminfo/s/screen.xterm-new
/usr/share/terminfo/s/screen.vte-256color
/usr/share/terminfo/s/stterm
/usr/share/terminfo/s/screen.teraterm
/usr/share/terminfo/s/st-meta
/usr/share/terminfo/s/screen.konsole-256color
/usr/share/terminfo/j/jfbterm
/usr/share/terminfo/b/bterm
/usr/share/terminfo/a/ansi
/usr/share/terminfo/a/ansi80x25
/usr/share/terminfo/a/ansis
/usr/share/terminfo/a/aterm
/usr/share/terminfo/l/linux

~
❯ 
```
if you need anything else , please tell me

**Comment by ahloiscreamo** [comment]
Hi,
I spends long time to figure what did i do wrong in my config and i just realized what a brainless i am.

1. TERM issue.
I finally found out why did the TERM messed up,
long time ago i set  `export TERM=xterm-256color` in my zshrc so no wonder kitty preview didn't work.
I removed the line and now set the `TERM=kitty` in my kitty config and now kitty preview is working as it should.

2. w3m preview not aligned issues.
I dig out my kitty config and i totally forgot that i set a few pixel for border before.
so i adjusted the value a little bit and the preview now work like charm.

Thanks for your assist,
should i have any further problem then i will come again.

**Comment by toonn** [comment]
The default `TERM` kitty uses is `xterm-kitty`, for compatibility reasons so it'd be a good idea to use that instead. Or not set it at all, since kitty sets it automatically unless you override it.

**Comment by Tanath** [comment]
I've read over this and I still can't get image previews working, by either method. In kitty my `$TERM` is `xterm-kitty`. I've not set `TERM` in my zsh files. I've set `set preview_images_method kitty`, and tried w3m too. I have `python-pillow`, `python2-pillow` and `w3m` installed. I'm testing in kitty as well as guake & xfce4-terminal, (with `$TERM`=`xterm-256color`).
I would think w3m method would work in the others if kitty doesn't.

**Comment by toonn** [comment]
@Tanath, I suspect this'd be much easier to discuss on irc.

What's your ranger version? Are you expecting ranger to fall back to w3m when not run in kitty? I doubt w3mimgdisplay works with guake tbh, and it's unlikely to work with xfce4-terminal since that's libVTE based.

**Comment by Tanath** [comment]
Thanks irc. So my issue was I needed to set these as well:
`set use_preview_script true`
`set preview_script ~/.config/ranger/scope.sh`
