### ISSUE TITLE
Document Ueberzug preview method

### ISSUE THREAD

**Issue by toonn** [ranger/ranger#1453]
We didn't document the ueberzug preview method in the man page, let's fix that before the next release. Maybe even mention it works with tilix's tiling, cf. #1445.

**Comment by seebye** [comment]
> Maybe even mention it works with tilix's tiling, cf.

Please not, it's not official supported.
Also in my test the image wasn't correctly placed and sized.

**Comment by Old-Knitterhemd** [comment]
> > Maybe even mention it works with tilix's tiling, cf.
> 
> Please not, it's not official supported.
> Also in my test the image wasn't correctly placed and sized.

Is there a way to set the padding for tilix via ueberzug config file?

**Comment by toonn** [comment]
For in ranger? You could try if the `w3m_offset` works.

**Comment by Old-Knitterhemd** [comment]
> For in ranger? 

Yes, ueberzug keeps drawing the picture on the window decoration in tilix.

> You could try if the `w3m_offset` works.

You mean in rc.conf? I already tried that with no effect.

**Comment by toonn** [comment]
Then it's impossible currently.
