### ISSUE TITLE
Preview fb2 files as images

### ISSUE THREAD

**Issue by krnl0138** [ranger/ranger#1463]
#### Runtime Environment

- Operating system and version: linux-lqx 4.17.14-1
- Terminal emulator and version: alacritty 0.2.7-2
- Python version: 3.7.2-3
- Ranger version/commit: 1.9.2.149.ge3f89a7c-1
- Locale: en_US.UTF-8

#### Current Behavior

Preview fb2 files as plain texts 

#### Expected Behavior

Preview fb2 files as images

#### Context

1. Uncommented section for fb2 in 'images' in scope.sh
2. Still see plain text instead of images

#### Possible Solutions

1. Seems like ranger ignores the options like:
`application/x-mobipocket-ebook|application/x-fictionbook+xml)`
and understands fb2 files as:
`text/* | */xml)`
files as far as I understood. 
So I need to comment out this section and change this line
`application/x-mobipocket-ebook|application/x-fictionbook+xml)`
into `*/xml)` in order to make it works.
2. Need to find a way for ranger to treat .fb2 extension properly

#### Steps to reproduce
1. install ranger-git
2. do in console ranger --copy-config=scope
3. uncomment line in scope.sh for fb2 in images section
4. comment out the section `text/* | */xml`
5. change `application` line in fb2 part to `*/xml`

**Comment by krnl0138** [comment]
moved fb2 section to the `file extention lower`, works fine, closed.

**Comment by toonn** [comment]
Yes, `file(1)` doesn't detect the correct mimetype for them. That's a known issue and afaik we can't really solve it satisfactorily. You wouldn't want to render all xml files as ebooks. And we don't normally do image previews outside of `handle_image` so we don't have a good answer for this issue.

Your solution is fine if it works for you though. 👍
