### ISSUE TITLE
File previews show only one character per line / have newlines after each character

### ISSUE THREAD

**Issue by vicmortelmans** [ranger/ranger#1464]
Hi,

I'm readdressing the issue #1210 as I still see it myself.

I'm running the master version from github:

```
vic@vic-SATELLITE-PRO-A50-D:~ () $ ranger --version
ranger version: ranger-master 1.9.1
Python version: 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
Locale: None.None
```

I also have chardet intalled, which is referred to in the related issue threads:

`Requirement already satisfied: chardet in ./.local/lib/python2.7/site-packages (3.0.4)`

It looks like it might have something to do with filesize. I noticed in a directory with a set of files ranging between 224K and 753K that the files < 226K were OK, but the files > 282K were displayed on a single column. My educated guess is that there's a magical threshold at 256K :)

OK:
![image](https://user-images.githubusercontent.com/162956/52238016-502b5500-28cb-11e9-9256-7092448b4809.png)

Not OK:
![image](https://user-images.githubusercontent.com/162956/52238024-54f00900-28cb-11e9-8686-3e4c036d04de.png)

I hope this might help to solve the problem !!

Best regards,
Vic

**Comment by toonn** [comment]
That doesn't look like the master version. Master's past the release for `1.9.2`.

**Comment by vicmortelmans** [comment]
So it is! I was pulling from git://git.savannah.nongnu.org/ranger... where did I get that repository :/ ?

I cloned again from Github and now the file preview is working indeed!!

Sorry for disturbing :(

best regards,
Vic

**Comment by toonn** [comment]
No problem, glad this was such an easy fix : )

We used to be hosted on the savannah.
