### ISSUE TITLE
[Question] Is there a way to hide folders or atleast hide selection 

### ISSUE THREAD

**Issue by qymspace** [ranger/ranger#1465]
#### Runtime Environment
* Operating system and version: `Ubuntu 16.04`
* Terminal emulator and version: `Gnome terminal`
* Python version: `2.7.12`
* Ranger version/commit:  `1.9.2`
* Locale: `None.None`

I want to hide all directories in current working directory so as to easily work with remaining files.

**Comment by toonn** [comment]
Yep, the new filter_stack functionality can do this: `.d.!` would filter *out* directories.

**Comment by qymspace** [comment]
Thanks. Found it
