### ISSUE TITLE
scrolling in preview

### ISSUE THREAD

**Issue by rhacker** [ranger/ranger#147]
Is there anyway that we can scroll in preview pane ? 

Thanks for great work !

**Comment by dufferzafar** [comment]
@hut I too would like the ability to scroll the preview (without 'entering' the preview.) 

I am new to the codebase, so can you please provide some pointers as to where should I start if I have to add this sort of functionality?

**Comment by abrodkin** [comment]
Looks like a pretty convenient feature if it exists.
Any chance to reopen that issue or maybe it worth opening a new one to track this feature request?

**Comment by teranex** [comment]
I was also looking for a way to scroll in the preview without having to "enter" the full preview, so +1 from me as well for this feature request

**Comment by jlopezr** [comment]
+1

**Comment by rafaqz** [comment]
+1

**Comment by j-degreef** [comment]
+1

**Comment by kclevenger** [comment]
+1

**Comment by vicmortelmans** [comment]
+1

**Comment by kclevenger** [comment]
Or as a workaround, is there a way to swap the right-arrow/"l" behavior when on a text file to jump into viewing the file instead of editing it?

**Comment by banderlog** [comment]
+1

**Comment by techknowfile** [comment]
+1. It would also be cool to be able to focus it and enable less-like navigation of it

**Comment by kajzersoze** [comment]
+1
With mouse wheel it would be perfect.

**Comment by existme** [comment]
+1

**Comment by izhakjakov** [comment]
+1

**Comment by gdkrmr** [comment]
+1

**Comment by toonn** [comment]
@kclevenger You could alter `rifle.conf` so the pager rule's higher up than  the editor rule but that would open the file in your pager, which is subtly different from `i`.

**Comment by langenhagen** [comment]
+1 I also like to see a scrolling through the preview support. As an example, tig (https://github.com/jonas/tig) does a pretty good job in demonstrating such a feature. In tig, one can scroll with up/down through the main view and with j/k through a secondary diff view. I think, in ranger, using <ALT>+j / <ALT>+k would be awesome to scroll through the preview.

**Comment by toonn** [comment]
@langenhagen this has already been implemented. It's just not in a release yet.

**Comment by masaeedu** [comment]
@toonn Awesome. If I build from source, how would I configure the shortcuts for this?

**Comment by laoshaw** [comment]
it's not released but I build from master and it indeed works well.
