### ISSUE TITLE
Image preview don't working on kiTTY

### ISSUE THREAD

**Issue by juacq97** [ranger/ranger#1471]
#### Runtime Environment

- Operating system and version: Manjaro Linux
- Terminal emulator and version: kitty 0.13.3 
- Python version: 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127]
- Ranger version/commit: ranger 1.9.2
- Locale: es_MX.UTF-8

#### Current Behavior
When I put the cursor over a image, it doesn't preview. Very strange, the previews were NOT working in urxvt or xterm, but now they do.

#### Expected Behavior
When I put the cursor over a image, a preview appears.

#### Context

I can't see the preview of the images, doesn't matter the size of the window or the image. I don't know if it is useful to know, but yesterday I updated the system and installed the "common python and haskell updates".

#### Possible Solutions
- Check if there's a problem in the configuration file, but I don't see anything.
- Check if `kitty +kitten icat image.png` works. I does.

#### Steps to reproduce
1. Open ranger.
2. Activate the image preview pressing `zp`
3. Put the cursor over an image file.

**Comment by toonn** [comment]
Did you set `preview_images_method kitty`?

**Comment by juacq97** [comment]
> Did you set `preview_images_method kitty`?

I changed to kitty and now works. I suppose that all this time was working with w3m.

**Comment by metal3d** [comment]
I set `preview_images_method kitty` in rc file... but that doesn't work for me :cry:

**Comment by metal3d** [comment]
OK, forget, I missed the `preview_image true`... my bad
