### ISSUE TITLE
No image preview on st

### ISSUE THREAD

**Issue by juacq97** [ranger/ranger#1474]
#### Runtime Environment

- Operating system and version: Manjaro
- Terminal emulator and version: st 0.8.2
- Ranger version: ranger 1.9.2
- Python version: 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127]
- Locale: es_MX.UTF-8

#### Current Behavior
When I put the cursor over an image, the preview doesn't appears

#### Expected Behavior
When I put the cursor over an image, a preview appears.

#### Context

I change to st terminal, I have 4 patches (scrollback, scrollback mouse, scroolback mouse alt-screen and alpha). All works perfect, except for the image preview. I set `preview-image-method` to w3m.

#### Possible Solutions
Change the `preview-image-method` to another one, but any works.

#### Steps to reproduce
1.  Open ranger.
2. Put the cursor over an image

**Comment by toonn** [comment]
Couple things first, is `w3mimgdisplay` installed? Does it work seperate from ranger? In other words, do previews work for you in xterm? Depending on your answer here there's different next steps.

You could also try the `ueberzug` preview method if you install the latest master version of ranger, that should always work whenever an X windowing system is available.

**Comment by juacq97** [comment]
> In other words, do previews work for you in xterm?

Yes, it woks.
Here's XTerm
![captura-2019-02-14](https://user-images.githubusercontent.com/7623047/52818088-00832100-3063-11e9-9b04-88bcb379f2ba.png)

And here's st
![captura-2019-02-14_1](https://user-images.githubusercontent.com/7623047/52818109-0e38a680-3063-11e9-8d21-3fc990fd9ece.png)

> You could also try the `ueberzug` preview method

I have the manjaro version of ranger. I will try with master.

**Comment by juacq97** [comment]
I tried with `ueberzug` and this appears

![captura-2019-02-14_2](https://user-images.githubusercontent.com/7623047/52818616-7d62ca80-3064-11e9-9b42-e016eba11cec.png)

**Comment by toonn** [comment]
@seebye, could you check out that error?

@juacq97, does w3mimgdisplay work if you invoke it in st outside of ranger? I suspect it's just not compatible with your version of st.

**Comment by seebye** [comment]
@toonn The library attrs isn't installed which is used by ueberzug.  
He likely installed https://aur.archlinux.org/packages/python-ueberzug/ (misses dependencies) instead of https://aur.archlinux.org/packages/python-ueberzug-git/

**Comment by juacq97** [comment]
> He likely installed https://aur.archlinux.org/packages/python-ueberzug/ (misses dependencies) instead of https://aur.archlinux.org/packages/python-ueberzug-git/ (these are **in**official packages).

I had installed the first, changed to the second package and now the `ueberzug` preview works very well.

> does w3mimgdisplay work if you invoke it in st outside of ranger?

I checked w3m outside the ranger and no, the images are not shown, it seems that they stopped the support for w3m.

**Comment by SBanya** [comment]
Hi there, just to confirm to possibly test this issue for you guys, you guys are using Suckless Terminal aka ssterm right?

Just confirming because I found 'ssterm' on Lubuntu's Muon package manager, and wanted to know before I download it and try to replicate this issue.

**Comment by toonn** [comment]
@SBanya, yes, this is about st from the Suckless project.
I'm fairly confident that they don't try to be xterm compatible enough for w3mimgdisplay to work though. So I'm closing this until someone shows it does/should work.

**Comment by LuxGiammi** [comment]
I experienced the same issue, but I found a way to "partially" fix it. 
I have ranger v. 1.9.2, python 2.7.13 and I use st. 
After having copied the default configuration file (`ranger --copy-config all`) I changed my `~/.config/ranger/rc.conf` by setting  `w3m_delay` to 0.1. (`set w3m_delay 0.1`).
Now, the first time I try to preview an image it fails, but it's enough to change directory (i.e. go to the parent directory) and visit the directory I'm interested in again to show previews correctly, and then as long as I don't quit ranger, previews are correctly displayed. And on the next start it's enough to do the same trick again to make it work.

**Comment by toonn** [comment]
Have you tried different settings for the delay?

**Comment by LuxGiammi** [comment]
@toonn Yes, but 0.1 works ok for most of the times. I tried some values less than 0.1, but I've experienced some issued (i.e. image previews disappears). I found out that, by using ranger a bit, sometimes previews are not shown correctly, even with 0.1, and I need to switch image back and forth to see the preview correctly with w3m. I've not still tried with other methods (ueberzug), but I'm looking forward to in the next few weeks,

**Comment by WloHu** [comment]
My env is similar to @juacq97 excluding OS:

#### Runtime Environment
Operating system and version: 5.1.14-arch1-1-ARCH (it's old)
Terminal emulator and version: st 0.8.2
Ranger version: ranger 1.9.2-1
Python version: Python 3.7.3 (default, Mar 26 2019, 21:43:19) [GCC 8.2.1 20181127]
System Locale: LANG=en_US.UTF-8
W3M version: w3m 0.5.3.git20190105-1

I have the same issue and solution that @LuxGiammi noted: preview blinks for split second and fails (nothing is shown); setting the delay to at least `0.1` helps.

I've also noticed that when last image in directory is focused and I press `j` (down) the preview dissappears but focus is still on the last image in directory.

**Comment by plasmoduck** [comment]
w3m image previews work fine for ranger in st. You just can't have the alpha patch.

**Comment by prosoitos** [comment]
Similar problem with st (without the alpha patch): most images get a preview just fine, but quite a few only appear for the briefest of instant and disappear. Those problematic images get a preview just like the others with urxvt.

OS: 5.9.14-arch1-1
ranger: 1.9.3-3
st: 0.8.4
w3m: 0.5.3.git20200507-2

**Comment by plasmoduck** [comment]
Yes it only works for some images, jpg or png only I believe. Something to do with the metadata I belive

**Comment by prosoitos** [comment]
From my observations, some png work, others don't (always the same ones).

For the png that do work (as well as for pdfs which are turned to images by pdftoppm in scope.sh), it doesn't work nearly as well as with urxvt (might have to go back to the file twice before the preview works).

Shouldn't this issue be re-opened considering that previews with st are not all that great?

**Comment by toonn** [comment]
Not in my opinion, st just isn't compatible with w3mimgdisplay, nothing we can do about that. If you're running X11 you can use ueberzug instead.

**Comment by prosoitos** [comment]
OK. Thanks for the suggestion! I will give it a try.

**Comment by prosoitos** [comment]
Works like a charm! Thanks again for the suggestion 🙂  My copy of `rc.conf` is quite old now and I hadn't kept up with the new updates, so I had missed the addition of this option.

As a really great added bonus, ueberzug redraws images while switching workspaces which solves that long lasting problem. So this is great!!

**Comment by prosoitos** [comment]
Just read the comments above about Arch Linux and ueberzug: the package is now in Community 🙂. So it works great and is now a real no-brainer to install. For people using X11, even without the st problem, I think that this is a much better option now.

https://archlinux.org/packages/?q=ueberzug

**Comment by plasmoduck** [comment]
Yes st isn’t designed to be used with w3—img because it’s a really hacky way to display images. It will work sometimes if your lucky but fails most of the time. Instead of w3m the suckless community recommends using sixel to display images in st.

**Comment by toonn** [comment]
Ranger doesn't have sixel support yet. There's an open PR but it hasn't been reviewed yet.

**Comment by plasmoduck** [comment]
Yep that’s what we’re all waiting for, in the meantime I use vifm and nnn
