### ISSUE TITLE
Image preview not working on Wayland

### ISSUE THREAD

**Issue by harrisonthorne** [ranger/ranger#1476]
#### Runtime Environment

- Operating system and version: Arch Linux 4.19
- Terminal emulator and version: Alacritty 0.2.9
- Python version: 3.7.2
- Ranger version/commit: 1.9.2 
- Locale: en_US.UTF-8

#### Current Behavior

ranger fails to show image previews with w3m on Wayland; (`('Failed to execute w3mimgdisplay', [])`)

#### Expected Behavior

ranger should be able to display images on Wayland

#### Steps to reproduce
1. Use a Wayland session (I'm using Sway)
2. Select an image
3. Notice that ranger displays `('Failed to execute w3mimgdisplay', [])`, or doesn't do anything at all

#### Traceback
```
20:13:25 ERRO Notification: ('Failed to execute w3mimgdisplay', [])
20:13:25 ERRO ('Failed to execute w3mimgdisplay', [])
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/pager.py", line 111, in draw_image
    self.wid, self.hei)
  File "/usr/lib/python3.7/site-packages/ranger/ext/img_display.py", line 145, in draw
    input_gen = self._generate_w3m_input(path, start_x, start_y, width, height)
  File "/usr/lib/python3.7/site-packages/ranger/ext/img_display.py", line 209, in _generate_w3m_input
    raise ImageDisplayError('Failed to execute w3mimgdisplay', output)
ranger.ext.img_display.ImageDisplayError: ('Failed to execute w3mimgdisplay', [])
```

**Comment by toonn** [comment]
Does it work in xterm? Is w3mimgdisplay installed somewhere ranger looks?

**Comment by Vifon** [comment]
I wouldn't expect w3m-img to work on Wayland at all. That being said, the current error message isn't too helpful indeed.

**Comment by toonn** [comment]
"Failed to execute w3mimgdisplay," seems pretty clear to me. The next step it suggests is "Figure out why w3mimgdisplay doesn't work."
How would you suggest improving the error message? Detecting whether we're running in a Wayland environment? That'll have us writing specific error message for people running ubuntu or arch or i3 or whatever in no time.

**Comment by Vifon** [comment]
Fair enough. It's a pretty grey area of "unclearness", so I guess we can close it. That being said, to whoever might want to do so, a PR handling it in a more graceful way would be welcome.

**Comment by harrisonthorne** [comment]
Just a note to add: I've confirmed image previews work in xterm. They do not work in Alacritty.

**Comment by toonn** [comment]
@harrisonthorne, I assume XTerm uses the X emulation layer? Good to know though.

**Comment by charlie39** [comment]
> Just a note to add: I've confirmed image previews work in xterm. They do not work in Alacritty.

Image preview works on alacritty. It doesn't work under Wayland however. Can the preview be changed to something like imv which can display images gifs both under X and Wayland ? 
And how do I change the default tool to open images ?
I want to change it to imv 
in rifle.conf right ? 
I have been trying but I couldn't figure it out

**Comment by toonn** [comment]
`imv` as a preview method would be accepted as a PR.

Yes, you want to edit `rifle.conf`. You need to create a rule (or edit one) that matches your image files and calls `imv` on them. The rules are tried in order so you want to add it pretty high up in the file. Something like `mime image = imv -- "$@"`, depending on whether imv supports all image formats and whether it accepts `--` as an argument (means to stop processing arguments as option by convention).

**Comment by charlie39** [comment]
> `imv` as a preview method would be accepted as a PR.
> 
> Yes, you want to edit `rifle.conf`. You need to create a rule (or edit one) that matches your image files and calls `imv` on them. The rules are tried in order so you want to add it pretty high up in the file. Something like `mime image = imv -- "$@"`, depending on whether imv supports all image formats and whether it accepts `--` as an argument (means to stop processing arguments as option by convention).

i have it working as a image/gif opener. Couldn't figure out how to preview though.
 Can this be accepted as a PR though?

```mime ^image, has imv, X, flag f = imv -- "$@" ```

And what is the X for ? X server ?

**Comment by toonn** [comment]
Yes, that distinguishes whether or not we're running on X. Is it only gifs? Then let's match the extension rather than a broad mime type.
