### ISSUE TITLE
Changing preview_script on-the-fly fails

### ISSUE THREAD

**Issue by slackhead** [ranger/ranger#1483]
#### Runtime Environment
ranger version: ranger 1.9.2
Python version: 3.6.7 (default, Feb  4 2019, 07:50:16) [GCC 5.5.0]
Locale: en_GB.UTF-8

#### Current Behavior

When doing :set preview_script /path/to/script on first starting ranger, it is OK so long as no files have been previewed yet.  It seems to have random behaviour if you have previewed any.  That's the first problem, which may be releated to the greater problem.

After previewing some files (in my case I'm using a custom hex edit script) and then using :set to go back to the default ~/.config/ranger/scope.sh it doesn't not work.  It carries on using the custom script.

There is no error at all.  It just continues to show files in my hex script.

#### Expected Behavior

Ranger should be able to change preview scripts on-the-fly.

#### Context

I sometimes would like to hex view all the files in a directory.  My custom script uses xxd to do this.

#### Possible Solutions

Does ranger cache preview info somewhere?  Can it be cleared?

#### Steps to reproduce
1. Set a preview script
2. View some files
3. Set a different preview script

This is my script if you want to test it.  It's a zsh script.  I'm not sure if sh/bash can do the calcualtions.

#!/bin/zsh

IN=$(xxd -g0 -c1 -u "$1" | head -n $2)

printf "%-9b %3b %3b %3b %3b %-8b\n" "OFFSET" "ASC" "HEX" "DEC" "OCT" "BIN"
while read -r OFF HEX ASC; do
	DEC=$((0x$HEX))
	OCT=$(([##8]0x$HEX))
	BIN=$(([##2]0x$HEX))
	[ ${#BIN} -lt 8 ] && BINFMT="%0$((8-${#BIN}))i%s" || BINFMT="%n%s"

	printf "%9b %-3b %-3b %03i %03i $BINFMT\n" \
		"$OFF" "$ASC" "$HEX" "$DEC" "$OCT" 0 "$BIN"
done <<< "$IN"

**Comment by slackhead** [comment]
It looks like doing a 'reset' after changing preview_script fixes this problem.  I'm not sure if it affects other things though.

Is there a way of flushing the preview cache without doing a full reset?

**Comment by slackhead** [comment]
I added a simple command that clears the preview cache.  I've also tried it in actons.py (different syntax of course) so I'll make a very small PR for it:

```
class reset_previews(Command):
    """:reset_previews
    Reset the file previews
    """
    def execute(self):
        self.fm.previews = {}
```

map <F11> chain set preview_script ~/.config/ranger/hexview.zsh; reset_previews; redraw_window
map <F12> chain set preview_script ~/.config/ranger/scope.sh; reset_previews; redraw_window

This seems to work fine.  For some reason adding the redraw command in the function doesn't work - i.e. self.fm.draw_window.

**Comment by toonn** [comment]
Hmm, @slackhead, could you investigate that issue further? Not ergonomic enough to include with ranger if you have to remember to redraw anyway imo : /

**Comment by slackhead** [comment]
Yes, I'll take a look at it.

**Comment by slackhead** [comment]
OK, so marking the window for redraw accomplishes it:

self.fm.previews = {}
self.fm.ui.need_redraw = True

I mailed a patch directly to Hut, rather than making a PR.

**Comment by toonn** [comment]
Hut's pretty busy so a PR might get merged faster but you do you.
