### ISSUE TITLE
map key to shell action with clipboard value?

### ISSUE THREAD

**Issue by niksfirefly** [ranger/ranger#1491]
Is there any way to map key to shell action with clipboard value?
for example in rc.conf
map ,c shell wget %<ubuntu-clipboard-value>
regards

**Comment by Vifon** [comment]
Not directly, though you should be able to use:

```
map ,c shell wget `xsel`
```

...to retrieve the current clipboard contents.

**Comment by toonn** [comment]
Or these macros for ranger's copy buffer:
```
%c   the full paths of the currently copied/cut files
%p   the full paths of selected files
```

**Comment by niksfirefly** [comment]
@Vifon very nice It works!
regards
