### ISSUE TITLE
`ranger --copy-config .` 

### ISSUE THREAD

**Issue by mcarifio** [ranger/ranger#1502]
I realize there's a closed issue with --copy-config. I don't think you should close it until you update `README.md` to use an argument with it, e.g. `--copy-config=all`. Based on the readme, I was expecting `[path]` to be the _target_ directory receiving the config files. I'm guessing the `.` is the end of the sentence not current directory? When I finally read #1002, I got this result:

```bash
python3 ranger.py --copy-config=all /tmp/.config/ranger
already exists: /home/mcarifio/.config/ranger/rifle.conf
already exists: /home/mcarifio/.config/ranger/commands.py
creating: /home/mcarifio/.config/ranger/commands_full.py
already exists: /home/mcarifio/.config/ranger/rc.conf
creating: /home/mcarifio/.config/ranger/scope.sh

> Please note that configuration files may change as ranger evolves.
  It's completely up to you to keep them up to date.

> To stop ranger from loading both the default and your custom rc.conf,
  please set the environment variable RANGER_LOAD_DEFAULT_RC to FALSE.
```

I suggest updating the `README.md`, it's pretty confusing.

**Comment by toonn** [comment]
What exactly is confusing? `--copy-config` doesn't have a path argument at all so I'm not sure where you're getting that from? `ranger /some/path` opens that directory in ranger.
