### ISSUE TITLE
Wrong free space is reported on remote filesystem

### ISSUE THREAD

**Issue by nQ8hzkZw** [ranger/ranger#1505]
#### Runtime Environment

- Operating system and version: Linux Mint 19.1 MATE
- Terminal emulator and version: xterm (330-1ubuntu2)
- Python version: 2.7.15rc1
- Ranger version/commit: 1.9.2
- Locale: en_US.utf8

#### Current Behavior
Ranger displays free space of remote root filesystem even if path on external hdd is opened.
#### Expected Behavior
Display free space on external hdd.

#### Steps to reproduce
1. Mount a remote filesystem:
`$ sshfs user@server:/ /path/to/mountpoint`
2. Navigate to external hdd `/path/to/mountpoint/media/user/external-hdd/Downloads`.
3. Status bar shows how much space is left on remote root `/` filesystem. Expected behaviour: show how much space is left on external hdd `/media/user/external-hdd`.

Free space on remote external drive is reported corectly in other file managers (for example: Caja; Double Commander).

When the remote file system is mounted as shown below, Ranger reports free space correctly.
`$ sshfs user@server:/media/user/external-hdd/Downloads /path/to/mountpoint`

**Comment by Vifon** [comment]
@nQ8hzkZw Good catch! Please test if the referenced PR fixes it for you.

**Comment by toonn** [comment]
I can reproduce this. The fix is pretty simple but I'm worried about performance. Could you test #1506?

**Comment by nQ8hzkZw** [comment]
Thanks @Vifon,
I confirm that the fix works.

**Comment by toonn** [comment]
Is it performant though? That's what worries me.

**Comment by nQ8hzkZw** [comment]
I didn't notice performance issues after the fix. Navigation is as smooth as before.
Unfortunately, I don't know how to properly measure small differences in directory load times or CPU usage.

**Comment by toonn** [comment]
If it's not noticeable I guess it's fine, we can fix it if it becomes a problem. Thanks for the report and the testing!
