### ISSUE TITLE
Mappings with common prefix

### ISSUE THREAD

**Issue by mb720** [ranger/ranger#1509]
#### Runtime Environment

- Operating system and version: 5.0.4-arch1-1-ARCH
- Terminal emulator and version: termite v14
- Python version: Python version: 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127]
- Ranger version/commit: 1.9.2
- Locale: en_US.UTF-8

#### Current Behavior
I have two key mappings in my ranger.conf, each to enter a directory:

    map gd  cd ~/dir/
    map gds cd ~/dir/sub

When I want to go to `~/dir/`, I press `gd`.

Ranger waits for me to press `s` to complete the `gds` mapping which would take me to `~/dir/sub`, but that's not where I want to go.

It seems to me that the `gds` mapping has rendered the `gd` mapping useless.

#### Expected Behavior
I was hoping that I still could use the `gd` mapping by pressing enter or tab after entering `gd`.

#### Possible Solutions
I could choose different mappings with that don't share the same prefix; in this case the prefix is `gd`. But this would be harder to remember since the mapping wouldn't reflect in its name (`gds`) that it takes me to a subdirectory of a mapping with the same prefix (`gd`).

#### Steps to reproduce
Use those two example mappings and try to go to the directory that `gd` would take you.

**Comment by toonn** [comment]
You can kinda cheat and do `map gd<bg> cd ~/dir`, that would always cause `cd ~/dir` to be run. Then you can press `ESC` to stop there or `s` to `cd ~/dir/sub`. Far from ideal, yes. But adding timeouts is an ugly solution too imo.

What seems to me to be a better fit for your purpose is bookmarks. Or, if single letters aren't enough you can write a custom command that uses a dictionary to look up the destination for an alias, then you could do something like `:g ds`.

Something else that might interest you is the `fzf` or `fd` or `fasd` or other integrations on the wiki.

**Comment by hut** [comment]
@toonn explained the solution. ranger only supports these sort of key bindings when using `<bg>`. This seems to be a good compromise to me, so I will close this issue for the time being. Feel free to reopen it if you find a use case where this doesn't work.

`<bg>` might not be ideally documented, but issue #1501 is open for that problem.
