### ISSUE TITLE
Arrow/vim keys not working anymore

### ISSUE THREAD

**Issue by lifeBalance** [ranger/ranger#1519]
Can't navigate at all, the arrow keys as well as the Vim shortcuts don't respond. What could be the reason?
ranger version: ranger 1.9.2
Python version: 3.7.3 (default, Mar 26 2019, 21:43:19) [GCC 8.2.1 20181127]
Locale: en_US.UTF-8

**Comment by toonn** [comment]
Did you maybe accidentally press `ctrl-s`? That's a terminal feature, you can unfreeze with `ctrl-q`.

**Comment by lifeBalance** [comment]
Hey toonn, thanks for chiming in. Hadn't heard of that feature, interesting. Anyways, tried ``ctrl-q`` didn't do anything.

**Comment by hut** [comment]
Does it happen if you run ranger with the `--clean` parameter?

**Comment by lifeBalance** [comment]
No it doesn't. Thanks for the tip, didn't know the ``--clean`` option.
So that means that my configuration is broken. Any suggestion about where can be the problem? I've barely touched the defaults. 
What I did is setting ``RANGER_LOAD_DEFAULT_RC=FALSE`` in my ``.bash_profile``.

**Comment by toonn** [comment]
Oh, you're probably just not defining everything you need in your `rc.conf`. Easiest way is to run `ranger --copy-config=rc` then edit that with your customizations. *Or* not preventing the loading of the default : >

**Comment by lifeBalance** [comment]
Yes, I did that, I was just adding little touches to the default generated configuration, but I guess I messed up somewhere. 
Thanks a lot toonn, I guess I can close this question. Maybe it's useful to anybody.

**Comment by toonn** [comment]
np
