### ISSUE TITLE
sxiv -f  shows smaller unwanted image to the left

### ISSUE THREAD

**Issue by catzybluphish** [ranger/ranger#1529]
#### Runtime Environment

- Operating system and version: Arch Linux
- Terminal emulator and version: rxvt-unicode
- Python version: 3.7.3
- Ranger version/commit: 1.9.2
- Locale: en_US.UTF-8

#### Current Behavior
Starting sxiv with the -f argument for fullscreen and quitting shows the image to the left cut off by directory/file listings. Does not seem to happen in floating mode in bspwm.
![2019-04-12-231208_1920x1080_scrot](https://user-images.githubusercontent.com/40843060/56040207-36016d80-5d79-11e9-8c68-0253a76a6db8.png)
#### Expected Behavior
Not show the image.
#### Steps to reproduce
1. Open an image with ```sxiv -f``` configured in rifle.conf.
2. Quit.

**Comment by toonn** [comment]
I doubt this is a ranger issue. What previewing method do you use, w3m? Try the urxvt method or ueberzug.

**Comment by catzybluphish** [comment]
@toonn 
I've tried using the method shown in https://wiki.archlinux.org/index.php/Ranger#Troubleshooting, and the image cut-off no longer shows. Doubt this helps the core issue, but it works.
