### ISSUE TITLE
Installing ranger-fm with pip fails

### ISSUE THREAD

**Issue by lifeBalance** [ranger/ranger#1538]
Trying to install ranger from Pypi, but I keep getting the same error:

```
$ pip install ranger-fm
Collecting ranger-fm
  Using cached https://files.pythonhosted.org/packages/6c/95/a5a211e35084ac72cd427702dcc13982ddfbd7145522f68fd15b366e4201/ranger-fm-1.9.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mf/8v1qvz9j69lb5mqfjlr140qh0000gn/T/pip-install-9gvja590/ranger-fm/setup.py", line 12, in <module>
        import ranger
      File "/private/var/folders/mf/8v1qvz9j69lb5mqfjlr140qh0000gn/T/pip-install-9gvja590/ranger-fm/ranger/__init__.py", line 59, in <module>
        from ranger.core.main import main  # NOQA pylint: disable=wrong-import-position
      File "/private/var/folders/mf/8v1qvz9j69lb5mqfjlr140qh0000gn/T/pip-install-9gvja590/ranger-fm/ranger/core/main.py", line 22, in <module>
        'Locale: {0}'.format('.'.join(str(s) for s in locale.getlocale())),
      File "/Users/javi/.virtualenvs/testranger/lib/python3.7/locale.py", line 587, in getlocale
        return _parse_localename(localename)
      File "/Users/javi/.virtualenvs/testranger/lib/python3.7/locale.py", line 495, in _parse_localename
        raise ValueError('unknown locale: %s' % localename)
    ValueError: unknown locale: UTF-8

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/mf/8v1qvz9j69lb5mqfjlr140qh0000gn/T/pip-install-9gvja590/ranger-fm/
```

**Comment by toonn** [comment]
Is it possible your locale isn't set up right? It would usually be something like `en_US.UTF-8`.

**Comment by lifeBalance** [comment]
Hey toonn, that was it. I'm in macOS, I just had to add the following two lines to my shell configuration file:
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

I could install it, but when I try to launch it, I get this:
```
$ ranger
Traceback (most recent call last):
  File "/Users/javi/.virtualenvs/testranger/bin/ranger", line 35, in <module>
    import ranger  # NOQA pylint: disable=import-self,wrong-import-position
ModuleNotFoundError: No module named 'ranger'
```

**Comment by lifeBalance** [comment]
**Solved**, adding the following **environment variable**:
```
export VIRTUALENVWRAPPER_PYTHON=/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7
```
I was trying to install it in a **virtual environment**, but not sure why I had to set up this variable.
Anyways, thanks.

**Comment by toonn** [comment]
Did you activate the venv, with something like venv/bin/activate.sh/.fish/.zsh...?

**Comment by lifeBalance** [comment]
Yes, I use virtualenvwrapper to do that. I did `workon testranger` before installing it, it activates the environment.
This morning I'm getting the same error though, so apparently adding that line didn't solve the problem.

**Comment by toonn** [comment]
Did you export the variable on the command line or in `.bashrc`? Same thing with the `workon`. You don't need to do that only once, you need to do that in every shell where you want to use ranger, or in `.bashrc`.

**Comment by lifeBalance** [comment]
I exported the variable on my `.bashrc`, and source the file or start a new terminal.
I run `workon` on my shell to activate the virtual environment. 
As a sanity test, (apart from deleting and creating a new environment) I installed pywal on the same environment, and I have no problems launching it.
I have other virtual environments, I use sphinx a lot for example, got no issues at all.

**Comment by lifeBalance** [comment]
*Solved* Deleted the environment and create a new one. I guess s**t happens sometimes with virtual environments.
Thanks for the support.

**Comment by toonn** [comment]
I'll look into those later today, I've been getting them as well.
