### ISSUE TITLE
Ranger only implements custom colorschemes part of the way

### ISSUE THREAD

**Issue by j-james** [ranger/ranger#1545]
#### Current Behavior

After doing `:set colorscheme pathfinderdark` in Ranger, the colorscheme only partially applies. Images are linked below. 

#### Expected Behavior

[Images for reference](https://imgur.com/a/uKP2wxM)

[Colorscheme code](https://gist.github.com/j-james/8f891dca439d9979ab6121858f737e8e)

I wrote a colorscheme that was a copy of [default.py](https://github.com/ranger/ranger/blob/master/ranger/colorscheme/default.py), but with the `blue` and `cyan` values switched. I expected the blue and cyan colors to switch. 

#### Possible Solutions

My first guess would be that I wrote my colorscheme incorrectly. However, it's basically the same as `default.py`. 

My second guess would be that [colorscheme.py](https://github.com/ranger/ranger/blob/master/ranger/gui/colorscheme.py) uses `blue` as a default, and `default.py` never overwrote this. 

My third guess is that I'm making colorschemes objectively the wrong way. I tried reading through the [Adapt a Colorscheme doc](https://github.com/ranger/ranger/blob/master/doc/colorschemes.md#adapt-a-colorscheme), and understood nothing. I _think_ my colorscheme is doing it correctly, but maybe not the boolean values part. 

#### Steps to reproduce
1. Copy my colorscheme to `/.config/ranger/colorschemes/pathfinderdark.py`.
2. Run `:set colorscheme pathfinderdark`.

Colorschemes also don't stay consistent across ranger sessions, but that's probably intended behavior?

**Comment by nQ8hzkZw** [comment]
I think, the default colorscheme was partially applied to some items before you switched to other colorscheme.
So you need to reset ranger (`CTRL+R`) after setting new colorcheme.
Or you can change the line `set colorscheme default` in `rc.conf` to `set colorscheme pathfinderdark`. This will make the colorscheme persistent.

**Comment by j-james** [comment]
That's it!
