### ISSUE TITLE
iTerm2 image preview doesn't work with python 3

### ISSUE THREAD

**Issue by laggardkernel** [ranger/ranger#1546]
#### Runtime Environment

- Operating system and version: macOS 10.13.6
- Terminal emulator and version: iTerm2 3.3
- Python version: 3.6.8 installed by pyenv
- Ranger version/commit: 1.9.2
- Locale: en_US.UTF-8

#### Current Behavior
`ranger` installed by `pip3 install ranger-fm` doesn't work with iTerm2 image preview. A placeholder image is displayed but not the real image.

After removing the `pip3` installed `ranger` and reinstalled it with Homebrew, the problem disappeared.

The shebang of `ranger` from the brew installed one is `#!/usr/bin/python -O` (python 2). I could reproduce the problem by changing it to `#!/usr/local/bin/python3 -O`.

Besides, iTerm2 image preview works with shebang `#!/usr/local/bin/python -O` (python 2) as well.

~~The reason I tried to use `ranger` with Python 3 is that, the keybindings from the wiki for tmux integration doesn't work Python 2.~~

~~Error `'module' object has no attribute 'quote'` occurred on Python 2, which is already reported by #1335~~

**Update**: the tmux integration is solved.

**Comment by toonn** [comment]
Hmm, the iterm2 preview method indeed doesn't work for me with python 3. It shows placeholder images or something.

You're in luck, your problem is solvable. In python 2 `shlex` didn't have the `quote` function but `pipes` *did*. So simply replace `shlex` with `pipes` and then the mappings should work with python 2.

**Comment by toonn** [comment]
*Or* could you please test the changes I made on the wiki? If I didn't make any syntactic mistakes that should work regardless of python version.

**Comment by laggardkernel** [comment]
@toonn Thanks for your reply. The 2nd problem about the tmux integration is solved on my side. I use the new added tmux keybindings to achieve the same thing now. I'm sorry I didn't update it in the original post.

**Comment by toonn** [comment]
It'd be great if you could still test the changes I made. You don't need to switch to that method.

**Comment by laggardkernel** [comment]
The Syntax error with

```
map ef eval try: from shlex import quote; except ImportError: from pipes import quote; fm.run("tmux splitw -h rifle " + quote(fm.thisfile.basename))
```

```
ERRO Notification: The error `invalid syntax (<string>, line 1)` was caused by evaluating the following code: `try: from shlex import quote; except ImportError: from pipes impor
```

The other two methods provided by me work well. There's no need to stick to the python commands way.

**Comment by toonn** [comment]
I "fixed" the bindings. Try/except's not allowed to be single line in python.
Your bindings don't achieve the same thing btw. Could you either point that out or fix them?

**Comment by laggardkernel** [comment]
I'm talking about the other two methods I provided in the [Keybindings part from the wiki](https://github.com/ranger/ranger/wiki/Keybindings). The `map ew shell tmux new-window -c %d` works for me.

I tested your bindings on Python 2, the new pane closes quickly after it's created. Is it terminated after `fm.run()` is done, or because I run ranger with Python 2? Not so sure what happened.

**Comment by toonn** [comment]
@laggardkernel, I think you're misunderstanding what the keybindings do maybe. The open a file with *rifle* in a new tmux pane/window. So if you're running them on a file that is opened with `flag f/t` then the pane will close again immediately. Try a txt file if your editor is something like vim or nano. This is also what I'm talking about with your solutions. They don't achieve the same thing, so either mention what they do differently *or* change the behavior to be in line with the former.

**Comment by laggardkernel** [comment]
Sorry, my bad. I didn't notice the `rifle ` thing there. You're right, my keybindings are doing different things. I'll correct it on the wiki page.

**Comment by caikaidi** [comment]
When I move the cursor to a picture file, ranger shows
```
a bytes-like object is required, not 'NoneType'
```
Are there any instructions to fix this?

**Comment by caikaidi** [comment]
When I move the cursor to a picture file, ranger (python3)shows
```
a bytes-like object is required, not 'NoneType'
```
After switching to python2, it shows
```
str
```
in red, still no picture previewed.
Are there any instructions to fix this?

**Comment by toonn** [comment]
@caikaidi, gonna need more information. What version of ranger are you running? Do you have pillow installed?

**Comment by caikaidi** [comment]
@toonn , I'm using 
iTerm2 build 3.3.8beta3
ranger version: ranger-master
Python version: 3.7.4 (default, Sep 28 2019, 16:39:19) [Clang 11.0.0 (clang-1100.0.33.8)]
Locale: en_US.UTF-8
Successfully installed pillow-6.2.1
<img width="1132" alt="Screen Shot 2019-12-27 at 8 03 57 PM" src="https://user-images.githubusercontent.com/30190144/71516473-2a90ab00-28e4-11ea-8de5-f0a044dc4444.png">

**Comment by toonn** [comment]
@caikaidi, I can't reproduce the problem. Do you get an error when you run the following in ranger? `:eval import PIL`

**Comment by caikaidi** [comment]
@toonn Nothing happened, no error, I guess pillow is installed well.

**Comment by toonn** [comment]
@caikaidi, your checkout of master is recent? Could you try a non beta build of iTerm?

**Comment by caikaidi** [comment]
@toonn  Everything is up to date.  Beta build of iTerm is updated when I trying to fix this problem.
I think the error comes from `.config/ranger/scope.sh`:
```python
    image/*)
            local orientation
            orientation="$( identify -format '%[EXIF:Orientation]\n' -- "${FILE_PATH}" )"
            if [[ -n "$orientation" && "$orientation" != 1 ]]; then
                # ...auto-rotate the image according to the EXIF data.
                convert -- "${FILE_PATH}" -auto-orient "${IMAGE_CACHE_PATH}" && exit 6
            fi
```
If I change `convert -- "${FILE_PATH}"` to some path, like `convert -- "~/Desktop"`, there are still errors, but if I change it to `convert -- decode("~/Desktop")`,  or `convert -- decode("${FILE_PATH}")`, the error disappears and the picture can be previewed in text. Just like `vim somePicture.png`.

Will this found help?

**Comment by toonn** [comment]
That's weird, what's this `decode`? "~/Desktop" isn't a path to an image so it sounds like you're making the convert command error, making scope continue with the next command.
*But* nothing in scope could explain getting a *python* error.

What do you mean by "previewed in text?"

Could you run with `ranger --debug` to provide the full error? Also, for good measure, try running `ranger --clean` and then `:set preview_images_method iterm2`, `:set preview_images true`, if that works there's a problem in your config. (Both without changes to `scope.sh`)

**Comment by xeor** [comment]
Anyone looking into this? Do ranger have any plans for only supporting python 3? Might be easier to cleanup and fix this if it was a python3 only project..

**Comment by toonn** [comment]
Nope, we maintain backwards compatibility to 2.6.

**Comment by xeor** [comment]
@toonn oh.. That was worse than I thought. Any special reason for this? Python 2 is very soon to be unsupported. I see no `six` in the codebase either, does that mean that you need to write 2.6 code when submitting a patch? That might hold off a bunch of people wanting to fix issues like this..

**Comment by toonn** [comment]
It's not actually a big deal. There's a couple library functions you can't use. If checking some docs for compatibility is too big a hurdle that's unfortunate. But a couple contributions don't weigh up against compatibility with py2. Ranger's used by system administrators, many systems still run python 2 and will for several years *at least*. Then there's Pypy which isn't ever dropping py2 support and pypy3 is still in beta.

**Comment by xiaoger-liubu** [comment]
@toonn run with ranger --debug，

> That's weird, what's this `decode`? "~/Desktop" isn't a path to an image so it sounds like you're making the convert command error, making scope continue with the next command.
> _But_ nothing in scope could explain getting a _python_ error.
> 
> What do you mean by "previewed in text?"
> 
> Could you run with `ranger --debug` to provide the full error? Also, for good measure, try running `ranger --clean` and then `:set preview_images_method iterm2`, `:set preview_images true`, if that works there's a problem in your config. (Both without changes to `scope.sh`)

Python version: 2.7.17 (default, Dec 23 2019, 21:25:34) [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.16)]
Locale: None.None
Current file: '/Users/hx/Desktop/WechatIMG17.jpeg'

Traceback (most recent call last):
  File "/usr/local/Cellar/ranger-fm/HEAD-d8c363c/libexec/lib/python2.7/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/local/Cellar/ranger-fm/HEAD-d8c363c/libexec/lib/python2.7/site-packages/ranger/core/fm.py", line 381, in loop
    ui.draw_images()
  File "/usr/local/Cellar/ranger-fm/HEAD-d8c363c/libexec/lib/python2.7/site-packages/ranger/gui/ui.py", line 401, in draw_images
    self.browser.columns[-1].draw_image()
  File "/usr/local/Cellar/ranger-fm/HEAD-d8c363c/libexec/lib/python2.7/site-packages/ranger/gui/widgets/pager.py", line 124, in draw_image
    self.fm.notify(ex, bad=True)
  File "/usr/local/Cellar/ranger-fm/HEAD-d8c363c/libexec/lib/python2.7/site-packages/ranger/core/actions.py", line 173, in notify
    raise obj
TypeError: str

**Comment by laggardkernel** [comment]
Seems fixed. Close it.
