### ISSUE TITLE
preview images using kitty

### ISSUE THREAD

**Issue by joamatab** [ranger/ranger#1549]
How can we preview images using kitty terminal?

https://sw.kovidgoyal.net/kitty/kittens/icat.html

**Comment by toonn** [comment]
Install pillow. Change `rc.conf` to include: `set preview_images true` and `set preview_images_method kitty`.

**Comment by J-F-Liu** [comment]
[Viu](https://github.com/atanunq/viu) is also an option.

**Comment by toonn** [comment]
Is that kitty specific? It's far lower resolution than the native method though.

**Comment by joamatab** [comment]
Im on MacOs, miniconda3 python 3.7.2, and also tried with brew python 3.7.3
`pip install pillow ranger-fm`
in `~/.config/ranger/rc.conf` i have `set preview_images true` and `set preview_images_method kitty`

if I use`set preview_images_method iterm2` and iterm2 terminal images appear as broken

**Comment by toonn** [comment]
@joamatab, check in ranger whether PIL is installed for the correct python by running `:eval import PIL`, you shouldn't get an error (check the log with `W`).

What's your `TERM` set to? It *needs* to contain (or is it end with) `kitty`.

The `iterm2` method can have problems that are not due to ranger, some solutions are described in #864.

**Comment by joamatab** [comment]
TERM was set to `xterm-256color`, I set it up to xterm-kitty and images show now :tada:  thank you for your help toonn!!

any ideas how can we have images working inside a tmux terminal as well? by default tmux sets `TERM` to `screen-256color`

**Comment by toonn** [comment]
The kitty preview method doesn't currently work in tmux. No one's had time to look into whether it's possible since @mark-dawn implemented the method. There's some unfinished work around the method but I think that was about positioning or scaling rather than tmux support.

**Comment by Davincible** [comment]
@toonn Any progress on the tmux issue since?

**Comment by toonn** [comment]
Unfortunately not, we'd love for someone to dig into this!

**Comment by ppwwyyxx** [comment]
The reason it does not work in tmux is that the escape code that kitty expects to see is not recognized by tmux and will be removed by tmux.

A workaround to make it work is to 
1. User should enable the "allow-passthrough" option in tmux config
2. If `$TMUX` is detected, ranger should wrap the kitty image escape sequence with the "tmux passthrough escape code" so that tmux can properly send these codes to the terminal.
  https://github.com/ppwwyyxx/dotfiles/blob/1805b00e2b65d9835bc608bf6df09e9d84655c3f/scripts/tmux-escape#L54-L63 demonstrates how to do this. However with this trick it's unable to control where the image is displayed in the terminal - which I don't understand how to fix.

**Comment by toonn** [comment]
@ppwwyyxx, thank you for that pointer. That definitely sounds like a step in the right direction. Have you figured out the issue wrt placement since then?

**Comment by mark-dawn** [comment]
Sorry for not having commented in a long time, work took a bit over my time and I stopped using kitty so I haven't kept up with it. 

I remember trying to try to get tmux to work but to no avail, looking into escape codes might be the way but I didn't manage to make it work. There is a note and commented code [here](https://github.com/ranger/ranger/blob/master/ranger/ext/img_display.py#L586), that should point anyone brave enough to where the check needs to happen.

 Also the issue about the `$TERM` environment variable needed to contain kitty is to stop ranger from hanging if you load it up with previews in any other terminal (like in a non graphical shell while trying to fix something). I think I left a comment about that in the standard configuration file but it might got lost or I never actually did it.

Finally when I implemented this kitty's image IPC protocol was still in the work and had some inconsistencies, so nowadays something might be broken or might be easier to implement than then.

**Comment by I-like-stuff** [comment]
I am using NixOS so the old method of just putting ``set preview_images true``  & ``set preview_images_method kitty`` in the rc.conf does not work and instead I'd have to specify the terminal in the scope.sh shell script but I genuinely have no idea how to do that on my own so would love some help

**Comment by toonn** [comment]
@I-like-stuff, Nix doesn't change your TERM setting. Unless you explicitly tell it to, so it should still be `xterm-kitty`, you can check by running `env` or `echo $TERM`.

As far as making changes to `scope.sh` is concerned, Nix doesn't affect that. Run `ranger --copy-config=scope` and then edit `$XDG_CONFIG_HOME/ranger/scope.sh`.

**Comment by PhilT** [comment]
> I am using NixOS so the old method of just putting `set preview_images true` & `set preview_images_method kitty` in the rc.conf does not work and instead I'd have to specify the terminal in the scope.sh shell script but I genuinely have no idea how to do that on my own so would love some help

I'm using NixOS too and if you've not changed anything else, `set preview_images_method kitty` in `~/.config/ranger/rc.conf` is all you need. As long as `echo $TERM` is returning `xterm-kitty` (as toonn mentions), you should be good.

**Comment by reinux** [comment]
Seems to work all right, but is anyone getting flickering right as the image loads?

**Comment by newptcai** [comment]
Nowadays you can also install ranger and pillow via 

```
uv tool install --with pillow ranger-fm
```
