### ISSUE TITLE
Wiki: Are custom image previews shown via w3m?

### ISSUE THREAD

**Issue by wilecoyote2015** [ranger/ranger#1553]
On the video previews page ( https://github.com/ranger/ranger/wiki/Video-Previews ), it is stated that the custom preview images generated according to scope.sh would always be displayed using `w3mimgdisplay`.

However, according to the code, it seems to me that the general `ImageDisplayer` subclasses are used to display the generated images. Just like the regular image previews. 
This seems reasonable to be because custom image previews may be shown also in terminals where `w3mimgdisplay` does not work.

I am using Wayland where `w3mimgdisplay` does not work at all. However, using the Kitty preview method with the kitty terminal works perfectly for both, image and video previews. So thanks for implementing that by the way!

Hence, maybe the documentation should be updated accordingly?

**Comment by toonn** [comment]
That was probably written when we only had w3m previews. Feel free to update that : )

**Comment by wilecoyote2015** [comment]
Done :)
