### ISSUE TITLE
How to exit and cd into last dir you were on ranger?

### ISSUE THREAD

**Issue by rudevdr** [ranger/ranger#1554]
I want to achieve this:

1. Open ranger
2. Go inside a dir, say '/home/user/testdir'
2. Press a key, say 'Q'
3.  Ranger quits and user changes dir to '/home/user/testdir'

What I don't want:

1. I am aware of `S` keypress. It drops me to a shell inside ranger and I don't want that. I want ranger to quit.
2. I am also aware of `--choosedir` args. Using that method will change dir every time but I want to change dir only on pressing certain key. #915 [(more)](https://github.com/ranger/ranger/blob/master/examples/bash_automatic_cd.sh)

How can this be achieved on ranger? I didn't find anything on docs or the internet.

[more discussion](https://redd.it/bngtqt)

**Comment by toonn** [comment]
No real solution to this. It's oft requested but not as easy as people think.
You can source ranger, so start it like this `. ranger`. That'll cd to ranger's cwd when quitting. I guess you could make this dependent on the key you use to quit ranger by mapping `q` to "cd to original dir ranger was opened with; then quit" and `Q` to just quit. Still hackish and I'm not sure it's a good idea.

Best we have to offer is @Vifon's [deer](https://github.com/Vifon/deer) or [zranger](https://github.com/Vifon/zranger) but they only work with zsh.

**Comment by laggardkernel** [comment]
Easy.

```bash
function ranger {
    local IFS=$'\t\n'
    local tempfile="$(mktemp -t tmp.XXXXXX)"
    local ranger_cmd=(
        command
        ranger
        --cmd="map Q chain shell echo %d > "$tempfile"; quitall"
    )
    
    ${ranger_cmd[@]} "$@"
    if [[ -f "$tempfile" ]] && [[ "$(cat -- "$tempfile")" != "$(echo -n `pwd`)" ]]; then
        cd -- "$(cat "$tempfile")" || return
    fi
    command rm -f -- "$tempfile" 2>/dev/null
}
```

I'm think how to sync the location after you quit from a subshell. If you use `S` enter a subshell, when you quit the subshell, is there any way to make ranger sync to the location when you quit from the subshell?

**Comment by rudevdr** [comment]
Very well done. Thank you very much.

I am sure this is an useful feature. It will be great if this becomes an out-of-the-box feature.

**Comment by toonn** [comment]
@rudevdr, that function can never be *out-of-the-box* it needs to be defined for your shell. We have no intention to force shell configuration on people during install.

**Comment by toonn** [comment]
@laggardkernel, feel free to add this to [this wiki section](https://github.com/ranger/ranger/wiki/Integration-with-other-programs#changing-directories), having the choice of whether to quit and cd or just quit is a nice improvement.

**Comment by rudevdr** [comment]
So there is no way to change ranger's code to make this work? Is this a limitation and can only work when you call that function?

**Comment by toonn** [comment]
@rudevdr, just try to understand what that shell function does. It runs ranger and afterwards checks whether a file exists. If it does it changes directories. And the `Q` mapping writes to that file.
*If* this was possible with a script we could ship that with ranger, but it's not because the `cd` would happen in the context of the script and be forgotten afterwards.

**Comment by laggardkernel** [comment]
@rudevdr I don't think it's easy to integrate this into ranger. Since ranger is run as a subprocess, I have no idea how to make ranger operate the parent process, the shell in this case.

**Comment by laggardkernel** [comment]
I also find a way to make ranger sync to the directory where you leave the subshell spawned by ranger.

Firstly, output the `$PWD` before you quit the subshell with custom keybindings for you shells (Bash or ZSH).

```bash
function dump_before_exit {
  if [[ -n $RANGER_LEVEL ]]; then
    echo "$PWD" >| "/tmp/picked"
  fi
  exit
}

# zsh
zle -N dump-before-exit dump_before_exit
bindkey '^Q' dump-before-exit

# bash
# bind '"\C-q":"dump_before_exit\C-m"'
```

Secondly, use hook in `~/.config/ranger/plugins/cd_after_exit.py` to trigger `cd` in ranger, after you exit the shell created by ranger.

```python
# This plugin reads dir from /tmp/picked and cd into that location

from __future__ import absolute_import, division, print_function

import os
# import subprocess

import ranger.api
from ranger.ext.spawn import check_output


HOOK_INIT_OLD = ranger.api.hook_init


def hook_init(fm):
    def cd_after_eixt(signal):
        input_file='/tmp/picked'
        result=''
        # read the file directly, cause Popen doesn't spawn shells
        # No env vars could be expanded.
        if os.path.isfile(input_file):
            with open(input_file, 'r') as f:
                result = f.read().rstrip("\n")
            os.remove(input_file)

            if result and os.path.isdir(result):
                signal.origin.cd(result)

    fm.signal_bind("runner.execute.after", cd_after_eixt)
    return HOOK_INIT_OLD(fm)


ranger.api.hook_init = hook_init
```

There's one problem about the security. I'm not sure if I can add this one into the wiki as well. @toonn 

`/tmp` is accessible by all users on your machine. `$XDG_RUNTIME_DIR` may be a better choice to dump the location string before you exit the subshell. But `subprocess.Popen` doesn't run things in a shell and the environment variables are not available in it.

To expand `$XDG_RUNTIME_DIR` to the real path, we need to run `/bin/bash -c` by `subprocess.Popen` to read in the saved location string. I just don't bother to do this because no on uses my laptop except me. Anyone who need the security could do it by yourself.

**Comment by toonn** [comment]
@laggardkernel, feel free to add it in an appropriate place on the wiki. Just mention the issue there. We don't make any promises on the quality of things on the wiki so it's not a big deal.

**Comment by Aster89** [comment]
The issue #1414 is quite the same, so this is to facilitate the ones who find this issue first.

**Comment by francescoboc** [comment]
> Easy.
> 
> ```shell
> function ranger {
>     local IFS=$'\t\n'
>     local tempfile="$(mktemp -t tmp.XXXXXX)"
>     local ranger_cmd=(
>         command
>         ranger
>         --cmd="map Q chain shell echo %d > "$tempfile"; quitall"
>     )
>     
>     ${ranger_cmd[@]} "$@"
>     if [[ -f "$tempfile" ]] && [[ "$(cat -- "$tempfile")" != "$(echo -n `pwd`)" ]]; then
>         cd -- "$(cat "$tempfile")" || return
>     fi
>     command rm -f -- "$tempfile" 2>/dev/null
> }
> ```
> 
> This function lets you quit normally with `:q`, but changes your location if you quit with `Q`.
> 
> ~I'm thinking about how to sync the location after you quit from a subshell. If you use `S` enter a subshell, when you quit the subshell, is there any way to make ranger sync to the location back from the subshell?~

Uhm. This works, however, the first time that I exit ranger using Q I have a strange output in the terminal:
![image](https://user-images.githubusercontent.com/33369475/223709136-5f1b4627-abf3-41e5-a03c-463af01c7551.png)
After this first time, then the behavior is as expected... Any idea about how to solve this?

**Comment by IsaacPang** [comment]
@francescoboc , I had the same behaviour. I just added a `clear` command to that function. Purely for aesthetic reasons, like so:

```bash
function ranger {
    local IFS=$'\t\n'
    local tempfile="$(mktemp -t tmp.XXXXXX)"
    local ranger_cmd=(
        command
        ranger
        --cmd="map Q chain shell echo %d > "$tempfile"; quitall"
    )
    
    ${ranger_cmd[@]} "$@"
    if [[ -f "$tempfile" ]] && [[ "$(cat -- "$tempfile")" != "$(echo -n `pwd`)" ]]; then
        cd -- "$(cat "$tempfile")"; clear || return
    fi
    command rm -f -- "$tempfile" 2>/dev/null
}
```

**Comment by francescoboc** [comment]
@IsaacPang thank you but this is not really solving the problem, just hiding it under the rug...

**Comment by laggardkernel** [comment]
Can't reproduce it in my shell. But it seems like a shell prompt related problem. What about using the func in a shell without any init files loaded? @francescoboc 

- `bash --no-rc`
- `zsh --no-rcs`

**Comment by francescoboc** [comment]
> Can't reproduce it in my shell. But it seems like a shell prompt related problem. What about using the func in a shell without any init files loaded? @francescoboc
> 
> * `bash --no-rc`
> * `zsh --no-rcs`

The problem is still there:
![image](https://user-images.githubusercontent.com/33369475/224001663-e18ff41d-957a-4b0c-8bd9-9ecadd6a291a.png)
PS. the correct option for bash is `--norc`

**Comment by schaefsteven** [comment]
I'm getting the same bug as @francescoboc in Alacritty, but not in x-terminal-emulator. 
Strange that it would be not only the newlines, but it's also printing out "ranger."

@francescoboc , what terminal emulator are you using?

**Comment by francescoboc** [comment]
@schaefsteven I'm using WSL.

**Comment by toonn** [comment]
I'm pretty sure those strings are from Ranger attempting to set the window title.

**Comment by kohane27** [comment]
If someone wants a python script to do the trick, check out the project [ranger-quit_cd_wd](https://github.com/JohanChane/ranger-quit_cd_wd).

**Comment by alper** [comment]
I don't understand the reticence here. Lots of tools ship with shell specific modifications that often are required but also can be optional.

Writing the path to the ranger config directory (which exists anyway) and then catching that, seems reasonable.

**Comment by djorgens2** [comment]
Just a thought - how about a 'feature' to copy the navigated path to the clipboard/buffer? I love the ranger concept - it enhances the navigation experience thru deep/complex application trees. My initial thought was to right click (or select) the path navigated allowing a follow up paste. At any rate - kudos to the developers!

**Comment by LesserSpottedAustralianSquirel** [comment]
The solution; to make ranger exit the subdirectory you were last in at ranger; rather than when you first started ranger 
is as follows

# at the terminal type (NB ". <space> ranger)
alias R=". ranger"
R
<You should be in ranger now, changed directory. hit q>
pwd
<hopefully you are in a different directory>


# To setup this alias every time you go into terminal or putty
#Debian tested
open a terminal 
cd ~
pwd
<Hopefully you are now in your home directory>

ls -la
vi .bashrc
# vi command to go to the bottom of file
G
#vi command to insert line
i
#add the following line
alias R=". ranger"
#press escape key
escape key
:w
:q
exit

cat .bashrc
#hiopefully you have an alias command at the end


# test it all works
# start terminal 
R
change directories
q
Hopefully you are where you want to be

**Comment by gplusplus314** [comment]
> Uhm. This works, however, the first time that I exit ranger using Q I have a strange output in the terminal: ![image](https://user-images.githubusercontent.com/33369475/223709136-5f1b4627-abf3-41e5-a03c-463af01c7551.png) After this first time, then the behavior is as expected... Any idea about how to solve this?

I just stumbled across this GitHub issue and ran into this same bug. I figured out a workaround and somewhat of an explanation, although I'm not 100% sure why and this is somewhat of a guess.

The Ranger console's `shell` command, which is invoked with `map Q chain shell ...` in the original code snippet, seems to do something weird with the shell's state that is managed by `ncurses` for drawing the TUI. When completely avoiding this command, everything seems to work without that one-time-per-shell-session bug.

Here's a workaround that I'm happy with for my purposes.

First, add this to `~/.config/ranger/commands.py`:
```python
class quitallcd(Command):
    def execute(self):
        if self.arg(1):
            tmp_file = self.arg(1)
            cur_dir = self.fm.thisdir.path
            os.system('echo "' + cur_dir + '" > "' + tmp_file + '"')
            self.fm.execute_console("quitall")
```
Then let's modify the shell function that was provided by @laggardkernel earlier in the thread (in your shell's RC file, so `~/.zshrc` in my case):
```sh
# Allow Ranger to `cd` your current shell by exiting with capital Q
function ranger {
  local IFS=$'\t\n'
  local tempfile="$(mktemp -t tmp.XXXXXX)"
  local ranger_cmd=(
    command
    ranger
    --cmd="map Q quitallcd \"$tempfile\""
  )
  
  ${ranger_cmd[@]} "$@"
  local target_dir=$(cat -- "$tempfile" | tr -d ' ')
  local cwd=$(echo -n `pwd` | tr -d ' ')
  if [[ -f "$tempfile" ]] && [[ "$target_dir" != "" ]] && \
      [[ "$target_dir" != "$cwd" ]]; then
    cd -- "$target_dir"
  fi
  command rm -f -- "$tempfile" 2>/dev/null
}
```

Ugly? Yes. Works? Yes. But hey, good enough for my purposes and I figured it might help someone else out there who ends up here from a search engine.

**Comment by razouck** [comment]
> > Uhm. This works, however, the first time that I exit ranger using Q I have a strange output in the terminal: ![image](https://user-images.githubusercontent.com/33369475/223709136-5f1b4627-abf3-41e5-a03c-463af01c7551.png) After this first time, then the behavior is as expected... Any idea about how to solve this?
> 
> I just stumbled across this GitHub issue and ran into this same bug. I figured out a workaround and somewhat of an explanation, although I'm not 100% sure why and this is somewhat of a guess.
> 
> The Ranger console's `shell` command, which is invoked with `map Q chain shell ...` in the original code snippet, seems to do something weird with the shell's state that is managed by `ncurses` for drawing the TUI. When completely avoiding this command, everything seems to work without that one-time-per-shell-session bug.
> 
> Here's a workaround that I'm happy with for my purposes.
> 
> First, add this to `~/.config/ranger/commands.py`:
> 
> class quitallcd(Command):
>     def execute(self):
>         if self.arg(1):
>             tmp_file = self.rest(1)
>             cur_dir = self.fm.thisdir.path
>             with open(tmp_file, "w") as f:
>                 f.write(cur_dir)
>             self.fm.execute_console("quitall")
> 
> Then let's modify the shell function that was provided by [@laggardkernel](https://github.com/laggardkernel) earlier in the thread (in your shell's RC file, so `~/.zshrc` in my case):
> 
> # Allow Ranger to `cd` your current shell by exiting with capital Q
> function ranger {
>   local IFS=$'\t\n'
>   local tempfile="$(mktemp -t tmp.XXXXXX)"
>   local ranger_cmd=(
>     command
>     ranger
>     --cmd="map Q quitallcd $tempfile"
>   )
>   
>   ${ranger_cmd[@]} "$@"
>   local target_dir=$(cat -- "$tempfile" | tr -d ' ')
>   local cwd=$(echo -n `pwd` | tr -d ' ')
>   if [[ -f "$tempfile" ]] && [[ "$target_dir" != "" ]] && \
>       [[ "$target_dir" != "$cwd" ]]; then
>     cd -- "$target_dir"
>   fi
>   command rm -f -- "$tempfile" 2>/dev/null
> }
> 
> Ugly? Yes. Works? Yes. But hey, good enough for my purposes and I figured it might help someone else out there who ends up here from a search engine.

You gotta add the line `from ranger.api.commands import *` to `commands.py` if it's not there, otherwise ranger won't even open.
