### ISSUE TITLE
Remapping the Navigating Keys for the Colemak Keybaord Layout

### ISSUE THREAD

**Issue by theniceboy** [ranger/ranger#1555]
HI, I am a [Colemak Keyboard Layout](https://colemak.com/) user, and I just started to learn how to use ranger.

In my keyboard, the `h`, `j`, `k`, and `l` keys are not all so easy to reach, so I want to remap those keys. I found [this isssue](https://github.com/ranger/ranger/issues/8) that was closed 8 years ago, which addressed my needs. **However**, the solution no longer works, since it relies on `keys.py`, which has already been removed ([change log here](https://github.com/ranger/ranger/blob/7f6f6b13894be2f150f4789305e009b7b9f8df63/CHANGELOG.md#2011-10-11-version-150))

Is there a solution for Colemak users like me, or other keyboard layout users? Any help would be much appreciated!

-- David

**Comment by toonn** [comment]
WOW! Now that's an old version : )
We've since moved to having an `rc.conf` for configuration. You can generate one by running `ranger --copy-config=rc`, it'll be in $XDG_CONFIG_HOME/ranger/rc.conf`. From there it should be easy enough to figure out how to change mappings. Good luck 👍

**Comment by theniceboy** [comment]
Thank you so much! I set the environment variable `ranger_load_default_rc` to `false` according to the directions given from your command `ranger --copy-config=rc`. It works! I will be spending my next 5 hours configuring ranger! It is the best thing!

Thank you again!

**Comment by toonn** [comment]
You don't *have* to set that variable btw. You could also overwrite only the things you want to in your `rc.conf`. Enjoy though : )

**Comment by TheColorman** [comment]
@theniceboy you wouldn't happen to still have that config? It's either asking you or me spending an additional 5 hours on it 😅

**Comment by theniceboy** [comment]
@TheColorman https://github.com/theniceboy/.config/blob/master/ranger/rc.conf

:)

**Comment by TheColorman** [comment]
Ah, right in front of me haha
