### ISSUE TITLE
improve highlight flexibility in scope.sh

### ISSUE THREAD

**Issue by Boruch-Baum** [ranger/ranger#1556]
Currenlty, file `scope.sh` hard-codes all its colorization configurations, including the options being sent to the external `highlight` program for colorization. That program, `highlight`, offers a zillion [colorization styles](http://www.andre-simon.de/doku/highlight/en/theme-samples.php) and makes available an environment variable `HIGHLIGHT_OPTIONS` so that the style can be set without needing to copy and modify `scope.sh` just for that. Also, because `scope.sh` explicitly calls `highlight` with a hard-coded style, any user-selected style in that environment variable `HIGHLIGHT_OPTIONS` is ignored.

My recommendation is to delete the assignment of the highlight_style (currently line 39), modify the call to `highlight` (currently line 232) to not pass a style argument, and possibly add to the documentation that a particular highlight style can be set using the environment variable. For people using highlight in other contexts, this gives them allows them to uniformly change the setting across all uses of `highlight` just as the developers intended.

Also, I see that the project made allowance to choose `pygmentize` instead of `highlight`, but commented out the actual invocation. If you want to offer the choice, set a variable COLORIZER near line 39, and perform a case/esac on it around line 232. Better would be to have a config option in file `rc.conf` to set that variable.

If you want, I could make this a pull request, but it's quite trivial so your option.

**Comment by toonn** [comment]
I like it. I'm thinking doing something like `HIGHLIGHT_OPTIONS=${$HIGHLIGHT_OPTIONS:-defaultWeCurrentlyUse}`. I'm not sure scope inherits the environment but we'll see. This might affect our sandboxing PR though.

I don't like the colorizer variable. What I'd prefer is falling through, like we do for mutool/pdftotext, attempt highlight and if it fails attempt pygmentize.

**Comment by toonn** [comment]
It'd be great if you could test that PR ^

**Comment by Boruch-Baum** [comment]
Continued [here](https://github.com/ranger/ranger/pull/1557#issuecomment-492803797)
