### ISSUE TITLE
Image preview shows broken image

### ISSUE THREAD

**Issue by Riiskyy** [ranger/ranger#1560]
#### Runtime Environment

- Operating system and version: 4.19.42-1-MANJARO (i3 edition)
- Terminal emulator and version: Urxvt 9.22-7
- Python version: 3.7.3 (default, Mar 26 2019, 21:43:19) [GCC 8.2.1 20181127]
- Ranger version/commit: ranger-master 1.9.2
- Locale: en_GB.UTF-8

#### Current Behavior
Preview will initially show the full image but then 'breaks' the image after a second.

![alt text](https://i.imgur.com/TUHp2rX.jpg)
#### Expected Behavior

Display full image

![alt text](https://i.imgur.com/RFipwFC.png)
#### Context

I have tried disabling the rc.conf in ~/.config/ranger/ however when I do that I get ASCII render of the image. This only seems to affect about a 1/3 of the images in my library. The image previews were working fine until I created a new copy of the rc.conf file (backing up the one that was already there, not sure if that was the manjaro one or the one that was produced after running `--copy-config=all`). I had added just a few customisations to the new file but this is when problems arose. So I renamed the backup file so it would be used for the config, however the issue with image previews remained and I can't seem to get it working again.

**Comment by toonn** [comment]
I suspect you're using the w3m previewing method? Try the urxvt method.

I recommend *against* `--copy-config=all` only `--copy-config` the config files you want to edit. Otherwise updates can break because of outdated config files.

**Comment by Riiskyy** [comment]
> I suspect you're using the w3m previewing method? Try the urxvt method.
> 
> I recommend _against_ `--copy-config=all` only `--copy-config` the config files you want to edit. Otherwise updates can break because of outdated config files.

If I select urxvt nothing displays at all I tried wtichting over to the version with pixbuf and still no preview

**Comment by toonn** [comment]
Hmm, @Vifon, can you troubleshoot this?

**Comment by Riiskyy** [comment]
Ok so I tried re-installing ranger and now I can see image previews without the image breaking using urxvt method. However it now completley ignores the terminal background and setis it to nothing. It also causes some overlap with the file information at the top.

![2019-05-25-103302_915x484_scrot](https://user-images.githubusercontent.com/30751766/58366936-e9a96180-7ed0-11e9-83e5-ae466b4059d1.png)

As you can see the blue background colour from my earlier images is on realy down the right hand side of the window for a few pixels.

**Comment by Riiskyy** [comment]
This example probably explains things better. I also tried removing and re-installing w3m but still no change.

![2019-05-27-105839_915x484_scrot](https://user-images.githubusercontent.com/30751766/58412479-69b8fe00-806e-11e9-9dd4-5c333cd012e1.png)

**Comment by Riiskyy** [comment]
Ok, I managed to get the previews working, to do this I had to do the following:
+ `enable set preview_script`
+ `set use_preview_script true`
+ `set method to w3m`
Without the above I got no image previews at all (I had previously disabled the preview script as pre previous advice. I then changed the `draw_borders` to true and I no longer got black bars. I found this on this wiki  page https://github.com/ranger/ranger/wiki/Image-Previews seems a shame  as I really like the look without borders

**Comment by toonn** [comment]
You could try the ueberzug method. It's not in a release yet though.

**Comment by Riiskyy** [comment]
How would I go about trying that method if it isn't in a release?

**Comment by toonn** [comment]
Run the master branch : ) Since you're on arch you can get it from the AUR `pacaur -S ranger-git` (iirc). Or you can clone the repo and install manually, `make install`.

**Comment by Riiskyy** [comment]
Ok, I might give that a try at some point, thank you. For now I have switched over to kitty instead or Urxvt and image previews are working without borders. There is already a wiki article noting this problem with no borders so I think this can be closed.

**Comment by toonn** [comment]
Alright, image preview support for kitty is second only to the support for terminology so that's a fine solution : )
