### ISSUE TITLE
sshfs mounted paths - severe lag by ranger

### ISSUE THREAD

**Issue by cvr** [ranger/ranger#1564]
#### Runtime Environment
- Operating system and version: Debian Stretch 9.9
- Terminal emulator and version: rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
- Python version: Python version: 3.5.3 (default, Sep 27 2018, 17:25:39) [GCC 6.3.0 20170516]
- Ranger version/commit: ranger 1.9.2
- Locale: en_GB.UTF-8

#### Current Behavior
In paths mounted with sshfs, ranger lags severely.

#### Expected Behavior
No lag.

#### Context
I have remote paths mounted with sshfs. When ranger goes to such location it starts to lag severely. Also, when one changes directory out of the sshfs mounted area, it still lags and becomes unresponsive.

#### Possible Solutions
I believe the problem is due to I/O bandwidth due to the following operations:
* disk usage (at status bar),
* file count for selected path (appearing in the middle pane, to the right of each folder).

This issue was partly solved by setting
```
set display_free_space_in_status_bar false
set automatically_count_files false
```
in `~/.config/ranger/rc.conf`. However, range still has significant lag as there is no way to remove the file count when we select one path in the middle pane. One solution would be to eliminate such count, via `~/.config/ranger/rc.conf`.

#### Steps to reproduce
1. Mount a remote area through sshfs, especially a system with a large number of files/directories and disk usage.
2. With ranger navigate through those paths.
3. Compare against simple use of the shell to achive this.

**Comment by cvr** [comment]
Disabling the following options in `rc.conf` improves ranger's responsiveness:
```sh
set display_size_in_main_column false
set display_size_in_status_bar false
```
However it still presents a lag while closing down.

**Comment by toonn** [comment]
I'm closing this in favor of #1025. #151 is also similar and #1173. All of these would probably be helped by a less synchronous ranger. #192 is some previous work on this for previews and there's a little bit of discussion of another part of the issue in #1063.

Aside from the solution you found, other stopgap measures are disabling previews or using ranger's `freeze_files` setting.
