### ISSUE TITLE
Use a safe working directory for image preview processes

### ISSUE THREAD

**Issue by FichteFoll** [ranger/ranger#1565]
#### Runtime Environment

- Operating system and version: Arch
- Terminal emulator and version: alacritty
- Python version: 3.7
- Ranger version/commit: 6315c2f9 (current master)
- Locale: en_US.UTF-8

#### Current Behavior

When an image is previewed for the first time using an external process previewer, such as w3m or ueberzug, the new process is launched in the currently shown directory.

However, the preview process sticks around and will continue to hold a handle on the original working dir even when you navigate to different folders/tab/files. This may cause unmounting to fail, for example.

#### Possible Solutions

Use a safe working directory, e.g. `$HOME` or something that ranger controls.

#### Steps to reproduce
1. Preview an image using the w3m or ueberzug method in a mounted directory.
2. Use ranger as usual, eventually leaving the mounted directory.
3. Attempt to unmount said directory.

**Comment by toonn** [comment]
Could you check whether #1532 fixes this?

**Comment by FichteFoll** [comment]
I highly doubt it, since #1532 sandboxes the preview script (`scope.sh`), not the image previewer which is set with `pager.set_image`. However, `bwrap`, by default, [does launch the process in `$HOME`](https://jlk.fjfi.cvut.cz/arch/manpages/man/bwrap.1#ENVIRONMENT).

Regardless, I believe this should be the default and not hidden behind an option, so I might wrap this up in a quick PR. No promises, though.

**Comment by toonn** [comment]
Maybe consider something like `${XDG_RUNTIME_DIR:-$HOME}`.
