### ISSUE TITLE
:setlocal does not work on some directories

### ISSUE THREAD

**Issue by nQ8hzkZw** [ranger/ranger#1566]
#### Runtime Environment

- Ranger version/commit: ranger-master 1.9.2

#### Current Behavior
`:setlocal` command does not change settings if directory name (or path) contains a character from the list: `()[]{}$^,\';:"`.

#### Steps to reproduce
1. Create a directory `:mkdir test(1)` and some files inside or rename any other directory by adding a character from the list: `()[]{}$^,\';:"`.
2. Enter the created/renamed directory.
3. The `:setlocal sort_reverse True` command does not sort files and subdirectories. Any other settings also have no effect.

**Comment by toonn** [comment]
I can reproduce this. We need to make escaping possible with `setlocal`.
