### ISSUE TITLE
"Enter" doesn't work

### ISSUE THREAD

**Issue by unInstance** [ranger/ranger#1568]
"Enter" doesn't work. I had such an issue with i3wm but i fixed it by replacing "bindsym $mod+Return exec i3-sensible-terminal" with "bindsym $mod+KP_Enter exec i3-sensible-terminal". I can't send a command to the program even.

I guess it is the same issue, but I don't know where do I have to change the key. I went over rc.conf but found nothing about "Enter" key.f

**Comment by toonn** [comment]
The key we map is commonly called "carriage return/CR/return" and we map it as `<CR>`. `<enter>` and `<return>` are aliases for the exact same key. The one on the keypad is commonly referred to as "enter," and it simply happens to work for me. I'm not sure why, could you find out what keycodes your enter and return keys result in?

**Comment by unInstance** [comment]
$ xmodmap -pke | grep Enter
keycode 104 = KP_Enter NoSymbol KP_Enter

**Comment by toonn** [comment]
Return and enter are respectively 44 and 84 for me and they both work in ranger. They're 36 and 104 for someone else and enter only works there with numlock on. I don't have a numlock so that's why I couldn't reproduce the problem.

**Comment by unInstance** [comment]
Yeah, but how can I change the value?

**Comment by toonn** [comment]
Change what value? Enter should just work once you turn numlock on.

**Comment by toonn** [comment]
Could you test the PR I just opened?

**Comment by unInstance** [comment]
> Change what value? Enter should just work once you turn numlock on.

IT WORKS

**Comment by toonn** [comment]
@unInstance, yeah but that PR is about making it work regardless of Num Lock. Could you test it? I can't since I don't have a Num Lock : |

**Comment by unInstance** [comment]
If i just have to install ranger-git package form AUR then no, it doesn't work.

**Comment by unInstance** [comment]
PR works fine
