### ISSUE TITLE
Linemode does not show/work

### ISSUE THREAD

**Issue by ranisalt** [ranger/ranger#1572]
#### Runtime Environment
- Operating system and version: Arch Linux
- Terminal emulator and version: kitty 0.14.0
- Python version: 3.7.3
- Ranger version/commit: 1.9.2
- Locale: en_US.UTF-8

#### Current Behavior
Changing linemode does not affect ranger in any way. There is no message on the console. `--debug` also does not help.

#### Expected Behavior
Changing to a different line mode should show different information somewhere.

#### Context
I'm trying to organize some images by resolution and I thought that `fileinfo` linemode should display the output of `file`, which contains resolution. However, neither using `:linemode fileinfo` or adding `default_linemode fileinfo` to rc.conf change a thing. Maybe the linemode is hidden and I am missing the shortcut to show it?

Here's what shows right after typing `:linemode fileinfo`:

![image](https://user-images.githubusercontent.com/1993083/58533199-5f664380-81d7-11e9-8430-d21e170bd3be.png)

That is exactly the same thing that shows before the command, that is, it does nothing.

**Comment by toonn** [comment]
Try disabling file and image previews. The extra info's probably just getting cut off.
