### ISSUE TITLE
ranger requires python 2.6, but uses 2.7 features

### ISSUE THREAD

**Issue by mova** [ranger/ranger#1573]
Running ranger with python 2.6.6 yields:
```
ranger
Traceback (most recent call last):
  File "/home/user/.bin/ranger", line 35, in <module>
    import ranger  # NOQA pylint: disable=import-self,wrong-import-position
  File "/home/user/.apps/ranger/ranger/__init__.py", line 49, in <module>
    VERSION = version_helper()
  File "/home/user/.apps/ranger/ranger/__init__.py", line 24, in version_helper
    git_describe = subprocess.check_output(['git', 'describe'],
AttributeError: 'module' object has no attribute 'check_output'
```
apparently this feature needs 2.7:
(subprocess.check_output() module object has out attribute 'check_output')[https://stackoverflow.com/questions/26894024/subprocess-check-output-module-object-has-out-attribute-check-output]

**Comment by toonn** [comment]
Woops, mea culpa.

**Comment by toonn** [comment]
@toonn saves the day! (This was not the fuckup you were looking for :hand_sweep:)
Should be fixed on master. (No attempts to force push to master were made during the release of this fix : >)
