### ISSUE TITLE
I want to contribute and to say thanks. day of the newbie

### ISSUE THREAD

**Issue by SHV007** [ranger/ranger#1579]
#### Runtime Environment

- Operating system and version: 
- Terminal emulator and version: 
- Python version: 
- Ranger version/commit: 
- Locale: 

#### Current Behavior
when I quit by typing only "q" (without colons) the program quits but after a while it's consuming alot of cpu resource by runing in the background and in "htop" one of the cpu cores is running on 100% load
#### Expected Behavior
when I quit by typing only "q", then an error should arise or it could just quit like with :q
#### Possible Solutions
I don't really have one because I'm pretty much a newbie in python. (wish I could contribute by writing some of the code...)
#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```

```

**Comment by toonn** [comment]
Keep an eye on our issue tracker, might add some "good first issue" labels in the next week or two.

Could you check whether #1367 is the same/a similar issue?

**Comment by SHV007** [comment]
Thanks
