### ISSUE TITLE
Is there method to run action on directory by regex?

### ISSUE THREAD

**Issue by 717g301github** [ranger/ranger#1582]
Is there any method to run on directory by regex or by verification or checks what is inside of directory?

For example, directory like `somebody@example.com` could be Maildir folder and easily read by `mutt -f somebody@example.com`

Maybe I could run some small script to verify if it is maildir and on positive result engage mutt?

**Comment by toonn** [comment]
You can definitely write a rifle rule that matches on a regex, check the comments at the top of `~/.config/ranger/rifle.conf` (get it by running `ranger --copy-config=rifle`).

I don't think you can override the default behavior of entering the directory though. But you can always hit `r` and select one of the matching rules.

**Comment by 717g301github** [comment]
match *.\@*.\.$*, has mutt, directory = mutt -f $@

Is the above something workable?

**Comment by toonn** [comment]
Not sure what you want it to match? It currently matches "`ANYCHAR`@`ANYCHAR``ANYCHAR``EOL``0 or more`, I'm not sure you can repeat the `EOL/$` character that way. I think you'd rather want something like `.+@.+`, optionally adding `\..+` *if* you want to require a dot in the domain.

**Comment by 717g301github** [comment]
That works well, thank you
