### ISSUE TITLE
Ranger crashed

### ISSUE THREAD

**Issue by taigacute** [ranger/ranger#1588]
#### Runtime Environment

- Operating system and version: mac os 10.13.6
- Terminal emulator and version: iterm2 3.2.9
- Python version: Python 3.7.3
- Ranger version/commit: 1.9.2
- Locale: 
```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="zh_CN.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

#### Current Behavior

After entering the directory, move some files up and down, the program crashes. 
It will crash frequently. There may be a problem with my configuration？ Help
#### Expected Behavior
work well
#### Context

doesnt see any similiar issue.
#### Possible Solutions
N/A
#### Steps to reproduce
1. brew install ranger
2. brew install highlight
3.ranger --copy-config=all
4. add preview photo support 
```
set preview_images true
set preview_images_method iterm2
```
5. add plugin `https://github.com/alexanderjeurissen/ranger_devicons`
6. open ranger  and hjkl
7. Boom
#### Traceback
dont know how to debug ranger

## ScreenShot
maybe you need.i found the title changed to ranger(highlight) or ranger(bash) the ranger will be crashed. 
![ranger](https://user-images.githubusercontent.com/41671631/59275759-87ea4500-8c8f-11e9-979e-2b917a7b36e8.gif)

**Comment by taigacute** [comment]
i removed the `scope.sh`, but the problem still exist
![ranger](https://user-images.githubusercontent.com/41671631/59278414-81120100-8c94-11e9-9db8-3dc2e472c69f.gif)

**Comment by taigacute** [comment]
this is the case of title chaged to ranger(highlight)

![ranger](https://user-images.githubusercontent.com/41671631/59279031-cd117580-8c95-11e9-87ac-1636d82d32c7.gif)

**Comment by toonn** [comment]
Hmm, weird. Normally you can check running tasks with `w`. That may not work if it's hanging though.

If you want to disable scope you have to `set use_preview_script false`. Can you reproduce the problem if you run `ranger --clean`? That should run with default configuration.

**Comment by taigacute** [comment]
if  i removed the `.config/ranger`, it works. dont know why

**Comment by toonn** [comment]
Do you want to customize `rc.conf` or `rifle.conf`? If not you can just leave it like this. If you do want to customize them only copy the specific file you want to customize with `--copy-config`.

**Comment by taigacute** [comment]
i delete scope.sh. only rc.conf and rifle.conf. add icon and preview 。 not customize all config .

**Comment by toonn** [comment]
I suspect the plugin is to blame btw. It's just hard to prove so.

**Comment by taigacute** [comment]
maybe you are right . i use default config .work well.
