### ISSUE TITLE
Feature request: ability to move (= reorder) tabs

### ISSUE THREAD

**Issue by prosoitos** [ranger/ranger#1592]
I don't mean `tab_move` or the ability to move from one tab to another as this is already implemented, but the ability to move the position of the tabs relative to each other.

When deleting tabs and opening new ones, the tab numbers don't get reset and tabs opened one right after the other may end up far apart, making jumping back and forth less easy (I know I can jump to a tab by its number or make big jumps, but `tab_move 1` and `tab_move -1` remain the ones I find the most convenient and being able to re-order tabs would be nice.

Note: maybe this feature already exists and I missed it?

**Comment by toonn** [comment]
This functionality already exists, it's in `1.9.2`. Default bindings are `<a-l>` and `<a-r>`. I'm not sure why there's no mention of it in `?c`, should really look into why that doesn't always work. But I noticed it's *not* in the manpage either, this should really be documented there.

**Comment by prosoitos** [comment]
I saw `<a-l>` and `<a-r>` in the default rc.conf file. But, unless something is weird in my system, those are the default bindings for `tab_move 1` and `tab_move -1` which I use all the time.

What I was hoping for was the ability, *not* to switch which tab is selected, but to move the tab itself relative to the other tabs.

**Comment by prosoitos** [comment]
`tab_move 1` and `tab_move -1` allow me to switch the selection to the tab to the right or the tab to the left. But the order of the tabs stays the same. So 2 tabs that are far apart remain far apart. I was hoping to move tabs around to have 2 tabs between which I want to switch back and forth next to each other.

Sorry if I was not clear. I tried to make the distinction between moving the selection and moving the tab, but I guess I didn't do a good job at it.

**Comment by toonn** [comment]
Nope, in the [default config they're mapped to `tab_shift`](https://github.com/ranger/ranger/blob/master/ranger/config/rc.conf#L541) which does exactly what you're asking for.

**Comment by prosoitos** [comment]
Oh! Wonderful! By `<a-r>` and `<a-l>` I thought you meant `<A-right>` and `<A-left>` (I thought it was a shorter way of writing it). And `<A-right>` and `<A-left>` are bound to `tab_move`.

My rc.conf does not have those `tab_shift` lines. It is a new addition? (I may have deleted them by accident though).

Anyhow, this is great! Thank you for your answer @toonn and I guess I will close this issue then.

**Comment by prosoitos** [comment]
(Unless you'd rather keep it open because you want to work on the doc for this?)

**Comment by prosoitos** [comment]
I tested `tab_shift 1` and `tab_shift -1` and it works perfectly (and is indeed exactly what I wanted) in miller viewmode. But in multipane view mode, it doesn't work (the tabs do shift, but the actual panes don't.

**Comment by prosoitos** [comment]
According to #1125 (which by the way confirms that this is a fairly recent addition, which explains why I didn't have them in my rc.conf), it should work. But at least for me, it doesn't: I end up with the tabs and the panes being mis-matched.

**Comment by prosoitos** [comment]
Mmm. It is weird. With several tabs open, in multipane viewmode, I can make the non-selected tabs move, but the selected tab does not. So the mis-match is actually not between the tab and the pane (those remain correct), but in the order of the tabs as compared to the order of the panes.

**Comment by prosoitos** [comment]
If this is not just something weird in my settings and if you can reproduce the problem, I will open a separate issue on this.

The workaround is to move to miller viewmode, order the tabs however I want, then go back to multipane viewmode.

**Comment by toonn** [comment]
Please do, sounds like a bug.

**Comment by prosoitos** [comment]
ok, will do. And I was wrong about the workaround: it actually doesn't work. So `shift_tab` allows to move the tabs around, but does not move the panes. Maybe it was never meant to move the panes around, but having a mismatch in the order of the tabs and panes and very awkward.

**Comment by toonn** [comment]
It was never meant to move panes around because of oversight on the part of the pull requester and us. Multipane is not used much by anyone active in #ranger afaict.

**Comment by prosoitos** [comment]
My default viewmode is miller too. But there are situations when multipane is really convenient and I am really glad that it exists for those times.

**Comment by laggardkernel** [comment]
> Oh! Wonderful! By `<a-r>` and `<a-l>` I thought you meant `<A-right>` and `<A-left>` (I thought it was a shorter way of writing it). And `<A-right>` and `<A-left>` are bound to `tab_move`.

Does `<A-right>`, `<A-left>` work for you to to `tab_move`. I just tried these two keybindings and nothing happened. I guess maybe the `alt-arrow` keys in ranger don't work on macOS.

**Comment by toonn** [comment]
@laggardkernel, indeed, I can confirm that on Mac OS the option key does not affect the keycode sent for the arrow keys. I checked with `xev`. That means you won't be able to use those mappings.

**Comment by laggardkernel** [comment]
@toonn  Thanks for your explanation.
