### ISSUE TITLE
Freeze when executing shell command while Kitty preview visible

### ISSUE THREAD

**Issue by wilecoyote2015** [ranger/ranger#1603]
#### Runtime Environment

- Operating system and version: Arch Linux
- ranger version: ranger-master 1.9.2
- Python version: 3.7.3 (default, Mar 26 2019, 21:43:19) [GCC 8.2.1 20181127]
- Locale: en_GB.UTF-8

#### Current Behavior
In Kitty terminal with preview method kitty, when an image File is selected so that a preview is shown, pressing `CTRL-s` and entering a command (for example `mkdir test`), the command is executed, but ranger freezes and needs to be restarted.

#### Expected Behavior
Ranger should continue to work after command execution.

#### Steps to reproduce
1.  Set preview method to kitty
2. Navigate to an image file so that the preview is shown
3. Press `CTRL-s` and enter `mkdir test`

#### Traceback
I cannot start ranger in debug mode (bug report will follow soon if not already present)

**Comment by toonn** [comment]
That's a terminal feature though, it's called flow control. `C-s` freezes output to the terminal and `C-q` resumes it.

**Comment by wilecoyote2015** [comment]
Ah, I see; thank you!
Thus, pressing `C-q` after executing a shell command should cancel the alleged freeze? Unfortunately, this I cannot reproduce this.

**Comment by toonn** [comment]
Hmm, then it sounds like a bug. However, I can't reproduce it. What did you map `<C-s>` to? It's not bound in the default config.

**Comment by toonn** [comment]
Ah, actually. I think you don't have `<C-s>` bound at all. I got it to freeze up by typing `mkdir test<CR>`. Which is basically equivalent to `r test<CR>` I think.

**Comment by i007c** [comment]
same issue

**Comment by i007c** [comment]
any shell command while previewing an image will freeze the ranger
even going to the man page will freeze it

**Comment by i007c** [comment]
@toonn yep its been fix. tnx <3
