### ISSUE TITLE
[FeatureRequest] run git command in ranger

### ISSUE THREAD

**Issue by taigacute** [ranger/ranger#1605]
## Feature
First sorry for broken the issue template.
Most time i will do some git command. but  i cant do it in ranger .i need to create a second screen by tmux to run git command .

**Comment by toonn** [comment]
Not sure why you closed the issue, maybe you figured it out?

You can do this two ways, either use the `:shell git commit` command (`s`, `!`, `@`, `#` all open the console with a variation of the `:shell` command), which you can bind to some keys if you want. Or, you can pop into a shell with `S`.
