### ISSUE TITLE
Ranger attempts to preview binary files

### ISSUE THREAD

**Issue by hut** [ranger/ranger#161]
With scope.sh disabled, ranger attempts to preview .odt and .apk files even though they are binary.  The effect is that the preview pane is opened (if it was collapsed before), but it stays blank, no preview is displayed.

In this snippet, the first file does not provoke a preview whereas the second does.
https://gist.github.com/SammysHP/764fcd3d1c474bd49645

**Comment by swalladge** [comment]
I think one of the problems is that `firstbytes` will return None if there is a `UnicodeDecodeError` - which seems to happen on every binary file when ranger is running on python3. If it returns None, then `is_binary()` returns False.

I don't see this bug when running ranger under python2, so it must be related to the changes in how strings are handled in python3.

**Comment by nfnty** [comment]
@swalladge Could you test the branch `is_binary`?

**Comment by swalladge** [comment]
That looks like it could work, but it doesn't fix the underlying issue with python2/3 compatibility. Hang on a tick, I've come up with a fix that I'll submit a pull request for.
