### ISSUE TITLE
'tmux-statusbar' refuse tu honour ranger :)

### ISSUE THREAD

**Issue by rtng1** [ranger/ranger#1615]
#### Runtime Environment

- Operating system and version: 
- Terminal emulator and version: 
- Python version: 
- Ranger version/commit: 
- Locale: 

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```

```

**Comment by rtng1** [comment]
tmux-statusbar shows 'python 3.7' for the window i'm running ranger in even though `update_tmux_title` is set to 'true'
running: `funced ranger` then type `if test -n "$TMUX"; tmux rename-window ranger; end; ranger` changed the window-title from 'python 3.7' to 'ranger' and that stayed even after quitting ranger, but running ranger in a different window still shows window-title python 3.7.

**Comment by toonn** [comment]
That function would only be available in the session where you defined it. You need to run `funcsave ranger` to have it work in other tmux windows and across sessions.

**Comment by rtng1** [comment]
@toon: just funcsaved ranger, but now my command 'ranger' does not prompt anything.
tried /usr/bin/ranger instead, what starts ranger again but window-title is 'python 3.7' again.

**Comment by toonn** [comment]
Did you actually do the `funced` again before the `funcsave`?

**Comment by 3ruce** [comment]
I'm having the same problem in bash... Any ideas?

**Comment by toonn** [comment]
Ah, I think this is because of a tmux default setting, you need to configure `allow-rename` to `on`. #1740 will warn about this when it gets merged.

**Comment by 3ruce** [comment]
Hmmm... ok, so I've added these lines to tmux.conf

```
set-option -g allow-rename on
set-window-option -g automatic-rename on
```

And have also added this line to .bashrc

```
## https://stackoverflow.com/a/33400476
DISABLE_AUTO_TITLE=true
```

I'm still getting `python 3.7` when running ranger inside tmux but all other apps are renaming fine? I'm on Debian 10 if that helps?

**Comment by toonn** [comment]
@3ruce, hmm if running `printf '\033kranges\033\\'` on the command line works, I have no idea why ranger can't set the window name.

**Comment by 3ruce** [comment]
hmmm... that command works... I get `ranges` which I suspect is a typo... very odd...

**Comment by toonn** [comment]
Yep, was a typo. That's the command ranger runs to set the title so I don't know why it's not working : /

**Comment by 3ruce** [comment]
It's working now... I'm not sure what I did but maybe adding these 2 helped?

Plug 'francoiscabrol/ranger.vim'
Plug 'rbgrouleff/bclose.vim'

**Comment by toonn** [comment]
Those have little to do with ranger. They're only run in vim. I suspect you forgot to reload the tmux config before or something similar.

**Comment by 3ruce** [comment]
Yeah, it was weird... it might have been because I have mutiple tmux sessions going on multiple workspaces in Xfce... I think it was fixed after a reboot

**Comment by toonn** [comment]
That might've prevented tmux from reloading the config.

**Comment by 3ruce** [comment]
Yeah, I've had luck with the manual reload in the past but not this time...
