### ISSUE TITLE
I have Debian 10 buster installed / ranger does not open

### ISSUE THREAD

**Issue by regxr** [ranger/ranger#1626]
#### Runtime Environment

- Operating system and version: Debian 10 buster / x86_64 Linux 4.19.0-5-amd64
- Terminal emulator and version: guake 3.4.0-1
- Python version: Python 3.7.3
- Ranger version/commit: ranger 1.9.2
- Locale: pt_BR.UTF-8

#### Current Behavior
I try to run ranger, by:

> $ ranger

It does not open.

#### Expected Behavior
It is supposed to open.

#### Context

When I try to run ranger in my new Debian 10 buster, released this month, it shows me the error:

> ranger version: ranger 1.9.2
> Python version: 3.7.3 (default, Apr  3 2019, 05:39:12) [GCC 8.3.0]
> Locale: pt_BR.UTF-8
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 118, in main
>     load_settings(fm, args.clean)
>   File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 401, in load_settings
>     load_custom_commands(system_comm_path, custom_comm_path)
>   File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 388, in load_custom_commands
>     custom_comm_path)
>   File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 371, in import_file
>     spec.loader.exec_module(module)
>   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/home/rbr/.config/ranger/commands.py", line 364, in <module>
>     class setlocal(set_):
>   File "/home/rbr/.config/ranger/commands.py", line 369, in setlocal
>     PATH_RE = re.compile(r'^\s*path="?(.*?)"?\s*$')
> NameError: name 're' is not defined
> 
> ranger crashed. Please report this traceback at:
> https://github.com/ranger/ranger/issues

When I type "ranger --clean" it runs normally.

Anyone knows how to solve this out and make us free from typing the option "--clean" (without scripting -- obviously) forever?

**Comment by toonn** [comment]
The problem is your custom `commands.py` isn't correct. It needs an `import re` at the least. If you've never customized it it's probably a remnant from a very old version and no longer compatible, so just remove it.

**Comment by regxr** [comment]
In fact, @toonn, I was enjoying an old $HOME partition where the config files were kept. Just deleted that $HOME/.config/ranger/ directory to force ranger to generate new config files and it solved the issue. Thanks a lot!

**Comment by toonn** [comment]
I know this is kinda annoying btw. But there's not really a good solution to outdated configs. In newer versions of ranger you don't have to copy any configs to your `$HOME` so the problem should at least only occur if you customized some of the files.
