### ISSUE TITLE
Ranger in the Windows console

### ISSUE THREAD

**Issue by WscriChy** [ranger/ranger#163]
Hi, 

I am using ConEmu on Windows as a terminal for shells. For shell I usually use bash, zsh from Msys 2.
I like Ranger very much, thank you for the great work. But it seems like ConEmu or, as project members say, the native Windows console are not a right environment for Ranger.

Is it possible to make it work on Windows.

I have found a solution which employs Mintty form Msys 2 instead of ConEmu. But still I would like to use ConEmu for several reasons.

The issue in ConEmu reported [here](https://code.google.com/p/conemu-maximus5/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Stars%20Type%20Status%20Modified%20Reporter%20Summary&groupby=&sort=&id=1743). But the guys say that it is totally Ranger's issue.

**Comment by nfnty** [comment]
Just run under `cygwin`. There are a lot of unixisms in ranger that may never be fixed in a platform independent way.

**Comment by kellpossible** [comment]
@mtelesha any luck with cmder?

**Comment by cebaa** [comment]
@nfnty Installed ranger-fm with pip and under cygwin I'm getting this:

```
Traceback (most recent call last):
  File "c:/python371/Scripts/ranger", line 37, in <module>
    sys.exit(ranger.main())  # pylint: disable=no-member
  File "C:\python371\lib\site-packages\ranger\core\main.py", line 34, in main
    from ranger.core.fm import FM
  File "C:\python371\lib\site-packages\ranger\core\fm.py", line 12, in <module>
    import pwd
ModuleNotFoundError: No module named 'pwd'
```

It seems `pwd` is Unix-only.

**Comment by toonn** [comment]
@cebaa, long shot maybe but you try installing `pypiwin32`. If that doesn't help we could conceivably patch out pwd but I suspect it'll be a bit of a whack-a-mole.

**Comment by cebaa** [comment]
@toonn Thanks - actually, that was an error on my end. I ran it with an external, non-cygwin python. It works when running with cygwin-provided python, so yay! So if anyone else runs into this, worth confirming that you're using cygwin python instead of an external (Windows) installation first.

**Comment by Tritaya** [comment]
@cebaa how to run with cygwin provided python?

**Comment by cebaa** [comment]
@Tritaya Make sure you're using `/usr/bin/python` instead of something else. Running `which python` will give you the default one.

**Comment by Tritaya** [comment]
Are you on windows? I've python installed natively on windows, how do I
choose which one to use?

пн, 9 нояб. 2020 г., 20:31 cebaa <notifications@github.com>:

**Comment by cebaa** [comment]
@Tritaya It looks like you need to use Cygwin python instead of "Windows" python. If you open a Cygwin terminal and type `which python`, it should say `/usr/bin/python`. If it says something else - namely, the location of your "Windows" python - you'll probably run into the same issues I did. Just make sure you user `usr/bin/python` - e.g. you can set it to be the first in your path:

```
PATH=/usr/bin:$PATH
```
