### ISSUE TITLE
Previewing 'text/*' MIME types does not work out of the box in PyPI release 1.9.2

### ISSUE THREAD

**Issue by ernstki** [ranger/ranger#1631]
#### Runtime Environment
- Operating system and version:  Ubuntu 18.04 (elementaryOS) and CentOS 7
- Terminal emulator and version: _n/a_
- Python version: 2.7.x
- Ranger version/commit: 1.9.2
- Locale: de_DE.UTF-8#### Current Behavior

#### Current Behavior

Ranger will syntax-highlight the previews for files having a `text/*` MIME type out of the box.

#### Expected Behavior

This does not occur at PyPI release v1.9.2 _unless_ the user already had `highlight` installed on their system.

#### Context

When installing ranger from PyPI, where the latest release is 1.9.2, `highlight` is set as the previewer for files having a `text/*` MIME type in [`scope.sh`](../blame/5ae67755cfa84177613b48a698b4ed58e9751fc4/ranger/data/scope.sh#L231).

This means that unless you'd already had [`highlight`](https://gitlab.com/saalen/highlight) installed, you don't get syntax highlighted previews for `text/*` files out of the box. This program _is_ available in most distros' repositories, but I wouldn't say it's a super well-known package, and "highlight" is somewhat frustratingly ungoogleable.

Somewhere between `master` and 5ae67755cfa84177613b48a698b4ed58e9751fc4, the default `text/*` highlighter in `scope.sh` changed from `highlight` (back?) to `pygmentize`, so this is probably not an issue for people using the latest Git master—assuming they already have the `pygments` package installed. Fortunately `pygments` is quite common, and packages like IPython will bring it in as a dependency.

Accordingly, I'm closing this issue, but wanted to have a workaround in the issue tracker, for people using the current PyPI release (and for posterity).

#### Workarounds

Possible workarounds are:

1. to install `highlight` using your OS's package manager, or
2. use the latest Git master of ranger, and replace your `scope.sh` with the version shipping with that release, like this:

    ```bash
    mv ~/.config/ranger/scope.sh ~/config/ranger/scope.sh.orig
    ranger --copy-config scope
    ```

**Comment by toonn** [comment]
This is not and never was a bug. *All* ranger dependencies are optional. Also, pygments does *not* override `highlight` if that is installed, it's a fallback.

**Comment by ernstki** [comment]
Hi. Thanks for your work on ranger! `:)`

I experienced some unintuitive behavior that caused frustration, which did not seem to be clearly addressed in the README, or the wiki. When I searched for it in the issue tracker, and it wasn't documented there, I filed an issue to describe the situation to the best of my ability.

And immediately closed it, because, as you say, it's not a bug.

Not for me, not for you (the maintainers), but for someone else who will have this problem. If that's contrary to your notion of how the issue tracker should work, I apologize, and will not do that again.

**Comment by toonn** [comment]
It's fine. Though an issue saying something like "Documentation's unclear about `highlight`s." might've been more helpful. Things like this should be clear from both the README and the manpage.

How did you interpret this bit of the "PREVIEWS" section of the manpage for example:
>  This default script is %rangerdir/data/scope.sh. It contains more
     documentation and calls to the programs lynx and elinks for html,
     highlight for text/code, img2txt for images, atool for archives,
     pdftotext or mutool for PDFs and mediainfo for video and audio files.
     </br>
     Install these programs (just the ones you need) and scope.sh will
     automatically use them.

**Comment by ernstki** [comment]
It's all good. It was a newbie mistake.

I'll edit the issue to make it clear that this is spelled out in the manual page. That way it'll be there for the next person who didn't read the manpage carefully enough. `:)`
