### ISSUE TITLE
sudo ranger followed by ctrl+s is dangerous?

### ISSUE THREAD

**Issue by sealmove** [ranger/ranger#1632]
I am not sure if this is an issue, but if it is, then it's a big one...
Executing `sudo ranger` and then exiting back to shell with `ctrl+s` permanently grants you root privilege!

**Comment by toonn** [comment]
I suspect you're talking about `S`? That doesn't exit ranger. It just opens a subshell. And it's both expected and intended behavior for that subshell to retain the privilege of the ranger program.
