### ISSUE TITLE
Adding docx support?

### ISSUE THREAD

**Issue by keiichiiownsu12** [ranger/ranger#1633]
Hello. I read a recent pull request asking for you to add in docx preview support. 

Not sure if you have done this yet, but there is a script called docx2txt (similar to the odt2text you use in the scope.sh file; link: [http://docx2txt.sourceforge.net](url) ) that can convert docx files to plain script. 

After installing docx2txt and adding the following lines to your scope.sh file:
`#Docx stuff
        docx)
           /usr/bin/docx2txt < "${FILE_PATH}" && exit 5
           exit 1;;`

I was able to preview a .docx file as plaintext in ranger just like a normal odt. Confirmed to not work with .doc files though. 

I was curious if you had a different method implemented potentially?

**Comment by toonn** [comment]
Yep, #1576 uses pandoc to render `docx`. It'd be cool if you could try it out and give us a value judgement of the quality of the conversion. Try both markdown and plaintext outputs for pandoc.

**Comment by geolaw** [comment]
You can use catdoc with the same syntax as docx2txt

       #Doc stuff
        doc)
            /usr/bin/catdoc < "${FILE_PATH}" && exit 5 exit 1;;

**Comment by toonn** [comment]
@geolaw, do either of these provide better output than pandoc?

**Comment by HappyCthulhu** [comment]
@toonn, i had few files: .doc and .docx. Also i had default rifle.conf. Ranger couldnt preview these files. But after i installed pandoc, ranged started working fine with preview .doc and .docx. So, i dont think, that catdoc is better. At least, in my case
