### ISSUE TITLE
Update taskbar title together with window title when set update_title true

### ISSUE THREAD

**Issue by siikamiika** [ranger/ranger#1637]
#### Runtime Environment

- Operating system and version: `Linux es 5.2.1-arch1-1-ARCH #1 SMP PREEMPT Sun Jul 14 14:52:52 UTC 2019 x86_64 GNU/Linux`
- Terminal emulator and version: `rxvt-unicode (urxvt) v9.22 - released: 2016-01-23`
- Python version: `3.7.3 (default, Jun 24 2019, 04:54:02) [GCC 9.1.0]`
- Ranger version/commit: `ranger 1.9.2`
- Locale: `en_US.UTF-8`

#### Current Behavior
Ranger updates the title (`WM_NAME`) but not the taskbar title (`WM_ICON_NAME`) when `set update_title true` is set in `rc.conf`.

#### Expected Behavior
Both the title and taskbar title should be changed.

#### Context

I want to be able to see from the taskbar what I have open in ranger.

#### Possible Solutions
Change [this line](https://github.com/ranger/ranger/blob/669100aad83e3a51f140b6085d836a8260eda8d0/ranger/gui/ui.py#L385) to `'\x1b]0;',` (source: http://tldp.org/HOWTO/Xterm-Title-3.html). Running
```
curses.setupterm()
curses.tigetstr('tsl')
```
returns `b'\x1b]2;'`, which only changes the window title but not the icon name.

It would be preferred of course if there was a way in `curses` to set the taskbar title without hard-coding this string.

#### Steps to reproduce
1. Open ranger with `set update_title true`
2. Navigate to the previous directory
3. Window title changes but the taskbar title doesn't

#### Traceback

```

```

**Comment by toonn** [comment]
Hmm, as I see it, this is intentional. We could add a new option though: `update_icon_title`.
