### ISSUE TITLE
Widestring preview cut off on Python 2

### ISSUE THREAD

**Issue by amerlyq** [ranger/ranger#164]
Preview for cyrilic texts (in UTF-8) has half width of ansi, filling only left half of preview window and cropping text in middle of it. Seems the reason in using byte-width instead of character-width inside associated code.

**Comment by amerlyq** [comment]
Seems like for new releases this problem is non-existent. At least for Python3 on ArchLinux.

**Comment by Vifon** [comment]
I can confirm that it still happens on Python 2.

![2015-11-17-144010_840x350_scrot](https://cloud.githubusercontent.com/assets/624347/11212908/2abf27aa-8d39-11e5-8ae1-11d3b3557cdb.png)

**Comment by amerlyq** [comment]
Reopened. I don't see much necessary, though.
Single place w/o Python3 is my router with old linux kernel, and there are no non-english texts at all:)
Hovewer for someone forced to work on legacy platforms... it could be helpful, I think?

**Comment by Vifon** [comment]
Many (almost all?) distributions ship with ranger running on Python 2. Besides, ranger does officially support Python 2.7+, so it's a valid bug.

**Comment by amerlyq** [comment]
Aah, really, I forgot. Linux corrupts and ArchLinux corrupts absolutely:)

**Comment by nfnty** [comment]
Can't reproduce this issue. Request to reopen if you're still experiencing this issue on `master` or the latest release.

**Comment by Vifon** [comment]
I can still reproduce it on Python 2.

**Comment by nfnty** [comment]
Can you provide steps to reproduce?

**Comment by nfnty** [comment]
And what versions are you using? Terminal emulators etc.?

**Comment by Vifon** [comment]
Create a testfile like this:

    perl -E 'say "ą"x40; say "a"x40' > testfile

Then run ranger on Py2:

    python2 `which ranger`

I'm using a fresh master version of ranger. Should be reproducible on any 80 chars wide terminal. I'm on urxvt but it shouldn't matter.

**Comment by Vifon** [comment]
I can no longer reproduce it, seem to be fixed. Thank you.
