### ISSUE TITLE
How to make ranger dont automatically run into the folder after using the f key to search

### ISSUE THREAD

**Issue by P1G3s** [ranger/ranger#1643]
Greeting sir, since i'm not quite familiar with a lot of things in linux, i'm not sure **how to make ranger dont automatically run into the folder when i use the f key to search**, it is quite annoying and sometimes i make some extra typing which might invoke some operation i dont want at all. I appreciate your help.

**Comment by toonn** [comment]
`find` is aliased in `rc.conf` to `scout -aets`, `-a` automatically opens the file on an unambiguous match. So you could change the alias. Though I think what you actually want to use is `/` aka `:search`.

**Comment by P1G3s** [comment]
> `find` is aliased in `rc.conf` to `scout -aets`, `-a` automatically opens the file on an unambiguous match. So you could change the alias. Though I think what you actually want to use is `/` aka `:search`.

Thank you sir! Exactly what i need, the **find** command can keep changing and highlighting the target as i'm typing, while the **search** doesn't. And again, very appreciate your help!!

**Comment by toonn** [comment]
Note that coming up with your personal version of find and search and other commands is `scout`'s raison d'être. You can compose your very own search command using a scout alias or simply map a scout invocation.
