### ISSUE TITLE
Command to rename a file which puts the current filename in the command line

### ISSUE THREAD

**Issue by rightaway** [ranger/ranger#1650]
When you use the `:rename` command, if you want to append something to the end of a filename or edit the filename, you first need to copy the current filename into the command line. Could there be a command where when you go to rename it the current filename is added to the command line so it's easy to edit? This would work for renaming a single file.

**Comment by Vifon** [comment]
There is already such a keybinding (not a command though), it's under <kbd>A</kbd> by default. There is also <kbd>I</kbd> for prepending to the filename. Both of them mirror the analogous vi commands.

**Comment by toonn** [comment]
Also check out the `:rename_append` command bound to `a`.
