### ISSUE TITLE
Moving a file to a renamed directory causes file deletion

### ISSUE THREAD

**Issue by sfischme** [ranger/ranger#1660]
#### Runtime Environment
ranger version: ranger 1.9.2
Python version: 3.7.4 (default, Jul 16 2019, 07:12:58) [GCC 9.1.0]
Locale: en_US.UTF-8

#### Current Behavior

Ranger deletes a file that you move and fails to create the file in the new directory.

0) mkdir /tmp/foo
1) touch /tmp/bla 
2) touch /tmp/foo/bla2
3) ranger /tmp/foo
4) in ranger: :tab_new /tmp
5) in ranger in tab (/tmp) select file /tmp/bla
6) in ranger in tab (/tmp): dd (cut selection)
7) in ranger switch to tab /tmp/foo
8) in a terminal: mv /tmp/foo /tmp/foo2
9) in ranger: pp

Result: the file /tmp/bla is deleted, and it's not in directory /tmp/foo2. 

#### Expected Behavior

Either an error that the directory is no longer exsting, but actually better would be to move /tmp/bla to /tmp/foo2

#### Context

I renamed a directory while ranger still had an open tab.

**Comment by toonn** [comment]
I succesfully reproduced this. Paste should fail if the destination directory no longer exists.
