### ISSUE TITLE
opened pdf gets auto focussed

### ISSUE THREAD

**Issue by ky0n** [ranger/ranger#1664]
#### Runtime Environment

- Operating system and version: Manjaro(xfce version)
- Terminal emulator and version: Guake 3.6.3,  VTE 0.56.3
- Python version: 3.7.4
- Ranger version/commit: ranger-master
- Locale: en_US.UTF-8

#### Current Behavior
auto-focus on opened pdf.
have to click on the terminal to be able to use ranger again with keyboard
#### Expected Behavior
an option to disable auto-focussing on opened Files, so that i can open multiple pdfs without clicking

**Comment by Vifon** [comment]
Not much can be done on our side, you'd need to configure your window manager to not focus new windows.

**Comment by toonn** [comment]
A semi-solution would be to `mark` the pdfs in ranger before opening one. Or to gather them in the copy buffer and then use the `%c` macro in a command to open all of them (less ergonomic but necessary if you want to be to cross directory boundaries).
