### ISSUE TITLE
ranger ignores modifications in commands_full.py

### ISSUE THREAD

**Issue by nsklaus** [ranger/ranger#1665]
#### Runtime Environment

- Operating system and version: ubuntu 19.04
- Terminal emulator and version:  st
- Python version: python 3.7.3
- Ranger version/commit: 1.9.2
- Locale:  en_US.UTF-8

#### Current Behavior
ranger ignores my modified function in commands_full.py

#### Expected Behavior
ranger should use my modified commands_full.py

#### Context
when deleting multiple files and directory, i want confirmation, but i noticed ranger tried to list all my selected files and dirs, like:
```confirm deletion of: file1.xyz, file2.xyz,file3.xyz,file4.xyz,file5.xyz,file6.xyz,file7.xyz (y / N)```
depending the length of filenames and the number of files this can be a very long string.
i wanted ranger to just say instead:
`confirm deletion of  [7]  elements (y / N)`
so i went and modified the delete function accordingly.
a very simple and little modification, i just did this:
```
# i changed this line:
"Confirm deletion of: %s (y/N)" % ', '.join(files)

# into this:
"Confirm deletion of: %d elements (y/N)" % (len(files))
```
 but nothing happened. ranger kept using the original long string method.

#### Possible Solutions
manualy editing `/usr/lib/python3/dist-packages/ranger/config/commands.py` worked for me,
but this isn't the correct solution.

#### Steps to reproduce
1. modify delete command in ~/.config/ranger/commands_full.py
2. see your modifications being ignored.
3.

**Comment by toonn** [comment]
From the manual:

```
--copy-config=commands will copy only a small sample
configuration file with a thoroughly commented example.
It is recommended to keep this file tidy to avoid getting
defunct commands on ranger upgrades.  The full default
commands.py can be copied with
--copy-config=commands_full, but that file will be
ignored by ranger and serves only as a reference for
making your own commands.
```

You *could* simply rename the file but note the reasoning in this paragraph. We don't recommend including definitions for commands for which you actually want the default behavior.
