### ISSUE TITLE
Previews and Metadata

### ISSUE THREAD

**Issue by cpchan** [ranger/ranger#1667]
It would be nice to separate previews and metadata as two different views and have a key toggle between them. They are both useful.

**Comment by toonn** [comment]
Hmm, you could be referring to two things, ranger's concept of metadata, previews that look like metadata, like `file` output. I assume you're talking about the latter?

We've had people combine image previews and textual output before. I'm sure there's something to be found in past issues.

**Comment by cpchan** [comment]
Toon Nolten <notifications@github.com> writes:

> Hmm, you could be referring to two things, ranger's concept of
> metadata, previews that look like metadata, like file output. I assume
> you're talking about the latter?

Yes, the output from file.

Charles

**Comment by toonn** [comment]
Easiest way currently would be to use `zi` to toggle the fancy previews.

**Comment by cpchan** [comment]
Thanks, that worked. Still exploring Ranger as I have only started using it a few days ago.

**Comment by toonn** [comment]
Since you're happy with this I'll close the issue?
