### ISSUE TITLE
permission denied while preview

### ISSUE THREAD

**Issue by dumbPy** [ranger/ranger#1669]
#### Runtime Environment
ranger version: ranger 1.9.2
Python version: 3.6.8

#### Current Behavior

No previews. As all previews are processed by `scope.sh` I assume.

#### Expected Behavior

In the current setup, I don't have the permissions to run any binary/executable files from my home. any `/home/**/filename.sh` can be ran though as `bash /home/**/name.sh`. Is there a way to make ranger run `~/.config/scope.sh` by appending bash before the `~/.config/scope.sh`

#### Context

Not able to preview files. I am on kitty terminal and using the kitty method for preview images. the same scope.sh works on my personal machine. On work machine, I don't have the permissions to run executable from any `/home/*` path. Kitty's installed in `/var/opt/kitty` but my configs are of course in `~/.config`.

#### Possible Solutions
A hacky way to add `bash` before calling the `scope.sh` from `kitty/core/loader.py`

#### Traceback

```
17:09:25 ERRO Notification: Loader work process failed: Getting preview of /home/sufiyan/Downloads/coo_old_300dpi_mask/coo_old_300dpi_mask/1_0.json (Percent: 0)
17:09:25 ERRO [Errno 13] Permission denied: '/home/sufiyan/.config/ranger/scope.sh'
Traceback (most recent call last):
  File "/home/sufiyan/.local/lib/python3.7/site-packages/ranger/core/loader.py", line 411, in work  
    next(item.load_generator)
  File "/home/sufiyan/.local/lib/python3.7/site-packages/ranger/core/loader.py", line 171, in generate
    self.process = process = Popen(self.args, **popenargs)
  File "/var/opt/anaconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/var/opt/anaconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/home/sufiyan/.config/ranger/scope.sh'
```

**Comment by toonn** [comment]
Hmm, curious. Unless you changed `rc.conf` to point to `~/.config/ranger/scope.sh` then it should be using the `scope.sh` that's included with ranger which presumably wouldn't be in the home directory.

The request is reasonable but it would prevent people from implementing their own preview script in whatever language they wanted (as long as they can specify a #! for that language). That's quite a bit of flexibility to give up for what's arguably a silly setup. If people want to run a file, is having to specify the interpreter something that makes them think about what they're doing?

Maybe we can fall back to running `bash preview_script` if the executable mode isn't set though.

**Comment by dumbPy** [comment]
Got around it by asking my admin to edit the `rc.conf` in global settings and not saving any settings in `~/.config`. Works as expected.
A simple bash with sed command does the job
```
for rc_conf in $(locate rc.conf | grep ranger)
do
    sed -i 's/set preview_images false/set preview_images true/g' $rc_conf
    sed -i 's/set preview_images_method w3m/set preview_images_method kitty/g' $rc_conf
done
```

**Comment by dumbPy** [comment]
OK wait, don't even need the admin's help. My mistake, didn't cared enough earlier about how the configs work for ranger. If you have the `~/.config/ranger/scope.sh` then it's used, or else default `1scope.sh` is used, while the `rc.conf` is loaded both from default and `~/.config/ranger/rc.conf`. So I can basically override any settings from default by re-setting them as required in my `~/.config/ranger/rc.conf`.

i.e., 
adding 
```
set preview_images true
set preview_images_method kitty
```
 to `~/.config/ranger/rc.conf` works for me, and the problem with running scope.sh is averted by not having the scope.sh in my config folder.

**Comment by toonn** [comment]
Ah, yeah, that's what I said in the first comment. Not being able to customize `scope.sh` is a bummer though. We're still looking into how we'd solve this.
