### ISSUE TITLE
`ranger` crashes on invalid file timestamps

### ISSUE THREAD

**Issue by mapellidario** [ranger/ranger#1671]
#### Runtime Environment
- Python version: Python 2.7.13 (default, Sep 26 2018, 18:42:22)
- Ranger version/commit: ranger-stable 1.7.1
- Locale: LANG=en_GB.UTF-8

#### Current Behavior

Directory tree structure
```
.
├── dir1
└── dir2
```
`dir2` has broken metadata (in this case it was mtime):
```
  File: dir2
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Access: (0755/drwxr-xr-x)  Uid: ( 1000/   user)   Gid: ( 1000/   user)
Access: 2019-08-23 17:13:28.759352125 +0200
Modify: 1754-08-30 23:33:37.128654848 +0049
Change: 2019-08-23 17:13:28.755352074 +0200
 Birth: -
```
Browse the content of `./` with the command `ranger`. When the cursor is moved from `dir1` to `dir2`, a `ValueError` exception is raised and ranger crashes returning the following traceback:
```
ranger version: 1.7.1, executed with python 2.7.13
Locale: en_GB.UTF-8
Current file: /home/user/path/dir2
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ranger/core/main.py", line 140, in main
    fm.loop()
  File "/usr/lib/python2.7/dist-packages/ranger/core/fm.py", line 338, in loop
    ui.redraw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 265, in redraw
    self.draw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/ui.py", line 291, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/displayable.py", line 246, in draw
    displayable.draw()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/statusbar.py", line 99, in draw
    self._calc_bar()
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/statusbar.py", line 104, in _calc_bar
    self._get_left_part(bar)
  File "/usr/lib/python2.7/dist-packages/ranger/gui/widgets/statusbar.py", line 182, in _get_left_part
    localtime(stat.st_mtime)), 'mtime')
ValueError: year out of range

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
```

#### Expected Behavior
Catch the exception and display `invalid metadata` in the bottom status line.

#### Context
Simply browsing a directory content.

#### Possible Solutions
Catch the exception.

#### Steps to reproduce
1. Break a file/directory metadata (I do not really know how)
2. Browse its content by moving the cursor on it

**Comment by toonn** [comment]
1.7.1 is very old. Please try 1.9.2 or master if that doesn't work. I remember an issue about this but I'm not sure we've fixed it.

**Comment by mapellidario** [comment]
I managed to replicate the error in a non-production environment. It was enough to set a very old mtime with touch, as described at https://www.unixtutorial.org/commands/touch. No need to actually corrupt the filesystem and break the metadata.

`ranger` version 1.9.2 works fine. kudos! :)

I am sorry for not having had the possibility to check it earlier.
