### ISSUE TITLE
copymap command -NOT AN ISSUE- More like Help~

### ISSUE THREAD

**Issue by annata83** [ranger/ranger#1678]
Hello there everyone!
I am going deeper in understanding Ranger so expect me often here.
I found this copymap command:

> 
> **copycmap key newkey [newkey2 ...]**
> See copymap
> 
> **copymap key newkey [newkey2 ...]**
> Copies the keybinding key to newkey in the “browser” context.  This is a deep copy, so if you change the new binding (or parts of it) later, the old one is not modified.
> 
> To copy key bindings of the console, taskview, or pager use “copycmap”, “copytmap” or “copypmap”.
> 
> **copypmap key newkey [newkey2 ...]**
> See copymap
> 
> **copytmap key newkey [newkey2 ...]**
> See copymap
> 
I notice the `See copymap ` pointer but i dont find anything on it yet.. what does this command exacly mean?

Sorry for create an issue for this question maybe will be a good idea to have a place for ranger users questions and guides!

**Comment by Vifon** [comment]
It makes `newkey` do what `key` does in a given keymap. For example if <kbd>j</kbd> moves cursor down, `copymap j x` will make <kbd>x</kbd> also do so. The `copyXmap` variants are for various keymaps.

> Sorry for create an issue for this question maybe will be a good idea to have a place for ranger users questions and guides!

We have a subreddit, feel free to make it more alive. :)

https://reddit.com/r/ranger/

**Comment by annata83** [comment]
Excellent explanation! If this explanation is in the manual I totally miss it!.
Very useful command.
I will see you in [Reddit](https://reddit.com/r/ranger/)
Thanks @Vifon

**Comment by toonn** [comment]
@annata83, there's an explanation in the manpage. Would appreciate you taking a look and judging whether or not it's clear. We appreciate any improvements that could be made to the docs!

**Comment by annata83** [comment]
Hi @toonn; to be honest i found copymap in:
 
```
*copymap key newkey [newkey2...]

*copymap key newkey [newkey2 ...]
Copies the keybinding key to newkey in the “browser” context.  This is a deep copy, so if you change the 
new binding (or parts of it) later, the old one is not modified.

To copy key bindings of the console, taskview, or pager use “copycmap”, “copytmap” or “copypmap”.

copypmap key newkey [newkey2 ...]
See copymap
```
Maybe where it says  
> See copymap

Would be better to add an example like the one @Vifon explain to me

> It makes newkey do what key does in a given keymap. For example if j moves cursor down, copymap j x will 
> make x also do so. The copyXmap variants are for various keymaps. 

...because that one was really easy understand and very seld explanatory.

**Comment by Vifon** [comment]
> I also notice that:
copymap key newkey [newkey2...]
...appears three times and are exactly the same except for the second one that has the bottom info!

Note that these are `copycmap`, `copypmap` and `copytmap` which operate on different keymaps.

**Comment by annata83** [comment]
Hi @toonn,  Allow me to explain because I didn't explaing myself very well before, what I am saying is that there is four copymap command:

```
copycmap, copymap, copypmap, & copytmap .
```

what I notice is that in the descirption section of commands you will see:  copycmap, copymap,copypmap & copytmap as well only that their description is the same for all except for number 2

-----------------------------------------------------------------------------------------------------------
1)copycmap key newkey [newkey2 ...]
See copymap
------------------------------------------------------------------------------------------------------------
2)copymap key newkey [newkey2 ...]
Copies the keybinding key to newkey in the “browser” context.  This is a deep copy, so if you change the new binding (or parts of it) later, the old one is not modified.
To copy key bindings of the console, taskview, or pager use “copycmap”, “copytmap” or “copypmap”.
--------------------------------------------------------------------------------------------------------------
3)copypmap key newkey [newkey2 ...]
See copymap
----------------------------------------------------------------------------------------------------------------
4)copytmap key newkey [newkey2 ...]
See copymap
-----------------------------------------------------------------------------------------------------------------

Maybe will be better to have an example of each and  every different one  instead of See copymap

**Comment by toonn** [comment]
Hmm, thing is they do the exact same thing, just for other modes. I'll add a tiny extra note to them. But we don't want to maintain 4 copies of almost the exact same explanation.

**Comment by toonn** [comment]
Decided on just scrapping them : )
