### ISSUE TITLE
Request: colour files committed with git differently

### ISSUE THREAD

**Issue by dylan-chong** [ranger/ranger#1681]
This is a very useful feature when you have a folder with many files, some of which are temporary. Such as with latex documents where there are many files of the same name and different extensions most of these files are temporary files and would be ignored with a git ignore file. Would be very useful to show the file committed with git in a different colour so that it is easy to know which file I should edit

**Comment by toonn** [comment]
```
set vcs_aware true
set vcs_backend_git enabled
```

**Comment by dylan-chong** [comment]
Thank you!
