### ISSUE TITLE
Celebrate 1.9.2

### ISSUE THREAD

**Issue by techtonik** [ranger/ranger#1686]
It a few days it will be exactly one year since the release of 1.9.2 - https://github.com/ranger/ranger/releases - it will be interesting to know what happened since then, what is expected, etc.

#### Expected Behavior

1.9.3 =)

**Comment by toonn** [comment]
Working on it, you can track progress at the milestone: https://github.com/ranger/ranger/milestone/1

**Comment by techtonik** [comment]
Maybe release and move that to `1.9.4`?

**Comment by toonn** [comment]
It's not hard to run/install the master branch. Feel free to review items in that milestone to speed the process along.

**Comment by techtonik** [comment]
I am not sure I have enought time to any active development, except for occasional fixes in packed stable versions and reports through downstream distributions (which like to mess with `ranger`).

https://github.com/ranger/ranger/compare/v1.9.2...master

**Comment by toonn** [comment]
Yes, time is what all of us lack. I know it's been almost a year but I don't want to rush the release just for the sake of rushing it.
