### ISSUE TITLE
[Proposal] Load default rifle.conf also when there is a custom rifle.conf

### ISSUE THREAD

**Issue by rayx** [ranger/ranger#1688]
If user defines a custom rifle.conf, ranger skips default rifle.conf and loads that custom file only. See the code [here](https://github.com/ranger/ranger/blob/master/ranger/core/fm.py#L97-L100). 

This behavior makes it difficult to maintain a custom rifle.conf because it's impossible for user to add only the settings he would like to change to custom rifle.conf. The issue was discussed in issue https://github.com/ranger/ranger/issues/516. @hut mentioned it was because the order of the rules in rifle.conf mattered (ranger evaluates the rules in a "first-match" way). 

I wonder how about implementing the following approach? It allows user to add only the settings he would like to change to custom rifle.conf and is compatible with existing custom rifle.conf. It's not perfect but it seems good enough to me and useful. 

- If there is a custom rifle.conf, load the file first. The rules in this file will be added to the internal `rules` list of `Rifle` object. 
- Then loads the default rifle.conf. The rules in this file will be appended to the internal `rules` list of `Rfile` object. 

With this change, since all user defined rules precede Ranger default rules, for file types that user defines in custom rifle.conf, their behavior will be same as before. For file types that user doesn't define, ranger will open them by failing over to the rules in default rifle.conf.

### An example scenario where the new approach helps

Suppose I specify a custom text editor in my custom rifle:

     mime ^text,  label editor = myeditor "$@"

That's it. I don't need to add rules for pdf, etc because ranger would fail over to rules in default rifle.conf.

### An example scenario where the new approach doesn't help

With the above custom rfile, html file can't be opened correctly because its MIME type is text/html. The rule in my custom file is matched first and hence ranger calls myeditor, instead of browser, to open it. To solve the issue, one has to add a rule for html file as below:

     ext x?html?, has firefox,          X, flag f = firefox -- "$@"
     mime ^text,  label editor = myeditor "$@"

I don't this is a big issue with the new approach because user has to do the same with the current version of Ranger anyway. Also, the new behavior is not difficult to be explained to user.

**Comment by toonn** [comment]
That's bad UX though. We've discussed this quite a bit in #ranger. Adding a rule at the top of `rifle.conf` is something I *never* do, neither have I ever added anything to the very bottom.
The only thing you lose by copying the full `rifle.conf` is additions/changes to the default rules. Usually that's not a big deal if you're already customizing your `rifle.conf` anyway.

I don't want to close discussion on this but pre-/appending is not good enough imo.

**Comment by rayx** [comment]
> The only thing you lose by copying the full `rifle.conf` is additions/changes to the default rules. Usually that's not a big deal if you're already customizing your `rifle.conf` anyway.

The issue with this approach is that one needs to merge the changes when upgrading to a newer version of ranger. Of course, rifle.conf doesn't contain critical configuration so it's fine to use older version in this specific case. But it would be good to maintain changes only, instead of a big monolithic file.

I'm closing it because I can't think out a better way and don't have strong opinion on this. Thanks.
