### ISSUE TITLE
Can't launch Ranger in macOS 

### ISSUE THREAD

**Issue by lifeBalance** [ranger/ranger#1694]
I installed ranger using **pip3** following the **user scheme**:
`pip3 install --user ranger-fm`

My user site packages location is:
```
python3 -m site --user-base
/Users/javi/Library/Python/3.7
```

I have exported the following environment variable:
`export="${HOME}/Library/Python/3.7/bin:${PATH}"`

So that I can call Python executables from anywhere. I have installed other Python programs(pywal) this way and have no problem running them.

#### Runtime Environment
- macOS Movaje
- iTerm2
- Python 3.7
- Ranger 1.9.2
- Locale: 

 ```
 export LC_ALL=en_US.UTF-8  
 export LANG=en_US.UTF-8
```

#### Current Behavior
I can not launch Ranger:
```
ranger
Traceback (most recent call last):
  File "/Users/fito/Library/Python/3.7/bin/ranger", line 35, in <module>
    import ranger  # NOQA pylint: disable=import-self,wrong-import-position
ModuleNotFoundError: No module named 'ranger'
```
#### Expected Behavior
Type `ranger`, press Enter and Ranger starts.

**Comment by toonn** [comment]
Not sure what to say. It's not like ranger does anything weird here. It simply tries to import a module. Check whether your pythonpath actually includes that site-packages and that ranger's actually in there.

Kinda confused that the usernames in the site-packages location and `bin/ranger` don't match.

**Comment by lifeBalance** [comment]
Yeah, sorry about the usernames, I was taking notes and copy-pasted the wrong outputs. This is the correct output:
```
$ python3 -m site --user-base
/Users/fito/Library/Python/3.7
```
I'm pretty sure I don't need to set `PYTHONPATH` since the *user-site* packages directory is automatically searched. I mean, pywal works right out of the bat.

Most probably it's a problem on my side. The thing is that I installed Python3 using the official installer which added the following line to my Bash configuration:
```
PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:${PATH}"`
```
But since it also creates automatically a symbolic link in `/usr/local/bin/python3`, I deleted the PATH line above from my shell configuration. 
Then I installed Ranger, tried to launch it without success, and add back again:
```
PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:${PATH}"`
```
To my shell config, but still can't launch it.

**Comment by toonn** [comment]
Could you check the shebang of `which ranger`? Maybe it's getting run with the system python.

**Comment by lifeBalance** [comment]
```
$ which ranger
/Users/fito/Library/Python/3.7/bin/ranger
```
But nevermind, I reinstalled it and now it launches fine, still not sure why it didn't the first time. 

I knew that `/Library/Frameworks/Python.framework/Versions/3.7/bin` contains both:
* The Python interpreter.
* Other Python executables (such as pip, and other important Python utilities **aaand** packages we install to the **Global site-packages**...)

But, given that:
* The installer creates **symbolic links** to Python, pip and such utilities in `/usr/local/bin`
* And I install everything to the **User site-packages**

I felt pretty comfortable taking out of my **PATH** `/Library/Frameworks/Python.framework/Versions/3.7/bin` and adding instead the directory for the executables of the **User site-packages** (`${HOME}/Library/Python/3.7/bin`)

So I did, and Ranger didn't launch at the beginning, which confused me a bit. But now after reinstalling it, it launches fine.

Anyways, thanks for the assistance toonn.

**Comment by toonn** [comment]
Np, glad you got it sorted. Maybe it creates the symlinks to whatever it finds on the `PATH`?
