### ISSUE TITLE
Image previews broken on Kitty after Pillow update

### ISSUE THREAD

**Issue by avalonv** [ranger/ranger#1695]
#### Runtime Environment

- Operating system and version: Void Linux 5.1
- Terminal emulator and version: Kitty 0.14.4 
- ranger version: ranger 1.9.2
- Python version: 3.6.9 (default, Jul  5 2019, 09:47:14) [GCC 9.1.0]
- Locale: en_US.UTF-8

Image previews are broken after updating Pillow to 6.1.0.
```/usr/lib/python3.6/site-packages/PIL/Image.py:116: RuntimeWarning: The _imaging extension was built for another version of Pillow or PIL: Core version: 6.0.0 Pillow version: 6.1.0  warnings.warn(str(v), RuntimeWarning)```

![2019-09-14-205056_maim](https://user-images.githubusercontent.com/29720696/64915072-fdedc480-d734-11e9-8899-373e2ba915c7.png)

**Comment by toonn** [comment]
Do other programs using pillow still work? This sounds like something implemented internally to pillow.

**Comment by avalonv** [comment]
I apologise for not testing when I opened the issue, it was really late for me.

```
c>>> from PIL import Image
/usr/lib/python3.6/site-packages/PIL/Image.py:116: RuntimeWarning: The _imaging extension was built for another version of Pillow or PIL:
Core version: 6.0.0
Pillow version: 6.1.0
  warnings.warn(str(v), RuntimeWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/PIL/Image.py", line 101, in <module>
    "Pillow version: %s" % (getattr(core, "PILLOW_VERSION", None), __version__)
ImportError: The _imaging extension was built for another version of Pillow or PIL:
Core version: 6.0.0
Pillow version: 6.1.0
```

After uninstalling Pillow from both pip and my package manager and reinstalling it again I could import `Image` and ranger displayed images normally.
