### ISSUE TITLE
Image preview in wrong urxvt window

### ISSUE THREAD

**Issue by KiraDotRose** [ranger/ranger#1696]
#### Runtime Environment
- Operating system and version: manjaro-i3 stable 
- Terminal emulator and version: rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
- Python version: 3.7.4 (default, Jul 16 2019, 07:12:58) [GCC 9.1.0]
- Ranger version/commit: ranger-master 1.9.2
- Locale: en_US.UTF-8

#### Current Behavior
If two urwvt windows are open and ranger is launched in the one opened first, the image preview will be displayed in the last opened window.
![2019-09-17-194857_1920x1080_scrot](https://user-images.githubusercontent.com/55358004/65066204-3a632f80-d984-11e9-9daa-9af00edc11e8.png)

If the second opened terminal is runing ranger too the ranger in the first terminal will display its preview under the preview of the second.
![2019-09-17-194509_1920x1080_scrot](https://user-images.githubusercontent.com/55358004/65066060-f5d79400-d983-11e9-9b1a-4a7946aea260.png)

If the second terminal is opened after ranger is launched the preview will behave as expectet.
![2019-09-17-194829_1920x1080_scrot](https://user-images.githubusercontent.com/55358004/65066591-ed338d80-d984-11e9-8aa1-5c03a5461fbf.png)

#### Expected Behavior
The preview schould be displayd in the terminal running urxvt.

**Comment by toonn** [comment]
The urxvt method is a hack so I'm not sure this can be resolved.
@Vifon input?

**Comment by Vifon** [comment]
Very interesting. Do you use any software like tmux or some window compositor?

**Comment by KiraDotRose** [comment]
I have compton.

**Comment by Vifon** [comment]
Can you disable it for a minute and test without it?

**Comment by KiraDotRose** [comment]
Disabeling compton doesn't fix it.

**Comment by KiraDotRose** [comment]
I was able to fix it by seting image-preview-method to w3m, it was set to uberzug. Tho now guake has the problem that images seem to be drawn ontop of each other instead of removing previously viewed images, so if i preview a smaller image after an larger one the larger one is visible underneath the smaller one. Also displaing the file with "i" doesn't work neither in guake nor urxvt now.

**Comment by toonn** [comment]
Oh, I assumed you were using the urxvt method. @seebye, could you chime in?

**Comment by seebye** [comment]
He's using urxvt's demon mode.  
ueberzug only supports terminal emulators which use a process per window.

**Comment by Vifon** [comment]
Ah, it makes sense now. I'm closing it then as it's not on our side. Thanks for explaining, @seebye!
