### ISSUE TITLE
Rename cunmap, punmap, tunmap

### ISSUE THREAD

**Issue by toonn** [ranger/ranger#1698]
These names break the pattern of expectation set by `copycmap` and friends, which simply prefix `cmap` and variations. So you might reasonably expect `uncmap` rather than `cunmap`.

My suggestion, either we rename these or the `copymap` variants, taking them out of the docs but not actually out of the code to avoid breaking backwards compatibility.

Imo, I'd be more likely to think/type `un<tab>` to find the right mode to unmap for than `p<tab>` to find the right action I want to perform for the pager mode.

**Comment by Vifon** [comment]
Agreed. Good call about the backwards compatibility, we definitely should keep the old names as aliases for a time being.

**Comment by toonn** [comment]
I suggest we add these to this version and add a deprecation warning to the old ones. So, we rename, alias the old ones to "notify('deprecated'); unc/p/tmap".
