### ISSUE TITLE
No commit on status bar

### ISSUE THREAD

**Issue by davoudarsalani** [ranger/ranger#1704]
ranger version: ranger 1.9.2
Python version: 3.7.4 (default, Jul 16 2019, 07:12:58) [GCC 9.1.0]
Locale: en_US.UTF-8

The commit sometimes does not show up on the status bar. It seems to happen when the commit is too long.

![1398-07-09-22-39-52-ss](https://user-images.githubusercontent.com/50229325/65992662-8215ab00-e49c-11e9-9a23-4e97598cc3ae.png)

**Comment by Vifon** [comment]
It makes sense considering how the status bar works but it'd also make sense to truncate the commit message if it's really long. I'll take a look into it.
