### ISSUE TITLE
Startup delay

### ISSUE THREAD

**Issue by varrel1337** [ranger/ranger#1717]
#### Runtime Environment

- Operating system and version: archlinux (kernel 5.2)
- Terminal emulator and version: termite v15
- Python version: 3.7.4
- Ranger version/commit: https://github.com/ranger/ranger/tree/7338801c355e72354ec73beee798c21c46757b03
- Locale: en_US

#### Current Behavior

When ranger starts for the first time after the system booted, there is a noticeable startup delay of maybe 1 second. After closing ranger and starting it again, the delay is gone until the next reboot.

#### Expected Behavior

There should not be any delay at first start.

#### Context
--copy-config=all has been used. All config files are in the home dir.

RANGER_LOAD_DEFAULT_RC=FALSE is also set.

#### Possible Solutions

If this turns out to be a caching issue, it might help to provide a way to precache the necessary files by a startup script.

#### Steps to reproduce
1. reboot
2. start ranger
3. close ranger
4. start ranger
5. compare the time needed to start ranger

**Comment by toonn** [comment]
Sounds like pages in memory. Don't think we can do anything about this. Maybe try Pypy, might start up quicker.

**Comment by varrel1337** [comment]
using pypy is even slower ...


> Sounds like pages in memory. Don't think we can do anything about this. Maybe try Pypy, might start up quicker.

Shouldn't that mean that a) this issue reappears after a while as soon as the requested files are no longer in memory and b) that this could be solved by starting a process (at startup) that requests these files and keeps running in the background? Like having ranger run without a terminal as a background task. Is there any way to have ranger run as a background task? Running ranger with 'ranger &' will just kill the process immediately.

**Comment by toonn** [comment]
Ranger can't run without STDIN. It *can* hang and consume resources though, so that's not a good solution. I suspect you have enough memory that you're just not causing it to swap out. Ranger's normally run with python's `-O` so there's not really a way to make it any faster. Also, 1s isn't exactly long, we don't have the manhours to spend optimizing ranger's startup unfortunately.

I just have a single long-running ranger session usually. Maybe running ranger in screen/tmux'd suit you better? Setting up a systemd service that starts that session at boot?

**Comment by Vifon** [comment]
Does it also happen with other Python processes, @varrel1337?

**Comment by varrel1337** [comment]
> Does it also happen with other Python processes, @varrel1337?

Nope. However I will have an eye on it if it happens with larger python applications?
In the end it probably does not matter that much, just looking to optimize my setup

**Comment by varrel1337** [comment]
There is only a minor delay on modern hardware.

If anyone finds a way to speed up the startup process anyway, please reopen the issue.
