### ISSUE TITLE
Allow for filtering by unique files

### ISSUE THREAD

**Issue by mvrozanti** [ranger/ranger#1730]
Hello there

I'm not sure if this is a wanted feature but I have a recurrent use-case in that I have several duplicate, identical files that I need to open/preview. To get unique files outside of ranger, I currently just check all the `md5sum`s for each file in the directory and get the first distinct ones found. 

I'd like to have this feature in ranger so I can easily do this with few keystrokes directly on my favorite file browser. This should be doable with a simple plugin, but I'm not really sure where to start.

**Comment by toonn** [comment]
I'm not quite sure what you're looking for. You could implement a linemode that prefixes the filename with a hash then sorting should make it easy to identify files with identical hashes.

**Comment by mvrozanti** [comment]
I'd like to be able to make a custom filter depending on a condition to show a file or not. Is that possible?

**Comment by toonn** [comment]
Depends on the predicate. You can filter by name, filetype, type dir/file/link. Not by size for example, or hash, in your case. We'd probably accept a contribution adding that as a `filter_stack` feature though.

**Comment by mvrozanti** [comment]
oh cool this was implemented thanks!
