### ISSUE TITLE
Command not found: `map' every time I open ranger

### ISSUE THREAD

**Issue by ChausseBenjamin** [ranger/ranger#1735]
#### Runtime Environment

- Operating system and version: Manjaro Linux
- Terminal emulator and version: st (Luke Smith build)
- Python version: 3.7.4 (default, Oct  4 2019, 06:57:26) [GCC 9.2.0]
- Ranger version/commit: ranger-master 1.9.2
- Locale: en_US.UTF-8

#### Current Behavior
Whenever I laiunch ranger: 
```
 π ~/.config/ranger ❯ ranger 
Command not found: `map' 
Command not found: `map' 
```
Also there is a one second delay upon launch...

#### Expected Behavior
Ranger running without any error messages

**Comment by toonn** [comment]
Sounds like an issue with one of your config files. Does it happen when you run `ranger --clean`?

**Comment by ChausseBenjamin** [comment]
Sadly yes...

**Comment by ChausseBenjamin** [comment]
Found the issue! It had to do with poorly written code on my side... (A shortcut mapping generator I made was creating duplicate mappings)

**Comment by kohane27** [comment]
If someone is wondering, hopefully the following is helpful.

```bash
➜ ranger
Command not found: `"'
Command not found: `"'
```

Turned out that I had the following in my `rc.conf`:

```bash
" map V       toggle_visual_mode
" map uV      toggle_visual_mode reverse=True
```

The correct way to comment out is with `#`, not with `"`.
