### ISSUE TITLE
After update to macOs Catalina iterm2 image preview shows broken image icon on random images

### ISSUE THREAD

**Issue by l4zygreed** [ranger/ranger#1738]
#### Runtime Environment

- Operating system and version: MacOs Catalina 10.15
- Terminal emulator and version: Iterm2 3.3.6
- Python version: 2.7.6
- Ranger version/commit: 1.9.2
- Locale: None.None

#### Current Behavior
Corrupted image icon displays in preview on random images (on any image filetypes and sizes, but mostly on images that are lower than 1MB)
<img width="912" alt="Screenshot 2019-10-24 at 00 00 12" src="https://user-images.githubusercontent.com/9384565/67433733-51cfb100-f5f1-11e9-913f-4462b136efc5.png">

#### Expected Behavior
Preview the actual image

**Comment by toonn** [comment]
#539 seems similar.

**Comment by genkobar** [comment]
Did you install via pip3?

Image previews work for me after I installed via homebrew. I just commented on https://github.com/ranger/ranger/issues/539#issuecomment-546747460 after finding it via this issue.

**Comment by laggardkernel** [comment]
@toonn iTerm2 image preview doesn't work with Python 3. There have been 2 pull requests for this problem. It seems the maintainers overlooked them. GH-1604, GH-1601.

**Comment by toonn** [comment]
I haven't overlooked anything. We're just short on time.

**Comment by lazygreed** [comment]
@genkobar nope, installed via homebrew
It's just messed up after update to macOs Catalina
(and maybe I did iterm2 update)

**Comment by lazygreed** [comment]
seems like it somehow fixed after todays `brew upgrade`

should I close the issue?

**Comment by toonn** [comment]
Let's keep it open because others seem to have had the same issue.

**Comment by toonn** [comment]
On second thought let's close this issue. The python3 fix is landing in master soon.
