### ISSUE TITLE
Tmux window gets not renamed even if option is set

### ISSUE THREAD

**Issue by aRkedos** [ranger/ranger#1739]
#### Runtime Environment

- Operating system and version: Linux Manjaro 5.2.21
- Terminal emulator and version: urxrvt
- Python version: Python 3.7.4
- Ranger version/commit: Ranger-Master **1.9.20**
- Locale: de.DE_UTF.8

#### Current Behavior
If using Tmux, the window in which Ranger is started does not get renamed even if the option is set.

#### Expected Behavior
Tmux window should be renamed if option is set. And should again rename itself when Ranger closes.

#### Possible Solutions

I've found the issue in ui.py. In ui.py the command `tmux show-window-option -v automatic-rename` gets invoked via the `check_output` method which was imported from `ranger.ext.spawn`. This returns the output of `stdout` of that command. Nothing more (see `gui/ui.py` **lines 116 - 128*). This output is stored in the variable `self._tmux_automatic_rename.`

In order to rename the window, ranger must issue the command `tmux rename-window ranger`. 

Later on in order to restore the automatic-rename behaviour of tmux Ranger issues the command `tmux set-window-option automatic-rename` with `self._tmux_automatic_rename as parameter` (gui/ui.py lines 178 - 189). This does not get really issued because `if self._tmux_automatic_rename` is not a boolean since the `stdout` of `tmux show-window-option -v automatic-rename` is `on` or `off`

Solution
If `tmux show-window-option -v automatic-rename` returns `off` set it to `on` instead to make sure tmux gets renamed after closing
Add a check_output which issues `tmux rename-window ranger` to actually rename the thing.
remove the else-block in `gui/ui.py` (starting at line 185) since it is no longer needed with the aforementioned changes.
Maybe even the `sys.stdout.write` call can be removed (see line 127) could be removed (but not entirely sure which purpose it serves)

#### Steps to reproduce
1. Simply start Ranger in a Tmux session

**Comment by aRkedos** [comment]
added it to the still open PR #1732

**Comment by lonelykid** [comment]
I think this should be better documented. Tmux has ``allow-rename`` and ``automatic-rename``. The former is what ranger needs, and ranger would set the latter to off.

**Comment by toonn** [comment]
Ranger emits a warning if you enable the setting but allow-rename is set to off.
What would you expect to be documented better?

**Comment by lonelykid** [comment]
This warning does not show up for me.  I just checked the code. It only checked window-options(``tmux show-options -w``), but does not check global window options(``tmux show-options -gw``). When you set it globally in your `.tmux.conf`, the former will be null and fall back to the global one. I could PR to fix this.

Some other idea:
1. If ranger takes the effort to modify my setting on ``automatic-rename``. Why doesn't let it modify setting on ``allow-rename`` as well? 
2. Current implementation has side effect of changing my setting. I could change it back in quit function. But it would be nice if we could use a hook to add tasks to quitting.

**Comment by toonn** [comment]
We [restore the setting here](https://github.com/ranger/ranger/blob/master/ranger/gui/ui.py#L522) though. And we don't mess with `allow-rename` because we don't have to, `automatic-rename` prevents us from setting the window name properly even if we're "allowed," we choose to adhere to the spirit of the configuration rather than the letter : )

I think you're right about the global/local options, that'd be a good PR.

**Comment by lonelykid** [comment]
Thanks for pointing to the code. It seems not working as expected also because global/local options are not considered. 

`automatic-rename` is not preventing anything. There is no need to modify it manually. Instead `allow-rename` off is indeed preventing manual renaming. If you allow, I'd rather change it to modify/restore allow-rename setting. 
>This flag(`automatic-rename`) is automatically disabled for an individual window when a name is specified at creation with new-window or new-session, or later with rename-window, or with a terminal escape sequence.

**Comment by toonn** [comment]
Nope, we won't touch `allow-rename`, that's not ranger's responsibility. We disable `automatic-rename` because otherwise programs started from ranger will cause the window name to be changed and it won't change back when they stop. Feel free to improve on the latter.

**Comment by lonelykid** [comment]
OK. I get the point. I will modify it to work with global/local options properly.
