### ISSUE TITLE
Mkv file color is blue instead of purple since update

### ISSUE THREAD

**Issue by Alkeryn** [ranger/ranger#1744]
![image](https://user-images.githubusercontent.com/11599075/67930646-7f53c600-fbc0-11e9-8e8d-a24ab5f0d001.png)
they look like this but used to look like this
![image](https://user-images.githubusercontent.com/11599075/67930619-6d722300-fbc0-11e9-9b64-0c7a4a32a0b4.png)
Mp4 kept their original colors

**Comment by toonn** [comment]
Hmm, can't reproduce on master. Are you using a colorscheme? Did you change your terminal's colors? Can you run `file some.mkv/mp4`?

**Comment by Alkeryn** [comment]
i did not change my colors, all my mkv now appear blue, all mp4 still purple
i'm running on nixos and i have an overlay which basically makes me use the lattest commit from master

**Comment by toonn** [comment]
Without further info, like the `file --mimetype` output, we can't help.

**Comment by Alkeryn** [comment]
@toonn 
![image](https://user-images.githubusercontent.com/11599075/67975195-f23a5c80-fc13-11e9-8dac-e8e426923827.png)
they are standard matroska file
it has nothing to do with it most likely
ALL the mkv file i have behave like that since the update and i got thousands of mkv ^

**Comment by toonn** [comment]
That's the same mime type they have for me. Run a python interpreter and then:
```
import mimetypes
mimetypes.guess_type('an mp4 and an mkv')
```

**Comment by Alkeryn** [comment]
![image](https://user-images.githubusercontent.com/11599075/67976325-2adb3580-fc16-11e9-9d19-ce6ecb3014c1.png)
it seems like it is an issue with python's mimetypes guess function ^

**Comment by toonn** [comment]
Yep, that'll be the problem. Python 3.7.4 reports the right type for me though.

**Comment by Alkeryn** [comment]
Uh turns out i'm running python 3.7.5 so maybe that's a regression

**Comment by toonn** [comment]
I've reported the problem on the [python issue tracker](https://bugs.python.org/issue38656).

**Comment by The-Compiler** [comment]
Hmm, I see something similar after upgrading to Python 3.8 (on Archlinux):

![image](https://user-images.githubusercontent.com/625793/68975697-3cb30000-07f4-11ea-956b-aad0bd4af8fc.png)

However, I do get a correct output from the `mimetypes` module:

```
>>> print(mimetypes.guess_type('E01.mkv'))
('video/x-matroska', None)
>>> print(mimetypes.guess_type('E01.mp4'))
('video/mp4', None)
```

The output with Python 3.7 is exactly the same, but there, both filetypes were purple in ranger.

**Comment by toonn** [comment]
Curiouser and curiouser. Could you run these from within ranger, to make sure you're running ranger with *that* python? `eval import mimetypes; self.fm.notify(mimetypes.guess_type('E01.mkv'))`

**Comment by cheap-glitch** [comment]
Similar issue here, with ranger 1.9.2 and python 3.8 on Arch: `mkv` files are not highlighted anymore (but no problem with `mp4` and `mov` files).

**Comment by The-Compiler** [comment]
@toonn That shows me `('video/mkv', None)` which is different from what I got inside Python. However, `eval import sys; self.fm.notify(sys.executable)` gives me `/usr/bin/python`, which definitely gives me a different output:

```
$ /usr/bin/python -c "import mimetypes; print(mimetypes.guess_type('E01.mkv'))"
('video/x-matroska', None)
```

**Comment by toonn** [comment]
@The-Compiler, o.O What's `sys.version` when you run it using `:eval`?

**Comment by The-Compiler** [comment]
3.8.0, as you'd expect.

However, I digged into ranger's source a bit, and it looks like it does this:

```python
mimetypes.knownfiles.append(os.path.expanduser('~/.mime.types'))
mimetypes.knownfiles.append(self.relpath('data/mime.types'))
self.mimetypes = mimetypes.MimeTypes()
```

Trying the same in the Python shell, I get:

```
>>> import os.path
>>> import mimetypes
>>> mimetypes.knownfiles.append(os.path.expanduser('~/.mime.types'))
>>> mimetypes.knownfiles.append(os.path.expanduser('~/tmp/ranger/ranger/data/mime.types'))
>>> mt = mimetypes.MimeTypes()
>>> mt.guess_type('E01.mkv')
(None, None)
>>> mimetypes.guess_type('E01.mkv')
('video/x-matroska', None)
```

Which seems odd, because the Python documentation claims:

> This class represents a MIME-types database. By default, it provides access to the same database as the rest of this module. The initial database is a copy of that provided by the module

Still not sure where the `video/mkv` with the global `mimetypes` module in ranger is coming from, though.

**Comment by toonn** [comment]
Oh, right `video/mkv` comes from `ranger/data/mime.types`. What confuses me is the `None` result you're getting in the interpreter. That seems like the likely culprit for the coloring.

**Comment by toonn** [comment]
Could you run `:eval self.fm.mimetypes.guess_type('something.mkv')`? That should report `video/mkv`.

**Comment by The-Compiler** [comment]
It indeed reports `(None, None)` which is consistent with what I've mentioned in the [Python bug](https://bugs.python.org/issue38656) - it does look like the result via the `mimetypes.MimeTypes` class is different to using the `mimetypes` module directly.

FWIW when I tell it to load the ranger `mime.types` file via its constructor, it seems to work:

```python
>>> import mimetypes
>>> import os.path
>>> mt = mimetypes.MimeTypes()
>>> mt.guess_type('E01.mkv')
(None, None)
>>> mt2 = mimetypes.MimeTypes([os.path.expanduser('~/tmp/ranger/ranger/data/mime.types')])
>>> mt2.guess_type('E01.mkv')
('video/mkv', None)
```

but there's definitely something weird going on with its default database.

**Comment by toonn** [comment]
Seems like dhess is saying on the issue that we probably shouldn't instantiate a `MimeTypes` object?

**Comment by The-Compiler** [comment]
I personally do believe this is a Python bug (as it's backwards-incompatible and contrary to the documentation, see my comment on the Python tracker for an explanation).

However, the pragmatic solution would indeed be for ranger to use the `mimetypes` module directly. In fact, it already does so in various places (`ext/rifle.py` and `core/filter_stack.py`); only `container/fsobject.py` uses a class (mostly for historical reasons I think, looking at 871c502d58055c7611f0763eaa71a7fafad7efdc where a `MimeTypeAware` class was introduced and a457053815d72ef5d7ccfedbfda02101665bdec6 where it was removed).

Thus, using the module directly would happen to work better (avoiding that bug) and also make ranger's code more clean/consistent. Is it okay to remove `FM.mimetypes` or is that exposed to plugins or something of that sorts? Should I open a pullrequest for doing so?

**Comment by toonn** [comment]
Hmm, it actually came in quite handy in testing what mimetypes ranger sees, otherwise we'd have to make sure users load the extra file manually, so maybe just bind it to the module name?

**Comment by The-Compiler** [comment]
I don't follow - ranger can still load the extra files, just at module-level/globally, right?

**Comment by toonn** [comment]
Yeah, that's not what I mean. What I mean is, how do we get users to test the mime type returned for a file without having to laboriously explain where to find the extra data files and how to append them. `:eval self.fm.mimetypes.guess_type('whatever')` is a lot easier than "Find the data file, import mimetypes in an interpreter and `.knownfiles.append....`"

**Comment by The-Compiler** [comment]
Modules are singletons in Python. If ranger does the necessary setup, the user can simply do `:eval :eval import mimetypes; self.fm.notify(mimetypes.guess_type('E01.mkv'))` and get the same result as before - see our [earlier conversation](https://github.com/ranger/ranger/issues/1744#issuecomment-554634703) where I did exactly that (as per your suggestion) and got `video/mkv` (due to ranger's initialization) rather than `video/x-matroska` (like in Python outside of ranger).

**Comment by toonn** [comment]
Ah, but we do the initialization in three places? We need it in rifle but do we need it for `filter_stack` I wonder?

**Comment by Vifon** [comment]
> Ah, but we do the initialization in three places? We need it in rifle but do we need it for filter_stack I wonder?

We need it for the mimetype-based filters. I agree it should be unified of course.

**Comment by Alkeryn** [comment]
After downgrading to python 35 i don't have the issue anymore, 36 could also be working too
so i think that's a bug that happened due to python's new version but might also be fixed on ranger side, no idea ^

**Comment by toonn** [comment]
@Vifon, I meant, do we need it twice within ranger. Can't we have `filter_stack` use the mimetypes `fsobject` initializes, shouldn't it already be? If the scopes don't work out, extracting the mimetypes setup into `ranger/ext` or something would be fine too of course.

**Comment by Vifon** [comment]
> @Vifon, I meant, do we need it twice within ranger. Can't we have `filter_stack` use the mimetypes `fsobject` initializes, shouldn't it already be? If the scopes don't work out, extracting the mimetypes setup into `ranger/ext` or something would be fine too of course.

Yes, that's how it should have been done.

**Comment by atticus-sullivan** [comment]
Hi,
I've experienced the same and searched for a fix to colourize mkv files as well. While doing so I've found this issue and wondered if this is already fixed and my bug is due to an error made by me or if this is simply not fixed.

**Comment by toonn** [comment]
@atticus-sullivan, what version of python are you running ranger with?

**Comment by atticus-sullivan** [comment]
I get `python -V
Python 3.8.1`

Oh and I noticed a slight difference, I have the mkv files not even marked blue, mine a displayed white (but this might be a thing with the colorschme, I use the default one)

**Comment by erik55** [comment]
Me too. Running python 3.8.7 and ranger 1.9.3

**Comment by rbehzadan** [comment]
In ```core/fm.py``` (in ```FM.__init__```), I changed 
```python
self.mimetypes = mimetypes.MimeTypes()
```
to
```python
self.mimetypes = mimetypes
```
and it seems to solve the problem for me.

**Comment by Alkeryn** [comment]
tried @rbehzadan 's fix, and i can comfirm that it does work !

**Comment by toonn** [comment]
@SimSaladin's PR is the proper fix, fyi.

**Comment by rbehzadan** [comment]
Thank you @toonn.
I should have been more thorough.

**Comment by toonn** [comment]
Np, just pointing out that a PR with a fix is already linked to this issue.
