### ISSUE TITLE
Exiting shell suspends ranger

### ISSUE THREAD

**Issue by jrwrigh** [ranger/ranger#1747]
#### Runtime Environment
- Operating system and version: Manjaro 18.1.2
- Terminal emulator and version: xfce4-terminal 0.8.8
- Python version: 3.7.4
- Ranger version/commit: 1.9.2
- Locale: en_US.UTF-8

#### Current Behavior
Exiting a shell launched inside ranger causes ranger to suspend and become a background process.

#### Expected Behavior
When exiting a shell launched inside ranger, exit should return to ranger

#### Steps to reproduce
1. Launch ranger, navigate to a directory
2. Press `S` to launch shell in that directory
3. Exit the shell using either `exit` or Ctrl + D
4. Ranger is suspended in the background:

```
~ 
➜ ranger                 

~/Downloads via 🅒 base 
➜ exit
[1]  + 3191 suspended (tty output)  ranger

~ took 10s 
✦ ➜ 
```
*Note the `✦` means there is a background process running. 

#### Workaround
Running `fg %1` opens the ranger session again.

**Note** Possibly related to #1367, but I'm not sure, so here's another issue.

**Comment by toonn** [comment]
What shell are you running? We've never seen this.

**Comment by jrwrigh** [comment]
This was using zsh on my desktop.

I'm currently away from my desktop, so I've tried a few things on my laptop (same basic stats as above): 

ZSH Laptop: Doing the reproduction steps above in zsh, I get this:
![image](https://user-images.githubusercontent.com/20801821/68150342-beee1b00-fefc-11e9-805d-795d2359a748.png)
There appears to be a traceback, but it's a bit wonky. ranger is no longer a background task, as it looks like it crashed.

Bash Laptop: Starting ranger through bash results in a slightly different background status than the desktop through zsh:
```
~     
➜ bash    
[USER@COMPUTER ~]$ cd Downloads/    
[USER@COMPUTER Downloads]$ ranger    
     
~     
➜ exit    
     
[1]+  Stopped                 ranger    
[USER@COMPUTER Downloads]$ jobs    
[1]+  Stopped                 ranger    
[USER@COMPUTER Downloads]$ 
```
Also note that the shell launched through ranger was zsh.

**Comment by Ablesius** [comment]
can't reproduce that :-/ but no ZSH here. Have you updated everything on your system?

**Comment by jrwrigh** [comment]
Everything on my system is up to date. Both ranger installs are through Manjaro's repositories. If I get a chance, I'll clone the repo directly and see if that changes anything.

**Comment by Ablesius** [comment]
@jrwrigh any specific settings? Could you try with a clean config and similar stuff?

**Comment by toonn** [comment]
@jrwrigh Another thing to try. Run bash and start ranger as `env SHELL=(which bash) ranger`.

**Comment by jrwrigh** [comment]
This is the contents of `rc.conf`:

```
map so shell odrivesync %s                                                                                          
map sh set show_hidden!    
set colorscheme default    
set vcs_aware true    
    
# Sort Downloads dir by time added     
setlocal path=~/Downloads sort atime    
setlocal path=~/Downloads sort_reverse False    
    
# let mkdir create multiple directories at once (like `mkdir dir1 dir2`)    
alias mkdir shell mkdir -p    
# a plugin that adds file glyphs / icon support to Ranger:    
# https://github.com/alexanderjeurissen/ranger_devicons    
default_linemode devicons  
```
#### Running `env SHELL=$(which bash) ranger`

That actually worked. So I guess the problem is with closing a zsh shell.

**Comment by toonn** [comment]
Not really. I'll try to find some zsh users that can shed a light (@Vifon?). How heavily customized is your zsh, OMZsh, prezto, anything?

**Comment by jrwrigh** [comment]
I'm running OMZsh with a SpaceShip theme. I do have a good number of plugins installed. You can look at jrwrigh/dotfiles2.0 for the details. Everything is inside the .zshrc.

**Comment by Vifon** [comment]
In this case it's almost certain on of these plugins is causing it. I never had such a problem on zsh (without OMZ). Try disabling some of them and then narrowing it down to the culprit.

**Comment by jrwrigh** [comment]
The issue appears to be with zplug actually. zplug/zplug#328 and zplug/zplug#426. Guess I'll have to change plugin managers...

Thanks for you guy's help though!
