### ISSUE TITLE
image preview not work for all image

### ISSUE THREAD

**Issue by Monirzadeh** [ranger/ranger#1754]
#### Runtime Environment

- Operating system and version: kubuntu 19.10
- Terminal emulator and version: Konsole 19.04.3
- Python version: 2.7 and 3
- Ranger version/commit: ranger-master v1.9.2-389-g28f3d014

#### Current Behavior
ranger preview break after upgrade to kubuntu 19.10 (i test on a fresh installation)
i test all possible version of ranger repository,master,pip.I use ueberzug for image preview
in pip and repository version image preview not work at all
in master version some image not showing
i think ranger has problem with preview image with bigger than an specific size ,but i am not sure about that.
[example file that Ranger can't show](https://ibb.co/dDWSNKp)
[example file without problem](https://ibb.co/1JrTHXT)

**Comment by toonn** [comment]
Are you running ranger in tmux? We have an existing issue where someone figured out images above a certain size don't work when in tmux. I *think* it was with the iterm2 preview method though.

**Comment by Monirzadeh** [comment]
No  I am not using tmux
I test image preview in vifm too
same problem happen there but in vifm after a while image preview stop working completely.
Maybe some incompatibility with ueberzug?
How can I get log about image preview?
Maybe that can be helpful?

**Comment by toonn** [comment]
@seebye, could you take a look at this? It seems specific to `ueberzug`, are there compatibility issues with the latest python 3 or Konsole or is Kubuntu 19.10 running an X compatibility layer on top of wayland that ueberzug doesn't agree with?

@Monirzadeh, could you check whether you installed ueberzug with `pillow-simd` or just `pillow`? Some users experience problems with the former.

**Comment by Monirzadeh** [comment]
I am use pillow-simd
Can you explain with more details what do you want to test?
Do you want to test that with wayland?

**Comment by seebye** [comment]
I think it's a bug of pillow-simd:  
https://github.com/uploadcare/pillow-simd/issues/53#issuecomment-499449269
Also a user reported that this bug won't occur if a older version of gcc was used to compile pillow-simd:  
https://github.com/uploadcare/pillow-simd/issues/53#issuecomment-508328182
=> Try pillow instead of pillow-simd.

**Comment by Monirzadeh** [comment]
i switch to pillow and problem solved
so the problem is pillow-simd
i am not test gcc for now

**Comment by Monirzadeh** [comment]
use pillow with ranger from ubuntu 19.10 repository not working
only ranger that clone for repository work

**Comment by toonn** [comment]
I wonder why ubuntu packages it with `pillow-simd` by default?
