### ISSUE TITLE
Not able to start after update.

### ISSUE THREAD

**Issue by vevais** [ranger/ranger#1755]
Hello, after updating ranger-git from the AUR I am no longer able to start ranger.

#### Runtime Environment

- Operating system and version: 5.3.11-arch1-1
- Terminal emulator and version: urxvt 9.22
- Python version:  Python 3.8.0
- Ranger version/commit:  ranger-git-1.9.2.333.gfcb01c2c-1
- Locale: 
```
   System Locale: LANG=de_DE.UTF-8
       VC Keymap: de
      X11 Layout: de
       X11 Model: thinkpad
```
#### Current Behavior
Not able to start ranger
#### Expected Behavior
Being able to start ranger.
#### Context
I try to start the program without errors.

#### Possible Solutions
Downgrading to Python 3.7.4 solved the problem for now.
#### Steps to reproduce
1. Install latest ranger-git from AUR
2. Run ranger

#### Traceback

```
Traceback (most recent call last):
  File "/usr/bin/ranger", line 35, in <module>
    import ranger  # NOQA pylint: disable=import-self,wrong-import-position
ModuleNotFoundError: No module named 'ranger'
```
```

**Comment by vevais** [comment]
It didn't fully rebuild everything when updating. My fault, sorry.

**Comment by iambumblehead** [comment]
this command rebuilds [ranger-git](https://aur.archlinux.org/packages/ranger-git) from the cloned aur folder: `makepkg -sCLfi`
