### ISSUE TITLE
Input regarding desired behavior for marking across multiple directories

### ISSUE THREAD

**Issue by zyklotomic** [ranger/ranger#1759]
#### Current Behavior
When you select/mark multiple files (with space) across multiple directories and perform and action such as yank with `yy`, only the files in the currently focused directory get yanked. 

#### Potential Expected Behavior
Allow selection across multiple directories

#### Context

If you want to select files across multiple directories, you have to perform your actions on a per-directory basis. Fortunately, highlights / selections are preserved per directory. As in, if I select files in a directory, move out of the directory, and then later return to it, the selections persist.

#### Possible Solutions
- Allow for a setting on the behavior of selection that the user can set.
-  Add a binding such as prepending a command by `*` to act on all selections. For example, `*yy` to yank all selections instead of just in the current directory.

However, this may require a modification to the "Mrk" indicator on the status bar on the bottom right to accommodate this change in behavior.

I am not sure if this kind of behavior would be desirable to anyone else and would like to get some input on this.

**Comment by toonn** [comment]
You need to think more vim. Marking's like visual selections. So they're limited to what you can see. You can already do what you want by using `ya` to *add* to the copy buffer rather than replace its contents.

**Comment by zyklotomic** [comment]
That works, thank you for the clear up!

**Comment by Vifon** [comment]
@toonn, while we support it, I'd consider adding such a feature as (a) people often ask about it, (b) I indeed can see some value in it.

I'll look into it when I'll get some time.

**Comment by toonn** [comment]
@Vifon, sure, go ahead. Some `argdo` functionality would be great.
As long as it changes nothing about the current behavior though. I suspect this can get confusing pretty quick.
