### ISSUE TITLE
Open csv files with libreoffice

### ISSUE THREAD

**Issue by lyh970817** [ranger/ranger#1761]
#### Runtime Environment

- Operating system and version: Manjaro 5.3.12
- Terminal emulator and version: gnome-terminal 3.34.2
- Python version: 3.7.4
- Ranger version/commit: 1.9.2
- Locale: eu_GB

#### Current Behavior

`ranger` opens csv files with my default text editor neovim, even after I changed the settings in 
rfile.conf.

#### Expected Behavior

Use `libreoffice` as default to open csv files.

#### Steps to reproduce

I removed all csv from all sections of rfile.conf, and added `ext csv = libreoffice "$@"` then tried to open csv file in `ranger`.

**Comment by toonn** [comment]
Couple things:
  - Does `libreoffice your.csv` open the file in LO?
  - Does the file have the `.csv` extension?
  - Where did you add the rule? If you add it to the bottom of `rifle.conf` generic rules will match it first.

**Comment by lyh970817** [comment]
Thank you so much for the response.

* What is LO? `libreoffice your.csv` works fine in terminal.

* Yes I've checked that the file has `.csv` extension.

* I put it at the end of `rifle.conf`. So the last part of it looks like

```
# The very last action, so that it's never triggered accidentally, is to execute a program:
mime application/x-executable = "$1"

ext csv = libreoffice "$@"
```

The `rifle.conf` file I modified is in `~/.config/ranger/`.

**Comment by toonn** [comment]
That last part's gonna be the problem. Put the rule high up in the file. There's a couple catch-all rules that are probably getting triggered before your rule has a chance to.

**Comment by lyh970817** [comment]
Thank you! It works fine now. I thought I had deleted thouse catch-all rules by removing all the "csv" in the file so I didn't think this was the reason.
