### ISSUE TITLE
Disable preview caching?

### ISSUE THREAD

**Issue by smackesey** [ranger/ranger#177]
I am running Ranger on OS X. Because I can't figure out how to get `w3mimgdisplay` to work on OS X, I modified `scope.sh` to preview images by opening them in an external viewer:

```
# ... scope.sh
image/*)
  open -ga "Lyn" "$path" && echo "displaying $path" && exit 0;;
```

As I scroll down over images, this works very well. The problem is, when I scroll back up, the images do not reload in Lyn. I've determined that this is not an issue with calling `open` on Lyn-- my guess is that ranger is caching the preview result and so my command is not being executed when I scroll over the target image again. Is there a way to disable this caching? If not, I think it should be added.

**Comment by nfnty** [comment]
Are you still having this issue?

**Comment by smackesey** [comment]
Stopped using Ranger a while ago so I can't say.

**Comment by nfnty** [comment]
Alright. If you start using ranger again and still experience this issue, then open a new issue.
