### ISSUE TITLE
Ranger won't start after I updated something.

### ISSUE THREAD

**Issue by ShaddaiSchelin** [ranger/ranger#1779]
Hi, 
I updated my system on Manjaro i3. I couldn't launch ranger after that, it would blink up and then gone. 
I tried running from terminal and getting the version with --version but all I get back is this.

Traceback (most recent call last):
  File "/usr/bin/ranger", line 35, in <module>
    import ranger  # NOQA pylint: disable=import-self,wrong-import-position
ModuleNotFoundError: No module named 'ranger'

Thanks for any help.

**Comment by toonn** [comment]
You've updated python and ranger didn't get installed for the new one. If you've installed ranger from the package manager that shouldn't happen, report it as a bug to the maintainers.
If you installed ranger using pip this is unavoidable and you need to `pip install ranger-fm` every time you update python. Similar thing if you install from the repo manually.

**Comment by ShaddaiSchelin** [comment]
Thanks!
I just installed the ranger-git from the AUR. It works now.
