### ISSUE TITLE
Keybindings for cut/yank/paste not working

### ISSUE THREAD

**Issue by Emceelamb** [ranger/ranger#1782]
Hi I'm not sure if its a bug or user error but I can't get file movement operations on ranger working. I haven't seen any information on the wiki or elsewhere.

*What works*: I can move with with `<h>`, `<j> `,`<k>`, `<l>`, rename files, `<A>`, `<I>`, etc. and mark files `<Space>`. But when it comes to two stroke commands like cut ,`<dd>`, yank`<y>` or paste `<p>`, instead of performing the action a  table of key and command bindings shows up instead.

I tried installing from installing from pacman, make install from the repo, and running ranger without installing but all have the same result.   I copied the config files as well with no result. `ranger --copy-config=all`

I'm sure its something I haven't set up but any info would be great. 
Thanks!

**Comment by toonn** [comment]
The table that pops up shows you which commands you could enter. For example, for `y` it should show something like:
```
y copy
a copy mode=add
r copy mode=remove
t copy mode=toggle
etc.
```

This is because `yy`, `ya`, `yr`, etc. are all valid commands and we don't expect users to remember all of the sequences. So you're just not pressing enough keys or you're pressing them too fast, which'd surprise me.

**Comment by Emceelamb** [comment]
That makes sense. I think I was trying to cut and I saw the file was still there so I thought nothing happened. The file gets removed *after* you paste.

Thanks!

**Comment by toonn** [comment]
Yes, cutting/yanking does grey out the file to indicate it's in the copy buffer but it's the paste that does the move or copy action.
