### ISSUE TITLE
Ranger cannot open macOS alias files

### ISSUE THREAD

**Issue by tbrodbeck** [ranger/ranger#1788]
#### Runtime Environment

- Operating system and version: macOS 10.15.2 19C57 x86_64
- Terminal emulator and version: iTerm Build 3.3.6
- Python version: 2.7.16
- Ranger version/commit: 1.9.2
- Locale: None.None

#### Current Behavior
macOs aliases cannot be opened. Alias files are something like symbolic links to directories in macOS.

#### Expected Behavior
1. Most essential request: Open the alias files in some way, so ranger changes to the referenced directory.

2. Additional wish: It would be even more awesome to treat alias files exactly as directories (apart from copying).

#### Context

I am using alias files on my desktop (to have all my most essential directories in one place and to quickly move files) and it would be awesome to use them in ranger as well.

#### Possible Solutions
I found a bash binary (https://apple.stackexchange.com/questions/180762/how-to-go-to-alias-from-terminal) to retrieve the linked name from an alias file. 
Right now I tried to find a way to let ranger change the current directory to the output of that shell script (to solve 1). Something like: `map b eval cd subprocess.Popen(['getTrueName', fm.thisfile.relative_path])`- but this is invalid syntax (and I did not import subprocess in python). 
Therefore, any suggestions are more than welcome!

#### Steps to reproduce
1. Create an alias file of a directory in macOS.
2. Browse this file in ranger.

**Comment by toonn** [comment]
I don't think we'll add this feature unfortunately. These "aliases" are a feature specific to Finder. We can't very well be expected to add support for "special links" that other file managers want to add. Are you sure replacing these aliases with symlinks isn't a sufficient solution?

@Vifon, this *is* pretty central to macOS's Finder. Do you think revising our handling of symlinks to include aliases is worth the trouble?

**Comment by tbrodbeck** [comment]
I never used symlinks before. So I just created a symlink (`ln -s Box ~/Desktop`), but ranger does not seem handle these files neither.

Furthermore, I can understand if the correct handling of aliases in a finder'esque manner is not high in priority. Then maybe you could then help me out how to change the ranger directory to the output of the `getTrueName` shell script? I am kinda stuck there.

**Comment by toonn** [comment]
Symlinks work just fine so you must be doing something wrong.

Getting a preview to show of the contents of an alias would be easy, probably just a new block in `scope.sh`. Having an alias function as if it's a symlink is hard and requires changes to ranger's internals. We can try to help in #ranger@freenode but you'd have to do some heavy lifting first.

**Comment by tbrodbeck** [comment]
Yes, the `ln` command has some issues (https://unix.stackexchange.com/questions/141436/too-many-levels-of-symbolic-links). Now I feel enlightened. Finder integrated symlinks exactly as aliases. 
Thanks guys. Merry xmas

**Comment by Vifon** [comment]
> @Vifon, this is pretty central to macOS's Finder. Do you think revising our handling of symlinks to include aliases is worth the trouble?

@toonn, it depends on how much trouble we are talking about.

@tbrodbeck, do you consider it solved then?

**Comment by tbrodbeck** [comment]
Yes, from my side this is solved!

**Comment by Vifon** [comment]
@toonn, I'm not familiar with macOS enough to judge how serious it is in general. Should we close it?

**Comment by toonn** [comment]
I'm ok with closing this and here's my motivation:

People interested in using ranger are usually somewhat terminal power users. You can't create aliases from outside the Finder and you can't use `ls/cd`, for example, with an alias. So these people usually don't take long to switch to symlinks.

BUT, previews might not be too hard and are a fair feature request imo.

**Comment by Vifon** [comment]
I see. I guess I wouldn't expect ranger to work with the Windows .lnk files either. I'm closing for now then.
