### ISSUE TITLE
Fuzzy Tab completion on cd only inserts highest directory level result

### ISSUE THREAD

**Issue by wilecoyote2015** [ranger/ranger#1792]
#### Runtime Environment
```
ranger version: ranger-master 
Python version: 3.8.0 (default, Oct 23 2019, 18:51:26) [GCC 9.2.0]
Locale: en_GB.UTF-8
```
- Operating system and version: Arch Linux
- Terminal emulator and version: Termite 15
- Ranger version/commit: Master build today
- `cd_tab_fuzzy true`

#### Current Behavior
When trying to fuzzy-complete relatively over two directory levels, the first level is omitted. For example, `cd usr/sh` completes to `cd share`

#### Expected Behavior
In the example given above, `cd /usr/sha` should complete to `/usr/share`.

#### Context
This issue is preventing quick multi-level directory changes using cd fuzzy completion.

#### Steps to reproduce
1. Navigate to `/`
2. `cd usr/sh`
3. Press tab. The line is replaced by `cd share`. When pressing enter, the directory is not changed accordingly.

**Comment by toonn** [comment]
Yep, I can confirm this is a bug. The entire prefix that already *is* an exact match is simply dropped.

**Comment by toonn** [comment]
You might want to take a look at `:travel` while waiting for that fix to land : )

**Comment by wilecoyote2015** [comment]
Thank you for the hint! :)
