### ISSUE TITLE
Cannot Set Title for Terminal Emulator

### ISSUE THREAD

**Issue by 3N4N** [ranger/ranger#1797]
#### Runtime Environment

- Operating system and version: Ubuntu 18.04.3 LTS
- Terminal emulator and version: xfce4-terminal 0.8.7.4 (Xfce 4.12)
- Python version: 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
- Ranger version/commit: ranger 1.9.2
- Locale: en_US.UTF-8

#### Current Behavior
The title for terminal emulator doesn't change when `ranger` is executed.
#### Expected Behavior
The titlebar of terminal emulator should say ranger is running.
#### Context

I would like to know which window of terminal emulator is running ranger so I can quickly locate it from the windows-panel or taskbar. I have `set update_title true` in my `rc.conf`, but it does nothing.
I do have the following snippet in my `bashrc` which sets the title for my terminal emulator window when in bash.
```bash
case "$TERM" in
	xterm*)
		PROMPT_COMMAND='printf "\033]0;%s@%s:%s\007" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/"~"}"'
		;;
esac
```
Maybe this is clashing somehow with ranger, but I have checked disabling the snippet, and ranger still doesn't set the title. So it can't be the problem.

**Comment by JadowityHerbatnik** [comment]
What's the output of ```xprop```?

**Comment by 3N4N** [comment]
@JadowityHerbatnik The output of `xprop` is pasted below, ignoring the icons.

```
_NET_WM_ICON_GEOMETRY(CARDINAL) = 501, 0, 200, 30
_NET_FRAME_EXTENTS(CARDINAL) = 1, 1, 24, 1
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_STICK
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x6f392f00
_NET_WM_DESKTOP(CARDINAL) = 1
_NET_WM_STATE(ATOM) = 
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x3a00c5a
		bitmap id # of mask for icon: 0x3a00c61
		window id # of group leader: 0x3a00001
_GTK_THEME_VARIANT(UTF8_STRING) = 
XdndAware(ATOM) = BITMAP


WM_WINDOW_ROLE(STRING) = "xfce4-terminal-1577637356--21142018"
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 60820568, 60820569
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x3a00c57
WM_CLIENT_LEADER(WINDOW): window id # 0x3a00001
_NET_WM_PID(CARDINAL) = 17385
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "elariel"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 30 by 32
		program specified resize increment: 7 by 15
		program specified base size: 2 by 2
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "xfce4-terminal", "Xfce4-terminal"
WM_ICON_NAME(STRING) = "enan@elariel:~"
_NET_WM_ICON_NAME(UTF8_STRING) = "enan@elariel:~"
WM_NAME(STRING) = "enan@elariel:~"
_NET_WM_NAME(UTF8_STRING) = "enan@elariel:~"
```

**Comment by toonn** [comment]
@3N4N, remove that snippet from your bashrc and run xprop's spy feature. Then run ranger in the terminal you're spying on and move through some directorie. You should see `WM_NAME` being updated in the xprop output.

**Comment by 3N4N** [comment]
> You should see `WM_NAME` being updated in the xprop output.

@toonn, It doesn't change. I have removed the snippet, run ranger on a terminal, run `xprop -spy` and selected the window running ranger and moved around in the filesystem. But the title of the terminal doesn't change.

**Comment by toonn** [comment]
What if you `export TERM=xterm+sl` first?

**Comment by 3N4N** [comment]
@toonn Ranger crashes when I try to open it. The output (traceback) is pasted below.

```
Traceback (most recent call last):
  File "/home/enan/.local/bin/ranger", line 36, in <module>
    sys.exit(ranger.main())  # pylint: disable=no-member
  File "/home/enan/.local/lib/python3.6/site-packages/ranger/core/main.py", line 32, in main
    from ranger.container.settings import Settings
  File "/home/enan/.local/lib/python3.6/site-packages/ranger/container/settings.py", line 13, in <module>
    from ranger.gui.colorscheme import _colorscheme_name_to_class
  File "/home/enan/.local/lib/python3.6/site-packages/ranger/gui/colorscheme.py", line 33, in <module>
    from ranger.gui.color import get_color
  File "/home/enan/.local/lib/python3.6/site-packages/ranger/gui/color.py", line 74, in <module>
    curses.setupterm()
_curses.error: setupterm: could not find terminal
```

**Comment by toonn** [comment]
What does messy mean?

**Comment by 3N4N** [comment]
![Screenshot_2019-12-30_20-23-39](https://user-images.githubusercontent.com/32037751/71585883-4ee9c300-2b42-11ea-8931-1b153e531a3e.png)

**Comment by toonn** [comment]
Do these problems show up if you run `ranger --clean`?

**Comment by 3N4N** [comment]
Yeah, same thing.

**Comment by toonn** [comment]
Oh, hold on. You're asking for something different. We recently merged something so `WM_ICON_TITLE` is updated as well. I think that's what you're looking for. So either run the master branch or wait for the next release.

**Comment by 3N4N** [comment]
I just tried the master branch. It doesn't work as well. Same result for all the test cases.

**Comment by toonn** [comment]
And you still have that snippet commented out? How about a different terminal?

**Comment by 3N4N** [comment]
Yes, the snippet is still commented out. I have tried `xterm`, that also doesn't work, same output/result. But `xterm` or `xfce4-terminal`, I think, are very similar. I have tried it on `st` terminal, the suckless terminal, and it works there. The `$TERM` is `st-256color` in `st`. But I have some problems with `st`, it doesn't work well with my workflow. So, I need `ranger` to work the title on `xfce4-terminal`.

**Comment by toonn** [comment]
I don't think this issue can be fixed on our side. We use `tput` to get the proper escape code for `tsf` (*to*-status-line). And for some reason you're not getting the proper escape code when `TERM=xterm*`.

**Comment by 3N4N** [comment]
Can I at least set the titlebar to say the word "Ranger" when running `ranger`? I should be able to do that with a plugin.

**Comment by toonn** [comment]
`printf "\033];Ranger\007"; ranger` should do that. That's also what ranger internally usually uses but instead of a literal escape we get the proper one from tput.

**Comment by 3N4N** [comment]
Thanks, that'll be enough for me. Thanks for the help!

**Comment by holzboa** [comment]
I recognized this behaviour in xfce4-terminal. 
When i do `ranger --clean` the title changes.
Usually i use `st` to run ranger and there the title changes as advertised.
I stopped using the xfce4-terminal in the first place because of leftover fragments when using w3m preview.
