### ISSUE TITLE
Cannot map <C-h> to move left in console

### ISSUE THREAD

**Issue by smackesey** [ranger/ranger#180]
Not sure what it is about <C-h> specifically, but I have it mapped to

```
cmap <C-h>  eval fm.ui.console.move(left=1)
```

And the mapping simply doesn't work. It performs a backspace to the left instead of just moving the cursor. I have this as the last line in my rc.conf and `?1` shows the mapping correctly.

**Comment by GhostSquad57** [comment]
Hey I found a fix too this issue!

from my `~/.local/config/ranger/rc.conf` file:

`unmap <C-h>
map <263> eval fm.ui.console.move(left=1)`

Should work for you!

Nice knowing you can just supply the key code for bindings. :)
