### ISSUE TITLE
The current directory is not readable when using a light theme.

### ISSUE THREAD

**Issue by Kharacternyk** [ranger/ranger#1800]
#### Runtime Environment
ranger version: ranger 1.9.2
Python version: 3.8.1 (default, Dec 21 2019, 20:57:38) [GCC 9.2.0]
Locale: None.None
OS: Arch Linux
Terminal: Termite v15, Alacritty is affected too.

#### Current Behavior
When one uses a light theme in the Termite some text (current folder on top) appears as white on white background.

#### Expected Behavior
Text is rendered properly: black on white.

#### Context
The desired behaviour is achieved when I use xterm. I believe, that the issue has something to do with the default background of a terminal emulator, since Termite and Alacritty are dark by default and xterm is light.

#### Possible Solutions
Workaraounds, that users may use now:
- Swap black and white in the Termite settings. Works poor, since other programms, such as neovim, expect that black (color 0) is actually black.
- `export TERM=xterm`

I see a global setting to hint ranger what color background is as a proper solution.

#### Steps to reproduce
1. Open ranger in Termite or Alacritty while using light theme.
2. See that the current directory is not readable.

**Comment by Kharacternyk** [comment]
![screen](https://user-images.githubusercontent.com/43315801/71593056-25796900-2b3b-11ea-9651-43a4f0c4f104.png)
The screenshot may be helpful. Notice that there isn't `lost+found` on top in the ranger instance in Termite.

**Comment by toonn** [comment]
I'd expect the same problem in xterm if `TERM=xterm-256color`.

**Comment by toonn** [comment]
I'd expect the same problem in xterm if `TERM=xterm-256color`.

Could you try if #1801 fixes the issue?

**Comment by Kharacternyk** [comment]
> Could you try if #1801 fixes the issue?

Yes, it does!
