### ISSUE TITLE
Loading pictures is slow

### ISSUE THREAD

**Issue by xiaolongGitHub1498** [ranger/ranger#1808]
#### Runtime Environment

- Operating system and version: macOS 10.14.6
- Terminal emulator and version:  iTerm Build 3.3.7
- Python version: 3.7.3
- Ranger version/commit: 1.9.3
- Locale: 

#### Current Behavior
picture size is about 1M
Loading pictures is slow

#### Steps to reproduce
1. set open_all_images true
2. set preview_images_method iterm2

#### Traceback

```

```

**Comment by toonn** [comment]
There's nothing we can do to speed it up. Ranger doesn't process the image so there's no code we can optimize. I believe we have a setting that prevents previews above a certain size.
