### ISSUE TITLE
Add sort

### ISSUE THREAD

**Issue by hk0kizu** [ranger/ranger#1813]
May be to add option sorting for current dir?
Now <O-_x_> is not using anywhere and may add function sorting current path on this key.

**Comment by toonn** [comment]
I'm not sure what you're asking for we have various sorting methods available typing `o` will show a hints window with options.

**Comment by lkhd** [comment]
I think he means independent sorting methods per folder.

**Comment by toonn** [comment]
That's possible with `:setlocal`.

**Comment by hk0kizu** [comment]
> That's possible with `:setlocal`.

Oh, thank, `map <O-x> chain setlocal sort=` - that's what I need.
