### ISSUE TITLE
w3m Preview out of alignment (even with borders)

### ISSUE THREAD

**Issue by hisacro** [ranger/ranger#1817]
[out of alignment image preview with w3m](https://i.imgur.com/KpZ81bM.png) 

ranger --version
`ranger version: ranger-master 
Python version: 3.8.1 (default, Jan  8 2020, 23:09:20) [GCC 9.2.0]
Locale: en_US.UTF-8
`
w3m version
`w3m 0.5.3.git20190105-1`
rc,conf
`set preview_images true
set preview_images_method w3m
set draw_borders true
`

**Comment by hisacro** [comment]
I have isolated the issue, it's because of xfce4-terminal

**Comment by hisacro** [comment]
I couldn't solve the issue, but simple workaround using ueberzug

**Comment by toonn** [comment]
There may not be a true solution for `w3mimgdisplay`. It is designed for `XTerm` and *no* other terminals. So it only kinda works by accident in some other terminals.
