### ISSUE TITLE
Warning: Unable to set locale.  Expect encoding problems.

### ISSUE THREAD

**Issue by kjhuanhao** [ranger/ranger#1818]
#### Runtime Environment

- Operating system and version: ArchLinux
- Terminal emulator and version: konsole19.12.1
- Python version: 3.8.1
- Ranger version/commit: 1.9.3
- Locale: None None

#### Current Behavior
The following error occurred after I quit the Ranger.
```
Warning: Unable to set locale.  Expect encoding problems.
```
#### Expected Behavior
I should have quit Ranger perfectly.
#### Context

I don't want to see the last warning. I don't know how to solve this problem.
#### Possible Solutions
Maybe it's a matter of variables.
#### Steps to reproduce
1. open the ranger
2. 
Screenshot:
![](https://cdn.jsdelivr.net/gh/kjhuanhao/cdn/blog/ranger.gif
)

#### Traceback

```
Warning: Unable to set locale.  Expect encoding problems.

```

**Comment by toonn** [comment]
This is due to this code in `main.py`:
```python
    try:
        locale.setlocale(locale.LC_ALL, '')
    except locale.Error:
        print("Warning: Unable to set locale.  Expect encoding problems.")
```

I'm not sure on why we explicitly clear `LC_ALL` tbh. And I'm not sure why `setlocale` doesn't work in your environment. You should find that out.

**Comment by sebhahn** [comment]
I have the same issue
