### ISSUE TITLE
st v0.8.2 with image preivew under w3m not work

### ISSUE THREAD

**Issue by iysheng** [ranger/ranger#1820]
```bash
[yys@yys st]$ ranger --version
ranger version: ranger 1.9.2
Python version: 3.7.6 (default, Dec 19 2019, 22:52:49) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
Locale: en_US.UTF-8
```
I want to set imgae preview under st v0.8.2,and i modify **~/.config/ranger/rc.conf** file as blew
```vim
set preview_images true
set preview_images_method w3m
```
but it doesn't work, i test under xterm,it works.
it confused me, i see [wiki](https://github.com/ranger/ranger/wiki/Image-Previews), since st v0.6 support w3m with image preview.
besides, i install ranger-master,but it's still not work on st v0.8.2
```bash
[yys@yys Downloads]$ ranger --version
ranger version: ranger-master
Python version: 3.7.6 (default, Dec 19 2019, 22:52:49) [GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
Locale: en_US.UTF-8
```

**Comment by toonn** [comment]
Unless you can verify that `w3mimgdisplay` works in the `w3m` browser in `st` there's nothing we can do. Try the `ueberzug` preview method instead.

**Comment by iysheng** [comment]
@toonn thanks,that's ok after i use ueberzug methord.why not add this methord to wiki?

**Comment by toonn** [comment]
Not sure where on the wiki you'd expect to find it? Feel free to edit the wiki though, it's specifically for community contributions. Ueberzug is documented in both `README.md` and the ranger man page.
