### ISSUE TITLE
I have a red colon next to a directory. I pressed some keys that made it appear. 

### ISSUE THREAD

**Issue by unphased** [ranger/ranger#1821]
Does anyone know what this is? 

It's on the `git` dir here.

![image](https://user-images.githubusercontent.com/1542910/73407705-f1bf6980-42c7-11ea-90fd-7cdc9c43b156.png)

I would like to know how to remove it and also what keys i might have pressed to make it appear.

**Comment by dennisschagt** [comment]
It looks like that mark/tag can be added (and removed) by pressing `"` -> `:` (or entering command: `:tag_toggle tag=:`

**Comment by unphased** [comment]
Thank you. Did the trick

**Comment by toonn** [comment]
Yep, you probably tagged it by accident by pressing `":`, you can remove any tag using `ut` for "undo tag," btw.
