### ISSUE TITLE
Issue while opening ranger directly from the file manager without the terminal

### ISSUE THREAD

**Issue by LucKy-4U** [ranger/ranger#1822]
I tried making ranger my default file manager by having a shortcut to start ranger directly without having to go into the terminal but it looks very ugly and doesn't go full screen. :(
here is how it looks like : 
![image](https://user-images.githubusercontent.com/8860476/73609685-462f5580-45f6-11ea-962f-2f06553e1335.png)

How do I fix the ugliness to make it look like this?:
https://i.stack.imgur.com/rTL1n.png

also, how do I make it start in full screen instead of that small window?
I would really appreciate any help, Thank You very much.

I am on Ubuntu 16.4 LTS.

**Comment by toonn** [comment]
It's getting started in XTerm probably. So change the `.desktop` file to start it in a different terminal or find out whether you can set a default terminal. Whether or not you can have it start fullscreen depends on the terminal you run ranger in and whether it has a `--fullscreen` flag or similar. Good luck!

**Comment by LucKy-4U** [comment]
yea, I figured this out already, thats why I closed this issue. :))
I wanted to use terminology for this but wasn't able to. :((

**Comment by toonn** [comment]
You should be able to, it even has a `--fullscreen` flag.

**Comment by LucKy-4U** [comment]
> You should be able to, it even has a `--fullscreen` flag.

How? like this?
`Exec=/snap/bin/terminology --fullscreen /usr/bin/ranger`

This turns my entire screen black. it doesn't work.

when I remove `--fullscreen` and just use:
`Exec=/snap/bin/terminology /usr/bin/ranger`

This somehow starts 2 instances of terminology but neither of them have ranger opened. :((
so I am unable to get terminology to work for ranger.

**Comment by toonn** [comment]
I don't think you can simply pass a path to terminology, you'd use `--exec`. I'm also not sure whether desktop files allow more than a simple command in the Exec clause.

**Comment by LucKy-4U** [comment]
> I don't think you can simply pass a path to terminology, you'd use `--exec`. I'm also not sure whether desktop files allow more than a simple command in the Exec clause.

ok, that works. but the problem is that now I can't use the --fullscreen flag. :P
can only use either --exec or the fullscreen flag.
It works perfectly fine with Gnome-terminal though, just the terminal isn't as pretty as Terminology. :))

I really want to make Ranger my default File manager for my system but it's sad that I can't. I hate the fact that everytime I need to access it, I gotta go inside the terminal. Even though now I have figured out how to start it directly without the terminal but still, It can't be used to open files when lets say uploading a file on firefox using the open button.

one more thing that I would have loved for it to have is direct access to Terminal at the bottom.

so sorta like Terminology on steroids. I don't find any purpose for having a terminal which is only good for executing commands. One line for commands is enough, which could be made bigger if we ever needed to see the output, etc.

**Comment by toonn** [comment]
Did you try both orders of the flag? I suspect `--fullscreen` would have to precede the `--exec`.
That's what `S` is for. And `shell` also has flags to keep showing output iirc.

Firefox doesn't use any file managers afaik. It uses the GTK or Qt or whatever window framework's filepicker. I vaguely remember some comments from someone who was trying or managed to use ranger as firefox's filepicker though.

**Comment by LucKy-4U** [comment]
Yes, that's how I know that I am unable to use both flags together. :P
I tried preceding --exec and then after it as well. neither worked.
I don't understand what you mean by S though. I didn't use S anywhere.

and regarding setting Firefox as the filepicker in firefox, Really? that would be awesome, could you please give me the link to that? if possible? I would like to set ranger as the default filepicker for all apps as well but only for firefox is atleast a good start. :))

**Comment by LucKy-4U** [comment]
It works fine when I use just `--exec` though.

**Comment by toonn** [comment]
I don't have a link, that's why I said "vaguely."

`S` is a key binding in ranger to open up a shell in the current directory.
