### ISSUE TITLE
Image preview not working with kitty or w3m

### ISSUE THREAD

**Issue by VariabileAleatoria** [ranger/ranger#1823]
#### Runtime Environment

- Operating system and version: Ubuntu 18.04
- Terminal emulator and version: kitty 0.16.0 | xfce4-terminal 0.8.7.4
- Python version: Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 7.4.0]
- Ranger version/commit: ranger-stable 1.8.1
- Locale: en_US.UTF-8

#### Current Behavior

Trying to display image preview, edited rc.conf with
`set preview_images true`
`set preview_images_method kitty`

but nothing shows up inside kitty terminal  

here a screenshot: https://imgur.com/a/zkroGo8

I tried too with xfce4 terminal (using w3m method) but still no previews are showed, (but I'm able to see images in both terminals using their different methods icat and w3m, but unable to see them inside ranger)

ranger --version displays Python 2.7.17 but I also have Python 3.6.9, I don't know if this can cause conflicts.

EDIT: there were actually some dependencies missing (now it's working with w3m in config both for kitty and xfce4, the latter is buggy as expected)

**Comment by toonn** [comment]
1.8.1 is ancient, way too old for the kitty preview method fyi.

**Comment by VariabileAleatoria** [comment]
> 1.8.1 is ancient, way too old for the kitty preview method fyi.

idk it just works, even though the method in rc.conf is w3m

**Comment by toonn** [comment]
It's great if w3mimgdisplay works. That's actually fairly unexpected. But your original issue report included `set preview_images_method kitty`. I was merely informing you that would never work with such an old ranger version, 1.9.2 is the first that got support for kitty native image previews.
