### ISSUE TITLE
Bulk renaming not working

### ISSUE THREAD

**Issue by jrwrigh** [ranger/ranger#1825]
#### Runtime Environment

- Operating system and version: Manjaro
- Terminal emulator and version: xfce4-terminal 0.8.9.1
- Python version: 3.8.1
- Ranger version/commit: ranger-master (that's all `ranger --version` gives. According to Manjaro, it's `1.9.3.4.gd8c363c9-1`)
- Locale: en_US.UTF-8

#### Current Behavior
Running `:bulkrename` while having marked files simply brings up `No renaming to be done!`
![Peek 2020-02-03 16-16](https://user-images.githubusercontent.com/20801821/73699312-af6ba300-46a0-11ea-9bae-0118a56f11e9.gif)

#### Expected Behavior
It to launch the standard `:bulkrename` feature (open file with the names, then do the renaming once the file is saved and closed).

#### Context
I'm trying to rename multiple files

#### Possible Solutions
Not sure why it's happening, so can't really offer any

#### Steps to reproduce
1. Go to directory
2. Mark files
3. Type `:bulkrename`

**Comment by toonn** [comment]
I suspect you've configured rifle to open a graphical text editor?

**Comment by jrwrigh** [comment]
I have not. It's supposed to open in neovim.

**Comment by toonn** [comment]
Maybe neovim forks? That would mean it cannot work with `bulkrename` unfortunately. We wait for the process to return and then read the file. If the process forks, the call returns *immediately*.

**Comment by jrwrigh** [comment]
Today it's deciding to work for some reason. It's not a blanket neovim issue, as I've used it with neovim for awhile before now and it worked fine. I'll close for now.

**Comment by toonn** [comment]
Curious

**Comment by jrwrigh** [comment]
Error came back inexplicably. I think it's an issue with `rifle` as it won't let me open any text documents.

**Comment by jrwrigh** [comment]
So trying to open anything right now doesn't work *except* for pdfs. I do have a custom `rifle.conf` placed in `~/.config/ranger`. It's contents are simply: `ext pdf, has masterpdfeditor4,     X, flag f = masterpdfeditor4 "$@" `

So is rifle not able to read the default configuration file?

**Comment by toonn** [comment]
Rifle only reads a single configuration file because the order matters and whether we read the users config first or last there's always someone who wants it the other way around.

**Comment by jrwrigh** [comment]
Makes sense. Thanks for the clarification. It might be worth adding that to `rifle`'s man page since that isn't mentioned.

**Comment by jrwrigh** [comment]
Would I need to edit the `rifle.pod` or `rifle.1` file for a PR? Can't tell if one is used to create the other.

**Comment by toonn** [comment]
`rifle.1`'s generated from `rifle.pod`.
