### ISSUE TITLE
Setting Ueberzug to preview images is not working in Ubuntu

### ISSUE THREAD

**Issue by LucKy-4U** [ranger/ranger#1827]
I have set this inside my rc.conf file:
`set preview_images true`
`set preview_images_method ueberzug`

This doesn't seem to work. I installed ueberzug using pip3 command.
when I remove the `set preview_images_method ueberzug`, image previews work perfectly fine but by using the w3mdisplay. I wanted to use ueberzug because it was superior to w3mdisplay.

I can confirm that ueberzug is in the PATH. I am able to execute it directly from my command prompt.

#### Runtime Environment

- Operating system and version: Ubuntu 16.4 LTS
- Terminal emulator and version: Terminology 1.6.99
- Python version: 3.5.2
- Ranger version/commit: ranger-stable 1.7.1
Python 2.7.12 (default, Oct  8 2019, 14:14:10)
[GCC 5.4.0 20160609]

**Comment by toonn** [comment]
Such an ancient version of ranger doesn't support ueberzug. Even Debian has 1.8.1 : )
You need 1.9.3 for ueberzug previews.

**Comment by LucKy-4U** [comment]
> Such an ancient version of ranger doesn't support ueberzug. Even Debian has 1.8.1 : )
> You need 1.9.3 for ueberzug previews.

lol, sorry, I am using 16.4 LTS. probably why ubuntu installed such an old version.
does ranger have its own ppa? which I can setup to get the latest version automatically?

**Comment by r4v** [comment]
@LucKy-4U i'm on ubuntu too. Try this:
`sudo apt remove ranger`
and
`sudo -H pip3 install ranger-fm`

**Comment by toonn** [comment]
We don't maintain a ppa. The nix package manager is a cross platform option. Pip is another option and manually installing from the repo should be pretty easy.

**Comment by LucKy-4U** [comment]
> @LucKy-4U i'm on ubuntu too. Try this:
> `sudo apt remove ranger`
> and
> `sudo -H pip3 install ranger-fm`

Thank You my friend. This works. :)) But colors were much nicer in the older version though, This version doesn't look as slick or pretty. :P
@toonn, ueberzug is still not working though? :((
I just checked the rc.conf, everything is still in there but it's still not working.

ranger version: ranger 1.9.3
Python version: 3.5.2 (default, Oct  8 2019, 13:06:37) [GCC 5.4.0 20160609]
Locale: en_US.UTF-8
lucky@Lucky:/usr/loc

**Comment by LucKy-4U** [comment]
> We don't maintain a ppa. The nix package manager is a cross platform option. Pip is another option and manually installing from the repo should be pretty easy.

@toonn, ueberzug is still not working though? :((
I just checked the rc.conf, everything is still in there but it's still not working.

ranger version: ranger 1.9.3
Python version: 3.5.2 (default, Oct  8 2019, 13:06:37) [GCC 5.4.0 20160609]
Locale: en_US.UTF-8
lucky@Lucky:/usr/loc

**Comment by toonn** [comment]
And you installed ueberzug with for that same python version?

**Comment by LucKy-4U** [comment]
yes. I used:
sudo pip3 install ueberzug.

**Comment by LucKy-4U** [comment]
well, it seems ungrading `ranger` stopped the preview altogether even though I still have w3m in my system.

**Comment by toonn** [comment]
What terminal are you using? Terminology has its own preview method.

**Comment by LucKy-4U** [comment]
> What terminal are you using? Terminology has its own preview method.

Yes, it does but Terminology installed using Snap doesn't show previews. Terminology's developer knows it and he says he doesn't "yet" know how to fix it.
Here is the link to that issue: https://phab.enlightenment.org/T8603

But I am pretty sure that `tycat` isn't interferring with this as the previous version of ranger was able to show previews perfectly well using w3m.

**Comment by paulkass** [comment]
> Such an ancient version of ranger doesn't support ueberzug. Even Debian has 1.8.1 : )
> You need 1.9.3 for ueberzug previews.

Yeah, it seems like many package managers don't have `1.9.3` as their main distribution. Here on gentoo `1.9.2` is the latest, and `1.9.3` is only available in "test", so you have to manually unmask it. Hopefully maintainers of these ebuilds or whatever update the repository more often.

**Comment by OverClock-11** [comment]
I use Windows Terminal, but it doesn't work as well.
![image](https://user-images.githubusercontent.com/75160741/188538863-3a4dfb93-acd6-4cf1-9295-6d7a834620a7.png)
![image](https://user-images.githubusercontent.com/75160741/188539248-bf12fa40-235c-409a-8725-19192ba1a24e.png)
the PATH can find ueberzug but ranger can not use it, without any error massage and preview.

**Comment by toonn** [comment]
@LucKy-4U, I think maybe the problem is that your configuration files are too old and no longer in sync with the Ranger version. So try running `ranger --clean` and turning settings on while it's running.

@OverClock-11, Ueberzug requires X11 so it doesn't work on Windows. Unless you really mean WSL?
