### ISSUE TITLE
Release 1.9.3 is unsigned

### ISSUE THREAD

**Issue by maklor78** [ranger/ranger#1834]
The current release version 1.9.3 has not been signed unlike the previous releases.

Please sign all releases and confirm this release as well

SHA256:
ce088a04c91c25263a9675dc5c43514b7ec1b38c8ea43d9a9d00923ff6cdd251  ranger-1.9.3.tar.gz
e4c46c663a4411a52c4bc028adbf6e795f4d56292fbe3b3345bbe9582042ee58  ranger-1.9.3.zip

**Comment by toonn** [comment]
The release *was* signed, I used a temporary key though because I didn't have access when I did the release. I've changed the signatures for ones with my key and published the key to `hkps://keys.openpgp.org` again.

Thanks for the diligence, please let me know if anything's still off.

**Comment by toonn** [comment]
Updated the download page with information about the keyserver I used.
For some reason I couldn't get it to work  with `keys.openpgp.org` so I used `pgp.mit.edu`.
