### ISSUE TITLE
mkdir doesn't accept a directory name that contains %

### ISSUE THREAD

**Issue by crocket** [ranger/ranger#1835]
#### Runtime Environment

- Operating system and version: Gentoo
- Terminal emulator and version: alacritty-0.4.1
- Python version: python-3.6.9
- Ranger version/commit: 1.9.2
- Locale: en_US.UTF-8

#### Current Behavior

`:mkdir a % b` results in an error.

![issue](https://user-images.githubusercontent.com/748856/74132791-94fa7200-4c2a-11ea-8574-3b2ce7bd9664.png)

#### Expected Behavior

It should create a directory that contains %.

**Comment by toonn** [comment]
`%` is ranger's character for macros, try escaping it by doubling up `%%`.

**Comment by crocket** [comment]
`%%` is replaced by `%`. Is it documented anywhere?
