### ISSUE TITLE
enhancement request

### ISSUE THREAD

**Issue by c-amow** [ranger/ranger#1836]
Using latest master each filetype seems to have a best method for previewing - it would be nice to assign a default and then overrides.

Thanks, I'm late to the party but loving this file manager (not an mc fan)

**Comment by toonn** [comment]
Not sure what you mean. Scope already uses a fallback mechanism using the best or rarest way to generate a preview first and then trying the next one if it fails.

**Comment by c-amow** [comment]
Ok, thanks - probably pilot error - it seems like some settings are cached in some way or do not get updated immediately.  e.g. I change method to terminology and then back to w3m and have residual behavior...

**Comment by toonn** [comment]
Did you mean previewing jpegs with the w3m method and pngs with the terminology method or something?

That's not supported for various reasons. Most of the previewing methods are pretty fragile even when you don't switch back and forth. We get tons of issues about previews we can't do anything about as it is so this is not a usecase we want to support.
