### ISSUE TITLE
Support for symbolic links in the image cache directory

### ISSUE THREAD

**Issue by seebye** [ranger/ranger#1837]
### Current Behavior
In the current version of ranger an image in the cache directory of ranger is outdated if it's last modified timestamp is smaller than **or equal** to the last modified timestamp of the file it's a preview of.  
See: 
https://github.com/ranger/ranger/blob/3f8e7c14103a6570b0e55fbcf84242c86f42a7cb/ranger/core/actions.py#L1127

#### Expected Behavior / Context

I just wanted to ask whether the the `>` could be changed to `>=` as it would allow to use a work around to prevent the execution of the scope.sh script.  
(Creating a symbolic link for actual images would prevent the execution of the scope.sh script and therefore save the time required to execute this script)
(Another possibility to support symbolic links would be to extend the 'last modified' clause with os.path.islink)

**Comment by toonn** [comment]
This is a pretty reasonable request. I figure it was done this way because generating a preview always takes at least a little time. I don't think a single second's difference in this handling would introduce many (if any) more glitches.

**Comment by toonn** [comment]
Maybe we can handle such files better in `scope.sh`, either not caching or creating symlinks for them?

**Comment by toonn** [comment]
Actually, hmm, we already `exit 7` if we don't run convert on images. So what images are you running into where they are unnecessarily cached?

**Comment by seebye** [comment]
> Maybe we can handle such files better in `scope.sh`, either not caching or creating symlinks for them?

Currently ranger determines how to preview files by executing the scope.sh script which allows to customize the the preview however an user wants.  
I think this is fine and for e.g. videos a preview will be created by extracting a frame of the image.  
So by supporting symbolic links it's possible to change the scope.sh script to tell ranger that it should just display an existing image by creating a symbolic link to it in the cache directory  
(-> ranger won't rerun the scope.sh script for this file (so a new ranger process would also just tell the image previewer to show the image)).  
Making this decision within ranger would lead to problems e.g. the orientation fix in scope.sh wouldn't be executed.  
So I though that would be the proper way to tell ranger just to always display the image as it seems to fit to the rest of the previewing system.  
Although I wasn't sure whether these symbolic links would lead to problems which is why I wanted to ask before creating a pull request.  

> Actually, hmm, we already `exit 7` if we don't run convert on images. So what images are you running into where they are unnecessarily cached?

I changed my scope.sh script to run
```bash
ln -s "${FILE_PATH}" "${IMAGE_CACHE_PATH}" && exit 6
```
instead of just running
```exit 7```

**Comment by toonn** [comment]
Oh, yeah, gotcha. That's what I was thinking of for scope.

We could have it depend on an env var for people who don't want this behavior. I could imagine the number of symlinks getting pretty big. Probably big enough to exhaust file nodes on most peoples' disks.
