### ISSUE TITLE
Can't not start ranger in alacritty

### ISSUE THREAD

**Issue by xiaolongGitHub1498** [ranger/ranger#1842]
#### Runtime Environment

- Operating system and version: macOS 10.14.6
- Terminal emulator and version:  iTerm Build 3.3.7, Alacritty Version 0.4.1
- Python version: 3.7.3
- Ranger version/commit: 1.9.3
- Locale: zh_CN.UTF-8

#### Current Behavior
when i use iterm2 to start ranger, it works, but it dosen't work in alacritty

in alacritty
![image](https://user-images.githubusercontent.com/26108004/74723831-2fcffd80-5276-11ea-91ef-59c260180fcc.png)

works in iterm2
![image](https://user-images.githubusercontent.com/26108004/74723893-5a21bb00-5276-11ea-9c9a-72b27f21062c.png)

#### Traceback

```
Traceback (most recent call last):
  File "/usr/local/bin/ranger", line 36, in <module>
    import ranger  # NOQA pylint: disable=import-self,wrong-import-position
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/__init__.py", line 62, in <module>
    from ranger.core.main import main  # NOQA pylint: disable=wrong-import-position
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/main.py", line 22, in <module>
    'Locale: {0}'.format('.'.join(str(s) for s in locale.getlocale())),
  File "/System/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/locale.py", line 587, in getlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/locale.py", line 495, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

```

**Comment by toonn** [comment]
`UTF-8` is not a valid locale. What's your output for `locale`?

**Comment by xiaolongGitHub1498** [comment]
@toonn `locale` is `zh_CN.UTF-8`

**Comment by toonn** [comment]
No, I'm asking for the full output of the `locale` command.

**Comment by xiaolongGitHub1498** [comment]
thanks, i fixed it,

**Comment by toonn** [comment]
Please share the solution here for other people who might run into the same problem later.

**Comment by xiaolongGitHub1498** [comment]
![image](https://user-images.githubusercontent.com/26108004/87403410-67f22700-c5ef-11ea-87cf-f92ba4cc0d7d.png)
I add this in alacritty.yml
