### ISSUE TITLE
Tmux title is changed when update_tmux_title is false but title is NOT changed when update_tmux_title is true

### ISSUE THREAD

**Issue by yang-ling** [ranger/ranger#1844]
#### Runtime Environment

- Operating system and version: Manjaro 19.0.0 Kyria
- Kernel: x86_64 Linux 5.5.2-1-MANJARO
- Shell: zsh 5.7.1
- DE: KDE 5.66.0 / Plasma 5.17.5
- WM: KWin
- Terminal emulator and version: Konsole 19.12.2
- Python version: 3.8.1
- Ranger version/commit: 1.9.3.4.gd8c363c9-1
- Locale:
  - LANG=en_US.UTF-8
  - LC_CTYPE="en_US.UTF-8"
  - LC_NUMERIC=zh_CN.UTF-8
  - LC_TIME=zh_CN.UTF-8
  - LC_COLLATE="en_US.UTF-8"
  - LC_MONETARY=zh_CN.UTF-8
  - LC_MESSAGES="en_US.UTF-8"
  - LC_PAPER=zh_CN.UTF-8
  - LC_NAME=zh_CN.UTF-8
  - LC_ADDRESS=zh_CN.UTF-8
  - LC_TELEPHONE=zh_CN.UTF-8
  - LC_MEASUREMENT=zh_CN.UTF-8
  - LC_IDENTIFICATION=zh_CN.UTF-8
  - LC_ALL=

#### Current Behavior

When I put `set update_tmux_title true` in `~/.config/ranger/rc.conf`, tmux title isn't updated.

When I put `set update_tmux_title false` in `~/.config/ranger/rc.conf`, tmux title is updated.

#### Expected Behavior
When `update_tmux_title` is `true`, update tmux title.

When `update_tmux_title` is `false`, do not update tmux title.

#### Context

It doesn't affect me much, but it is confusing me much at first.

#### Possible Solutions

Maybe rename `update_tmux_title` to `disable_update_tmux_title` ?

##### set update_tmux_title true

1. Put `set update_tmux_title true` in `~/.config/ranger/rc.conf`
2. Launch Terminal emulator.
3. Launch Tmux, or byobu (I use byobu)
4. Set tmux title, like "test". If you use byobu, press F8 and then input "test"
5. Run `ranger`
6. Tmux title isn't updated. It is still "test"
7. Press `q` to exit from ranger
8. Tmux title isn't updated. It is still "test"
9. Run other program, like `sleep 10`, the tmux title isn't updated.

##### set update_tmux_title false

1. Put `set update_tmux_title false` in `~/.config/ranger/rc.conf`
2. Launch Terminal emulator.
3. Launch Tmux, or byobu (I use byobu)
4. Set tmux title, like "test". If you use byobu, press F8 and then input "test"
5. Run `ranger`
6. Tmux title isn't updated. It is still "test"
7. Press `q` to exit from ranger
8. Tmux title changes to "python" from "test" at first, and after about 1 second or less, it changes to "zsh".
9. Run other program, like `sleep 10`, the tmux title changes to "sleep". After 10 seconds, it changes to "zsh" back.

**Comment by toonn** [comment]
Hmm, I don't see a problem with the code and I can't reproduce this.
What is your output for `tmux show-option -gw`?

**Comment by yang-ling** [comment]
@toonn Thanks for reply. Here is output of `tmux show-option -gw`

```
aggressive-resize on
allow-rename off
alternate-screen on
automatic-rename on
automatic-rename-format "#{?pane_in_mode,[tmux],#{pane_current_command}}#{?pane_dead,[dead],}"
clock-mode-colour magenta
clock-mode-style 24
main-pane-height 24
main-pane-width 80
mode-keys vi
mode-style fg=black,bg=magenta
monitor-activity on
monitor-bell on
monitor-silence 0
other-pane-height 0
other-pane-width 0
pane-active-border-style fg=red,bg=red
pane-base-index 0
pane-border-format "#{?pane_active,#[reverse],}#{pane_index}#[default] \"#{pane_title}\""
pane-border-status off
pane-border-style fg=magenta
remain-on-exit off
synchronize-panes off
window-active-style default
window-size smallest
window-style default
window-status-activity-style fg=black,bg=#e3e272,bright
window-status-bell-style reverse
window-status-current-format "#I:#W#{?window_flags,#{window_flags}, }"
window-status-current-style fg=black,bg=#e3e272,reverse
window-status-format "#I:#W#{?window_flags,#{window_flags}, }"
window-status-last-style default
window-status-separator " "
window-status-style fg=black,bg=#e3e272
wrap-search on
xterm-keys on
```

**Comment by yang-ling** [comment]
Just now I put `set-option -wg automatic-rename off` in my tmux config file,
and tmux window is never renamed no matter what the value of `update_tmux_title` in
ranger config is

This is what I want.

Thanks for help!

**Comment by toonn** [comment]
Ok, fwiw, the reason it wasn't changing the title when it's set to true is that renaming wasn't allowed. `allow-rename` is set to `off` in your settings.
The reason it *was* renaming when set to false is that `automatic-rename` is set to `on` which makes tmux try to automatically determine a good window name.
