### ISSUE TITLE
ranger/config/rifle.conf: trash using wrong directory

### ISSUE THREAD

**Issue by emberfade** [ranger/ranger#1848]
#### Context

https://github.com/ranger/ranger/blob/870435dd9bec311d0866eb4a801ff174366ed0a9/ranger/config/rifle.conf#L284

#### Possible Solutions

XDG_DATA_DIR should be XDG_DATA_HOME as is also specified in the man page of ranger.

The standard fallback if that environment variable is not defined is usually ``$HOME/.local/share``.  Ranger already uses ``$HOME/.local/share/ranger`` for data files. Wouldn't it be better to use that for the trash as well?

My suggestion would be:

```
diff --git a/ranger/config/rifle.conf b/ranger/config/rifle.conf
index 86f53fd1..60b4b22d 100644
--- a/ranger/config/rifle.conf
+++ b/ranger/config/rifle.conf
@@ -281,4 +281,4 @@ mime application/x-executable = "$1"

 # Move the file to trash using trash-cli.
 label trash, has trash-put = trash-put -- "$@"
-label trash = mkdir -p -- ${XDG_DATA_DIR:-$HOME/.ranger}/ranger-trash; mv -- "$@" ${XDG_DATA_DIR:-$HOME/.ranger}/ranger-trash
+label trash = mkdir -p -- ${XDG_DATA_HOME:-$HOME/.local/share}/ranger/trash; mv -- "$@" ${XDG_DATA_HOME:-$HOME/.local/share}/ranger/trash

```

**Comment by toonn** [comment]
This'd be a great PR 👍
