### ISSUE TITLE
w3m image preview damaged when file list scrolled down

### ISSUE THREAD

**Issue by tex** [ranger/ranger#185]
I'm using urxvt. There might be some connection to #86.
My problem is that when file list is scrolled down and it is image and it is to be previewed by w3m, the image is shown damaged.
The preview is ok if file list is not scrolled.
It looks like there might be problem in logic in ranger: the image is previewed before file list is scrolled.

**Comment by nfnty** [comment]
Are you still having this issue?

**Comment by tex** [comment]
Yes. I did update ranger and try image preview and image previews are still getting corrupted.

**Comment by nfnty** [comment]
Have you tried using `preview_images_method urxvt`?

**Comment by nfnty** [comment]
Continue discussion in #86.
