### ISSUE TITLE
Can't navigate under fish shell

### ISSUE THREAD

**Issue by sleeeeeeper** [ranger/ranger#1851]
I used `sudo -H pip3 install ranger-fm` to install my ranger in bash, and it worked all fine,navigation,selection,preview,all good.

But then I installed fish shell.When I switch to fish from bash, I can still get into ranger using `ranger`, but it doesn't respond to any of my operation. When I press `q` to quit and switch back to bash, it doesn't work either. But if I reopen the terminal, it works all fine in bash.

I'm confused.I

**Comment by sleeeeeeper** [comment]
Sorry, I  can navigate using arrow keys, but my `h,j,k,l` doesn't work like in bash.

**Comment by toonn** [comment]
Hmm, no idea why this happens tbh. Does the same happen with other shells? Like `sh` or `zsh`?

**Comment by sleeeeeeper** [comment]
Sorry, it magically worked fine like three days after I wrote this issue. I didn't know why and what I've done, but it works fine now. Thank you.
