### ISSUE TITLE
xdg-open unexpected option: '--'

### ISSUE THREAD

**Issue by jrwrigh** [ranger/ranger#1853]
#### Runtime Environment

- Operating system and version: Manjaro 18.1.5
- Terminal emulator and version: N/A
- Python version: python 3.8.1
- Ranger version/commit: ranger-master (see #1826)
- Locale: en_US.UTF-8 
- xdg-open version: 1.1.3+

#### Current Behavior
Attempting to open a `.yml` file from within ranger causes the error:

```
xdg-open: unexpected option '--'
Try 'xdg-open --help' for more information.
```

#### Expected Behavior
Either open the file, or trigger the `open_with` dialogue.

#### Possible Solutions
It's possible to add a rule to `rilfle.conf` to redirect `*.yml` files to the `$EDITOR`, but I think the more pressing issue is the actual use of `xdg-open --`.

The example of the [`rifle.conf` that just uses `xdg-open`](https://github.com/ranger/ranger/blob/325f41e6a841ab1413020b9d2d86c3922d90f407/examples/rifle_different_file_opener.conf) does not have the extra `--`. Any idea why this has been added in the default `rifle.conf`?

#### Steps to reproduce
1. Create `*.yml` file
2. Try to open inside ranger

**Comment by toonn** [comment]
Apologies, I only tested this on macOS.

**Comment by toonn** [comment]
Planned for this month™.

**Comment by UsersDoProgram** [comment]
Has anyone found the fix for this issue yet?

**Comment by toonn** [comment]
@UsersDoProgram, it *has* been fixed, just not released yet. You can simply edit `rifle.conf` to remove the `--` though. Just remember to remove `rifle.conf` again next release if you don't make any further changes, that way you don't have to worry about keeping it up to date.

**Comment by mizhozan** [comment]
@toonn Thanks for the explanation. However, I still need to keep the rifle.conf update bcz I just have some (not very common extensions) set up (e.g. xopp). Also sometimes priorities need to changes, etc. Is there a way to load default /usr level `rifle.config` and in the home config only add some new matching rules with higher priorities? 

I tested this and it seems when I use rifle.conf then that's it there is no precedence mechanism.

**Comment by toonn** [comment]
It's not possible because it's not all that useful. A very common change to `rifle.conf` is adding options that don't become the defaults. So you can access them using `r`. And that's very cumbersome if you can only add rules from one end. So we never bothered adding the functionality so as not to paint ourselves into a corner. I'm currently thinking the most useful design would be adding sentinel comments in between the various blocks in `rifle.conf` and then allow substituting those from a personal `rifle.conf`.

```
default rifle.conf:
mime ^text, has vim = vim -- "$@"

#alternative-editors

user rifle.conf:
#alternative-editors
mime ^text, has emacs = emacs -- "$@"

Rifle would behave as if the rifle.conf looked like this:
mime ^text, has vim = vim -- "$@"

mime ^text, has emacs = emacs -- "$@"
```

**Comment by mizhozan** [comment]
What about break the rifle.conf such that it first apply the home rules and then apply system rules. The benefit might be marginal but this is what I supposed according to your example:

 ```
default rifle.conf:
mime ^text, has vim = vim -- "$@"

user rifle.conf:
#alternative-editors
mime ^text, has emacs = emacs -- "$@"

Rifle would behave as if the rifle.conf looked like this:
mime ^text, has emacs = emacs -- "$@"
mime ^text, has vim = vim -- "$@"
```

I understand that this might be cumbersome, but this at least make user's maintenance more straight-forward across updates. The user config its home config and does not need to check if rifle.conf has been added new updates and handle merging the old and new each time.

**Comment by vifon** [comment]
Adding new rules at the end of rifle.conf is also a very valid use case. Or in the middle of it, for the matter. rifle.conf is flexible enough there is no good way to guess the user's intended order without them specifying it explicitly.

**Comment by JDeepD** [comment]
@toonn Is this fixed in version 1.9.3? I have the same issue in opening a file called `.tldrrc`. Its the only file that doesn't open through ranger.

**Comment by ccaneke** [comment]
This still happens on

```
ranger version: ranger 1.9.4
Python version: 3.13.2 (main, Feb  4 2025, 00:00:00) [GCC 14.2.1 20250110 (Red Hat
```

**Comment by toonn** [comment]
Maybe you have an old `rifle.conf`?
