### ISSUE TITLE
Crashes If opened as   sudo ranger

### ISSUE THREAD

**Issue by Tanish2002** [ranger/ranger#1855]
#### Runtime Environment

- Operating system and version: Bedrock Linux {Void+Arch}
- Terminal emulator and version: st{tmux} 0.8.2
- Python version: 3.8.1
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
Ranger does not open using `sudo ranger`

#### Expected Behavior
should open using `sudo ranger`
#### Context

I have done a fresh Installation of Bedrock Linux on top of void and added the arch strata,  The ranger package is from the Void Repo, Normal `ranger` command works

#### Traceback

`$ sudo ranger`

```
ranger version: ranger 1.9.3
Python version: 3.8.1 (default, Dec 23 2019, 13:11:45) [GCC 9.2.0]
Locale: en_US.UTF-8

Traceback (most recent call last):  File "/usr/lib/python3.8/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 132, in initialize
    self.ui.initialize()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 127, in initialize
    self.handle_multiplexer()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 499, in handle_multiplexer
    self._screen_title = check_output(
  File "/usr/lib/python3.8/site-packages/ranger/ext/spawn.py", line 35, in check_output
    process = Popen(popenargs, stderr=fd_devnull, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'screen'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by Vifon** [comment]
Is it possible that your `sudo` comes from a different distro than `ranger` and they don't work well together?

**Comment by Tanish2002** [comment]
> Is it possible that your `sudo` comes from a different distro than `ranger` and they don't work well together?

No It's not possible as I have also tried
`strat void sudo ranger`
and 
`strat arch sudo ranger`

The `strat <distro>` command used files/config from only the distro specified

**Comment by Tanish2002** [comment]
I fixed it the problem was that the `$TERM` variable was set to `screen-256colors` due to tmux.conf therefore after changing it the issue was fixed

**Comment by toonn** [comment]
#1852 should fix this.

**Comment by toonn** [comment]
Closing because that was merged.
