### ISSUE TITLE
Loader work process failed: compressing / extracting

### ISSUE THREAD

**Issue by p1k0pan** [ranger/ranger#1858]
#### Runtime Environment

- Operating system and version: Manjaro
- Terminal emulator and version: st
- ranger version: ranger-master
- Python version: 3.8.1 (default, Jan 22 2020, 06:38:00) [GCC 9.2.0]
- Locale: en_US.UTF-8

I have copied the compress / extract command from [archwiki](https://wiki.archlinux.org/index.php/ranger) into my `~/.config/ranger/command.py` .

Then bind my key in `rc.conf`:
`map C console compress%space`
`map E console extracthere%space`

When I try to use the two command , It return an same error:
`Loader work process failed: compressing the files in: a.zip (Percent: 0)`
`Loader word process failed : extracting files from: Downloads (Percent: 0)`

Pls help

**Comment by p1k0pan** [comment]
Maybe I could customize a command `unzip` on shell , but I m noob and got no idea how to do it.

**Comment by toonn** [comment]
Did you install `atool`?

**Comment by p1k0pan** [comment]
ye, sorry I have missed to install atool ,thank you @toonn
