### ISSUE TITLE
Slow image preview in iterm2

### ISSUE THREAD

**Issue by eralus** [ranger/ranger#1864]
#### Runtime Environment
- Operating system and version: macOS 10.15.3
- Terminal emulator and version: iterm2 3.3.9
- Python version: 2.7.6
- Ranger version/commit: 1.9.3
- Locale: None
- image_preview_method iterm2

#### Current Behavior

When previewing images, the imgcat script always takes a moment to load the image. Obviously, the bigger the file, the longer the delay. While the image is loading, the terminal is frozen and does not respond to input until the script is done.

#### Expected Behavior

While the image preview loads, one should still be able to control the cursor.

#### Context

Limiting the file size for file previews does not solve this issue, because even for small images (~70k) the delay is long enough to make scrolling through a long list of such images very laggy. 

#### Possible Solutions

Making the preview somehow run as a background process, so that the user does not lose control during the execution. Alternatively setting a short delay before the preview gets loaded, so that quick scrolling does not trigger the preview.

**Comment by toonn** [comment]
Only recourse for now is the `w3m_delay`.
Gonna close this as a duplicate because I'm sure there's open issues.
