### ISSUE TITLE
Ranger integration with presto works on "Release 317" but fails on versions later

### ISSUE THREAD

**Issue by har5havardhan** [ranger/ranger#1865]
Hi,

I am trying to integrate ranger with presto and its working on "Release 317" 
I followed the following documentation : [https://cwiki.apache.org/confluence/display/RANGER/Presto+Plugin](url) 

But, when when I go with versions after that, It throws the following errors.

query: SHOW CATALOGS
error : [65536] Query failed (#20200303_063413_00002_h5s89): Internal error java.lang.RuntimeException: java.lang.IllegalStateException

query:select * from hive.db_name.table_name limit 10
error:[4] Query failed (#20200303_063836_00000_x47vg): Access Denied: Cannot access catalog hive java.lang.RuntimeException: io.prestosql.spi.security.AccessDeniedException: Access Denied: Cannot access catalog hive

I've tried versions 318,319,323,329 and i am facing similar errors. How do I solve this ?

**Comment by toonn** [comment]
You're probably looking for the [Apache Ranger Bugtracker](https://issues.apache.org/jira/projects/RANGER/issues/RANGER-2532?filter=allopenissues).
