### ISSUE TITLE
BAT_STYLE environment variable clashes with bat

### ISSUE THREAD

**Issue by dmarcoux** [ranger/ranger#1866]
#### Runtime Environment
- Operating system and version: openSUSE Tumbleweed on snapshot 20200218
- Terminal emulator and version: Konsole 19.12.2
- Python version: 3.7.3
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
Whenever setting `BAT_STYLE` to one of the themes from `bat --list-themes` as described in the [documentation](https://github.com/ranger/ranger/blob/b032a10e487927e6a8b5f5340d9b76ebefa22a18/doc/ranger.1#L1873-L1876), `ranger` cannot preview files.

#### Expected Behavior
Be able to preview files.

#### Context
This issue is preventing me from setting a theme to use whenever previewing files with `bat` within `ranger`. 

#### Possible Solutions
Use another environment variable name, such as `BAT_THEME`, so it doesn't clash with `BAT_STYLE` from `bat`. `BAT_STYLE` is already used in `bat` as you can see in the documentation [here](https://github.com/sharkdp/bat/blob/20ba984c6d73e59cfeb315c1d17962a10fc64e9c/assets/manual/bat.1.in#L113-L121).

#### Steps to reproduce
1. Have `bat` and `ranger` installed.
2. Set the environment variable `BAT_STYLE` to `ansi-light` (or another theme from `bat --list-themes`)
3. Run `bat some_file.txt` and see the error `[bat error]: Unknown style 'ansi-light'`
4. In `ranger`, just try to preview a file and it won't work.
5. Running `unset BAT_STYLE` fixes both issues from steps 3 and 4.

**Comment by toonn** [comment]
Does bat handle specifying a `BAT_THEME` and passing `--style="plain"`?

**Comment by dmarcoux** [comment]
There is `BAT_THEME` and it does work with `--plain`, which is just a shortcut for `--style="plain"`. This environment variable is described upstream

So the documentation of `ranger` needs to be updated. Replacing `BAT_STYLE` by `BAT_THEME` should do it, right?

**Comment by toonn** [comment]
I think so, yeah.

**Comment by toonn** [comment]
Thanks for the contribution! 🎉 : )

**Comment by dmarcoux** [comment]
You're welcome and thank you for your quick reply yesterday.
