### ISSUE TITLE
Ranger preview image issure

### ISSUE THREAD

**Issue by XinYang-YXY** [ranger/ranger#1872]
Hi, I am using the terminology terminal emulator with ranger (version 1.8.1). Everything is working great except the image preview. It is unable to display image preview. Is there any solution to it? Thanks!

**Comment by toonn** [comment]
Version 1.8.1 is very old and doesn't support image previews in Terminology. Please update to version 1.9.3.

**Comment by XinYang-YXY** [comment]
Thanks, the issue solved after installing ranger using pip, install of the apt.
