### ISSUE TITLE
When compiling, the error message is too vague

### ISSUE THREAD

**Issue by projoy** [ranger/ranger#1875]
#### Runtime Environment

- Operating system and version: centos 7.6
- Terminal emulator and version: VIM 7.4.629
- Python version: 2.7
- Ranger version/commit: 2.0.0
- Locale: zh-CN

#### Current Behavior
When I compile it with <pre>mvn clean compile package assembly:assembly install</pre> there was some error:
<pre>
[INFO] ------------------------------------------------------------------------
[INFO] Building Ranger Util 2.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven-version) @ ranger-util ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-versions) @ ranger-util ---
[INFO] 
[INFO] --- maven-antrun-plugin:1.7:run (generate-version-annotation) @ ranger-util ---
[INFO] Executing tasks

main:
     [exec] Traceback (most recent call last):
     [exec]   File "/export/servers/ranger-2.0/ranger-util/src/scripts/saveVersion.py", line 154, in <module>
     [exec]     main()
     [exec]   File "/export/servers/ranger-2.0/ranger-util/src/scripts/saveVersion.py", line 72, in main
     [exec]     output = check_output(query)
     [exec]   File "/export/servers/ranger-2.0/ranger-util/src/scripts/saveVersion.py", line 41, in check_output
     [exec]     output = subprocess.check_output(query)
     [exec]   File "/usr/lib64/python2.7/subprocess.py", line 568, in check_output
     [exec]     process = Popen(stdout
     [exec] =PIPE, *popenargs, **kwargs)
     [exec]   File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
     [exec]     errread, errwrite)
     [exec]   File "/usr/lib64/python2.7/subprocess.py", line 1327, in _execute_child
     [exec]     raise child_exception
     [exec] OSError: [Errno 2] No such file or di
     [exec] rectory
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Skipping ranger

</pre>
At the beginning, I thought it was a problem with my python configuration, and then reconfigured python, it didn't work;
then I thought the python version being too low, so I rose it to python3.0, but it didn't work.
Finally, I looked at the source code of "ranger-util/src/scripts/saveVersion.py" and found that the git command was not installed. 

After installed git, the problem was solved
#### Expected Behavior
The except  in "saveVersion.py" is too vague, it looks list this: 
<pre>
def check_output(query):
         try:
                 output = subprocess.check_output(query)
                 return output.decode("UTF-8")
         except CalledProcessError:
                 # Not a git repository, or no git is installed
                 return ''

</pre>

I hope there is a clear prompt message，so it can tell what's happend in it. thank you

**Comment by toonn** [comment]
You're probably looking for the [Apache Ranger Bugtracker](https://issues.apache.org/jira/projects/RANGER/issues/RANGER-2532?filter=allopenissues).
