### ISSUE TITLE
Question: is it possible to filter by entire subpath?

### ISSUE THREAD

**Issue by peey** [ranger/ranger#1877]
I've looked through the man page, it seems that filter only looks at the names in the current directory

Suppose these files exist in current directory:
```
a/1.txt
a/2.txt
b/1.txt
b/2.txt
c/2.txt
```

If I filter by `1`, is it possible to filter the entire subtree by pattern `1`, so only folders `a` and `b` are shown in current directory and only the file `1.txt` is shown in both of them?

**Comment by toonn** [comment]
Hmm, not really possible. You can flatten the directory and then filter, that'll work.

Maybe one of the integrations or custom commands on the wiki can help you? They're for search rather than filter but maybe that's good enough?

**Comment by peey** [comment]
I haven't found a solution but closing this since it's not a issue

**Comment by toonn** [comment]
Flattening before filtering didn't help you?

**Comment by peey** [comment]
There are just too many files (and paths too long) to flatten. 

The filtered-filesystem view, as I described, would be pretty cool. I don't have a clue what integrations will work to achieve it.
