### ISSUE TITLE
Status bar should reflect active pane in multipane viewmode

### ISSUE THREAD

**Issue by politas** [ranger/ranger#1880]
#### Runtime Environment
- Operating system and version: Linux 5.4.18-1-MANJARO #1 SMP PREEMPT Thu Feb 6 11:41:30 UTC 2020 x86_64 GNU/Linux
- Terminal emulator and version: xfce4-terminal 0.8.9.1
- Python version: 3.8.1 (default, Jan 22 2020, 06:38:00) [GCC 9.2.0]
- Ranger version/commit: 1.9.3.4.gd8c363c9-1
- Locale: en_AU.UTF-8

#### Current Behavior

In multipane viewmode, the status bar always reflects the currently highlighted item in the first pane.

#### Expected Behavior

Status bar should reflect the currently highlighted item in the active pane

#### Steps to reproduce
1. Set viewmode to multipane
2. Open two or more panes
3. compare status when first pane is active to other panes

**Comment by politas** [comment]
Looks to me like https://github.com/ranger/ranger/blob/master/ranger/core/tab.py#L40-L44 on_tab_change() is the relevant code for this - we need to trigger a change of StatusBar.column to the column attached to the now active tab. I'm still working on figuring out how to do that. If anyone has any hints, please feel free to point me in the right direction.

**Comment by toonn** [comment]
Is this no longer an issue?

**Comment by toonn** [comment]
Ah, it didn't get closed before. Thanks!
