### ISSUE TITLE
Ranger freezes with "loading..." message if run from screen

### ISSUE THREAD

**Issue by pkrumins** [ranger/ranger#1883]
#### Runtime Environment

- Operating system and version: Debian 9.8
- Terminal emulator and version:  screen 4.05.00 ($TERM is `screen`)
- Python version: 3.5.3
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior

On my machine, when starting ranger from within `screen`, it freezes for about 5 seconds with a message "loading...". After that it loads. If I exit screen and start ranger, then it loads instantly.

#### Expected Behavior

Ranger starts instantly.

#### Context

Ranger startup.

#### Possible Solutions

Please let me know what other info you need from my machine to help you find a solution to this problem.

#### Steps to reproduce

1. Start screen.
2. Start ranger inside screen.
3. Ranger freezes for 5 seconds with "loading..." message.

**Comment by toonn** [comment]
Could you try the master branch? Just clone and run `./ranger.py` from the repo.
Try running ranger with a different python version, 3.5 had problems.
Try running `ranger --clean` to make sure the problem's not your personal config.

**Comment by hssathya** [comment]
i do have similar issue. it displays loading... for almost 20-30 seconds.
i have installed it from master branch, since i don't have permission to root, i installed as below
./setup.py install --user

**Comment by toonn** [comment]
@hssathya, only when starting from inside `screen`?

**Comment by hssathya** [comment]
No, even if I start it outside the screen, I see similar issue

**Comment by toonn** [comment]
Then it sounds like an unrelated issue. Please find a more appropriate one or open one if need be.

**Comment by bergercookie** [comment]
I have the same issue but when running `ranger` inside `tmux`.

**Comment by pkrumins** [comment]
It's fixed now.
