### ISSUE TITLE
git VCS folders misaligned columns

### ISSUE THREAD

**Issue by katawful** [ranger/ranger#1889]
#### Runtime Environment

- Operating system and version: Arch Linux
- Terminal emulator and version: kitty v0.16.0-2
- Python version: 3.8.2-1
- Ranger version/commit: 1.9.3-1
- Locale: en-US.UTF-8

#### Current Behavior

When in a git VCS managed folder, the columns misalign and eventually fall apart entirely whenever a git VCS tag appears:
https://i.redd.it/is4xq0ab79o41.png

#### Expected Behavior

I expect that this doesn't happen

#### Context

I switched from konsole to kitty recently and this issue appeared

#### Possible Solutions

None that I found

#### Steps to reproduce
1. Run ranger through kitty
2. Have a VCS managed folder and use git as the backend

**Comment by toonn** [comment]
And you're sure this never happened with konsole? Or did you not use that with the VCS integration?

**Comment by katawful** [comment]
I just checked cause I don't remember, and it doesn't but it seems like there's a font issue. Konsole doesn't appear to have the right fonts for what appears to be for untracked folders. It displays a question mark glyph (is this appropriate behavior?)  In kitty, tracked folders either have a modified marker (+) or a blank space, while the untracked folders have nothing which makes me wonder if I have the right fonts at all. The untracked folder border lines up in the same spot in Konsole and kitty but the tracked folder symbols seem to push the border over some.
What fonts are required for these symbols? Both terminals are using Meslo LGS NF as the main font.
![ Konsole on right, kitty on left](https://user-images.githubusercontent.com/45222045/77353296-17408080-6d17-11ea-8cca-5edde8e20c9f.png)

**Comment by toonn** [comment]
Actually, could you check if PR #1882 fixes this for you? Maybe the glyph-width calculations are just off. Otoh, it could also be we need to handle the difference in width of the various symbols better.

**Comment by katawful** [comment]
That didn't seem to do anything for me, both terminals act the same as before

**Comment by toonn** [comment]
Ok, thanks, that narrows it down.

**Comment by katawful** [comment]
I tried ranger with urxvt, st, and xterm and beside xterm not rendering anything properly, they all seemed to not have the issue I'm having with kitty. Its probably a kitty problem so I'm gonna close this and ask that team

**Comment by toonn** [comment]
Be sure to link the issue here. Might still be a problem on our side. I think kitty's stricter with font widths. Oh hold on. Maybe the problem is you're not using a proper monospace font?

**Comment by katawful** [comment]
I'm using MesloLGS NF which is monospace, but I also just tried it with xos4 terminus with no change in appearance

**Comment by toonn** [comment]
Many so-called "monospace" fonts actually lie about really being monospace though. I haven't had issues with `DejaVu Sans Mono` so far, can you reproduce the issue with that font?

**Comment by katawful** [comment]
That font reproduced the issue

**Comment by katawful** [comment]
Ok so it turns out my locale was never set up properly, I ended up forcing it in zsh and the issue no longer appears. I'm not sure why it never got set up but the problem was entirely on my end

**Comment by ahmadie** [comment]
could you kindly tell us what changes you did to locale to solve the problem?
