### ISSUE TITLE
Support for extensions

### ISSUE THREAD

**Issue by notEvil** [ranger/ranger#189]
Hi,

first of all thanks a lot for your great work on ranger. I just found it by chance and liked it from the start.
There is just one question: do you plan to implement support for extensions. I would really love to see this project grow with its users, just as vim did and does.

My current wishes:
- traverse archives as if they were directories
- search the history

last but not least, I used mbreese's swalign to add item ordering and filtering using Smith Waterman score; all inside the users' command.py :)  see attached (hopefully)

https://www.dropbox.com/sh/2adceq6eu6vjimn/AACI_TvPDaPwH0CXXnSGua0ia?dl=0

**Comment by a13ph** [comment]
> traverse archives as if they were directories

https://github.com/ranger/ranger/issues/456

**Comment by nfnty** [comment]
Please, split this issue into multiple issues if you want to have these functionalities added to ranger.

Add your custom plugins to [Wiki - Community plugins](https://github.com/ranger/ranger/wiki/Community-plugins).
