### ISSUE TITLE
Kitty image preview

### ISSUE THREAD

**Issue by michalens** [ranger/ranger#1894]
Image preview in kitty doesn't work on MacOS.
I have this error:
`Image previews in kitty require PIL (pillow)`

I did set `preview_images true` and `set preview_images_method kitty`.
My `$TERM` is `xterm-kitty`

I also installed Pillow with
`python3 -m pip install --upgrade Pillow`

My `which python` is `/usr/bin/python`, so I don't need to change anything in `ranger.py` (as was suggested in another issue. If I change it to `#!/usr/local/bin/python -O`, ranger doesn't open up)
And I have imagemagick installed.

**Comment by toonn** [comment]
`/usr/bin/python` is probably a python 2.7 which means you didn't install pillow for the right python.

**Comment by michalens** [comment]
> `/usr/bin/python` is probably a python 2.7 which means you didn't install pillow for the right python.

Yes, here's what i have
```
$ python --version
Python 2.7.10
```
So how do I fix it?

**Comment by michalens** [comment]
**Solution:**

Install pip for Python 2.7:
```
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
python get-pip.py
```
Install Pillow for Python 2.7:
```
python -m pip install --upgrade Pillow
```
Works like charm.

**Comment by toonn** [comment]
@michalens, another alternative would be to install ranger using pip, `pip install ranger-fm pillow` would make sure that whatever python pillow is installed for, that's the one ranger would use.
