### ISSUE TITLE
only preview img less than 100K

### ISSUE THREAD

**Issue by zdmgmail** [ranger/ranger#1900]
I use the preview method,  w3m, only images smaller than 100K are previewed. 

Google did not find this problem, is there a solution?

```
~/Pictures/screenshots » uname -a                                                        zdm@ar
Linux ar 5.5.13-arch2-1 #1 SMP PREEMPT Mon, 30 Mar 2020 20:42:41 +0000 x86_64 GNU/Linux
------------------------------------------------------------------------------------------------
~/Pictures/screenshots » ranger --version                                                zdm@ar
ranger version: ranger 1.9.3
Python version: 3.8.2 (default, Feb 26 2020, 22:21:03) [GCC 9.2.1 20200130]
Locale: en_US.UTF-8
------------------------------------------------------------------------------------------------
~/Pictures/screenshots » w3m -version                                                    zdm@ar
w3m version w3m/0.5.3+git20190105, options lang=en,m17n,image,color,ansi-color,mouse,gpm,menu,cookie,ssl,ssl-verify,external-uri-loader,nntp,ipv6,alarm,mark

```

**Comment by toonn** [comment]
Hmm, are you running in screen or tmux?

**Comment by zdmgmail** [comment]
> Hmm, are you running in screen or tmux? Do you have `preview_max_size` set?

I use tmux, but ~/.tmux.conf no set preview_view_max_size

When I detach the client, still only preview less than 100K

**Comment by toonn** [comment]
It's not a tmux setting it's a ranger setting.

When you say detach do you mean you ran ranger outside of tmux?

**Comment by zdmgmail** [comment]
> It's not a tmux setting it's a ranger setting.
> 
> When you say detach do you mean you ran ranger outside of tmux?

Thanks , preview_max_size was 102400, change then  soloved
