### ISSUE TITLE
vim plugin is very inefficient

### ISSUE THREAD

**Issue by aranmohyeddin** [ranger/ranger#1904]
[this](https://github.com/ranger/ranger/blob/master/examples/vim_file_chooser.vim) plugin is very inefficient. When I open a ranger file chooser or choose a file and open it with it my fan starts working hard and there is too much delay given the simplicity of the task.

**Comment by toonn** [comment]
Improvements would be more than welcome but this is not considered a bug.

**Comment by mik13ST** [comment]
I think I was experiencing similar issues when using Ranger as a Vim file picker although using a [third party plugin](francoiscabrol/ranger.vim) (I was not aware of the Vim script in examples).

I am quite sure this is tied to the synchronous VCS thread wait described in #1841 and #902. Although this problem manifests itself when opening a file _or_ quitting.

@aranmohyeddin Could you test if your issue persists if you `set vcs_aware=False`?

**Comment by aranmohyeddin** [comment]
I don't think that makes a difference. I still have 2 seconds of delay when openning ranger from within vim.

**Comment by kevinhwang91** [comment]
If you use neovim, you can try the plugin I wrote.  https://github.com/kevinhwang91/rnvimr
