### ISSUE TITLE
space to choose and j to the bottom then something wrong

### ISSUE THREAD

**Issue by Augists-ZDCZ** [ranger/ranger#1920]
#### Runtime Environment

- Operating system and version: macOS 10.15.4
- Terminal emulator and version: Terminal 2.10
- Python version: 2.7.16(default on mac), 3.8.1(installed)
- Ranger version/commit: 1.9.3
- Locale: None, None

#### Current Behavior

I use <space> to select on some files and use j to jump over one, then I reach the bottom. At that time, something went wrong! I can't do anything except command-q to quit my Terminal!

I try to reproduce it, and only to find that it need not reach the bottom. Just space to choose and j, a few seconds later, it happens. 

Either command-q or ctrl-c stops it

**Comment by toonn** [comment]
I can't reproduce this. Does it happen when you run `ranger --clean`?

**Comment by Augists-ZDCZ** [comment]
No, I didn't run ranger --clean :)
Just daily use
But I can't reproduce it today ^_^
I'll reopen this issue as soon as it happens again
Thanks

**Comment by Augists-ZDCZ** [comment]
Yes, it happens again^_^
But I don't know why it is, really sorry
It seems like ... occasionally?
I will remove ranger and re-install it
Before reinstalling
make u known
There may be something wrong
Thanks

**Comment by toonn** [comment]
This is still not actionable so I'm gonna close it again. Please only reopen if there's a consistent way to trigger it. I suspect ranger's just busy generating a preview that takes a while though. If it happens again try pressing `ctrl-C`, that should cancel the preview task.
