### ISSUE TITLE
install in my home directory

### ISSUE THREAD

**Issue by hssathya** [ranger/ranger#1922]
#### Current Behavior
Currently running make install, installs in / directory. 

#### Expected Behavior
We don't have access to root directory, Is it possible to install to our home directory, my modifying PREFIX in Makefile?

**Comment by Vifon** [comment]
You can run `./setup.py install --prefix=…` directly. The Makefile is just for some additional convenience. You may need to modify your `PYTHONPATH`. Consider using `./setup.py install --user` instead, it might fit your needs better.

**Comment by toonn** [comment]
We support passing of a prefix using the `PREFIX` environment variable. But that's for the docs and the location of the script that should be on the `PATH`. So you might want to specify `DESTDIR` instead, which defaults to `/`.

**Comment by hssathya** [comment]
yes, i'm able to install with ./setup.py install --user, but when i start ranger, it takes almost 20-30 seconds. It displays loading... for 20-30 seconds

**Comment by toonn** [comment]
Your home directory isn't hosted on a slow NFS share or something, is it?
