### ISSUE TITLE
setlocal for filter_stack command

### ISSUE THREAD

**Issue by aasril** [ranger/ranger#1923]
#### Runtime Environment

- Operating system and version: Ubuntu 20.04
- Terminal emulator and version: st 0.8.2
- Python version: 3.8.2
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

I have a directory with a bunch of video and subtitle files inside. I can run a filter to show only the videos with `:filter_stack add mime video`. What I want to do is to set this filter on `rc.conf`, something like `setlocal path=/path_of/the_videos filter_stack add mime video` since I never touch the subtitle files anyway.

That command gave `the option named filter_stack does not exist` error. Is it possible to do this, and how?

**Comment by toonn** [comment]
Hmm, you could try the older style of filters. I'm not sure you can set any filters from `rc.conf` though.

@Vifon, maybe you know of a way?

**Comment by aasril** [comment]
How would I use the the older style of filters? I read the man but couldn't figured out. For now, I quite satisfied with chaining `cd` and `filter_stack` command above.

**Comment by aasril** [comment]
In nautilus I've done it the other way around by occasionally running `ls *.vtt > .hidden`. Nautilus respect the `.hidden` file and hide those subtitle.

Regarding the vtt files, I can't filter them by using mime. `mimetype` command tells it's a `text/vtt` and `file --mime-type` tells it's a `text/plain`. But filtering by using `[text|vtt|plain]` none of them works.

**Comment by toonn** [comment]
The old filter command is bound to `zf`, it's a scout invocation.

Hmm, `.m vtt<CR>.!` should work afaict.

Cool to hear people are using the filter stack btw! 🚀

**Comment by aasril** [comment]
Unfortunately `filter` also doesn't work with `setlocal`. 

Though using `:filter vtt` works! While `:filter_stack add mime vtt` doesn't. That's something I can use (albeit without `.!` to reverse the filter)

Yep, I can imagine how very useful filter stack would be in some scenarios.

I think I'm good for now. Should I close the issue?

**Comment by toonn** [comment]
Hmm, actually, when I run `mimetypes.guess_type('sample.vtt')` I get `(None, None)`. So looks like the mimetypes library doesn't identify it properly?
