### ISSUE TITLE
Image preview for bash terminal

### ISSUE THREAD

**Issue by strogiyotec** [ranger/ranger#1928]
Good day, thank you for this adorable file manager.
I have a problem with image preview in bash terminal.
I didn't find instruction for bash in wiki (https://github.com/ranger/ranger/wiki/Image-Previews). 
My OS is Ubuntu 18.04, w3m is installed. image preview works if I open ranger within xterm, however image preview doesn't work within simple bash , is it possible to configure bash for it or bash is not supported ? 
Ranger version
```
ranger version: ranger 1.9.3
Python version: 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
Locale: en_US.UTF-8

```

**Comment by strogiyotec** [comment]
I'm sorry, I found this thread
https://github.com/ranger/ranger/issues/1736
It works for me  with ueberzug

**Comment by toonn** [comment]
Fyi, bash is not a terminal, it's a shell. Shells don't have any image viewing capabilities. Some terminals do. The w3m preview method only works with XTerm and any terminal that emulates XTerm sufficiently well (not many do). Ueberzug should work with any terminal as long as you're running X11. The terminal specific methods should be preferred if possible, Terminology, Kitty, iTerm2 and urxvt all have specific methods.
