### ISSUE TITLE
flooding in the central column

### ISSUE THREAD

**Issue by ev1313** [ranger/ranger#194]
This happens, when using ranger on my system:

![ranger1](https://cloud.githubusercontent.com/assets/3684655/5365014/a7552b48-7fe8-11e4-9118-6500b0939937.png)

I'm using terminology and zsh (with oh-my-zsh) on Fedora 21.

**Comment by nfnty** [comment]
Can't reproduce this issue. Request to reopen if you're still experiencing this issue on `master` or the latest release.
