### ISSUE TITLE
can't preview image and pdf 

### ISSUE THREAD

**Issue by sleeeeeeper** [ranger/ranger#1940]
manjaro kde kconsole fish-shell 

I use `sudo -H pip install ranger-fm` and `sudo -H pip install ueberzug` to install ranger and ueberzug, and it can't preview image and pdf

**Comment by toonn** [comment]
You're running X11, right?
And did you change the settings?
```
# rc.conf
set preview_images_method ueberzug
set preview_images true
```

And if you want pdf previews rendered to images:
```
$ ranger --copy-config=scope
# Uncomment the following section in scope.sh
## PDF
# application/pdf)#     pdftoppm -f 1 -l 1 \
#              -scale-to-x "${DEFAULT_SIZE%x*}" \
#              -scale-to-y -1 \
#              -singlefile \
#              -jpeg -tiffcompression jpeg \
#              -- "${FILE_PATH}" "${IMAGE_CACHE_PATH%.*}" \
#         && exit 6 || exit 1;;
```

**Comment by sleeeeeeper** [comment]
Yes, I've done what you mentioned above. And it didn't work until I reboot my machine.
Still don't know why. But it's working now.
