### ISSUE TITLE
Copy absolute path of selected file

### ISSUE THREAD

**Issue by TornaxO7** [ranger/ranger#1941]
Hello! I've a little question (I hope that I can use github issues to ask my question):
I'd like to add a shortcut to copy the absolute path of the current selected directory/file into my clipboard.
I'm using 
```
map P shell printf "$(pwd)" | xclip -selection clipboard
```
at this moment, but it copies only the path to the local directory. Do you have any ideas how I can copy the absolute path of the selected file/directory into my clipboard?

I've tried this
```
map P eval fm.open_console(fm.thisfile.absolute_path("%")) | xclip -selection clipboard
```
but it's obviously not working. (it was just an idea xD)

**Comment by toonn** [comment]
`yp` is already bound to `:yank path`. Have a nice day! 👍

**Comment by TornaxO7** [comment]
Awesome! Thank you :D
