### ISSUE TITLE
Consult a few questions about key binding, please help me

### ISSUE THREAD

**Issue by yyy33** [ranger/ranger#1945]
#### Runtime Environment

- Operating system and version: Linux x550vc-yyy 5.6.4-arch1-1 #1 SMP PREEMPT Mon, 13 Apr 2020 12:21:19 +0000 x86_64 GNU/Linux
- Terminal emulator and version: XTerm(353)
- Python version: Python version: 3.8.2 (default, Apr  8 2020, 14:31:25) [GCC 9.3.0]
- Ranger version/commit: ranger version: ranger 1.9.3
- Locale: Locale: en_US.UTF-8

#### Current Behavior
- I added the following two lines in `/home/yyy/.config/ranger/rc.conf`, but when I press `ctrl-m`, his behavior does clear the character in front of the cursor

````
cmap <c-j>  eval fm.ui.console.delete_rest(-1)
cmap <c-m>  eval fm.ui.console.execute()
````

-  How do I bind `= +  number` change permissions instead of the default `number + = `change permissions

- How to bind `ut` to remove all tags from the current folder instead of removing the tags from the current cursor by default

#### Expected Behavior
`ctrl-m` should execute the command

#### Possible Solutions
I ran `ranger --debug` and everything worked

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```

```

**Comment by toonn** [comment]
Not sure what you're referring to with the `ctrl-m`, `^M` is the control character for carriage return, so those functions are tied together. In the console it executes the command you typed, in the file browser it opens the file with rifle or enters the dir.

The key bindings with `=` rely on the numeric prefix quantifier, much like the behavior in vim `6j` so that's not as easily possible. You could use the any macros but you'd have to figure out a way to not pass all three numbers. `map =<any1><any2><any3> chmod %any1%any2%any3`
Maybe `map = console chmod%space` is what you're actually looking for, or the various `+uw/-or` key bindings?

Something like `map ut chain mark_files all=True val=True; chain tag_remove; mark_files all=True val=False` should do. Has side-effects like clearing your selection though and you can't pass a character to `tag_remove`. I'll leave those as exercises to the reader.

**Comment by yyy33** [comment]
> Not sure what you're referring to with the `ctrl-m`, `^M` is the control character for carriage return, so those functions are tied together. In the console it executes the command you typed, in the file browser it opens the file with rifle or enters the dir.
> 
> The key bindings with `=` rely on the numeric prefix quantifier, much like the behavior in vim `6j` so that's not as easily possible. You could use the any macros but you'd have to figure out a way to not pass all three numbers. `map =<any1><any2><any3> chmod %any1%any2%any3`
> Maybe `map = console chmod%space` is what you're actually looking for, or the various `+uw/-or` key bindings?
> 
> Something like `map ut chain mark_files all=True val=True; chain tag_remove; mark_files all=True val=False` should do. Has side-effects like clearing your selection though and you can't pass a character to `tag_remove`. I'll leave those as exercises to the reader.

- On the first question, what I meant was that when I added the following line to rc.conf, I pressed ^M in the console and it changed to delete all the text after the current cursor instead of executing the command

````
cmap <c-j>  eval fm.ui.console.delete_rest(-1)
````

- The second problem was solved

The third problem is that I think I'm overdoing it because I've just discovered that `tag_toggle` and `tag_remove `can be used in conjunction with `mark`

**Comment by toonn** [comment]
Re the first, are you saying `<c-m>` is triggering `<c-j>`?
Re the third, yeah usually I'd probably do `v``ut`.

**Comment by yyy33** [comment]
> Re the first, are you saying `<c-m>` is triggering `<c-j>`?
> Re the third, yeah usually I'd probably do `` v``ut ``.

Yes, I just want to map `<c-j>`, why is the behavior of `c-m` also changed

**Comment by toonn** [comment]
Oh, probably because of this line in your `rc.conf`: `copycmap <CR>  <C-j>`. It makes `C-j` behave the same as `CR` and `C-m` is the same thing as `CR`.

**Comment by yyy33** [comment]
> Oh, probably because of this line in your `rc.conf`: `copycmap <CR> <C-j>`. It makes `C-j` behave the same as `CR` and `C-m` is the same thing as `CR`.
> 
> That does seem strange though. If you're changing `C-j`, it shouldn't affect `CR` but the other way around.

I tried to comment the line you said, the single result is still the same
I also tried to replace other shells and terminals, but the results were not satisfactory
I don't know if other people have this problem

**Comment by toonn** [comment]
Ok, looked into this more. `C-j` is equivalent to the LF/line feed character. `C-m` is equivalent to CR/carriage return. The meaning of both is close and I assume curses interprets them the same way. (We use cbreak mode, not raw mode.)

So there's no way to assign separate bindings to those atm.

**Comment by toonn** [comment]
You *can* disable this behavior by calling `curses.nonl()`. And if I add this to the initialize function in `ranger/gui/ui.py` I can indeed bind `C-j` and `C-m` separately.

**Comment by yyy33** [comment]
> You _can_ disable this behavior by calling `curses.nonl()`. And if I add this to the initialize function in `ranger/gui/ui.py` I can indeed bind `C-j` and `C-m` separately.

Oh , it ' s working . Thanks！
