### ISSUE TITLE
Memory leak. Ranger takes all my RAM

### ISSUE THREAD

**Issue by ThePonyCoder** [ranger/ranger#1946]
#### Runtime Environment

- Operating system and version: NixOS 20.03
- Terminal emulator and version: kitty 0.16.0 
- Python version: 3.7.6 
- Ranger version/commit: 1.9.3 
- Locale: en_US.UTF-8

#### Current Behavior
When trying to preview djvu file ranger uses all of my memory
Maybe memory leak
I don't know, maybe it is problem in only this file

#### Expected Behavior
Don't preview/raise exeption

#### Steps to reproduce
1. Download this djvu file https://dropmefiles.com/qaa3V
2. Try to preview it with ranger

#### Traceback
no traceback

**Comment by toonn** [comment]
Does `djvutxt` work fine on the file? Or, if you don't have that installed, `exiftool`?

**Comment by firmart** [comment]
Try the solution depicted here #1815

**Comment by toonn** [comment]
Oh, thanks for noticing the similarity, firmart.

**Comment by ThePonyCoder** [comment]
I found fix. I've added this to `scope.sh` to function `handle_image():`
```
## DjVu
image/vnd.djvu)
    exit 0;;
```

**Comment by ThePonyCoder** [comment]
I found fix. I've added this to `scope.sh` to function `handle_image():`
```
## DjVu
image/vnd.djvu)
    exit 0;;
```
