### ISSUE TITLE
Modify the default file opening method

### ISSUE THREAD

**Issue by MrVBian** [ranger/ranger#1957]
I opened the file in the default ranger nano, but I hope to open the default mode is vim, what should I do.
Thank you very much for your help.

**Comment by toonn** [comment]
This isn't default behavior in ranger so either `VISUAL` or `EDITOR` is set to "nano" in your shell. If you either unset both or set `VISUAL=vim` ranger will use vim. (Setting `EDITOR` to vim is incorrect but many programs (including systemctl at one point) don't use the variables correctly so you might still want to do that.)
