### ISSUE TITLE
CPU running real high

### ISSUE THREAD

**Issue by communistkiro** [ranger/ranger#1959]
#### Runtime Environment
- Operating system and version: void linux
- Terminal emulator and version: st
- ranger version: ranger 1.9.3
- Python version: 3.8.2 (default, Mar 24 2020, 03:08:36) [GCC 9.3.0]
- Locale: en_US.UTF-8
- CPU: Intel i7-2620M (4) @ 3.4GHz

#### Current Behavior
With the last or next to-to-last update, CPU goes up significantly whilst ranger's merely open- it's not like there's anything major happening file-wise, to say intense monitoring or caching are going on.

[Here](https://www50.zippyshare.com/v/vq8eNkzn/file.html)'s a screenshot. edit- qbitt's dling to an external drive, and the behavior is the same with it closed.

#### Expected Behavior
In the past, I'd kept it running overnight wo/ fan going VRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR.

#### Possible Solutions
..?

#### Steps to reproduce
1. Open ranger.
2. 
3. 

I'll provide any relevant further info.

**Comment by toonn** [comment]
Do you have VCS integration turned on?

We did add some previews, are any preview tasks running? Check the task view.

**Comment by communistkiro** [comment]
Hm, I did indeed turn it recently on. 

Stranger yet - I'm looking at it open now, with normal CPU activity - (1--3 *) 0.7% every handful of seconds. -- `ranger --clean` is the exact same. Now reopening it a few times, and even turning off all previews-, it's hover at the 37% that were in the scrot beforehand.. `--clean` is low; turning on vcs with my config is ~5--6%.

I usually have file and directory previews on, but at the time there were no tasks in the tasks window- I wasn't scrolling down like a madman on any and all dirs.

Perhaps, and I don't know if this is a problem, or that I just shouldn't have it on- a possibility of toggling vcs once it's already open?

**Comment by toonn** [comment]
#192 or other PRs should fix the VCS issues. I'm not sure where these issues are coming from tbh, maybe preview processes that don't get killed properly?

**Comment by communistkiro** [comment]
Hm, I've never managed to get the imageviewer working, hence it's off. Mostly I diddled with ueberzug and farbfeld, but gave up, given it's mostly a nicety.

**Comment by toonn** [comment]
There's many textual preview processes that could be going haywire too though.

**Comment by communistkiro** [comment]
I set `vcs` to `true` again, and with `set use_preview_script ` false or true, it's at 40%; turning off all previews from within the program, does naught. I'm guessing it not the previews bogging it down. One perhaps important thing, CPU goes back to normal if not in a dir with a git repo.

**Comment by toonn** [comment]
Let's hope the VCS improvements fix it.

**Comment by mik13ST** [comment]
I believe this is a VCS problem. I believe this is exactly what I call "VCS problem No.2" (described in https://github.com/ranger/ranger/issues/902#issuecomment-630465258).

@communistkiro Can you confirm my description in https://github.com/ranger/ranger/issues/902#issuecomment-630465258 aligns with your issue? Can you quit ranger while the CPU load is high? Can you open a file while the CPU load is high? Does it calm down eventually (e.g. after 5 minutes)?

**Comment by communistkiro** [comment]
@mik13ST 
with `set vcs_aware true` I can _preview_ files that are both from and not from the repo. Both seemingly instantaneous.

**Comment by mik13ST** [comment]
Preview has nothing to do with this. By "open a file" I mean the `:edit` command. If you cannot do that, the `:shell $SHELL` (bound to the `shift + s` key combination by default) works too. Either way, `:quit` also works.

Running any of these commands while the CPU load is high and after the VCS marks appear, should make ranger halt for a couple of seconds. Is that the case?

**Comment by communistkiro** [comment]
I use sublime 3 as an editor, if it matters; it seems instantaneous with either right cursor key, i.e., opening it, or the `:edit` cmd. Unless subl's also opening a previously open project/workspace, it's no slower than usual.

**Comment by mik13ST** [comment]
I just checked, it doesn't matter whether the file is opened in a graphical application or terminal, the delay is the same. This means it's not the issue No.2 I though it was.

Anyways, if you want your issue solved, create a reproducible test case. It would be best to start in a clean environment, e.g. a virtual machine and see what exactly has to be to reproduce this issue.

**Comment by communistkiro** [comment]
Too much work on my part. Though I'm not helping the devs, if they can't reproduce it. It's bogged even if `.git` is renamed, so long as vcs is true and git is enabled, I don't want to give more itme.

**Comment by communistkiro** [comment]
Ah, got it. My main repo is a collection of my config files, scripts, etc., and since git doesn't allow relative files, I made my home dir my repo to have everything in the same place. A homedir is fucking huge, compared to <100 kb-sized text files. 
I still have no fucking idea how to make `.gitignore` work  properly.

But the thing I hadn't tried before was to rename the main .git, the one in the home dir. CPU went down to 4-5% afterwords.

So, imma close this issue, and continue hating on git.

**Comment by toonn** [comment]
@communistkiro, what I do is put symlinks in `$HOME` pointing into my dotfiles repo.
