### ISSUE TITLE
Ask questions about map

### ISSUE THREAD

**Issue by yyy33** [ranger/ranger#1960]
#### Runtime Environment

- Operating system and version: Linux x550vc-yyy 5.6.4-arch1-1 #1 SMP PREEMPT Mon, 13 Apr 2020 12:21:19 +0000 x86_64 GNU/Linux

- Terminal emulator and version: XTerm(353)
- Python version: Python version: 3.8.2 (default, Apr  8 2020, 14:31:25) [GCC 9.3.0]
- Ranger version/commit: ranger version: ranger 1.9.3
- Locale: Locale: en_US.UTF-8

#### Current Behavior
map <c-h> tab_new

#### Expected Behavior
The behavior of `c-h` is still the default behavior: hidden files

#### Possible Solutions
I use `? -k`  look at the key binding and see that it has been successfully bound

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```

```

**Comment by toonn** [comment]
C-h sends the same control character as backspace, so try mapping that.

**Comment by yyy33** [comment]
> C-h sends the same control character as backspace, so try mapping that.

Great! One more question.I use `fzf` and `fasd` with `ranger`,this line I want to change to use rifle to open the file directly instead of selecting the file,but I don't understand python,  please help me

````
self.fm.select_file(fzf_file)
````

-  __This is the entire script file__

````python
import os
from ranger.api.commands import Command
import ranger.api



try: from shlex import quote
except ImportError: from pipes import quote

old_hook_init = ranger.api.hook_init

def hook_init(fm):
    def fasd_add():
        fm.execute_console("shell fasd --add " + quote(fm.thisfile.path))
    fm.signal_bind('execute.before', fasd_add)
    return old_hook_init(fm)

ranger.api.hook_init = hook_init



class fasd_fzf(Command):
    def execute(self):
        import subprocess
        if self.quantifier:
            command="fasd | fzf --bind=alt-e:replace-query,ctrl-a:select-all,ctrl-r:toggle-all,ctrl-i:toggle+down,ctrl-p:toggle+up,alt-h:backward-char,alt-j:down,alt-k:up,alt-l:forward-char,alt-b:backward-word,alt-w:forward-word,alt-i:beginning-of-line,alt-a:end-of-line,ctrl-f:page-down,ctrl-b:page-up,ctrl-d:half-page-down,ctrl-u:half-page-up,alt-g:top,ctrl-h:backward-delete-char,bspace:backward-delete-char,ctrl-l:delete-char,ctrl-e:kill-word,ctrl-w:backward-kill-word,ctrl-j:unix-line-discard,ctrl-o:abort,ctrl-m:accept,enter:accept,alt-y:yank --marker=m -e --exit-0  --preview 'ccat <<< {}' --preview-window up:3:wrap +m --keep-right --tac --no-sort | awk '{ print substr($0, index($0,$2)) }'"
        else:
            command="fasd | fzf --bind=alt-e:replace-query,ctrl-a:select-all,ctrl-r:toggle-all,ctrl-i:toggle+down,ctrl-p:toggle+up,alt-h:backward-char,alt-j:down,alt-k:up,alt-l:forward-char,alt-b:backward-word,alt-w:forward-word,alt-i:beginning-of-line,alt-a:end-of-line,ctrl-f:page-down,ctrl-b:page-up,ctrl-d:half-page-down,ctrl-u:half-page-up,alt-g:top,ctrl-h:backward-delete-char,bspace:backward-delete-char,ctrl-l:delete-char,ctrl-e:kill-word,ctrl-w:backward-kill-word,ctrl-j:unix-line-discard,ctrl-o:abort,ctrl-m:accept,enter:accept,alt-y:yank --marker=m -e --exit-0  --preview 'ccat <<< {}' --preview-window up:3:wrap +m --keep-right --tac --no-sort | awk '{ print substr($0, index($0,$2)) }'"
        fzf = self.fm.execute_command(command, stdout=subprocess.PIPE)
        stdout, stderr = fzf.communicate()
        if fzf.returncode == 0:
            fzf_file = os.path.abspath(stdout.decode('utf-8').rstrip('\n'))
            if os.path.isdir(fzf_file):
                self.fm.cd(fzf_file)
            else:
                self.fm.select_file(fzf_file)

````

**Comment by toonn** [comment]
Replacing `select_file` with `execute_file` should do it.

**Comment by yyy33** [comment]
> execute_file
I replaced `select_file` with `execute_file`, and I got this tip
````
'str' object has no attribute path
````

**Comment by yyy33** [comment]
'

> Replacing `select_file` with `execute_file` should do it.

I replaced `select_file` with `execute_file`, and I got this tip
````
'str' object has no attribute 'path'
````

**Comment by yyy33** [comment]
> Replacing `select_file` with `execute_file` should do it.

I replaced `select_file` with `execute_file`, and I got this tip
````
'str' object has no attribute 'path'
````

**Comment by toonn** [comment]
Oh, right >.<, try `self.fm.rifle.execute(fzf_file)` instead.

**Comment by yyy33** [comment]
> Oh, right >.<, try `self.fm.rifle.execute(fzf_file)` instead.

Oh, this time I got this tip in the shell
````
xdg-open: unexpected option '--'
Try 'xdg-open --help' for more information.
````

**Comment by toonn** [comment]
Ah, yeah, edit the rifle rule for `xdg-open` it doesn't understand `--`.

**Comment by yyy33** [comment]
> Ah, yeah, edit the rifle rule for `xdg-open` it doesn't understand `--`.

Oh, thank you very much
