### ISSUE TITLE
Not responding

### ISSUE THREAD

**Issue by ask1234560** [ranger/ranger#1963]
#### Runtime Environment
- Operating system and version: 
```
 arch linux
 uname -a
 Linux arch 5.6.12-arch1-1 #1 SMP PREEMPT Sun, 10 May 2020 10:43:42 +0000 x86_64 GNU/Linux
 ```
- Terminal emulator and version:  ``` alacritty 0.4.2 ```
- Python version: ``` Python 3.8.2 ```
- Ranger version/commit: ``` ranger version: ranger 1.9.3
Python version: 3.8.2 (default, Apr  8 2020, 14:31:25) [GCC 9.3.0]
Locale: en_US.UTF-8 ```
- Locale: 
```LANG=en_US.UTF-8
LC_ADDRESS=en_IN
LC_IDENTIFICATION=en_IN
LC_MEASUREMENT=en_IN
LC_MONETARY=en_IN
LC_NAME=en_IN
LC_NUMERIC=en_IN
LC_PAPER=en_IN
LC_TELEPHONE=en_IN
LC_TIME=en_IN
 ```

#### Current Behavior

Ranger not responds,  increasing the cpu usage, check this [video](https://youtu.be/ubHFNT0JicM)

#### Context

After the issue, only killing the terminal 

#### Steps to reproduce
1. The issue is not common and appears some time
2. Appear when shell is launched from ranger, do some stuff, kill shell, then '''fg''' ranger

**Comment by toonn** [comment]
Do you have VCS integration enabled? Does it happen without that?
Next thing to try would be disabling some of the file previews.

**Comment by ask1234560** [comment]
Is VCS version control, how to check if it is enabled.
I have disabled previews for images, videos.

**Comment by toonn** [comment]
Yes, if you didn't turn on the vcs integration it's probably off. Ranger can show the status of files in git repositories with a mark.

Go through `scope.sh` and disable further previews by commenting them out.
Or disable file previews altogether and see if the unresponsiveness still happens.

**Comment by ask1234560** [comment]
hi @toonn , i set ```set use_preview_script false``` 
then the problem appears everytime

steps to produce -
```
*  set use_preview_script false in rc.conf
*  navigate to any folder press S
* exit from the shell using ^D  or typing exit
* the not responding problem appears

```
i haven't known about the :terminal command, so i mapped it to a key and using it .

**Comment by toonn** [comment]
Do `C-l` or `C-q` unstuck ranger?
Could you try with a different terminal emulator?
Could you try setting up your environment with the `en_US.UTF-8` locale?

**Comment by ask1234560** [comment]
* ```ctrl + l  & ctrl  + q``` have no effect


* i have find something,
  * i have a keybind for ``` alacritty -e ranger```
  *  keybind, then S, exiting, the error occurs
  * but if i open a terminal, then executing ranger, and follow S,exit, the problem is not there


* it is not terminal specific, the same error occur in urxvt ``` rxvt-unicode (urxvt) v9.22 - released: 2016-01-23 ```
in urxvt also the error occur when executing ranger form key bind.

* en_us is also in locale ```  /etc/locale.gen ```
```
en_US.UTF-8 UTF-8  
en_IN UTF-8  
```

**Comment by toonn** [comment]
Hmm, can't reproduce this with kitty. I'm not sure why this would happen tbh. The difference in your scenarios is that ranger is a direct child of the terminal, without a shell as a parent.

**Comment by ask1234560** [comment]
kitty ```kitty 0.17.4 created by Kovid Goyal``` also have the issue,  [check this](https://youtu.be/8s_dD0OInyU).

**Comment by toonn** [comment]
The problem is this `zsh suspended (tty output ranger)`. I'm not sure how to interpret it but it sounds like Software Flow Control (C-s, C-q) or job control (C-z, fg). So you'll need to figure out why that happens.

It's not a default behavior so the problem's probably in your zsh setup.

**Comment by ask1234560** [comment]
If it is not a default behavior then we can leave it, btw i am happy with `:terminal`

**Comment by mik13ST** [comment]
Has this started happening after a specific update? If so, please find one previous version where this issue is not yet happening. We could then do a `git bisect` to find which commit caused this.

**Comment by ask1234560** [comment]
This issue happens in zsh but not with bash

**Comment by toonn** [comment]
I don't think bisecting will help. It looks like a shell feature. I can't reproduce it in a vanilla zsh and zsh users haven't reported this before.

The next troubleshooting step would be to run zsh without your `.zshrc` and other config files and plugins.
