### ISSUE TITLE
Most efficient way to do:  "cp -a dir1 dir2" or "cp -a dir.1 dir.2" ?

### ISSUE THREAD

**Issue by philiprhoades** [ranger/ranger#1968]
People,

I am thinking that mapping to keys:
cp
might be the best answer but gurus might know better . . 

Thanks,
Phil.

**Comment by toonn** [comment]
What I'd do:
  1. Mark some files, either with space or `V` for visual selection. (`v` if I just want everything or want to unmark only a couple)
  2. `!`, opens the console with `:shell `
  3. `:shell cp -a %s target/path`

You could map it if you want: `map cp console shell %s%space`.

**Comment by philiprhoades** [comment]
@toonn ,

Thanks for that!
