### ISSUE TITLE
Preview doesn't work under ubuntu 20.04 as root user

### ISSUE THREAD

**Issue by ms-jpq** [ranger/ranger#1969]
#### Runtime Environment

- Operating system and version:  `Linux 5.4.0-29-generic #33-Ubuntu`
- Terminal emulator and version: `iTerm2 3.3.9`
- Python version: `3.8.2`
- Ranger version/commit: `1.9.3`
- Locale: default

#### Current Behavior

No file preview, not even on text files.

The `scope.sh` by itself works tho.

Only seems to happen under `root` user. I verified this using a digitalocean VM

#### Expected Behavior

Preview should work.

#### Steps to reproduce
1.  Make a new ubuntu 20.04 VM
2.  Install ranger-fm via pip3
3. Try to preview a text file using root user

**Comment by ms-jpq** [comment]
ok just found out that this is a “feature” 

:<

**Comment by toonn** [comment]
To be clear `zp` toggles the previews even as root.
