### ISSUE TITLE
Rifle can't open sc files using sc-im

### ISSUE THREAD

**Issue by strogiyotec** [ranger/ranger#1970]
Good day, I do use [sc-im](https://github.com/andmarti1424/sc-im) as spreadsheet editor and I want ranger to open all .sc files with sc-im.
I updated my `rifle.conf` file and added this line
```
ext sc ,  has sc-im,        X, flag f = sc-im -- "$@"
```
However when I try to open sc files then ranger doesn't do anything. How can I fix it ?

Ranger version is 
```
ranger version: ranger 1.9.3
Python version: 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
Locale: en_US.UTF-
```

**Comment by toonn** [comment]
Are you sure `sc-im` supports `--`? It's not listed in the man page.

**Comment by strogiyotec** [comment]
@toonn  thank you for fast response I checked it and you are right it doesn't, so for anyone who wants to open sc files using sc-im you should add this line into rifle.conf
```
ext sc = sc-im "$@"
```

**Comment by toonn** [comment]
`has sc-im` will prevent an error if the program isn't installed. `X` is for programs that require X11. `flag f` forks the program, useful if you want it to run in the background when started from ranger, usually something with a GUI.
