### ISSUE TITLE
Use a different file preview parser to display markdown file

### ISSUE THREAD

**Issue by macgeekpro** [ranger/ranger#1978]
#### Runtime Environment

- Operating system and version: MacOS Catalina 10.5.4
- Terminal emulator and version: iTerm 3.3.9
- Python version: 2.7.16
- Ranger version/commit: 1.9.3
- Locale: 

I am currently using [Glow](https://github.com/charmbracelet/glow), a markdown parser for the CLI. I would like to have Ranger use it whenever it previews a .md or .markdown files. 

I added the following snippets in my scope.sh within the `handle_extension()` function

```
        # Markdown
        markdown|md)
            # Preview as text conversion
            glow "${FILE_PATH}" && exit 5
            exit 1;;

```

But no dice. Any pointer on how I can make it work?

**Comment by toonn** [comment]
Try with another preview command which you know works like the one in handle_fallback to see whether the problem is the case not matching or the glow output not being acceptable.
Next, check whether glow reports success or a return code different from 0.

**Comment by macgeekpro** [comment]
ok. 2 questions 1) how do i access the ranger's log? 2) how do i check the boolean value of a particular option, let's say `use_preview_script`?

**Comment by macgeekpro** [comment]
After some tinkering, I manage to have glow shows its output in the preview pane. However, it seems the output is not the same as if i were to directly call glow in the shell. for example, the highlight colors are not shown or tables are not rendered correctly etc. I assume the preview output is filtered by Pager?

**Comment by toonn** [comment]
Nope, no filtering. Python curses doesn't support 256 colors though.

You can check settings values using `?s`.
And the only log you can access is `w` but that won't have any info from scope.sh.

**Comment by macgeekpro** [comment]
Got it. Thanks.

**Comment by kevinhwang91** [comment]
@yohannes
```bash
        md)
            ## markdown
            glow -s dark -- "${FILE_PATH}" && exit 5
            exit 1;;
```

**Comment by yohannes** [comment]
@kevinhwang91 Thanks. I can confirm that the render works with Kevin's suggestion.

**Comment by toonn** [comment]
This could easily make it into our default `scope.sh` imo. I think adding `-w "${PV_WIDTH}"` might be a further improvement (I expect glow's wrapping would be better than ranger re-wrapping a wrapping of glow that is too wide for the preview column). Otoh, people with a very wide preview pane might prefer narrower wrapping so maybe it should be bounded by 80 or 100 columns or so?

@charmbracelet, it looks like glow doesn't manage to detect the terminal's background color when invoked by ranger. Do you have any insight as to why this might be? And I couldn't find a feature to limit glow's output to 256 colors which would be ideal. It seems like the dark theme is limited to 256 colors so I'm surprised glow doesn't work without specifying the theme explicitly.
