### ISSUE TITLE
rendering breaks in a folder with a unicode name.

### ISSUE THREAD

**Issue by crocket** [ranger/ranger#1986]
#### Runtime Environment

- Operating system and version: Gentoo
- Terminal emulator and version: alacritty-0.4.2 
- Python version: 3.7.7
- Ranger version/commit: 1654128f955b320354eea98a0bb6970a159ab16f
- Locale: en_US.UTF-8

#### Current Behavior

![2020-06-04_Thu_11:10:42](https://user-images.githubusercontent.com/748856/83749970-89cac680-a69f-11ea-8ada-337b85b3ecd8.png)

#### Expected Behavior

![2020-06-04_Thu_11:10:38](https://user-images.githubusercontent.com/748856/83749958-833c4f00-a69f-11ea-8eaa-2c0c13242a14.png)

#### Steps to reproduce

1. Make a folder named `2020-06-03|gmarket.co.kr|케이제이통상|런던필 LF-590`
2. Put some files in it.
3. Be in the folder for a while.

**Comment by toonn** [comment]
Hmm, at first I thought maybe it's just a width calculation but the repetition of the name is weird.

**Comment by crocket** [comment]
In lf file manager, this issue doesn't happen.

**Comment by toonn** [comment]
We have some open PRs that probably fix this.

**Comment by crocket** [comment]
I discovered that the issue happens on alacritty, but not on st.

**Comment by crocket** [comment]
Weirdly, upgrading alacritty from 0.4.2 to 0.4.3 fixed the issue.

**Comment by toonn** [comment]
Oh, sweet : )
Thanks for reporting this!
