### ISSUE TITLE
render issue on kitty when renaming file while image preview is running

### ISSUE THREAD

**Issue by issadarkthing** [ranger/ranger#1997]
#### Runtime Environment
Ubuntu 19.10
ranger version: ranger 1.9.3
kitty 0.14.3
Python version: 3.7.5 
(default, Apr 19 2020, 20:18:17) 
[GCC 9.2.1 20191008]
Locale: en_US.UTF-8

#### Current Behavior
![image](https://user-images.githubusercontent.com/50593529/84683800-5a06a300-af6a-11ea-8040-2aa14f054f0d.png)

#### Context
This only happen when im using kitty and the image preview is on. Im trying to rename file but the name of the file to edit always misplaced around ranger and it causes weird UI look

#### Steps to reproduce
1. Use kitty terminal
2. Set image preview on
3. Change the name of the file

```

**Comment by toonn** [comment]
I think this is a duplicate issue, it'd help if you could search through the issues and link them.

**Comment by issadarkthing** [comment]
found the same issue https://github.com/ranger/ranger/issues/1598

**Comment by toonn** [comment]
Thank you, I'm closing this in favor of that one.
