### ISSUE TITLE
Create a command to create dirs and files

### ISSUE THREAD

**Issue by dagadbm** [ranger/ranger#1998]
This is a feature suggestion.

We have mkdir which creates directories and touch that creates files but we have no way to recursively create the directories if they don't exist.

For example doing :command a/b/c/d would create dirs a/b/c and then the file d inside it

**Comment by toonn** [comment]
`:mkdir` already creates directories recursively.
We should do the same for `:touch`.

**Comment by dagadbm** [comment]
Thats why I think we should only really need one command that does both
(sure you can argue its not very linux but so is using touch to create
files which was no its original intention)
