### ISSUE TITLE
ranger and single interactive bash session

### ISSUE THREAD

**Issue by ri-aje** [ranger/ranger#2000]
#### Runtime Environment

- Operating system and version: ubuntu 18.04
- Terminal emulator and version: terminator 1.91
- Python version: Python 3.7.1
- Ranger version/commit: 
ranger version: ranger-master v1.9.3-24-g1654128f
Python version: 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
Locale: None.None
- Locale: 

#### Current Behavior
N/A

#### Expected Behavior
ranger be able to show an interactive bash session without opening a new bash session every time, and throw current selected files onto the command line, or some other mechanism to allow the bash session to retrieve ranger info.

#### Context

as versatile as ranger, I often find myself needing my customization in bashrc that has no equivalence in ranger, such as alias and functions (and lifting everything into their own scripts isn't a solution, not even a good workaround). basically I would like to combine ranger's ability to select files/folders and my own stuff in bash to manipulate them for further usage. I believe this also unlocks many useful scenarios in future.

I hit two issues in this use case:
1. for my bashrc, starting bash gives noticeable slowdown and it quickly becomes annoying when I have to do it often which is the case when I enter/exit from ranger into bash from time to time.
2. I didn't find a way to access ranger info from bash, even one that is spawned by ranger with `shell $SHELL`, so I cannot combine the best parts of ranger and bash.

#### Possible Solutions
for the first problem.
1. have ranger to manage an interactive bash session in the background and bring it up with some ranger command, e.g., `bash`. we will need a special command to 'exit' that bash back into ranger without actually exiting it. this will avoid loading bashrc every time, or
2. `ctrl-z` to suspend ranger and back up into the bash session that spawned ranger (make sure to automatically `cd` into whatever directory ranger was in), and somehow allow accessing ranger info from that bash session. obviously we will use `fg` to go back to ranger. this assumes ranger was launched from a bash session, which I think is reasonable enough. 

for the second issue.
if accessing ranger for various info is not possible, the next best is to throw the current selection onto the bash command line (properly quoted and escaped), then let the user to decide what to do with them. in case the user doesn't need them at all, they can be easily dismissed.

#### Steps to reproduce
in ranger console, execute `shell $SHELL` shows the current behavior that spawns a new bash instance every time (their pid are different). I didn't find similar issue reported here, or similar ideas discussed. I tried to implement a ranger bash command based on `fzf_select` example, but cannot make the inter-process comm work, the managed bash session never gives me output, and there is no way to go back to ranger without exiting that bash.     

#### Traceback

```

```

**Comment by toonn** [comment]
If you're willing to switch to zsh I believe [deer](https://github.com/Vifon/deer) gives you what you want.

Re 1.1, refactor your rc files so it's not slow or use a faster shell, like fish. 1.2) You could pass things in env vars or the clipboard, `shell env FILES=%s $SHELL` (You'd probably have to convert the string to a colon-separated list but you get the idea) or `yp` to yank the paths and then use the clipboard in your shell through xclip/xsel. You can look into `--choosefiles` for another way to get at the selected files.

2.1) This is unlikely to become part of ranger, take a look at [zranger](https://github.com/Vifon/zranger), maybe you can adapt it for bash since it uses tmux.

2.2) That's not possible unfortunately, a child process can't influence its parent (unless they agree on some form of communication beforehand but afaik shells don't). We have a script in `examples/shell_automatic_cd.sh` which you can use to "cd to the dir selected in ranger." But ranger has to exit (after the shell *sources* that script) for it to work.

What's your reasoning for preferring aliases over scripts? Scripts are great, they're more portable across systems and shells, easier to share and easier to expand and you can basically write them in any language. The fish shell does away with aliases because they don't provide any value over functions and functions are basically simple scripts anyway.

**Comment by ri-aje** [comment]
@toonn thanks for the quick response and the pointers to deer and zranger. they look interesting and might be able to give me what I am after eventually.

as for my preference for alias and functions, I have lots of them. depending on the OS and other factors, I define some of them but not the others, or they have different definitions, e.g., copying stuff is different on linux (xsel/xclip as you mentioned) and osx (pbcopy), but I'd rather have an uniform interface. meanwhile, they also share some fundamentals, like detecting current system to branch. splitting them up would result in a bunch of duplicate code, like the os branching logic and in future maybe windows wsl will come into play so that's even more branching and harder to fix when they litter around in many small scripts, which in themselves is harder to manage depending on the circumstance, e.g., when working with remote servers, with one big bashrc, I can just copy/paste through the clipboard, whereas scripts aren't that easy to flow in this case, and some secure portal outright disallows transferring any files.

that said, I do appreciate the advantages (such as writing them in any languages) of scripts and happily use them where they fit, it's just overall they are two different worlds and each has its merits and one cannot reasonably displaces the other without losing some advantages. I guess their co-existence to this day is the best proof.

with ranger, scripts work without a problem, so that's why the focus is on bashrc and aliases which don't play that well with ranger.

**Comment by toonn** [comment]
They only still exist because bash still does : )

If you were to put all your aliases in a single script, or a couple scripts, you'd avoid all the disadvantages re duplication and you could could source the script from bashrc but also get at it through ranger.

To each their own though.

**Comment by ri-aje** [comment]
> They only still exist because bash still does : )
> 
> If you were to put all your aliases in a single script, or a couple scripts, you'd avoid all the disadvantages re duplication and you could could source the script from bashrc but also get at it through ranger.
> 
> To each their own though.

ok. once I have a separate aliases script, how do I have ranger to source them? and am I right that once ranger sourced them, they will be available on regular functions on ranger command line? I am trying to see how this works. thanks.

**Comment by toonn** [comment]
No, ranger commands are implemented in `commands.py` (we consider it a configuration file).
Ranger has no business sourcing your aliases. But you can write keybinds that source it in a shell where you want to use your aliases. `:shell` uses non-interactive shells which don't normally load aliases. So this is a way to get access to those. For interactive shells there wouldn't be a difference. You might be able to override the `:shell` command so it always sources the script though.

**Comment by ri-aje** [comment]
alright, that's what I thought (that ranger doesn't source my scripts by default, which makes sense). I can see to let `:shell` source it, but there seems to be no fundamental difference from sourcing bashrc altogether. just to make sure I understand you correctly, is the intention to source a potentially much smaller alias script than the whole bashrc to reduce the processing time down to negligible range, so the problem effectively goes away, without a complicated solution to manage an interactive bash session? thanks.

**Comment by toonn** [comment]
Well `:shell` spawns non-interactive shells. You say starting an interactive shell takes way too long. If you source bashrc, every non-interactive shell will take just as long. Having your aliases as functions in a script would also allow you to use them from other scripts. And if that script is large enough to cause noticeable slowdown you can easily refactor it into two or more parts so you can source just the most commonly used functions.
