### ISSUE TITLE
Bulkrename confirmations

### ISSUE THREAD

**Issue by sheepfleece** [ranger/ranger#2002]
#### Current Behavior
After confirming the changes and exiting vim for the second time, you are greeted with "Press ENTER to continue" message.

 ![1592553914](https://user-images.githubusercontent.com/47691267/85111374-e93ae180-b21c-11ea-881f-3c339ec085b2.png)

#### Expected Behavior
It would be nice if there were a way to stop this message from appearing at all. Also the "Review changes" message could be made opt-out as well.

**Comment by vascowhite** [comment]
I came here today to make a the same mistake. I had a lot of nulk renaming to do todya and this was very annoying!

Other than that, thanks for making Ranger, it is awesome!
