### ISSUE TITLE
Python version inside Ranger must be greater than 3,  Neovim recommends

### ISSUE THREAD

**Issue by lee-shun** [ranger/ranger#2006]
I am using ubuntu 18,04 with neovim on it.
I have installed python 2,7 and python 3,6 in os. 
here is my question: When I was running "checkhealth" in the nvim, there is an ERR about ranger: 
"
## Python
  - ERROR: Version: 2.7.17 (default, Apr 15 2020, 17:20:14) [GCC 7.5.0]
    - ADVICE:
      - Python version inside Ranger must be greater than 3
      - Please install Ranger properly
"
By the way, I make the ranger 1.9.3 manully locally, and install it after using "pip install ranger-fm'

Thanks!

**Comment by toonn** [comment]
We default to whatever version the python executable is. You can install for a different python like this: `env PYTHON=/path/to/pythonXYZ make install`.

I'm gonna keep this open as an enhancement request, `python` is supposed to always point to a python 2.x executable officially so it makes sense to default to `python3`.
