### ISSUE TITLE
argument with spaces

### ISSUE THREAD

**Issue by yonghie** [ranger/ranger#2031]
#### Current Behavior
Is it possible to get multi-word argument ?

#### Expected Behavior
something like ```:cmd -param "hello world"``` and "hello world" be one argument?

**Comment by toonn** [comment]
Depends on which command. `:mkdir` for example simply allows spaces in the filename. `:shell` requires you to shell-escape everything properly.

**Comment by yonghie** [comment]
> Depends on which command. `:mkdir` for example simply allows spaces in the filename. `:shell` requires you to shell-escape everything properly.

oh thanks. i found in ``commands_full.py``  ``self.rest()``  what helped a lot
