### ISSUE TITLE
Problems with ueberzug in alacritty

### ISSUE THREAD

**Issue by CramMK** [ranger/ranger#2033]
#### Runtime Environment

- Operating system and version: Fedora 32
- Terminal emulator and version: alacritty 0.4.3
- Python version: 3.8.3
- Ranger version/commit: 1.9.2
- Locale: en_US.UTF-8

#### Current Behavior
I recently switched from w3m to ueberzug for my image preview, because of alacritty not properly rendering the image. With ueberzug, no image gets rendered at all.

Config:
```aincrad ~  cat .config/ranger/rc.conf
set preview_images true
set preview_images_method ueberzug

#icons
default_linemode devicons

# separators, outline, both, none
set draw_borders none

set mouse_enabled true
```

Trying out various things suggested in https://github.com/ranger/ranger/pull/1284 didn't help me.

![Screenshot-20200707-173856](https://user-images.githubusercontent.com/39596050/86806029-c0b64280-c078-11ea-9208-b76c66ca06a7.png)

I can provide more information if necessary

**Comment by toonn** [comment]
Ranger 1.9.2 doesn't support Ueberzug.

**Comment by adnion** [comment]
The problem is that ueberzug doesn't support wayland. Do you know a previewer other than w3m or ueberzug?

**Comment by toonn** [comment]
@adnion, kindly don't hijack issues. I think you'll have to rely on one of the native previewing methods or mpv. And no, there's no native method for alacritty.

**Comment by adnion** [comment]
@toonn Oh there's an overview on the main page: 
> w3mimgdisplay, ueberzug, mpv, iTerm2, kitty, terminology or urxvt for image preview

I didn't hijack this issue, because Fedora is based on wayland and ultimately this is the solution to the issue. 
Even with latest master it's not working.

btw: Thank you for your work on ranger!

**Comment by CramMK** [comment]
Is there a plan to implement Überzug to the latest versions?

**Comment by adnion** [comment]
@CramMK This is not a ranger issue. Actually it's an ueberzug missing wayland support issue.
https://github.com/seebye/ueberzug/issues/30
I don't know how to resolve this.

**Comment by toonn** [comment]
@adnion, ah, didn't realize Fedora already pushed Wayland. Thank you for pointing it out.

Ok, so there's two reasons Ueberzug didn't work here:
  1. Ranger 1.9.2 is too old, the ueberzug method is supported from 1.9.3 onwards.
  2. Fedora defaults to Wayland and ueberzug is X11-only.

The "fix" in this case is probably to use one of the native image previewing methods.

**Comment by developic** [comment]
> Is there a plan to implement Überzug to the latest versions?

you can use xwayland
