### ISSUE TITLE
Custom command to copy files not working

### ISSUE THREAD

**Issue by Qwerty-Space** [ranger/ranger#2045]
#### Runtime Environment

- Operating system and version: Arch
- Terminal emulator and version: urxvt v9.2.2
- Python version: 3.8.3
- Ranger version/commit: 1.9.3
- Locale: en-gb

I'm trying to write a command to copy images to the clipboard.  It works just fine as a bash script running through ranger, but I'd like to make it a ranger command.

The original bash script:
```sh
TYPE=$(file -b --mime-type "$1")
xclip -se c -t "$TYPE" "$1"
```

The (non-working) ranger command:
```python3

class x_copy(Command):
    """
    Copies a file to the x clipboard
    """

    def execute(self):
        cf = self.fm.thisfile
        mimetype = self.fm.run('file -b --mime-type "{cf}"')

        self.fm.run(f'xclip -se c -t {mimetype} {cf}')
```

Even if I commend out the `mimetype=` line, and hardcode the mimetype in the last line, it won't copy.  What have I done wrong?

**Comment by Qwerty-Space** [comment]
With the help of __monty__ on irc (sorry I don't know your gh username) we came up with this solution.  

```python3
class x_copy(Command):
    """
    Copies a file to the x clipboard
    """

    def execute(self):
        cf = quote(self.fm.thisfile.path)
        self.fm.notify(cf)
        self.fm.run(f"xclip -se c -t $(file -b --mime-type {cf}) {cf}")
        self.fm.notify("Copied to x clipboard")


    def tab(self, tabnum):
        # tab completion
        return self._tab_directory_content()
```

There were a few problems with the original code.  Setting the output of `self.fm.run()` to a variable can't be done without  [Popen.communicate()](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate).  And `self.fm.thisfile` returns a file object instead of a string, so we need `self.fm.thisfile.path`

**Comment by toonn** [comment]
If you don't need a command and you can reduce your script to a one-liner, a simple binding is always an option: `map xyz shell xclip -se c -t $(file -b --mime-type %f) %f`.

**Comment by kevinhwang91** [comment]
@Qwerty-Space You inspire me to write this script. Now I don't always need to drag an image file by mouse.

```python
import os
import subprocess
from ranger.api.commands import Command
from ranger.container.file import File
from ranger.ext.get_executables import get_executables


class YankContent(Command):
    """
    Use xclip to copy content to the x clipboard
    """

    def execute(self):
        if 'xclip' not in get_executables():
            self.fm.notify('xclip is not found.', bad=True)
            return

        arg = self.rest(1)
        if arg:
            if not os.path.isfile(arg):
                self.fm.notify('{} is not a file.'.format(arg))
                return
            file = File(arg)
        else:
            file = self.fm.thisfile
            if not file.is_file:
                self.fm.notify('{} is not a file.'.format(file.relative_path))
                return

        relative_path = file.relative_path
        if not file.is_binary():
            target = 'TEXT'
        elif file.image:
            target = file.mimetype
        else:
            self.fm.notify('{} is not an image file or a text file.'.format(relative_path))
            return
        cmd = ['xclip', '-selection', 'clipboard', '-t', target, file.path]
        subprocess.check_call(cmd)
        self.fm.notify('Content of {} is copied to x clipboard'.format(relative_path))

    def tab(self, tabnum):
        return self._tab_directory_content()
```

I don't use a shell script to implement this feature because it will redraw and any errors can't be handled elegantly.

**Comment by Qwerty-Space** [comment]
@kevinhwang91 brilliant! I might have to use yours if it supports multiple files

**Comment by kevinhwang91** [comment]
> @kevinhwang91 brilliant! I might have to use yours if it supports multiple files

How can xclip copy multiple files content into the clipboard in shell?

**Comment by toonn** [comment]
@kevinhwang91, good catch using the file's `mimetype` attribute.

**Comment by Qwerty-Space** [comment]
> > @kevinhwang91 brilliant! I might have to use yours if it supports multiple files
> 
> How can xclip copy multiple files content into the clipboard in shell?

Well, the description in the man page says one or more files

**Comment by toonn** [comment]
The man page is probably talking about the names/paths of multiple files though.

**Comment by kevinhwang91** [comment]
I found that using `target` with tag file instead of input stream will make `xsel -o -b` output nothing.
updated script:
```python
import os
import subprocess
from ranger.api.commands import Command
from ranger.container.file import File
from ranger.ext.get_executables import get_executables


class YankContent(Command):
    """
    Copy the content of image file and text file with xclip
    """

    def execute(self):
        if 'xclip' not in get_executables():
            self.fm.notify('xclip is not found.', bad=True)
            return

        arg = self.rest(1)
        if arg:
            if not os.path.isfile(arg):
                self.fm.notify('{} is not a file.'.format(arg))
                return
            file = File(arg)
        else:
            file = self.fm.thisfile
            if not file.is_file:
                self.fm.notify('{} is not a file.'.format(file.relative_path))
                return

        relative_path = file.relative_path
        cmd = ['xclip', '-selection', 'clipboard']
        if not file.is_binary():
            with open(file.path, 'rb') as fd:
                subprocess.check_call(cmd, stdin=fd)
        elif file.image:
            cmd += ['-t', file.mimetype, file.path]
            subprocess.check_call(cmd)
            self.fm.notify('Content of {} is copied to x clipboard'.format(relative_path))
        else:
            self.fm.notify('{} is not an image file or a text file.'.format(relative_path))

    def tab(self, tabnum):
        return self._tab_directory_content()
```

**Comment by kevinhwang91** [comment]
> > > @kevinhwang91 brilliant! I might have to use yours if it supports multiple files
> > 
> > 
> > How can xclip copy multiple files content into the clipboard in shell?
> 
> Well, the description in the man page says one or more files

Actually, I mean pasting multiple copied image files, not text files.
Copying multiple text files like cat is useless in ranger.
