### ISSUE TITLE
scope.sh: use built-in bash lowercase substitution instead of tr

### ISSUE THREAD

**Issue by strongberrypearl** [ranger/ranger#2051]
scope.sh currently does this to get the file's extension:

```
FILE_EXTENSION="${FILE_PATH##*.}"
FILE_EXTENSION_LOWER="$(printf "%s" "${FILE_EXTENSION}" | tr '[:upper:]' '[:lower:]')"
```

Bash 4+ has a built-in way to do this. Here is the adjusted example:
```
FILE_EXTENSION="${FILE_PATH##*.}"
FILE_EXTENSION_LOWER="${$FILE_EXTENSION,,}"
```

I timed both of these 10,000 times and got these results.

```
FILE_PATH='/path/to/wow.TxT';time ( for x in $(seq 10000); do FILE_EXTENSION="${FILE_PATH##*.}"; FILE_EXTENSION_LOWER="$(printf "%s" "${FILE_EXTENSION}"
| tr '[:upper:]' '[:lower:]')"; done )

real    0m14.057s
user    0m13.881s
sys     0m3.724s
```
```
FILE_PATH='/path/to/wow.TxT';time ( for x in $(seq 10000); do FILE_EXTENSION="${FILE_PATH##*.}"; FILE_EXTENSION_LOWER="${FILE_EXTENSION,,}"; done )

real    0m0.060s
user    0m0.060s
sys     0m0.000s
```

As you can see, the Bash version is much faster. I made sure that both give 'txt' as well. This may cause problems if on a system with an ancient version of Bash (4.0 came out in early 2009); if that is unacceptable a check like ((BASH_VERSINFO[0] >= 4)) could be run to ensure Bash 4+ before using it.

**Comment by toonn** [comment]
Tbh I'd rather not include a bashism that probably makes very little difference in practice. The runtime for this string extraction is dwarfed by the time the conversions take.

I know scope.sh isn't currently posix sh compatible but I'd like to move towards that rather than away. Also, you'd be surprised how old bash on MacOS can be, mine's currently 3.2.57.

**Comment by strongberrypearl** [comment]
I didn't realize that Macs had such old versions of Bash.

In that case, I suppose that it could be left the way it is. If anyone who stumbles upon this issue has Bash 4+ and happens to care, he could just change the line himself.
