### ISSUE TITLE
Is there a method for remote image preview ?

### ISSUE THREAD

**Issue by lyjdwh** [ranger/ranger#2057]
When I login in a remote linux with ssh, the image preview doesn't work. 
Remote ranger is well set up.

ssh config
```
  ForwardAgent yes
  ForwardX11 yes
  ForwardX11Trusted yes
```
system: `manjaro`
terminal: `st`
image preview method: `ueberzug`

**Comment by toonn** [comment]
I think you'll have more luck over on the ueberzug issue tracker.
The kitty method works over ssh without X forwarding.

**Comment by lyjdwh** [comment]
Thanks for your suggestions. 
But I didn't get a solution from ueberzug issue tracker and don't want to change my terminal temporarily.

**Comment by toonn** [comment]
If @seebye doesn't have an answer then you're probably out of luck.

**Comment by seebye** [comment]
Ueberzug uses shared memory to display images faster, so it's not supported in the latest version.  
(Old version does support it - but I don't like it at all as you would need to start an terminal emulator on the server to display images (due to implementation details))

**Comment by toonn** [comment]
Hope that answers your question, @lyjdwh. That makes kitty the only currently supported previewing method that works transparently over ssh. Maybe you could use a remote filesystem like sshfs or nfs with a locally running ranger for image previews?
