### ISSUE TITLE
Ranger logo for Wikipedia/Commons

### ISSUE THREAD

**Issue by nunmap** [ranger/ranger#2087]
Hello,
Could you please publish the Ranger logo as a svg & and release it under one of the following licenses?

* Creative Commons Attribution ShareAlike 4.0 (legal code)
* Creative Commons Attribution ShareAlike 3.0 (legal code)
* Creative Commons Attribution ShareAlike 2.5 (legal code)
* Creative Commons Attribution 4.0 (legal code)
* Creative Commons Attribution 3.0 (legal code)
* Creative Commons Attribution 2.5 (legal code)
* Creative Commons CC0 Waiver (release all rights, like public domain: legal code)

So the logo can freely be used on the [Ranger Wikipedia](https://en.wikipedia.org/wiki/Ranger_(file_manager)) article.

**Comment by toonn** [comment]
@zaeph, can I count on you to do this?

**Comment by nunmap** [comment]
I don't mind uploading it to Wikimedia Commons. If you could just commit it along with a file with who the artists are and the name of the licence.

**Comment by zaeph** [comment]
I'll take care of it by Friday.

**Comment by zaeph** [comment]
@toon Done in ranger/ranger-assets/pull/3.

@nunmap The file to be merged is [here](https://raw.githubusercontent.com/ranger/ranger-assets/166f067acf9f641a21cc1dc3c4b5e7804e20822c/logo/ranger312.svg).  Once it's merged, you'll find [inside the repo](https://github.com/ranger/ranger-assets/blob/master/logo/ranger312.svg).

**Comment by nunmap** [comment]
Ah, I didn't know it was in another repo, so no need to commit it here. [I've added it](https://commons.wikimedia.org/wiki/File:Ranger_logo.svg) but it only renders correctly on [this page](https://upload.wikimedia.org/wikipedia/commons/6/64/Ranger_logo.svg) so it will look wrong on Ranger's Wikipedia page. Also cleaning it with [svgcleaner](https://github.com/RazrFalcon/SVGCleaner) brakes it in a similar same way as the browsers are rendering it incorrectly.

Anyway it looks as good as the Vim logo and I thought it deserves to become just as recognizable.

**Comment by zaeph** [comment]
I could _path-ify_ the font.  Let me see what I can do.

**Comment by zaeph** [comment]
Done in ranger/ranger-assets/pull/4.  You can verify it works [here](https://github.com/zaeph/ranger-assets/blob/pathified/logo/ranger312_pathified.svg).

**Comment by nunmap** [comment]
Okay, [png version](https://en.wikipedia.org/wiki/Ranger_(file_manager)) will be fine. Thanks guys
