### ISSUE TITLE
Question: how to unmark files?

### ISSUE THREAD

**Issue by peey** [ranger/ranger#2090]
I'm using `SPC` or `V` to mark files. Is there a way to unmark a single file without unmarking the entire selection (which is what `:unmark` does)? 

I was expecting `SPC` to actually toggle the mark, but it doesn't do that.

**Comment by toonn** [comment]
Space *does* toggle selection. (Marks are a different concept in ranger.)

**Comment by peey** [comment]
In that case, I might be confusing something. I'll go over these concepts again, thanks!
