### ISSUE TITLE
How to reset cache? seems that ranger doesn't detect some of the videos when i force quit it.

### ISSUE THREAD

**Issue by p0txky** [ranger/ranger#2094]
#### Runtime Environment

- Operating system and version: Manjaro
- Terminal emulator and version: URxvt v9
- Python version: 3.8.5
- Ranger version/commit: 1.9.
- Locale: 2.32

**Comment by p0txky** [comment]
I think the files are corrupted.

**Comment by toonn** [comment]
There's `~/.cache/ranger` and `~/.local/share/ranger`, I think that's all for caching.
