### ISSUE TITLE
:checkhealth ERROR: Failed to run healthcheck for "rnvimr" plugin.

### ISSUE THREAD

**Issue by AlexanderBlum** [ranger/ranger#2098]
#### Runtime Environment
- Operating system and version: Ubuntu 18.04.4
- Terminal emulator and version: Bash 4.4.20(1)
- Python version: 2.7.17
- Ranger version/commit: ranger-stable 1.8.1

#### Current Behavior
My ranger config file isn't seen by rnvimr. Any configuration options I add work when I access ranger via bash, but aren't there when I access ranger through vim. For example my default ranger editor is Neovim in bash, but Nano when going through Neovim. When I run :checkhealth in Neovim I get this message:
  - ERROR: Failed to run healthcheck for "rnvimr" plugin. Exception:
    function health#check[21]..health#rnvimr#check[2]..<SNR>79_check_python_ranger, line 7
    Vim(let):E688: More targets than List items

#### Expected Behavior
For my Ranger text editor to remain constant inside and outside of Neovim.

#### Context

I would like Ranger to work identically inside and outside of Neovim.

#### Possible Solutions
I removed ranger and rnimr completely from my system and did a fresh install of both. Same error occurred.

#### Steps to reproduce
1. Install ranger
2. Install rnvimr
3. Open Neovim and run checkhealth

#### Traceback

```

```

**Comment by kevinhwang91** [comment]
From https://github.com/kevinhwang91/rnvimr.
> Requirements
Ranger (v1.9.3 at least)
Pynvim
Neovim
Python3.6
Ueberzug (optional, v18.1.6 at least)

This issue isn't related to ranger, please understand the relationship between rnvimr and ranger.

**Comment by toonn** [comment]
Yep, please report this on the rnvimr tracker : )

**Comment by AlexanderBlum** [comment]
Thanks guys, that was pretty unhelpful but I fixed it.

**Comment by lumb3rjack** [comment]
how?

**Comment by Jacob3075** [comment]
@AlexanderBlum How did you fix it?

**Comment by kevinhwang91** [comment]
Why don't you post an issue at https://github.com/kevinhwang91/rnvimr?

rnvimr is not an official plugin of ranger.

**Comment by dm-grinko** [comment]
How to fix it?
![Screen Shot 2022-05-29 at 10 31 21 AM](https://user-images.githubusercontent.com/14158015/170883651-a070000b-39dd-4890-ad29-bd6fc545bb96.png)

**Comment by kevinhwang91** [comment]
> How to fix it? ![Screen Shot 2022-05-29 at 10 31 21 AM](https://user-images.githubusercontent.com/14158015/170883651-a070000b-39dd-4890-ad29-bd6fc545bb96.png)

Install ranger under your `PATH`.
