### ISSUE TITLE
Why don't work "yn" for copy filename?

### ISSUE THREAD

**Issue by seriiserii825** [ranger/ranger#2102]
#### Runtime Environment

- Operating system and version: xubuntu 18.04
- Terminal emulator and version: I use terminal quake, but in default terminal yn for copy filename don't work. 
- Python version: 2.7.17
- Ranger version/commit: 1.8.1 

#### Current Behavior
I have installed the xubuntu at my work place too, and there "yn" works to copy filename. But for home notebook, this shortcut don't work.
#### Expected Behavior
I want to copy filename from ranger. 

#### Context

This is command from rc.conf 
map yn shell -f echo -n %f    | xsel -i; xsel -o | xsel -i -b

Thanks for help.

**Comment by toonn** [comment]
That's a very old version of the command. It should still work if you install `xsel` though. If you upgrade ranger you can also use `xclip`.

**Comment by seriiserii825** [comment]
Wooowwwww. 
Thanks a lot. 
I installed xsel and now i can copy filename to clipboard. 

Thanks man!!!!
