### ISSUE TITLE
Open new tab after all tabs when start

### ISSUE THREAD

**Issue by StephanoGeorge** [ranger/ranger#2107]
### Current Behavior

Edit `rc.conf`: `set save_tabs_on_exit true`

Start ranger, keep some tabs and exit.

Start with `ranger` command, ranger will open a new tab of current path in front of all tabs.

#### Expected Behavior

I want ranger to open new tab after all tabs, or do not open new tab.

#### Context

I want to fix some tags at the beginning.

Thanks.

**Comment by toonn** [comment]
There's an open issue about this.
