### ISSUE TITLE
ranger becomes a fork bomb when previewing svg

### ISSUE THREAD

**Issue by lilydjwg** [ranger/ranger#2113]
#### Runtime Environment

- Operating system and version:  Arch Linux current
- Terminal emulator and version: gnome-terminal 3.36.2-1 + tmux 3.1_b-1
- Python version: 3.8.5-2
- Ranger version/commit: 240d8a0ea1b82690372ba067c24a3f581a29c782
- Locale: zh_CN.UTF-8
- imagemagick-fftw 7.0.10.31-1 and inkscape 1.0.1-1

#### Current Behavior

Lots of child `identify` and `inkscape` processes

#### Expected Behavior

Not too many to bring the system down.

#### Steps to reproduce
1. in `~/.config/ranger/rc.conf` put `set preview_images true`
1. protect yourself with e.g. systemd + cgroups. If you have systemd + cgroups v2, you can run `systemd-run --user --scope -p CPUQuota=10% -p TasksMax=100 -p MemoryMax=1G -u ranger ./ranger.py`
2. navigate to a (large) svg, e.g. one generated with `systemd-analyse plot`
3. see quite a few child processes being created (in htop or `systemctl --user status ranger.scope`). If not too many, try `Ctrl-C` one or more times. Memory is using up, CPU time is using up.
4. to cleanup, run `systemctl --user kill ranger.scope` and `systemctl --user kill -s KILL ranger.scope` several times.

**Comment by toonn** [comment]
Isn't this an upstream issue?

**Comment by lilydjwg** [comment]
What upstream?

The process tree is like this:

* ranger
  * bash
    * identify
      * inkscape
  * bash
    * identify
      * inkscape
  * bash
    * identify
      * inkscape

**Comment by toonn** [comment]
Either Inkscape or ImageMagick. We don't do anything but call `convert` and `identify`.

**Comment by lilydjwg** [comment]
The problem is that ranger calls `identify` too many times concurrently. Inkscape or ImageMagick is only slow, not behaves wrongly as far as I can see.

**Comment by toonn** [comment]
Yeah, this is just #1320. Closing in favor of that one.
