### ISSUE TITLE
Incorrect syntax for pygmentize in scope.sh

### ISSUE THREAD

**Issue by NetherKing1357** [ranger/ranger#2114]
#### Runtime Environment

- Operating system and version: Ubuntu 18.04 on WSL2
- Terminal emulator and version: Windows Terminal Preview 1.4.2652
- Python version: 3.6.9
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
`pygmentize` installed through pip3 (Pygments==2.7.1) will not highlight correctly for the commands in scope.sh.

#### Possible Solutions
Replace the text in scope.sh pertaining to highlighting with the following: (line 100)
```shell
        if [ "$(tput colors)" -ge 256 ]; then
            pygmentize_format=terminal256
            highlight_format=xterm256
        else
            pygmentize_format=terminal
            highlight_format=ansi
        fi
	
        try safepipe highlight --out-format=${highlight_format} "$path" && { dump | trim; exit 5; }
        try safepipe pygmentize -O style=default -f ${pygmentize_format} "$path" && { dump | trim; exit 5; } # change highlight style here if you wish
```
This solution will work on terminals with and without truecolor support. It will also work with custom styles installed by the user.

**Comment by toonn** [comment]
Hmm, you're describing a patch to an ancient version of scope.sh. Get rid of your scope.sh and --copy-config a new one, or simply remove it from `~/.config/ranger` if you don't intend to customize it. Then see if you can reproduce the problem.

**Comment by NetherKing1357** [comment]
Ah right, my fault entirely. The newer versions work fine, and changing style just involved updating the PYGMENTIZE_STYLE variable on line 46. Thanks!

**Comment by toonn** [comment]
Note that it's easier to just export a definition of that variable in your shell's rc file. That way you don't need to alter `scope.sh` and if you don't have a `scope.sh` it doesn't get outdated across updates : )

**Comment by NetherKing1357** [comment]
Is there a way to choose the highlighter without editing `scope.sh`? I have `bat` installed but would prefer to use `pygmentize`

**Comment by toonn** [comment]
No. We can't add variables for all the possible choices so we consider scope.sh a configuration file, to be changed for most things. Styles are an exception because they're more system-wide configuration things and the programs already have such behavior built-in. We generally use an order of least-likelihood of programs being installed. Reasoning is if you have a rare program installed it's probably because you like using it rather than just a coincidental thing that comes with your system.
