### ISSUE TITLE
Sometimes ranger will automatically open apps when it closed ?

### ISSUE THREAD

**Issue by fsrzen** [ranger/ranger#2122]
Hi, I've been using ranger as my default file manager for a few days and I've noticed something odd.
When I use some applications (fsearch, udiskie, Intellij IDEA, etc.) and click on the "show in folder" menu provided by these applications, ranger shows the path and it works fine. When I close ranger, firefox (my default browser) automatically opens and shows the same path. Every time this happens, I have to close it over and over again and it drives me crazy. Did I miss something? When I use pcmanfm as my default file manager, everything is ok. I hope that the ranger won’t link and open other applications spontaneously, when I use the function “show in folder” provided by other applications.

I've tried these ways:
1. Download some files with firefox, then click "open containing folder". When ranger is closed, firefox does not automatically open and show the same path. When I use the above mentioned application to display the same file in the folder and close the ranger, firefox will automatically open and display the same path again.
2. Uninstall firefox, install chromium, and after closing ranger, chromium shows the same problem again.

Could anybody please offer me ways to solve the problem ?
#### Runtime Environment
- Operating system and version: archlinux
- WM: i3-gaps
- Terminal emulator and version: rxvt-unicode v9.22
- Python version: 3.8.5
- Ranger version/commit: ranger 1.9.3
- Locale: zh_CN.UTF-8

**Comment by toonn** [comment]
What I think is happening is your program tries to "show folder" in ranger and when you close ranger it thinks it failed, so it falls back to the next appropriate application.
Ranger isn't doing anything here. So you need to figure out why the other programs think it fails, do they expect a specific return code?

**Comment by fsrzen** [comment]
Sorry for my late reply, as I'm quite busy these days.
First of all, thank you very much for providing a new direction. I built a clean system environment for reproducing the problem in a virtual machine. Then I noticed that the problem seems to be here with xdg-open.
Here are the logs of the program output and the related configuration files from those programs that I am using, which I hope will help.

1. /usr/share/applications/ranger.desktop

> [Desktop Entry]
Type=Application
Name=ranger
Comment=Launches the ranger file manager
Icon=utilities-terminal
Terminal=true
Exec=ranger
Categories=ConsoleOnly;System;FileTools;FileManager
MimeType=inode/directory;
Keywords=File;Manager;Browser;Explorer;Launcher;Vi;Vim;Python

2. /home/vmuser/.local/share/applications/ranger.desktop

>[Desktop Entry]
Type=Application
Name=ranger
Comment=Launches the ranger file manager
Icon=utilities-terminal
Terminal=false
Exec=urxvt -e ranger
Categories=ConsoleOnly;System;FileTools;FileManager
MimeType=inode/directory;
Keywords=File;Manager;Browser;Explorer;Launcher;Vi;Vim;Python

3. log

>vmuser@archlinux> fsearch
/usr/bin/xdg-open: line 756: 4336 Segmentation fault     (core dumped) "$command_exec" "$@"
Error: Must run ranger from terminal
/usr/bin/xdg-open: line 881: x-www-browser: command not found
vmuser@archlinux> echo $?
0

**Comment by toonn** [comment]
Hmm, strange, it's as if ranger is *not* being run in a terminal. But both your desktop files seem to ensure it does. Next step is to remove one of the desktop files so you can figure out which way of starting ranger is causing problems.

**Comment by fsrzen** [comment]
1.Here is the log after removing the desktop file from the user directory:
>vmuser@archlinux> fsearch
Error: Must run ranger from terminal
/usr/bin/xdg-open: line 881: x-www-browser: command not found

Ranger wasn't opened but Firefox did.

2.This is the log after removing the desktop file in the /usr/share directory:
>vmuser@archlinux> fsearch
/usr/bin/xdg-open: line 756: 696 Segmentation fault (core dumped) "$command_exec" "$@"
/usr/bin/xdg-open: line 881: x-www-browser: command not found

Ranger was opened. When I close the ranger, firefox was opened.

3. I also try udiskie and IDEA, both of their results are the same.

**Comment by toonn** [comment]
Ok, so with Terminal=true apparently ranger can't detect it's running in a terminal.
And with urxvt -e there's a segmentation fault somehow. Maybe in urxvt?

Next up, find out why a command run with Terminal=true wouldn't be able to detect it's running in a tty, using python's `io.isatty()`. And maybe look into why urxvt would segfault.

**Comment by fsrzen** [comment]
Thanks for the help and I figured it out.
Yes, it's urxvt, actually the perl extension! I didn't know it until I checked syslogs. It turns out that urxvt crashed on exit, but it still can run every program I want it to run.
So, I disabled the perl extension and now everything is working fine.

Add the following to .Xresources and reload to finish:
>URxvt.perl-ext:
URxvt.perl-ext-common:
