### ISSUE TITLE
Env vars in bookmarks

### ISSUE THREAD

**Issue by majkinetor** [ranger/ranger#213]
It would be awesome to support this. For instance, I have ranger on both mac and linux which follow different file system hierarchy, but within my home folder I organize files the same way. 

Unless I am mistaken, and I tried and RTFMed, there is no way to currently do this in bookmarks file.

**Comment by randynobx** [comment]
The idea of over hauling the bookmarks feature has been tossed around a bit, and I am looking into different ideas for it right now. I will definitely keep this in mind. It would be a very handy feature indeed.

**Comment by nfnty** [comment]
You can easily map custom paths in `rc.conf`, e.g. `map cHc cd ~/.config`. And if you need to use environment variables then use `eval`.

**Comment by kdewilde** [comment]
@nfnty could you elaborate on the `eval`?

I would like to have a mapping to go to my projects folder.
But I have that folder in `$PROJECTS_HOME`. how would this look as a bookmark?

**Comment by toonn** [comment]
@kdewilde, `rc.conf` already has examples: `gi eval fm.cd('/run/media/' + os.getenv('USER'))`.
