### ISSUE TITLE
Is there any way to use map and move cursor position like vim?

### ISSUE THREAD

**Issue by zdmgmail** [ranger/ranger#2132]
map x console shell vim %space.cpp

Is there a way let  cursor before .cpp?

like vim 

    nnoremap si :e<space>.cpp<left><left><left><left>

**Comment by toonn** [comment]
Yep, use `console -pN` where N is the position where you want the cursor, like [this keybinding in the default config](https://github.com/ranger/ranger/blob/master/ranger/config/rc.conf#L372).

**Comment by zdmgmail** [comment]
thanks a lot

> Yep, use `console -pN` where N is the position where you want the cursor, like [this keybinding in the default config](https://github.com/ranger/ranger/blob/master/ranger/config/rc.conf#L372).
