### ISSUE TITLE
Is there a way to dynamic set terminal title by path in ranger

### ISSUE THREAD

**Issue by zdmgmail** [ranger/ranger#2137]
when open ranger, it will set terminal title to "ranger"
I want ranger set terminal title by path in ranger , and dynamic change 
so my statusbar can show different  window name by terminal title  
Is there a way to do this?

**Comment by toonn** [comment]
You might be able to kludge something together by rebinding the movement commands with chain and eval to echo the right escape sequence to stdout.

Or you could patch `ranger/gui/ui.py` and add a setting to toggle the behavior and submit a PR : )

**Comment by chu4ng** [comment]
When path changes, windows title change too for me.

May be you need look the **update_title** option in rc.conf file?

**Comment by toonn** [comment]
Yeah, you're right. I didn't notice because I ran ranger in tmux. So this is an issue with your terminal or terminal multiplexer, not ranger.
