### ISSUE TITLE
diff : cannot fork inside subshell

### ISSUE THREAD

**Issue by aureooms** [ranger/ranger#214]
If I try to run `diff` in a subshell spawned with key binding `S` I get the following error,

```
/usr/bin/sensible-pager: 3: /usr/bin/sensible-pager: Cannot fork
```

I get the same error with `git diff`.

**Comment by hut** [comment]
Can't reproduce that. What OS, python version and ranger version are you using? Is anything else happening that might be suspicious?

**Comment by aureooms** [comment]
Ubuntu 14.10. Unfortunately I cannot tell you more about python and ranger version for the moment as I'm not using this computer right now.

I checked on my current computer with Ubuntu 12.04, Python 2.7.3 and ranger 1.5.2 (stable) and I cannot reproduce the issue.

**Comment by aureooms** [comment]
I was able to reproduce it with the following configuration,

  - **OS** Ubuntu 14.10 x64
  - **Kernel** 3.16.0-23-generic
  - **Window Manager** i3
  - **Shell** bash
  - **Terminal** terminator

**Comment by hut** [comment]
What command exactly causes this issue?

**Comment by aureooms** [comment]
open `ranger` inside terminator
`shift+S`
`git diff`(or `diff fileA fileB`)

Also, `git status` seems to be extremely slow but eventually completes.

**Comment by Wh0p** [comment]
I can reproduce as well on 
 * **OS** Ubuntu 15.10
 * **Kernel** 4.2.0-38-generic
 * **Window Manager** i3 (as well as unity)
 * **Shell** bash
 * **Terminal** gnome-terminal, xterm
 * **git version** 2.5.0

in ranger `:shell` or `:shell -f` 
`git diff` produces the same error
`git status` works well though

**Comment by johnoneil** [comment]
At least for git I was able to fix the issues listed (and issues with git grep) by explicitly specifying a pager in my ~/.gitconfig
```
[core]
     pager = less
```

**Comment by sim590** [comment]
I didn't have that problem on ArchLinux. I've just started using debian a few days ago and I have noticed this bug.

If I can add a little bit to the list of symptoms: I can reproduce this doing
```
:shell urxvt &
```
The issue occurs in the shell inside the new urxvt window.

Ranger version
```
ranger-stable 1.7.1

Python 2.7.13 (default, Dec 18 2016, 20:19:42) 
[GCC 6.2.1 20161215]
```

Git version
```
git version 2.11.0
```

**Comment by sim590** [comment]
I want to point out that this will also affect the `man` program. It will be unusable.
