### ISSUE TITLE
is it possible to show pictures on terminal(ms) in wsl2 environment(maybe it is troublesome)

### ISSUE THREAD

**Issue by howin98** [ranger/ranger#2146]
#### Runtime Environment

- Operating system and version: Debian 10 buster(x86_64 Linux 4.19.128-microsoft-standard)
- Terminal emulator and version: Windows Terminal 1.3.xxxx
- Python version: Python version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
- Ranger version/commit: ranger version: ranger 1.9.2
- Locale: en_US.UTF-8

#### Current Behavior
w3m-img settled and it doesn't work

#### Expected Behavior
show picture on MS Terminal(maybe via VcXsrv tools)

#### Possible Solutions
maybe via VcXsrv tools

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```
just as the title
```

**Comment by toonn** [comment]
I know w3m works with cygwin. I think the kitty, terminology and urxvt methods would work if you can run those with WSL. And I also seem to recall ueberzug works with WSL.

**Comment by howin98** [comment]
https://github.com/seebye/ueberzug/issues/87
it is disappointed that ueberzug doesn't have plan to support wsl2 with windows terminal and i think that launch terminal emulator in vcxsrv is the most direct solution.
