### ISSUE TITLE
Pygmentize true color highlight

### ISSUE THREAD

**Issue by RouNNdeL** [ranger/ranger#2148]
#### Runtime Environment

- Operating system and version: Linux 5.9.1-arch1-1
- Terminal emulator and version: Termite 15.3
- Python version: 3.8.6
- Ranger version/commit: 1.9.3 (official Arch repo)
- Locale: en_US.UTF-8

#### Current Behavior
When setting the pygmentize format to true color (`pygmentize -f 16m`) in `scope.sh` it renders incorrectly. 
Example:

![image](https://user-images.githubusercontent.com/22538735/98825551-e8f1eb80-2434-11eb-9cab-53bccf9022ff.png)

#### Expected Behavior
Running pygmentize in the same terminal window after closing **ranger**:

![image](https://user-images.githubusercontent.com/22538735/98825706-19398a00-2435-11eb-9aea-f160f61119b0.png)

#### Context

I was trying to get more accurate colors in previews using the text highlight feature.

#### Possible Solutions
It's possible to stick with 256 colors but that makes them very inaccurate.

#### Steps to reproduce
1. Comment out the automatic terminal detection in `scope.sh` 
2. Mannually set `pygmentize_format='16m'`
3. Preview a file that can be highlighted

**Comment by toonn** [comment]
This is a python `curses` limitation. Upstream ncurses supports truecolor but the python library does not.
