### ISSUE TITLE
ranger not open in alacritty

### ISSUE THREAD

**Issue by onthecouch** [ranger/ranger#2153]
hi, so I recently updating my arch linux. but somehow my ranger doesnt open with alacritty terminal in i3 windows manager. While im using KDE plasma its working fine. any help?

#### Runtime Environment
ranger 1.9.3
python: 3.8.6
locale: en_US.UTF-8

![2020-11-15_19-17](https://user-images.githubusercontent.com/63456026/99184690-6d1ada80-2777-11eb-88cc-78bd15bc537a.jpg)

**Comment by toonn** [comment]
Are you launching it through the `.desktop` file? I think you'll have to configure `xdg-open` to use alacritty rather than XTerm.

**Comment by onthecouch** [comment]
dang, yeah my bad. I totally forgot about that. I'm launched it thru dmenu not terminal. thank you for reminding me about `.desktop` file

**Comment by toonn** [comment]
No problem. Btw, with simple issues like these you can usually get more eyes on the issue over on reddit, r/ranger.
