### ISSUE TITLE
No such file or directory on try open .php file

### ISSUE THREAD

**Issue by cristoferfb** [ranger/ranger#2154]
#### Runtime Environment

- Operating system and version: Alpine Linux 3.11 (WSL Windows 10)
- Terminal emulator and version:  ConEmu 191012
- Python version: 3.8.2
- Ranger version/commit: 1.9.2-r1
- Locale: en_US.UTF-8

#### Current Behavior
Error on try to open .php file, no problem on open other files like .sh or .html
`[Errno 2] No such file or directory: 'file'`

#### Expected Behavior
Open .php file in nvim

#### Steps to reproduce
1. navigate to a .php file
2. press r and type 'nvim'
3. `[Errno 2] No such file or directory: 'file'`

**Comment by toonn** [comment]
I can't reproduce this. What if you try `vim` or `nano` or another editor? And why are you explicitly using `:open_with nvim` rather than configuring nvim as your editor?

**Comment by cristoferfb** [comment]
I have the same behaviour using any other editor with `:open_with` or directly pressing `enter` (I have the default `rifle.conf`)

**Comment by toonn** [comment]
How about `:shell nvim %s`?

**Comment by cristoferfb** [comment]
That works ¿Any way to set it as the default behaviour?

**Comment by toonn** [comment]
Check if `E` has that behavior. But I don't see any reason it wouldn't work via rifle. Unless you're not explicitly choosing nvim (there's a bug where the numbering of the open_with list is off).

**Comment by cristoferfb** [comment]
I have the same error using `E`

**Comment by toonn** [comment]
AH, I think you're missing the ubiquitous `file(1)` utility! That's pretty much ranger's only hard dependency.

**Comment by cristoferfb** [comment]
Yeah! solved with `sudo apk add file`. Thanks :)

**Comment by toonn** [comment]
Sorry this took so long to realize. The subreddit r/ranger probably has more windows users who might spot issues quicker because they've been through them.
