### ISSUE TITLE
Delete does nothing

### ISSUE THREAD

**Issue by FalconChrome** [ranger/ranger#2159]
#### Runtime Environment
- Operating system and version: archlinux 5.9.9-arch1-1
- Terminal emulator and version: zsh 5.8 (x86_64-pc-linux-gnu)
- Python version: 3.8.6 (default, Sep 30 2020, 04:00:38) [GCC 10.2.0]
- Ranger version/commit: ranger 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
I just want to delete a file while working in ranger. But \<delete\> key does nothing. It doesn't even cut like dd does.
#### Context

I see no way how to implement deleting anything; I don't know what should it be like in config if I wished to map it to some shortcut key. I think it should work by itself because I don't see anybody with same problem.

**Comment by toonn** [comment]
[The map for <DELETE> is not enabled by default](https://github.com/ranger/ranger/blob/master/ranger/config/rc.conf#L423) this is to avoid accidental deletions when people have disabled `confirm_on_delete`.
`<F8>` and `dD` are available by default.

Note that there's also support for trashing files via rifle.
