### ISSUE TITLE
Executing a ranger command instead of opening files

### ISSUE THREAD

**Issue by paddybu** [ranger/ranger#2164]
**Is it possible to configure rifle so that it executes a (custom) ranger command when attempting to open files of a specific type?**

Context is that I am currently figuring out how to use [`avfs`](https://sourceforge.net/projects/avf/) to browse archives in the same way as normal directories in ranger. Basically, `avfs` creates a virtual copy of the filesystem in `~/.avfs/` and to access a zip archive you just visit `~/.avfs/home/user/path/to/archive.zip#/`.

To achieve this in ranger I created a custom command that switches to the `avfs` path of the selected archive file. It works as intended, but it would be much more convenient if one could switch to `avfs` automatically if opening an archive file (by pressing `l` or `Enter`).

**Comment by toonn** [comment]
I don't think you need rifle even. I'd change the keybind to something like `eval if zip then my_command else rifle`.

**Comment by paddybu** [comment]
Thank you for your answer. Solved by replacing `map <RIGHT>    move right=1` by 

`map <RIGHT>    eval fm.execute_console('avfs_open') if fm.thisfile.extension in ['zip', 'tar'] else fm.move(right=1)`

in `rc.conf`

**Comment by toonn** [comment]
Depending on which archives avfs can deal with you could also go by MIME type or even simply check the container property which is true if the extension is any of these:
```
('7z', 'ace', 'ar', 'arc', 'bz', 'bz2', 'cab', 'cpio',
 'cpt', 'deb', 'dgc', 'dmg', 'gz', 'iso', 'jar', 'msi',
 'pkg', 'rar', 'shar', 'tar', 'tbz', 'tgz', 'txz',
 'xar', 'xpi', 'xz', 'zip')
```
