### ISSUE TITLE
ueberzug processes are not being killed

### ISSUE THREAD

**Issue by jedi2610** [ranger/ranger#2172]
#### Runtime Environment
- Operating system and version: Arch linux
- Terminal emulator and version: alacritty(0.6.0)
- Python version: Python version: 3.9.0 (default, Oct  7 2020, 23:09:01) [GCC 10.2.0]
- Ranger version/commit: ranger 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
ranger fails to kill the running ueberzug preview process after updating python from 3.8 to 3.9. this causes a memory hog and ueberzug fills the htop listing and it doesn't kill the process even after killing the terminal

#### Expected Behavior
the ueberzug processes should be killed while quitting ranger

#### Context
this is happening every time i try to preview an image or even a video file. each image's preview process in not getting killed
i don't think this is an ueberzug issue and i guess it has to do with ranger. can provide more info if needed.

#### Steps to reproduce
1. turn on previews
2. try to preview an image or video file
3. on python version 3.9

**Comment by MRAAGH** [comment]
I have encountered this exact issue on:

-     Operating system and version: Arch linux
-     Terminal emulator and version: rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
-     Python version: Python version: 3.9.0 (default, Oct 7 2020, 23:09:01) [GCC 10.2.0]
-     Ranger version/commit: ranger 1.9.3
-     Locale: en_US.UTF-8

**Comment by jedi2610** [comment]
@MRAAGH did you also encounter this issue after updating python from version 3.8 to 3.9?

**Comment by MRAAGH** [comment]
@jedi2610 Yes, that is correct. I updated python yesterday (3.8.6-1 -> 3.9.0-1) and started noticing this issue later that day.
These packages were also updated at the same time: https://gist.github.com/MRAAGH/3bc096c2fa3cc8f368aa494917fc9bcf

**Comment by jedi2610** [comment]
prolly @toonn  should take a look at this issue

**Comment by FollieHiyuki** [comment]
This is a known issue I believe as in last comment of #1874

**Comment by jedi2610** [comment]
@FollieHiyuki i guess. #1874  just looks similar to this issue just with another bug to it

**Comment by jedi2610** [comment]
there was an update for ueberzug, from pip, yesterday. after updating ueberzug the problem was solved. so i guess it was an ueberzug issue all along. but the thing is ranger is taking like a second or so to close ranger if there is preview on the screen

**Comment by FollieHiyuki** [comment]
Yes `ueberzug` fixed the problem with commit [ff5ff63](https://github.com/seebye/ueberzug/commit/ff5ff632ba51cfa99a9d8d624886eefe622b1de7)

**Comment by MRAAGH** [comment]
Images no longer persist, but as @jedi2610 said, ranger takes an unusually long time to close if there is a preview on screen. The same thing happens if trying to spawn a shell with shift+S. The same thing happens if there is no preview on screen but there was one earlier in the Ranger session.

### Steps to reproduce:
1. make `ueberzug` your image preview method
2. run the command `ranger`
3. preview an image
4. (optional: focus a different file, so image preview is no longer shown)
5. press `q` or `shift+s`
6. notice a delay before this action is executed

### Environment:

- Operating system and version: Arch linux
- Terminal emulator and version: rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
- Python version: Python version: 3.9.0 (default, Oct 7 2020, 23:09:01) [GCC 10.2.0]
- Ranger version/commit: ranger 1.9.3
- Locale: en_US.UTF-8
- Ueberzug version: 18.1.7

**Comment by toonn** [comment]
And this delay didn't happen with older python and ueberzug versions?

**Comment by MRAAGH** [comment]
> And this delay didn't happen with older python and ueberzug versions?

This started happening at the same time as the issue described previously.

**Comment by toonn** [comment]
@seebye, do you have any clue as to why this delay may be happening?

**Comment by seebye** [comment]
@toonn I think that's unrelated to ranger, so you can close the issue.

**Comment by MRAAGH** [comment]
Would be nice to figure out where it came from, though

**Comment by toonn** [comment]
I'm closing this. Discussion can keep going though, a mention of the problem once found would be nice. Is there an ueberzug issue report we can link this one to, @seebye?

**Comment by seebye** [comment]
In python3.9 a few functions (which were used to shutdown asyncio) were moved to other modules.  
It should be fixed in the master branch.
I will release a new version soon.

**Comment by jedi2610** [comment]
there was an update for ueberzug today and the issue was fixed so i'm closing this issue thanks @seebye @toonn
