### ISSUE TITLE
Ueberzug fails to open images 

### ISSUE THREAD

**Issue by siduck76** [ranger/ranger#2179]
![d](https://user-images.githubusercontent.com/59060246/101428723-4ccdde00-3927-11eb-859e-8437309b5465.png)
 Ive been using ranger + ueberzug to preview images for a while but ueberzug now doesnt open the image now and shows these errors :

![image](https://user-images.githubusercontent.com/59060246/101426603-51909300-3923-11eb-913d-c979cecb0ffa.png)

**Comment by siduck76** [comment]
nvm it got fixed , I removed the attrs module installed with pip and re-installed attrs from my distros repo

**Comment by sett6** [comment]
> nvm it got fixed , I removed the attrs module installed with pip and re-installed attrs from my distros repo

I have a similar problem. How did you solve it?
![image](https://user-images.githubusercontent.com/75558384/213372365-79efc72f-e4f9-4bc7-932a-caeb3bf70564.png)
![image](https://user-images.githubusercontent.com/75558384/213372425-5ab6b2f4-206f-42d7-8a66-dc979a534089.png)

**Comment by siduck** [comment]
> > nvm it got fixed , I removed the attrs module installed with pip and re-installed attrs from my distros repo
> 
> I have a similar problem. How did you solve it? ![image](https://user-images.githubusercontent.com/75558384/213372365-79efc72f-e4f9-4bc7-932a-caeb3bf70564.png) ![image](https://user-images.githubusercontent.com/75558384/213372425-5ab6b2f4-206f-42d7-8a66-dc979a534089.png)

try reinstalling ueberzug

**Comment by sett6** [comment]
> > > nvm it got fixed , I removed the attrs module installed with pip and re-installed attrs from my distros repo
> > 
> > 
> > I have a similar problem. How did you solve it? ![image](https://user-images.githubusercontent.com/75558384/213372365-79efc72f-e4f9-4bc7-932a-caeb3bf70564.png) ![image](https://user-images.githubusercontent.com/75558384/213372425-5ab6b2f4-206f-42d7-8a66-dc979a534089.png)
> 
> try reinstalling ueberzug

I have reinstalled it, but it doesn't work

**Comment by siduck** [comment]
> > > > nvm it got fixed , I removed the attrs module installed with pip and re-installed attrs from my distros repo
> > > 
> > > 
> > > I have a similar problem. How did you solve it? ![image](https://user-images.githubusercontent.com/75558384/213372365-79efc72f-e4f9-4bc7-932a-caeb3bf70564.png) ![image](https://user-images.githubusercontent.com/75558384/213372425-5ab6b2f4-206f-42d7-8a66-dc979a534089.png)
> > 
> > 
> > try reinstalling ueberzug
> 
> I have reinstalled it, but it doesn't work

idk then, i used it from arch repos and it works fine
