### ISSUE TITLE
zsh aliases not working

### ISSUE THREAD

**Issue by indeedwatson** [ranger/ranger#2185]
I have an `.aliases` file that I source from `zshrc`. For example `alias py='python'`.

However when using ranger's command line, nothing happens, and when I exit ranger, I see displayed in the terminal `zsh:1: command not found: py`.

Needless to say the aliases work on the terminal itself.

As a side note, why is that message not displayed within ranger somehow? Should ranger not give feedback when it fails to find a command the user inputted? Let me know if I should open a separate issue for this.

ranger version: ranger-master 
Python version: 3.9.1 (default, Dec 13 2020, 11:55:53) [GCC 10.2.0]
Locale: en_US.UTF-8
Arch linux

**Comment by vifon** [comment]
`zshrc` is only loaded by the interactive shells, so it's not loaded in a shell ranger uses to launch commands. If you insist on using aliases, you can use `zshenv` instead, though I urge you to consider converting them into standalone scripts if they don't need to run in the same shell. In short: not a `ranger` bug.

The message is visible if you run `:shell -w`. It might be a good idea for `ranger` to check the exit code and show the output if it's non-zero. I'll check back later how much trouble it would be to implement it.

**Comment by indeedwatson** [comment]
I didn't think it was actually a bug, I figured it was something beyond my knowledge, thank you for the explanation. I created `.zshenv` and simply sourced the `.aliases` file from there (I don't see the value in having aliases as individual scripts, I have enough of those).

> It might be a good idea for ranger to check the exit code and show the output if it's non-zero. I'll check back later how much trouble it would be to implement it.

That would be great, like how vim displays messages at the bottom.
