### ISSUE TITLE
shell -t returns (eval):1: command not found: xterm with both st and urxvt

### ISSUE THREAD

**Issue by prosoitos** [ranger/ranger#2186]
#### Runtime Environment
OS: 5.9.14-arch1-1
st: 0.8.4
ranger: 1.9.3-3
Python: 3.9.1-1

#### Current Behavior
I used to be able to run `shell -t <command>` without issue. But for the past few months, whenever I try it I get:
```sh
(eval):1: command not found: xterm
```
with both st and urxvt.

So I resorted to using `shell <command>` instead but it is a lot less convenient.

`export TERMCMD=st-256color` did not help.

Thanks!

**Comment by chu4ng** [comment]
Could you run ranger with "-c" and "-d" options?

**Comment by prosoitos** [comment]
I get the same behaviour when I run `ranger -cd`.

**Comment by toonn** [comment]
I doubt your st binary is called st-256color, try `TERMCMD=st`.

**Comment by prosoitos** [comment]
Same behaviour.

**Comment by prosoitos** [comment]
**With urxvt:**

I tried setting the variable `TERMCMD` to `urxvt`, `/usr/bin/urxvt`, `urxvt-256color`... nothing worked.

**With st:**

I tried similar values for `TERMCMD` (including `st`) and nothing works either.

I finally found something that works, but it is not satisfactory:

`TERM=st` does work.

Now, since st doesn't display image preview properly (though, I will try ueberzug and see if that fixes that), I actually switched to using urxvt with ranger. And I don't know how to set `TERM` to something that will work with `urxvt` (`TERM=urxvt` returns `can't find terminal definition for urxvt`).

**Comment by prosoitos** [comment]
Note: as I mentioned in my first post, `shell -t` used to work just fine until a number of months ago. If it helps, I could dig into my config history which is under version control to pinpoint when I had to switch to `shell`. That might help find out what change created this issue. So let me know if you'd like me to dig that out.

**Comment by prosoitos** [comment]
From the ranger man page:

> The terminal program name for the "t" flag is taken from the environment variable $TERMCMD.  If it doesn't exist, it tries to extract it from $TERM and uses "xterm" as a fallback if that fails.

It is weird that ranger is able to extract `st` from `TERM` but will not accept `st` as the value for `TERMCMD`...

**Comment by prosoitos** [comment]
AH! Actually, `export TERMCMD=st` **does** work.

It doesn't work if I set `TERMCMD=st` and then run ranger in the same terminal session (which is weird), but it works if I export the variable.

**Comment by prosoitos** [comment]
And I can confirm that `TERMCMD=urxvt` also works (with `export` in my case because of my workaround).

Thanks again @toonn for your quick and useful help!!

**Comment by toonn** [comment]
The weird thing is it should work for `st-256color` just the same as you can [see here](https://github.com/ranger/ranger/blob/master/ranger/ext/rifle.py#L382).

**Comment by prosoitos** [comment]
Weird, indeed...

Again: it used to work just fine and suddenly stopped working (at least on my system) with both `st-256color` and `urxvt-256color` a number of months ago. I didn't change anything in my config then, so something in the ranger code broke that (at least on my system).
