### ISSUE TITLE
Remove "open_all_images" limit

### ISSUE THREAD

**Issue by daankata** [ranger/ranger#2192]
I am not able to open more than 120 images in a single directory. Before I didn't have a problem opening any large number (>400) of images in a directory. I have more than enough RAM. I am finding this very frustrating so I have been trying to revert it on my system.

I saw that the change happened in pull [1490](https://github.com/ranger/ranger/pull/1490/commits). I tried reverting actions.py to the previous one but with no success, as it still doesn't open anything.

**Comment by toonn** [comment]
Hmm, I don't see how that change could have disabled it. All that did was wrap the execute calls to catch an exception in case the argument list is too long. So all it does is make ranger not crash when there's too many images to open all at once, falling back to only opening one image.

I suspect you're just running into the case that prompted this fix, having so many images in a directory that they can't all be passed as arguments.

**Comment by daankata** [comment]
> Hmm, I don't see how that change could have disabled it. All that did was wrap the execute calls to catch an exception in case the argument list is too long. So all it does is make ranger not crash when there's too many images to open all at once, falling back to only opening one image.
> 
> I suspect you're just running into the case that prompted this fix, having so many images in a directory that they can't all be passed as arguments.

Actually, yes, you are right. I just tested opening a directory with 300 images from the terminal with feh and got `Error: too many arguments`. What is my alternative then? Are you able to open large number of images in ranger? Maybe I should try changing the image opener with another program.

**Comment by daankata** [comment]
I changed the 'feh' setting in rifle.conf and modified the arguments by adding a recursive and opening all images in the current directory and my problem was gone. I just tested it with more than 400 images and I didn't have any problem opening all.
`mime ^image, has feh,       X, flag f, !ext gif = feh -r --scale-down -d "./"`

Thank you!

**Comment by toonn** [comment]
Yes, that's much better. `open_all_images` is a hack which just works by pretending all the images were selected. To open a selection of images you have to pass them as arguments, if you always passed the directory you might open more than the selected images. The only way around this would be to pipe the paths into the program but that requires the receiving program to support this, mpv and vim do for example. This might be a possible fix for the `open_all_images` hack but someone who actually uses it would have to contribute such a fix.
