### ISSUE TITLE
Freeze on accessin unaccessible SSHFS mount points

### ISSUE THREAD

**Issue by danbst** [ranger/ranger#2193]
#### Runtime Environment

- Operating system and version: Nixos 20.09
- Terminal emulator and version: gnome-terminal
- Python version: 3.8.3
- Ranger version/commit: 1.9.3
- Locale: en-US

#### Current Behavior

I have an automount mountpoint for a remote SSHFS filesystem. When I access it using rancher, the automount process starts, however mount doesn't work (which is expected, remote server is not accessible), and ranger freezes (apparently waiting for completion). Unfortunately, it never unfreezes and there is no way to unstuck it. Ctrl-C or Esc also doesn't help.

#### Expected Behavior

The Ctrl-C or Esc should kill the background process which blocks UI.

**Comment by toonn** [comment]
There's open issues on this so I'm closing this one. It'd be great if you could find one to #mention though, to link as many issue reports so people searching are more likely to find what they're looking for.

**Comment by danbst** [comment]
@toonn I guess you talk about this issue https://github.com/ranger/ranger/issues/2027

Though I do not experience "slowishness", it is complete freeze with no way of getting out. So this issue is not about fixing slowness, but about Ctrl-C to interrupt all the synchronous processes.

**Comment by toonn** [comment]
There may be other relevant issues.
