### ISSUE TITLE
How can I add new context or otherwise colorcode specific filetypes?

### ISSUE THREAD

**Issue by waynongithub** [ranger/ranger#2194]
Hi, I'm sorry but I can't find the relevant documentation on how to add a new context to colorschemes. Basically, I want ranger to display files in a color based on the file extension. Colorschemes seem to apply a color to a "context", but I can't figure out where those contexts are defined or how I can add a context. Can anyone point me in the right direction? Thanks.

**Comment by toonn** [comment]
You should take at look at the LS_COLORS colorscheme PR on our ranger/colorschemes repo.

**Comment by waynongithub** [comment]
thanks!

**Comment by toonn** [comment]
If that helped I'll close this issue. Feel free to hop into #ranger@freenode for questions related to this. Or a post on the r/ranger subreddit. A post detailing how to do this would probably be appreciated by many users : )

**Comment by user1180** [comment]
> You should take at look at the LS_COLORS colorscheme PR on our ranger/colorschemes repo.

Where would I find that? I checked [here](https://github.com/ranger/colorschemes) already, but the only apparent colorscheme is zenburn.py

I also cloned the git repo is per the instructions in the Readme, but again, zenburn.py is the only colorscheme available. 

Am I missing something or have all other colorschemes been removed?

**Comment by toonn** [comment]
It's an unmerged *PR*.
