### ISSUE TITLE
Ranger crashes if tmux isn't running

### ISSUE THREAD

**Issue by lverweijen** [ranger/ranger#2195]
#### Runtime Environment

~% ranger --version
ranger version: ranger 1.9.3
Python version: 3.9.1 (default, Dec  8 2020, 07:51:42) [GCC 10.2.0]
Locale: en_DK.UTF-8
~% tmux -V
tmux 3.1c
~% cat /etc/issue
Debian GNU/Linux bullseye/sid \n \l
~% echo $TERM
st-256color
~% echo $TMUX
~% tmux
~% echo $TMUX
/tmp/tmux-1000/default,53624,0

#### Steps to reproduce

- Make sure tmux isn't running (not even in another shell)
- Launch ranger

#### Current Behavior

~/Downloads% ranger
ranger version: ranger 1.9.3
Python version: 3.9.1 (default, Dec  8 2020, 07:51:42) [GCC 10.2.0]
Locale: en_DK.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 132, in initialize
    self.ui.initialize()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 127, in initialize
    self.handle_multiplexer()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 476, in handle_multiplexer
    tmux_allow_rename = check_output(
  File "/usr/lib/python3/dist-packages/ranger/ext/spawn.py", line 41, in check_output
    raise error
subprocess.CalledProcessError: Command '['tmux', 'show-window-options', '-v', 'allow-rename']' returned non-zero exit status 1.

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
~/Downloads% echo $TMUX

~/Downloads% echo "R${TMUX}R"
RR

~/Downloads% ranger --clean
ranger version: ranger 1.9.3
Python version: 3.9.1 (default, Dec  8 2020, 07:51:42) [GCC 10.2.0]
Locale: en_DK.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
...

#### Expected Behavior

Ranger should launch without error

**Comment by lverweijen** [comment]
I found a more reliable way to reproduce:

- Open terminal
- Start tmux
- Open new terminal window from tmux
- Close tmux
- In new terminal window "start ranger"

I suspect the problem is the following:

```
~% python3 -c 'import os; print("TMUX" in os.environ)'
True
```

Probable solution is to not just check if variable exists, but whether it's empty.

**Comment by jbrains** [comment]
If I run **screen**, then ranger doesn't crash when it starts.

**Comment by toonn** [comment]
Could you try testing the master branch? I can't reproduce this anymore.

**Comment by jbrains** [comment]
Sadly, I can't reproduce this any more, either. :shrug:

**Comment by toonn** [comment]
That's great, means it's fixed already : )
