### ISSUE TITLE
 In Urxvt the background-image disappears after I exit ranger

### ISSUE THREAD

**Issue by StandardNerd** [ranger/ranger#2198]
#### Runtime Environment

- Operating system and version: Ubuntu 20.04
- Terminal emulator and version: Urxvt, v9.22
- Python version: 3.8.5
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
I use a pixmap (PNG-Image) as background in Urxvt. After I exit ranger the pixmap disappears and no background-image is shown anymore.

#### Expected Behavior
The background image is still shown in Urxvt after exiting Ranger.

#### Steps to reproduce
1. set a background image in Urxvt 
2. start ranger
3. quit ranger

**Comment by toonn** [comment]
Do you use the urxvt image preview method?

**Comment by StandardNerd** [comment]
no, I don't use urxvt image preview method (at least I don't set it explicitly in .Xresource)

**Comment by toonn** [comment]
Why would you set it in `.Xresource`? It's a ranger configuration. The urxvt image previewing method uses urxvt's image background feature. You might be able to figure out a way to reload the background image upon quitting ranger if this is the issue.

**Comment by StandardNerd** [comment]
> Why would you set it in `.Xresource`? It's a ranger configuration. 

I did set my Urxvt background image in .Xresource :
`URxvt.backgroundPixmap: ` 

I'm not sure what you mean by "It's a ranger configuration". Do I have to set a background-image in ranger, too?

**Comment by toonn** [comment]
Ranger supports image previews. For urxvt specifically it supports using its background image feature to display these previews. Do you have `set preview_images_method urxvt` in your `~/.config/ranger/rc.conf`?
If you don't have this enabled there's no reason for ranger to affect the urxvt background.

**Comment by StandardNerd** [comment]
Yes, preview_images_method was set indeed! I removed it and ranger doesn't remove the background image in URxvt anymore, thanks a lot!
