### ISSUE TITLE
Displaying "Subject: " and "From: " header lines of email text files in the right-hand panel?

### ISSUE THREAD

**Issue by philiprhoades** [ranger/ranger#2202]
#### Runtime Environment

- Operating system and version: 
Fedora 33 x86_64

- Terminal emulator and version: 
kitty-0.19.3-1.fc33.x86_64

- Python version: 
python3-3.9.1-1.fc33.x86_64

- Ranger version/commit: 
ranger-1.9.3-3.fc33.noarch

- Locale: 
LANG=en_AU.UTF-8
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=C

#### Current Behavior
Doesn't work

#### Expected Behavior
When viewing a single email file (Maildir format), it would be great to have the "Subject: " and "From: " header fields / lines displayed in the right-hand panel - this would allow easier tagging and bulk moving etc of files.

#### Context

It is a new, suggested enhancement to ranger so it hasn't affected me yet . .

#### Possible Solutions
Macro?  Code change?

**Comment by toonn** [comment]
Any CLI tools which produce useful email previews?

**Comment by philiprhoades** [comment]
toonn,


On 2021-01-01 02:33, toonn wrote:
> Any CLI tools which produce useful email previews?


Ah . . well this would do what I want:

   grep -e "Subject: " -e "From: " {}

but how to replace the "{}" with the file name as I cursor down each 
file?

Thanks,

Phil.
-- 
Philip Rhoades

PO Box 896
Cowra  NSW  2794
Australia
E-mail:  phil@pricom.com.au

**Comment by toonn** [comment]
@philiprhoades, you'd add a case to `scope.sh` probably in `handle_extension`, something like:
```
emlx)
    grep -e "Subject: " -e "From: " -- "${FILE_PATH}" && exit 5
    exit 1;;
```

**Comment by philiprhoades** [comment]
toonn,


On 2021-01-03 01:48, toonn wrote:
> @philiprhoades [1], you'd add a case to scope.sh probably in
> handle_extension, something like:
> 
> emlx)
>     grep -e "Subject: " -e "From: " -- "${FILE_PATH}" && exit 5
>     exit 1;;


Hmm . . no action yet - for file:

1594606798.M363273P2360043.prix.pricom.com.au,S=76234,W=77549:2,

- I still get:

----- File Type Classification -----
RFC 822 mail, UTF-8 Unicode text, with very long lines

Doing this:

file ~/Maildir/.0_arlo/cur/*6798*

- I get:

/home/phr/Maildir/.0_arlo/cur/1594606798.M363273P2360043.prix.pricom.com.au,S=76234,W=77549:2,: 
RFC 822 mail, UTF-8 Unicode text, with very long lines

Thanks,

Phil.
-- 
Philip Rhoades

PO Box 896
Cowra  NSW  2794
Australia
E-mail:  phil@pricom.com.au

**Comment by toonn** [comment]
Ah, it's because the file doesn't have an extension. That complicates matters.

Check if `file` reports a MIME type for these files, `file --mimetype path/to/an/email`. If it does you can move that case to the `handle_mime` function, replacing `emlx` with the appropriate MIME type.

If that doesn't work you can try creating a separate file "mailpreview.sh":
```
grep -e "Subject: " -e "From: " -- "${FILE_PATH}" && exit 5
exit 1
```

Then in your `rc.conf` (or while running ranger to test): `setlocal path=~/Maildir preview_script ~/mailpreview.sh`
With the correct paths of course.
This way that script should be used to generate previews for all the files under that directory.

**Comment by philiprhoades** [comment]
toonn,


On 2021-01-03 03:55, toonn wrote:
> Ah, it's because the file doesn't have an extension. That complicates
> matters.
> 
> Check if file reports a MIME type for these files, file --mimetype
> path/to/an/email.


No "--mimetype" with Fedora 33 x86_64 "file" command - I tried 
installing a perl "mimetype" but that doesn't give any more info than 
the file command (RFC 822 mail, ASCII text, with very long lines).


> If it does you can move that case to the handle_mime
> function, replacing emlx with the appropriate MIME type.


Unfortunately that didn't work . .


> If that doesn't work you can try creating a separate file
> "mailpreview.sh":
> 
> grep -e "Subject: " -e "From: " -- "${FILE_PATH}" && exit 5
> exit 1
> 
> Then in your rc.conf (or while running ranger to test): setlocal
> path=~/Maildir preview_script ~/mailpreview.sh
> With the correct paths of course.


I used:

setlocal path=~/Maildir preview_script ~/.config/ranger/mailpreview.sh


> This way that script should be used to generate previews for all the
> files under that directory.


Odd . . it didn't work but the the right-hand pane disappeared! (and the 
middle pane expanded to fill up almost all the vacated space . .).

So the script is having some effect - just not the one we want . .

Thanks,

Phil.
-- 
Philip Rhoades

PO Box 896
Cowra  NSW  2794
Australia
E-mail:  phil@pricom.com.au

**Comment by toonn** [comment]
Ah, it's `--mime-type`.

**Comment by toonn** [comment]
Got it to work, you need to add a shebang, e.g., `#!/bin/sh` and make sure the script is executable: `chmod +x mailpreview.sh`.

**Comment by philiprhoades** [comment]
Toonn,


On 2021-01-03 04:48, toonn wrote:
> Ah, it's --mime-type.


Ah right - but still no more information than before:

message/rfc822

P.
-- 
Philip Rhoades

PO Box 896
Cowra  NSW  2794
Australia
E-mail:  phil@pricom.com.au

**Comment by philiprhoades** [comment]
toonn,


On 2021-01-03 05:00, toonn wrote:
> Got it to work, you need to add a shebang, e.g., #!/bin/sh and make
> sure the script is executable: chmod +x mailpreview.sh.


I had already done that . . you are not getting the missing right pane 
and the script is doing what it is supposed to?

P.
-- 
Philip Rhoades

PO Box 896
Cowra  NSW  2794
Australia
E-mail:  phil@pricom.com.au

**Comment by toonn** [comment]
Oh, but that sounds like a MIME type. Move the case to the `handle_mime` function in `scope.sh` and change the `emlx)` to `message/rfc822)`.

**Comment by philiprhoades** [comment]
toonn,


On 2021-01-03 05:17, toonn wrote:
> Oh, but that sounds like a MIME type. Move the case to the handle_mime
> function in scope.sh and change the emlx) to message/rfc822).


Yes!  That's it! - many thanks!

The only trivial annoyance was that even though I added "^" to the grep 
string, it was still finding more occurances of "^Subject: " in the body 
of some emails . . so I had to change the grep line to:

   grep -e "^Subject: " -e "^From: " -- "${FILE_PATH}" | head -2 && exit 
5$

- now it is perfect!

Regards,

Phil.
-- 
Philip Rhoades

PO Box 896
Cowra  NSW  2794
Australia
E-mail:  phil@pricom.com.au

**Comment by philiprhoades** [comment]
I also used that mime type for an addition to the text editor section in 
rifle.conf .


On 2021-01-03 05:58, Philip Rhoades wrote:
> toonn,
> 
> 
> On 2021-01-03 05:17, toonn wrote:
>> Oh, but that sounds like a MIME type. Move the case to the handle_mime
>> function in scope.sh and change the emlx) to message/rfc822).
> 
> 
> Yes!  That's it! - many thanks!
> 
> The only trivial annoyance was that even though I added "^" to the
> grep string, it was still finding more occurances of "^Subject: " in
> the body of some emails . . so I had to change the grep line to:
> 
>   grep -e "^Subject: " -e "^From: " -- "${FILE_PATH}" | head -2 && exit 
> 5$
> 
> - now it is perfect!
> 
> Regards,
> 
> Phil.

-- 
Philip Rhoades

PO Box 896
Cowra  NSW  2794
Australia
E-mail:  phil@pricom.com.au

**Comment by toonn** [comment]
I think you should use `'`s rather than `"`s, the latter get expanded by the shell before being fed to grep.

**Comment by philiprhoades** [comment]
toonn,


On 2021-01-03 06:34, toonn wrote:
> I think you should use 's rather than "s, the latter get expanded by
> the shell before being fed to grep.


Ah right, good call . .

Thanks,

Phil.
-- 
Philip Rhoades

PO Box 896
Cowra  NSW  2794
Australia
E-mail:  phil@pricom.com.au

**Comment by toonn** [comment]
If it's solved for you I'm going to close this issue. I personally think the message body is too useful to take out of previews. It would be great if we could get nicer rendered previews for mail though, skipping over all the obscure fields.

**Comment by philiprhoades** [comment]
toonn,


On 2021-01-03 07:01, toonn wrote:
> If it's solved for you I'm going to close this issue. I personally
> think the message body is too useful to take out of previews. It would
> be great if we could get nicer rendered previews for mail though,
> skipping over all the obscure fields.


Agreed!  It is quite a nice terminal mail skimmer for me now . .

P.
-- 
Philip Rhoades

PO Box 896
Cowra  NSW  2794
Australia
E-mail:  phil@pricom.com.au
