### ISSUE TITLE
tab_new tab-name

### ISSUE THREAD

**Issue by lifeike** [ranger/ranger#2210]
request a feature

:tab_new [user-input-tab-name]

**Comment by toonn** [comment]
Simply use `:tab_open name=FooBar path=./foo/bar`.

**Comment by lifeike** [comment]
> Simply use `:tab_open name=FooBar path=./foo/bar`.

Thanks toonn, Hope my question is not duplicated. I tried searching. 
and Best wish to you.

**Comment by toonn** [comment]
That's ok. Our subreddit is a slightly better place to ask such questions because the community there can help out and also learn from such questions.

🖖
