### ISSUE TITLE
Crash when starting ranger

### ISSUE THREAD

**Issue by ZweiEuro** [ranger/ranger#2211]
ranger version: ranger 1.9.3
Python version: 3.9.1 (default, Dec 13 2020, 11:55:53) [GCC 10.2.0]
Locale: en_GB.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 334, in redraw
    self.finalize()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 391, in finalize
    DisplayableContainer.finalize(self)
  File "/usr/lib/python3.9/site-packages/ranger/gui/displayable.py", line 268, in finalize
    displayable.finalize()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/view_base.py", line 59, in finalize
    col_y = self.main_column.y + self.main_column.target.pointer \
AttributeError: 'NoneType' object has no attribute 'pointer'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

Installed Source Code Pro  via font-manager and now it crashes (I was missing the icons before)

**Comment by toonn** [comment]
Similar to #2205 and #2209. Should be fixed by #2072.

**Comment by toonn** [comment]
I was too quick when reading this error message. This is a different problem.
Do you get the same error when you remove all plugins and run `ranger --clean`?

**Comment by ZweiEuro** [comment]
yes

**Comment by toonn** [comment]
Hmm, how did you install ranger? I can't reproduce this by running either 1.9.3 or the master branch with a python 3.9.

**Comment by ZweiEuro** [comment]
pacman -S ranger

**Comment by toonn** [comment]
And the only difference was installing the font? You didn't update ranger or python simultaneously?

**Comment by ZweiEuro** [comment]
nope

**Comment by toonn** [comment]
Can you try the master branch and/or a different python version?

**Comment by ZweiEuro** [comment]
please specify what python version i should try.
I will try installing from this master (and first uninstall from pacman)

**Comment by ZweiEuro** [comment]
Works from master, but still broken icons; which i am geussing is because i am missing some icons.
I've been trying to find the icons i am missing, no luck. Arch is so confusing in this aspect
![Uploading 2021-01-11-53.png…]()

**Comment by toonn** [comment]
The plugin developer recommends one of these fonts, https://github.com/ryanoasis/nerd-fonts

**Comment by ZweiEuro** [comment]
thanks, so it was my error
