### ISSUE TITLE
Minor issue with backspace escape sequence

### ISSUE THREAD

**Issue by magnus-ISU** [ranger/ranger#2223]
#### Runtime Environment
- Operating system and version: Arch
- Terminal emulator and version: st
- Python version: 3.9.1
- Ranger version/commit: ranger-master, re-cloned before submitting this issue
- Locale: None.None

#### Current Behavior

When editing text in command mode, \<C-h> increments the visual cursor's location, but decrements the location where text is getting typed. For example, typing

 > :abc\<C-h>\<C-h>\<C-h>123

results in ":123......|" being the bottom row where pipe is the terminal's cursor and periods are spaces (3 from typing <C-h> and 3 from "123"

Typing

> :abc\<C-h>\<C-h>\<C-h>\<C-h>12

Results in "12bc......|"; even the starting colon is overwritten

As soon as a single \<C-h> is inputted, no command will work. You can get it to say funny things like "Command not found: search"

#### Expected Behavior

\<C-h> behaves exactly like a backspace

#### Context

I am trying to get in the habit of using \<C-h> instead of backspace to save my pinky from an early grave (dvorak user, so h is on the home row in a very nice spot).
It should be noted that \<C-m> correctly works exactly like pressing the enter key, and \<C-i> like a tab, as far as I can tell, so this isn't a universal problem with keycodes not being interpreted as their counterparts.

#### Possible Solutions

I do not know python ncurses and have not looked into the ranger code, but it is likely that the code is something like
```
if inputted_char == backspace: decrement the cursor location
else: increment and add inputted_char to some buffer
```
So you can just add whatever keycode \<C-h> corresponds to in the if statement
And the reason that I get wonky behaviour regarding the cursor position and displaying of string is because ranger is using a function like C ncurses printw and '^h' is interpreted by my terminal emulator as moving the position to draw back by one.

When I have time later I will try to verify this and fix it.

#### Steps to reproduce
1. Open ranger
2. Type / (or anything else to get into command mode, optionally adding some text in)
3. Press \<C-h> some times and some other keys, explore the funky behaviour

**Comment by toonn** [comment]
I can't reproduce this. I think you're running into a gnarly part of terminal escape codes. Backspace is *sometimes* `^H` but it's also sometimes `^?`. `C-h`, `C-S-?` and backspace all work identically for me. I suspect in this case your terminal emulator is somehow also interpreting the escape code.

**Comment by magnus-ISU** [comment]
Actually, its my fault for being an idiot. I customized my ranger configuration file a lot, and ended up deleting the mapping for that because I didn't understand what it was doing at the time.
