### ISSUE TITLE
Bad arguments for tab_move: [1], {}

### ISSUE THREAD

**Issue by hejops** [ranger/ranger#2228]
#### Runtime Environment
- Operating system and version: Manjaro 5.10.2-2
- Terminal emulator and version: urxvt 9.22, alacritty 0.6.0
- Python version: 3.9.1
- Ranger version/commit: 1.9.3.143.g5047d9e5-1

#### Current Behavior
Calling `tab_move` produces the aforementioned error once. (After that, the error does not occur.)
In addition, inputting L/H (see rc.conf below) while filtering crashes ranger.

#### Expected Behavior
`tab_move` and `filter` work without errors.

#### Context
```
rc.conf
map L tab_move 1
map H tab_move -1
map F console filter%space
```

#### Steps to reproduce
I typically invoke ranger as such:
```
ranger /home/user/ '/run/media/user/my hdd/files/downloads/'
tab_move 1
```

Note: this error does not occur for
```
ranger /home/user/ /home/user/
ranger '/run/media/user/my hdd/files/downloads/' '/run/media/user/my hdd/files/downloads/'
```

#### Traceback
https://pastebin.com/raw/1NNQWzyz

**Comment by toonn** [comment]
Ah, this stacktrace has nothing to do with `:tab_move` and it was fixed recently. It shouldn't happen anymore if you run the latest master branch.
