### ISSUE TITLE
0-based index Go-to-line

### ISSUE THREAD

**Issue by ixzh** [ranger/ranger#2229]
gg and G works fine.

but 3gg or 3G will go to line 4.

**Comment by chu4ng** [comment]
Idk. 3G send me to line with index 3.
What you mean, how it should works?

**Comment by toonn** [comment]
`3G` ends up on the fourth file in the directory for me. In vim `3G` would go to the third line.

**Comment by chu4ng** [comment]
So we need settings for 1-based index for display files and move cursor?

**Comment by toonn** [comment]
Don't think this needs a setting. It should just be 1-indexed.

**Comment by chu4ng** [comment]
Hm. We alreade have this features.
See `one_indexed` in rc.conf.

**Comment by toonn** [comment]
>.< Thanks for noticing!

**Comment by ixzh** [comment]
haha true.... needs to read rc.conf carefully to see if any other useful options there 🙈
