### ISSUE TITLE
[Feature request?] use third-party tool to select files

### ISSUE THREAD

**Issue by dnastase** [ranger/ranger#2233]
I would like to use ranger and sxiv (image viewer) together in the sense that I would like the sxiv to be the file selection method for ranger; use case scenario: in ranger I'm in a photos directory, I press a key shortcut, sxiv opens and I browse the images and select a couple and then I close the sxiv; I would like those files/photos to be selected in ranger ready to be copied/moved; is there a way to achieve that already (I didn't find it); or if it needs to be programmed, do you have a suggestion on how it's best to do it ?

**Comment by dnastase** [comment]
Ah, I apologize, now I see: https://github.com/ranger/ranger/pull/2151, however it's not merged ...

**Comment by chu4ng** [comment]
In theory, you can just paste [plugin_sxiv.py](https://github.com/chu4ng/ranger/blob/sxiv_select/examples/plugin_sxiv.py) in $HOME/.config/ranger/plugins/

Also you can clone repository and patch it yourself. But you still shoud copy plugin_sxiv.py to config dir.
Branch has only this file and one fix for mimetype, that have effect only to colors.

**Comment by dnastase** [comment]
Yes, thank you, the PR shows nicely what needs to be done. And maybe having it as a plugin is not a bad idea as it's a more flexible solution for code changes.

I am going to close the Issue so as not have the contributors distracted.
