### ISSUE TITLE
Synchronize the CWDs of ranger and the spawned sub-shell

### ISSUE THREAD

**Issue by cheap-glitch** [ranger/ranger#2246]
#### Runtime Environment

- Operating system and version: Arch Linux
- Terminal emulator and version: alacritty 0.7.1
- Python version: 3.9.1
- Ranger version/commit: 1.9.3
- Locale: en_US

#### Context

I've started using [`broot`](https://github.com/Canop/broot) to jump between directories on the command line. When opening an interactive sub-shell in a ranger instance with <kbd>Shift</kbd> + <kbd>s</kbd>, changing the cwd of that sub-shell, and exiting, the cwd of ranger doesn't change.

I know this is actually the correct behavior, as child processes cannot modify their parent's environment. But is there any way to circumvent that, and make ranger jump to the cwd of the sub-shell when it is exited?

I apologize in advance if this has been answered somewhere else already. I've searched around a lot, but all I've found are solutions to change the shell's cwd when ranger is exited — which is the exact opposite of what I want.

**Comment by toonn** [comment]
Yes, ranger is a python/bash polyglot so you can source it `. ranger`, this'll basically make ranger echo `cd /current/dir` which your shell executes as instructed. Also check the wiki for functions that wrap ranger to do this, for fish, for example.

**Comment by cheap-glitch** [comment]
Sorry if I'm wrong, but I think you misunderstood me. I'd like for *ranger itself* to change its cwd when the shell is exited, not the opposite.

**Comment by toonn** [comment]
Ah, you're right. I think vifon's zranger is the closest thing to this. You're best off implementing a custom command to integrate `broot`, look at the fasd and fzf commands on the wiki, for example.

**Comment by toonn** [comment]
>.> <.< >.> Shhh 🤫  Don't tell anyone I showed you this and caveat emptor.
https://bitbucket.org/Vifon/zsh-config/commits/b6dd6eaa0540e1bc7f7c933626a6f3f39c675bd6
https://github.com/vifon/dotfiles/commit/3cb37e62205c03ca9db6753b68f646e68e4a344c

Modifying your shell and ranger's `:shell` command you can get this behavior but it's full of warts.

**Comment by cheap-glitch** [comment]
Instead of rewriting `:shell`, could this be doable with `fm.run()` and the `runner.execute.after` hook? Or just with:
```python
eval fm.run('bash -i -c br') with open("/tmp/rangershelldir", "r") as f: fm.cd(f.readline().strip()) os.unlink("/tmp/rangershelldir")
```
(going out on a limb here, I have no real knowledge of Python)

**Comment by toonn** [comment]
Yeah, something along those lines. But you have to turn it into a valid single line of python.

**Comment by toonn** [comment]
You can also define ":myshell" for this if you want. Just throw the code into `commands.py`, which is considered a configuration file.
