### ISSUE TITLE
shell_automatic_cd example file has misnamed bind function

### ISSUE THREAD

**Issue by tannerlegvold** [ranger/ranger#2249]
This a relatively simple issue. [shell_automatic_cd](https://github.com/ranger/ranger/blob/master/examples/shell_automatic_cd.sh) is a small shell script to be ```source```ed or included in a ```.bashrc``` to make a ```ranger_cd``` command that runs ranger and, upon quiting, ```cd```s the user into the directory ```ranger``` was last in. This works fine. The script also adds a keybinding to call this command on Ctrl + o, but it mistakenly calls ```ranger-cd``` instead of ```ranger_cd```. Changing the final line from 
```
bind '"\C-o":"ranger-cd\C-m"'
```
to 
```
bind '"\C-o":"ranger_cd\C-m"'
```
fixes the problem on my system.

**Comment by toonn** [comment]
👍 That's for bringing this up!

**Comment by toonn** [comment]
Fixed in 20cc5e861afbe8c2afed2ce843a1ca6f0bc2f218

**Comment by 3nuc** [comment]
If you're using zsh you also need to use `bindkey` (zsh), not `bind` (bash)

**Comment by toonn** [comment]
: ( Looks like there's no posix compliant way to bind a function to a key?
