### ISSUE TITLE
Issue with natural sort

### ISSUE THREAD

**Issue by z0rc** [ranger/ranger#2251]
#### Runtime Environment

- Operating system and version: Kubuntu 20.10
- Terminal emulator and version: Konsole 20.08.2
- Python version: 3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]
- Ranger version/commit: 1.9.3
- Locale: en_US.utf8

#### Current Behavior
```
~/workspace/sorttest
% ls -1v
626087_p0_OD2u13OtQVdA3VVRDl5Yny9T
891469_p0_7A655Klfg7WYIJrTl83TlchW
891469_p1_aoUeWW90Tt8fAWJ0vhFcdQDS
1826089_p1_JxC2iAo4h5Co49STvlECHtmS
1912362_p0_1ukJVK8xfqT7B7ILM2g3ejuY
```

But ranger with natural sort does
```
1826089_p1_JxC2iAo4h5Co49STvlECHtmS
1912362_p0_1ukJVK8xfqT7B7ILM2g3ejuY
626087_p0_OD2u13OtQVdA3VVRDl5Yny9T
891469_p0_7A655Klfg7WYIJrTl83TlchW
891469_p1_aoUeWW90Tt8fAWJ0vhFcdQDS
```

#### Expected Behavior
ranger with natural sort should sort like `ls -v`.

#### Possible Solutions
I monkey patched natural sorting option with plugin:
```python
from __future__ import (absolute_import, division, print_function)
import re
from ranger.container.directory import Directory


Directory.sort_dict['natural'] = lambda s: [int(t) if t.isdigit() else t.lower() for t in re.split(r'(\d+)', str(s))]
```
Entirely based on https://stackoverflow.com/a/16090640/1392263.

**Comment by toonn** [comment]
I can't reproduce this. And it looks like your sort function splits by digit? That'd have the opposite effect of what we want and make "1826089_p1_JxC2iAo4h5Co49STvlECHtmS" sort before "626087_p0_OD2u13OtQVdA3VVRDl5Yny9T".

![Screen Shot 2021-02-21 at 13 33 56](https://user-images.githubusercontent.com/1486805/108625177-b733ec00-7449-11eb-9bc1-18cb560f201f.png)

**Comment by z0rc** [comment]
Okay, did a bit more research, `set sort_unicode true` was affecting sort order in my case. Probably dupe of #1440.

**Comment by toonn** [comment]
Ah, yes. Kinda stuck on that one. Maybe special-casing digits is less confusing in the end, even though it'd be less consistent.
