### ISSUE TITLE
Copying a directory tree with broken symlinks does not work

### ISSUE THREAD

**Issue by lahwaacz** [ranger/ranger#2252]
#### Runtime Environment
- Operating system and version: Arch Linux
- Terminal emulator and version: termite 15
- Python version: 3.9.1 (default, Feb  6 2021, 06:49:13) [GCC 10.2.0]
- Ranger version: 1.9.3
- Locale: en_GB.UTF-8

#### Current Behavior
For whatever reason, copying a directory tree with yy and pasting with pp will abort when a "broken" symlink (i.e. leading to a non-existent target) is encountered.

#### Expected Behavior
The directory tree should be copied exactly as-is, just like with `cp -r`.

#### Steps to reproduce
1. `mkdir test`
2. `ln -s foo test/bar`
3. `mkdir test2`
4. Open ranger, select both `test` and `test2`, copy with yy and pp them somewhere else
5. The following error message appears at the bottom:

       Loader work process failed: copying: /home/user/test (1 B) (Percent: 0)

6. Observe that the `test` tree has been copied, but `test2` is missing.

**Comment by toonn** [comment]
This sounds a lot like an open issue I vaguely remember. Please try finding that to link these issues.

**Comment by lahwaacz** [comment]
Oh, it's probably https://github.com/ranger/ranger/issues/1116...
