### ISSUE TITLE
Image/video preview via mpv

### ISSUE THREAD

**Issue by BogdanLysenko** [ranger/ranger#2256]
It seems like instructions about how to configure ranger to display image/video preview via mpv is out of date. For example, there is no ImageDisplayer() method anymore in fm.py, or it has another form now. So, I hope you add valid information about how to do it beacause now I think it is the only way to enable image/video preview in my alacritty terminal.

**Comment by toonn** [comment]
I think there's an open PR or issue with more up to date instructions in the comments. The ueberzug method should work with alacritty though, as long as you're on X.

**Comment by BogdanLysenko** [comment]
@toonn 
No, the whole point is I'm on pure Wayland under Sway, otherwise I'd prefer another preview method from guide.

**Comment by toonn** [comment]
Maybe switching to kitty temporarily is an option? Or you could try out the sixel PR if alacritty supports sixel.

**Comment by BogdanLysenko** [comment]
@toonn, I did fix of mpv due to your recomendation in this issue https://github.com/ranger/ranger/issues/2065#issuecomment-758603998, so I can close my. 
However, it looks poor and runs images in another window drugging me from my one.. So I had to disable it. 
Sixel support in alacritty is currently not implemented. But there already is a pull request for this. I'm leaving reference if anyone is interested maybe to test this or help to contribute:
https://github.com/alacritty/alacritty/pull/4763

**Comment by toonn** [comment]
Maybe look into ueberzug again. Last I heard the author was working on Wayland support.

**Comment by echozhangxiaomin** [comment]
> 看看代码也不难加进去啊。 现在我的问题是，如何不启动新的窗口在ranger中预览，

**Comment by echozhangxiaomin** [comment]
> @toon，由于您在此问题[#2065（comment）](https://github.com/ranger/ranger/issues/2065#issuecomment-758603998)中的建议，我修复了 mpv，所以我可以关闭我的。 但是，它看起来很差，并且在另一个窗口中运行，使我从我的 窗口中毒......所以我禁止但它。吸，谢谢你。将留下参考： [alacritty/alacritty#4763](https://github.com/alacritty/alacritty/pull/4763)
俺也一样

**Comment by Bellavene** [comment]
This code works as expected

`@register_image_displayer("mpv")
class MPVImageDisplayer(ImageDisplayer):
    """Implementation of ImageDisplayer using mpv, a general media viewer.
    Opens media in a separate X window.

    mpv 0.25+ needs to be installed for this to work.
    """

    def _send_command(self, path, sock):

        message = '{"command": ["raw","loadfile",%s]}\n' % json.dumps(path)
        s = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        s.connect(str(sock))
        info('-> ' + message)
        s.send(message.encode())
        message = s.recv(1024).decode()
        info('<- ' + message)

    def _launch_mpv(self, path, sock):

        proc = Popen([
            * os.environ.get("MPV", "/Applications/IINA.app/Contents/MacOS/iina-cli --keep-running --no-focus-on-open").split(),
            # "--no-terminal",
            "--force-window",
            "--image-display-duration=inf",
            "--loop-file=inf",
            "--no-separate-windows",
            "--no-input-default-bindings",
            "--keep-open",
            "--keepaspect",
            "--keepaspect-window",
            "--fixed-vo",
            # "--",
            path,
        ])

        @atexit.register
        def cleanup():
            proc.terminate()
            sock.unlink()

    def draw(self, path, start_x, start_y, width, height):

        path = os.path.abspath(path)
        cache = Path(os.environ.get("XDG_CACHE_HOME", "~/.cache")).expanduser()
        cache = cache / "ranger"
        cache.mkdir(exist_ok=True)
        sock = cache / "image-slave.sock"

        try:
            self._send_command(path, sock)
        except (ConnectionRefusedError, FileNotFoundError):
            info('LAUNCHING ' + path)
            self._launch_mpv(path, sock)
        except Exception as e:
            logging.exception(traceback.format_exc())
            sys.exit(1)
        info('SUCCESS')
`

**Comment by toonn** [comment]
Deleted some comments written in hanzi or something and no members of the team are able to read those. So we can't verify whether they're spam/inappropriate. Please keep comments in english, if possible.

@BogdanLysenko, I recently saw an issue or PR mentioning mpv previews again but I can't find it right now.
