### ISSUE TITLE
use $PS1 in the TitleBar._get_left_part in ranger.gui.widgets.titlebar

### ISSUE THREAD

**Issue by nkh** [ranger/ranger#227]
instead for showing the user/hostname/directory, use the $PS1 variable set by the user for his normal prompt.

I, for example, displaay git related information in directories under git control

**Comment by NoSuck** [comment]
Interesting idea.  I don't necessarily agree with using the shell's $PS1, but it would be nice to customize that area of the screen.  It gets in the way when a lot of tabs are open.

**Comment by nkh** [comment]
as long as it can point to PS1 or use a bash script to generate it, I am good with something that does more

**Comment by nfnty** [comment]
This will never work properly. Open a new feature request issue if there's specific information you're missing from the UI.

**Comment by NoSuck** [comment]
In retrospect, @nkh might have been happy simply by configuring `vcs_backend_git`.
