### ISSUE TITLE
Include webp in open_all_images setting

### ISSUE THREAD

**Issue by mvrozanti** [ranger/ranger#2271]
May be related to #1953

#### Runtime Environment

- Operating system and version: 
`Linux mndrgr 5.10.15-arch1-1 #1 SMP PREEMPT Wed, 10 Feb 2021 18:32:40 +0000 x86_64 GNU/Linux`
- Terminal emulator and version: kitty 0.19.3
- Python version: Python 3.9.1
- Ranger version/commit: ranger 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
webp extension files are not in the set defined by `open_all_images` setting, and they should.

#### Expected Behavior
webp extensions are treated as images

#### Context
Opening a directory with mixed file extensions

#### Possible Solutions
Include webp in open_all_images setting

#### Steps to reproduce
1. Add a png to a directory
2. Add a webp to same directory
3. Set sxiv as default image viewer
4. Navigate to directory and open one image.
5. Notice how when you try to jump to next image it doesn't.

**Comment by toonn** [comment]
Hmm, I think both issues should've been fixed in #2095. Could you try running ranger from a checkout of the master branch to verify?

**Comment by mvrozanti** [comment]
Will do and report back soon

**Comment by mvrozanti** [comment]
Didn't work on master with cd17ea8c1d2cd89754f625df25134f00c7227b65

**Comment by toonn** [comment]
Ok, closing in favor of #1953 but I do consider this a bug.
