### ISSUE TITLE
Faulty UI adjustment when terminal window size changes

### ISSUE THREAD

**Issue by 80KiloMett** [ranger/ranger#2275]
##### Operating system and version:
```
5.11.2-arch1-1
window manager: qtile 0.17.0
``` 
##### Terminal emulator and version: 
The issue occurs with `kitty 0.19.3` and `alacritty 0.7.2`.
`st 0.8.4` (an old version I just happened to have installed) does not show the issue.

##### Python version: 
3.9.2 and 3.7.9 (still had this lying around)

##### Ranger version: 
1.9.3
also on current master cd17ea8

##### Locale: 
en_US.UTF-8

#### Current Behavior
When the size of the terminal window is changed ranger fails to adjust its interface correctly.

normal interface:
![normal interface](https://i.imgur.com/YG7XEi9.png)

after resize:
![after window resize](https://i.imgur.com/Zx4m6PP.png)

#### Expected Behavior
Ranger's UI should adjust properly.

#### Steps to reproduce
1. Start a terminal
2. Start ranger
3. resize the window

#### Comments
It's possible this is more of an issue in the curses module, or maybe my window manager just doesn't report window sizes correcty (Honestly don't know how that stuff works). On the other hand ranger works fine with my old installation of st.

**Comment by toonn** [comment]
Hmm, afaik ranger just reacts to SIGWINCH. Do other curses programs not exhibit similar problems?

**Comment by ParaSait** [comment]
I have this problem as well.

It seems dependent on window managers indeed; I have this issue in qtile, but not in xfce.

However, Midnight Commander (afaik also curses-based) doesn't have this issue.

**Comment by toonn** [comment]
Maybe it's specific to python's curses bindings?

**Comment by 80KiloMett** [comment]
Can also confirm that midnight commander and vifm are working fine. I don't know any other popular curses software written in Python out of the top of my head, though.

**Comment by josevega96** [comment]
also having this issue seems after some testing with qtile + kitty the issue can be reproduced just by changing the window size, when i try the same inside qtile + xterm everything works fine

**Comment by 80KiloMett** [comment]
Okay, I've found two issues on qtile's tracker that relate to the problem (https://github.com/qtile/qtile/issues/2204, https://github.com/qtile/qtile/discussions/2164). Seems like indeed qtile broke something here. There is a workaround though:
```
unset LINES
unset COLUMNS
```
I'm going to put this in my zshrc for now and see if something else breaks.
Since this seems to be a qtile specific problem and there's a workaround, I'm closing this here.
