### ISSUE TITLE
Ueberzug starts rendering previews only after change font size in alacritty

### ISSUE THREAD

**Issue by yagarea** [ranger/ranger#2279]
#### Runtime Environment

- Operating system and version: Linux arch-thinkpad 5.11.6-arch1-1 x86_64 GNU/Linux
- Terminal emulator and version: alacritty 0.7.2 (5ac8060b)
- Python version: Python 3.9.2
- Ranger version/commit: ranger version: ranger 1.9.3

#### Current Behavior
Previews wont render until I change font size with `crt +` or `crt -`

#### Expected Behavior
Render images without need to change font size

#### Context
I am using ueberzug as preview method.

#### Possible Solutions
Check rendering UI updating 

#### Steps to reproduce
Open ranger and navigate to any directory with pictures.

#### Traceback
None

**Comment by seebye** [comment]
It sound to me like you're using fish as the terminal will update its window size information on changing the font size.  
So if you're using fish as shell in old versions they set the terminal size to the max size of a unsigned short (=65535px).  
https://github.com/fish-shell/fish-shell/commit/d5a239e59ec0e84a47d499270f618e432abd747f  
The size information is provided in two units chars and pixels, so if you change the font size your terminal emulator will update the information and therefore delete fish unnecessary modifications.  
So if you use fish either change to another shell or update your shell or use a preview method which does not need this information.

**Comment by yagarea** [comment]
Fixxed in alacritty `0.9.0`
