### ISSUE TITLE
Scrolling in preview not working

### ISSUE THREAD

**Issue by wolfisberg** [ranger/ranger#2280]
#### Runtime Environment
- Operating system and version: Manjaro
- Terminal emulator and version:  Konsole 20.12.2
- Python version: 3.9.2
- Ranger version/commit: ranger-master (through AUR
$ pacman -Qs ranger-git
local/ranger-git 1.9.3.196.gb50949e2-1
- Locale: en_US.UTF-8

#### Current Behavior
alt+j/alt+k don't seem to work.

I tried ```set xterm_alt_key true``` and ```false``` with no success.

#### Expected Behavior
alt+j/alt+k allow scrolling in preview

**Comment by toonn** [comment]
Can you bind them to another function?

**Comment by wolfisberg** [comment]
The key binds don't work for other functions either (tested with setting them to "help").
Setting a different bind (tested with "SS" and "Ss") to preview scrolling works fine.
changing the ```xterm_alt_key``` setting didn't affect any of the mentioned configurations.

**Comment by toonn** [comment]
Could you try different terminals, Xterm, urxvt, kitty?

**Comment by wolfisberg** [comment]
I'm an idiot. A kwin script bound alt+j/k to another function (kwin quartertiling) without me noticing.

**Comment by guidomz** [comment]
I concur @wolfisberg's observation, even his attempt to `set xterm_alt_key`. This used to work in a previous version (1.9.3-5), but I can no longer make it work after upgrading to 1.9.4. I downgraded back to 1.9.3-5 but functionality is similarly not there. I made no changes to my custom rc.conf
