### ISSUE TITLE
Neovim editor support

### ISSUE THREAD

**Issue by sky96111** [ranger/ranger#2281]
#### Runtime Environment

- Operating system and version: Arch Linux
- Terminal emulator and version: Gnome Terminal 3.38.3
- Python version: 3.9.2
- Ranger version/commit: 1.9.3
- Locale: zh_CN.UTF-8

#### Current Behavior
Nothing opened. After exiting Ranger I can see `/bin/sh:行1: vim：未找到命令` ( `/bin/sh: line 1: vim: command not found` )
#### Expected Behavior
Ranger start Neovim and enter editing mode.
#### Context

I use `ln -s /bin/nvim /bin/vim` to pretend I have installed Vim, but, it is not an elegant solution.
It may be better to support it officially by detecting not just `vim` but also `nvim`
#### Steps to reproduce
1. Just install Neovim and Ranger without Vim.
2. Select a text file and press Enter.

#### Traceback

```

```

**Comment by toonn** [comment]
Fixed in #2072. Thanks for the report.

**Comment by toonn** [comment]
Whoops, commented on and closed the wrong issue >.<

**Comment by toonn** [comment]
For editor configuration we simply adhere to shell customs, so simply set `VISUAL` to `nvim` in your shell's rc file. Alternatively you could add a rule to `rifle.conf`, look at the `label editor` rule for reference.
