### ISSUE TITLE
Rewrite ranger in Rust

### ISSUE THREAD

**Issue by EvanCarroll** [ranger/ranger#2285]
Nice app, but why does my file manager need a garbage collector? This is an insult to my files and life work.

I like me a Rust.

**Comment by toonn** [comment]
[Hunter](https://www.laeran.pl/repositories/hunter/wiki?name=Home)'s the best I can do for you. ¯\\\_(ツ)\_/¯

**Comment by leontepe** [comment]
@toonn I think you linked the wrong Hunter. [This](https://github.com/rabite0/hunter) is the one written in Rust.

**Comment by toonn** [comment]
@leontepe, yep, you're right. I didn't bother double-checking because it was as a reply to a shitpost ; )

**Comment by EvanCarroll** [comment]
w/ love though.

**Comment by hektr** [comment]
if you have already build a building from bricks, you are not going to rebuild it from blocks☝️

**Comment by EvanCarroll** [comment]
pretty close: https://github.com/kamiyaa/joshuto
