### ISSUE TITLE
How to use select files (name contain space) to shell

### ISSUE THREAD

**Issue by zdmgmail** [ranger/ranger#2286]
I hope merge some pdf file , so use

`map mpm console shell pdfunite %s output.pdf`

but filename contain space, `1 1 .pdf` `2 2 .pdf`

so I will get `:shell pdfunite 1 1 .pdf 2 2 .pdf  output.pdf`

then  error `I/O Error: Couldn't open file '1': No such file or directory.
Syntax Error: Could not merge damaged documents ('1'`

How to get `:shell pdfunite "1 1 .pdf" "2 2 .pdf"  output.pdf`

Or  `:shell pdfunite "1\ 1\ .pdf" "2\ 2\ .pdf"  output.pdf`

(`:shell pdfunite "1 1 .pdf 2 2 .pdf"  output.pdf` not work)

**Comment by toonn** [comment]
This is a known issue. Two workarounds, drop `console`, things are properly escaped when you just use `shell`, or you can escape the macro `%%s` so the console will open with `:shell %s output.pdf`, that way you could edit the output filename but the macro isn't expanded yet so escaping's not an issue.

**Comment by toonn** [comment]
Tracked in PR #1931.

**Comment by zdmgmail** [comment]
> This is a known issue. Two workarounds, drop `console`, things are properly escaped when you just use `shell`, or you can escape the macro `%%s` so the console will open with `:shell %s output.pdf`, that way you could edit the output filename but the macro isn't expanded yet so escaping's not an issue.

drop console seems not properly escaped .   I use `console shell %%s` work, but only use `shell` always not work

**Comment by toonn** [comment]
Could you report with more detail? Using shell without console should escape file names properly.
