### ISSUE TITLE
Show both devicons and sizemtime for files/directories?

### ISSUE THREAD

**Issue by smartding** [ranger/ranger#2290]
I want show both devicons and sizemtime information for files/directories, but setting "default_linemode  devicons sizemtime" in rc.conf doesn't work.

Is there any other way I can have both devicons sizemtime?

**Comment by toonn** [comment]
You'd probably have to write your own modeline. This isn't as hard as it may sound and can be done from `${XDG_CONFIG_HOME}/ranger/commands.py` using a decorator.

**Comment by smartding** [comment]
ok, thanks
