### ISSUE TITLE
[minor config] add mcomix and qcomicbook in rifle

### ISSUE THREAD

**Issue by pirate486743186** [ranger/ranger#2292]
just add this at line 178, of rifle.conf

```
ext cbr,  has qcomicbook,      X, flag f = qcomicbook -- "$@"
ext cbz,  has qcomicbook,      X, flag f = qcomicbook -- "$@"
ext cbr,  has mcomix,      X, flag f = mcomix -- "$@"
ext cbz,  has mcomix,      X, flag f = mcomix -- "$@"
```

just above of:
```
ext cbr,  has zathura,      X, flag f = zathura -- "$@"
ext cbz,  has zathura,      X, flag f = zathura -- "$@"
```

and also at 203, add:

`mime ^image, has mcomix,     X, flag f = mcomix -- "$@"`

if you open an image, mcomix will treat the rest of the folder as a comic book. It's not meant to be an image viewer, so it should get low priority, users probably want to use something else first.

**Comment by toonn** [comment]
Can you check whether mcomix and qcomicbook support the `--` convention? `mcomix -- path/to/some/cbz`

**Comment by pirate486743186** [comment]
lol... i had simply copy pasted that XD

it works with mcomix, but not with qcomicbook

**Comment by toonn** [comment]
Np, thanks for testing. Feel free to submit changes like this as a PR next time : )
