### ISSUE TITLE
Error while trying untag several files

### ISSUE THREAD

**Issue by chu4ng** [ranger/ranger#2295]
#### Runtime Environment

- Operating system and version: Linux 5.11.2-arch1-1
- Terminal emulator and version: st
- ranger version: ranger 1.9.3 (b50949e) / ranger-master
- Python version: 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
- Locale: en_US.UTF-8

#### Current Behavior
Cannot untaging a several files. 
I still can cut or yank these files.
#### Expected Behavior
Before this function worked fine.
#### Context

I first saw it a week ago with _strange-filename_, but now I have this behavior for any several files.

#### Possible Solutions
I haven't update python or ranger recently, so idk. 
I will try resolve this issue.
#### Steps to reproduce
1. Select multiple file.
2. `:tag_remove` or `ut` bind.

#### Traceback

```
15:38:58 ERRO Notification: len() takes exactly one argument (32 given)
15:38:58 ERRO len() takes exactly one argument (32 given)
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/api/commands.py", line 403, in execute
    return func(**{'narg': self.quantifier})
TypeError: tag_remove() got an unexpected keyword argument 'narg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/core/actions.py", line 269, in execute_console
    cmd.execute()
  File "/usr/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/api/commands.py", line 405, in execute
    return func()
  File "/usr/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/core/actions.py", line 883, in tag_remove
    self.tag_toggle(tag=tag, paths=paths, value=False, movedown=movedown)
  File "/usr/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/core/actions.py", line 867, in tag_toggle
    self.tags.remove(*tags)
  File "/usr/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/container/tags.py", line 43, in remove
    if len(*items) == 0:
TypeError: len() takes exactly one argument (32 given)

```

**Comment by chu4ng** [comment]
Problem in `if len(*items) == 0:` lines, but I don't understand why it works before.
`len` gets one container, and unpacking by `*` return one or more elements, right? 
I'm not sure where actually problem.

**Comment by toonn** [comment]
Hmm, cannot reproduce the problem but I did notice tags don't even show up on master anymore : /

**Comment by chu4ng** [comment]
@toonn Hm, with `--clean` key I don't see tags, because then ranger has not datadir. I think it's ok.

**Comment by toonn** [comment]
I think `--clean` should use a temp dir for such things.

**Comment by chu4ng** [comment]
I start the ranger with `--debag` and `--clean` keys and watch in the message log:
```
cache dir: '/tmp/whatever.ranger-cache'
data dir: 'None'
config dir: 'None'
```
And I'm not sure in "good" behavior, because both case looks like good choice: None and in /tmp.

**Comment by chu4ng** [comment]
So.. toonn, what you can say about `len(*items)` in this tags.py context? This makes no sense? I think.
Also this bug is gone when I change to `len(items)`.
May I create new PR or I don't understand something?

**Comment by toonn** [comment]
I'll try to take a look tomorrow.

**Comment by toonn** [comment]
Well, that was a long tomorrow...
Fixed finally, thanks!
