### ISSUE TITLE
Unexpected behaviour when using shell with xargs

### ISSUE THREAD

**Issue by w2kpro** [ranger/ranger#2298]
:shell xargs -0 gvim < %s
Not all the selected (or tagged) files are opened. The first selected file is missed. If there are 5 files selected 1.exe, 2.ext, 3.ext, 4.ext and 5.ext, 5 files are loaded into gvim, starting with 2.ext and ending with a file that was not on the selection list!

#### Runtime Environment

- Operating system and version: Linux Mint Mate 20
- Terminal emulator and version:  Mate-Terminal 1.24.0
- Python version: 3.8
- Ranger version/commit: 1.9.3
- Locale: en

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```

```

**Comment by toonn** [comment]
That sounds bad. What if you drop the `-0` though? Ranger doesn't pass the files separated by NULs.

**Comment by w2kpro** [comment]
Hi Toon,

5 sed script test files i1.sed - i5.sed

:shell xargs -r0 gvim < %s

failure, with output to console "5 files to edit"

:shell xargs gvim < %s

failure, with output to console "xargs: unmatched double quote; by 
default quotes are special to xargs unless you use the -0 option"

:shell xargs -r0a %s gvim

failure, with output to console "xargs: i2.sed: No such file or directory"

:shell echo %s | xargs -t gvim

success, with output to console "gvim i1.sed i2.sed i3.sed i4.sed i5.sed"

Typical content of files (used to scrape web pages):

#n
/<title>.*<\/title>/x
/noWrap">Apr 01, 2021</ {
:a
N
/<\/tr>/!ba
H
g
/\n/ s///g
/,/ s///g
/^.*<title>.*(\(.\{2,6\}\)).*"\([0-9]*\.[0-9]*\|[0-9]*\)".*"\([0-9]*\.[0-9]*\|[0-9]*\)".*"\([0-9]*\.[0-9]*\|[0-9]*\)".*"\([0-9]*\.[0-9]*\|[0-9]*\)".*"\([0-9]*\)".*$/ 
s//\1,2021-04-01,\3,\4,\5,\2,\6/
p
q
}

Kind regards,

Chris

**Comment by toonn** [comment]
Unfortunately it looks like this isn't something we can handle. The problem is the redirect `<` applies to the first argument. You'll have to echo and pipe or maybe `<(echo %s)`. Not sure why you're using xargs tbh, `:shell gvim %s` would work fine, no?

**Comment by w2kpro** [comment]
Hi toonn,

Thanks for the info. I was using xargs as my main file manager is nnn. 
gvim $sel in nnn just opens the .selection file, which is a list of "00" 
separated path/filenames. It doesn't open their content in individual 
buffers. So when using nnn, xargs has to be used, and I thought ranger 
might behave in a similar fashion.

Kind regards,

Chris

**Comment by toonn** [comment]
No problem.
