### ISSUE TITLE
Unable to Filter Items by Extension

### ISSUE THREAD

**Issue by Zhu-Justin** [ranger/ranger#2299]
#### Runtime Environment

- Operating system and version: MacOS High Sierra
- Terminal emulator and version: iTerm  
- Python version: Python3.9
- Ranger version/commit: 
- Locale: 

#### Current Behavior
Thank you for your hard work! I want to currently filter my files according to extensions, so something like `:filter *.py` but I don't think I am aware of a command to do so. Could you add this as a feature if possible, or otherwise let me know what is the correct way to only display files of a certain extension on ranger? Thank you so much!

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```

```

**Comment by toonn** [comment]
The scout filter command already does this, `:filter .py$`. You might want to use the newer stack-based filters though `:filter_stack add name .py$`.

The former's bound to `zf`, the latter to `.n`.
