### ISSUE TITLE
complete %f in command field

### ISSUE THREAD

**Issue by nkh** [ranger/ranger#230]
When using the command field, ranger completes the macro.

one of the main useage I have is when renaming files. The name of the selectd file is added (c-up, which I discovered by accident), when I want to rename only a little part of a long file name, I have to retype the whle name.

Note tht file name completion doesn't work either in the  command field

**Comment by hut** [comment]
Without making your suggestion invalid, I wanna throw in that there are the key bindings `A`, `I` and `a` for simple renaming

**Comment by nfnty** [comment]
Just use the default mappings for renaming, as mentioned by @hut.
