### ISSUE TITLE
Indentation size

### ISSUE THREAD

**Issue by FormidablePencil** [ranger/ranger#2310]
I want to change the indentation spacing of code files I'm looking through with Ranger.

**Comment by toonn** [comment]
Depends on the tool used to preview the files. I think this can be set for highlight and bat, maybe pygments too.

**Comment by FormidablePencil** [comment]
Ok, I know where to look. Would you know how to switch highlight for pygments (highlight docs are confusing) and enable syntax highlighting for *.ts files?

**Comment by toonn** [comment]
By uninstalling highlight : )
If you need it on the PATH you'll have to customize `scope.sh`.

**Comment by FormidablePencil** [comment]
In scope.sh I changed the 8 to what I wanted the tab indentation to be so changing tab indention was a success:
`HGHLIGHT_TABWIDTH="${HIGHLIGHT_TABWIDTH:-2}"` 
Thanks for your help with switching highlight for pygments. Highlighting for *.ts started working after reinstalling highlight.

**Comment by toonn** [comment]
🎉 
You can simply set `HIGHLIGHT_TABWIDTH` in your environment, shell rc file or `.profile` btw.
