### ISSUE TITLE
How to automatically execute one command when I go to different directories

### ISSUE THREAD

**Issue by c02y** [ranger/ranger#2315]
#### Runtime Environment
  
  - Operating system and version: `Manjaro-Linux`
  - Terminal emulator and version: `Alacritty`
  - Python version: `v3.9.3`
  - Ranger version/commit: `277e1db` 
  - Locale: `en_US.UTF-8`

#### Possible Solutions
For example, I have a binding `map ds chain mark_files all=True toggle=True; get_cumulative_size; mark_files all=True toggle=True; set sort=size` which gets the size of all files/dirs in the current directory and sort the size, but sometimes I need to use ranger as a tiny disk usage analyzer, so I when I goto another dir I need to execute the binding again, is there a way that I can use to automatically keep executing the bidninging/command whenever I go?

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```

```

**Comment by toonn** [comment]
Not currently. Maybe you could bind the movement key for entering a directory to chain doing the move and then checking if you've registered a hook to run?

I'd really rather recommend using ncdu for disk usage analysis though.

**Comment by c02y** [comment]
> I'd really rather recommend using ncdu for disk usage analysis though.

That's why I said "but sometimes I need to use ranger as a tiny disk usage analyzer", when I'm using an external disk usage analyzer like ncdu I'm always missing ranger, when I'm using ranger and when I need a tiny disk analyzer function from ranger, I always think that if it would be nice once ranger has auto-ds-cross-dirs feature.

**Comment by c02y** [comment]
**UPDATE**:

I just bind two keys for this feature:
```
map { chain move left=1; mark_files all=True toggle=True; get_cumulative_size; mark_files all=True toggle=True; set sort=size; move to=0
map } chain move right=1; mark_files all=True toggle=True; get_cumulative_size; mark_files all=True toggle=True; set sort=size; move to=0
```
Just hoping `C-Left/Right` would work. https://github.com/ranger/ranger/issues/2064
