### ISSUE TITLE
Ranger Colorscheme Changes Between Home Directory And Non-Home Directories

### ISSUE THREAD

**Issue by user1180** [ranger/ranger#2317]
Operating system: Manjaro Linux 21.0.2 (Ornara), kernel 5.9.16-1
Emulator version: rxvt-unicode 9.22-10
Ranger version: ranger-master 
Python version: 3.9.3 (default, Apr  8 2021, 23:35:02) [GCC 10.2.0]
Locale: en_US.UTF-8
------------------------------

Current Behaviour-
Current colorscheme colors defined filetypes as expected within home directories and all it's subdirectories. Outside the home directory, certain filetypes are not colored as defined. Examples: 
-Within home, pdf files are colored pastel pink, whereas on a mounted data drive, they are colored bright green.
-In contrast, image files like png or svg are bright pink in all directories.

Expected Behaviour-
Filetypes are to be colored consistently, as defined in the colorscheme config, throughout all directories.

Context-
Trying to implement a colorscheme that colors files by extension categories to aid in file organization. Currently using a slightly modified version of `[LS_COLORS](https://github.com/isene/LS_COLORS/blob/master/ranger/isene.py)`. The only additions are two extra categories to differentiate video and audio files, as well as adding a few extensions to existing categories.

The main directory where file organization takes place is on a separate data drive that is automatically mounted startup, which my user owns and has rwx perms.

Possible Solutions
-Learn how to code a colorscheme properly other than "copy/paste what this guy did and just tweak it until it works"

Steps to reproduce
1. Install isene.py 
2. Copy/paste my additions
3. Launch ranger and compare extension colors within home directory and, specifically, a separate mounted filesystem. (All my changes are marked with "# my..."

[isene_modded.txt](https://github.com/ranger/ranger/files/6382218/isene_modded.txt)

Screenshots:
ranger colors in home directory-
![rangerColors_home](https://user-images.githubusercontent.com/60323465/116194436-7630b000-a6f6-11eb-985b-3bdd1012de4e.png)
ranger colors in mounted data drive-
![rangerColors_mount](https://user-images.githubusercontent.com/60323465/116194437-76c94680-a6f6-11eb-8db5-d8baf540c4f0.png)

**Comment by toonn** [comment]
Maybe it's picking up `~/.mimetypes` but only when started in `~`? I think strace might be enlightening in this case to see what the difference is in loaded configuration files and stuff.

**Comment by user1180** [comment]
Here are two strace files for two separate sessions of ranger; one is a summary and the other is detailed. I performed the same actions in both sessions. I navigated between two directories in home and then two in the data drive; same directories in each session.

Summary- [ranger_trace_8172.txt](https://github.com/ranger/ranger/files/6388640/ranger_trace_8172.txt)
Detailed- [ranger_trace_8442.txt](https://github.com/ranger/ranger/files/6388641/ranger_trace_8442.txt)

I also noticed when moving into a directory for the first time in a session. A message flashes at the bottom, left-hand corner reading- `Bad arguments for move: [], {"right": 1}`

I should also mention that I previously had installed Isene's LS_COLORS terminal colorscheme, but disabled it shortly afterwards (deleting the lines added to the .bashrc) because Firejail was having an issue with so many colors.

**Comment by toonn** [comment]
You'd have to compare straces when opening ranger in HOME and outside of it. No need to move around in ranger, we're just interested in the files read during startup so filter for open or read calls.

**Comment by user1180** [comment]
So I've found a workaround to this problem. Executables in Isene's colorscheme are green and Ranger seems to view almost every file type in the data drive as an executable unless it is listed in one of the context groups in lines 37-57 and that group is excepted in the following elif statement (starting line 117):
```
 elif context.executable and not \
                    any((context.media, context.container,
                        context.fifo, context.socket, context.videofiles...)):
```

So I simply added the problematic extensions (pdfs mostly) and that seemed to fix the problem. I didn't seem to have that problem with files in the home directory though. Only files that had execute permissions were colored green. So I'm not sure what's going on there. Anyhow, here's the straces  for opening ranger inside and outside of home.

[ranger_strace_dataDrive_detailed.txt](https://github.com/ranger/ranger/files/6435788/ranger_strace_dataDrive_detailed.txt)
[ranger_strace_dataDrive_summary.txt](https://github.com/ranger/ranger/files/6435789/ranger_strace_dataDrive_summary.txt)
[ranger_strace_home_detailed.txt](https://github.com/ranger/ranger/files/6435790/ranger_strace_home_detailed.txt)
[ranger_strace_home_summary.txt](https://github.com/ranger/ranger/files/6435791/ranger_strace_home_summary.txt)

**Comment by toonn** [comment]
Well, documents shouldn't have the execute bit set. There's your problem. It's a security feature that executable file coloring takes precedence really.

This could maybe also happen on file systems that don't support any mode flags.

Closing since it's not really a problem with ranger nor the colorscheme.
