### ISSUE TITLE
Error: No covariates found.

### ISSUE THREAD

**Issue by gulinlin** [ranger/ranger#2318]
Hello, Why does the following situation occur when running ranger?
{Error in ranger(y = AdjustedTarget, x = obsX, num.trees = num.trees, mtry = max(floor(ncol(obsX)/3),  : 
  Error: No covariates found.}
Thanks for the ranger package, anyway!

**Comment by toonn** [comment]
I suspect you're having a problem with a different ranger. Maybe an R package or something? This is the issue tracker for the [file manager](https://ranger.github.io/).

Good luck finding help elsewhere!
