### ISSUE TITLE
Starting frozen and with a single column

### ISSUE THREAD

**Issue by keeganjk** [ranger/ranger#2324]
#### Runtime Environment

```
ranger version: ranger 1.9.3
Python version: 3.9.4 (default, Apr 20 2021, 15:51:38) [GCC 10.2.0]
Locale: en_US.UTF-8
```
- Operating system and version: `Linux NAVI 5.11.16-arch1-1 #1 SMP PREEMPT Wed, 21 Apr 2021 17:22:13 +0000 x86_64 GNU/Linux`
- Terminal emulator and version: `st`
- Python version: `Python 3.9.4` (See above)
- Ranger version/commit: See above
- Locale: en_US.UTF-8 (See above)

#### Current Behavior
Whenever I open `ranger`, it shows only a single column (it normally has 2, I believe) and keypresses are entirely unresponsive. I need to kill the terminal emulator or press Ctrl+Z to exit.
![2021-05-06_15-13-24](https://user-images.githubusercontent.com/24554125/117353053-ac4ffb80-ae7d-11eb-8b1f-472954075707.png)

#### Expected Behavior
Multiple columns, keypresses that actually do things, e.g. navigate.

#### Context

I am trying to use `ranger` normally but cannot at all—I have only been able to use CLI navigation. The issue seems to have started after my drive which is mounted to `/` was accidentally filled. I have tried to clear `ranger`'s cache and share directories, but it had no visible affect. I've also tried reinstalling.

#### Possible Solutions
Removing some sort of file that has been corrupted or is otherwise hindering proper performance?

#### Steps to reproduce
Maybe:
1. Fill drive on which `ranger is installed`
2. Launch `ranger`

**Comment by toonn** [comment]
Does running `ranger --clean` make a difference? Otherwise, does `ranger --debug` tell you anything more? If neither seems to do anything try uninstalling and reinstalling ranger.

**Comment by keeganjk** [comment]
> Does running `ranger --clean` make a difference? Otherwise, does `ranger --debug` tell you anything more? If neither seems to do anything try uninstalling and reinstalling ranger.

`ranger --clean` seems to work perfectly fine but running `ranger` afterwards does not work (same problem as mentioned above). `ranger --debug` seems identical to just running `ranger`. 

It also seemed that moving `rc.conf` and running `ranger` worked correctly, but removing individual lines from `rc.conf` had no effect. In case it is relevant, my `rc.conf` contains:

```
set show_hidden false
set preview_images true
set preview_script ~/.config/ranger/scope.sh
set preview_images_method ueberzug
```

**Comment by toonn** [comment]
`ranger --clean` runs ranger with the default configuration, it doesn't remove anything. If that works and ranger works when you remove `rc.conf` then the problem's clearly with your configuration.

What I think is happening is you set "RANGER_LOAD_DEFAULT_RC=false" BUT you *aren't* providing a complete configuration, the default config sets up the various columns and bindings. So either complete your `rc.conf` or simply stop setting that variable : )

**Comment by keeganjk** [comment]
Yes, that seemed to be the issue. I guess I didn't realize that `rc.conf` needed "everything" to be set, and rather thought that I could only define a few things with it.

**Comment by toonn** [comment]
You can. You just can't do that *and* tell ranger not to load the default settings.

**Comment by keeganjk** [comment]
So if one has `export RANGER_LOAD_DEFAULT_RC=TRUE` and also adds custom values to `rc.conf`, it will load the default `rc.conf` and then override a few select values with the custom one?

**Comment by toonn** [comment]
Maybe. Though not setting the variable at all is probably less confusing.
