### ISSUE TITLE
No image preview when using tmux 

### ISSUE THREAD

**Issue by lsli0116** [ranger/ranger#2329]
Hi everyone, I use ranger in `iterm2` on `macOS` and it works fine under no `tmux` running circumstance. But when runing `tmux`, no image preview in `tmux` terminal when I use ranger, it's really strange and I don't know how to fix it.

**Comment by toonn** [comment]
Most methods aren't compatible with tmux. You could search our issue tracker because I vaguely remember someone getting it to work, kind of, with iTerm2. But this is not something we can fix unfortunately.
