### ISSUE TITLE
Hardcoding "$EDITOR" and "$PAGER" with `--` in riffle.conf is confusing for new users.

### ISSUE THREAD

**Issue by stroobandt** [ranger/ranger#233]
Hardcoding `"$EDITOR"` and `"$PAGER"` with `--` in `riffle.conf` is confusing for new users and should be refrained from. Even worse, this «feature» is not documented.

The `--` string should be removed by default. It should be up to the user to include this in either `$EDITOR` or his/her own copy of `riffle.conf`under `~/.config/ranger`.

Finally, here is proof that I am not alone in experiencing this as an undocumented inconvenience:
https://bbs.archlinux.org/viewtopic.php?pid=1275688

**Comment by hut** [comment]
I was about to tell you about the security implications, until I realized that `--` is not needed anymore, since ranger now passes absolute paths to commands. So I don't see any reason to keep it there, for *any* command.

Any objections, anyone?

**Comment by Vifon** [comment]
Personally I'd keep it as it does no harm and if you'll change the form of the passed paths in the future, you may forget to add the `--` back (just like right now with its removal). Just my $0.02.

**Comment by serge-stroobandt** [comment]
Even though I prefer it would go, at the very least it should be properly documented and mentioned in the help. As a newcomer, I had to search a bunch of sites to know what is going on. This is not really welcoming. This basic functionality should work out of the box, independently of the desktop one is using.

**Comment by nfnty** [comment]
It guards against files starting with `-`. `--` is documented all over the web and in almost every single man page.
