### ISSUE TITLE
Ranger doesn't resize properly

### ISSUE THREAD

**Issue by Haku55** [ranger/ranger#2333]
Hi, everybody! Whenever I resize my terminal (which is currently alacritty) ranger doesn't seem to resize with it. I think I've found a fix for it here before, but I reinstalled my OS and doesn't seem to find that fix anymore. Thanks for any advice, in advance!

**Comment by toonn** [comment]
Not sure about a real fix. Try <c-l> or <c-r>.

I think the real problem is either alacritty not properly sending SIGWINCH or ranger not properly reacting to the signal.
