### ISSUE TITLE
idea about template expansion

### ISSUE THREAD

**Issue by hektr** [ranger/ranger#2334]
:filter command works with substring/filename, but linux shell also understands templates and expands them by default. May be it could be useful also for :filter command in ranger. What do you think??

**Comment by toonn** [comment]
Hmm, examples? We support regular expressions iirc. Maybe that covers the same  usecase?

**Comment by hektr** [comment]
Aha, I've understood. I can use scout command, if I need regular expressions or globs.

**Comment by toonn** [comment]
And the newer `filter_stack` machinery also supports REs in the filename filter.

Note that I didn't mean "let's not do this." If the UX is better with shell templates it could be a cool addition.

**Comment by hektr** [comment]
I tried `:filter -g *.jpg`, but it's now working.

**Comment by toonn** [comment]
Ah, I guess that's because it's already a regex match. We do substring matching with something like `.*yourstrong.*` : )

**Comment by hektr** [comment]
Aha, that's good :+1:  It's needed to update man page and help file :)
