### ISSUE TITLE
MacOS v1.9.3 does not refresh after changes

### ISSUE THREAD

**Issue by marius-m** [ranger/ranger#2338]
#### Runtime Environment

- Operating system and version: macOS Catalina 10.15.7
- Terminal emulator and version: iTerm3 3.4
- Python version: 2.7.16 (default, Jun  5 2020, 22:59:21) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-)
- Ranger version/commit: ranger 1.9.3
- Locale: None.None

#### Current Behavior
In newest version (currenly 1.9.3), after any action the content does not refresh automatically. Always need to do this manually (Shift + R). 

For ex.: Move / rename files, need to do Shift+R to refresh content in the folder. 

Just installed older version (1.9.2), it does not have this issue. So something got a bit broken in between. 

#### Expected Behavior
After rename / move / copy I'd expect to see content refreshed. 

#### Possible Solutions
1. Currenly downgrading manually a version helps
2. Maybe there could be an option to install explicit version from "Homebrew" ?

#### Steps to reproduce
1. Rename folder
2. Folder remains the same name as before (even if technically its name was changed)
3. Do manual refresh (shift + R) would refresh content

**Comment by toonn** [comment]
Hmm, I can't reproduce this. Maybe it's related to Catalina? Can you describe how to reproduce the issue in as few steps as possible?

**Comment by marius-m** [comment]
Okay, I'm in such a loss. 

Just upgraded to newer version that had this issue (1.9.3). Created a folder structure, started OBS to record, installed KeyCastr (shows button presses on screen), started to rename things and *everything seems to work*. 

I have to restart my computer every now and then 🤦 And upgrade to newer version for that matter. 

Thanks for a response, probably it was a /my computer/ problem, not the software. Love the tool!

**Comment by toonn** [comment]
That's the best kind of issue! : )
