### ISSUE TITLE
Ranger resets color scheme set with pywal

### ISSUE THREAD

**Issue by salteax** [ranger/ranger#2350]
Ranger often (for example after opening a file and then going back) resets the colorscheme of my terminal to its default which messes some things up. Is there a way to prevent this?

**Comment by toonn** [comment]
Ranger does no such thing. There's a previous closed issue on this, don't remember the details you'll have to carefully search past issues.

Pywal doesn't actually properly change your terminal's theme. It just echoes some escape codes that change the colors. I think it was something to do with the terminal resetting or subprocesses that resets them.
