### ISSUE TITLE
enhancement: shift + space to mark file and move *up*

### ISSUE THREAD

**Issue by scottkosty** [ranger/ranger#2357]
#### Current Behavior

When I press <kbd>Space</kbd> key, the file is marked and the cursor moves down. If I hold the modifier <kbd>Shift</kbd> while pressing <kbd>Space</kbd> the behavior is the same.

#### Expected Behavior

It would be nice for the modifier <kbd>Shift</kbd> to cause the cursor to move up.

#### Context
I often want to select contiguous files. Sometimes I happen to be at the beginning, but sometimes I happen to be at the end.

I'm sure I could add a local keybinding that would accomplish this, but I'm wondering if other Ranger users would be interested in this feature as well.

Thanks for all of your work on Ranger!

**Comment by toonn** [comment]
I'm actually not sure you can map this. Terminals are weird and S-space is one of the quirks IIRC.

**Comment by scottkosty** [comment]
> I'm actually not sure you can map this. Terminals are weird and S-space is one of the quirks IIRC.

Ah good to know. In that case, we might want to close this.

Than you for the quick reply!

**Comment by toonn** [comment]
Yeah, [even Vim can't do it](https://www.reddit.com/r/vim/comments/eg3bkc/mapping_shift_space_to_esc/), that doesn't make me hopeful : /

Emacs might have a trick but since we're tied to ncurses it may not even help us.
