### ISSUE TITLE
AttributeError: 'str' object has no attribute 'path' , ERROR when try to move selected data to trash

### ISSUE THREAD

**Issue by ghost** [ranger/ranger#2361]
when i try to remove a file/folder to trash using dT and i confirm using Y i face an error 
![image](https://user-images.githubusercontent.com/85073629/122109088-e1ecea80-ce14-11eb-9eb6-20fa1f066a34.png)

**Comment by toonn** [comment]
Could you try ranger from the master branch? I think this issue was fixed.

**Comment by manujchandra** [comment]
I think I fixed it with [this](https://github.com/ranger/ranger/issues/1798#issuecomment-805301717).

until fixed here a hack which works for me:

File "/usr/lib/python3.8/site-packages/ranger/core/actions.py", line 459, in <listcomp>
`    filenames = [f.path for f in files]`
change the line to

`   filenames = [f if isinstance(f, str) else f.path for f in files]`
Use at your own risk though, no guarantees.

Credit : @AXGKl

**Comment by lyhxiangyang** [comment]
> I think I fixed it with [this](https://github.com/ranger/ranger/issues/1798#issuecomment-805301717).
> 
> until fixed here a hack which works for me:
> 
> File "/usr/lib/python3.8/site-packages/ranger/core/actions.py", line 459, in 
> ` filenames = [f.path for f in files]`
> change the line to
> 
> ` filenames = [f if isinstance(f, str) else f.path for f in files]`
> Use at your own risk though, no guarantees.
> 
> Credit : @AXGKl

soloved this bug.

**Comment by toonn** [comment]
Why not simply run the master branch of ranger? There's no need to maintain a separate patch.

**Comment by AlbeyAmakiir** [comment]
Presumably because when the new release makes it to the package manager on their distro, that'll automatically remove the need to manually update it via git. A crash like this seems like the kind of thing that would demand a quick fix release (especially since the bug tells users to come here and make a new issue).

I came here because I have the same issue.

**Comment by toonn** [comment]
The release has been anything but quick. We have a severe shortage of round tuits, donations welcome.

**Comment by z0xyz** [comment]
@manujchandra
Thanks for the fix , but the file path was "/usr/lib/python3/dist-packages/ranger/core/actions.py" for me

**Comment by maxreuben** [comment]
@manujchandra The workaround you mentioned doesn't seem to trash the files but delete them permanently. I wasn't able to see the trashed file in my Trash folder.  I'm running ranger with sudo on Fedora 34.

**Comment by manujchandra** [comment]
@maxreuben 

I am running the master branch 

```
ranger version: ranger-master
Python version: 3.10.0 (default, Oct  4 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
Locale: en_US.UTF-8
```

And I am not experiencing this issue. Are you getting any errors?

**Comment by maxreuben** [comment]
@manujchandra 
I just switched to ranger-master. When i run ranger.py, everything seems to be working correctly, image previews, file previews and trash-put. However, after doing sudo make install, ranger command is acting weird, no previews of any kind, not using the preview script, not even my .vimrc is being loaded. I copied my local config to the root config but to no avail. How do I uninstall ranger after building it from source? sudo make uninstall does nothing. For the time being, I've aliased ranger.py to ranger in my .bashrc

**Comment by manujchandra** [comment]
I am glad it got resolved.

**Comment by Friptick** [comment]
Getting this on Ubuntu 20 LTS. So: v1.9.3, Py 3.8.10

Is a fix on the way?

**Comment by toonn** [comment]
@Friptick, yes, eventually at some point.

@maxreuben, by default an install log is generated in `install_log.txt` that'd be the easiest way to reverse the install. If you don't have that you'll have to check what the `setup.py` does.

**Comment by fesnavarro** [comment]
ranger version: ranger 1.9.3
Python version: 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
Locale: en_AU.UTF-8

We still don't solve it

**Comment by markus-bauer** [comment]
@fesnavarro 
Have you tried the master branch like suggested?

**Comment by fesnavarro** [comment]
> @fesnavarro Have you tried the master branch like suggested?

All good, did the workaround mentioned here https://github.com/ranger/ranger/issues/2361#issuecomment-888886168

**Comment by rcrx** [comment]
Used the [above fix](https://github.com/ranger/ranger/issues/2361#issuecomment-923807542) but had to alter `/usr/lib/python3/dist-packages/ranger/core/actions.py`

Before anybody starts hollering about the master branch, I'm using the native package in my distro's official repo.

**Comment by rcrx** [comment]
Going to have to amend that. The fix wasn't actually a fix, it perma-deletes the file instead of sending it to the trash. The work around I came up with for now was to create a file `/usr/bin/trash` (marked executable) with
```
#!/bin/bash

mv $1 -t $HOME/.local/share/Trash/files/
```
I can then `!<cr>` `trash <tab>` in ranger... this does technically work.

**Comment by toonn** [comment]
Should be fixed on the master branch.

**Comment by cskeeters** [comment]
The ability to move files to the Trash is important to me since I'm just learning ranger and don't want to make any mistakes that result in data loss.

For anyone running homebrew, you can switch to master without much fuss with:

    brew install --HEAD ranger

**Comment by clst** [comment]
It looks to me like the current stable build includes the old trash command. I am experiencing the issue again as well.

This pull request probably got lost sometime: https://github.com/ranger/ranger/pull/1871/commits

See here: https://github.com/ranger/ranger/blame/55fc2839f693aed9486d211694d7317d78161341/ranger/config/commands.py#L730
