### ISSUE TITLE
Command not found:  `search_previous`

### ISSUE THREAD

**Issue by ysl2** [ranger/ranger#2363]
![image](https://user-images.githubusercontent.com/39717545/122153606-e9a0a380-ce95-11eb-8d78-d679a01829d6.png)

Could you please help me? Thanks :-)

**Comment by toonn** [comment]
I'm not sure where you found that command? Ranger uses `:search_next forward=False`, mapped to `N` by default.

**Comment by ysl2** [comment]
Thank you, maybe I modified this previously, and I didn't realize it. Things has been solved now. :-)
