### ISSUE TITLE
`source ranger` only works on second invocation, problem with zle_bracketed_aste

### ISSUE THREAD

**Issue by MehdiSaffar** [ranger/ranger#2364]
#### Runtime Environment

- Operating system and version: Ubuntu 21.04
- Terminal emulator and version: Kitty 0.19.1
- Shell: zsh 5.8 (x86_64-ubuntu-linux-gnu)
- ZSH plugins: oh-my-zsh with 
```
plugins=(
  zsh-nvm
  git
  zsh-syntax-highlighting
  zsh-autosuggestions
  tmux
  timer
  safe-paste
  ripgrep
  history-substring-search
)
```
- Python version: 3.9.5
- Ranger version/commit: 1..9.3
- Locale: en_US.UTF-8

#### Current Behavior
In a new zsh shell:
- First invocation of `source ranger` gives error: `/usr/bin/ranger:17: command not found: zle_bracketed_paste`
- 2.+ invocation of `source ranger` works.

#### Expected Behavior

`source ranger` works everytime.

#### Context

Annoying. I have to type `source ranger` at least twice for it to work anytime I open a shell.

**Comment by toonn** [comment]
I think this is a problem with your shell. The ranger polyglot doesn't invoke `zle_bracketed_paste` so I don't know why it's erroring about that not being found.

A workaround might be to add a function to achieve the cd behavior you want, similar to [this function](https://github.com/ranger/ranger/blob/master/examples/shell_automatic_cd.sh).

**Comment by MehdiSaffar** [comment]
Thanks, I will try that
