### ISSUE TITLE
problem with djvu files, if image preview is enabled

### ISSUE THREAD

**Issue by hektr** [ranger/ranger#2366]
Ranger works with djvu-files, like they are images, if image preview is enabled. It runs ` identify -format '%[EXIF:Orientation]` and it takes about 300 Mb of RAM on each djvu file. If you go across list, consisting of 15-20 djvu files with enabled image preview, your system will die :(

**Comment by toonn** [comment]
Hmm, we've had performance problems with imagemagick before. Maybe we should just disable that on certain extensions, like djvu.

**Comment by heinwol** [comment]
For those who struggle with this issue: I've come up with a workaround. One should edit scope.sh and put the following lines inside the case statement of the `handle_image()` function (somewhere around line 140 as of july 2022):
```
        image/vnd.djvu)
            exit 1;;

```
Then no djvu preview at all will be displayed.

**Comment by toonn** [comment]
Testing of #2743 would be appreciated.

**Comment by peskovdev** [comment]
I fix by adding this in handle_image:
```sh
        image/vnd.djvu)
            ddjvu -format=tiff -quality=90 -page=1 -size="${DEFAULT_SIZE}" \
                  - "${IMAGE_CACHE_PATH}" < "${FILE_PATH}" \
                  && exit 6 || exit 1;;
```
