### ISSUE TITLE
Freezing due to unavailable network resource

### ISSUE THREAD

**Issue by yash-fn** [ranger/ranger#2367]
#### Runtime Environment

ranger version: ranger 1.9.3
Python version: 3.8.5 (default, May 27 2021, 13:30:53) [GCC 9.3.0]
Locale: en_US.UTF-8

#### Current Behavior
I have a folder in user directory with symlinks to an autofs mount to a samba server in `/mnt`. i.e. `/home/user/cloud/samba` points to `/mnt/samba` . Samba server is temporarily down for maintenance. Thus, autofs freezes any request to view `/mnt/samba` until timeout which is a lengthy 10 seconds. 

Let's say I have 3 folders:
```
Apps
cloud
documents
```

Starting ranger selection rests on `Apps`. If I press J (thereby listing contents of `cloud` folder with symlinks to downed network resource) ranger completely freezes until the 10 second timeout. Cannot escape or anything. If instead of one J I press J twice in rapid succession, the program still freezes despite pressing J twice essentially is same as pressing 2J (which works perfectly and skips loading `cloud` folder). 

#### Expected Behavior
It would be nice if while waiting for a networked, or even local, resource to return a value that ranger still be able to process the next motion command if one is present. i.e. Pressing J once will attempt to load `cloud` folder, but before 10 second timeout if user presses J again, ranger immediately aborts its attempt to load `cloud` folder and goes to process the `documents` folder. I.e. pressing J twice should equal pressing 2J behavior in that loading of `cloud` folder is aborted or skipped. Alternately, at a minimum, ranger should offer me the ability to at least cancel any active attempt to load the current folder (perhaps by processing control-c as a command to abort the current attempt to load a resource). 

GUI-based browsers such as gnome files app currently allows me to abort the attempt to load the unavailable network drive in that if I press back before `cloud` folder loads, it does so immediately.  

#### Context

This is problematic because navigation of networked folders becomes extremely slow and cumbersome forcing me to resort to using GUI based browsers which allow me to abort active attempts. Even is resource is present, sometimes network delays can add to delay as well.
 
#### Possible Solutions
I'm a beginner computer science student so I know basically nothing right now, but maybe if there is a way to treat any keyboard presses during the attempt to load a resource as an escape/interrupt character whereby if the keypress actually translates to a valid command that precludes having the process the current request then it aborts the current request and moves to processing the next request. Similar to how Control-C aborts most programs except this case instead of exiting it simply aborts the current request.
#### Steps to reproduce
1. Pressing any movement command that passes through an unavailable network resource freezes entire program until network process times out. 

#### Traceback

```
No crash. Just freeze until timeout.
```

**Comment by toonn** [comment]
This is a known issue. Please search the issue tracker so we can cross-reference them.. We'd be happy to assist you in tackling this. Though the real answer is probably that we need asynchronous processing and that's a PITA to retrofit.

**Comment by yash-fn** [comment]
Sounds good. When I get the time I can try to see if I can help in some way. Thanks.
