### ISSUE TITLE
How do I open Ranger

### ISSUE THREAD

**Issue by yyy33** [ranger/ranger#2368]
After I install range with PIP, how should I open range. Run the Ranger command directly, indicating that there is no such command.
Thank you for your help

**Comment by Rom1deTroyes** [comment]
Have you installed by `pip install ranger-fm`, and run `ranger` ?
Because, if you `pip install ranger` and run `range` it may not working as expected...
BTW, depending of your shell, you may have to update the available binary list (relaunching the shell is the simplest way).

**Comment by yyy33** [comment]
I restart the machine, but I still can't.

````
❯ pip show ranger-fm                                               Name: ranger-fm
Version: 1.9.3
Summary: Vim-like file manager
Home-page: https://ranger.github.io
Author: Roman Zimbelmann
Author-email: hut@hut.pm
License: GPL3
Location: /home/yyy/.local/lib/python3.9/site-packages
Requires:
Required-by:

**Comment by yyy33** [comment]
````
❯ ranger                                                           
zsh: command not found: ranger
````

**Comment by toonn** [comment]
Do other pip-installed programs work? I suspect the right directories are just not on your PATH.

**Comment by chu4ng** [comment]
>/home/yyy/.local/lib/python3.9/site-packages

I think here is trouble. You may be should install ranger under root.
Also could you show your $PATH var. I think you can just add $HOME/.local/bin(or something like that) in your PATH definition.

**Comment by yyy33** [comment]
Thank you brothers, I found the binary file in $HOME/.local/bin.
