### ISSUE TITLE
How to reorder tabs?

### ISSUE THREAD

**Issue by tkossak** [ranger/ranger#2371]
Hi, is it possible to reorder tabs? For example: move current tab one place right, so it becomes number 4 instead of 3 (and 4'th tab becomes 3'rd now).

**Comment by toonn** [comment]
Yes, `:tab_shift` bound to `<alt>l/r`.

This is the kind of question that's better suited to our subreddit r/ranger. That way more people can help you and find out about the feature : )

**Comment by tkossak** [comment]
Thank you very much :)
