### ISSUE TITLE
What is method number combined with `l`? How to disable it or set it?

### ISSUE THREAD

**Issue by deeperlearner** [ranger/ranger#2377]
#### Runtime Environment

- Operating system and version: Ubuntu 18.04.5 LTS
- Terminal emulator and version: tmux
ranger version: ranger-master
Python version: 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]
Locale: en_US.UTF-8

#### Current Behavior
When using `4` + `l`: `trash-put` the file, `5` + `l`: `rm` the file. I accidently type the commands and it removed my file...
If I press `[6-9]` + `l`, it shows: `Method number [6-9] is undefined.`
I can not find any documentation about this.

#### Expected Behavior
Disable it or map it to other function.

**Comment by toonn** [comment]
If you press `r` you'll see where they're coming from. The only way to disable the behavior is to redefine the command in `commands.py` and make it ignore the "narg." (If that's possible, I'm not 100% sure you can create commands to shadow existing ones like that.)

**Comment by deeperlearner** [comment]
I see. It mv file to ranger/trash. Not rm it.
