### ISSUE TITLE
Preview color inconsistency

### ISSUE THREAD

**Issue by miskiewiczm** [ranger/ranger#2379]
I have noticed some preview color inconsistency:
The first image is taken from pure bat with nord theme:
<img width="812" alt="Zrzut ekranu 2021-06-27 o 12 38 21" src="https://user-images.githubusercontent.com/72819516/123541482-1af65a80-d745-11eb-933b-584438f7cf9e.png">
The second one is taken form ranger preview window (ranger uses bat to generate preview)
<img width="799" alt="Zrzut ekranu 2021-06-27 o 12 39 12" src="https://user-images.githubusercontent.com/72819516/123541500-3bbeb000-d745-11eb-9a89-1fd41807827b.png">

I woul like to ask about the colors in both previews - they are not the same. I have realized thet problem is related to the `COLORTERM` variable, but when i change teh value of the `COOLORTERM` (for example to `truecolor`), highlight colors dissapear. The same problems comes with other syntax highlighters like highlight or pygmentize.
I use iTerm2.

**Comment by toonn** [comment]
Yep, unfortunately python's curses doesn't support truecolor.
