### ISSUE TITLE
Editing readmi file

### ISSUE THREAD

**Issue by hektr** [ranger/ranger#2382]
It would be good to add on README.md file information about bad performance in the case of installing/enabling mediainfo/exiftool or may be other tools for previewing non-text files. Ranger looks for metadata of any media file, using exiftool, if you have it installed. So, it consumes a time and resources and makes ranger much slower.

**Comment by toonn** [comment]
I'm not sure this warrants a mention in the README. All previews can impact performance. If you can show that the slow down is egregious we could disable the previews by default.
