### ISSUE TITLE
Official user guide wiki translated to Spanish

### ISSUE THREAD

**Issue by victorhck** [ranger/ranger#2383]
Hello!

I was reading the [Official user guide](https://github.com/ranger/ranger/wiki/Official-User-Guide) and at same time I learnt about Ranger, also wanted to translate to es_ES. Maybe someone can found it useful. 

Didn't know if this translations are allowed in official Wiki, so I upload to my forked repo. 

[Here you have](https://github.com/victorhck/ranger/wiki/Gu%C3%ADa-oficial-del-usuario) if you want the text and use it in your own Wiki

Greetings!

**Comment by toonn** [comment]
Afaiu wiki pages are fairly insular. So two different language wikis could co-exist without much problems. If you found it useful, feel free to link to it from our wiki overview page. Whether or not you move the pages over is up to you.

**Comment by victorhck** [comment]
Ok, so added a new wiki page with [spanish translation](https://github.com/ranger/ranger/wiki/Gu%C3%ADa-oficial-del-usuario)
Thanks for your work!
Close the issue.
