### ISSUE TITLE
Backwards Compatibility with old configs

### ISSUE THREAD

**Issue by cab-1729** [ranger/ranger#2386]
#### Runtime Environment

- Operating system and version: OpenSuse Leap 15.2 on wsl
- Terminal emulator and version: wsl 1
- Python version: 3.6
#### Context
This might a be a stupid question. I'm new to this stuff.
I've recently updated ranger but when I use my previous configs, ranger gives a ton of errors. Is there any way to make old configs compatible or do I have to edit the new ones from scratch? Also, is there anyway to make my configs work again when I'm switching distros or moving to another machine (besides saving the source code)?

**Comment by toonn** [comment]
We try to maintain backwards compatibility so I suspect you're upgrading from a very old version. There's nothing to make it easier, no. You can have an rc.conf that only sets the things you want diverging from the defaults then porting takes the minimum amount of effort.

**Comment by cab-1729** [comment]
I installed it about a week or two ago, then again today. I didn't use git however, used my package manager (zypper) instead, so it might not have been the latest version at the time. Anyways, thanks, I guess I have to go through the rc again.
