### ISSUE TITLE
Ranger crashes when --datadir option is specified and tagged file is absent

### ISSUE THREAD

**Issue by jeenuv** [ranger/ranger#2388]
#### Runtime Environment
- Operating system and version: Linux
- Terminal emulator and version: PuTTY
- Python version: 2.7.5

Ranger crashes when invoked with `--datadir` if the directory doesn't contain a file named `tagged`. The trace is below. If the directory does contain such a file, `ranger` works fine.

This happens when run from `master`.

```
ranger version: ranger-master v1.9.3-231-g8181077f
Python version: 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Locale: None.None

Traceback (most recent call last):
  File "/users/is/jviswambharan/sources/ranger/ranger/core/main.py", line 173, in main
    fm.initialize()
  File "/users/is/jviswambharan/sources/ranger/ranger/core/fm.py", line 116, in initialize
    self.tags = Tags(self.datapath('tagged'))
  File "/users/is/jviswambharan/sources/ranger/ranger/container/tags.py", line 28, in __init__
    self.sync()
  File "/users/is/jviswambharan/sources/ranger/ranger/container/tags.py", line 81, in sync
    fobj = open(self._filename, 'r')
IOError: [Errno 2] No such file or directory: '/users/is/jviswambharan/tagged'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by chu4ng** [comment]
I don't have this problem. If there is no tags/history/etc files, ranger will create they.
I'm not sure, but can you try with 3.* python version?

**Comment by jeenuv** [comment]
You're right. This crash seems to happen on on Python 2. Python 3 on `master` seems to be happy.

**Comment by chu4ng** [comment]
@jeenuv Do branch #2389 resolve this error for you?

**Comment by jeenuv** [comment]
Thanks. That PR works with Python2, which was previously crashing.
