### ISSUE TITLE
image preview now working with Ueberzug, with Alacritty in arch linux

### ISSUE THREAD

**Issue by felipejoribeiro** [ranger/ranger#2392]
#### Runtime Environment

- Operating system and version: 5.12.15-arch1-1
- Terminal emulator and version: alacritty 0.8.0 (a1b13e68)
- Python version: Python 3.9.6
- Ranger version/commit: ranger 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
Can´t see image previews on the terminal. Everything was fine but suddenly stop working. I use the `ueberzug` method for image preview and was working very well. Can´t tell when it stoped working and wy. Can´t fine logs from the error, the images simply don´t show up in the preview section:

![image](https://user-images.githubusercontent.com/39244876/125355269-32376980-e33b-11eb-97c1-13e1543788b7.png)

On kitty i can make it work using w3m, but only with full terminal opacity. Would really like to use with ueberzug in alacritty.

#### Expected Behavior
Images to show up as usual.

**Comment by toonn** [comment]
Kitty has a native method, try that.
Does ueberzug work for you outside of ranger?
Try downgrading alacritty and/or python.

**Comment by felipejoribeiro** [comment]
Thank you! Trying the Ueberzug outside ranger was the best advice.
I managed to solve the problem. 
I tried to identify the issue running  minimal working Ueberzug routine with the following code:

```bash
ueberzug layer --parser bash 0< <(
    declare -Ap add_command=([action]="add" [identifier]="example0" [x]="0" [y]="0" [path]="/home/fejori/downloads/GrandTeton.jpeg")
    declare -Ap add_command=([action]="add" [identifier]="example1" [x]="10" [y]="0" [path]="/home/fejori/downloads/GrandTeton.jpeg")
    sleep 5
    declare -Ap remove_command=([action]="remove" [identifier]="example0")
    sleep 5
)
```

And the following error message appeared:

```
Traceback (most recent call last):
  File "/usr/bin/mousetrap", line 11, in <module>
    load_entry_point('mousetrap==3.0.4', 'console_scripts', 'mousetrap')()
  File "/usr/lib/python3.6/site-packages/mousetrap/mousetrap.py", line 30, in main
    display = Display()
  File "/usr/lib/python3.6/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3.6/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/lib/python3.6/site-packages/Xlib/protocol/display.py", line 160, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":1.0": b'Invalid MIT-MAGIC-COOKIE-1 key
```

Not this one, this is the one i found in the internet wile researching the problem, but was identical only changing software versions.

The solutions was running the following command:

```
xhost +local: 
```
Here is the link with the complete discussion:

https://unix.stackexchange.com/questions/199891/invalid-mit-magic-cookie-1-key-when-trying-to-run-program-remotely
