### ISSUE TITLE
copy/cut/paste freezes ranger until the transfer completes

### ISSUE THREAD

**Issue by ledti** [ranger/ranger#240]
I've noticed that when I copy `yy` or cut `dd` files and then paste `pp` them to mounted USB devices with slow read/write access (microSD cards), ranger will generally freeze or stutter until the transfer completes. The devices in question are formatted to fat32 (vfat).

I _don't_ see similar behavior when transferring files across faster hard drives/solid state disks. In that scenario, everything works fine.

I'm using the latest development version, but the same behavior happens with stable.

**Comment by tex** [comment]
I noticed it too... Sometimes the job gets to work queue in which case it doesn't block, but sometimes it doesn't in which case it blocks...

**Comment by tex** [comment]
One/several big files are queued in work queue and doesn't block, lots of small files are not and blocks.

**Comment by hut** [comment]
Ranger is not a threaded program, and as such, it switches between a blocking "work" mode and a "gui" mode that deals with user input. There will always be some amount of blocking until the input/output code is completely isolated from the user interface.

@tex for me, all copying operations are added to the queue, even if it's many small files.

**Comment by notEvil** [comment]
I also had a stuttering/little repsonsive ranger session a while ago, using sshfs over low bandwidth connection. However, I don't think that @hut can do much about it. FS ops are blocking, and this becomes an issue when multiple ops target the same file/directory. So when pasting something, it does make sense to switch the directory so ranger won't update file size or directory structure every millisecond.

Recently I moved the read/write code into a seperate thread, but with indecisive results. Maybe some of you want to try and tell if it helped. You find it there:
https://github.com/notEvil/ranger-ext/tree/master/experimental/copy%20thread

**Comment by hut** [comment]
Back then, copying/moving happened in a separate process because ranger just called `cp` or `mv` to do the job. This feature was replaced in 19995fd134ac40c940e05e091246e384bbd2e3b1 with built in python code, for compatibility (the `cp` on BSD was insufficient for rangers use case) and in order to get progress information. For users who don't care about those things, we could add this feature back in as an option.

**Comment by nfnty** [comment]
Continue discussion in #151.
