### ISSUE TITLE
Image preview not working with kitty

### ISSUE THREAD

**Issue by pkail** [ranger/ranger#2408]
Describe the bug
There is no preview window.

To Reproduce
Highlight .png file in Ranger.

ranger-stable 1.8.1
kitty 0.22.2
Installed pillow 8.3.1
ImageMagick 7.1.0-4 Q16 x86_64

Environment details
In rc.config:
set preview_images true
set preview_images_method kitty

Tried starting kitty with --config NONE, but got the same result.
kitty +kitten icat image.jpeg works (i.e., I can display an image in kitty).

**Comment by toonn** [comment]
Pretty sure that ranger version's too old.

**Comment by pkail** [comment]
You are right!  I didn't check that.  I'll try to find the latest version.  Thanks!

**Comment by bcorneglio** [comment]
what's the value of $TERM?
