### ISSUE TITLE
Tab command names are not consistent with vim ones

### ISSUE THREAD

**Issue by thiagowfx** [ranger/ranger#2412]
#### Runtime Environment

- Operating system and version: Arch Linux
- Terminal emulator and version: N/A
- Python version: 3.9.6
- Ranger version/commit: 1.9.3
- Locale: `en_US`

#### Current Behavior

Tab commands are: `:tab_new`, `:tab_close`, etc - **with underscores**.

#### Expected Behavior

Ranger should be more consistent with vim commands: `:tabnew`, `:tabclose`, etc - **without underscores**.

Why? Because ranger shortcuts and commands are heavily based on vim ones. This inconsistency makes it harder to work with ranger out-of-the-box.

Workaround: Users can currently define their own aliases in their ranger config in order to mitigate this.

#### How to resolve this

A few options:

- Add aliases e.g. so that `tabnew=tab_new`, and so on.
- Add built-in commands e.g. so that a `tabnew` function just proxies to `tab_new`.

**Comment by thiagowfx** [comment]
If you let me know how you prefer to proceed (aliases, built-in commands, or another solution), I am happy to send a contribution to fix this behavior.

**Comment by toonn** [comment]
I'd be fine with commands. That way people who disable loading the default `rc.conf` will still get the change and I don't think claiming that part of the namespace is egregious.
