### ISSUE TITLE
devicons2 does not display 

### ISSUE THREAD

**Issue by p1k0pan** [ranger/ranger#2417]
#### Runtime Environment

- Operating system and version:  archlinux 5.13.9
- Terminal emulator and version: st 0.8.2
- Python version: 3.9.6
- Ranger version/commit: 1.9.3
- Locale: None.None

#### Current Behavior
I have followed the guide from devicons2  ,
1. clone the repo 
2. add the script in my rc.conf
3. install nerd-font (sauce code pro nerd font)
4. change my st terminal default font to nerd font ( I have even changed my system default font)
#### Expected Behavior
my ranger should show devicons after I follow the guide completely

**Comment by toonn** [comment]
The plugin developer will probably know more.

**Comment by p1k0pan** [comment]
ok I will ask them
