### ISSUE TITLE
How to get highlighted folder and copy selection to it?

### ISSUE THREAD

**Issue by manujchandra** [ranger/ranger#2418]
Hello,

I have a mapping as follows:

`map ycf shell -f cp --backup=numbered %s %f`

What is does is that it copies selected files to the highlighted folder. I wish to achieve the same using a command.

I got the following code from GitHub (cant remember where):

`class moveselected(Command):`

    def execute(self):
        cwd = self.fm.thisdir
        cf = self.fm.thisfile
        if not cwd or not cf:
            self.fm.notify("Error: no file(s) selected", bad=True)
            return
        files = [f for f in self.fm.thistab.get_selection()]

        target_dir = self.rest(1)
        if not target_dir:
            self.fm.notify("Error: target directory not specified", bad=True)
            return

        from os.path import join, expanduser, lexists
        from os import makedirs
        target_dir = join(self.fm.thisdir.path, expanduser(target_dir))
        if not lexists(target_dir):
            makedirs(target_dir)
        for f in files:
            self.fm.rename(f, join(target_dir, f.relative_path))

    def tab(self):
        return self._tab_directory_content()

I want to know, 
1) How to get the highlighted folder (%f) in python? (similar to self.fm.thisdir)
2) How to copy to a folder using self.fm.??? into that folder?

Thanks in advance

**Comment by toonn** [comment]
1.  `self.fm.thisfile.relative_path`
2. It's the `:copy` defined in `ranger/core/actions.py`, so just `self.fm.copy(...)` IIRC.

**Comment by manujchandra** [comment]
Hi,

Thanks for the reply. I have been able to get this far:

`class copy_selected_to_highlight(Command):`
  `  """:copy_selected_to_highlight"""`

    def execute(self):
        files = [f for f in self.fm.thistab.get_selection()]

        # Get highlighted directory
        target_dir = self.fm.thisfile.relative_path

        if not target_dir:
            self.fm.notify("Error: target directory not highlighted", bad=True)
            return

        from os.path import join, expanduser
        target_dir = join(self.fm.thisdir.path, expanduser(target_dir))

        for f in files:
            self.fm.copy(f, join(target_dir, f.relative_path))

I have printed and checked all the paths seem correct.

But the moment I enable this line: `self.fm.copy(f, join(target_dir, f.relative_path))` I get this error:

![Screenshot from 2021-08-16 18-49-27](https://user-images.githubusercontent.com/15191493/129572945-5e95bc6a-1ca6-41aa-a38d-e3c19944d49b.png)

Not sure how to copy. Thanks.

**Comment by toonn** [comment]
Grep the ranger codebase, it's used there. The error isn't even about the copy function but about concatenating a `str` and an `int`. I'm not sure where the int is coming from though.

**Comment by manujchandra** [comment]
HI, I will be grateful if someone can share an example of how `self.fm.copy(...)` is used. I am unable to search for it. Because I have tried many combinations of using it, but it always comes up with the same error.

**Comment by toonn** [comment]
Oh, you want to use `:paste` instead. You don't actually want to copy stuff into the copy_buffer.

**Comment by manujchandra** [comment]
Hi,

I tried this

```
def execute(self):
    files = [f for f in self.fm.thistab.get_selection()]

    # Get highlighted directory
    target_dir = self.fm.thisfile.relative_path

    if not target_dir:
        self.fm.notify("Error: target directory not highlighted", bad=True)
        return

    from os.path import join, expanduser
    target_dir = join(self.fm.thisdir.path, expanduser(target_dir))

    for f in files:
        self.fm.paste(f, join(target_dir, f.relative_path))

AND

self.fm.paste(f, target_dir)


```

but no luck. I dont get any error also.

**Comment by toonn** [comment]
You can't just guess at the argument order. [Here's the definition site](https://github.com/ranger/ranger/blob/master/ranger/core/actions.py#L1581).

**Comment by manujchandra** [comment]
Thanks @toonn 

I was able to make it work using:

```

class copy_selected_to_highlight(Command):
    """:copy_selected_to_highlight"""

    def execute(self):
        # Get highlighted directory
        target_dir = self.fm.thisfile.relative_path

        if not target_dir:
            self.fm.notify("Error: target directory not highlighted", bad=True)
            return

        from os.path import join, expanduser
        target_dir = join(self.fm.thisdir.path, expanduser(target_dir))

        self.fm.execute_console("copy")
        self.fm.paste(dest=target_dir)
        
```
Using the native functionality gives me the progress bar as well. This is exactly what I wanted - even though I could not figure out how to copy using `fm.copy()`. I can live with that but would be good to know for curiosity's sake.

Thanks for your help.

**Comment by toonn** [comment]
I think you can simply set `self.fm.do_cut = False` prior to pasting.

**Comment by toonn** [comment]
Next time ask on the r/ranger sub. There's probably people there interested in the same kinds of changes.
