### ISSUE TITLE
How to store rifle.conf in /etc/ranger/

### ISSUE THREAD

**Issue by yyy33** [ranger/ranger#2422]
I want to build a system level configuration files, to let any user can be regarded as the configuration file, without having to separate for one user configuration file, but the ranger default will only find `~/.config/ranger/rifle.conf`,I tried to modify the content in `/usr/lib/python3.9/site-packages/ranger/ext/rifle.py`, the penultimate line, the content I added, does not seem to work

```
def find_conf_path():
    # Find configuration file path
    if 'XDG_CONFIG_HOME' in os.environ and os.environ['XDG_CONFIG_HOME']:
        conf_path = os.environ['XDG_CONFIG_HOME'] + '/ranger/rifle.conf'
    else:
        conf_path = os.path.expanduser('~/.config/ranger/rifle.conf')
    default_conf_path = conf_path
    if not os.path.isfile(conf_path):
        conf_path = os.path.normpath(os.path.join(os.path.dirname(__file__),
                                                  '../config/rifle.conf'))
    if not os.path.isfile(conf_path):
        try:
            # if ranger is installed, get the configuration from ranger
            import ranger
        except ImportError:
            pass
        else:
            conf_path = os.path.join(ranger.__path__[0], "config", "rifle.conf")

    if not os.path.isfile(conf_path):
        sys.stderr.write("Could not find a configuration file.\n"
                         "Please create one at %s.\n" % default_conf_path)
        return None

        conf_path = "/etc/ranger/rifle.conf"
    return conf_path
```

**Comment by toonn** [comment]
Did you intend for it to only be triggered if no configuration file can be found? Because the one included with ranger is always found. You'll have to study the logic of the function more carefully.

Keep in mind that it's impossible to have multiple `rifle.conf` files combine elegantly. This is why `rc.conf` *is* supported in `/etc/ranger` but `rifle.conf` isn't.

**Comment by yyy33** [comment]
> Did you intend for it to only be triggered if no configuration file can be found? Because the one included with ranger is always found. You'll have to study the logic of the function more carefully.
> 
> Keep in mind that it's impossible to have multiple `rifle.conf` files combine elegantly. This is why `rc.conf` _is_ supported in `/etc/ranger` but `rifle.conf` isn't.

I haven't learned python, I just hope that the ranger always reads `/etc/ranger/rifle.conf` and ignores other configuration files, so I think that assigning the file path to `conf_path` before return should be effective, but unfortunately, it Did not take effect

**Comment by toonn** [comment]
The problem is you indented the line, making it part of the if statement. If you do it unconditionally it'll cause a crash if that file doesn't exist though. Put it right under the `default_conf_path` line instead.

**Comment by yyy33** [comment]
> The problem is you indented the line, making it part of the if statement. If you do it unconditionally it'll cause a crash if that file doesn't exist though. Put it right under the `default_conf_path` line instead.

I've learned a lot, it turns out that indentation also affects python syntax, thank you

**Comment by toonn** [comment]
This kind of question would be great on the r/ranger subreddit, btw. That way more people can try to help and everyone can learn from each other.
