### ISSUE TITLE
w3m image preview, broken in 32bit debian 11

### ISSUE THREAD

**Issue by pirate486743186** [ranger/ranger#2423]
#### Runtime Environment

- Operating system and version: Debian 11, 32bit, MATE
- Terminal emulator and version: mate-terminal, xterm, urxvt
- ranger version: ranger-master v1.9.3-304-g236b8f6a and from the distributions version 1.9.3
- Python version: 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
- Locale: en_US.UTF-8

#### Current Behavior

the w3m method for image previews seams completely broken in all terminals in Debian 11.

In mate-terminal, if i move in and out of fullscreen fast enough, or move fast enough left and right inside ranger, i sometimes see the preview flicker for an instant and even more rarely it stays there until something else happens and goes away again. (this is difficult to reproduce, probably a race condition) This also shows, that the configuration must be correct.

it used to work in mate-terminal (a bit buggy), so it should still work.

in xterm it's nothing at all.

#### Expected Behavior

i should see the preview with just the old bugs.

#### Context

I was on ubuntu 18.04, where xterm worked fine, and mate-terminal was a bit buggy.

w3m currently works fine with images in xterm and mate-terminal (same old buggy behavior). It even very buggily works  in urxvt.

i don't think i see a duplicate of this issue.

#### Possible Solutions

No idea. Debian might fix it on it's own in the next 6 months. It just was officially released.

I installed, from the live image, that came with a bunch of input methods. It might be an input method doing something. Then again, w3m works fine....

As a work around, i use urxvt with it's own special method.

#### Steps to reproduce

I would expect that all Debian 11 installs are like this. Same thing with the dev version of ranger.

#### Traceback

If i used the debug feature correctly, the log doesn't say anything relevant.

**Comment by toonn** [comment]
The ueberzug method is probably your best bet. I don't see this getting fixed unless someone comes around and does so.

**Comment by pirate486743186** [comment]
the problem, is most likely a race condition. It almost works in mate-terminal.

**Comment by pirate486743186** [comment]
I tested it in 64bits in a relatively recent laptop and it works fine.

The bug appears in a quite old 32bit laptop. The slow hardware could be exposing a race condition. I tested with clocks to max and min, no change.  w3m_delay didn't help either.

**Comment by toonn** [comment]
Does XTerm work any better? W3mimgpreview is only guaranteed to work with XTerm. Maybe the 64bit versions of other terminals have gotten more XTerm-compatible over the years?

**Comment by pirate486743186** [comment]
to clarify:
- in the 64bit laptop, everything is normal as expected
- The bug is in the old 32bit laptop. Here w3m in Xtern works fine, but ranger in xterm doesn't show pictures at all.

**Comment by toonn** [comment]
And you're running the same ranger version in both?

**Comment by pirate486743186** [comment]
yes, Debian 11 in both, i even copied over $HOME

**Comment by pirate486743186** [comment]
i narrow it down to:
commit 40bd7bc111775ae10ea547bc4d281830eb95757a

**Comment by pirate486743186** [comment]
ignore the other one
this must be it
commit df6a07140c04ce24620337c5211dbaa762dde027

**Comment by pirate486743186** [comment]
i confirm, reverting that commit fixes this problem.
It's probably just revealing an other bug elsewhere, by it self, it's probably correct.

**Comment by pirate486743186** [comment]
actually that commit is a work around for the memory leak
https://github.com/ranger/ranger/issues/451#issuecomment-309900698
