### ISSUE TITLE
ranger --choosefile gives `Bad arguments for move` when selecting.

### ISSUE THREAD

**Issue by gauteh** [ranger/ranger#2461]
Using latest ranger from git and running:

`ranger --choosefile=asdf --clean`

when I try to select a file with `l` I get:

```
Bad arguments for move: [], {'right': 1}
```

and nothing happens.

Terminal: tmux within gnome-terminal
Python: 3.9.7

**Comment by toonn** [comment]
Hmm, I can't reproduce this. What version does ranger report? `ranger --version`, if you're running it from a checkout it should report a revision.

**Comment by gauteh** [comment]
❯ ranger --version
ranger version: ranger-master 1.9.3
Python version: 2.7.17 (default, Feb 27 2021, 15:10:58) [GCC 7.5.0]
Locale: None.None

❯ git describe
v1.9.3-422-g1de6787c

**Comment by toonn** [comment]
And you get the same problem when you run `./ranger.py` rather than `ranger`?

**Comment by gauteh** [comment]
No 🙁

fre. 1. okt. 2021, 18:44 skrev toonn ***@***.***>:

**Comment by toonn** [comment]
@gauteh, if running `ranger.py` works fine then your ranger isn't actually the most recent checkout from master. You'll need to figure out why it's not actually updating to the very latest revision if you're getting it from the AUR.

**Comment by gauteh** [comment]
Hi. I tried to also use ranger.py directly in vim, where the issue first
arose. Gave the same issue. But also prepending python to the
ranger_override helped.
