### ISSUE TITLE
unset WM_NAME property while quitting

### ISSUE THREAD

**Issue by jedi2610** [ranger/ranger#2485]
#### Runtime Environment
- Operating system and version: Arch Linux
- Terminal emulator and version: st 0.8.4
- Python version: Python 3.9.7
- Ranger version/commit: ranger 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
ranger doesn't unset the window name(`WM_NAME`) property while quitting and the window name still equals `ranger` even after quitting ranger.

#### Expected Behavior
ranger should unset the window name so that the window gets back it's previous `WM_NAME` property.

#### Context
i'm using `dwm` and it affects me while navigating b/w workspaces (custom patch to move between vacant workspaces). for example, `bpytop` sets the `WM_NAME` to `BpyTOP` but unsets it while quitting and the terminal falls back to a fallback `WM_NAME` that i set in the source code of `st`.

#### Steps to reproduce
1. Open `st`
2. Open `ranger`
3. Quit `ranger`

**Comment by toonn** [comment]
Is this fallback behavior common across terminal emulators? And what does "unset" mean? IIRC we just echo an ANSI escape sequence to set it and I don't think we'd want to set it to an empty string explicitly.

**Comment by jedi2610** [comment]
huh weird, i thought you can print back the original name of the window(unset) and it's not common across terminal emulators, only in `st`. nvm i'll just fix it in st source code as it makes it more reliable too. ty
