### ISSUE TITLE
Can not install ueberzug properly

### ISSUE THREAD

**Issue by khalidalwalid** [ranger/ranger#2495]
Everything is good during ranger installation.
But, it cannot preview the images as it sets w3m as the default image preview method.
So, I think I need to install ueberzug so that it's gonna preview image well.
But, the problem is coming when I install ueberzug with pip3, it says:

Xshm/Xshm.c:5:10: fatal error: X11/Xlib.h: No such file or directory

Here is the complete error:
Collecting ueberzug
  Downloading ueberzug-18.1.9.tar.gz (36 kB)
Requirement already satisfied: attrs>=18.2.0 in /usr/lib/python3/dist-packages (from ueberzug) (20.3.0)
Collecting docopt
  Downloading docopt-0.6.2.tar.gz (25 kB)
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from ueberzug) (8.1.2)
Collecting python-xlib
  Downloading python_xlib-0.31-py2.py3-none-any.whl (179 kB)
     |████████████████████████████████| 179 kB 559 kB/s 
Requirement already satisfied: six>=1.10.0 in /usr/lib/python3/dist-packages (from python-xlib->ueberzug) (1.16.0)
Building wheels for collected packages: ueberzug, docopt
  Building wheel for ueberzug (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-09pixzb8/ueberzug_3264457e5b3a4b50b3e93af7227661a2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-09pixzb8/ueberzug_3264457e5b3a4b50b3e93af7227661a2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-q45h5e_l                                 
       cwd: /tmp/pip-install-09pixzb8/ueberzug_3264457e5b3a4b50b3e93af7227661a2/                    
  Complete output (51 lines):                                                                       
  running bdist_wheel                                                                               
  running build                                                                                     
  running build_py                                                                                  
  creating build                                                                                    
  creating build/lib.linux-x86_64-3.9                                                               
  creating build/lib.linux-x86_64-3.9/ueberzug                                                      
  copying ueberzug/query_windows.py -> build/lib.linux-x86_64-3.9/ueberzug                          
  copying ueberzug/ui.py -> build/lib.linux-x86_64-3.9/ueberzug                                     
  copying ueberzug/version.py -> build/lib.linux-x86_64-3.9/ueberzug                                
  copying ueberzug/batch.py -> build/lib.linux-x86_64-3.9/ueberzug                                  
  copying ueberzug/files.py -> build/lib.linux-x86_64-3.9/ueberzug                                  
  copying ueberzug/scaling.py -> build/lib.linux-x86_64-3.9/ueberzug                                
  copying ueberzug/pattern.py -> build/lib.linux-x86_64-3.9/ueberzug                                
  copying ueberzug/tmux_util.py -> build/lib.linux-x86_64-3.9/ueberzug                              
  copying ueberzug/layer.py -> build/lib.linux-x86_64-3.9/ueberzug                                  
  copying ueberzug/library.py -> build/lib.linux-x86_64-3.9/ueberzug                                
  copying ueberzug/__init__.py -> build/lib.linux-x86_64-3.9/ueberzug                               
  copying ueberzug/geometry.py -> build/lib.linux-x86_64-3.9/ueberzug                               
  copying ueberzug/terminal.py -> build/lib.linux-x86_64-3.9/ueberzug                               
  copying ueberzug/action.py -> build/lib.linux-x86_64-3.9/ueberzug                                 
  copying ueberzug/xutil.py -> build/lib.linux-x86_64-3.9/ueberzug                                  
  copying ueberzug/conversion.py -> build/lib.linux-x86_64-3.9/ueberzug                             
  copying ueberzug/parser.py -> build/lib.linux-x86_64-3.9/ueberzug                                 
  copying ueberzug/__main__.py -> build/lib.linux-x86_64-3.9/ueberzug                               
  copying ueberzug/process.py -> build/lib.linux-x86_64-3.9/ueberzug                                
  copying ueberzug/loading.py -> build/lib.linux-x86_64-3.9/ueberzug                                
  copying ueberzug/thread.py -> build/lib.linux-x86_64-3.9/ueberzug                                 
  creating build/lib.linux-x86_64-3.9/ueberzug/lib                                                  
  copying ueberzug/lib/__init__.py -> build/lib.linux-x86_64-3.9/ueberzug/lib                       
  creating build/lib.linux-x86_64-3.9/ueberzug/lib/v0                                               
  copying ueberzug/lib/v0/__init__.py -> build/lib.linux-x86_64-3.9/ueberzug/lib/v0                 
  running egg_info                                                                                  
  writing ueberzug.egg-info/PKG-INFO                                                                
  writing dependency_links to ueberzug.egg-info/dependency_links.txt                                
  writing entry points to ueberzug.egg-info/entry_points.txt                                        
  writing requirements to ueberzug.egg-info/requires.txt                                            
  writing top-level names to ueberzug.egg-info/top_level.txt                                        
  reading manifest file 'ueberzug.egg-info/SOURCES.txt'                                             
  reading manifest template 'MANIFEST.in'                                                           
  writing manifest file 'ueberzug.egg-info/SOURCES.txt'                                             
  copying ueberzug/lib/lib.sh -> build/lib.linux-x86_64-3.9/ueberzug/lib                            
  running build_ext                                                                                 
  building 'Xshm' extension                                                                         
  creating build/temp.linux-x86_64-3.9                                                              
  creating build/temp.linux-x86_64-3.9/Xshm                                                         
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.9 -c Xshm/Xshm.c -o build/temp.linux-x86_64-3.9/Xshm/Xshm.o                                               
  Xshm/Xshm.c:5:10: fatal error: X11/Xlib.h: No such file or directory                              
      5 | #include <X11/Xlib.h>                                                                     
        |          ^~~~~~~~~~~~                                                                     
  compilation terminated.                                                                           
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1                            
  ----------------------------------------                                                          
  ERROR: Failed building wheel for ueberzug

I use:
- OS : Kali Linux 2021.3
- Kernel Version : 5.10.0-kali9-amd64
- ranger version: ranger 1.9.3
- Python version: 3.9.7 (default, Sep  3 2021, 06:18:44) [GCC 10.3.0]
- Locale: en_US.UTF-8
- Terminal version : qterminal 0.16.1

Thanks for the response and help.

**Comment by toonn** [comment]
You probably need libx11-dev or something. This sort of issue doesn't belong on the ranger repo though. Report it to the Ueberzug project next time.
