### ISSUE TITLE
Ranger could not Move selected files to trash, ubuntu.

### ISSUE THREAD

**Issue by Chaudhary-Furqan** [ranger/ranger#2499]
#### Runtime Environment

- Operating system and version: 
- Terminal emulator and version: 
- Python version: 
- Ranger version/commit: 
- Locale: 

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```

```

**Comment by toonn** [comment]
Gonna need more than that. I'll reopen if you add enough information.
