### ISSUE TITLE
Ranger cant find w3mimageviver

### ISSUE THREAD

**Issue by Fmert24** [ranger/ranger#2500]
#### Runtime Environment

- Operating system and version: 
- Terminal emulator and version: 
- Python version: 
- Ranger version/commit: 
- Locale: 

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```
I just read man page where mı spose to put this coment

W3MIMGDISPLAY_PATH/data/data/com.termux/files/usr/libexec/w3m/w3mimgdisplay
So ranger can find the path
```

**Comment by Fmert24** [comment]
W3MIMGDISPLAY_PATH/data/data/com.termux/files/usr/libexec/w3m/w3mimgdisplay
W3m instaled w3m-img is instolad when 1 year before it worked whitout anything but this time cant

**Comment by toonn** [comment]
If that's the path for `w3mimgdisplay` try running ranger like so: `W3MIMGDISPLAY_PATH=/data/data/com.termux/files/usr/libexec/w3m/w3mimgdisplay ranger`.

If that works then you can set the variable in your `.profile` or `.zshenv`, whichever environment file your shell loads.

Alternatively, consider trying out the ueberzug method, it tends to work better than w3m.

**Comment by Fmert24** [comment]
> environment file
W3MIMGDISPLAY_PATH=/data/data/com.termux/files/usr/libexec/w3m/w3mimgdisplay ranger
error list index out of range

**Comment by toonn** [comment]
Install instructions here, https://github.com/seebye/ueberzug

Not sure what the index error is. Is the path correct?

**Comment by Fmert24** [comment]
> .zshenv

yes its correct  ım startıng feel like w3m-img not working correctly?

**Comment by Fmert24** [comment]
> > environment file
> > W3MIMGDISPLAY_PATH=/data/data/com.termux/files/usr/libexec/w3m/w3mimgdisplay ranger
> > error list index out of range
> > ı tried uberzug libarys are not in system maybe in  another repo but ı have no idea where they are

pip install -U uberzug
ERROR: Could not find a version that satisfies the requirement uberzug (from versions: none)
ERROR: No matching distribution found for uberzug
u0_a3160@localhost ~/.c/fish [1]> pip install -U uberzug

**Comment by toonn** [comment]
Possible, maybe try getting images to work in w3m first? That's what w3mimgdisplay was designed for.

Oh, you're using fish? Then neither `.profile` nor `.zshenv` are the proper way to set `W3MIMGDISPLAY_PATH`. You'll have to use `set -Ux W3MIMGDISPLAY_PATH /your/path/to/w3mimgdisplay`.

**Comment by Fmert24** [comment]
> Possible, maybe try getting images to work in w3m first? That's what w3mimgdisplay was designed for.
> 
> Oh, you're using fish? Then neither `.profile` nor `.zshenv` are the proper way to set `W3MIMGDISPLAY_PATH`. You'll have to use `set -Ux W3MIMGDISPLAY_PATH /W3MIMGDISPLAY_PATH .

well ı missed space between W3MIMGDISPLAY_PATH W3MIMGDISPLAY_PATH 
so ı find a method

so 
export W3MIMGDISPLAY_PATH="/data/data/com.termux/files/usr/libexec/w3m/w3mimgdisplay"
ıs walid method to

**Comment by Fmert24** [comment]
error index out of range 
also ı find thsi about index error 
https://github.com/ranger/ranger/issues/439

**Comment by toonn** [comment]
The index out of range issue might be fixed on the master branch. Could you try cloning the repo and running `ranger.py` from it?

**Comment by Fmert24** [comment]
> The index out of range issue might be fixed on the master branch. Could you try cloning the repo and running `ranger.py` from it?

Yes ı tried do8ng that and this is the result
ranger
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/ranger", line 37, in <module>
    sys.exit(ranger.main())  # pylint: disable=no-member
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/ranger/core/main.py", line 34, in main
    from ranger.core.fm import FM
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 18, in <module>
    from ranger.core.actions import Actions
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/ranger/core/actions.py", line 10, in <module>
    from os import link, symlink, listdir, stat
ImportError: cannot import name 'link' from 'os' (/data/data/com.termux/files/usr/lib/python3.10/os.py)
u0_a3160@localhost ~ [1]> pip -U install ranger-fm

**Comment by toonn** [comment]
That error is bizarre because the `os` module in Python 3.10 stdlib still has the `link` function.

**Comment by Fmert24** [comment]
> That error is bizarre because the `os` module in Python 3.10 stdlib still has the `link` function.

So I am using termux repo for ranger.... Maybe termux repo packages and pip packages are not compatible I will try clean install of ranger tomorrow

**Comment by toonn** [comment]
As long as the binary is on the PATH I'd expect ranger to be able to find it.

**Comment by joshjetson** [comment]
Did this ever get sorted out ?
