### ISSUE TITLE
Preview images not working with terminator on Mint

### ISSUE THREAD

**Issue by RaviPabari** [ranger/ranger#2501]
```
OS: Linux Mint 20.1 x86_64
Shell: zsh 5.8
DE: Cinnamon
Terminal: gnome-terminal

ranger version: ranger 1.9.3
Python version: 3.8.10 (default, Jun  2 2021, 10:49:15) [GCC 9.4.0]
Locale: en_IN.ISO8859-1
```

using the default config files for ranger, by running command `ranger --copy-config=all`
tried to `set preview_images true` and `method w3mimgdisplay` and others but none are working
also tried setting the path for w3m but no luck

**Comment by toonn** [comment]
Gnome-terminal is VTE-based. Most of those terminals don't properly support w3mimgdisplay. Try ueberzug instead if you're on X11. If you're on Wayland you could try patching the SIXEL PR into your ranger.

**Comment by RaviPabari** [comment]
> Gnome-terminal is VTE-based. Most of those terminals don't properly support w3mimgdisplay. Try ueberzug instead if you're on X11. If you're on Wayland you could try patching the SIXEL PR into your ranger.
> 
> Fyi, don't `--copy-config=all`, only copy the specific configuration files you need. It's a real pain when we update them and users don't remember to update their configuration files and there's incompatibilities. Rule of thumb, don't need to edit it, then don't copy it : )

Ok I'll try and update you, thanks.

**Comment by manujchandra** [comment]
Using ueberzug fixed this problem for me.

**Comment by RaviPabari** [comment]
Tried ueberzug but images not displaying 
![image](https://user-images.githubusercontent.com/46424422/144185898-5aeb4401-dcc0-4e67-81b2-4a2b5b5633ca.png)

**Comment by manujchandra** [comment]
Check if ueberzug is installed correctly. You can try to run https://github.com/OliverLew/fontpreview-ueberzug and see if its showing any output. Its a single bash script.

If its not showing output it means either ueberzug is not installed properly or you need to try a different terminal emulator.

Try using Alacritty.

set `preview_images true` and `method ueberzug`

Also, in your scope.sh the in the `handle_image` function the image part should not be commented.

**Comment by RaviPabari** [comment]
> Check if ueberzug is installed correctly. You can try to run https://github.com/OliverLew/fontpreview-ueberzug and see if its showing any output. Its a single bash script.
> 
> If its not showing output it means either ueberzug is not installed properly or you need to try a different terminal emulator.
> 
> Try using Alacritty.
> 
> set `preview_images true` and `method ueberzug`
> 
> Also, in your `scope.sh` in the `handle_image` function the image part should not be commented.

Tried the fontpreview-ueberzug script but still image was not displayed in that
I have installed ueberzug
```
❯ ueberzug version
18.1.9
```
Any idea what might be going wrong here?

**Comment by manujchandra** [comment]
If fontpreview-ueberzug is also not showing a preview, it means its not a Ranger problem.

Have you tried Alacritty terminal emulator? Maybe your terminal does not support images. Try running fontpreview-ueberzug in Alacritty.

**Comment by RaviPabari** [comment]
Just tried the Alacrity terminal, but I had no luck there either.

> If fontpreview-ueberzug is also not showing a preview, it means its not a Ranger problem.
> 
> Have you tried Alacritty terminal emulator? Maybe your terminal does not support images. Try running fontpreview-ueberzug in Alacritty.

**Comment by manujchandra** [comment]
Lets focus on one thing first - fontpreview-ueberzug and Alacritty.

We will come to ranger later.

Also, doest hurt to try but reboot your computer.

When you run this bash script called fontpreview-ueberzug in alacritty does it show any errors or warnings? Is there any terminal output?

**Comment by RaviPabari** [comment]
As per your instructions, I rebooted and tried running fontpreview-ueberzug on Alacritty, this was the output 

![image](https://user-images.githubusercontent.com/46424422/144207448-ce220453-46ca-4282-8a96-beb8e1e208d3.png)
![image](https://user-images.githubusercontent.com/46424422/144207624-cdccf33e-b57f-4e7e-8814-6eadd0a75992.png)


> Lets focus on one thing first - fontpreview-ueberzug and Alacritty.
> 
> We will come to ranger later.
> 
> Also, doest hurt to try but reboot your computer.
> 
> When you run this bash script called fontpreview-ueberzug in alacritty does it show any errors or warnings? Is there any terminal output?

**Comment by manujchandra** [comment]
There is something else going on. Even if no font preview is shown, it should at least show the names of fonts as you can see on fontpreview-ueberzug github page.

Change of plan : lets try to get ueberzug working first.

Using alacritty only, 

Follow instructions here:

https://linuxtut.com/en/d7fd311633452a9d0b4c/

Install the required dependencies

Create this bash script as shown in the tutorial

```
#!/bin/bash
[ -z "$5" ] && echo "Usage: $0 <image> <x> <y> <max height> <max width>" && exit

source "`ueberzug library`"

ImageLayer 0< <(
    ImageLayer::add [identifier]="example0" [x]="$2" [y]="$3" [max_width]="$5" [max_height]="$4" [path]="$1"
    read
)
```
If you do `chmod + x show.sh` and hit it like `./show.sh images / AX141105107519_TP_V4.jpg 50 10 20 20`


Open an image with the above script. Do you see any errors?

**Comment by RaviPabari** [comment]
Installed all the dependencies
created the bash script as mentioned
got error when I tried to run it,
```
❯ chmod +x show.sh
❯ ./show.sh ~/Pictures/tom.png 50 10 20 20
Traceback (most recent call last):
  File "/home/ravi/.local/bin/ueberzug", line 8, in <module>
    sys.exit(main())
  File "/home/ravi/.local/lib/python3.8/site-packages/ueberzug/__main__.py", line 55, in main
    module.main(options)
  File "/home/ravi/.local/lib/python3.8/site-packages/ueberzug/layer.py", line 217, in main
    windows = batch.BatchList(window_factory.create(*window_infos))
  File "/home/ravi/.local/lib/python3.8/site-packages/ueberzug/ui.py", line 58, in create
    return [OverlayWindow(self.display, self.view, info)
  File "/home/ravi/.local/lib/python3.8/site-packages/ueberzug/ui.py", line 58, in <listcomp>
    return [OverlayWindow(self.display, self.view, info)
  File "/home/ravi/.local/lib/python3.8/site-packages/ueberzug/ui.py", line 162, in __init__
    self.create()
  File "/home/ravi/.local/lib/python3.8/site-packages/ueberzug/ui.py", line 232, in create
    self._set_click_through()
  File "/home/ravi/.local/lib/python3.8/site-packages/ueberzug/ui.py", line 285, in _set_click_through
    Xshape.SO.Set, Xshape.SK.Input, 0,
AttributeError: module 'Xlib.ext.shape' has no attribute 'SO'
```

**Comment by manujchandra** [comment]
This is not a Ranger issue. Your ueberzug is not working, maybe because "module 'Xlib.ext.shape'" is not of the compatible version.

I suggest you open the ticket on ueberzug repository and ask for help there. Once ueberzug script will work as shown in the tutorial above, Ranger will automatically work.

**Comment by RaviPabari** [comment]
> This is not a Ranger issue. Your ueberzug is not working, maybe because "module 'Xlib.ext.shape'" is not of the compatible version.
> 
> I suggest you open the ticket on ueberzug repository and ask for help there. Once ueberzug script will work as shown in the tutorial above, Ranger will automatically work.

Got it, thanks for your time and efforts 👍🏼

**Comment by toonn** [comment]
Just for future search hits. Ueberzug doesn't depend on your terminal. It draws an X window on top of any terminal, so you only need to be using X11 (I think they were working on Wayland support but I'm not up to date on the status of that).

**Comment by aasril** [comment]
I'm on Manjaro (ranger v1.9.3), ueberzug (v18.1.9-3) doesn't work on Wayland session but it works on X11.
