### ISSUE TITLE
Ranger crashed

### ISSUE THREAD

**Issue by DiegoAlcoba** [ranger/ranger#2504]
#### Runtime Environment

- Operating system and version: latest Manjaro 
- Terminal emulator and version:  zsh v.5.8
- Python version: python 3.9.7
- Ranger version/commit: ranger-master
- Locale: es_ES.UTF-8

#### Current Behavior
When i try to open ranger it crashes and gives the traceback below and I only can execute it if I type *ranger --clean*

#### Context
I am using bspwm and need ranger to move between directories and search things in the ~/, using terminal searching in every directory is so sad. I've tried debug, install and reinstall and nothing works.

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/core/main.py", line 174, in main
    fm.initialize()
  File "/usr/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/core/fm.py", line 128, in initialize
    self.bookmarks.load()
  File "/usr/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/container/bookmarks.py", line 49, in load
    new_dict = self._load_dict()
  File "/usr/lib/python3.9/site-packages/ranger_fm-1.9.3-py3.9.egg/ranger/container/bookmarks.py", line 235, in _load_dict
    for line in fobj:
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 0: invalid start byte

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by toonn** [comment]
Looks like one of your bookmarks (possibly the latest visited dir) isn't getting decoded properly. Manually editing `~/.config/ranger/bookmarks` is the easiest solution. If you find the issue it would be great if you could share the troublesome path so I can take a deeper look into why the encode/decode return trip fails.

**Comment by DiegoAlcoba** [comment]
> Looks like one of your bookmarks (possibly the latest visited dir) isn't getting decoded properly. Manually editing `~/.config/ranger/bookmarks` is the easiest solution. If you find the issue it would be great if you could share the troublesome path so I can take a deeper look into why the encode/decode return trip fails.

There is no bookmark directory or archive in `~/.config/ranger`, could be this the problem?

**Comment by toonn** [comment]
Oh, might be in `$XDG_DATA_DIR/ranger/bookmarks`.

**Comment by DiegoAlcoba** [comment]
It's been a while, but I finally found the solution, it is in https://github.com/ranger/ranger/issues/2606#issuecomment-1118515536
Basically you have to remove ~/.local/share/ranger/bookmarks and it works normally.
Thanks for the help btw.
