### ISSUE TITLE
Launch error because a directory has a "space" between the name

### ISSUE THREAD

**Issue by qwyzex** [ranger/ranger#2510]
When I execute `ranger` in **Git Bash SDK-64 for Windows** (please don't hate me), it throws me an error saying `bash: /c/Users/Pro Komputer/AppData/Local/Programs/Python/Python310/Scripts/ranger: C:\Users\Pro: bad interpreter: No such file or directory`. I install ranger trough `pip`. By the way, this is a **second hand Laptop**. Somebody already uses it before. And I don't know why tf did they call the pc '**Pro Komputer**'. It's already give me a headache couple times just because there is a **space between the name**... **I blame 99% of this problems to the previous device user**. I think I might be just gotta re-install this PC goddamn...

It works well on [Termux](https://termux.com/) btw, love it

**Comment by toonn** [comment]
Hmm, ranger shouldn't have problems with paths in spaces. Are you simply running `ranger` or passing a path with a space, `ranger /Users/Pro Komputer`? In the latter case you need to escape the space somehow because otherwise the path is word-split, by the shell, into two arguments. The easiest way is probably to quote the path, `ranger '/Users/Pro Komputer'`.

**Comment by qwyzex** [comment]
> Hmm, ranger shouldn't have problems with paths in spaces. Are you simply running `ranger` or passing a path with a space, `ranger /Users/Pro Komputer`? In the latter case you need to escape the space somehow because otherwise the path is word-split, by the shell, into two arguments. The easiest way is probably to quote the path, `ranger '/Users/Pro Komputer'`.

The problem is the path to the ranger script which going through the "Pro Komputer", but hey... **I think I can figure it out**, I run `which ranger` then copy the path. After that I `vim ~/.bashrc` and create an alias
```
alias rg='C:/Users/"Pro Komputer"/AppData/Local/Programs/Python/Python310/Scripts/ranger'
```
That should do it, thanks for the response tho!
