### ISSUE TITLE
Ranger As Default File Manager (Xfce)

### ISSUE THREAD

**Issue by InternetDr3am** [ranger/ranger#2517]
#### Runtime Environment

- Operating system and version: Linux 5.15.2-2
- Terminal emulator and version: xfce4-terminal 0.8.10-2
- Python version: 3.9.7-2
- Ranger version/commit: 1.9.3.143
- Locale: ?

#### Current Behavior
Unable to set as default file manager

#### Expected Behavior
Open folders on desktop in ranger

#### Context
Can't open ranger by default for, e.g., opening downloads folder from a gui app

#### Possible Solutions
Ranger could accept 3 slashes instead of only 4 when providing a directory argument in terminal

#### Steps to reproduce
1. Set default file manager in xfce as `/home/user/.scripts/Ranger_Default_File_Manager.sh "%s"`
2. Ranger_Default_File_Manager.sh just has `xfce4-terminal -T "Ranger File Manager" -x ranger $@`
3. The problem is that files & directories passed to $@ always have 3 slashes instead of 4 which causes ranger to declare invalid directory
4. I tried using this sed command `sed "s/\/\/\//\/\/\/\//g"`, but always just got blank output from it

#### Traceback

```

```

**Comment by InternetDr3am** [comment]
Solution:
https://stackoverflow.com/questions/70282286/how-to-set-ranger-as-default-file-manager

**Comment by toonn** [comment]
I cannot reproduce the issue. No matter how many consecutive slashes it just works, both with and without `file://`, as expected, because repeated `//` don't change paths on unix-like systems.

Fyi, you can use any character to delimit a substitution, `sed 's:///:////:g`.

**Comment by InternetDr3am** [comment]
Additional Solution for Spaces:

1. `OUT=$(echo "$@" | sed "s:///:////:g" | sed "s/%20/ /g")`
2. `xfce4-terminal -T "Ranger File Manager" -x ranger "$OUT"`

**Comment by InternetDr3am** [comment]
> I cannot reproduce the issue. No matter how many consecutive slashes it just works, both with and without `file://`, as expected, because repeated `//` don't change paths on unix-like systems.
> 
> Fyi, you can use any character to delimit a substitution, `sed 's:///:////:g`.

Probably something wrong with my computer because my `file:` is always followed by 3 slashes & the fourth slash represents the root directory, whereas for everybody else it seems like `file:` is always followed by 2 slashes & the third slash represents the root directory.

**Comment by toonn** [comment]
Yes, `file://` is like `http://` it's the protocol specifier of the URL, it's always two slashes. The value following it should just be a path, so a single `/` should signify the root directory, though repeated `/` are valid and don't change the meaning of a path.

I also see you're doing poor man's URL decoding though, because of `%20` for space. Maybe there's something else in between that's messing with the path actually passed to ranger?
