### ISSUE TITLE
Please use entry_points in setup.py

### ISSUE THREAD

**Issue by blueyed** [ranger/ranger#252]
I am trying to use [pipsi](https://github.com/mitsuhiko/pipsi/) to install ranger in a isolated virtualenv, but that does not pick up the "scripts" from setup.py (https://github.com/mitsuhiko/pipsi/issues/14).

Using entry_points would solve / work around this issue.

**Comment by hut** [comment]
I don't believe entry points are supported by distutils

**Comment by blueyed** [comment]
This now works, probably (also) because of 8b958c5.

Thanks!

**Comment by blueyed** [comment]
Re-opening.. it still does not work for the `--editable` option:

    % pipsi install ~v/ranger
    Running virtualenv with interpreter /home/daniel/.local/venvs3/pipsi/bin/python3.4
    Using real prefix '/home/daniel/.pyenv/versions/3.4.3'
    New python executable in /home/daniel/.local/venvs/ranger/bin/python3.4
    Also creating executable in /home/daniel/.local/venvs/ranger/bin/python
    Installing setuptools, pip, wheel...done.
    Processing /home/daniel/Vcs/ranger
    Installing collected packages: ranger
      Running setup.py install for ranger
    Successfully installed ranger-1.7.1
      Linked script /home/daniel/.local/bin/rifle
      Linked script /home/daniel/.local/bin/ranger
    Done.

    % pipsi uninstall ranger
    The following paths will be removed:
      /home/daniel/.local/venvs/ranger
      /home/daniel/.local/bin/ranger
      /home/daniel/.local/bin/rifle

    Do you want to uninstall ranger? [y/N]: y
    Done!

    % pipsi install --editable ~v/ranger
    Running virtualenv with interpreter /home/daniel/.local/venvs3/pipsi/bin/python3.4
    Using real prefix '/home/daniel/.pyenv/versions/3.4.3'
    New python executable in /home/daniel/.local/venvs/ranger/bin/python3.4
    Also creating executable in /home/daniel/.local/venvs/ranger/bin/python
    Installing setuptools, pip, wheel...done.
    Obtaining file:///home/daniel/Vcs/ranger
    Installing collected packages: ranger
      Running setup.py develop for ranger
    Successfully installed ranger
    Did not find any scripts.  Uninstalling.

**Comment by nfnty** [comment]
Should be fixed by 34e28e6159dece029770a0c172e25021beea9edf. Request to reopen if you're still experiencing this issue on `master` or the latest release.
