### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ueberzug'

### ISSUE THREAD

**Issue by dscharalampidis** [ranger/ranger#2523]
#### Runtime Environment

- Operating system and version: 5.10.76-gentoo-r1-x86_64
- Terminal emulator and version: st 0.8.4
- Python version: 3.9.9
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
`$ ranger --debug`
ranger version: ranger 1.9.3
Python version: 3.9.9 (main, Dec 12 2021, 22:49:15) [GCC 11.2.0]
Locale: en_US.UTF-8
Current file: '/mnt/data/Pictures/Wallpapers/3D_Fantasy_Places_HD_0029.jpg'

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.9/site-packages/ranger/core/fm.py", line 381, in loop
    ui.draw_images()
  File "/usr/lib/python3.9/site-packages/ranger/gui/ui.py", line 401, in draw_images
    self.browser.columns[-1].draw_image()
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/pager.py", line 124, in draw_image
    self.fm.notify(ex, bad=True)
  File "/usr/lib/python3.9/site-packages/ranger/core/actions.py", line 173, in notify
    raise obj
  File "/usr/lib/python3.9/site-packages/ranger/gui/widgets/pager.py", line 118, in draw_image
    self.fm.image_displayer.draw(self.image, self.x, self.y,
  File "/usr/lib/python3.9/site-packages/ranger/ext/img_display.py", line 747, in draw
    self._execute(
  File "/usr/lib/python3.9/site-packages/ranger/ext/img_display.py", line 742, in _execute
    self.initialize()
  File "/usr/lib/python3.9/site-packages/ranger/ext/img_display.py", line 737, in initialize
    self.process = Popen(['ueberzug', 'layer', '--silent'], cwd=self.working_dir,
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ueberzug'

#### Expected Behavior
Should be showing image previews.

**Comment by toonn** [comment]
Did you install ueberzug?

**Comment by dscharalampidis** [comment]
@toonn yes, I've installed `ueberzug` with `pip`and it's working fine if I do something like this:

`
ueberzug layer --parser bash 0< <(
    declare -Ap add_command=([action]="add" [identifier]="example0" [x]="0" [y]="0" [path]="/mnt/data/Pictures/Wallpapers/9098.jpg")
    declare -Ap add_command=([action]="add" [identifier]="example1" [x]="10" [y]="0" [path]="/mnt/data/Pictures/Wallpapers/9098.jpg")
    sleep 5
    declare -Ap remove_command=([action]="remove" [identifier]="example0")
    sleep 5
)

`
`which ueberzug`
/home/dscharalampidis/.local/bin/ueberzug

`echo $PATH`
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/lib/llvm/13/bin:~/.local/bin

`$ ueberzug version`
18.1.9

**Comment by toonn** [comment]
Ok, so from the error it seems like ranger can't find ueberzug on the PATH. How did you install ranger?

**Comment by dscharalampidis** [comment]
I installed it via the official Gentoo repositories, but before posting here I also cloned this git and run it with
`./ranger.py`
Didn't work either.

**Comment by dscharalampidis** [comment]
Okay... it's indeed a path problem, but I don't understand why this is happening.
After your comment, I edited the `img_display.py` and I changed line 737 as follows:

`self.process = Popen(['~/.local/bin/ueberzug', 'layer', '--silent'], cwd=self.working_dir,`

It didn't work.

Then I changed it to:

`self.process = Popen(['/home/dscharalampidis/.local/bin/ueberzug', 'layer', '--silent'], cwd=self.working_dir,`

and now it works.

I don't understand why this is happening. Any idea?

**Comment by toonn** [comment]
I think `~` isn't interpreted in paths there. The shell is typically responsible for expanding that.

I'm not sure why ranger doesn't find it on the PATH though.

**Comment by dscharalampidis** [comment]
Hmm, okay, now I know that something's fundamentally wrong with my bash/path.

I reversed the code to the original.
Then I changed my path from `~/.local/bin` to `/home/dscharalampidis/.local/bin`

Now it works.

I still don't know why this is happening, but I am making this as closed as this is not a ranger issue.
Many thanks for the help!
