### ISSUE TITLE
Set the scale of the image preview 

### ISSUE THREAD

**Issue by c02y** [ranger/ranger#2535]
#### Runtime Environment

- Operating system and version: Archlinux
- Terminal emulator and version: Kitty+Tmux+Fishshell
- ranger version: ranger 1.9.3
- Python version: 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0]
- ocale: en_US.UTF-8

#### Current Behavior
I use `set preview_images_method ueberzug` in my `ranger/rc.conf`, when I use ranger inside directory with some videos, ranger will generate preview image for the video with a small layer/window, I notice that the generated preview images are all inside `~/.cache/ranger` and the image file size is big and its resolution(such as 1920x1080) is the same as the video file.
#### Expected Behavior
Big size and original resolution from the video for just previewing video in that small layer/window is totally unnecessary, it only causes performance issue for ranger.

I love ranger, but one of the few issues  I don't like ranger is its performance.

#### Context

Lower the scale of the image preview for videos.

#### Possible Solutions
change the resolution or scale of the previewed image for the video.

#### Steps to reproduce
1. ranger on video files
2. 
3. 

#### Traceback

```

```

**Comment by toonn** [comment]
I don't think scaling would necessarily be more performant. The benefit of keeping the original resolution is that it doesn't require any conversion. If we scale to the size of the preview pane then we have to scale the image *and* do it again for every window size we happen to preview the files at.

Especially in the case of ueberzug where ranger simply passes a path to preview to ueberzug and doesn't have to handle any of the image data I think this shouldn't be a performance issue. Unless ueberzug is really slow at displaying high resolution images?

**Comment by c02y** [comment]
Sure, I was thinking about the same thing, capturing smaller scale of the video may need extra steps and may slow down the preview process more.

Unless someone gets the opposite result, I'll close this for now.
