### ISSUE TITLE
Set the timeout for previewing files

### ISSUE THREAD

**Issue by c02y** [ranger/ranger#2536]
#### Runtime Environment

- Operating system and version: Archlinux
- Terminal emulator and version: Kitty+Tmux+Fishshell
- ranger version: ranger 1.9.3
- Python version: 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0]
- ocale: en_US.UTF-8

#### Current Behavior
When I move my keyboard point in the file list inside ranger, sometimes the files are hard to be previewed, or it just takes too much time, there will be 
```
Getting preview of /tmp/file
Getting preview of /tmp/file
Getting preview of /tmp/file
Getting preview of /tmp/file
Getting preview of /tmp/file
......
```
in the background (open the task window using `taskview_open` binding), and it will freeze ranger or slow ranger even I'm not doing anything using ranger such as copy or moving.

This is a serious issue of ranger since it happens a lot to me, I can't do anything else, or it is just very slow, and I cannot quit ranger when this happens.

#### Expected Behavior
Set a timeout for previewing files. If it fails to preview it, quit the previewing job.

#### Context

This issue seems similar to https://github.com/ranger/ranger/issues/151 and https://github.com/ranger/ranger/issues/736 , and they are there for years.

But my issue is about previewing function, if it is hard to do that in the whole ranger project scale, maybe we can start from small one
 
#### Possible Solutions
This is a serious issue of ranger since it happens a lot to me, I can't do anything else, or it is just very slow, and I cannot quit ranger when this happens.
#### Steps to reproduce
1. open ranger in directoryA
2. Open another terminal or tmux panel, copy a big video file to directoryA using simply `cp` command
2. move the keyboard point to the file which is being currently coping here
3. ranger tries to preview it but it just fails and freeze ranger before the copy finishes

#### Traceback

```

```

**Comment by snuffop** [comment]
:+1:

**Comment by toonn** [comment]
Yes, this is a known issue. Some solutions have been suggested but we just don't have the time to really work on this. Testing of the few PRs that try to implement asynchronous previews in some ways, like using non-blocking I/O would be super helpful.

I'm closing this issue because it's well-known and there's other open issues and it's better for the discussion to remain focused there.
