### ISSUE TITLE
Alt+Left/Right keybinding not working

### ISSUE THREAD

**Issue by maxreuben** [ranger/ranger#2541]
#### Runtime Environment
- Operating system and version: Fedora 34
- Terminal emulator and version: Alacritty 0.9.0
- Python version: 3.9.9
- Ranger version/commit:  ranger-master
- Locale: en_US.UTF-8

#### Current Behavior
Alt+Left/Right in console does nothing. The cursor doesn't move. While Alt+B/F work. Remapping the keybinding to Ctrl+Left/Right doesn't work either. I tried commenting the previous command mapping Alt+Left/Right to switching tabs but no luck.

#### Expected Behavior
By default, the Alt+Left/Right is bound to move cursor left/right.

#### Steps to reproduce
1. Open ranger
2. Enter console
3. Type something and then try to move the cursor using Alt+Left/Right

#### Traceback
```
N/A
```

Might be related to #2064

**Comment by toonn** [comment]
Closing this in favor of #2064, let's collect mappings that don't work there.
