### ISSUE TITLE
Fzf Integration Command

### ISSUE THREAD

**Issue by jebaum** [ranger/ranger#255]
I wrote a command to support changing directory in ranger using [junegunn/fzf](https://github.com/junegunn/fzf). This goes in commands.py

```
from subprocess import PIPE
class fzfcd(Command):
    def execute(self):
        command="find -L \( -path '*.wine-pipelight' -o -path '*.ivy2*' -o -path '*.texlive*' -o -path '*.git' -o -path '*.metadata' -o -path '*_notes' \) -prune -o -type d -print 2>/dev/null | fzf"
        fzf = self.fm.execute_command(command, stdout=PIPE)
        stdout, stderr = fzf.communicate()
        directory = stdout.decode('utf-8').rstrip('\n')
        self.fm.cd(directory)
```

Combined with a keymapping I find it extremely useful, not sure where to share it though.

**Comment by tex** [comment]
It would be nice to create a wiki page? with these users' additions?

**Comment by Vifon** [comment]
Like this one? https://github.com/hut/ranger/wiki/Commands

**Comment by EvanCarroll** [comment]
> Like this one? https://github.com/hut/ranger/wiki/Commands

which one?

**Comment by toonn** [comment]
https://github.com/ranger/ranger/wiki/Custom-Commands#fzf-integration
