### ISSUE TITLE
Custom command to copy file contemt not worked

### ISSUE THREAD

**Issue by woshichuanqilz** [ranger/ranger#2553]
- Operating system and version: 
- manjaro 21
- Terminal emulator and version: 
- - Python version: 
- 0.9.0
- Ranger version/commit: 
- 3.10.1
- Locale:
- LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=zh_CN.UTF-8
LC_TIME=en_US.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=zh_CN.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=zh_CN.UTF-8
LC_NAME=zh_CN.UTF-8
LC_ADDRESS=zh_CN.UTF-8
LC_TELEPHONE=zh_CN.UTF-8
LC_MEASUREMENT=zh_CN.UTF-8
LC_IDENTIFICATION=zh_CN.UTF-8
LC_ALL= 

#### Current Behavior
Add commands in `commands.py`

```py
class copyFileContent(Command):
    def execute(self):                                              
        self.fm.run(['xclip', self.fm.thisfile])
        self.fm.notify(self.fm.thisfile)

```

I want to use xclip to copy the content of the file. But it not worked.  It will work sometime but very rarely. 

Why this happened ?

**Comment by markus-bauer** [comment]
Copying with xclip is already explained here (not tested by me):
https://github.com/ranger/ranger/wiki/Custom-Commands#copy-the-content-of-image-file-and-text-file-with-xclip

It uses subprocess and doesn't directly answer your question (Why doesn't the runner work?).
I think the runner expects the command as a string like this:

```python
class copyFileContent(Command):
    def execute(self):                                              
        self.fm.run("xclip {}".format(self.fm.thisfile))
        self.fm.notify(self.fm.thisfile)
```

If you don't need this to be a command, you can also have a binding like this:
```
map yx shell xclip %f
```

Or any other macro:
> %f   the highlighted file
%d   the path of the current directory
%s   the selected files in the current directory
%t   all tagged files in the current directory
%c   the full paths of the currently copied/cut files
%p   the full paths of selected files

**Comment by toonn** [comment]
markus-bauer's answer is pretty comprehensive, hope you managed to solve your issue.
