### ISSUE TITLE
segmentation fault while using preview pane and moving in network folder

### ISSUE THREAD

**Issue by tkossak** [ranger/ranger#256]
Hello,

I have network folder mapped to "K:" drive. After starting ranger, when i enter /cygdrive/k folder and move few times (up/down) through folders/files, ranger crashes. Sometimes without any error - it just shows shell prompt in the middle of text, sometimes it just writes "Segmentation fault (core dumped)".

I managed to notice that it crashes because of preview pane. When i turn it off (`zp` and `zP`) it works fine.
Ranger crashes when i try to move up/down when the preview pane for current item (folder/file) isn't fully loaded (for example didn't manage to read all the files in the folder yet). When the preview pane is ready (it fully loaded current item's content) i can move up/down without any crashes. It happens only with network folders.

os: Windows 7 x64
shell: CYGWIN_NT-6.1 1.7.33-2(0.280/5/3) 2014-11-13 15:47 x86_64 Cygwin
ranger v 1.6.1

Is there any way to fix this? When i go to other file, the preview pane should just cancel loading the previous item, without crashing ranger.

**Comment by randynobx** [comment]
Are there any file types in particular that seem to cause the seg fault?

**Comment by tkossak** [comment]
The filetype/folder probably doesn't matter. I tried it now and it crashed while going from ```_viminfo``` file to ```*.pptx``` file.

When it crashes i see ```python2.7.exe.stackdump``` file in ```/cygdrive/k``` whith the content:
````
Exception: STATUS_ACCESS_VIOLATION at eip=68025D92
eax=FFBF162C ebx=FFCE8B3C ecx=2A4AA8B7 edx=80010358 esi=FFBF162C edi=00000000
ebp=FFCAE18C esp=0028BCB0 program=C:\cygwin\bin\python2.7.exe, pid 7556, thread main
cs=0023 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame     Function  Args
End of stack trace
```

I just created few empty files with ```touch a.txt b.txt c.txt```, turned on file preview (```zp```) and it crashed instantly while going from one txt file to another with the stackdump file:
```
Exception: STATUS_ACCESS_VIOLATION at eip=00000000
eax=00000001 ebx=00000000 ecx=00000334 edx=0008E3C8 esi=2A4A9933 edi=456404FF
ebp=1A98AE80 esp=0028BD50 program=C:\cygwin\bin\python2.7.exe, pid 1788, thread main
cs=0023 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame     Function  Args
```

Maybe it's some bug in my python version/implementation (Python 2.7.8)

**Comment by nfnty** [comment]
Can't reproduce this issue. Request to reopen if you're still experiencing this issue on `master` or the latest release.
