### ISSUE TITLE
Rancher crashes - looses path to docker

### ISSUE THREAD

**Issue by joeg1484** [ranger/ranger#2561]
#### Runtime Environment

- Operating system and version: Mac OS Monterey 12.1 fully patched
- Terminal emulator and version: iTerm2 Build 3.4.15
- Python version: Python 2.7.18
- Ranger version/commit: Version: 1.0.1
- Locale: EN

#### Current Behavior
We can run rancher for hours at a time and then suddenly it crashes with:

RRO[27060] error waiting for container: unexpected EOF
ERROR [2022-02-08 15:49:08] Error while execing error="exit status 125" path=/usr/local/bin/docker
FATAL [2022-02-08 15:49:08] Error while running acm error="exit status 125"

Sometimes, it crashes in a couple hours, sometimes it lasts for a couple days.

The docker path is 
lrwxr-xr-x  1 USER  admin  80 Jan 31 12:54 /usr/local/bin/docker -> /Applications/Rancher Desktop.app/Contents/Resources/resources/darwin/bin/docker

#### Expected Behavior

Rancher to continue to run without issue

Our containers would run for weeks on Docker Desktop and we had no issues until moving to Rancher.

#### Context

We use Rancher to spin up containers that allow us to connect to remote sites. The container has things built into it like ssh keys, utilities etc. They are like troubleshooting pods for our work.

#### Possible Solutions
I looks like the unix socket is disappearing. Not sure how to fix this.

#### Steps to reproduce
1. Just launch our custom containers and wait

**Comment by Rom1deTroyes** [comment]
Hi !
I've never tryed to use `Ranger` (the File Manager) under `Rancher` (the container plateform), but there is a big chance that your issue find better answers at https://github.com/rancher/rancher :-)

**Comment by joeg1484** [comment]
Oh good grief... I made a typo... Yes, my bad! So sorry!

**Comment by Rom1deTroyes** [comment]
No problem, I'm the first to mangle my fingers from time to time :crossed_fingers:
Can you close this issue so the maintainers here can pass their way ?

Good luck with your issue : random problems are always hard to reproduce and fix !

**Comment by joeg1484** [comment]
You bet... Thanks!
