### ISSUE TITLE
Windows OS support 😅 

### ISSUE THREAD

**Issue by yashpalgoyal1304** [ranger/ranger#2562]
hi, any thoughts or plans or instructions for how can i get this vim based ranger file manager on windows os?

<details>
<summary>
Unfilled template
</summary>

#### Runtime Environment

- Operating system and version: 
- Terminal emulator and version: 
- Python version: 
- Ranger version/commit: 
- Locale: 

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```

```

</details>

**Comment by toonn** [comment]
Your best bet is probably through WSL. Or one of the various projects trying to bring a Unix shell to Windows like Cygwin.

This kind of question is better asked over on our subreddit r/ranger, more participants there who might be using Windows.

**Comment by toonn** [comment]
It is one of the ways to get in touch with the community though. The other alternative is #ranger@Libera.Chat but there's no Windows users hanging around there AFAIK. If you figure out a comfortable way to use Ranger on Windows, a page or section on the wiki would be highly appreciated!
