### ISSUE TITLE
Please do a release

### ISSUE THREAD

**Issue by magnetophon** [ranger/ranger#2572]
The last release was more than 2 years ago, I'm sure there have been many improvements in the meantime.

**Comment by toonn** [comment]
Working on it. There's a couple more serious bugs in the 1.9.4 milestone. Extra eyes and hands on those are welcome.

**Comment by magnetophon** [comment]
Thanks!
I have no experience with python, but I'm happy to test.
Anything in particular?
[The list] (https://github.com/ranger/ranger/milestone/2) is a bit long!  ;)

**Comment by toonn** [comment]
Yes, the list being long is the problem. Anything on that list marked as bug should take priority. I know that doesn't actually narrow it down much : s
