### ISSUE TITLE
Pressing `Ctrl-c` closes programs (windows) that were opened with `nohup` and `&`

### ISSUE THREAD

**Issue by Gregaras** [ranger/ranger#2577]
#### Current Behavior

Whenever I open some program in another window with `nohup` and `&`, go back to Ranger window and press `Ctrl-c`, the opened program closes.

Happens with:
`nohup qutebrowser &`
`nohup mpv %s &` (%s is some video file that is selected)
some other programs

Doesn't happen with:
`nohup leafpad &`

#### Expected Behavior

Perhaps when pressing `Ctrl-c`, Ranger (or maybe something else) wouldn't close windows.

#### Context

Had been looking for default keybinds to replace ESC. Found default keybind Ctrl-c and this behaviour occured. Also found Ctrl-g default keybind which does `eval fm.ui.console.close()`.

#### Steps to reproduce
(with mpv)
1. Select some video to play in Ranger
2. Execute `shell nohup mpv %s &`
3. Click on Ranger window instead of mpv window (focus to Ranger window I guess)
4. Press `Ctrl-c`

**Comment by toonn** [comment]
I'm not sure how to fix this. Probably just use either the `-f` or the `-t` flag with `:shell` or rifle's `flag f` and `flag t`. Not sure why you want to use shell with nohup and backgrounding since ranger's default rule for mpv already forks.

**Comment by Gregaras** [comment]
I see `shell -f` does things which I wanted `nohup` and `&` to do, I used `nohup` thinking that it doesn't let child window to close when parent is being closed but now I see `&` is enough. I also see that Ctrl-c doesn't close windows opened with `shell -f`.

I am closing this issue.
