### ISSUE TITLE
How to toggle between files?

### ISSUE THREAD

**Issue by acampove** [ranger/ranger#2578]
Hello,

This is not an issue with the software itself but a question. When I press `t`, I see a red star next to the filename, I understand that the file can be marked for toggling like that. If I mark two files, how do I switch back and forth between them?

Cheers.

**Comment by Gregaras** [comment]
I suppose these are default keybindings in `rc.conf`:
`map n  search_next`
`map N  search_next forward=False`
`map ct search_next order=tag`

I suppose you press `ct` to search for marked (tagged) files, `n` to search for next, `N` to search for previous.

**Comment by acampove** [comment]
Hi, @Gregaras 

Thanks, I missed the `ct` part :). I had done:

```
:search log
```

and `n` was jumping between the `log` stuff.

Cheers.

**Comment by toonn** [comment]
Questions that aren't really issues are more suited to the IRC channel #ranger@libera.chat or the subreddit r/ranger, more people there to provide a quick answer.

@Gregaras thank you for helping out! 🤗
