### ISSUE TITLE
ranger with `update_title` set crashes in terminal emulators that don't support/advertise statusline capabilities

### ISSUE THREAD

**Issue by camoz** [ranger/ranger#2587]
#### Runtime Environment

```
$ ranger --version
ranger version: ranger 1.9.3
Python version: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
Locale: en_US.UTF-8
```

- Operating system and version: Up-to-date archlinux
- Terminal emulator and version: `foot version: 1.11.0 +pgo +ime +graphemes -assertions`

#### Current Behavior

If using a terminal emulator that does not support updating the window title (no statusline capabilities in terminfo), and `rc.conf` contains `set update_title true`, ranger does not start (crash).

#### Expected Behavior

Ranger should not crash but print a warning and not update the window title.

#### Context

AIUI whether a terminal emulator supports updating the window title or not is determined by the respective terminfo file. On archlinux and voidlinux, the regular `foot` terminfo is provided by ncurses (v6.3), but [currently lacks statusline capabilities](https://codeberg.org/dnkl/foot/issues/872) (this will be fixed in the next ncurses release according to the linked issue). This is how I found the issue.

#### Possible Solutions

On archlinux and voidlinux, install `foot-terminfo`, which installs foot's own terminfo as `foot-extra`. Then set `term=foot-extra` in `foot.ini` (or run foot with `--term=foot-extra`). Then foot advertises statusline capabilities correctly and ranger updates the window title, and does not crash.

#### Steps to reproduce

1. Use a terminal emulator that does not support updating the window title (no statusline capabilities in terminfo).
2. `set update_title true` in `rc.conf`
3. start ranger

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
Locale: en_US.UTF-8
Current file: '/home/camoz/bin'

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 375, in draw
    curses.tigetstr('tsl').decode('latin-1'),
AttributeError: 'NoneType' object has no attribute 'decode'


```

**Comment by toonn** [comment]
Finally got around to this. Thank you for the report.
I have a tentative fix in #2654, would appreciate if you can verify this solves your problem.

**Comment by camoz** [comment]
Tested, works fine! Thank you!

**Comment by camoz** [comment]
For the record, tested with `foot --term=foot` using `foot version: 1.12.1 +pgo +ime +graphemes -assertions`, which still results in a crash without your patch, but not with your patch.
