### ISSUE TITLE
ranger ValueError: Color pair is greater than COLOR_PAIRS-1 (-1).

### ISSUE THREAD

**Issue by GissingValeska** [ranger/ranger#2608]
<img width="1402" alt="image" src="https://user-images.githubusercontent.com/59323863/162892288-3ac27b31-33d0-47e0-8384-98480f1ae2e3.png">
How to solve this problem, the system is MacBook Air, the terminal is iTerm2. This problem occurs when starting the ranger.

**Comment by yamsu** [comment]
This is likely an issue with the TERM definition, try
```
TERM=xterm-256color ranger
```

**Comment by toonn** [comment]
Closing as a duplicate of #2498.
