### ISSUE TITLE
Pandoc is silently fired up and eating up 99% of memory

### ISSUE THREAD

**Issue by glyh** [ranger/ranger#2610]
#### Runtime Environment

- Operating system and version: `Linux arch 5.17.1-arch1-1 #1 SMP PREEMPT Mon, 28 Mar 2022 20:55:33 +0000 x86_64 GNU/Linux`
- Terminal emulator and version: `kitty 0.25.0 created by Kovid Goyal`
- Python version: `Python 3.10.4`
- Ranger version/commit: 
```
ranger version: ranger 1.9.3
Python version: 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]
Locale: en_US.UTF-8
```
- Locale: see above

#### Current Behavior
Ranger fire up pandoc and eat up all my memory

#### Expected Behavior
It will not.

#### Context

Nothing, just browsing.

#### Possible Solutions
Constrain the memory pandoc is allowed to use.

#### Steps to reproduce
Happens randomly.

**Comment by glyh** [comment]
Why this software keep memleaking?

**Comment by Friptick** [comment]
Same here. Latest Ubuntu, 23.04. Same experience on previous Ubuntus.

Bad enough to crash my computer. Had to uninstall.

**Comment by manero6** [comment]
Same on Fedora Rawhide.
16 cores at 100% and my laptop's battery drained extremely quickly...

**Comment by toonn** [comment]
`scope.sh` is considered a configuration file so if you can't run Ranger from the master branch, remove the calls to Pandoc. Closing until demonstrated that it's not fixed on latest master.
