### ISSUE TITLE
ranger crashed

### ISSUE THREAD

**Issue by Yan-weihao** [ranger/ranger#2636]
ranger version: ranger 1.9.3
Python version: 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0]
Locale: zh_CN.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 127, in initialize
    self.bookmarks.load()
  File "/usr/lib/python3.10/site-packages/ranger/container/bookmarks.py", line 47, in load
    new_dict = self._load_dict()
  File "/usr/lib/python3.10/site-packages/ranger/container/bookmarks.py", line 237, in _load_dict
    dct[key] = self.bookmarktype(value)
  File "/usr/lib/python3.10/site-packages/ranger/container/directory.py", line 150, in __init__
    assert not os.path.isfile(path), "No directory given!"
AssertionError: No directory given!

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
<img width="959" alt="2022-06-08_19-58" src="https://user-images.githubusercontent.com/61379647/172610970-85f76b0a-5069-4815-924f-a1c09e10243d.png">

**Comment by Unsavory1** [comment]
hi, this is happening to me as well, have you solved the error?

**Comment by Unsavory1** [comment]
> There is no solution > hi, this is happening to me as well, have you solved the error?

hmm now thats odd. ive tried updating python, done multiple system updates but still i get the error, hopefully it gets solved

**Comment by thomasjsn** [comment]
I had the same error, this fixed it: https://github.com/ranger/ranger/issues/2606#issuecomment-1118515536

**Comment by Unsavory1** [comment]
> I had the same error, this fixed it: https://github.com/ranger/ranger/issues/2606#issuecomment-1118515536

Thanks a lot!

**Comment by toonn** [comment]
Closing as resolved. Making Ranger deal more gracefully with non-existent paths in saved tabs and bookmarks and such is on the radar.
