### ISSUE TITLE
How to disable default keymappings (for remaps)?

### ISSUE THREAD

**Issue by kohane27** [ranger/ranger#2649]
Hello there. Hope you're doing well.

#### Runtime Environment

- Operating system and version: Linux (Kernel: 5.15.46-1-MANJARO)
- Terminal emulator and version: kitty 0.25.2 
- ranger version: ranger-master
Python version: 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0]
Locale: en_US.UTF-8

#### Current Behavior

Remapping default keymappings (e.g., `<C-f>`) don't work.

#### Expected Behavior

I have the following in my `~/.config/ranger/rc.conf` (as suggested in [`Ctrl-i` cannot be used · Issue #2546](https://github.com/ranger/ranger/issues/2546)):

```
# jchook/ranger-zoxide
# find dirs
unmap <C-f>
map <C-f> zi
```

I'm trying to map `Ctrl-f` to trigger `zi` to use `fzf` to search dir. However, ranger doesn't allow me to remap `Ctrl-f`. `Ctrl-f` is the default keymap to scroll down. 

`<C-w>`: doesn't work
`<C-h>`: works
`<C-s>` even freezes and breaks ranger (freeze shell)

#### Context

Interestingly, if I add `export RANGER_LOAD_DEFAULT_RC=FALSE` to `.zshrc`, `<C-f>` are remap-able but the following appears:

```
"Tried to copy the keybinding `<UP>', but it was not found."
"Tried to copy the keybinding `<DOWN>', but it was not found."
"Tried to copy the keybinding `<LEFT>', but it was not found."
"Tried to copy the keybinding `<RIGHT>', but it was not found."
"Tried to copy the keybinding `<HOME>', but it was not found."
"Tried to copy the keybinding `<END>', but it was not found."
"Tried to copy the keybinding `<PAGEDOWN>', but it was not found."
"Tried to copy the keybinding `<PAGEUP>', but it was not found."
"Tried to copy the keybinding `<backspace>', but it was not found."
```

Because well, the default keymappings are not loaded.

The question is, how do I remap the default keys with loading the `default_rc`?

Any input is much appreciated. Thank you:)

**Comment by kohane27** [comment]
I was trying to remap `C-q` but failed. After much googling I found the clue to the answer here: [Can't map exit to <C-q>](https://www.reddit.com/r/ranger/comments/vlz2vq/cant_map_exit_to_cq/). In short, I simply added `stty -ixon` to my `.zshrc` and I can remap `C-q` in my ranger. Cheers!

**Comment by kohane27** [comment]
I also figured out why `C-F` wasn't working. I need to comment out the following line:

```bash
copymap <PAGEDOWN> <C-F>
```

Such that the following works:

```bash
unmap <C-f>
map <C-f> zi
```

Cheers!

**Comment by toonn** [comment]
Using keys combined with Ctrl is riddled with difficulties in terminals because the terminal interprets many of them. `<C-s>` freezing Ranger for example is a flow control feature. It literally freezes the programs output. So of course it would seem to "freeze ranger." `<C-q>` is the corresponding control sequence that will resume the program's output.

Glad you figured something out that works for you though!
