### ISSUE TITLE
Memory Leak while previewing .ods file

### ISSUE THREAD

**Issue by anurag3301** [ranger/ranger#2651]
#### Runtime Environment

- Operating system and version: Linux arch 5.18.3-arch1-1 
- Terminal emulator and version: kitty 0.25.2
- Python version: Python version: 3.10.5
- Ranger version/commit: ranger 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
File Preview turned on
Just create a ods file using Libre Calc
As you select select the ods file and ranger try to preview it, memory leakage starts
The culprit is `pandoc`

#### Expected Behavior
Preview the file if possible else dont.

#### Context

This is a huge problem, as I mistakenly select any ods to file the memory leak starts, I have to open a new terminal to kill pandoc.

#### Possible Solutions
Not Sure, maybe just turn off preview for ods or any such file which lead to pandoc leak memory.

#### Steps to reproduce
1. Turn on file preview
2. Create a ods file using libre calc
3. Just select the file in ranger, and monitor the ram usage

#### Traceback

```

```

**Comment by anurag3301** [comment]
If its `pandoc`'s problem, please do let me know how can I inform them about this.

**Comment by markus-bauer** [comment]
I think this is already solved:
https://github.com/ranger/ranger/commit/9da2b4c79323a3f34da8d54198364d549a29ff00

See also:
https://github.com/ranger/ranger/issues/2594

There hasn't been a ranger release in a long time. Try to use the github master branch.

And, please search for existing issues before opening a new one.

**Comment by anurag3301** [comment]
Sorry, didnt know about that, Thank you.
BTW why there hasn't been any release for ranger in a long time.

**Comment by markus-bauer** [comment]
Don't know. I think the maintainer(s) just don't have enough time.

Also, If you look at the patch I linked, you'll see that it's just a small change in scope.sh.
If you want to use ranger from your package manager, it might be enough to modify that file (scope is considered to be a config file anyway).

**Comment by anurag3301** [comment]
Okay, so I think I got the solution. Hope we get further releases for ranger.
