### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by KAZI-SAMIR** [ranger/ranger#2658]
#### Runtime Environment

- Operating system and version: Termux Emulator
- Terminal emulator and version: linux
- Python version: 3.10.0
- Ranger version/commit: latest
- Locale: 

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```
ImportError: cannot import name 'link' from 'os' (/data/data/com.termux/files/usr/lib/python3.10/os.py)
```

**Comment by p3nal** [comment]
This is a termux issue not a ranger one. I don't think ranger is meant to be ran on termux.

**Comment by toonn** [comment]
`link` is a function in Python`s `os` module so I'm not sure what's going wrong here. Maybe Termux adds a directory to Python`s Module Search Path? May be worth raising this issue with the Termux maintainers.

I'm closing this for now as it seems unlikely to be a ranger issue. Apologies for taking so long to get around to this, trying to catch up to the backlog.
