### ISSUE TITLE
Unable to map modifier keys

### ISSUE THREAD

**Issue by zaxebo1** [ranger/ranger#266]
as suggested somewhere, I installed trash-cli and then in rc.conf of ranger, put the following line
map <DELETE> shell -s trash-put %s

so, now pressing "**delete**" button inside ranger, sends it to trash (just like what happens in nautilus)
# 

QUESTION 1:
Now, my question is that, (just like in nautilus) I want to define that pressing "**shift+delete**" should not send it to trash, but rather directly delete it (preferably showing warning before going to delete) . HOW to do it?
I tried all of the below lines in rc.conf:
 map <s-DELETE> shell -s rm -f %s 
map <s-DELETE>  console delete
but none of them worked. And additionally i want it to ask confirmation(y/n) before actually deleting it
# 

QUESTION2:
In ranger, How to select  multiple files(consecutively listed) 
( for example: In nautilus, we press Shift+Uparrow (or Shift+Downarrow) to select multiple consecutive files  )
actually if i have ten consecutive files - which need to be selected, then pressing "space" for each of them is very cumbersome. In nautilus, we have shift+Uparrow and shift+downarrow to select multiple consecutively listed files. How can i emulate it in ranger

**Comment by hut** [comment]
Q1: `map <S-DELETE> delete` works for me. If you have an older ranger version where the key `<S-DELETE>` was not implemented yet, try `:map <383> delete`.
To ask for confirmation, add `set confirm_on_delete always` to your ~/.config/ranger/rc.conf.

Q2: Excerpt from the man page:

       Space         Mark a file.
       v             Toggle the mark-status of all files
       V             Starts the visual mode, which selects all
                     files between the starting point and the
                     cursor until you press ESC.  To unselect
                     files in the same way, use "uV".

**Comment by zaxebo1** [comment]
Answer1) thanks for reply . I am using ranger version 1.6.1 on ubuntu 12.04 , in my PC this Answer1 is still not working. But now as you have given me the hint, i will look into it . Thanks :-)   

Answer2) I have reworded my question . Probably i was not able to convey my question clearly earlier. Now read my question 2 as :
**'(like in nautilus) can i somehow map my shift+uparrow and shift+down arrow keybindings also to the functionality of what "V and ESC" are currently providing in ranger. That is, can i additionally map keys such that till Shift+Downarrow is pressed that files are keep being marked for selection, until i lift the shift+Downarrow' . actually, I want to emulate nautilius keybindings as much close as possible.

**Comment by eMPee584** [comment]
`map <s+delete> [anything]` also doesn't work for me (with `'s-delete': curses.KEY_SDC` defined), neither does `<383>`.. both just opens console *:*
*<SHIFT><DEL>* in console mode echoes `[3;2~` here, for reference.

**Comment by zaxebo1** [comment]
i agre with @eMPee584  . s-delete is not working with me too even with latest git version of ranger  :-(

**Comment by eMPee584** [comment]
@zaxebo1 if you press <s-del> on console, does it print the same sequence for you?
also, paste the output of `:shell -p infocmp -1L`, mine is here:

```

screen-256color|GNU Screen with 256 colors,                                                                                               [109/511]
        auto_right_margin,
        backspaces_with_bs,
        eat_newline_glitch,
        has_hardware_tabs,
        has_meta_key,
        move_insert_mode,
        move_standout_mode,
        columns#80,
        init_tabs#8,
        lines#24,
        max_colors#256,
        max_pairs#32767,
        acs_chars=++\054\054--..00``aaffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        back_tab=\E[Z,
        bell=^G,
        carriage_return=^M,
        change_scroll_region=\E[%i%p1%d;%p2%dr,
        clear_all_tabs=\E[3g,
        clear_screen=\E[H\E[J,
        clr_bol=\E[1K,
        clr_eol=\E[K,
        clr_eos=\E[J,
        cursor_address=\E[%i%p1%d;%p2%dH,
        cursor_down=^J,
        cursor_home=\E[H,
        cursor_invisible=\E[?25l,
        cursor_left=^H,
        cursor_normal=\E[34h\E[?25h,
        cursor_right=\E[C,
        cursor_up=\EM,
        cursor_visible=\E[34l,
        delete_character=\E[P,
        delete_line=\E[M,
        ena_acs=\E(B\E)0,
        enter_alt_charset_mode=^N,
        enter_blink_mode=\E[5m,
        enter_bold_mode=\E[1m,
        enter_ca_mode=\E[?1049h,
        enter_insert_mode=\E[4h,
        enter_reverse_mode=\E[7m,
        enter_standout_mode=\E[3m,
        enter_underline_mode=\E[4m,
        exit_alt_charset_mode=^O,
        exit_attribute_mode=\E[m\017,
        exit_ca_mode=\E[?1049l,
        exit_insert_mode=\E[4l,
        exit_standout_mode=\E[23m,
        exit_underline_mode=\E[24m,
        flash_screen=\Eg,
        init_2string=\E)0,
        insert_line=\E[L,
        key_backspace=\177,
        key_btab=\E[Z,
        key_dc=\E[3~,
        key_down=\EOB,
        key_end=\E[4~,
        key_f1=\EOP,
        key_f10=\E[21~,
        key_f11=\E[23~,
        key_f12=\E[24~,
        key_f2=\EOQ,
        key_f3=\EOR,
        key_f4=\EOS,
        key_f5=\E[15~,
        key_f6=\E[17~,
        key_f7=\E[18~,
        key_f8=\E[19~,
        key_f9=\E[20~,
        key_home=\E[1~,
        key_ic=\E[2~,
        key_left=\EOD,
        key_mouse=\E[M,
        key_npage=\E[6~,
        key_ppage=\E[5~,
        key_right=\EOC,
        key_up=\EOA,
        keypad_local=\E[?1l\E>,
        keypad_xmit=\E[?1h\E=,
        newline=\EE,
        orig_pair=\E[39;49m,
        parm_dch=\E[%p1%dP,
        parm_delete_line=\E[%p1%dM,
        parm_down_cursor=\E[%p1%dB,
        parm_ich=\E[%p1%d@,
        parm_insert_line=\E[%p1%dL,
        parm_left_cursor=\E[%p1%dD,
        parm_right_cursor=\E[%p1%dC,
        parm_up_cursor=\E[%p1%dA,
        reset_2string=\Ec\E[?1000l\E[?25h,
        restore_cursor=\E8,
        save_cursor=\E7,
        scroll_forward=^J,
        scroll_reverse=\EM,
        set_a_background=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
        set_a_foreground=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
        set_attributes=\E[0%?%p6%t;1%;%?%p1%t;3%;%?%p2%t;4%;%?%p3%t;7%;%?%p4%t;5%;m%?%p9%t\016%e\017%;,
        set_tab=\EH,
        tab=^I,
```

**Comment by eMPee584** [comment]
@zaxebo1: you still haven't provided the output of `:shell -p infocmp -1L`
with `TERM=xterm ranger`, binding `s-delete` works, but neither `<alt><left/right>` nor `<s-f12>` nor `<c-f12>` . Neither in xterm nor konsole nor guake (vte). And with `TERM=screen` or `linux`, `<s-f12>` and `<s-del>` show command prompt `:`, then escape sequence if pressed again.
And `<SHIFT-TAB>` always works ? 
very strange :confused:

**Comment by zaxebo1** [comment]
@eMPee584 currently i am out of city for long and away from my laptop.
I will report within two - three days, when i get back to my laptop.

**Comment by zaxebo1** [comment]
the output of :shell -p infocmp -1L is:

#       Reconstructed via infocmp from file: /lib/terminfo/x/xterm
xterm|X11 terminal emulator,
        auto_right_margin,
        back_color_erase,
        backspaces_with_bs,
        eat_newline_glitch,
        has_meta_key,
        move_insert_mode,
        move_standout_mode,
        no_pad_char,
        prtr_silent,
        columns#80,
        init_tabs#8,
        lines#24,
        max_colors#8,
        max_pairs#64,
        acs_chars=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        back_tab=\E[Z,
        bell=^G,
        carriage_return=^M,
        change_scroll_region=\E[%i%p1%d;%p2%dr,
        clear_all_tabs=\E[3g,
        clear_screen=\E[H\E[2J,
        clr_bol=\E[1K,
        clr_eol=\E[K,
        clr_eos=\E[J,
        column_address=\E[%i%p1%dG,
        cursor_address=\E[%i%p1%d;%p2%dH,
        cursor_down=^J,
        cursor_home=\E[H,
        cursor_invisible=\E[?25l,
        cursor_left=^H,
        cursor_normal=\E[?12l\E[?25h,
        cursor_right=\E[C,
       cursor_up=\E[A,
        cursor_visible=\E[?12;25h,
        delete_character=\E[P,
        delete_line=\E[M,
        enter_alt_charset_mode=\E(0,
        enter_am_mode=\E[?7h,
        enter_blink_mode=\E[5m,
        enter_bold_mode=\E[1m,
        enter_ca_mode=\E[?1049h,
        enter_insert_mode=\E[4h,
        enter_reverse_mode=\E[7m,
        enter_secure_mode=\E[8m,
        enter_standout_mode=\E[7m,
        enter_underline_mode=\E[4m,
        erase_chars=\E[%p1%dX,
        exit_alt_charset_mode=\E(B,
        exit_am_mode=\E[?7l,
        exit_attribute_mode=\E(B\E[m,
        exit_ca_mode=\E[?1049l,
        exit_insert_mode=\E[4l,
        exit_standout_mode=\E[27m,
        exit_underline_mode=\E[24m,
        flash_screen=\E[?5h$<100/>\E[?5l,
        init_2string=\E[\041p\E[?3;4l\E[4l\E>,
        insert_line=\E[L,
        key_b2=\EOE,
        key_backspace=\177,
        key_btab=\E[Z,
        key_dc=\E[3~,
        key_down=\EOB,
        key_end=\EOF,
        key_enter=\EOM,
        key_f1=\EOP,
        key_f10=\E[21~,
        key_f11=\E[23~,
        key_f12=\E[24~,
        key_f13=\E[1;2P,
        key_f14=\E[1;2Q,
        key_f15=\E[1;2R,
        key_f16=\E[1;2S,
        key_f17=\E[15;2~,
        key_f18=\E[17;2~,
        key_f19=\E[18;2~,
        key_f2=\EOQ,
        key_f20=\E[19;2~,
        key_f21=\E[20;2~,
        key_f22=\E[21;2~,
        key_f23=\E[23;2~,
        key_f24=\E[24;2~,
        key_f25=\E[1;5P,
        key_f26=\E[1;5Q,
        key_f27=\E[1;5R,
        key_f28=\E[1;5S,
        key_f29=\E[15;5~,
        key_f3=\EOR,
        key_f30=\E[17;5~,
        key_f31=\E[18;5~,
        key_f32=\E[19;5~,
        key_f33=\E[20;5~,
        key_f34=\E[21;5~,
        key_f35=\E[23;5~,
        key_f36=\E[24;5~,
        key_f37=\E[1;6P,
        key_f38=\E[1;6Q,
        key_f39=\E[1;6R,
        key_f4=\EOS,
        key_f40=\E[1;6S,
        key_f41=\E[15;6~,
        key_f42=\E[17;6~,
        key_f43=\E[18;6~,
        key_f44=\E[19;6~,
        key_f45=\E[20;6~,
        key_f46=\E[21;6~,
        key_f47=\E[23;6~,
        key_f48=\E[24;6~,
        key_f49=\E[1;3P,
        key_f5=\E[15~,
        key_f50=\E[1;3Q,
        key_f51=\E[1;3R,
        key_f52=\E[1;3S,
        key_f53=\E[15;3~,
        key_f54=\E[17;3~,
        key_f55=\E[18;3~,
        key_f56=\E[19;3~,
        key_f57=\E[20;3~,
        key_f58=\E[21;3~,
        key_f59=\E[23;3~,
        key_f6=\E[17~,
        key_f60=\E[24;3~,
        key_f61=\E[1;4P,
        key_f62=\E[1;4Q,
        key_f63=\E[1;4R,
        key_f7=\E[18~,
        key_f8=\E[19~,
        key_f9=\E[20~,
        key_home=\EOH,
        key_ic=\E[2~,
        key_left=\EOD,
        key_mouse=\E[M,
        key_npage=\E[6~,
        key_ppage=\E[5~,
        key_right=\EOC,
        key_sdc=\E[3;2~,
        key_send=\E[1;2F,
        key_sf=\E[1;2B,
        key_shome=\E[1;2H,
        key_sic=\E[2;2~,
        key_sleft=\E[1;2D,
        key_snext=\E[6;2~,
        key_sprevious=\E[5;2~,
        key_sr=\E[1;2A,
        key_sright=\E[1;2C,
        key_up=\EOA,
        keypad_local=\E[?1l\E>,
        keypad_xmit=\E[?1h\E=,
        memory_lock=\El,
        memory_unlock=\Em,
        orig_pair=\E[39;49m,
        parm_dch=\E[%p1%dP,
        parm_delete_line=\E[%p1%dM,
        parm_down_cursor=\E[%p1%dB,
        parm_ich=\E[%p1%d@,
        parm_index=\E[%p1%dS,
        parm_insert_line=\E[%p1%dL,
        parm_left_cursor=\E[%p1%dD,
        parm_right_cursor=\E[%p1%dC,
        parm_rindex=\E[%p1%dT,
        parm_up_cursor=\E[%p1%dA,
        print_screen=\E[i,
        prtr_off=\E[4i,
        prtr_on=\E[5i,
        reset_1string=\Ec,
        reset_2string=\E[\041p\E[?3;4l\E[4l\E>,
        restore_cursor=\E8,
        row_address=\E[%i%p1%dd,
        save_cursor=\E7,
        scroll_forward=^J,
        scroll_reverse=\EM,
        set_a_background=\E[4%p1%dm,
        set_a_foreground=\E[3%p1%dm,
        set_attributes=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
        set_background=\E[4%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m,
        set_foreground=\E[3%?%p1%{1}%=%t4%e%p1%{3}%=%t6%e%p1%{4}%=%t1%e%p1%{6}%=%t3%e%p1%d%;m,
        set_tab=\EH,
        tab=^I,
        user6=\E[%i%d;%dR,
        user7=\E[6n,
        user8=\E[?1;2c,
        user9=\E[c,

**Comment by zaxebo1** [comment]
<SHIFT><DEL> in console mode echoes 2~       on my machine

**Comment by zaxebo1** [comment]
now, i am using ranger version 1.6.1 on top of Python 3.4.3  (python was compiled with GCC 4.6.3), which is running on ubuntu 12.04 LTS

**Comment by nfnty** [comment]
Are you still having this issue on `master`? What terminal emulator are you using? tmux?

**Comment by zaxebo1** [comment]
i have not checked it with master, i checked it with the ranger 1.7.1 , which is packaged in ubuntu.
I am just using plain gnome-terminal (i am not using tmux,urxvt etc)

i will check it tonight with master and then update it here

**Comment by nfnty** [comment]
This will need quite a bit of work to solve completely. Continue discussion in #574.
