### ISSUE TITLE
selected item incorrect after sort

### ISSUE THREAD

**Issue by adlainewson** [ranger/ranger#2660]
#### Runtime Environment

- Operating system and version: Arch linux
- Terminal emulator and version: Alacritty
- ranger version: ranger 1.9.3
Python version: 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0]
Locale: en_US.UTF-8

#### Current Behavior
After a sort, the selected item is not correctly updated. 

### Reproduce
- navigate to directory, note that the first item is selected (eg, directory AAA)
- sort directory based on new criterea
- note that the first item in the directory post-sort is now selected (eg, file ZZZ)
- press enter to open selected file (ie, ZZZ)
- instead, directory AAA will open

#### Expected Behavior
- Selected file highlighting should either update after the sort (AAA remains highlited after sort) or selected file should change after sort (file ZZZ should open)

```

```

**Comment by markus-bauer** [comment]
I just can't reproduce this. (Although I didn't test in in alacritty.)

For me, the cursor stays on the selected item (AAA in your example).
This is what should happen.

Does this happen with a clean version of ranger?

**Comment by adlainewson** [comment]
hmm, you're right it doesn't happen with default conf. here is my config: https://pastebin.com/UzG8FBkd

**Comment by markus-bauer** [comment]
I tried your config. From what I saw, the bug only happens in multipane view.
It doesn't happen in the never ranger versions. So it looks like this bug was already fixed.
(Don't know where exactly, perhaps: https://github.com/ranger/ranger/commit/0c54184fbc507c81d4eee77f71df27152535e226.)

Can you try the github master branch and see if this fixes the issue?

**Comment by adlainewson** [comment]
ah you're right, this is fixed using master branch, cheers!
