### ISSUE TITLE
[Feature Request] Command to show all currently running tasks

### ISSUE THREAD

**Issue by luiz00martins** [ranger/ranger#2665]
#### Runtime Environment

- Operating system and version: Pop!_OS 22.04 LTS x86_64
- Terminal emulator and version: zsh 5.8.1 (x86_64-ubuntu-linux-gnu)
- Python version: Python 3.10.4
- Ranger version/commit: ranger-master
- Locale: en_US.UTF-8

#### Context
Sometimes when using Ranger, I'll have some task that sticks in the background, blocking me from quitting the program. That's not a problem. Sometimes that's a bad config, sometimes a bug, or sometimes it's simply a long task, that I have to wait to finish.

The problem however, is that I don't know what the task is. I don't know if it's an important task, that I really should wait on, or if it's unimportant and I should just force quit. It would be nice to know what's blocking Ranger from exiting.

#### Possible Solutions
- A command (e.g. `:current_tasks`) that would present a list of currently running tasks
- Clicking on the active "loading icon" on the top right would display a popup with a list of currently running tasks

**Comment by markus-bauer** [comment]
I think you're looking for 'taskview'. 
task view can be opened by pressing 'w'.
Look in rc.conf to see more button mappings related to taskview (tmap). Or search the man page.

**Comment by luiz00martins** [comment]
Thank you! 

_Note for future readers: The command is `:taskview_open`_
