### ISSUE TITLE
ranger crashed and requested to be reported as an issue here

### ISSUE THREAD

**Issue by brandonnola** [ranger/ranger#2666]
#### Runtime Environment

- Operating system and version: 
- Terminal emulator and version: 
- Python version: 
- Ranger version/commit: 
- Locale: 

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```









```

**Comment by p3nal** [comment]
Hello, could you please put the error that ranger displayed (Traceback) (the lots of mumbo jumbo displayed when crashing) in here so the community can help? Also if you can try and pinpoint what you did that caused it to crash. Thank you.

**Comment by toonn** [comment]
Without information we can't help. Feel free to open a new issue and fill out the template if you're still experiencing this.
