### ISSUE TITLE
Add nsxiv to sxiv_workaround_hook(...)

### ISSUE THREAD

**Issue by someApprentice** [ranger/ranger#2671]
Sxiv now is unmaintained and [nsxiv](https://github.com/nsxiv/nsxiv) came as a replacement of it. It fixes some bugs (for example some gifs don't play in sxiv for me) and «adding simple, sensible features».

But ranger doesn't open all files in the current directory with this fork and [nsxiv-rifle](https://codeberg.org/nsxiv/nsxiv-extra/src/branch/master/scripts/nsxiv-rifle) doesn't keeping the order of files the same as in ranger.

I don't know about ranger's implementation details but seems like you just need to add `nsxiv` to [this](https://github.com/ranger/ranger/blob/391f061cb0b0cfa8266c0651f2a6d948f22e01dd/ranger/core/fm.py#L154) line and exactly the same condition block for it as for sxiv. nsxiv accepts exactly the same arguments.

```
re.match(r'^(feh|sxiv|nsxiv|imv|pqiv) ', command):

...

    if command[0:6] == 'nsxiv ':
        number = images.index(self.thisfile.relative_path) + 1
        new_command = command.replace("nsxiv ", "nsxiv -n %d " % number, 1)
```

As a temporary solution (for those who came across to this feature request) one can create a symlink to nsxiv:

`ln -s /usr/bin/nsxiv /usr/bin/sxiv`

and everything will work.

**Comment by toonn** [comment]
I've implemented this suggestion in #2739. Could you test this?
