### ISSUE TITLE
Project dependencies may have API risk issues

### ISSUE THREAD

**Issue by PyDeps** [ranger/ranger#2676]
Hi, In **ranger**, inappropriate dependency versioning constraints can cause risks.

Below are the dependencies and version constraints that the project is using
```
flake8*
pylint*
pytest*
```

The version constraint **==** will introduce the risk of dependency conflicts because the scope of dependencies is too strict.
The version constraint **No Upper Bound** and **\*** will introduce the risk of the missing API Error because the latest version of the dependencies may remove some APIs.

After further analysis, in this project,
The version constraint of dependency **pylint** can be changed to *>=2.2.0,<=3.0.0a5*.

The above modification suggestions can reduce the dependency conflicts as much as possible, 
and introduce the latest version as much as possible without calling Error in the projects.

The invocation of the current project includes all the following methods.

    
<details>
<summary>The calling methods from the pylint</summary>
<pre>
utils.safe_infer
</pre>
</details>

    
<details>
<summary>The calling methods from the  all methods</summary>
<pre>
self.fm.mimetypes.guess_type
human_readable
tokens.pop
Runner
node.root
func
fm.datapath
char.isspace
input
get_color
signal.fm.bookmarks.enable_saving_backtick_bookmark
thread.start
self.fm.thisdir.filter_stack.append
path_user.islower
MetadataManager
v.path.startswith
self.tags.add
cmds.update
linum_format.format
perms.append
key_to_string
self.fm.relpath
curses.mouseinterval
self.fm.run
defaultdict
self._draw_line
args.len.self.line.lstrip
self.ui.close_pager
cmdfile.write
Popen
self.container.index
_basename
_in_screen
self.suspend
curses.noecho
self.execute_console
util.spec_from_file_location
self._set_scroll_begin
self.tab_deque.rotate
_in_tmux
META_DICT.items
self.load_if_outdated
hook_before_drawing
token.startswith
fm.commands.load_commands_from_module
datetime.now
os.path.basename
self.fm.thisdir.set_linemode_of_children
self.fm.get_directory
arg.find
ansi_re.sub
self.fm.datapath
regex.search
ranger.api.hook_ready
path_file.startswith
self.history_backup.add
self.hint
fsobj.vcs.reinit
column.resize
self._get_sizes
find_conf_path
self._set_metadata_raw
self.process.stdin.write
min
KeyMaps
sys.stdin.fileno
displayable.click
cwd.move
tagged_display.append
datetime.strptime
fnc
line.split
self.shift
os.chmod
deque
popen2.wait
random.random
self.type_key
group_by_hash
json.dumps
directory.load_content_if_outdated
get_common_base
char.encode
Py2CompatibilityChecker
io.TextIOWrapper
symlink
names.index
profile.strip_dirs.sort_stats
self.load
self.marked_items.append
signal_name.self._signals.sort
self.enter_dir
self.fm.default_linemodes.appendleft
base.split
self.taskview.resize
self.handle_key
fm.settings.nested_ranger_warning.lower
ord
paths.sort
self.fm.input_is_blocked
self.get_focused_obj
self.empty
self.addstr
MethodType
subprocess.check_output
self.bulkrename.super.__init__
shutil.copy
win.getch
self.load_bit_by_bit
os_stat
chunk.hashes.append
pattern.startswith
event.mouse_wheel_direction
diskcmd.subprocess.check_output.decode.replace.replace
os.path.join
context.squash_flags
fobj.read.base64.b64encode.decode
self.tab_open
self.container.remove
tabs_saved.split
path.endswith
git_describe.communicate
prompt_metadata._console_chain.pop
get_paths
self.right.fixedsize
pattern.islower
temporarily_moved_cursor
self.set_search_method
path.startswith
self.msg.is_alive
filt
SignalDispatcher.__init__
disk.upper
self.fm.ui.keymaps.use_keymap
rootvcs.check_outdated
exists
self.thisdir.search_fnc
self.hook_environment
self.titlebar.resize
self._exit_no_work
path_file.lower
self.fm.thisdir.unload
self.fm.ui.keymaps.bind
self.fm.block_input
repr
set.dirname.groups.setdefault.add
value.lower
locale.strxfrm
logging.FileHandler
self._is_targeted
pathstring.split
self.signal_emit
History
check_output.strip
is_directory_with_files
stack.extend
Exception
arg.replace
self.fm.confpath
self.line.rsplit
string._MacroTemplate.safe_substitute
self._generate_w3m_input
self.fm.exit
self.keymaps.use_keymap
os.rename
command.split.split.strip
self.fm.select_file
etree.fromstring
typ
command_alias_factory
self.browser.pager.draw_image
self.fm.ui.press
import_file
datetime.fromtimestamp
self._settings.get
linemode
isfunction
self.paused.wait
self.ui.setup_curses
self.nonpersistent_bookmarks.remove
new_browser.resize
tests.split
Direction.down
self.on_line_change
QueueHandler
cwd.unload
tablist.index
options.p.isdigit
self.stdbin.read
makedirs
doctest.testmod
self._get_font_dimensions
self.parse_setting_line
basename.re.search.end
self.obj.fm.get_directory
self.thistab.get_selection
self.add_to_history
NamedTemporaryFile
item.relative_path.lower
self.queue.popleft
self.win.getch
self._parse
self.history.append
self._draw_hints
cProfile.run
text.startswith
Loadable.__init__
event.pressed
popen2.stdout.close
self.set_fg_bg_attr
path_user.lower
self.get_duplicates
fm.source
keybuffer.add
f.replace
self.fm.edit_file
self.fm.commands.alias
Bookmarks
self._clean_input
type
self.get_outputs
stack.append
self.pos.self.question_queue.decode
copyfile
command.find
rifle.list_commands
self.browser.columns.clear_image
Loadable.pause
self._signals.values
cwd.toggle_mark
ColorScheme
self.replace_child
display_data.append
keys.pop
node.previous_sibling
self.get_selection_attr
self.marked_items.remove
self._tab_directory_content
signal.fm.relpath
self.history.add
line.rindex
self.ui.browser.main_column.scroll
target.fm.get_directory
ValueError
xdg_path
press_enter
abs
ismount
ViewBase.draw
self.rebuild
log.append
self.right.sumsize
localtime
Vcs
self._get_index_of_selected_file
self.notify
some_dir.count
self.sha512_encode
self.history_backup.fast_forward
self.confpath
self.bookmarktype
self._draw_bookmarks
bar.shrink_from_the_left
temporary_file.write
set
self.thisdir.sort_if_outdated
self._update_walk
cwd.mark_item
self.target.has_preview
self._tab_fuzzy
basename
line.strip
UI
self.dct.items
callback
self.fm.get_tab_list
self._build_command
Accumulator.correct_pointer
string.lstrip.split
self._get_image_dimensions
rifle.execute
self.add_message
self.main_column.scroll
command_class
self.original_copy_buffer.clear
expanduser
codecs.lookup
groups.items
self.ui.status.request_redraw
curses_interrupt_handler.install_interrupt_handler
inode_path.encode
SignalHandler
self.data_info
rifle.get_mimetype
fm.initialize
word_beginnings.append
self.bookmarks.enter
self._activate_ui
self.__init__
self._tab_paths
i.str.isdigit
self.set
os.path.abspath
window.addstr
load_settings
self.fm.tabs.values
child.destroy
self.history.remove
partitions.lower
fm.notify
get_term
self.fm.bookmarks.update_if_outdated
value.split
hints.sort
self._get_tab
Directory
Message
self.restorable_tabs.append
arg.len.rest.lstrip
states.append
flatten
output.split
_copyxattr
logging.getLogger
self
self.pager.resize
answer.lower
old_sort_func
self.fm.thisdir.load_content
self.parse_flags
self.rifle.list_commands
self._is_app
zombie.poll
codecs.encode
sorted
DisplayableContainer.destroy
self.history.__iter__
strftime
arg.encode
KeyError
rootvcs.update_root
paths.add
self._load_dict
self._gc_marked_items
self._draw_border_rectangle
cdpath.split
vcsstr.strip
self._viewmode_to_class
self.arg
direction.move_cycles
curses.curs_set
self.save
copy
self.bookmarks.update_if_outdated
data.get
path.strip
path.str.startswith
self.bidi_transpose
self.REPOTYPES.items
self.hook_command_postprocessing
CopyLoader
groups.append
_MacroTemplate
self.hook_before_executing
path.replace
f.upper
line_bit.rstrip
self.fm.tab_new
self.stopped.wait
self.ui.taskview.move
utils.safe_infer
wrootobj.load_if_outdated
ACCEPT_FILE_OLD
self.path_re_squoted.match
getsize
self.fm.thisdir.vcs.action_add
curses.tigetstr
self.fm.ui.keymaps.unbind
file.shell_escaped_basename.startswith
self._tab_args
robjs.read
self.status.clear_message
mypath.count
join
self.fm.signal_bind
git_description.strip
unique
self.data_branch
self.win.touchwin
profile.strip_dirs
self.fm.set_search_method
self.tunmap.super.execute
self.init_line
command.rindex
tabshiftreorder
iter
self.stopped.set
self.redrawlock.set
self.fm.ui.win.move
curses.initscr
self.garbage_collect
warning.upper
self.bind
self.right.add
self.target.empty
process.poll
self._calculate_size
self.ui.redraw_window
self.rifle.execute
self.fm.move_parent
self._run.split
HOOK_READY_OLD
partcmd.subprocess.check_output.decode
self.move
logging.StreamHandler
self._get_line
self.fm.tab_close
filenames.join.encode
self.load_content_once
self.execute_file
time.strftime
mimetypes.init
spec.loader.exec_module
file_handle.seek
self.files_all.reverse
self.copy_buffer.difference_update
chardet.detect
pathway.append
special_keys_init
self.links.remove
self.history.modify
groupby
self.keys.append
json.loads
upos.uchar.join.encode
self.fm.open_console
logging.Handler.__init__
self.__setattr__
parser.add_option
TaskView
self._get_owner
FileManagerAware.fm_set
shlex.split
paths_seen.add
self.fm.thisdir.filter_stack.pop
cwd.correct_pointer
getattr
BarSide
self.metafile_cache.clear
check_output
self._awoken.set
plugins.append
rifle.reload_config
self.display_file
locals
os.fork
curses.tparm
item.get_description
east_asian_width
self.fm.ui.keymaps.copy
self.ctrl
direction.vertical
handler.setFormatter
ostruct
subprocess.Popen
var
self.signal_bind
mkdtemp
self.pointer_is_synced
math.ceil
t.lower
column.level_restore
value_completers.get
self.nonpersistent_bookmarks.add
executables.add
self.fm.update_preview
special_keys.update
self.execute
colorstr.__dict__.update
self._parent.get
tmpf.name.encode
selectlist.append
statuses.add
self.fm.toggle_option
self.paused.clear
self.left.add
self.pos.self.line.decode
self.pager.close
Pager.__init__
f.strip.split
cwd.cycle
startswith
self._mimetype_known_files.append
scripts_hack
self._tab_fuzzy_match
module.vars.values
self.signal_function_factory
self.ui.destroy
win.refresh
self.target.get_preview_source
self.fm.execute_console
self.keybuffer.clear
self.thistab.enter_dir
source.splitlines
GET_MACROS_OLD
stat.S_IMODE
self.metadata_cache.clear
line.startswith
self.initialize
self.tab_close
walklevel
uwid
tab.enter_dir
listdir
self.rest.split
self._fit_width
self._get_metafile_content
self.win.addnstr
self.list_commands
LocalSettings
self.console.close
self.thisdir.refilter
self.search_next
rel_dest.startswith
self.loader.destroy
self.look_up_cumulative_size
queue.Queue
self.dct.update
self.assign_cursor_positions_for_subdirs
_colorscheme_name_to_class
relpath
sha512
image_displayer_class
self.tags.remove
self.stdbout.write
node.root.scope_lookup
self._late_init
os.symlink
self.left.sumsize
path.split
load_custom_commands
str
self.win.getparyx
self.fixedsize
_setup_mouse
self.win.leaveok
self.settings.set
self.tab_new
self.fm.dump_keybindings
self.__stop.is_set
fname.endswith
loader.has_work
self.is_binary
rootvcs.init_root
flags.find
real_dict.copy
self._close_source
self.rest.replace
image.getdata
self.fm.tab_move
DisplayableContainer.press
command.split
exec
self.fm.loader.remove
Widget.poke
warnings.simplefilter
fobj.read
displayable.finalize
self.cunmap.super.execute
locale.getlocale
self.datapath
handlers.sort
command.replace
self._draw_message
obj.pause
parse_arguments
self._advance.set
partcmd.subprocess.check_output.decode.replace.replace
self._close_command_prompt
value.self._viewmode_to_class
date.date
Signal
Widget.destroy
pointer.items
base64.standard_b64encode
self.remove_child
struct.pack
self.__eq__
self.data_status_subpaths
cmdfile.flush
os.environ.split
cmd.execute
self._queue_process
issubclass
re.match
self.queue.pause
hash
string.lstrip
root.count
self.close_pager
self.browser.open_pager
link
self.fm.execute_command
stdin.write
_ALIAS_LINE_RE.split
is_scheme
self.fm.rename
self.fm.image_displayer.quit
SystemExit
self._get_metafile_names
obj.parent.remove_child
self.thistab.history_go
self.ui.get_pager
self.parse_setting_line_v2
self._format_line_number
direction.left
self._get_metafile_name
self.set_load_mode
args.append
self._get_max_sizes
os.environ.get.upper
ImgDisplayUnsupportedException
next_available_filename
string_control_replace
image.convert
self.ui.open_taskview
self._mimetype.startswith
getuid
self.image_displayer.quit
_command_init
curses.echo
get_executables_uncached
self.fm.metadata.get_metadata
item.vcs.rootvcs.status_subpath
abspath
f.lower
self.win.getmaxyx
self.columns.append
files.append
sha256
self._execute
ViewBase.poke
atexit.register
Default.use
ansi.char_slice
fsrc.read
wdirs.remove
self.fm.set_option_from_string
os._exit
maketrans
self.rest.strip
image.resize
dir
Pager.draw
self.jump_non.super.__init__
LOG.exception
dirpath.count
fobj.look_up_cumulative_size
dirobj.vcs.__init__
Displayable.__init__
self.rifle.reload_config
Widget.__init__
child.has_preview
self.get_unique
self.fm.thisfile.load_if_outdated
codesplit_re.findall
self._recurse_hardlinked_tree
self.sumsize
os.path.split
self.path_re_unquoted.match
path.count
os.path.relpath
string.split
ui.set_load_mode
getpwuid
self._tab_normal
weakref.proxy
self.current
os.setsid
fobj.stat.st_mtime.datetime.fromtimestamp.strftime
string_to_charlist
self.status.resize
self.columns.has_preview
self.tabs.values
self.backend.open
self.handle_mouse
fm.commands.load_commands_from_object
tuple
self._method
_destinsrc
self._get_default
pager.move
dn.startswith
SettingsAware.settings_set
any
Error
zip_longest
dirobj.vcs.reinit
inode_path.sha512.hexdigest
shutil_g.copytree
self.punmap.super.execute
macros.update
handlers.append
os.wait
self.fm.loader.has_work
arg1.startswith
ViewBase.__init__
os.path.isabs
cmd.items
self.fm.tags.update_path
BrowserColumn
string.decode
__doc__.strip
win.derwin
diskcmd.subprocess.check_output.decode.replace
zip
update_dict.items
os.access
signal.default_int_handler
chr
self._localregexes.items
os.readlink
self._draw_tagged_display
self._find_w3mimgdisplay_executable
self.commands.get_command
encodings.insert
self.queue.appendleft
DisplayableContainer.finalize
self.process.communicate
self._compile
map
curses.tigetflag
item.rsplit
__file__.replace
self._draw_borders_setting
stat.S_ISSOCK
self.tab_move
self.bookmarks.enable_saving_backtick_bookmark
images.index
setup_logging
self.basename.lower
fobj.read.partition
chunk.hashes.remove
self.gap.add
pager.set_source
self._eval_condition
codecs.open
self.rename_append.super.__init__
get_display
cmdfile.read
args.paths.insert
sort_hints
dirobjs.append
self.fm.tags.marker
self._ui.fm.notify
WideString
all
self.fm.move
copytree
self.addch
kwargs.pop
self.start
self._non
rest.lstrip
f.basename.startswith
os.mkdir
codecs.decode
reversed
allowed.index
self.thisfile.get_preview_source
thunk
argument.isdigit
os.sep.join
shutil.rmtree
mount_path
self._awoken.clear
Pager.close
clipboards
self._get_entry
self._add_character
_EXTRACT_NUMBER_RE.split
function
self.fm.dump_settings
win.hline
unicodedata.category
linter.register_checker
self._queue.get
fm.confpath
os_lstat
ColorSchemeError
self._ui.redraw
curses.use_default_colors
hash_file
_is_terminal
fobj.write
os.environ.get
profile.strip_dirs.sort_stats.print_callees
cmd_class
float
fm.thistab.get_selection
temporary_filter_search
os.statvfs
filter_search
make_safe_path
self.source.close
sys.stdout.fileno
PREVIEW_BLACKLIST.search
self.redraw_window
LOG.info
stack.pop
ranger.main
k.startswith
KeyBuffer
self.VcsThread.super.__init__
focused_obj.press
hash_chunks
self.resize
curses.tigetnum
self.bookmarks.load
self.history.search
target.get_permission_string
self._set_pointer
self.line.split
self.left.pop
self.fm.tags.remove
self.fm.ui.status.request_redraw
fm.select_file
fobj.load_if_outdated
self.win.move
curses.color_pair
output.etree.fromstring.find
os.walk
self.rest
ljust
self.load_content
self.request_clear
re.MULTILINE.entry.re.search.group
self.traverse
self.string.chars.decode
self.thisfile.is_image_preview
DisplayableContainer.draw
warnings.catch_warnings
zombies.remove
importlib.import_module
self.correct_pointer
files.os.path.basename.rpartition
allow_access_to_confdir
self.pager.open
Direction.absolute
full_command.split
self._collapse
Loadable.unpause
self.right.pop
errors.append
window.getch
displayable.poke
fm.enter_dir
tab.at_level
self.color
self.arg.SIMPLE_FILTERS
Pager.open
hints.append
self.modes.keys
self.fm.thistab.at_level
split_ansi_from_text
self.tab_shift
self._get_offsets
cmd.items.v.k.v.k.format.join.encode
tab.inherit_history
cm.func.name.endswith
basename.rindex
os.remove
re.compile
__get_home_directory
int
self.arg.FILTER_COMBINATORS
DisplayableContainer.click
readlink
value
self.generate
i.self._get_line.expandtabs
os.utime
condition.startswith
stat
shutil_g.move
os.makedirs
self.status_subpaths.items
get_free_space
access
self.use
self.sync
sys.getfilesystemencoding
shell_escape
MacroDict
self._remote_ref
tmpf.flush
listfile.read
self.question_queue.decode
pstats.Stats
action.extend
groups.setdefault
os.stat
infostring.append
column.destroy
self.clear_image
self.vcsthread.unpause
self._queue.put
line_bit.rstrip.replace
eval
self.relpath
os.environ.startswith
self.handle_multiplexer
open
self._get_app_flags_mode
LOG.error
self._draw_file
popen2._wait
self.fm.paste
self.fm.ui.win.redrawwin
item.load
self._parse_option_value
unicode_buffer.encode.decode
self.fm.thisdir.path.startswith
item.startswith
self.restorable_tabs.pop
special_keys.values
others.get
abstractproperty
construct_keybinding
self.win.erase
cwd.toggle_all_marks
obj.unpause
results.replace
self._draw_text_display
self._generate_iterm2_input
self.draw
self.win.redrawwin
self.run
temporary_file.flush
_CACHED_EXECUTABLES.add
list
loadable.signal_bind
self._fill_console
self.basename.rindex
self._calc_bar
self.thisdir.correct_pointer
self._get_tab_text
self.fm.signal_emit
self.process.terminate
property
shell_quote
self.fm.thisdir.vcs.action_reset
self.browser.columns.draw_image
item.load_if_outdated
displayable.destroy
Popen23
dict
self.restore_multiplexer_name
string.str.replace
self._remove_current_process
recurse
self.fm.bookmarks.dct.values
script_lines.append
pager.set_image
self.poke
os.path.normpath
output.etree.fromstring.findall
self._run_pager
self._total_len
level.os.environ.isdigit
self.fill_gap
self.thisdir.load_content_if_outdated
self._log
self.settings.colorscheme.get_attr
basename.find
self.status_subpath
self.thisdir.get_selection
metadata.items
ImageDisplayError
populate_hints
curses.halfdelay
dirnames.sort
scheme_module.Scheme
ui.redraw
StatusBar
Widget.draw
devnull.close
diskcmd.subprocess.check_output.decode
self.addnstr
os.path.realpath
self._draw_infostring_display
json.load
tab_old
base_color.append
getLogger
self.close
self.loader.remove
target.load_content_if_outdated
max
f
fobj.path.spawn.check_output.strip
execute
self._remote_url
ui.handle_input
direction.horizontal
register_image_displayer
self.tag_toggle
write
displayable.get_focused_obj
os.path.exists
spawn.check_output
ranger.api.commands.CommandContainer
self._check_type
self.relative_path.lower
subpath.startswith
self._draw_directory_color
self._draw_directory
parse_keybinding
h.hexdigest
fobj.read.split
self.files_all.sort
self.fm.metadata.set_metadata
ui.draw_images
time
self._trash_files_catch_arg_list_error
self._get_centered_offsets
sys.argv.index
Tab
self._draw_info
self.target.move
self.ui.close_embedded_pager
Accumulator.__init__
os.chflags
self._status_translate
self.process.send_signal
csv.reader
self.win.addch
self.dump
self.history.rebase
Direction.right
time.time
self.add_child
pattern.re.escape.replace
macro_val
path.move_to_obj
authorstring.find
cmdfile.seek
self.queue.pop.destroy
curses.cbreak
self.press
self.update_if_outdated
path.translate
self.ui.suspend
self.pages
self._draw_vcsstring_display
self.CommandAlias.super.__init__
path.format.split
self.fm.thisdir.refilter
VcsThread
self._clear_marked_items
fdst.write
rel_dest.endswith
re.search
this_color.append
dest.endswith
self.fm.delete
bracket_content.join.lower
target.infostring.replace
self.fm.cd
fm.execute_console
os.chown
self.get_tab_list
self.load_pattern.match
self.line.decode
self.set_mimetype
lexists
self._get_group
sys.stdout.write
arg.search
sort_unicode_wrapper_list
self._roots.clear
mimetype.decode
self.fm.execute_file
self.__dict__.update
color_pair
OptionParser
win.vline
version_string.format
re.findall
self.win.attrset
self.ui.initialize
self.scout.super.__init__
self.commands.items
image.save
self.process.stdout.readline.split
self.ui.browser.main_column.request_redraw
self._get_repotype
directory.mark_item
self.fm.ui.win.refresh
self.fm.thistab.get_selection
self.fm.enter_dir
_context_init
target.load_if_outdated
self.ui.open_console
self.copy
Pager.clear_image
rootvcs.update_tree
self.fm.notify
self.one_indexed
dst_name.endswith
kwargs.setdefault
self._generate_lines
LOG.critical
get_all_colorschemes
self.refilter
settings.types_of
self.stdbout.flush
match.group
Loader
clr.append
relative.self.history.move.go
set_image_displayer
self._print_result
filters.append
self.settings.signal_bind
self._get_cumulative_size
self.fm.tags.dump
result.append
cwd.encode
self.setup
self._encode_image_content
directory.vcs.rootvcs.head.strftime
isinstance
self._calculate_offset
arg.isdigit
self._count
DisplayableContainer.resize
process.stdout.read
subprocess.check_call
self.change_mode
entry.find
item.unload
self.bookmarks.remember
left.add
self._get_scroll_begin
curses.ungetch
key.ljust
root_logger.setLevel
ignore
sys.stdout.flush
cwd.set_cycle_list
self.traverse_backwards
__import__
self.finalize
human_readable_time
handler.setLevel
var.get_name
setting.startswith
direction.right
curses.nocbreak
self.win.resize
h.update
self._format_cmd_str
self.fm.loader.move
self.ui.status.notify
self._run
self.color_reset
PREVIEW_WHITELIST.search
userinput.startswith
os.path.splitext
self.get_command
divmod
base_clr.append
item.mark_set
self.get_log
self.history.current
self.fm.ui.vcsthread.process
self.win.chgat
tokens.append
process.wait
bfile.path.startswith
main
mimetypes.guess_type
self.loader.add
ALLOWED_VALUES.items
DisplayableContainer.__init__
self._is_mode
self._set_dict
TagsDummy
self.mark_item
self._roots.add
bin_stdout.write
cwd.rsplit
self.percentage
f.read
listfile.write
left.add_space
tfile.relative_path.replace
findall
cls
self._build_regex
command_function_factory
get_relative_source_file
old_preprocessing_hook
self._raw_set
self.fm.ui.redraw_main_column
kw.get
ColoredString
new_dirs.append
newupos.uchar.join.encode
unique.add
self.question_queue.pop
dst.endswith
self.fm.tabs.items
ranger.api.hook_init
self.columns.clear_image
timer_kill.cancel
self.win.keypad
tmpf.write
collections.defaultdict.__init__
print
imghdr.what
i.self.columns.resize
signal.process.poll
self.enqueue
dst.count
item.unpause
direction.move
current_linemode.infostring
utils.parse_format_method_string
select.select
previous
curses.setupterm
vcsstring_display.append
self._draw_hint
pattern.endswith
self.process.poll
stdout.decode
self.cancel
robjs.readline
self.open_console
os.getpid
cwd.load_content
lstat
focused_obj.click
first_key_in_group
self.sync_index
Pager
self.tab_restore
path_init
self.tags.toggle
get_executables
bracket_content.append
program.startswith
FM
self.metadata.reset
tag.str.startswith
FileSystemObject.__init__
os.listdir
self.sort
environ.get
self.path.startswith
Context
random
self.append
curses.putp
getgrgid
self.format
format
lastdot.self.basename.lower
sys.stdin.isatty
CommandLoader
Settings
i.self.history.startswith
HOOK_INIT_OLD
self.history.move
partial
obj.get_description
squash_flags
errors.extend
self.data_status_remote
fm.ui.destroy
self.redrawlock.wait
Bar
arg.encode.decode
bytearray.join
func.bound.infer
normpath
self.vcsthread.paused.wait
globals
TitleBar
sys.version.splitlines
VcsError
cmd.tab
special_keys.items
duplicates.update
self.scrollbit
self.transpose_subr
self.fm.image_displayer.draw
sleep
_samefile
process.communicate
sys.stderr.write
handlers.remove
self._re_shift
os.mkfifo
program.str.rjust
bar.addright
parser.print_help
self.substitute_macros
curses.getmouse
item.cut_off_to
partcmd.subprocess.check_output.decode.replace
throbber
string.isdigit
self.move_by_word
fm.loop
self.process.kill
self.browser.resize
self.browser.destroy
command.strip
self.vcsthread.stop
os.path.isdir
tempfile.NamedTemporaryFile
Accumulator.move_to_obj
self.queue.remove
CursesShortcuts.color
undocumented.append
__file__.endswith
_unbind_traverse
setattr
tempfile.gettempdir
links.add
LOG.debug
self.read_text_file
self._advance.is_set
fm.relpath
self.get_list
struct.unpack
self.get_cmd_class
self.ImgDisplayUnsupportedException.super.__init__
curses.start_color
SourceFileLoader
threading.Event
lst.sort
right.add
self.process.stdout.readline
self.absolute
accept_file
self.fm.thisdir.move_to_obj
self.bookmarks.save
self._answer_question
self.cycle
self._advance.wait
logging.Formatter
File
group_hints
self.ui.redraw_main_column
preview_column.scrollbit
self.fm.ui.open_pager
self.get_name
string.encode
stdin.close
self._format_arg
self.path_re_dquoted.match
keys.encode.decode
curses.ungetmouse
SpecialFileError
self.fm.tab_open
macros.items
Tags
os.chdir
self.rotate
column.level_shift
len
scheme_module.__dict__.values
self.tabs.items
cmd.startswith
fsobj.vcs.__init__
self.fm.tags.sync
ViewBase.resize
os.path.lexists
self.types_of
remote.startswith
self.queue.pop
dirname
esc
MouseEvent
keys.append
self.tab_switch
self.down
self.handle_keys
keymap.items
popen2.stdin.close
some_dir.rstrip
self.console.resize
sys.exit
os.path.isfile
self.update
fobj.set_linemode
curses.init_pair
self._head_ref
cleandoc
event.ctrl
self.copy_buffer.symmetric_difference_update
self.old_item.pause
self.update_size
colorscheme.startswith
curses.mousemask
replace
ENCODING.mimetype.decode.strip
win.addstr
file_handle.read
text.split
self.cycle_list.rotate
Console
deq.rotate
self.vcsthread.pause
sort_unicode_wrapper_string
fcntl.ioctl
self.dct.clear
entry.find.text.split
self._find_root
traceback.format_exc
colorschemes.add
self._tab_match
_traverse
cwd.encode.decode
self.fm.loader.add
self.fm.display_help
self.fm.image_displayer.clear
signal.fm.confpath
next_tab.get_selection
date.strftime
self.obj.fm.notify
hasattr
command.__doc__.cleandoc.split
self.signal_garbage_collect
displayable.draw
Direction
cwd.startswith
self.data_status_root
fobj.read.sha512.digest
sys.path.append
pattern.re.escape.replace.replace
ansi.text_with_fg_bg_attr
next
re.escape
directory.use
entry.get
self.toggle_mark
util.module_from_spec
already_seen.append
listfile.read.split
self.ui.open_pager
self.get_mimetype
self.hint.split
parser.parse_args
stat.S_ISFIFO
self.fm.get_preview
self.fm.bookmarks.update_path
vars
self.queue.append
entry.update
text.encode
curses.flushinp
install_lib.run
self._advance.clear
os.geteuid
item.destroy
Direction._get_direction
rmtree
self.process.stdin.flush
self.win.refresh
self.thisdir.files.index
Direction._get_bool
self.browser.close_pager
self.hook_after_executing
argument.search
line.encode
copyfileobj
self.copy_buffer.update
current_linemode.filetitle
self.settings.signal_garbage_collect
self.set_image
dst.startswith
version_helper
relative_symlink
cmd.quick
imp.load_source
self.logfunc
output.endswith
self.fm.commands.get_command
bar.combine
self.wildcards.append
self.MacroDict.super.__init__
fobj.relative_path.split
self.queue.unpause
self.mark_files
fobj.get_permission_string
timer_kill.start
linemode_class
node.metaclass
keybuffer.clear
tabdir.get_selection
copy2
self.fm.commands.command_generator
unicode_buffer.encode
self.left.fixedsize
command.format
pwd.getpwuid
infostring_display.append
self.console.open
self._status_root
f.strip
Actions.__init__
iterable.type
self._process_command_stack
self.ui.titlebar.request_redraw
self.execute_curses_batch
print_all_colors
self.move_to_obj
self.fm.hide_bookmarks
direction.down
hashes.values
self.container.append
p
chunks.append
mtimelevel
os.unlink
cmd.init_line
bar.shrink_by_removing
s.strip
self.set_source
self.paused.set
self.rootvcs.status_subpaths.keys
default_value_completer.name.value_completers.get
key.self.go
self._draw_borders
self.vcs.rootvcs.status_subpath
self.clear
self.fm.ui.console.ask
kw.setdefault
self.lines.append
self.settings.draw_borders.lower
move
enumerate
self._get_cmd
dict.__init__
keys.encode
loader.work
_SETTINGS_RE.match
move_cur
self.quit
self.get_height
isdir
dirobj.fm.get_directory
programs.sort
target.use
direction.select
self.question_queue.append
self.fm.get_filesystem_objects
self.basename.translate
self._parent.set
self.fm.reset
cmd.get_name
stack_filter
self.get_macros
os.path.dirname
filters.extend
fobj.readlines
self.hook_logger
result.replace
self.fm.thisdir.filter_stack.pop.decompose
json.dump
self._validate
bar.right.sumsize
copy.deepcopy
lookup
self.thistab.at_level
self.redrawlock.clear
sum
fm.copy_config_files
datetime.now.date
self.add
thread.start_new_thread
safe_decode
self.thistab.ensure_correct_pointer
self.history.top
self._awoken.wait
line.rstrip
bool
os.path.islink
CalledProcessError
target.sort_if_outdated
bytearray
command.split.split
tfile.basename.replace
cwd.mark_all
filter_combinator
self._update_mtime
self.win.nodelay
src.find
self.hook_command_preprocessing
self.fm.mode.upper
fifo.read
waitfnc
cmd.cancel
self.fm.enter_bookmark
hidden_filter_search
self._get_mtime
popen2.stderr.close
Displayable.poke
predisplay_left.append
lmode.startswith
group.append
os.isatty
os.ttyname
self.fm.home_path.count
self.win.addstr
self.color_at
target.pointed_obj.load_if_outdated
self.fm.thisdir.filter_stack.extend
self.regex.search
curses.endwin
realpath
os.path.expanduser
os.path.getmtime
self.__getslice__
copystat
filter
bar.add
get_image_displayer
flag.lower
self.ui.close_taskview
curses.tigetstr.decode
setup
Popen_forked
Rifle
self._tab_through_executables
splitext
item.cut_off
super
self.tab_deque.appendleft
thisdir.mark_item
self._eval_condition2
range
key_value.decode
_fix_surrogates
shutil_g.copy2
script_content.encode
signal.fm.previews.clear
self.win.getyx
self.thisdir.move_to_obj
self.filetype.self.type_to_function
self.get
self.stopped.is_set
self.loader.pause
locale.setlocale
self.contains_point
self.rules.append
socket.gethostname
self.zombies.add
fm.signal_bind
fm.ui.initialize
threading.Timer
self._update_subroots
self.fm.settings.types_of
self._is_flags
self.win.mvderwin
ansi_re.split
self.target.is_image_preview
self.tags.items
root_logger.addHandler
signal.signal
self.setlocal_.super.__init__
console_widget.get_cmd_class
self.subfilter
self._get_right_part
utf_char_width
image.getbands
self.fm.dump_commands
argument.startswith
name.startswith
path.name.SourceFileLoader.load_module
self.group_paths_by_dirname
value.is_older_than
entry.splitlines
self.__stop.set
self.fm.thisfile.linemode_dict.keys
basenames.remove
self._get_left_part
DisplayableContainer.poke
self.fm.hide_console_info
OpenStruct
self.ui.get_pager.move
base64.b64encode
self.pager.draw_image
</pre>
</details>

    

Could please help me check this issue?
May I pull a request to fix it?
Thank you very much.

**Comment by toonn** [comment]
These are just tools for to use for ranger development not really dependencies and we do want to try to stay synchronized with the latest versions.

Closing as wontfix.
