### ISSUE TITLE
Question: how to quit ranger and go to the last directory I'm at in ranger?

### ISSUE THREAD

**Issue by dxxvi** [ranger/ranger#2679]
If the question is not clear enough: I run ranger from my home directory. In ranger, I go to directory `a`. If I quit with `q`, I'll be in my home directory. I'd like to quit ranger and go to the directory `a`.

**Comment by Rom1deTroyes** [comment]
From memory, the shell from which you have launched ranger don't know about the changed path when you quit ranger.
The way I do this is to use :

```sh
. ranger
```

This way, you will end in the last directory you visited with ranger :-)

**Comment by markus-bauer** [comment]
There's an entry in the wiki about this:
https://github.com/ranger/ranger/wiki/Integration-with-other-programs#make-your-shell-change-to-rangers-directory-on-quit

**Comment by tapyu** [comment]
You can also use my bash-compatible shell [function](https://github.com/tapyu/dotfiles/blob/main/zsh/.config/zsh/zsh-user-functions.sh#L2).
