### ISSUE TITLE
[Bug]: Configuration file: hjkl -> jkl;

### ISSUE THREAD

**Issue by t-h2o** [ranger/ranger#2683]
#### Runtime Environment

- Operating system and version: `Linux Mint 20.2 x86_64`
- Terminal emulator and version: `kitty 0.24.2`
- Python version: `Python 3.8.10`
- Ranger version/commit:
```
ranger version: ranger 1.9.3
Python version: 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
Locale: en_US.UTF-8
```

#### Current Behavior

ranger crashes

#### Expected Behavior

No error expected

#### Context

I was trying to remap `hjkl` with `jkl;` with:

1. From this forum: [ranger-how-to-remap-hjkl-keys](https://unix.stackexchange.com/questions/518771/ranger-how-to-remap-hjkl-keys)

```
copymap <UP>       k
copymap <DOWN>     j
copymap <LEFT>     h
copymap <RIGHT>    l
```

2. Try this from this issue: [Overwrite key mapping](https://github.com/ranger/ranger/issues/8)

```
map('j', fm.move(left=1))
map('k', fm.move(down=1))
map('l', fm.move(up=1))
map(';', fm.move(right=1))
```

3. From my vim dotfil

```
noremap ; l
noremap l k
noremap k j
noremap j h
```

#### Steps to reproduce
1. `cp /etc/ranger/config/rc.conf ~/.config/ranger/rc.conf` 
2. Add at the end of `~/.config/ranger/rc.conf` one of my tried
3. Launch `ranger`

#### Traceback

```error
ranger version: ranger 1.9.3
Python version: 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 98, in initialize
    self.rifle.reload_config()
  File "/usr/lib/python3/dist-packages/ranger/ext/rifle.py", line 170, in reload_config
    raise ValueError("Line without delimiter")
ValueError: Line without delimiter

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by toonn** [comment]
```
copymap l ;
copymap k l
copymap j k
copymap h j
```

Should just work, good luck!

**Comment by t-h2o** [comment]
> ```
> copymap l ;
> copymap k l
> copymap j k
> copymap h j
> ```
> 
> Should just work, good luck!

Thank you !
It works
