### ISSUE TITLE
image preview would not fill up the last columns in Konsole

### ISSUE THREAD

**Issue by zerobikappa** [ranger/ranger#2688]
#### Runtime Environment

- Operating system and version: 5.18.16-arch1-1
- Terminal emulator and version: konsole 22.04.3
- Python version: 3.10.5 (main, Aug  1 2022, 07:53:20) [GCC 12.1.0]
- Ranger version/commit: ranger-master v1.9.3-524-gfcf44f6f
- Locale: en_US.UTF-8

#### Current Behavior
image preview would not fill up the last columns in Konsole.
terminal Konsole, using ueberzug:
![Screenshot_20220808_063437](https://user-images.githubusercontent.com/26425881/183313612-aabd3005-0db7-4442-acf4-5e5720fd2e20.png)

terminal Konsole, using w3m(image also misaligned with column):
![Screenshot_20220808_064025](https://user-images.githubusercontent.com/26425881/183313974-9604d8a6-66fa-4d40-96d0-e078e64e095c.png)

I also tested with Xterm and Alacritty, they both worked well. It seems only occurs in Konsole.
terminal Alacritty, using ueberzug:
![Screenshot_20220808_064718](https://user-images.githubusercontent.com/26425881/183313935-b0420b06-85a8-4e11-980d-5cd5cf97a0fc.png)

**Comment by toonn** [comment]
Can you check whether the placing and size correspond to a Konsole at 80x24?

**Comment by zerobikappa** [comment]
> Can you check whether the placing and size correspond to a Konsole at 80x24?

Preview kept the same placing/size when I changed window/font size.

![1](https://user-images.githubusercontent.com/26425881/203123964-bc0988b7-dd9e-488f-a858-3b6c5b6500b9.png)

**Comment by toonn** [comment]
I suspect this is because Konsole reports the window size differently or something.
Ueberzug has been discontinued though so I'm not sure looking into this further is the correct solution.
Does Konsole support SIXEL, because support for that is coming to Ranger?
