### ISSUE TITLE
Preview image not showing

### ISSUE THREAD

**Issue by tapyu** [ranger/ranger#2692]
#### Runtime Environment
```
ranger version: ranger-master
Python version: 3.10.5 (main, Aug  1 2022, 07:53:20) [GCC 12.1.0]
Locale: en_US.UTF-8
```

- Operating system and version: 
```
 tapyu@tapyu-20qrcto1ww
 OS: Manjaro 21.3.6 Ruah
 Kernel: x86_64 Linux 5.15.60-1-MANJARO
 Uptime: 8h 17m
 Packages: 1495
 Shell: zsh 5.9
 Resolution: 3840x2160
 DE: GNOME 42.3
 WM: Mutter
 WM Theme:
 GTK Theme: Adw-dark [GTK2/3]
 Icon Theme: Papirus-Dark
 Font: Noto Sans 11
 Disk: 50G / 480G (11%)
 CPU: Intel Core i7-9750H @ 12x 4.5GHz [42.0°C]
 GPU: Quadro P620
 RAM: 4080MiB / 23678MiB
```
- Terminal emulator and version: 
`alacritty 0.10.1 ()`
- Python version:
`Python 3.10.5` 
- Ranger version/commit: 
`ranger version: ranger-master`
- Locale: 
`ranger version: ranger-master`

#### Current Behavior

`ranger` does not display `pdf` or images (.png, .jpeg, etc...) when preview_images is set to on.

#### Expected Behavior
It should display an image on the right column.

#### Context
I tried to debug `ranger`, the log config (at DEBUG level) prompt the following info:
```
main.py:ranger version: ranger-master 
main.py:Python version: 3.10.5 (main, Aug  1 2022, 07:53:20) [GCC 12.1.0]
main.py:Locale: en_US.UTF-8
main.py:Process ID: 42571
main.py:cache dir: '/home/tapyu/.cache/ranger'
main.py:config dir: '/home/tapyu/.config/ranger'
main.py:data dir: '/home/tapyu/.local/share/ranger'
main.py:Loaded custom commands from '/home/tapyu/.config/ranger/commands.py'
main.py:Loaded plugin 'ranger-zoxide'
main.py:Loaded plugin 'ranger_devicons'
actions.py:Sourcing config file '/usr/lib/python3.10/site-packages/ranger/config/rc.conf'
actions.py:Sourcing config file '/home/tapyu/.config/ranger/rc.conf'
```

I double-checked the cache directory and the images were created properly, although `ranger` does not display them.

PS: I am using two plugins, zoxide and devicons

#### Possible Solutions

I am not sure what is the solution to it, but `ranger` always annoys me regarding displaying images preview. It was working when I was on Ubuntu. When I moved to Majaro, I couldn't make it work again. I highly suggest setting `image_preview` to `true` as default, and making sure it will work out of the box.

#### Steps to reproduce
1. clear you config directory.
2. run `ranger --copy-config=all`
3. Go to `scope.sh` and uncomment the this section
```shell
## PDF
         application/pdf)
             pdftoppm -f 1 -l 1 \
                      -scale-to-x "${DEFAULT_SIZE%x*}" \
                      -scale-to-y -1 \
                      -singlefile \
                      -jpeg -tiffcompression jpeg \
                      -- "${FILE_PATH}" "${IMAGE_CACHE_PATH%.*}" \
                 && exit 6 || exit 1;;
```
4. open ranger and toggle the preview image default (shortcut to `zi`)
5. go to an image or a PDF.
6. it will not display anything

**Comment by markus-bauer** [comment]
What preview_images_method do you use?
I think the default config is set to w3m.

Have you tried other methods?

**Comment by tapyu** [comment]
@markus-bauer I was using `3wm`, but none of the other methods worked.

**Comment by markus-bauer** [comment]
I normally don't use alacritty.
But I quickly tested it with alacritty, and w3m and ueberzug work for me.

Is w3m installed under any of these paths?
https://github.com/ranger/ranger/blob/fcf44f6f12506fa0096cb6468de6a2706bbfaf51/ranger/ext/img_display.py#L39-L45

Are you using wayland? I don't think w3m works under wayland (not sure though).

**Comment by kohane27** [comment]
@markus-bauer 

I can confirm that no image previewer will work under tmux + wayland. I've exhausted all the solutions. It's a bit of a shame though.

If OP is on Wayland I suggest using Kitty, as I can confirm image previewer with Kitty (no tmux) works.

**Comment by tapyu** [comment]
I beg you pardon for my ignorance, I have not knowledge about display server protocols :( I suppose I am using X server protocol.



> I've exhausted all the solutions

But what is the problem exactly?

**Comment by kohane27** [comment]
@tapyu 

What is the output of `echo $XDG_SESSION_TYPE`? For me:

```
❯ echo $XDG_SESSION_TYPE
wayland
```

You're likely see `x11`.

If you're on x11 and Alacritty, you can definitely make it work.

I remember I used `ueberzug` in Alacritty to make image preview in Ranger work:

[Image Previews · ranger/ranger Wiki](https://github.com/ranger/ranger/wiki/Image-Previews#with-ueberzug)

**Comment by tapyu** [comment]
Indeed,
```
❯ echo $XDG_SESSION_TYPE
x11
```

**Comment by tapyu** [comment]
> I remember I used `ueberzug` in Alacritty to make image preview in Ranger work

I doesn't work...

**Comment by tapyu** [comment]
> But what is the problem exactly? Do you know?

???

**Comment by kohane27** [comment]
Please specify "doesn't work" how. What's the log output?

Did you install `ueberzug`?

Did you ddd the following lines to your `~/.config/ranger/rc.conf`:

```
set preview_images true
set preview_images_method ueberzug
```

As mentioned by @markus-bauer,

> But I quickly tested it with alacritty, and w3m and ueberzug work for me.

The issue is solvable, unlikely me with Wayland and tmux.

**Comment by tapyu** [comment]
I sear I had installed `ueberzug` before. I just reinstalled it and it worked!

Why is `ueberzug` not a required package for `ranger`? I think the preview image feature should be enabled by default and all all packages needed to make it work should be installed as required package for `ranger`. It would make the user experience easier...

**Comment by Rom1deTroyes** [comment]
> Why is `ueberzug` not a required package for `ranger`?

ueberzug is not the only choice for having an image preview, and it is not universal...

> I think the preview image feature should be enabled by default
> and all all packages needed to make it work should be installed as required package for `ranger`.

The dependencies for ranger are kept minimal to have the basics functionalities easy to install with a large amount of configuration : this gives a very large panel of choice (hardware, OS, Display Server, Desktop / Window Manager, Terminal Emulator, Multiplexer, Shell, themes, ... and all the ecosystem : finders, Documents previews, etc.) for the user, and as preferences may vary, deciding what is *default* is prone to flamewars :fire: 

I use ranger in a lot of remote devices (server and IoT), where image and video previews are not so useful, and where img2txt is sufficient for my usecase : having to install ueberzung and all his dependencies is not an option.

> It would make the user experience easier...

Sure, but not for all users :-)
The documentation, and the community are great to help people to discover what is the best solution for each everyone !

**Comment by pnchinmay** [comment]
ueberzug seems to be out of pypi.org
Not able to get it using pip
Any other tools which gives same result as ueberzug ?

**Comment by tapyu** [comment]
@pnchinmay Apparentely, [ueberzug](https://github.com/seebye/ueberzug) was close due to a harassment. That is pretty sad because that was the best solution for GNU/Linux environment with XDG session type `X11`. I recommend you to find `ueberzug` whether someone out there restart the project. You probably will not find a good image preview better than `ueberzug` (if you find, please, let me know).

**Comment by pnchinmay** [comment]
> @pnchinmay Apparentely, [ueberzug](https://github.com/seebye/ueberzug) was close due to a harassment. That is pretty sad because that was the best solution for GNU/Linux environment with XDG session type `X11`. I recommend you to find whether `ueberzug` was restarted by someone out there. You will probably not find a image preview better than `ueberzug` (if you find, please, let me know).

Yeah I saw his repo. It's really unfortunate.   
I had earlier used w3m but wasn't sure if it works as good as ueberzug. Tried it today again. Image previews are similar to ueberzug. Other previews anyways worked with rest of the packages mentioned in wiki

**Comment by dfokin** [comment]
> 

There is a drop-in replacement for ueberzug: https://github.com/jstkdng/ueberzugpp

**Comment by pnchinmay** [comment]
> There is a drop-in replacement for ueberzug: https://github.com/jstkdng/ueberzugpp

Awesome
Will surely try this one

**Comment by Natzgun** [comment]
Use ueberzug++ this found in X11 and Wayland, tested in Alacritty and Kitty in Hyprland
