### ISSUE TITLE
Ranger interprets a directory ending in question mark as URL

### ISSUE THREAD

**Issue by ignamartinoli** [ranger/ranger#2697]
#### Runtime Environment

- Operating system and version: Gentoo Linux
- Terminal emulator and version: kitty 0.26.2
- Python version: 3.10.6
- Ranger version/commit: 1.9.3 
- Locale: en_US.UTF-8

#### Current Behavior

Opening a directory from Firefox which name ends with a question mark results in

```
Open URL Error

Unknown URL type, cannot open:
  /home/sicro/dou?

Press Enter or Esc to exit
```

#### Expected Behavior

The directory to be opened

#### Context

Opening a directory ending with a question mark from Firefox is impossible

#### Possible Solutions

Some URL checks maybe?

#### Steps to reproduce

1. Open Firefox
2. Download something inside a directory with a name ending in a question mark (i.e. `directory?`)
3. Click on the _Download_ icon at the top bar of Firefox
4. Click on the _Show in folder_ icon

**Comment by toonn** [comment]
Hmm, I can't reproduce this with a local directory. Ranger has no problem opening a directory with a question mark in the name.

I think this issue might be on Firefox's side or whatever Firefox is trying to use to open the path? What does the desktop file for Ranger look like? Can you trigger the issue by trying to launch the desktop file with such a path as argument?

**Comment by ignamartinoli** [comment]
Very possible. I also found only one other issue like mine [here](https://socialgrep.com/post/u0fa0e). Thanks for your time.
