### ISSUE TITLE
Can't open Rust files

### ISSUE THREAD

**Issue by Shiztev** [ranger/ranger#2698]
#### Runtime Environment

- Operating system and version: Pop!_OS 22.04
- Terminal emulator and version: st 0.8.5
- Python version: 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
Does not open *.rs files. Can open files of any other types (e.g. no problems with foo.c, foo.sh, foo.pdf, etc.). Prints an xdg-open error, which I've pasted in the traceback section. Ranger **does not** crash, and I can still open other files after the error.

#### Expected Behavior
Opens the Rust file in nvim/whatever editor I choose.

#### Context

Trying to edit Rust files in nvim. Can open them via nvim, but use a ranger extension in nivm to navigate and open multiple files in a project.

#### Possible Solutions
Looked into other issues with xdg-open, and saw that I could update my rifle.conf to remove the '--' in the xdg-open call, but this just opens the file in a new instance of the system's default editor, without prompting me to select an editor.

#### Steps to reproduce
1. open whatever terminal (I've tried and found the error on both st and gnome)
and run ranger
2. find a *.rs file and hit enter/l
3. xdg-open error

#### Traceback

```
xdg-open: unexpected option '--'
Try 'xdg-open --help' for more information.
```

**Comment by Shiztev** [comment]
Didn't see #1804 when I was digging for similar issues, but looking through there, seemed to be a mime issue. Creating a `~/.mime.types file` and appending a line with `text/x-rust rs` fixed my issue.

**Comment by JohanChane** [comment]
add `rs` to the lines in rifle.conf

```

!mime ^text, label editor, ext xml|json|csv|tex|py|pl|rb|js|sh|php|rs = ${VISUAL:-$EDITOR} -- "$@"
!mime ^text, label pager,  ext xml|json|csv|tex|py|pl|rb|js|sh|php|rs = "$PAGER" -- "$@"
```
