### ISSUE TITLE
kitty image preview temporary files not automatically removed after viewing on kitty 0.26.0+

### ISSUE THREAD

**Issue by socksthefennec** [ranger/ranger#2699]
#### Runtime Environment

- Operating system and version: Arch Linux
- Terminal emulator and version: kitty 0.26.2
- Python version: 3.9.12 (05fbe3aa5b0845e6c37239768aa455451aa5faba, Aug 10 2022, 21:31:33) [PyPy 7.3.9 with GCC 12.1.1 20220730]
- Ranger version/commit: 1.9.3
- Locale: en_AU.UTF-8

#### Current Behavior
Temporary files generated for image previews in kitty are never deleted.

#### Expected Behavior
Temporary files generated for image previews in kitty should be automatically deleted after being read by the terminal.

#### Context

After browsing some amount of images in ranger my `/tmp` folder fills up, most notably causing image previews to stop working. This can temporarily be resolved by deleting the generated files.
kitty 0.26.0 ([changelog](https://sw.kovidgoyal.net/kitty/changelog)) introduces a new restriction on deletion of temporary files, which is the cause of the issue:
> - Graphics protocol: Only delete temp files if they have the string `tty-graphics-protocol` in their file paths. This prevents deletion of arbitrary files in `/tmp`.

#### Possible Solutions
The source of the issue is this line:
https://github.com/ranger/ranger/blob/fcf44f6f12506fa0096cb6468de6a2706bbfaf51/ranger/ext/img_display.py#L669
I suggest changing `prefix='ranger_thumb_'` to `prefix='tty-graphics-protocol-'` or similar.

#### Steps to reproduce
1. Open ranger in kitty 0.26.0 or newer
2. set `preview_files=true`, `preview_images=true` and `preview_images_method=kitty`
3. Browse through images (/anything that has an image preview?)
4. Run out of space in `/tmp`

**Comment by toonn** [comment]
I've created #2750 to address this. Could you test it to see whether the subdirectory works? I prefer it to including the string in the file name because it avoids cluttering up `/tmp` as much.

Thank you for the report!

**Comment by socksthefennec** [comment]
Tested, works on first run (creates `tty-graphics-protocol` folder in `/tmp`, images are cleaned up by kitty) but breaks image previews if the folder exists before starting ranger (shows an error in the status bar every time an image preview should be shown: `name 'tempFileDir' is not defined`, and no previews are shown)

The log in that case is as follows:
```
23:04:03 INFO ranger version: ranger-master v1.9.0b5-1530-gca2d9229
23:04:03 INFO Python version: 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]
23:04:03 INFO Locale: en_AU.UTF-8
23:04:03 INFO Process ID: 20790
23:04:42 ERRO Notification: name 'tempFileDir' is not defined
23:04:42 ERRO name 'tempFileDir' is not defined
Traceback (most recent call last):
  File "/home/socks/git/ranger/ranger/ext/img_display.py", line 599, in _late_init
    os.mkdir(self.tempFileDir)
FileExistsError: [Errno 17] File exists: '/tmp/tty-graphics-protocol'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/socks/git/ranger/ranger/gui/widgets/pager.py", line 118, in draw_image
    self.fm.image_displayer.draw(self.image, self.x, self.y,
  File "/home/socks/git/ranger/ranger/ext/img_display.py", line 641, in draw
    self._late_init()
  File "/home/socks/git/ranger/ranger/ext/img_display.py", line 603, in _late_init
    d=tempFileDir
NameError: name 'tempFileDir' is not defined
```
Changing line 603 in `ranger/ext/img_display.py` from `d=tempFileDir` to `d=self.tempFileDir` shows what I assume is the correct error in the status bar: `Could not create temporary directory for previews : /tmp/tty-graphics-protocol`, and falls back to a text preview afterwards.

In that case, the log reads:
```
23:27:42 INFO ranger version: ranger-master v1.9.0b5-1530-gca2d9229
23:27:42 INFO Python version: 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]
23:27:42 INFO Locale: en_AU.UTF-8
23:27:42 INFO Process ID: 24005
23:27:46 ERRO Notification: Could not create temporary directory for previews : /tmp/tty-graphics-protocol
23:27:46 ERRO Could not create temporary directory for previews : /tmp/tty-graphics-protocol
Traceback (most recent call last):
  File "/home/socks/git/ranger/ranger/ext/img_display.py", line 599, in _late_init
    os.mkdir(self.tempFileDir)
FileExistsError: [Errno 17] File exists: '/tmp/tty-graphics-protocol'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/socks/git/ranger/ranger/gui/widgets/pager.py", line 118, in draw_image
    self.fm.image_displayer.draw(self.image, self.x, self.y,
  File "/home/socks/git/ranger/ranger/ext/img_display.py", line 641, in draw
    self._late_init()
  File "/home/socks/git/ranger/ranger/ext/img_display.py", line 601, in _late_init
    raise ImgDisplayUnsupportedException(
ranger.ext.img_display.ImgDisplayUnsupportedException: Could not create temporary directory for previews : /tmp/tty-graphics-protocol
```
The underlying issue appears to be that you always attempt to create the directory, and don't handle the case where it already exists. Adding
```python
except FileExistsError:
    pass
```
between the `os.mkdir(self.tempFileDir)` and `except OSError:` resolves the issue, but I'm not certain of the greater implications and whether it's a good idea.
I'm also not sure the directory is necessary as the files are cleaned up by kitty almost immediately after being previewed, but that's your call.
