### ISSUE TITLE
Hotkey F11: Run script - open output text file - return to Ranger

### ISSUE THREAD

**Issue by philiprhoades** [ranger/ranger#2704]
People,

I have edited rc.conf for F1 as various permuations of "kitty" but I keep getting:

"Command not found"

What I would like to be able to do is to use F11 to run a script and to then open the resulting output text file (vim in my case) for editing - and then after quitting the editing, returning to the same place in Ranger.

Is this possible?  How do I do it?

Thanks again people!

Phil.

**Comment by nst0022** [comment]
I guess you want to run kitty, which in turn runs, say, otto, when pressing F11 in ranger

Then add this line to rc.conf:

`map <f11> console shell kitty otto`

When pressing f11 in ranger, it shows below:

`:shell kitty otto`

which not only serves as a confirmation prompt, but also allows you to make modifications

Press enter when done or cancel this command

**Comment by toonn** [comment]
Closing as resolved since there was no further activity.

The r/ranger SubReddit is a better place for user questions like these. There's a small community of Ranger users forming there so you're more likely to get faster answers.
