### ISSUE TITLE
Default settings (multipane with 2 tabs)

### ISSUE THREAD

**Issue by og900aero** [ranger/ranger#2705]
There is an option to make it a basic setting with multipane with 2 tabs?

I have set viewmode multipane, that's right, but where can you set the ranger to open with 2 tabs by default?

**Comment by nst0022** [comment]
You need to specify, which folders should appear in the tabs, then pass them when calling ranger:

`ranger <path1> <path2>`

Both paths can be the same:

`ranger <path1> <path1>`

and it is not resticted to two paths:

`ranger <path1> <path2> <path3> <path4>...`

**Comment by og900aero** [comment]
Thank you for your answer, but this is not what I want. It is not the same, when run ranger and press ctrl + n for multipane (like vifm). So there is an option for open ranger with ctrl + n like multipane?

**Comment by maln0ir** [comment]
You can `set viewmode multipane` in your `rc.conf` so it opens like `vifm` by default.

Alternatively, if you don't want to change this setting, you can press tilde.  It switches between tabs and multipane layout.

**Comment by og900aero** [comment]
> ranger --cmd='set viewmode=multipane'

Thx, working great. Now I run ranger the following command: ranger /home/Data --cmd='eval fm.tab_new()' --cmd='eval fm.tab_move(-1)'

And map viewmode_multipane to the mm keys.

Thx a lot!

**Comment by og900aero** [comment]
> You can `set viewmode multipane` in your `rc.conf` so it opens like `vifm` by default.
> 
> Alternatively, if you don't want to change this setting, you can press tilde. It switches between tabs and multipane layout.
> 
> Yet another option is to alias this command: `ranger --cmd='set viewmode=multipane'`

Thx, working great. Now I run ranger the following command: ranger /home/Data --cmd='eval fm.tab_new()' --cmd='eval fm.tab_move(-1)'

And map viewmode_multipane to the mm keys.

Thx a lot!
