### ISSUE TITLE
Ranger Crashes when a file is passed in as an arg; should instead highlight.

### ISSUE THREAD

**Issue by Jazztache** [ranger/ranger#2709]
1. Was this issue already reported?  Please do a quick search.
    Couldn't find a duplicate issue. Seems as if this is unique. Very surprising since this seems like it should be reported already?
2. Provide all the relevant information, as outlined in this template.
    I'm using fish shell, pretty sure this crashes with bash as well. Seeing as you can pass in a folder location, this should nav to that folder and select the corresponding file instead of putting the highlight (cursor) at the top. After the last slash. In this case, Ranger should open in `/home/jazztache/Desktop` then highlight `YT Links.txt`. 
 ```jazztache@jazztache-neon ~> ranger ~/Desktop/YT\ Links.txt 
ranger version: ranger 1.9.3
Python version: 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
Locale: en_AU.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 334, in redraw
    self.finalize()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 391, in finalize
    DisplayableContainer.finalize(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 268, in finalize
    displayable.finalize()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/view_base.py", line 59, in finalize
    col_y = self.main_column.y + self.main_column.target.pointer \
AttributeError: 'NoneType' object has no attribute 'pointer'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
jazztache@jazztache-neon ~ [1]>
```
About OS:
```
NAME="KDE neon"
VERSION="5.25"
ID=neon
ID_LIKE="ubuntu debian"
PRETTY_NAME="KDE neon User - 5.25"
VARIANT="User Edition"
VARIANT_ID=user
VERSION_ID="20.04"
HOME_URL="https://neon.kde.org/"
SUPPORT_URL="https://neon.kde.org/"
BUG_REPORT_URL="https://bugs.kde.org/"
LOGO=start-here-kde-neon
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

#### Runtime Environment

- Operating system and version: 
- Terminal emulator and version: 
- Python version: 3.8.10
- Ranger version/commit: ranger 1.9.3
- Locale: en_AU.UTF-8

#### Current Behavior
Crashes.
#### Expected Behavior
Open to folder before the last slash, then select what is after the last slash. i.e. Start ranger such that the highlighted file is the one specified by the path
#### Context
Passing an argument into a default no-nonsense, no flags ranger session.
#### Possible Solutions
Take in `$1` equiv in Python (using Bash as example.). Split the input at the last `/` and navigate to the folder, like you're passing in a folder normally. In this case, the `/home/jazztache/Desktop` part.
Then use the code for `:search` to snap to the correct one. In this case the `YT Links.txt` part.
#### Steps to reproduce
1. Pass in the path to file rather than the path to a folder.
2. Crash
3. :(

#### Traceback
```Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 334, in redraw
    self.finalize()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 391, in finalize
    DisplayableContainer.finalize(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 268, in finalize
    displayable.finalize()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/view_base.py", line 59, in finalize
    col_y = self.main_column.y + self.main_column.target.pointer \
AttributeError: 'NoneType' object has no attribute 'pointer'
```

Note: `--debug` also outputs the same output.
Note: Thankyou Ranger team for making an awesome (and very fast) TUI File Manager. Great for when Dolphin slows down :D

**Comment by TechWiz-3** [comment]
I'm not sure ranger is being maintained much anymore 🤔

**Comment by toonn** [comment]
This is already fixed on the master branch.

You can install Ranger from any branch by running `make install` from the repository. As a workaround until we can release the next version.

Ranger is still being maintained, albeit slowly. Though in this case the issue was really already fixed before it was reported. Always make sure to search through closed issues too.

**Comment by TechWiz-3** [comment]
Cool thanks for the followup, what PR was this fixed in? Just curious

**Comment by toonn** [comment]
I don't remember which one, I was probably the author though.
