### ISSUE TITLE
Label 'editor' is undefined, when use `:edit <filename>`

### ISSUE THREAD

**Issue by Innei** [ranger/ranger#2711]
#### Runtime Environment

- Operating system and version:  macOS 12.5
- Terminal emulator and version: iTerm2
- Python version: 3.9
- Ranger version/commit: 1.9.3
- Locale: enUS

#### Current Behavior

call `:edit 222`, got label editor undefined

<img width="842" alt="image" src="https://user-images.githubusercontent.com/41265413/194314095-74ed78f1-c820-48a4-80ed-64d689f6827b.png">

#### Expected Behavior

edit file.

#### Steps to reproduce
1. `:edit <filename>`
2. 
3. 

#### Traceback

```

```

My config is here: https://github.com/Innei/dotfiles/blob/master/tag-ranger/config/ranger/rc.conf

Thanks.

**Comment by toonn** [comment]
You need at least one rule in `rifle.conf` that has `label editor` in the constraints on the left-hand side. This rule should start an editor that does *not* fork because Ranger needs to know when the process is done editing the file and the only reference it has is when the process finishes.
