### ISSUE TITLE
Wrong characters in non-ascii filenames

### ISSUE THREAD

**Issue by pct** [ranger/ranger#272]
Hi, hut,

I'm a FreeBSD port maintainer of sysutils/py-ranger, some user and me find there is a non-ascii filename issue.

I just touch a file named '測試中文' (means test Chinese character), but at ranger it shows 'M-fM-8M-,M-hM-)M-&M-dM-8M--M-f~V~G0'.

My python version is 2.7.9 and ranger version is 1.6.1. And I have also clone the github master version, it has the same issue.

Please help, thanks.

**Comment by randynobx** [comment]
I partially recreated this issue.

When touching a file with the given name, Ranger displayed: 測試中æ~V~G

FreeBSD 10.0
Ranger 1.6.1
Python 2.7.6

**Installed Ranger directly from ports, let it install python itself.

**Comment by hut** [comment]
Works here (archlinux, python2.7, ranger-git), but I had this issue on gentoo once, because I compiled python without the "wide-unicode" useflag.

I can reproduce the behavior randynobx described by setting `LANG=C` rather than `LANG=en_US.UTF-8`.

So it could be a problem with the configuration of your python version or with your locale settings.

**Comment by pct** [comment]
I could say using Mac OS 10.9.5 with python 2.7.9 has no such issue, but it did happen on FreeBSD.

Not just the locale but maybe also 'wide-unicode'

**Comment by pct** [comment]
I've rebuild python using ports and use "UCS4      Enable UCS4 Unicode Strings" option, but still has this issue. (Both ports version and ranger master version)

Using en_US.UTF-8 got 'M-fM-8M-,M-hM-)M-&M-dM-8M--M-f~V~G' and using locale C got '測試中V~G'.

So I would try other way to figure out why this happened.

Thanks.

**Comment by petr-fischer** [comment]
Hello - also have this issue on FreeBSD 11-CURRENT. Python 2.7 compiled with UCS4 strings (default). 

In the filename, there is "M-EM->" insetad of single character "ž".

It"s broken even with en_US.UTF-8.

**Comment by hut** [comment]
Does it also happen with this barebone program? It displays all the filenames in your home directory starting with `foo`. So try creating a file named `~/foož` and run this program to see if it's displayed correctly.
```python
#!/usr/bin/python
import curses, os.path, sys
@curses.wrapper
def main(win):
    files = os.listdir(os.path.expanduser("~/"))
    try:
        # Draw all file names matching ~/foo* in the terminal
        win.addstr(", ".join(f for f in files if f.startswith("foo")))
    except:
        pass  # at this point, there's probably no space left in the window
    win.getch()  # wait for key press before exiting
```

If not, this is not a problem with ranger and you should take it to your python or libncursesw maintainer

**Comment by petr-fischer** [comment]
@hut Your test program works correctly (shows "foožžž"). Ranger shows "fooM-EM->M-EM->M-EM->"

**Comment by hut** [comment]
Okay. Just to be sure, you do run it with the same python version, right? Often there are multiple python versions installed on a system. You can check rangers python version by pressing W in ranger.

**Comment by petr-fischer** [comment]
@hut Yes - I used the first line from ..bin/ranger script:
```
#!/usr/local/bin/python2.7 -O
```

**Comment by hut** [comment]
what if you add this at the top of the script?
```python
import locale
locale.setlocale(local.LC_ALL, '')
```

**Comment by petr-fischer** [comment]
@hut Bingo! This is a problem. Even this line is a problem:
```
locale.setlocale(locale.LC_ALL, "cs_CZ.UTF-8") // or en_US.UTF-8 - also problem
```

**Comment by hut** [comment]
maybe your locales are not properly configured? don't know how to do it in bsd, but on linux you set them up like this: https://wiki.archlinux.org/index.php/Locale

**Comment by petr-fischer** [comment]
My locales:
```
18:00:45 pf@pf-bsd ~ $ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_TIME=cs_CZ.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=
```
All other console apps (mutt, newsbeuter, mc, vim...) works ok with accent chars on FreeBSD with UTF-8 locales above (like on my previous Arch linux installation). Only problem is with ranger. On Arch linux, ranger is running with default python 3.5.1 - isn't python 2.7 too old? Why your small test program works ok?

**Comment by Chr1stoph** [comment]
@hut, @pct
at least Umlaute work for me on FreeBSD with the following addition to ranger.py
`--- ranger.py.orig	2016-04-25 19:28:32 UTC
+++ ranger.py
@@ -24,6 +24,11 @@ return $returnvalue
 
 import sys
 from os.path import exists, abspath
+# This is to change the envrionment. Showing Umlaute and so on
+# worked with LANG=C. I have not found a method to make it work
+# in an utf-8 environemt.
+from os import putenv
+putenv('LANG', 'C')
 
 # Need to find out whether or not the flag --clean was used ASAP,
 # because --clean is supposed to disable bytecode compilation`
Is this reasonable for not Umlaute-only and for non-FreeBSD systems?

**Comment by petr-fischer** [comment]
Chr1stopch: it's a little better only - it shows "ž" char OK, but "č" is still crippled :(

**Comment by Chr1stoph** [comment]
Dear Petr,
thank you for the feedback. Now I have an additional filename as test case.
Kind regards,
Christoph

**Comment by petr-fischer** [comment]
full list is here :)
áčďéěíňóřšťúůýž
ÁČĎÉĚÍŇÓŘŠŤÚŮÝŽ

**Comment by Chr1stoph** [comment]
The test script of @hut above also shows "ž" char OK and "č" crippled. May be there is more than one issue which triggers the effect.

**Comment by petr-fischer** [comment]
Retested hut's script and you are right - half of all chars are crippled. My mistake :(

**Comment by citrin** [comment]
May be bug not in ranger, but in curses python module.
test_curses.py from lib/python2.7/test also does not work with utf-8.

**Comment by z11k** [comment]
Strange is that misc/vifm which also use ncurses works fine.

**Comment by petr-fischer** [comment]
@z11k yes but vifm is Core C, not python, maybe there is something bad with python+ncurses binding like @citrin suggested.

**Comment by nfnty** [comment]
Nothing we can do about this issue then. You'll have to fix it in your distro.
