### ISSUE TITLE
Ranger unable to preview a text file

### ISSUE THREAD

**Issue by fromtheeast710** [ranger/ranger#2725]
For some reason Ranger can't preview this text file taken from here [evil_lualine](https://github.com/nvim-lualine/lualine.nvim/blob/master/examples/evil_lualine.lua)
![2022-10-27-140905_1366x768_scrot](https://user-images.githubusercontent.com/79054870/198215464-e89f327a-0def-45d2-8cf6-b468bf852e2a.png)

compare to this file
![2022-10-27-140914_1366x768_scrot](https://user-images.githubusercontent.com/79054870/198215526-352bc018-3006-4260-a3c0-097919ebcde4.png)

**Comment by fromtheeast710** [comment]
@tuatara73 I'm using Ranger ranger 1.9.3 with Python version: 3.10.8 on ArtixLinux 6.0.6.artix1-1.

**Comment by fromtheeast710** [comment]
It's weird that only one file is affected by this. I tried removing the config file but nothing changed.

**Comment by sbradnick** [comment]
There are control (^) codes in the file, w/ them stripped out it previews fine; lines 100 and 106.

**Comment by fromtheeast710** [comment]
That worked, thank you. But is there any workaround for this bug?

**Comment by toonn** [comment]
This is probably caused by whatever syntax highlighting program is processing it. Which of `highlight`, `bat` or `pygments` do you have installed? (Or did, since it's a while ago .)
