### ISSUE TITLE
Ranger Interaction with os Memory

### ISSUE THREAD

**Issue by LokeshBadisa** [ranger/ranger#2729]
- Operating system and version: Ubuntu 22.04
- Python version: Python 3.10.6
- Ranger version/commit: ranger 1.9.3
- Locale: en_IN.ISO8859-1

#### Current Behavior
When I open my ranger within Ubuntu, it does not access other OS's(other refers to Windows) memory at first go. But when I open Windows's memory through Nautilus and open ranger then it shows Windows's memory. Please fix this

**Comment by toonn** [comment]
I'm not sure what you mean. Can you clarify? It sounds like you have a dual booting setup? I suspect Nautilus is automatically mounting an NTFS partition or something?

Apologies for taking so long in getting around to this. It doesn't sound like a bug though so I'm going to close this issue, we can reopen if it is clarified.

**Comment by LokeshBadisa** [comment]
Yes, nautilus is mounting ntfs partition after clicking on "Other locations"(Windows-SSD as it shows in my pc). It is only after that ranger is able to detect Windows-SSD.
