### ISSUE TITLE
[Feature Request] Loop file searching

### ISSUE THREAD

**Issue by DUOLabs333** [ranger/ranger#2731]
#### Runtime Environment

- Operating system and version: 
- Terminal emulator and version: 
- Python version: 
- Ranger version/commit: 
- Locale: 

#### Current Behavior
If I reach the end of a directory listing, or go to the beginning, it doesn't loop over. 
#### Expected Behavior
The directory listing should loop
#### Context

I don't have the home or end key, so I can't jump to the end, so I want to be able to loop to get to the end or beginning of a listing.
#### Possible Solutions
If end of the listing is reached, go back up.

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```

```

**Comment by DUOLabs333** [comment]
Oh wow. I didn't know I could do that. Thanks.

**Comment by toonn** [comment]
I think that happens because the default config binds `map <C-h> set show_hidden!` (same binding as for `zh`), and your Delete key sends `C-h` in your terminal.

**Comment by DUOLabs333** [comment]
Apparently, my Delete (Backspace) key is sending Ctrl+Shift+?

**Comment by toonn** [comment]
Both ^? and ^H are common control sequences sent by the backspace key. That's why the default config copies the map for "backspace" to `<C-h>`.

**Comment by DUOLabs333** [comment]
Ah, is there a "noop" option in ranger I can bind ^? to

**Comment by toonn** [comment]
You'd have to remove all the bindings for `<backspace>`, `<backspace2>`, `<C-h>` and `<C-?>` from `rc.conf`.
