### ISSUE TITLE
Custom key bind with multiple commands

### ISSUE THREAD

**Issue by og900aero** [ranger/ranger#2735]
I use multipane mode ( and run ranger --cmd='eval fm.tab_new()' ), and want to config F5 key to copy selected file from first pane to second pane (like mc).
I try this, but nothing happens: 
map <TAB> tab_move 1
map <F5> copy <TAB> paste

What is the solution?

**Comment by maln0ir** [comment]
Try `:chain` command, like this: `:chain copy; tab_move 1; paste`

**Comment by og900aero** [comment]
> Try mapping `:chain` command, like this: `:chain copy; tab_move 1; paste`

Thx, work like a charm! I added a little, so it's completely like the 2-tab file managers:
map <F5> chain copy; tab_move 1; paste; tab_move -1; copy mode=remove; mark_files all=True val=False
map <F6> chain cut; tab_move 1; paste; tab_move -1; copy mode=remove; mark_files all=True val=False

**Comment by og900aero** [comment]
Working great, thank u so much!

**Comment by og900aero** [comment]
> Try mapping `:chain` command, like this: `:chain copy; tab_move 1; paste`

Thx, work like a charm! I added a little, so it's completely like the 2-tab file managers:
map chain copy; tab_move 1; paste; tab_move -1; copy mode=remove; mark_files all=True val=False
map chain cut; tab_move 1; paste; tab_move -1; copy mode=remove; mark_files all=True val=False
