### ISSUE TITLE
Prompt flashing every second

### ISSUE THREAD

**Issue by rexagod** [ranger/ranger#2745]
#### Runtime Environment

- Operating system and version: `Fedora 37`
- Terminal emulator and version: `kitty 0.26.5`
- Python version: `3.11.0`
- Ranger version/commit: `1.9.3`
- Locale: `en_US.UTF-8`

#### Current Behavior

On running `:call termopen("ranger")` inside `neovim`, it shows a prompt (kind of?) that keeps repeating every second (PTAL below).

<details>
<summary>Screencast</summary>

[Screencast from 2022-11-21 05-43-38.webm](https://user-images.githubusercontent.com/33557095/202934409-f49b285c-4786-45b0-ba0c-2ca0de3327c2.webm)

</details>

#### Expected Behavior

No prompt flashing every second.

#### Context

I'm trying to run `ranger` inside vim as I use it outside of `neovim` too, and I was using [ranger.vim](https://github.com/francoiscabrol/ranger.vim) until recently I noticed this, and removed the plugin to verify where the bug was. Could this be stemming from the behavior specified in `ranger` when it runs as a nested process?

#### Steps to reproduce
1. Open `neovim`. 
2. Run `:call termopen("ranger")`.

**Comment by rexagod** [comment]
Pasting the config in a bit.

**Comment by rexagod** [comment]
- `rc.conf`: https://pastebin.com/607eMNfs
- `rifle.conf`: https://pastebin.com/5LyVJkcK
- `scope.sh`: https://pastebin.com/jWrLJqKC

**Comment by rexagod** [comment]
cc @toonn

**Comment by rexagod** [comment]
Bump.

**Comment by rexagod** [comment]
Update: this was fixed by setting `update_title` to `false`. Closing now.

**Comment by toonn** [comment]
Apologies for taking so long to get around to your issue.

What you're seeing is a sequence of escape codes that should be interpreted by a terminal emulator, or a terminal multiplexer like Screen or TMUX, to set the "window" title. This might be something the NeoVim maintainers would be interested in fixing. If not then we can consider adding an exception to Ranger to refrain from echoing that escape sequence, even if the user requested it by setting update_title.
