### ISSUE TITLE
Cannot import name 'Ranger'

### ISSUE THREAD

**Issue by yyytiancai** [ranger/ranger#2757]
#### Runtime Environment

- Operating system and version: macOS Big Sur 11.4
- Terminal emulator and version: Terminal.app 2.11
- Python version: Python 3.6.13
- Ranger version/commit: 
 ranger                    0.1.dev0                 
ranger-fm                 1.9.3                   

- Locale: 

#### Current Behavior
```
(py36_torch) ➜  ~ python
Python 3.6.13 |Anaconda, Inc.| (default, Feb 23 2021, 12:58:59) 
[GCC Clang 10.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ranger
>>> from ranger import Ranger
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Ranger'

```

#### Context
Why there is no error report when I type "import ranger", but cannot import Ranger？
Is a problem with version or my download process or something else?
CAN ANYBODY HELP ME?
Please!!Thanks!!!

**Comment by aaronXctl** [comment]
Same question here, I get ImportError

I am doing a deep learning project and run python script in terminal which contains Ranger() 
> optimizer = Ranger(model.parameters(), **config['optimizer']['args'])

- ImportError: cannot import name 'Ranger' from 'ranger'

**Comment by markus-bauer** [comment]
You're in the wrong repo.
Probably looking for this: https://github.com/lessw2020/Ranger-Deep-Learning-Optimizer

**Comment by yyytiancai** [comment]
您好，已收到。
