### ISSUE TITLE
Error Displaying image in ranger using w3m

### ISSUE THREAD

**Issue by piush-terminalwitchcraft** [ranger/ranger#2764]
OS - Ubuntu WSL 
terminal - alacritty 

error - 
![image](https://user-images.githubusercontent.com/76522725/209422646-ffcae2d4-62a7-42f9-aa0f-cd9065e77be9.png)

**Comment by toonn** [comment]
I doubt Alacritty is compatible enough with XTerm for w3m to work. Unfortunately the only current option is probably Ueberzug but that was discontinued by the author. Alacritty might support SIXEL and there's an open PR that implements support so you could try that out.
