### ISSUE TITLE
after reboot pop-up with editor choices doesn't work anymore

### ISSUE THREAD

**Issue by matrixcollegemtl1980** [ranger/ranger#2765]
#### Runtime Environment

- Operating system and version: Linux Mint 20.3 (Una)
- Terminal emulator and version:  Bash 5.0.17(1)
- Python version:  3.8.10
- Ranger version/commit:  3.8.10
- Locale:  en_CA.UTF-8

#### Current Behavior
after reboot, this option won't work anymore

#### Expected Behavior
after installing ranger in linux mint 20.3, and navigating to a *.txt- file. then on-click "enter" there was a pop up to choose among available editors.

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```

```

**Comment by kohane27** [comment]
What does your `rifle.conf` look like for `mime ^text`? 
`!mime ^text, label editor, ext txt = ${VISUAL:-$EDITOR} -- "$@"` should use your editor of choice

**Comment by matrixcollegemtl1980** [comment]
thank you for your prompt reply @kohane27 .
there was no riple.conf there so I have followed : 
ranger --copy-config=rifle
to have it.
here the lines similar, so to answer your question : 
mime ^text,  label editor = ${VISUAL:-$EDITOR} -- "$@"
mime ^text,  label pager  = "$PAGER" -- "$@"
!mime ^text, label editor, ext xml|json|csv|tex|py|pl|rb|js|sh|php = ${VISUAL:-$EDITOR} -- "$@"
!mime ^text, label pager,  ext xml|json|csv|tex|py|pl|rb|js|sh|php = "$PAGER" -- "$@"
I forgot to mention in the previous post that the when the "pop- menu" dissipated, on-click "enter" initially I was accessing with nano, then it has changed to vim, and now, after a reboot of ranger is still vim, and no "pop-up" as initially described.
When, I position on a txt- file, and click "r" I am able to open_with my existing editors.
Also, to open, images, and videos, i need to click "r", and choose either "xdg-open" or celluloid, and I see, for some guys it is asking to choose ...

**Comment by kohane27** [comment]
That's odd because if you're using ranger, there should be no pop-up menu at all, because ranger is a terminal application. ranger simply chooses the application to open the file with with the default set in your `rifle.conf`. If you set the default "Open with" in your Linux Mint, does it achieve the behaviors you want?

**Comment by matrixcollegemtl1980** [comment]
I found a way, thank you @kohane27:
# open ranger, press "s", that will open ranger 's shell,
# then enter  "select-editor" :

Select an editor. To change later, run 'select-editor'.
1. /bin/nano
2. /usr/bin/vim.basic
3. /usr/bin/vim.tiny
4. /bin/ed

Choose 1-4 [1]:
Cheers, and Happy New Year !

**Comment by toonn** [comment]
Yeah, this sounds like a fetaure of Linux Mint. They probably set `VISUAL` and/or `EDITOR` to `select-editor` initially and then the first time the user runs it and selects an editor they remember the choice and always use that editor from then on. Not really related to Ranger at all. Glad that you figured it out and didn't have to wait for me to get around to the issue though!
