### ISSUE TITLE
Bat theme looks darker in ranger preview than in standard output

### ISSUE THREAD

**Issue by 3rfaan** [ranger/ranger#2769]
I've made a custom theme for bat inspired by the Everforest theme by sainnhe. My issue is that in ranger the colors look darker than in the normal output in the terminal. I've attached a picture to show you what I mean.

Above you can see a normal bat output and it shows the right colors. But below in ranger when I open the exact same file in the preview the colors appear to be darker.

Is there any idea on how to get the true colors into the ranger preview?
![screenshot-20230103-182139Z-all](https://user-images.githubusercontent.com/28968837/211053735-5a202d1c-96eb-4ac0-8bc9-55eb19c3511f.png)

**Comment by markus-bauer** [comment]
Perhaps you should post your theme. Otherwise it will be difficult to debug this.

How do bat themes work? They are just hex colors, right?
Or do you add dim/bright modifiers?

**Comment by 3rfaan** [comment]
> Perhaps you should post your theme. Otherwise it will be difficult to debug this.
> 
> How do bat themes work? They are just hex colors, right? Or do you add dim/bright modifiers?

Yes they are hex colors and it's saved as .tmTheme file. What is weird that in normal bat output the colors are perfectly fine I just face this issue inside ranger. This is my everforest.tmTheme file:

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        
        <key>author</key>
        <string>Arfan Zubi</string>
        <key>name</key>
        <string>Everforest</string>
        <key>colorSpaceName</key>
        <string>sRGB</string>
        <key>settings</key>
        <array>
            <dict>
                <key>settings</key>
                <dict>
                    <key>background</key>
                    <string>#2F383E</string>
                    <key>caret</key>
                    <string>#D3C6AA</string>
                    <key>foreground</key>
                    <string>#D3C6AA</string>
                    <key>invisibles</key>
                    <string>#08000000</string>
                    <key>lineHighlight</key>
                    <string>#D3C6AA</string>
                    <key>selection</key>
                    <string>#543A48</string>
                    <key>gutter</key>
                    <string>#0a000000</string>
                    <key>gutterForeground</key>
                    <string>#08000000</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Text</string>
                <key>scope</key>
                <string>variable.parameter.function</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#D3C6AA</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Comments</string>
                <key>scope</key>
                <string>comment, punctuation.definition.comment</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#859289</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Punctuation</string>
                <key>scope</key>
                <string>punctuation.definition.string, punctuation.definition.variable, punctuation.definition.string, punctuation.definition.parameters, punctuation.definition.string, punctuation.definition.array</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#7FBBB3</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Delimiters</string>
                <key>scope</key>
                <string>punctuation, meta.brace, meta.delimiter, meta.bracket</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#859289</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Operators</string>
                <key>scope</key>
                <string>keyword.operator</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#E69875</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Keywords</string>
                <key>scope</key>
                <string>keyword</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#E67E80</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Variables</string>
                <key>scope</key>
                <string>variable</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#D3C6AA</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Functions</string>
                <key>scope</key>
                <string>entity.name.function, meta.require, support.function.any-method</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#A7C080</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Labels</string>
                <key>scope</key>
                <string>entity.name.label</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#E67E80</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Classes</string>
                <key>scope</key>
                <string>support.class, entity.name.class, entity.name.type.class</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#E69875</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Classes</string>
                <key>scope</key>
                <string>meta.class</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#E69875</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Methods</string>
                <key>scope</key>
                <string>keyword.other.special-method</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#A7C080</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Storage</string>
                <key>scope</key>
                <string>storage</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#E67E80</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Support</string>
                <key>scope</key>
                <string>support.function</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#A7C080</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Strings, Inherited Class</string>
                <key>scope</key>
                <string>string, constant.other.symbol, entity.other.inherited-class</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#A7C080</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Integers</string>
                <key>scope</key>
                <string>constant.numeric</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#D699B6</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Floats</string>
                <key>scope</key>
                <string>none</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#D699B6</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Boolean</string>
                <key>scope</key>
                <string>constant.language.boolean</string>
                <key>settings</key>
                <dict>
                    <key>fontStyle</key>
                    <string>bold</string>
                    <key>foreground</key>
                    <string>#D699B6</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Macro</string>
                <key>scope</key>
                <string>entity.name.function.preprocessor</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#DBBC7F</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Constants</string>
                <key>scope</key>
                <string>constant</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#83C092</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Tags</string>
                <key>scope</key>
                <string>entity.name.tag</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#E69875</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Attributes</string>
                <key>scope</key>
                <string>entity.other.attribute-name</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#DBBC7F</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Attribute IDs</string>
                <key>scope</key>
                <string>entity.other.attribute-name.id, punctuation.definition.entity</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#D699B6</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Selector</string>
                <key>scope</key>
                <string>meta.selector</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#05000000</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Values</string>
                <key>scope</key>
                <string>none</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#D3C6AA</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Headings</string>
                <key>scope</key>
                <string>markup.heading punctuation.definition.heading, entity.name.section</string>
                <key>settings</key>
                <dict>
                    <key>fontStyle</key>
                    <string>bold</string>
                    <key>foreground</key>
                    <string>#E69875</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Units</string>
                <key>scope</key>
                <string>keyword.other.unit</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#E69875</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Bold</string>
                <key>scope</key>
                <string>markup.bold, punctuation.definition.bold</string>
                <key>settings</key>
                <dict>
                    <key>fontStyle</key>
                    <string>bold</string>
                    <key>foreground</key>
                    <string>#7FBBB3</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Italic</string>
                <key>scope</key>
                <string>markup.italic, punctuation.definition.italic</string>
                <key>settings</key>
                <dict>
                    <key>fontStyle</key>
                    <string>italic</string>
                    <key>foreground</key>
                    <string>#7FBBB3</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Code</string>
                <key>scope</key>
                <string>markup.raw.inline</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#D3C6AA</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Link Text</string>
                <key>scope</key>
                <string>string.other.link, punctuation.definition.string.end.markdown, punctuation.definition.string.begin.markdown</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#01000000</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Link Url</string>
                <key>scope</key>
                <string>meta.link</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#09000000</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Quotes</string>
                <key>scope</key>
                <string>markup.quote</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#09000000</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Separator</string>
                <key>scope</key>
                <string>meta.separator</string>
                <key>settings</key>
                <dict>
                    <key>background</key>
                    <string>#0b000000</string>
                    <key>foreground</key>
                    <string>#07000000</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Inserted</string>
                <key>scope</key>
                <string>markup.inserted</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#02000000</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Deleted</string>
                <key>scope</key>
                <string>markup.deleted</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#01000000</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Changed</string>
                <key>scope</key>
                <string>markup.changed</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#05000000</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Colors</string>
                <key>scope</key>
                <string>constant.other.color</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#E69875</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Regular Expressions</string>
                <key>scope</key>
                <string>string.regexp</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#A7C080</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Escape Characters</string>
                <key>scope</key>
                <string>constant.character.escape</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#A7C080</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Embedded</string>
                <key>scope</key>
                <string>punctuation.section.embedded, variable.interpolation</string>
                <key>settings</key>
                <dict>
                    <key>foreground</key>
                    <string>#05000000</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Illegal</string>
                <key>scope</key>
                <string>invalid.illegal</string>
                <key>settings</key>
                <dict>
                    <key>background</key>
                    <string>#01000000</string>
                    <key>foreground</key>
                    <string>#0f000000</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Broken</string>
                <key>scope</key>
                <string>invalid.broken</string>
                <key>settings</key>
                <dict>
                    <key>background</key>
                    <string>#09000000</string>
                    <key>foreground</key>
                    <string>#00000000</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Deprecated</string>
                <key>scope</key>
                <string>invalid.deprecated</string>
                <key>settings</key>
                <dict>
                    <key>background</key>
                    <string>#0e000000</string>
                    <key>foreground</key>
                    <string>#0f00000</string>
                </dict>
            </dict>
            <dict>
                <key>name</key>
                <string>Unimplemented</string>
                <key>scope</key>
                <string>invalid.unimplemented</string>
                <key>settings</key>
                <dict>
                    <key>background</key>
                    <string>#08000000</string>
                    <key>foreground</key>
                    <string>#0f000000</string>
                </dict>
            </dict>
        </array>
        <key>uuid</key>
        <string>uuid</string>
    </dict>
<`

**Comment by markus-bauer** [comment]
Isn't this supposed to be a xml file?

**Comment by markus-bauer** [comment]
I think, this also happens with some of the builtin themes.
I suspect it is related to the COLORTERM variable in scope.sh:
https://github.com/ranger/ranger/blob/f8b304f74be20c56f8596e6ea312c7c041d0def4/ranger/data/scope.sh#L341

Set this variable in you terminal before running bat, and then compare bat and scope/ranger again.

If you want, you can also test it by removing the COLORTERM part in scope.sh. Then run that file directly. Just put in some dummy values for the other arguments:
```
~/.config/ranger/scope.sh FILE_NAME 100 100 "" ""
```

Now here's the problem. If you try it with ranger, it won't work, because ranger can't render that output.

There's a discussion about it here (search for COLORTERM):
https://github.com/ranger/ranger/pull/1394

And here's where I reach the end of my knowledge.

It might be that ranger's ansi parsing is incomplete.
More likeley it's because ncures only introduced extended color (true color, direct color, whatever it's called) recently and it would require python 3.10 (I think).

**Comment by toonn** [comment]
That's exactly right, thanks for doing the digging : )

Closing this for now, extended color support will probably be implemented at some point.
