### ISSUE TITLE
syntax highlighting is broken in wsl2

### ISSUE THREAD

**Issue by trace1729** [ranger/ranger#2770]
#### Runtime Environment

- Operating system and version:  WSL2 Ubuntu20.04 
- Terminal emulator and version:  Windows Termmial
- Python version: 3.8.10
- Ranger version/commit: 1.9.3-1build1
- Locale: en_US.UTF-8

#### Current Behavior
Syntax highlighting is broken  though I've already installed `highlight` 
![image](https://user-images.githubusercontent.com/69061787/211194588-43a9e5c3-9b40-42db-aaf7-dd8e289fd08d.png)

#### Expected Behavior
Being able to preveiw highlighted code

**Comment by markus-bauer** [comment]
I just noticed, that your image shows that you're running as root.
ranger disables the settings for file previews when running as root:
https://github.com/ranger/ranger/blob/f8b304f74be20c56f8596e6ea312c7c041d0def4/ranger/core/main.py#L144-L147

A message should be shown in the message log (press W).

So, that might be the issue. I think, you can still re-enable it (:set use_preview_script true)
I don't know if you should!
https://github.com/ranger/ranger/issues/1369#issuecomment-450551266

**Comment by trace1729** [comment]
Thanks for the reply!  Your assumption is correct. Running as root caused this issue. I tried re-enable `preview_files`  and `use_preview_script!` by `set xxx true`,  but this strategy only works for `preview_files`.  When I type `:set use_preview_script! true`, ranger just don't responding.

**Comment by toonn** [comment]
If you use the `!` you can't pass a value. That would cause setting the "use_preview_script!" setting, which isn't a setting. You can toggle image previews with `zi` BTW.
