### ISSUE TITLE
Suggestion: maybe make renaming files process faster.

### ISSUE THREAD

**Issue by segfaulty1** [ranger/ranger#2772]
#### Suggested Behavior
I thought it would be really cool if I could keep my eyes on the file itself while renaming it, instead of looking at the command input bellow.
It might be just me though but I feel I'm being slowed down when I had to shift my eyes around.

that is all.
keep it up. you are doing a really good job.

**Comment by manujchandra** [comment]
In my` rc.conf` I have mapped 

`map cb bulkrename`

Now, I can select one or more files and press cb, it will open all file names in vim. I can change them as I like using all vim tools and save. The files are all saved.

You can see a video of how to do it [here](https://youtu.be/0hzLjBx4E6M?t=1063).

**Comment by markus-bauer** [comment]
A note about bulkrename:
#1058

**Comment by manujchandra** [comment]
@markus-bauer Thanks for the useful link.

Sorry for an obvious question, but is this change already implemented or do I need to do it myself?

**Comment by markus-bauer** [comment]
@manujchandra I don't know much more about this, but since you asked me:

No it's not merged.

vidir is just a perl script: https://github.com/trapd00r/vidir.
You can download it and run it like any other shell command.
```
:shell vidir %s
```

It might be enough to to just bind it or alias it in ranger (not tested):
```
alias bulkrename shell vidir %s
```

**Comment by toonn** [comment]
Since there doesn't seem to be all that much interest in this feature request and we have so little time to work on things I'm inclined to close this. It might be different if someone made a PR implementing this.
