### ISSUE TITLE
"sudo ranger" crashes

### ISSUE THREAD

**Issue by da-the-dev** [ranger/ranger#2773]
#### Runtime Environment

- Operating system and version:  Fedora release 37
- Terminal emulator and version: GNOME Terminal version 3.45.90
- Python version: 3.11.1
- Ranger version/commit: ranger-master 
- Locale: en_US

#### Current Behavior
`sudo ranger` crashes the tool

#### Expected Behavior
ranger launches as a super user
#### Context
I need to browse some super-user restricted files and folders

#### Possible Solutions
I remember it working fine before, maybe a breaking change in some commit?

#### Steps to reproduce
1. sudo ranger

#### Traceback

```
~ sudo ranger
ranger version: ranger-master 
Python version: 3.11.1 (main, Dec  7 2022, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/ranger/core/main.py", line 174, in main
    fm.initialize()
  File "/usr/local/lib/python3.11/site-packages/ranger/core/fm.py", line 128, in initialize
    self.bookmarks.load()
  File "/usr/local/lib/python3.11/site-packages/ranger/container/bookmarks.py", line 49, in load
    new_dict = self._load_dict()
               ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ranger/container/bookmarks.py", line 239, in _load_dict
    dct[key] = self.bookmarktype(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ranger/container/directory.py", line 150, in __init__
    assert not os.path.isfile(path), "No directory given!"
AssertionError: No directory given!

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by Ragnyll** [comment]
can this issue get some attention? I'm seeing the exact same thing without sudo.  posting my info too in case it helps.

**Runtime Environment**

    Operating system and version: Arch Linux 6.1.8-arch1-1
    Terminal emulator and version: alacritty 0.11.0 (8dbaa0bb)
    Python version: 3.10.9
    Ranger version/commit: ranger-master
    Locale: en_US

**Current Behavior**

`ranger` crashes the tool

**Expected Behavior**

ranger launches

**Context**

I tried start ranger and it crashes

Possible Solutions

I remember it working fine before, maybe a breaking change in some commit?

**Steps to reproduce**

    `ranger`

Traceback
```
ranger version: ranger-master
Python version: 3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 174, in main
    fm.initialize()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 128, in initialize
    self.bookmarks.load()
  File "/usr/lib/python3.10/site-packages/ranger/container/bookmarks.py", line 49, in load
    new_dict = self._load_dict()
  File "/usr/lib/python3.10/site-packages/ranger/container/bookmarks.py", line 239, in _load_dict
    dct[key] = self.bookmarktype(value)
  File "/usr/lib/python3.10/site-packages/ranger/container/directory.py", line 150, in __init__
    assert not os.path.isfile(path), "No directory given!"
AssertionError: No directory given!

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
````

**Comment by mikeri** [comment]
Have you tried on a clean install? I just did a
`lxc launch images:fedora/37 fedora`
and in the container, as a normal user:
`git clone https://github.com/ranger/ranger`
`sudo python3 setup.py install`
`sudo ranger`
It worked fine.

If you haven't already, try removing ~/.config/ranger and ~/.local/share/ranger.
If it works, try moving things back one at a time to find out what is causing the issue, then report back here.

**Comment by Ragnyll** [comment]
blowing away that ~/.local/share/ranger did the trick for me.

**Comment by toonn** [comment]
This was probably because there was a bookmark to a path that no longer exists in the file system. Known bug but tracked elsewhere.
