### ISSUE TITLE
scope.sh video thumb nailing code is broke.

### ISSUE THREAD

**Issue by EvanCarroll** [ranger/ranger#2774]
This code

https://github.com/ranger/ranger/blob/master/ranger/data/scope.sh#L171

Is currently broke. I'm not even sure what that code as I have video thumbnails without it. But that code won't work,

    ffmpegthumbnailer -i "${FILE_PATH}" -o "${IMAGE_CACHE_PATH}" -s 0

The `-o` argument to ffmpegthumbnailer doesn't take a path in my tests. It only takes an absolute location to the file generated.

----

```
❯ ffmpegthumbnailer -i movie.webm -o /tmp/
Error: Failed to open output file: /tmp/
❯ ffmpegthumbnailer -i movie.webm -o /tmp/thumbnail.png
❯ file thumbnail.png
thumbnail.png: PNG image data, 128 x 72, 8-bit/color RGB, non-interlaced
```

**Comment by markus-bauer** [comment]
What do you mean? It's working:
> The -o argument to ffmpegthumbnailer doesn't take a path in my tests.
> ❯ ffmpegthumbnailer -i movie.webm -o /tmp/thumbnail.png

IMAGE_CACHE_PATH is just that, the file path where the cacheimage is to be created, like /tmp/cache_img.jpg.
And that's what ranger does.

I don't get what the problem is. What doesn't work?

**Comment by toonn** [comment]
I agree, it doesn't sound like there's an actual problem here.
