### ISSUE TITLE
NamedTemporaryFile ignores IMAGE_CACHE_DIRECTORY

### ISSUE THREAD

**Issue by EvanCarroll** [ranger/ranger#2775]
Previously thumbnails was done in scope.sh here,

https://github.com/ranger/ranger/blob/master/ranger/data/scope.sh#L171

This attempted to take into account IMAGE_CACHE_PATH

Now that code seems to be here,

https://github.com/ranger/ranger/blob/391f061cb0b0cfa8266c0651f2a6d948f22e01dd/ranger/ext/img_display.py#L669

And the problem with this is that there is no ability to set the cache directory so they're all recorded to `/tmp`. **At the very least. you should store them in a directory in tmp**. But ideally, we'd be able to configure the cache directory. The function you're using, [`NamedTemporaryFile`](https://docs.python.org/3/library/tempfile.html) permits that by setting the `dir` argument.

**Comment by markus-bauer** [comment]
That's not where "thumbnails" are created. They are created by scope.sh. The paths for those images are created here:
https://github.com/ranger/ranger/blob/f8b304f74be20c56f8596e6ea312c7c041d0def4/ranger/core/actions.py#L1115

Images are saved in your default cache path, most likely ~/.cache/ranger.

From `man ranger`:
```
--cachedir=dir
             Change the cache directory of ranger from $XDG_CACHE_HOME or ~/.cache/ranger to
             "dir".
```

What you linked is something entirely different. It's how image preview is done with the Kitty terminal. Ranger loads the image, perhaps resizes/converts it, and writes it to a temporary file, that kitty displays and then deletes. There's a PR about this:
https://github.com/ranger/ranger/pull/2750
