### ISSUE TITLE
tag and select not working as expected

### ISSUE THREAD

**Issue by w2kpro** [ranger/ranger#2777]
#### Runtime Environment

- Operating system and version:  Mint 20.3
- Terminal emulator and version: 
- Python version: 3.8.10
- Ranger version/commit: 1.9.3
- Locale: 

#### Current Behavior
Select a file using the spacebar. Tag the next file using 't''.
The tag jumps to the first file which is then both selected and tagged.
#### Expected Behavior
The first file should get selected and the second file should be tagged.
#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```

```

**Comment by w2kpro** [comment]
Select one file and tag the next. The first file gets both selected and tagged!

**Comment by toonn** [comment]
Tagging works on the selection, this is intended behavior so you can tag as many files as you want simultaneously.
