### ISSUE TITLE
A way to append actions.py into .config/ranger as commands.py ?

### ISSUE THREAD

**Issue by Twix53791** [ranger/ranger#2778]
Hello,

I am building my ranger config and I customized some functions into actions.py, as it was easier to modify the code here than create a plugin, or a command into commands.py. It that an easy way to place my custom functions into a file into .config/ranger and then source this file in ranger?? What would be the best way to customize the core of ranger without modifying the ranger build-in files? Thanks for any clue... 
PS: the best would be to create plugins, but I got plenty of errors when I move a function from actions.py to a plugin, and my level in python is way to far to solve easily all of them...

**Comment by toonn** [comment]
Maybe a tool like [quilt](https://www.man7.org/linux/man-pages/man1/quilt.1.html) could help to manage your patches.

Closing because we do not want to make `actions.py` configurable. `commands.py` already serves that purpose.
