### ISSUE TITLE
Unable to map `<C-j>`

### ISSUE THREAD

**Issue by Bekaboo** [ranger/ranger#2780]
#### Runtime Environment

- Operating system and version: Linux 6.1.9
- Terminal emulator and version: Kitty, 0.27.0
- Python version: 3.10.9
- Ranger version/commit: ranger-master
- Locale: en_GB.UTF-8

#### Current Behavior

Cannot map `<C-j>` to scroll_preview 8. It still performs the default behavior (opening a file).

#### Expected Behavior

Remapping `<C-j>` should work.

#### Context

Minimal config (`rc.conf`) to reproduce:

```
set use_preview_script true
set preview_files true
map <C-j> scroll_preview 8
map <C-k> scroll_preview -8
map <UP>       move up=1
map <DOWN>     move down=1
map <LEFT>     move left=1
map <RIGHT>    move right=1
map <HOME>     move to=0
map <END>      move to=-1
map <PAGEDOWN> move down=1   pages=True
map <PAGEUP>   move up=1     pages=True
map <CR>       move right=1
```

an interesting thing is that if I remove the last line (`map <CR>       move right=1`), hitting `<C-j>` will scroll the preview, but I need `<CR>` to open the files. I just cannot see why `<CR>` and `<C-j>` cannot coexist, after all they have different key codes in terminals.

#### Possible Solutions

N\A

#### Steps to reproduce

Use the minimal `rc.conf` above, launch ranger, press `<C-j>` on a file and see the result.

#### Traceback

```

```

**Comment by Bekaboo** [comment]
Found an issue that might be related: #1026. Is this a bug that hasn't been fixed yet?

**Comment by toonn** [comment]
When you press carriage return your terminal interprets it as `^J` which is identical to the effect pressing Ctrl and j has. So it's not possible to decouple these. This is not an issue with Ranger it's a more fundamental issue with how terminal emulators work.
