### ISSUE TITLE
rifle cant open binary file

### ISSUE THREAD

**Issue by DiarrheaMcgee** [ranger/ranger#2794]
#### Runtime Environment

- Operating system and version: 6.1.10-gentoo-x86_64
- Terminal emulator and version: kitty 0.26.5
- Python version: python 3.10.9
- Ranger version/commit: 1.9.3-r1
- Locale: en_US

#### Current Behavior
when i try to run an executable file (application/x-executable) it says

```
xdg-open: unexpected option '--'
Try 'xdg-open --help' for more information.
```

#### Expected Behavior
running the binary file

#### Context

i need to be able to run binary files from ranger
when i set ranger.conf to **ONLY**
```
mime application/x-executable = "$@"
```
only let me run some binary files but not others (even though they all had the same mimetype)
also when i do that it doesnt let me run any other files
when i have other things in the file (ranger --copy-config=rifle) it has the xdg error and can open other files

#### Possible Solutions
i dont know

#### Steps to reproduce
1. ranger --copy-config=rifle
2. attempt to run a binary file
3. observe the fact that it doesnt work

#### Traceback

```

```

**Comment by toonn** [comment]
Ah, the xdg-open error is something that has been fixed on the master branch. `xdg-open` doesn't support the convention of stopping processing of -flags and --options after `--`. You can delete the `--`. This does mean that that rule is being triggered for those files though.

**Comment by MikulasV** [comment]
Ensure that `mime application/x-executable = "$@"` is in the config file before `label open, has xdg-open = xdg-open "$@"` and it should work.
