### ISSUE TITLE
remove some dot files from hidden file in rc.conf

### ISSUE THREAD

**Issue by gabokamaze** [ranger/ranger#2798]
Hi,
I am facing problem with hidden files.
I would like to consider (for example) the ".config" folder as NOT a hidden file -> I tried to edit following parameter in rc.conf, but without success :
set hidden_filter

I succeed to add a new folder/file to the list of hidden file, but not the inverse (specify a dot file/folder which should not be considered as hidden file).

Is it possible ? If yes, how to do it ? If not, could you add a new parameter, for exemple "set no_hidden_file" (or something smarter) ?
Thanks by advance
Regards

**Comment by toonn** [comment]
You should be able to change the first part of the regular expression from `^\.` to `^\.(?!config$)`.

User question tend to get faster responses on our subreddit r/ranger or in our IRC channel #ranger at Libera.Chat.

Closing because I think this fixes your issue, we can reopen if it doesn't.
