### ISSUE TITLE
:find doesn't open highlighted entry, when exact but ambiguous match found

### ISSUE THREAD

**Issue by DerFlob** [ranger/ranger#281]
Image you have a folder with files named
- some-file
- something-test
- test

If the file 'some-file' is currently selected and you use the :find command to search for 'test', the file 'something-test' will be highlighted, as it is the first match found. However if you press Enter, the file 'test' will be opened, not the highlighted 'something-test'.

I'm using ranger 1.6.1.
Edit:
PS: Is there a way to cycle between matches, if they are ambigous like that? Or should the file 'test' been opened automatically, because it is an exact match?

**Comment by Vifon** [comment]
I can reproduce it with the latest Git master.

**Comment by randynobx** [comment]
Running ranger 1.6.1 with python 3.4.3 on Arch linux, I am *not* able to reproduce this bug.

@DerFlob and @Vifon could you please elaborate on your exact setup? And any other details regarding the issue.

**Comment by DerFlob** [comment]
Oh, I just retried it and the problem only seems to occur with folders, not files. Sorry about that. So you should have folders called 'some-folder', 'something-test' and 'test' for example.

If you then type ':find test' in the console, when 'some-folder' was selected, and hit Enter, ranger has highlighted 'something-test' but descends into the 'test' folder. 

I doesn't work for files, because ranger didn't automatically open the file upon hitting Enter.

**Comment by randynobx** [comment]
Ah, I am reproducing the bug now; using folders instead of files as you said.

Tip about opening files though, (assuming you're opening the file with vim), hitting enter does open the selected file, but the screen doesnt redraw with vim until you hit a key (like hjkl for navigation in vim) that forces it.

**Comment by vimeitor** [comment]
Yay, it works perfectly now. Thank you @nfnty =)
