### ISSUE TITLE
Prevent flickering when open editor in seperate window

### ISSUE THREAD

**Issue by ch3n9w** [ranger/ranger#2810]
Many thanks to this project and its contributors, I use ranger for years, but I noticed this problem which is not an error of program but still a little annoying for me.

#### Runtime Environment

- Operating system and version: Linux version 6.2.7-arch1-1 (linux@archlinux) 
- Terminal emulator and version: alacritty 0.11.0 (8dbaa0bb)
- Python version: Python version: 3.10.10
- Ranger version/commit: ranger 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior

Flicking before open editor in seperate window, here is screen record:
![output](https://user-images.githubusercontent.com/40637063/226509917-7b84c7c7-219e-4537-b54b-f894a7f79aa4.gif)

#### Expected Behavior

ranger will not flicker but stay in column view when open editor in seperate window

#### Context
My `rifle.conf` contains:
```
mime ^text,  label editor, flag t = ${VISUAL:-$EDITOR} -- "$@"
mime ^text,  label pager, flag t = "$PAGER" -- "$@"
!mime ^text, label editor, ext xml|json|csv|tex|py|pl|rb|js|sh|php|yml|yaml|qrc|go|rs|norg, flag t = ${VISUAL:-$EDITOR} -- "$@"
!mime ^text, label pager,  ext xml|json|csv|tex|py|pl|rb|js|sh|php|yml|yaml|qml|go|rs|norg, flag t = "$PAGER" -- "$@"
```

#### Possible Solutions

Add an option to stay in column view when there is flag t?

**Comment by toonn** [comment]
Can you clarify this issue? Does the flickering only happen during resizing?
I don't see Ranger not "staying in column view?"

**Comment by ch3n9w** [comment]
Oh! Yes the flickering only happen during resizing, sorry my bad !
