### ISSUE TITLE
How to paste path from ranger to terminal?

### ISSUE THREAD

**Issue by pigasus55** [ranger/ranger#2811]
There is way, how to change current shell directory https://github.com/ranger/ranger/wiki/Integration-with-other-programs#changing-directories
This is good. But it doesn't work when you need to write a command with multiple paths.

I want it like that: 1) start to write command 2) press hotkey 3) select path in file manager 4) path inserted into typing command
![find filemanager2](https://user-images.githubusercontent.com/128574753/226821438-5a068bf4-b018-4bcc-9d4a-c20fbbe04c18.png)

Default tab completion and ls are bad when folder have a lot of files.

I tried bash binding
bind -x '"\C-k":"echo -n 123"'
bind -x '"\C-k":"echo -n 123 > /dev/pts/2"
But the insertion does not pass after the cursor, but at the beginning of the line.
![find filemanager3](https://user-images.githubusercontent.com/128574753/226821499-715179aa-d75d-4e4c-a90e-34eb065f86f3.png)
'

Also, there is a clipboard in the bash. ctrl-w, ctrl-y — cut and paste text.
Man bash calls this clipboard as «killing ring».
Maybe it will be possible to solve it this way. But i don’t know, how use it programmatically.

Any more ideas?

**Comment by pigasus55** [comment]
But i want only terminal soulution.
If we can't insert the path into the cursor or into the terminal buffer. Then the other way is to send the selected path to a program that simulates pressing each letter of the path to insert the path into the cursor.

**Comment by pigasus55** [comment]
Dirty solution 2 - use variables
Pros - can work without X11. Cons - values are unvisible.

PushToSVars() {
    S3="$S2"
    S2="$S1"
    S1="$1"
}

PushToXclip() {
    echo -n "$1" | xclip -selection c
}

PushToClipboard() {
  PushToSVars "$1"  # uncomment, when without X11
  #PushToXclip "$1"   # uncomment, when use X11
}

FM_GetPath() {
    temp_file="$(mktemp -t "FMpath.XXXXXXXXXX")"
    ranger --choosedir="$temp_file" -- "${@:-$PWD}"    
    PushToClipboard "$(cat "$temp_file")"
    rm -f "$temp_file"
}

bind -x '"\C-o":"FM_GetPath"'


Example of use : cp "$2" "$1"

**Comment by pigasus55** [comment]
True solution.

The answer was under the nose, LOL!
Man bash speaks about it in description of bind command. Editable string have variables: READLINE_LINE, READLINE_MARK, READLINE_POINT.

Then a script will be like this:

```
PushToShell() {    
    befCurs="${READLINE_LINE:0:READLINE_POINT}"
    aftCurs="${READLINE_LINE:READLINE_POINT}"    
    READLINE_LINE="$befCurs$1$aftCurs"    
    READLINE_POINT=$(($READLINE_POINT+$(echo -n "$1" | wc -m)))
}

FM_PastePath() {
    dir="$(mktemp -t "FM_Dir.XXXXXXXXXX")"
    file="$(mktemp -t "FM_File.XXXXXXXXXX")"    
    ranger --choosedir="$dir" --choosefile="$file" "${@:-$PWD}"
    PushToShell "$([ -s "$file" ] && cat "$file" || cat "$dir")"
    rm -f "$dir"
    rm -f "$file"
}

bind -x '"\C-o":"FM_PastePath"'
```

It works independently of X11.
I recommend placing this next to https://github.com/ranger/ranger/wiki/Integration-with-other-programs#changing-directories.

**Comment by toonn** [comment]
@pigasus55, the wiki is editable by users, this seems like a cool addition 👍
