### ISSUE TITLE
The command prompt menu disappears when previewing pictures in kitty

### ISSUE THREAD

**Issue by fuanxka** [ranger/ranger#2833]
#### Runtime Environment

- Operating system and version: Archlinux 6.2.13
- Terminal emulator and version: kitty 0.28.1
- Python version: 3.10.10
- Ranger version/commit: 1.9.3
- Locale: zh_CN

#### Current Behavior
When press a command key, such as z, while previewing an image in kitty, the image disappears and the command menu below disappears with it. Until the picture is automatically refreshed for the first time, the command menu refreshes with it. But when the picture refreshes the second time, the command menu never appears again.

#### Expected Behavior
When the command key is pressed, the command menu is displayed and does not disappear.

#### Config
use_preview_script true
preview_images true
preview_images_method kitty

**Comment by toonn** [comment]
Already tracked in #2667, could use help troubleshooting this further.
