### ISSUE TITLE
Ranger doesnt respect nvim configs

### ISSUE THREAD

**Issue by HappyCthulhu** [ranger/ranger#2835]
#### Runtime Environment

- Operating system and version: Arch Linux x86_64 
- Terminal emulator and version: fish 3.6.1
- ranger version: ranger 1.9.3
- Python version: 3.11.1 (main, Feb 14 2023, 12:07:52) [GCC 12.2.1 20230201]
- Locale: en_US.UTF-8

#### Current Behavior

When i open text files with ranger, it open nvim without using my `init.vim`.

#### Expected Behavior

When i open text files with ranger, it will open them with my config from `~/.config/nvim/init.vim`

#### Context

At least, i want to be able to copy text from nvim, which was opened from ranger. Also, that will be cool, if my colorsheme and shortcuts and other settings will be available)

**Comment by toonn** [comment]
I suspect this is because you haven't set either `VISUAL` nor `EDITOR` and therefore Ranger is falling back to invoking `vim`. Combined with some behavior from NeoVim to not read its configuration if it is invoked as `vim`?

Ranger does nothing to keep editors from reading their configuration.

**Comment by HappyCthulhu** [comment]
I think u right, thx. Set `nvim` as default value of `EDITOR` var and ranger start to respect nvim configs
