### ISSUE TITLE
Unmark command bug

### ISSUE THREAD

**Issue by og900aero** [ranger/ranger#2840]
The unmark command only works, when the marked files/directory is on the same level. When browsing other directory, and run :unmark, then not delete previously marked files/directory.
Example:

1. go to the /etc/nftables/nftables.conf
2. Press space for marking
3. go to the /home/shyciii/.config
4. add :unmark command
5. The nftables.conf marking doesnt delete

**Comment by toonn** [comment]
Marks are current-view scoped if you will. So this is expected behavior. Ranger won't operate on marked files in other directories.

**Comment by toonn** [comment]
I'm not sure why you'd want to. The selection would only matter when you go back to that directory and can easily be cleared at that point with `uv` or the unmark command with a pattern.

The copy_buffer is a separate concept and determines what files are pasted. `yy` and `dd` add to the copy_buffer, pasting clears it again. You can add things from multiple directories to the copy_buffer at the same time if you wish, using `ya`/`da`. The selection is independent from the copy_buffer at all times and only influences the files operated on at a local scope. If you would like yanking to clear the selection every time then just change the binding, `map yy chain copy; mark_files all=True val=False`.

**Comment by og900aero** [comment]
> I'm not sure why you'd want to. The selection would only matter when you go back to that directory and can easily be cleared at that point with `uv` or the unmark command with a pattern.
> 
> The copy_buffer is a separate concept and determines what files are pasted. `yy` and `dd` add to the copy_buffer, pasting clears it again. You can add things from multiple directories to the copy_buffer at the same time if you wish, using `ya`/`da`. The selection is independent from the copy_buffer at all times and only influences the files operated on at a local scope. If you would like yanking to clear the selection every time then just change the binding, `map yy chain copy; mark_files all=True val=False`.

Thx  working great.
