### ISSUE TITLE
open_with r flag usage

### ISSUE THREAD

**Issue by og900aero** [ranger/ranger#2841]
I want to open file with sudo rights. The solution is map key open_with r. That's okay, but is there any way to add this to the CTRL+RIGHT button?
`map <C-RIGHT> open_with r`    doesnt work.

**Comment by og900aero** [comment]
`map <C-RIGHT> open_with r`

**Comment by toonn** [comment]
I think currently we only support a limited number of key combinations with Ctrl, `abcdefghijklmnopqrstuvwxyz_` and space.

**Comment by og900aero** [comment]
> I think currently we only support a limited number of key combinations with Ctrl, `abcdefghijklmnopqrstuvwxyz_` and space.

Thx.
