### ISSUE TITLE
Ranger bindings clash with NeoVim bindings when used as a plugin

### ISSUE THREAD

**Issue by I-Own-You** [ranger/ranger#2849]
#### Runtime Environment

- Operating system and version: arch linux kde latest version
- Terminal emulator and version:  kitty terminal latest version
- Python version: python 3.11.3
- Ranger version/commit: ranger 1.9.3
- Locale: en_US.UTF-8

Hi! I am using this file manager in terminal as its best through all i had used, but i have a weird problem and i want to ask you maybe you know how to solve it because my knowledge have limits on this topic even though i researched a bit.

I have tried all ranger plugins for neovim and they all are very *not as good as ranger is for terminal*, but i did find a good one written 3 weeks ago in lua, this [ranger-nvim](https://github.com/kelly-lin/ranger.nvim). But they all have 1 problem in common, when you open ranger in neovim, the keymaps from neovim do clash with ranger ones resulting in a lot of *delay and misstyping*. I have tried some ways of disabling all neovim keymaps when in ranger but i couldn't. I know i should ask ranger-nvim plugin maintainer but he is innactive for some time, so maybe you know how to achieve a way of disabling neovim keymaps being in a ranger instance or at least force ranger keymaps over anything neovim keymaps are trying to overwrite ?

**Comment by toonn** [comment]
You could try asking this on [our subreddit](https://www.reddit.com/r/ranger/), it's possible someone's run into this before and has a fix.

Either way, I think it is better asked in the NeoVim community. I'm not sure what we can do from our side to make Ranger play nice as a NeoVim plugin and I think the NeoVim community might have this information.
