### ISSUE TITLE
FEATURE REQUEST: Open_with as fork by default

### ISSUE THREAD

**Issue by connbrack** [ranger/ranger#2852]
#### Runtime Environment
- Operating system and version: Kubuntu 22.04.2 LTS
- Terminal emulator and version: konsole
- Python version: Python 3.10.6
- Ranger version/commit: ranger 1.9.3

#### Current Behavior
A fork flag is needed when using the open_with command. The solution printed [here](https://github.com/ranger/ranger/wiki/Keybindings#always-fork-when-using-open_with) works, but removes the ability to auto-complete the app name. 

#### Expected Behavior
Provide an option for users to open_with fork as a default behavior, or allow for autocomplete when the fork flag is present.

#### Context
Based on the discussion [here](https://github.com/ranger/ranger/issues/1310). I nearly always want to fork and often forget to add the flag.

#### Possible Solutions
 I imagine this could be done a number of ways but the alias method linked above combined with working autocorrect would be good. Alternatively giving users the ability to modify config files to specify programs open as fork even when using the open_with command. (I believe there is a way when not using open_with). Or allow the behavior to be flipped, always open as fork unless specified otherwise.

#### Steps to reproduce
Only an issue with some programs. For example, vscode always opens as a fork, while GIMP does not unless a flag is added.

**Comment by toonn** [comment]
Whoops, sorry, I guess I didn't communicate this clearly. You should open an issue on fixing tab completion when flags are provided for `open_with`, forking by default is up to the user to configure, with the flag.
Could you open an issue on the tab completion problem with a minimum reproducing example?
