### ISSUE TITLE
setting sc-im as default for sc file type in rifle.conf

### ISSUE THREAD

**Issue by pbwn** [ranger/ranger#2853]
#### Runtime Environment

- Operating system and version: MX linux 21.3
- Terminal emulator and version: xfce-terminal 1.0.2 (xfce 4.18)
- Python version: 3.9.2
- Ranger version/commit: 1.9.3
- Locale: en_AU.UTF-8

#### Current Behavior
try to open sc files with l in ranger and nothing happens

#### Expected Behavior
sc-im opens the file

#### Context
if i run `sc-im file.sc` on the command line it opens in sc-im, no problem. Using a line like that below (step 3) in my 
rifle.conf works for everything else, eg zathura for pdfs, libre calc for csv, etc. It would be great if i could get 
it to work for sc-im

#### Steps to reproduce
1. install ranger
2. install sc-im: https://github.com/andmarti1424/sc-im
3. add relevant line to rifle.conf: ext sc, has sc-im, X, flag f = sc-im -- "$@"
4. try opening an sc file in ranger with l

```

**Comment by toonn** [comment]
Closing this because it's more appropriate for the [subreddit, where it's already getting answered : )](https://www.reddit.com/r/ranger/comments/13rfpg3/setting_scim_as_default_for_sc_file_type/)
We can reopen this if it turns out to be a bug.
