### ISSUE TITLE
Status bar ':' input rendering issues with 2 columns and previews

### ISSUE THREAD

**Issue by BenCzu** [ranger/ranger#2854]
Hi, I wasn't able to find a similar issue (hope I am not repeating)

#### Runtime Environment

- Operating system and version: 
  - macOS Ventura 13.4
- Terminal emulator and version:
  - iTerm2 (not running ranger in tmux)
- Python version: 
  - 3.11.3
- Ranger version/commit: 
  - 1.9.3
- Locale: 
  - en_AU.UTF-8

#### Current Behavior
When entering ':' for commands sometimes it overlays the status bar (at the bottom) instead of clearing it and other times it starts typing on the otherside or underneath:
![Screenshot 2023-05-28 at 9 14 20 pm](https://github.com/ranger/ranger/assets/106460858/3605e8ad-9afa-4914-837b-aedaf8ebd14a)

#### Expected Behavior
When typing ':', the text at the bottom should clear and I can start typing at the bottom left of the window.

#### Possible Solutions
When I have 3 columns ('set column_ratios 2,3,4') I don't get this issue or when I am not currently previewing.
#### Steps to reproduce
This issue only occurs when I have a preview active (same issue with .mp4, .png and .pdf) and 2 columns set in my rc.conf with 'set column_ratios 3,4'. 

Thanks!!

**Comment by toonn** [comment]
Is it just with exactly 2 columns? How about more than 3 or fewer?
I assume this is with the iTerm2 preview method?

**Comment by BenCzu** [comment]
Yes I am using the iTerm2 preview method. No issue with more than 3 columns. Issue persists with fewer than 2 columns.
