### ISSUE TITLE
Image misalignment during st terminal image preview

### ISSUE THREAD

**Issue by fengwk** [ranger/ranger#2870]
#### Runtime Environment
- Operating system and version: Linux arch 6.1.37-1-lts
- Terminal emulator and version: st 0.9
- Python version: 3.11.3
- Ranger version/commit: 1.9.3
- Locale: zh_CN.UTF-8

#### Current Behavior

Preview image misalignment:

![image](https://github.com/ranger/ranger/assets/25793618/0f816059-cf6a-4904-98e9-90de65cf35a5)

#### Expected Behavior

The image is in the right position, like Alacrity:

![image](https://github.com/ranger/ranger/assets/25793618/b93dba84-b108-4a9d-be08-12d65c189501)

**Comment by markus-bauer** [comment]
What `preview_images_method` do you use?

**Comment by fengwk** [comment]
> What `preview_images_method` do you use? Wayland or Xorg (might be relevant)?

Xorg and `set preview_images true`

**Comment by moshpirit** [comment]
Same here, but it's not showing any picture at all. When commenting `set preview_images_method ueberzug` ranger shows the pictures horizontally at the middle of the terminal, vertically at the top of the terminal.

**Comment by toonn** [comment]
Might be worth reporting upstream for ueberzugpp. Ranger provides the rows and columns of the area to use unless I'm mistaken. It's possible `st` reports the window size in an unexpected way though. If someone digs into this it might be an easy fix.

**Comment by fengwk** [comment]
![image](https://github.com/ranger/ranger/assets/25793618/bcaea248-d6e0-4386-8208-3fa4dd801c77)

Recently, I found out that it has returned to normal in my environment. Could it be due to the updated and fixed version of ueberzugpp?

```
ueberzugpp 2.8.9-3
```

**Comment by toonn** [comment]
That's possible. Good to hear it's fixed.

**Comment by moshpirit** [comment]
extra/ueberzug is different from aur/ueberzugpp. I still have the issue with ueberzug, maybe it was fixed on ueberzugpp.
