### ISSUE TITLE
Ueberzug stopped displaying images after last Arch update

### ISSUE THREAD

**Issue by PoisonFrog** [ranger/ranger#2871]
#### Runtime Environment

- Operating system and version:  Arch Linux
- Terminal emulator and version:  kitty 0.28.1
- Python version:  3.11.3
- Ranger version/commit: ranger version: ranger-master 
- Locale:  en_US

#### Current Behavior
Ueberzug does not display images anymore. There is just a blank space.

#### Expected Behavior
Images being displayed in ranger when ueberzug is set as the image preview method.

Ueberzug just stopped working all of a sudden after I updated Arch Linux, not sure what package caused this but it doesn't work anymore. Since I use kitty I tried the kitty image preview method but I always had an issue that it would crash when running a command while it was displaying an image, but after some research here I found out that this issue would be gone when installing from git and that was what I did and it indeed fixed the issue BUT kitty image preview performance is not as good as ueberzug's performance. I wish the performance of kitty image preview could be improved in ranger because the way it is I kind want to go back to ueberzug so I hope someone knows how to fix this issue.

**Comment by sourav-majumdar-math** [comment]
I am facing the same issue. Seems like `python-pillow` upgrade causes the issue, downgrading to 9.5.0-2 fixes it.

**Comment by PoisonFrog** [comment]
> I am facing the same issue. Seems like `python-pillow` upgrade causes the issue, downgrading to 9.5.0-2 fixes it.
> 
> See also: [ueber-devel/ueberzug#15 (comment)](https://github.com/ueber-devel/ueberzug/issues/15#issue-1786543860)

Downgrading python-pillow fixed the issue. This is a good temporary solution.

I'm closing the issue since it is not a ranger issue.

**Comment by PoisonFrog** [comment]
As a more permanent solution you can install ueberzugpp (a fork of ueberzug written in C++) from the AUR since that seems to work without issues.

**Comment by gikunJo** [comment]
> > I am facing the same issue. Seems like `python-pillow` upgrade causes the issue, downgrading to 9.5.0-2 fixes it.
> > See also: [ueber-devel/ueberzug#15 (comment)](https://github.com/ueber-devel/ueberzug/issues/15#issue-1786543860)
> 
> Downgrading python-pillow fixed the issue. This is a good temporary solution.
> 
> I'm closing the issue since it is not a ranger issue.

Downgrading is not a good idea. Pillow has removed Image.ANTIALIAS in 10.0, which was used in ueberzug' s loading.py and scaling.py.  Just replace it with Image.LANCZOS.
