### ISSUE TITLE
Ranger displays strangely in macOS 13.5 

### ISSUE THREAD

**Issue by BLACKSWORD0** [ranger/ranger#2878]
#### Runtime Environment

- Operating system and version: macOS   13.5
- Terminal emulator and version: iterm2    3.4.19
- Python version: python 3.9.6
- Ranger version/commit:  ranger 1.9.3
- Locale: 

#### Current Behavior
When I try to show hidden files ,  ranger performs strangely. The following is process:

https://github.com/ranger/ranger/assets/56479341/0774caeb-9667-4798-a333-a6114ab63050

#### Expected Behavior
I think it should display no residual context when I show hidden files.

#### Steps to reproduce
1. Open iterm2
2. Clone the repository
3. Use "python3 ranger.py" to open ranger
4. Press "backspace" or "zh"  to show hidden file.

#### Traceback

```

```

**Comment by toonn** [comment]
I'm not sure what's going wrong here. Maybe an Ncurses issue? Maybe someone on macOS 13.5 should try reporting this upstream to iTerm2? Even if it's not their bug they may be able to point us to a more specific part to look at.

**Comment by BLACKSWORD0** [comment]
In fact，I use ranger in other terminal such as kitty, alacritty, there is the same issue. So I think this is not because of iterm2.   I have download the latest ncurses (from homebrew), the version is 6.4  .  
I have the same issue in macOS12.6.7  on same macbook with M1 chip.  So I think it is not because of the macOS version.
  And there is no issue in same macOS version on macbook with intel chip. So I think it might be because of the M1 chip.

**Comment by vincent-vega** [comment]
I'm experiencing the same bug on an Intel Mac with macOS 13.5.1, so it seems not related to the M1 chip only. It was running fine before the 13.5 update.

**Comment by Bellavene** [comment]
Wow, somehow I didn't found this post. updated a week ago the system and got the same screen update corruption.
https://github.com/ranger/ranger/issues/2893

**Comment by tiborsimon** [comment]
Upgrading to Sonoma seems to fix it.
