### ISSUE TITLE
Ranger crash with sixel preview method using foot

### ISSUE THREAD

**Issue by Erwsaym** [ranger/ranger#2879]
#### Runtime Environment

- Operating system and version: Fedora38 - Sway spin
- Terminal emulator and version: foot version: 1.15.0 -pgo +ime +graphemes +fractional-scaling -cursor-shape -assertions
- Python version: 3.11.4 (main, Jun  7 2023, 00:00:00) [GCC 13.1.1 20230511 (Red Hat 13.1.1-2)]
- Ranger version/commit: ranger 1.9.3
- Locale: en_US.UTF-8

#### Current 

I got a crash when configuring range to use preview image with sixel method using foot terminal emulator.

#### Expected Behavior

- Create a `rc.conf` file in `.config/ranger/` with preview configuration :
```
set preview_images true
set preview_images_method sixel
```
- Launch Ranger via Foot
- Go to my image folder and be able to see preview

#### Context

I'm trying to use preview image in ranger thanks to siexel implemented in terminal  emulator I use : foot.

#### Possible Solutions

None

#### Steps to reproduce
1. Be on Fedora 38 Spin : Sway
2. Install ranger
3. Create a `rc.conf` file in `.config/ranger/` containing
```
set preview_images true
set preview_images_method sixel
```
4. Launch ranger
5. Crash

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.11.4 (main, Jun  7 2023, 00:00:00) [GCC 13.1.1 20230511 (Red Hat 13.1.1-2)]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ranger/core/main.py", line 171, in main
    fm.initialize()
  File "/usr/lib/python3.11/site-packages/ranger/core/fm.py", line 104, in initialize
    set_image_displayer()
  File "/usr/lib/python3.11/site-packages/ranger/core/fm.py", line 103, in set_image_displayer
    self.image_displayer = get_image_displayer(self.settings.preview_images_method)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ranger/ext/img_display.py", line 99, in get_image_displayer
    image_displayer_class = IMAGE_DISPLAYER_REGISTRY[registry_key]
                            ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ranger/ext/img_display.py", line 79, in fallback_image_displayer
    raise ImgDisplayUnsupportedException
ranger.ext.img_display.ImgDisplayUnsupportedException

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by Ethsan** [comment]
Ranger 1.9.3 doesn't support sixel rendering, but it is merged https://github.com/ranger/ranger/pull/2466 and will be supported in 1.9.4.

**Comment by Erwsaym** [comment]
Ohh I assumed it was already in 1.9.x 😃 
Thanks !
