### ISSUE TITLE
Bump version for 1.9? What is going on?

### ISSUE THREAD

**Issue by EvanCarroll** [ranger/ranger#2882]
Background: I was following an issue a long time ago, #2750. It was patched on March 5 with https://github.com/ranger/ranger/commit/4d2c3413a55286f68d79b67f67cf992753cad8bb I thought the new version would be in my repo, but there was never a version bump.

Looking at the tags there hasn't been a version bump since 1.9.3 in 2019.

Maybe we could just release 1.9.4 to get this work out there?

**Comment by balejk** [comment]
See #2702.
