### ISSUE TITLE
Part of the interface is missing to be drawn when resizing the window over an image using the Sixel image preview method

### ISSUE THREAD

**Issue by joaopauloalbq** [ranger/ranger#2889]
#### Runtime Environment

- Operating system and version: Manjaro (up-to-date)
- Terminal emulator and version: 
xfce4-terminal 1.1.0
vte 0.75.0.r2.g2066534d
- Python version: 3.11.3
- Ranger version/commit: 1.9.3.719.g136416c7
- Locale: pt_BR.UTF-8

#### Current Behavior
Part of the interface is missing to be drawn.

#### Expected Behavior
Drawn the entire interface

#### Context

Resize the window and continue to see the entire content

#### Possible Solutions
Refresh content after window resizing?

#### Steps to reproduce
1. Set the image preview method to sixel
2. Open ranger over an image
3. Resize the window to a smaller size
4. Resize the window to a larger size

#### Demo
https://github.com/ranger/ranger/assets/9905202/10e1301e-20fa-4af9-a33a-35099ecd0bd3

**Comment by toonn** [comment]
Could you describe more precisely what part of the interface is missing after resizing? I don't see any statusbars missing or such in the video.

**Comment by joaopauloalbq** [comment]
For example, at 0:03 of the video, this entire part in red is missing after being resized.

![Screenshot_20230914_130603](https://github.com/ranger/ranger/assets/9905202/efc3c454-5cb1-4b25-980c-fd5588538edb)

**Comment by Bellavene** [comment]
That was an ncurses bug, or you have older part of ncurses library somewhere in your path.

**Comment by toonn** [comment]
Going to take @Bellavene on their word and close this. If it's still a problem, feel free to re-open.

**Comment by Bellavene** [comment]
Still, ranger sometimes does not update properly the window after resize. But it is rare. And I don't know how to reproduce it.
