### ISSUE TITLE
Garbage on PageUp/PageDown in multipane mode

### ISSUE THREAD

**Issue by Bellavene** [ranger/ranger#2893]
Somehow it started by itself. Whenever I try to navigate by page keys, the screen doesn't update correctly. Sometimes it gets corrupted after window resize.
Fun fact, it only behaves so in multipane view mode without opened tabs. In miller view mode or if more than one tab is opened, it behaves normally.

https://github.com/ranger/ranger/assets/77557804/a0be5d39-bff4-4bc2-81fe-da15cb2f4ecb

<img width="496" alt="Screenshot 2023-09-07 at 21 31 03" src="https://github.com/ranger/ranger/assets/77557804/77f277c6-a16d-4a78-afe6-44c75fea9cb4">

**Comment by toonn** [comment]
Does the problem only show up after resizing? It's not clear to me what "doesn't update correctly" means.

**Comment by Bellavene** [comment]
Nope. Mostly when ranger tries to update the screen, not all lines are updated. Not rangers fault, but I want to know what causes it. I believe it started after macos update...

**Comment by Bellavene** [comment]
Here is another video 

https://github.com/ranger/ranger/assets/77557804/fcb3167f-8554-4958-b04b-295fc1385e64

**Comment by Bellavene** [comment]
Microsoft found some security issues in ncurses [1] which was addressed in macOS 13.5 it seems
https://www.microsoft.com/en-us/security/blog/2023/09/14/uncursing-the-ncurses-memory-corruption-vulnerabilities-found-in-library/

Maybe it somehow changed the WINCH signal? I will leave this issue for open now, possibly someone with the same bug and a solution will see it.

**Comment by Bellavene** [comment]
Found another related post, but with nnn
https://github.com/jarun/nnn/issues/1703

**Comment by Bellavene** [comment]
As mysteriously it appeared, so it has gone suddenly by itself. I don't know what to say, and what is the OS doing by itself under the hood... I haven't even updated brew, just in one moment it went to normal.
