### ISSUE TITLE
Ranger crashes after update on arch linux

### ISSUE THREAD

**Issue by nath1as** [ranger/ranger#2903]
#### Runtime Environment

- Operating system and version:  Arch Linux 6.4.12-arch1-1
- Terminal emulator and version: st with zsh 5.9
- Python version: 3.11.5
- Ranger version/commit:  ranger 1.9.3
- Locale: en

#### Current Behavior
ranger crashes,
tried to reinstall and use other packages (ranger-git and ranger)

#### Steps to reproduce
run ranger command

#### Traceback
```
ranger version: ranger-master
Python version: 3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/ranger/core/main.py", line 183, in main
    fm.initialize()
  File "/usr/lib/python3.11/site-packages/ranger/core/fm.py", line 128, in
initialize
    self.bookmarks.load()
  File "/usr/lib/python3.11/site-packages/ranger/container/bookmarks.py", line 49, in load
    new_dict = self._load_dict()
               ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ranger/container/bookmarks.py", line 239, in _load_dict
    dct[key] = self.bookmarktype(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/ranger/container/directory.py", line 130, in __init__
    assert not os.path.isfile(path), "No directory given!"
AssertionError: No directory given!

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

```

**Comment by Traap** [comment]
I had the same issue with latest Arch.  I was able to resolve the issue with ```pacman -R ranger``` followed by ```yay ranger-git```.

**Comment by toonn** [comment]
Due to the error this may be a bookmarked that no longer exists. Try moving `${XDG_DATA_HOME:-$HOME/.local/share}/ranger/bookmarks` out of the way and starting Ranger again.

**Comment by nath1as** [comment]
> Due to the error this may be a bookmarked that no longer exists. Try moving `${XDG_DATA_HOME:-$HOME/.local/share}/ranger/bookmarks` out of the way and starting Ranger again.

thanks, this solves the issue
