### ISSUE TITLE
Which copy command is used by yy/pp

### ISSUE THREAD

**Issue by michaepr** [ranger/ranger#2920]
When I yank a file or folder with `yy` and then paste it somewhere with `pp`. Which command is actually executed under the hood? Is it `cp`? `rsync`? Something else? Does it depend on whether the copy is local or to a (mounted) remote drive?

Thanks for your help!

**Comment by gigamicro** [comment]
`paste()` from `ranger.core.actions` (loaded as commands in `ranger.core.main:390`) uses `CopyLoader` from `ranger.core.loader` uses functions from `ranger.ext.shutil_generatorized` which according to the first-line comment is originally from the python 2.7.13 standard library (and which uses python's `os` and `open`)
`ranger.ext.shutil_generatorized.move()` does a copy-and-delete if `os.rename()` fails

**Comment by michaepr** [comment]
Great, thanks for your answer
