### ISSUE TITLE
How to run ranger when installed via pip?

### ISSUE THREAD

**Issue by cyberdynesoftware** [ranger/ranger#2930]
I've installed ranger with pip instead of with a package manager (ok, I know, pip is also a package manager...). On pip the package is called 'ranger-fm'. This did not create a command I could simply run from the terminal (I didn't expect it to). I tried to run

    python3 -m ranger

which yields:

    /Library/Developer/CommandLineTools/usr/bin/python3: No module named ranger.__main__; 'ranger' is a package and cannot be directly executed

Not sure if that was supposed to work. So, how do I run ranger installed via pip?

**Comment by Rom1deTroyes** [comment]
If you had installed ranger by running `python3 -m pip install ranger-fm` you may have a `ranger` command somewhere (mine is in `~/.local/bin/ranger` because I had installed it for user only) : maybe this path is not in your `PATH` environment ?

**Comment by cyberdynesoftware** [comment]
I found it in `~/Library/Python/3.8/bin/`
