### ISSUE TITLE
yank path not working on wsl

### ISSUE THREAD

**Issue by freddieventura** [ranger/ranger#2949]
I am working on `wsl2` which has a special clipboard `clip.exe`

```
$ ranger --version
ranger version: ranger 1.9.3
Python version: 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0]
Locale: en_US.UTF-8
```

Simply when using any of the commands related to yank , such as `yank dir` `yank name` `yan path` etc... , they do not work.
It may be because `xclip` is not present in my system , instead (as mentioned before ) `wsl` uses `clip.exe`. So I normally have to come up with solutions around this.

For instance in `vim` I got the following

```
clip = '/mnt/c/Windows/System32/clip.exe' 
autocmd TextYankPost * if v:event.operator ==# 'y' | call system(clip, @0) 
```

Is there a way to instruct ranger to copy to `clip.exe` provided that `wsl` clipboard is not supported out of the box?

Thank you

**Comment by 1096015776** [comment]
hey,I have the same issue,but i use other method to solve it,maybe you can try it.
@freddieventura 
map yp eval fm.ui.console.execute(fm.open_console('shell echo -n ' + fm.thisfile.path+' | clip.exe'))
map yd eval fm.ui.console.execute(fm.open_console('shell echo -n ' + fm.thisfile.dirname+' | clip.exe'))

map yn eval fm.ui.console.execute(fm.open_console('shell echo -n ' + fm.thisfile.basename+' | clip.exe'))
map y. eval fm.ui.console.execute(fm.open_console('shell echo -n ' + fm.thisfile.basename_without_extension+' | clip.exe'))

**Comment by freddieventura** [comment]
Amazing , that works pretty well.
Thank you!!
