### ISSUE TITLE
Add filetype glyphs (icons)

### ISSUE THREAD

**Issue by AnderRasoVazquez** [ranger/ranger#298]
Would be nice to have a toggeable "show filetype glyphs" option, here is an example of [a vim plugin that does that](https://github.com/ryanoasis/vim-webdevicons/blob/master/readme.md)
![image](https://github.com/ryanoasis/vim-webdevicons/wiki/screenshots/v0.4.0/overall-screenshot.png)

**Comment by Vifon** [comment]
Are they Unicode characters? It should be fairly easy to implement using linemodes. See: [Custom linemodes guide][1].

[1]: https://github.com/hut/ranger/wiki/Custom-linemodes

**Comment by hut** [comment]
Looks like you need a special font for this

**Comment by Vifon** [comment]
Not necessarily. Unicode contains many characters you wouldn't expect it to. FontAwesome supports most of them and their subset is supported by most of the modern fonts.

**Comment by rosshadden** [comment]
The question can probably be a bit more general:  Would it be possible to add support for icons for files?  Ideally it would run a (defaulted) script, which can return an icon character when given a filename/extension.  Then we in userland could make a script that implements [vim-devicons](https://github.com/ryanoasis/vim-devicons).

**Comment by alexanderjeurissen** [comment]
I experimented a bit and using a patched NERD font and custom line-mode I got it working 
see the following gist:

https://gist.github.com/alexanderjeurissen/73053bb0a8b02f5d7f1674294c5fec3c

a screenshot of ranger with icons:
![screen shot 2016-05-05 at 18 38 41](https://cloud.githubusercontent.com/assets/1220084/15049821/a480f4be-12f0-11e6-9310-30e2cb818186.png)

only problem remaining is:
1. I'm still not sure how to force the default_linemode to be my custom line mode.
2. Directories of inactive columns somehow can't be resolved and fall back to my unknown file icon.

**Comment by rosshadden** [comment]
This looks awesome!  Do I have to import your linemode file from somewhere to make this work, or is there a magic place in the filesystem to put them?

**Comment by alexanderjeurissen** [comment]
@rosshadden you have to move both the `devicons.py` and `devicons_linemode.py` files to `.config/ranger/plugins` 

then to activate the linemode use `:linemode devicons` in ranger

if your content and it works then you can choose to make this your default line mode by adding the following line to `rc.conf`

`default_linemode devicons`

**Comment by rosshadden** [comment]
Thanks, the part I didn't know was where to put the files.  Putting them in `plugins` didn't work, and after some debugging I found it to be because the `devicons` import fails in the linemode file.  Are you sure you have `devicons.py` in the same directory?

Thanks

**Comment by AnderRasoVazquez** [comment]
What am I doing wrong? I have fontawesome and powerline-fonts installed. `devicons.py` or `~/.config/ranger` and `devicons_linemode.py` on `~/.config/ranger/plugins `
![seleccion_128](https://cloud.githubusercontent.com/assets/3936719/15094660/89053936-14ab-11e6-9836-4c04ef21af63.png)

**Comment by alexanderjeurissen** [comment]
@AnderRasoVazquez Try installing one of the nerd fonts 
https://github.com/ryanoasis/nerd-fonts

I personally use the Patched Source Code Pro font.

make sure to download one of the `complete` fonts as that project also contains patched fonts that only contain one of the glyph sets (font-awesome, powerline)

If that doesn't help can you check if the glyphs do show up if you open devicons.py inside your editor of choice ?

**Comment by AnderRasoVazquez** [comment]
Installing nerd-fonts did it. It looks really good! This should be included =)

**Comment by nfnty** [comment]
Add your plugin to the [Wiki - Community plugins](https://github.com/ranger/ranger/wiki/Community-plugins).

**Comment by j-degreef** [comment]
@nfnty 
Hi, I have the feeling you forgot to... ;)

**Comment by nfnty** [comment]
@j-degreef The wiki is editable by anyone, so go ahead and add it.

**Comment by ismay** [comment]
I'm running into the following error when using the plugin:

```
Invalid linemode: devicons; should be metatitle/sizemtime/filename/mtime/fileinfo/permissions
```

Everything seems to be working fine (all icons are showing etc.), and I've placed `devicons.py` in `~/.config/ranger/devicons.py` and `devicons_linemode.py` in `~/.config/ranger/plugins/devicons_linemode.py`. Did anyone else run into this? It's not broken anything, but it would be nice to prevent this error from showing everytime after I exit ranger.

**Comment by nfnty** [comment]
See [Wiki - Custom Linemodes](https://github.com/hut/ranger/wiki/Custom-linemodes) and the [example linemode in `examples` directory](https://github.com/ranger/ranger/blob/master/examples/plugin_linemode.py) for how to properly implement a linemode.

**Comment by ismay** [comment]
I did, it's just that I can't find anything else obviously wrong with the script. And I'm using the same files (from the gist) as everyone else in this thread, so I figured that I'm probably not the only one encountering this error.

**Comment by j-degreef** [comment]
@nfnty
I'll do it later (time...)
@ismay 
Same here but it doesn't seem to impact functionality.

Btw, icons are vertically "expanded" with Mono fonts in urxvt. I've read posts about this saying to use non Mono version of the font but it seem urxvt doesn't handle icons with non Mono fonts.
No problem with Terminator but then picture preview in Ranger don't work. Any idea what's the best terminal to have both (correct icons in ranger and image preview) ? I'm on Linux.

**Comment by j-degreef** [comment]
@alexanderjeurissen 
I've fixed the inactive columns problem, here's the code I use :
```
def devicon(file):                                                               
    if file.is_directory: return ''
    return file_node_exact_matches.get(file.relative_path, file_node_extensions.get(file.extension, ''))
```
file is passed as a directory object from devicons_linemode.py

I'll create a github repository if you don't mind and update the wiki later.

**Comment by alexanderjeurissen** [comment]
@j-degreef I was in the progress of creating a repo for this as well, if you don't mind I'll include your snippet and update the ranger wiki myself.

**Comment by j-degreef** [comment]
Ok, great.
To be complete, in devicons_linemode.py you should remove .relative_path in the call of devicon().
It's also necessary to remove the dot "." before the extensions in devicons.py.

When the repository is ready I will fork it and add missing files (.Xdefault, .Xressource, .vimrc,...) if it's not already done.

**Comment by alexanderjeurissen** [comment]
@j-degreef see: https://github.com/alexanderjeurissen/ranger_devicons

Could you clarify what you mean with missing files ?

**Comment by alexanderjeurissen** [comment]
I moved the gist to a separate repository including screenshots and installation instructions. I also added the plugin to the Wiki. So I think this issue can be closed.

https://github.com/alexanderjeurissen/ranger_devicons

**Comment by j-degreef** [comment]
@alexanderjeurissen 
I was talking about missing file names in devicons.py in the file_node_exact_matches section (like .vimrc, .Xdefault,...)

**Comment by alexanderjeurissen** [comment]
@j-degreef ah ok, well a PR is always welcome ;)

**Comment by yevhen-m** [comment]
What's the fix to this issue stated above by @ismay?
```
Invalid linemode: devicons;
```
The fact that it does not affect functionality does not mean that it should not be fixed.

**Comment by ismay** [comment]
I don't think that there's a fix for it currently. The issue for this is open here: https://github.com/alexanderjeurissen/ranger_devicons/issues/3 . I'm sure a pr to fix it would be welcome.

**Comment by yevhen-m** [comment]
@ismay this issues is not caused by `ranger-devicons` plugin, it implements everything according to the `ranger`'s wiki page. This is an issue of `ranger`. 
I assume `default_linemode` command in `rc.conf` is triggered before `devicons` linemode is registered. Cause if you manually switch to it  form inside `ranger`, there is no error.

**Comment by ismay** [comment]
Ah ok, well fixing it in ranger would be great yeah 👍

**Comment by FireAntJoe** [comment]
I have ranger installed and nerd-fonts and am having this issue. Any word on a fix?

**Comment by alexanderjeurissen** [comment]
@FireAntJoe please direct any issues with the provide script on the plugin repository. This issue is only meant as reference to the original discussion that resulted in the creation of the RangerDevIcons plugin. 

https://github.com/alexanderjeurissen/ranger_devicons/

**Comment by Vifon** [comment]
@FireAntJoe FWIW It seems to me it was fixed in #885.

**Comment by FireAntJoe** [comment]
@alexanderjeurissen @Vifon thank you. I was eventually able to get it fixed.

**Comment by pshoultz** [comment]
idk what I'm doing wrong.  

devicons is in ranger/
devicon_linemode.py is ranger/plugins/
downloaded the fonts.  They're viewable inside of vim.
set termite font = SauceCodePro Nerd Font 11
run :linemode devicons

and no icons.  I use another vim plugin to display my icons when I use ctrl+p, and the icons work there.

**Comment by toonn** [comment]
@pshoultz, do the other linemodes work? Maybe submit the question on the ranger_devicons issue tracker too.
