### ISSUE TITLE
Ranger's `%d` macro interferes with date command's `%d` format specification in the context of an alias

### ISSUE THREAD

**Issue by guidomz** [ranger/ranger#2981]
Ranger expands the `%d` in the following alias in rc.conf as the `/path/of/current/directory` instead of letting the shell's date command give the day's number:
```
alias logger shell echo $(date '+%Y%m%d %H:%M ') | tee -a logs
```
or I just probably don't know how to quote this, escape it or resolve this in any other way. 

But I managed a workaround, doing this instead (a while after I already wrote this issue):
```
alias logger shell echo $(date -I)$(date '+ %H:%M ') | tee -a logs
```
Nevertheless, it would still help if there was a way to use the finer-grained formatting arguments that the date command offers.

Disclaimers:
1. For brevity and to focus on the problem, I just simplified the example alias, which actually contains more commands.
2.  I googled "ranger" and "date" (quoted) and found no results.

**Comment by vejkse** [comment]
From the MACROS section of the man page:
```
To write a literal %, you need to escape it by writing %%.
```
For your case:
```
alias logger shell echo $(date '+%Y%m%%d %H:%M ') | tee -a logs
```

**Comment by guidomz** [comment]
Ok, thanks for the clarification. This actually solves the issue.
