### ISSUE TITLE
Doing cd is a problem when dealing with dynamic subdirectories

### ISSUE THREAD

**Issue by guidomz** [ranger/ranger#2991]
#### Runtime Environment

- Operating system and version:  Debian bookworm
- Terminal emulator and version:  terminator 2.1.2 on bash 5.2.15
- Python version: 3.11.2
- Ranger version/commit: 1.9.3
- Locale: en_US

#### Current Behavior
This runs fine on the bash commandline:
```
cd ~/Documents/$(date +%Y)-$(date +%m)
```

I want to create a key mapped to switching to a dynamic directory but all variations of cd (internal and shell) doesn't work when mixed with shell commands:
```
:shell cd ~/Documents/$(date +%Y)-$(date +%m)
:shell subdir=$(date +%Y)-$(date +%m); cd ~/Documents/$subdir
:cd ~/Documents/$(date +%Y)-$(date +%m)
```

in ~/.config/ranger/rc.conf:
```
alias this_month shell cd ~/Documents/$(date +%Y)-$(date +%m)
alias this_month shell subdir=$(date +%Y)-$(date +%m); cd ~/Documents/$subdir
alias this_month cd ~/Documents/$(date +%Y)-$(date +%m)
```

Using bookmarks instead of key mappings, in ~/.local/share/bookmarks:
```
d:/home/xxxxxx/Documents/$(date +%Y)-$(date +%m)
```

None of the preceeding commands switch to the desired directory and no error message is returned.

**Comment by vejkse** [comment]
Here's a way to cd into a directory whose name is the current year in ranger:
```python
:eval import datetime; fm.cd(datetime.datetime.now().year)
```
`eval` evaluates Python code, since ranger is in Python.

There may be other methods.  See https://github.com/ranger/ranger/issues/1869 for context, in particular you'll see why what you tried didn't work.

**Comment by guidomz** [comment]
ok, thanks for the guide. now I can do this in rc.conf:
```
alias cd_this_month eval import datetime; fm.cd('~/Documents/' + str(datetime.datetime.now().strftime('%Y-%m')))
map Cd cd_this_month
```
I hope this helps others.
