### ISSUE TITLE
Image preview with ueberzugpp fails on sway

### ISSUE THREAD

**Issue by psaikido** [ranger/ranger#2995]
#### Runtime Environment

1.9.3

- Operating system and version: 
endeavouros 2024.01.25

- Terminal emulator and version: 
foot 1.17.2

- Python version: 
3.12.4

#### Current Behavior
When looking at a jpg file it gives an error message:
"ueberzug: error while loading shared libraries: libopencv_videoio.so.409: cannot open shared object file: No such file or directory

#### Expected Behavior
An image preview rendered by ueberzugpp should display on the right of the screen as it used to before a recent system update I did on endeavour.

#### Context

I'm developing an application to manage wallpapers which is supposed to use ranger but it no longer can - https://gitlab.com/ue-tools/waywalls

I'm seeing this in swaywm using foot, alacritty or kitty.

**Comment by toonn** [comment]
This seems like ueberzugpp not finding a dependency on your system. This is really the reponsibility of the distribution first, ueberzugpp second, and not solvable by Ranger.

I recommend opening an issue with whoever manages the package for your distribution. Good luck!
