### ISSUE TITLE
Bug: opening ranger with ~ in paths var exits with "Inaccessible paths: ~"

### ISSUE THREAD

**Issue by pvl1** [ranger/ranger#3021]
#### Runtime Environment
- Arch Linux  6.10.10-arch1-1
- kitty 0.36.4 
- ranger version: ranger 1.9.3
- Python version: 3.12.7 (main, Oct  1 2024, 11:15:50) [GCC 14.2.1 20240910]
- Locale: en_US.UTF-8

#### Current Behavior
opening ranger with `ranger $(dirs)` fails with a message:

> Inaccessible paths: ~

#### Expected Behavior
would open in $HOME

#### Context
[[L98](https://github.com/ranger/ranger/blob/bd9b37faee9748798f3970468bd0d1dedbf0e99f/ranger/core/main.py#L98)]
[[L105](https://github.com/ranger/ranger/blob/bd9b37faee9748798f3970468bd0d1dedbf0e99f/ranger/core/main.py#L105)]
[[L344](https://github.com/ranger/ranger/blob/bd9b37faee9748798f3970468bd0d1dedbf0e99f/ranger/core/main.py#L344)]

#### Possible Solutions
maybe implement expanduser instead of abspath
https://stackoverflow.com/questions/2057045/os-makedirs-doesnt-understand-in-my-path
https://docs.python.org/3/library/os.path.html
(also a chance to refactor/DRY otherwise)

#### Steps to reproduce
1. `ranger $(dirs)`

**Comment by pvl1** [comment]
i guess this maybe a feature request rather than bug, for now i made a bash wrapper
```shell

alias ranger=rrranger
alias rrranger='if (( $(dirs | wc -w) > 1 )); then rrrrrranger $(dirs); else rrrrrranger;fi'
rrrrrranger () {
/usr/bin/ranger $@
}
```

**Comment by vejkse** [comment]
Wouldn’t just
```bash
ranger $(dirs -l)
```
be enough since `-l` makes `dirs` “not print tilde-prefixed versions of directories relative to your home directory”?

**Comment by pvl1** [comment]
wow i didnt think to look at the manpage for dirs, thought it was a builtin and simply printed a var.
because i dont use spaces in dir or file names, i figured wc would be enough
The array approach is definitely more elegant

**Comment by vejkse** [comment]
On my system, I can get it either by `help dirs` or deep inside `man bash`.

**Comment by toonn** [comment]
The reason `ranger ~` works and this didn't is because your shell actually expands twiddle before it's passed to Ranger in the former. This is a reasonable request though, IMO.
