### ISSUE TITLE
bookmarks, tags and history should be in XDG_DATA_DIR or ~/.local/share/ranger

### ISSUE THREAD

**Issue by jck** [ranger/ranger#303]

**Comment by jhxie** [comment]
After install you should first execute
> ranger --copy-config=all
then I believe all of the history, tags, etc should appear in ~/.local/share/ranger (although for me it is in ~/.config/ranger).

**Comment by jck** [comment]
I just tried with the latest git version, empty config dir and `ranger --copy-config=all` . history, tagged and bookmars are stored in ~/.config/ranger

**Comment by hut** [comment]
For clarification: Yes, this is a bug.
