### ISSUE TITLE
Search in display_file()

### ISSUE THREAD

**Issue by seamus-45** [ranger/ranger#312]
It would be nice to be able to search strings in a file when viewed by F3.
And something like `pmap  /  pager_search` in rc.conf. Or I do not know something?

**Comment by seamus-45** [comment]
Is there a way to use vimpager at the end of display_file () chain  ?

**Comment by hut** [comment]
"at the end of display_file () chain"?

You mean something like `pmap v shell vimpager %f` ?

**Comment by seamus-45** [comment]
display_file() is complex function, right? it handles not only text files but also archives and images. in case the preview includes text output, is it possible to send it to $PAGER?

**Comment by seamus-45** [comment]
my current settings is: map <F3> shell vimpager %s
but it only work for text file types and bad for archives and pdf for example

**Comment by hut** [comment]
You're probably looking for ~/.config/ranger/scope.sh. That's the script which generates the previews.
It takes arguments in the form of `scope.sh $path $width $height` where width/height specify the number of characters fitting in the preview pane. You can use this to pass stuff to vimpager, for example with:

`map F3 shell ~/.config/ranger/scope.sh %f 80 24 | vimpager`

If you don't have a scope.sh among your configs, run `ranger --copy-config=scope`.

Also I suggest to take a quick look into scope.sh, theres some further documentation inside.

**Comment by seamus-45** [comment]
This works quite well, thank you, but still no native support for search. Should we close this feature request?

**Comment by nfnty** [comment]
ranger shouldn't try to implement a feature complete pager. Much better to just rely on external pagers for the hard work.
