### ISSUE TITLE
highlight --out-format=xterm256 blinked

### ISSUE THREAD

**Issue by kobzar** [ranger/ranger#316]
Try to set another color theme for highlight.
I used rxvt-unicode-256colors
First try in terminal 
highlight --out-format=xterm256 --line-numbers --style=leo some.file
All good
![2015-05-14 14 46 46](https://cloud.githubusercontent.com/assets/1912842/7631234/1b515204-fa48-11e4-9ea3-e8b97dca19f7.png)
add this in scope.sh
highlight --out-format=xterm256 --line-numbers --style=leo "$path" | head -n $maxln
And when i try looked this file view window all time blinked without colors.
Whats wrong?

**Comment by hut** [comment]
maybe your TERM environment variable is wrong? Mine is `rxvt-unicode-256colors` and it works fine.

**Comment by kobzar** [comment]
i try many combination but not working

**Comment by nfnty** [comment]
Same issue as #547.
