### ISSUE TITLE
FreeBSD 10.1 Warning:Subwindowsizeoutofboundsfor<BrowserView>(x=0,y=29864864,hei=51,wid=99)  

### ISSUE THREAD

**Issue by demonking** [ranger/ranger#317]
I have a problem on my FreeBSD 10.1.

> ranger version: 1.7.1, executed with python 2.7.9
> Locale: en_US.UTF-8
> Current file: /usr/home/demonking/Repository/ranger/build
> Traceback (most recent call last):
>  File "/usr/local/lib/python2.7/site-packages/ranger/core/main.py", line 139, in main
>    fm.loop()
>  File "/usr/local/lib/python2.7/site-packages/ranger/core/fm.py", line 338, in loop
>    ui.redraw()
>  File "/usr/local/lib/python2.7/site-packages/ranger/gui/ui.py", line 253, in redraw
>    self.poke()
>  File "/usr/local/lib/python2.7/site-packages/ranger/gui/displayable.py", line 238, in poke
>    displayable.poke()
>  File "/usr/local/lib/python2.7/site-packages/ranger/gui/widgets/browserview.py", line 362, in poke
>    self.resize(self.y, self.x, self.hei, self.wid)
>  File "/usr/local/lib/python2.7/site-packages/ranger/gui/widgets/browserview.py", line 275, in resize
>    DisplayableContainer.resize(self, y, x, hei, wid)
>  File "/usr/local/lib/python2.7/site-packages/ranger/gui/displayable.py", line 161, in resize
>    x, y, hei, wid), bad=True)
>  File "/usr/local/lib/python2.7/site-packages/ranger/core/actions.py", line 128, in notify
>    raise Exception(str(text))
> Exception: Warning: Subwindow size out of bounds for <BrowserView> (x = 0, y = 29864864, hei = 51, wid = 199)
> 
> ranger crashed.  Please report this traceback at:
> https://github.com/hut/ranger/issues

If it helps my Enviroment:

rxvt-unicode (urxvt)
Xorg 1.14.7

**Comment by hut** [comment]
Does it occur randomly or consistently? After some time, or right when you start ranger?

**Comment by demonking** [comment]
Everytime i start ranger.
i also have tried to start it with xterm etc, but no change

**Comment by nfnty** [comment]
Are you still experiencing this issue on `master`? Have you tested with Python 3?

**Comment by nfnty** [comment]
@demonking Are you still experiencing this issue when running on `master`?

**Comment by demonking** [comment]
@nfnty I will test it during the weekend, and give you a response :)
My system is now upgraded to FreeBSD 11, but I will give it a try.

**Comment by demonking** [comment]
@nfnty ok it works now, without problems :)
Seems like it worked without problems since 1.7.2 and with python 2.7.
You can close it.

**Comment by nfnty** [comment]
Great, thanks!
