### ISSUE TITLE
Don't display Git status as "good" if status is unknown

### ISSUE THREAD

**Issue by Freso** [ranger/ranger#348]
I'm using [etckeeper](https://etckeeper.branchable.com/) to keep track of /etc. This means that all of /etc is under Git "control", but /etc/.git is readable only by root (and I don't run `ranger` as uid 1). ranger currently shows all files under /etc as `√` (though /etc itself is shown as `√?`), even though ranger really doesn't have any idea about the status of the files (verified by it showing this "good" status for ignored and changed files too).

I would suggest that either it shows `√?` or `?` (to indicate that its a Git/VCS directory, but status isn't known) or nothing at all.

**Comment by hut** [comment]
cc @aroig

**Comment by aroig** [comment]
Hi,

I do not have time to look into this right now. I have a list of several things to improve in the vcs thing, and I'll add this to that list, for when I get the time!

Anyway, One thing you could do is disable vcs indicators for the offending directories.

    setlocal path=/etc vcs_aware false

In fact I do the opposite, and only enable vcs for the directories I'm interested in.

**Comment by hut** [comment]
> In fact I do the opposite, and only enable vcs for the directories I'm interested in.

Argh, why did I never think of that? That pretty much solves the performance problem for me, thanks man. And happy to hear that you're still alive and kicking. :)

**Comment by hut** [comment]
Can you please check with the most recent version of the master branch if this is still an issue?

**Comment by nfnty** [comment]
Fixed by #408.
