### ISSUE TITLE
Silver Surfer support

### ISSUE THREAD

**Issue by breerly** [ranger/ranger#349]
Seems like you could add fuzzy recursive searching with `ag` easily enough - what do you think?

**Comment by amerlyq** [comment]
See https://github.com/amerlyq/airy/blob/master/cfg/term/ranger/commands.py
Also take a look at corresponding aliases in rc.conf.
What you think? Want something more?

**Comment by nfnty** [comment]
Add your plugin to the [Wiki - Community plugins](https://github.com/ranger/ranger/wiki/Community-plugins).
