### ISSUE TITLE
images preview doesn't appear with method iterm2

### ISSUE THREAD

**Issue by YannMoisan** [ranger/ranger#350]
ranger 1.7.1. / iterm2 2.2.1

No preview appears when I'm on an image

Here is an extract of my conf
set preview_images true
set preview_images_method iterm2

**Comment by hut** [comment]
Don't see anything wrong with your config.

@kattrali any idea ?

**Comment by pengux** [comment]
Images preview does work for me through iTerm2, but not when using tmux.

**Comment by kattrali** [comment]
> any idea ?

@hut Image support is [only in iTerm 2.9+](http://iterm2.com/images.html), and does not work through tmux as far as I know.

**Comment by hut** [comment]
Thanks kattrali. So @YannMoisan, does upgrading to iTerm 2.9+ solve your issue?

**Comment by fenque** [comment]
ranger 1.7.1. / iterm2 2.9.20150313
in tmux images not showing.

**Comment by tasmo** [comment]
Still no images were shown with `ranger-stable 1.7.2` inside homebrewed `tmux stable 2.1` on `iTerm2 Build 2.9.20160217`. Outside tmux it works very well.

**Comment by hut** [comment]
For your information, I feel no responsibility to fix image preview issues and rely completely on fixes in w3m, tmux, the terminals, and your contributions.

It doesn't hurt to report these problems here, but ranger only uses an external interface (which is a dirty hack, btw), and rarely it's actually rangers fault that things break.

**Comment by nfnty** [comment]
Continue this discussion in #539.
