### ISSUE TITLE
Changing directory causes difficulty

### ISSUE THREAD

**Issue by rreusser** [ranger/ranger#361]
Ranger is great! But here's the single biggest difficulty I have with it: If I navigate to, say, `app/models/post.js`, open it in vim, and want to split it with `app/controllers/post.js`, the vim command is:

`:sp ../../app/controllers/post.js`

instead of

`:sp app/controllers/post.js`

I can never keep track of how many `..`s to use, so I often just ditch ranger. Is it possible to disable the directory change or effectively preface the editor command with a cd to the directory in which ranger was started?

**Comment by hut** [comment]
Nothing like that is implemented in ranger at the moment. You could open vim in the project directory and then use ranger from vim to select files. See https://github.com/hut/ranger/blob/master/examples/vim_file_chooser.vim .

Although in my opinion that's inefficient. FYI, the way I do it would be something like `vim $(find . -name '*.js')`, then select the file I need with `:b filenam<tab><tab>` in vim.

**Comment by nfnty** [comment]
Use vim plugin [vim-rooter](https://github.com/airblade/vim-rooter).
