### ISSUE TITLE
<c-h> fails if old cwd doesn't exist

### ISSUE THREAD

**Issue by adam8157** [ranger/ranger#366]
reproducing steps:
1, browse ~/foo
2, jump to another directory via mark
3, rmdir ~/foo in another shell
4, <c-h>

it will pop error "no such file or directory ~/foo" and fail to toggle hidden option.

**Comment by amerlyq** [comment]
Truly speaking, it fails much more often, however I didn't deduced exact pattern yet.
Some combo of urxvt+tmux+ssh with some simple workflow. 
Sometimes it simply urxvt+ssh or urxvt+schroot.

**Comment by krompus** [comment]
Ah, so this *is* a ranger bug? I use <c-h> and <c-l> for changing tabs. This isn't the end of the world, but it would be nice to have it back.

I was using ranger in termite without issue, and I only started seeing this behaviour when I started using tmux; I thought it was a tmux bug.
