### ISSUE TITLE
Support git repositories in symbolic link directories

### ISSUE THREAD

**Issue by omrihar** [ranger/ranger#380]
I tend to make many symbolic links to parts of large repositories in my home directory for fast access. When I open one of these directories, with `vcs_aware` set to `true`, ranger does not detect that I am in a git repository (since it does not find `.git` in the path as a subdirectory).

Git provides a command `git rev-parse --show-toplevel` that returns the path of the toplevel directory of a git repository if it is indeed a git repository, even from within symbolic links. (Same is true for mercurial with `hg root`.

I started implementing support for this in ext/vcs/vcs.py but ran into some problems. You can see what I did so far in my fork of ranger: https://github.com/omrihar/ranger/blob/master/ranger/ext/vcs/vcs.py#L108 where I used the abovementioned git command to check whether this is a git repository.

The problem is that the function `get_root`, which I modified, is used quite extensively throughout the file and changing its functionality has a large impact on how the vcs module works. I did not want to proceed changing it without a discussion on whether this is something that the ranger team is interested in. Should I pursue this venue and submit a pull request? Are you interested in implementing this yourselves?

**Comment by hut** [comment]
Sorry for the late reply.

The feature is indeed useful and wanted. Right now, though, there is a refractoring in progress by @nfnty (see https://github.com/nfnty/ranger), and it would make sense to wait until it's merged.

**Comment by nfnty** [comment]
Support for symbolic links has now been implemented. Try it out: [nfnty/master](https://github.com/nfnty/ranger)

**Comment by omrihar** [comment]
Looks really good! Thanks!!!
Do you plan on adding support for committing to the repository as in fugitive (with :Gstatus) or other addons similar to fugitive?

**Comment by nfnty** [comment]
Glad to hear!

You can leverage vim and fugitive directly from ranger with `map Gs shell vim -c 'call fugitive#detect(getcwd()) | Gstatus | wincmd k | bdelete' .` while in the repository.

**Comment by omrihar** [comment]
Seems fancy, but when I run this, first of all Gs only opens :shell in ex mode, and when I map it to some other combination (zg) I get a vim with two horizontally split windows, one with NERDTree and the other with nothing (empty file). I assume I should include the `.` at the end of the line? Perhaps `getcwd()` doesn't change to the current directory in ranger?

**Comment by nfnty** [comment]
Silly me, if you use the default mappings then Gs will not work (G is already bound to move to=-1); you have to map it to something else. Yes, the `.` at the end is needed (means current directory).

Right, Vim's default split behavior is different. Try `map zg shell vim -c 'call fugitive#detect(getcwd()) | Gstatus | wincmd j | bdelete' .` And if that doesn't work, try removing the `| wincmd j | bdelete` part and experiment with other combinations. It all depends on your vim configuration.

**Comment by omrihar** [comment]
Thanks! Changing `wincmd k` to `wincmd j` did the trick for me. Not sure why though, but my vim is quite heavily customized so it's probably due to that.

How about adding some of these fancy maps to ranger but commented out so that people can enjoy these examples? I will now set up also similar keybindings for pushing, pulling, etc...

One last question - I have an alias for the git log command: 
`alias gl='git log --graph --pretty=format:'\''%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%an %cr)%Creset'\'' --abbrev-commit --date=relative'`

Is there a simple way to add this to your plugin support so that I get a more concise git log when using the `:log` map you provide?

**Comment by nfnty** [comment]
Good idea. You should implement some good base mappings and send a pull request.

I'm probably going to remove all functionality that is better suited for the shell. Mappings is a better option.

**Comment by hut** [comment]
Can you please check with the most recent version of the master branch if this is still an issue?

**Comment by nfnty** [comment]
Fixed by #408.
