### ISSUE TITLE
Adding cbz/cbr previews.

### ISSUE THREAD

**Issue by shaggytwodope** [ranger/ranger#383]
Hi, I found a way to add previews for cbz/cbr comic archives. Not sure what the rules/views on this is.
In the scope.sh file in the case "$extension" in section you can add

cbz|cbr)
        try comicthumb "$path" "$cached" 600 && exit 6 || exit 1;;

comicthumb is provided by the mcomix package (most distros should have this), this works well for me wondering if this should be added to scope.sh and commented out or the wiki etc.

**Comment by nfnty** [comment]
Doesn't seem like anyone else is interested in this feature, so I'm going to close this.

**Comment by peterjschroeder** [comment]
I am interested in this, but it doesn't seem to work. $path and $cached seem to have been changed to ${FILE_PATH} and ${IMAGE_CACHE_PATH}, but even changing those doesn't help.

comicthumb works fine on its own.

**Comment by jakem72360** [comment]
@peterjschroeder I got it to work. It seems that ranger by default, expects the preview image to be a thumbnail (`${IMAGE_CACHE_PATH}` is a filename ending in `.jpg`). The solution I found was using ImageMagick to convert the PNG image created by comicthumb to a JPEG. This goes in the `handle_extension()` function in your scope script.
```
cbz|cbr)
    comicthumb "${FILE_PATH}" "${IMAGE_CACHE_PATH}" 600 &&
    convert "${IMAGE_CACHE_PATH}" "${IMAGE_CACHE_PATH}" && exit 6
    exit 1;;
```

**Comment by peterjschroeder** [comment]
@jakem72360 Thank you, but it still doesn't work for me. What ranger version are you using? There is no handle_extension() function in mine, it is just extension (which I tried in there). I also tried putting your code into preview_images and still nothing.

**Comment by toonn** [comment]
@jakem72360, ranger's actually fine with `png`s, you just have to change the name. So `mv "${IMAGE_CACHE_PATH}" "${IMAGE_CACHE_PATH%.png}.jpg" && exit 6` should work.

@peterjschroeder, you probably have an ancient `scope.sh`, get a new one with `ranger --copy-config=scope` (you probably have to move the old one out of the way first). If that doesn't help you're running an ancient version of ranger, current is 1.9.2 : )
