### ISSUE TITLE
Startup warning when trying to use only 2 columns.

### ISSUE THREAD

**Issue by mibli** [ranger/ranger#384]
So ranger throws warnings when trying to use 2 collumns like this

``` rc.conf
set column_ratios 2,3
```

result:

```
loading... Warning: Subwindow origin below zero for <BrowserColumn at level 1> (x = -1, y = 0)
```

I'm using ranger version 1.7.1, i3 window manager and termite (based on vte3-ng)

**Comment by thewildweasel** [comment]
I don't seem to be able to replicate this error. Is there anything else you can provide that you believe may be relevant?

**Comment by hut** [comment]
This bug happens sometimes under different conditions and I haven't been able to isolate the underlying problem yet :|

**Comment by dylanaraps** [comment]
I'm getting the same issue with 2 columns on Arch Linux with Ranger version 1.7.2. 

This is what I have my columns set to:

    set column_ratios 3,4

**Comment by nfnty** [comment]
Can't reproduce this issue. Request to reopen if you're still experiencing this issue on `master` or the latest release.
