### ISSUE TITLE
Ranger on OSX

### ISSUE THREAD

**Issue by andyph666** [ranger/ranger#394]
Does ranger work on tmux for anyone? I have gotten the iterm2 image viewer to work but it does not work in tmux. Also, have people managed to get the w3m image viewer to work in OSX? I can't seem to find any information on the w3m image viewer anywhere.

**Comment by amerlyq** [comment]
Image viewing works for me on Arch both inside and outside tmux for urxvt and st terminals.

**Comment by nfnty** [comment]
Continue discussion in #539.
