### ISSUE TITLE
Suggestion: mkrc command

### ISSUE THREAD

**Issue by alphapapa** [ranger/ranger#401]
I'm used to using Pentadactyl, and occasionally Vim (being mostly an Emacs user), and so I was looking for an `:mkrc` command to save settings that I change from within Ranger.  But I haven't been able to find one.

So IIUC, the only way to set settings permanently is to edit `rc.conf` manually?

If so, I would like to suggest such a command, to write the current config to a file.  :)

**Comment by lamarpavel** [comment]
One way to almost do what you want is to edit the rc file and immediately source it from ranger. There is a keybinding to do just that [in the wiki](https://github.com/hut/ranger/wiki/Keybindings).

**Comment by nfnty** [comment]
This is a bad idea. Trying to automatically save your config files will cause many problems in the long term when you don't understand how or why settings ended up there. It's much better to just edit your config files manually and source them, as previously mentioned.
