### ISSUE TITLE
Tab completion does not take %macros into account

### ISSUE THREAD

**Issue by Vifon** [ranger/ranger#460]
The tab completion provided by `Command._tab_directory_content` may create an invalid completion if the file contains %-s which would be then interpreted as macros. Of course it applies only to the commands that resolve macros.

**Comment by nfnty** [comment]
Can't reproduce this. Could you provide steps to reproduce?

**Comment by nfnty** [comment]
Test the branch `tab_completion_macros`.

**Comment by Vifon** [comment]
Works for me.
