### ISSUE TITLE
Really long relative symbolic link paths.

### ISSUE THREAD

**Issue by beanaroo** [ranger/ranger#465]
Case: I'd like to symlink to `~/.irssi/scripts/autorun/nm2.pl` from `~/.irssi/scripts/nm2.pl`. Using `pL` results in:

```
$ ls -l ~/.irssi/scripts/autorun/
lrwxrwxrwx user user nm2.pl -> ../../../../../irssi/scripts/nm2.pl
```

This is reproducable:

```
lrwxrwxrwx user user avatar.png -> ../../../../../home/user/Media/3TB_External/Documents/Personal/avatar.png
```

**Comment by beanaroo** [comment]
As per IRC discussion, "ranger uses the real path of the source and destination of the symlink."
I have udisk's /run/media/user/... symlinked to ~/Media. As well as my dotfiles.

Please close this if it is not considered a valid issue.

**Comment by nfnty** [comment]
Can't reproduce this issue. Request to reopen if you're still experiencing this issue on `master` or the latest release.
