### ISSUE TITLE
Image preview with ranger

### ISSUE THREAD

**Issue by Fnux** [ranger/ranger#472]
HI!

I actually have some issues with ranger and termite : 
- Without any compositor, it shows me a black image. [Here.](http://file.fnux.ch/files/020116/2d377c.png)
- With compton (basic conf, no transparence) it shows me my background instead of the image.

Any Idea ? Thank you !

**Comment by rhssk** [comment]
Your link seems to be dead. Anyways, I'm using Termite+Ranger+Compton (with transparency) too and I get weird image preview behavior as well. Sometimes they appear with weird stripes all over them, other times they don't appear at all or my background pops out as if suddenly transparency was 100%. I have tried it without compton running and while I don't get any image artifacts, black bars appear below images and don't disappear after navigating away. 
The weird thing is that my previous urxvt config is acting weird as well. It works well with transparency disabled but has the same problem as Termite with trans disabled/enabled.

**Comment by nfnty** [comment]
Report this issue to Termite devs. We can't do anything about this issue.

Also see #86.
