### ISSUE TITLE
How to cd one dir ?

### ISSUE THREAD

**Issue by lidaling** [ranger/ranger#478]
How to cd one dir after quit ranger or exec keys in ranger?

I have try `bash_automatic_cd.sh`,it seems does not work.

**Comment by hut** [comment]
how do you use it? is your shell actually bash?

**Comment by jakub-wojciech** [comment]
Not sure if I understand your question correctly but if you want to exit ranger in current directory in ranger, you can just use 'shift + s'. You won't close ranger but you will go to command line in that directory. If you want come back to ranger just use 'ctrl + d'.

**Comment by btstw** [comment]
Is there have alternative solution? suppose I don't want open a new shell, because sometimes I forget to comeback to ranger and open a new ranger, when I repeat this process things are going ugly.
You will get multiple ranger :(
