### ISSUE TITLE
line numbers for the main column

### ISSUE THREAD

**Issue by v1kn** [ranger/ranger#489]
A `set number` toggle for the main pane would improve precise movement and selection across the file system.  
Thank You

**Comment by Delapouite** [comment]
The `set line_numbers` option has been added in the PR above and will be released in the next version of ranger. I guess this issue can be closed now.

**Comment by v1kn** [comment]
great news.
when the new version is planned to land?

**Comment by nfnty** [comment]
In a couple of days.

**Comment by v1kn** [comment]
Looking forward to it.
Thank You.
