### ISSUE TITLE
video opens twice?

### ISSUE THREAD

**Issue by dimitrieh** [ranger/ranger#492]
Hi there just started using ranger alongside the newest version of iterm2

Got img previews enables and also video previews (these are static btw, should they play? or only show a thumbnail?)

However when opening a video it plays twice in mplayer!

also I put `export RANGER_LOAD_DEFAULT_RC="false"` in my prompt.zsh (does that look correct?) as i thought i might be loading the settings twice or so.

would love some help

**Comment by hut** [comment]
No idea what could cause that, but loading the configs twice has nothing to do with it. Did you change any settings? Maybe run `ranger --clean`

**Comment by nfnty** [comment]
This issue seems to have been caused by misconfiguration. Request to reopen if you're still experiencing this issue.
