### ISSUE TITLE
I'm trying to get mpd/mpc to handle audio files by default.

### ISSUE THREAD

**Issue by krompus** [ranger/ranger#497]
I've tried adding 

```
mime ^audio|ogg$, terminal, has mpc      = mpc insert -- "$@"
```

(and a few variations on that command)

to `rifle.conf`, but no dice.

The only way I can get it to work is by adding

```
map <C-i> shell mpc insert %s
```

to `rc.conf`, which works, but is very slightly less convenient. :)

Any ideas? Thanks!

**Comment by hut** [comment]
When you add the rifle.conf entry, is it listed in the menu when you press `r`? Maybe you only need to change the order by putting the line somewhere at the top

**Comment by krompus** [comment]
Whelp, this is very strange. I can't test it currently, because I'm having some difficulties with mpd/mpc; when I try `mpc insert musicfile.mp3`, I get "error adding musicfile.mp3: Not found". My mpd client works though, and so do my mpc commands for playback/playlist manipulation.

I'll get back to you if I manage to fix mpd/mpc, perhaps someone with a functional mpd/mpc setup could test in the meanwhile.

**Comment by krompus** [comment]
Oh wait. It's working again. That was weird.

Okay, I added the command, and I see it at the top (0) when I press `r`, but nothing happens after that; the file isn't added to my mpd playlist.

Same thing when I `:shell mpc insert musicfile.mp3`.

**Comment by hut** [comment]
Generally, mpc requires the full path of the file, starting at the MPD root, so it's not as straight-forward as you may think. Some googling or bash scripting should help you here.

**Comment by krompus** [comment]
Ah, disregard what I said before about `mpc insert musicfile.mp3` working. I was in my MPD root directory (`~/music/`), and I thought the add commands were working in the current directory.

Yeah, I guess it's not a ranger bug. I'll look into ways to hack in support.

Thanks!

**Comment by arkhan** [comment]
you can serve something like, this script is loaded as the background for the cover of dicso in urxvt

```bash
#!/bin/bash

# Script intended to be executed from ncmpcpp (execute_on_song_change
# preference) running from urxvt to set album cover as background image

MPD_CONF=~/.config/mpd/mpd.conf
MUSIC_DIR=$( cat "$MPD_CONF" | grep -v '#' | grep 'music_directory' | cut -d ' ' -f2 | awk '{print $2}' | sed 's/"//g' )
DARKEN=70

TMP=/tmp
COVER=/tmp/cover.jpg
IMG_REG=".*/.*\(Front\|front\|Cover\|cover\|Art\|art\|Folder\|folder\).*[.]\(jpe?g\|png\|gif\|bmp\)"

function reset_background
{
    # is there any better way?
    printf "\e]20;;100x100+1000+1000\a"
}

{
    album="$(mpc --format %album% current)"
    artist="$(mpc --format %artist% current)"
    file="$(mpc --format %file% current)"
    dir="$MUSIC_DIR/$artist/$album"
    if [[ -d "$dir" ]] ; then
        album_dir="$dir"
    else
        album_dir="$MUSIC_DIR/${file%/*}"
    fi

    [[ -z "$album_dir" ]] && exit 1

    covers="$(find "$album_dir/" -type d -exec find {} -maxdepth 1 -type f -regex "$IMG_REG" \; )"
    src="$(echo -n "$covers" | head -n1)"
    darkenimg="$TMP/darken.jpg"
    rm -f "$COVER" "$darkenimg"
    if [[ -n "$src" ]] ; then
        light="$((100 - $DARKEN))"
        convert "$src" -fill "gray${light}" +level ${light}%,${light}% \
            +matte "$darkenimg"
        composite "$darkenimg" -compose Multiply "$src" "$COVER"
        if [[ -f "$COVER" ]] ; then
            printf "\e]20;${COVER};100x100+50+50:op=keep-aspect\a"
        else
            reset_background
        fi
    else
        reset_background
    fi
} &

```

**Comment by krompus** [comment]
@arkhan I'm not sure how this could be used?

**Comment by hut** [comment]
@krompus check out https://github.com/hut/ranger/wiki/Keybindings#go-to-currently-played-song-in-mpd

**Comment by Miesco** [comment]
Hi, I wrote something for this!

https://github.com/Miesco/playwithmpd

**Comment by nfnty** [comment]
This seems to have been caused by misconfiguration. Reopen if you're still experiencing this issue.
