### ISSUE TITLE
Remember last directories and tabs when reopening ranger

### ISSUE THREAD

**Issue by vitalybe** [ranger/ranger#502]
It could be nice if Ranger would remember the open tabs when closing and reopening ranger.

**Comment by tbrodbeck** [comment]
I added the line `set save_tabs_on_exit true` in my config, but it does nothing at all. Is this only me?

**Comment by toonn** [comment]
@tbrodbeck, that's probably because you're closing ranger by repeatedly pressing `q`? Try `Q`.

**Comment by tbrodbeck** [comment]
For me `Q` does exactly the same thing as `q`. It simply closes one tab and they are still not restored

**Comment by toonn** [comment]
Hmm, maybe try `:quitall`?

**Comment by tbrodbeck** [comment]
Ok that works. :)
For some reason there was this line in my config by default: `map     Q quit!'
I just changed it `map     Q quitall`

**Comment by toonn** [comment]
Well, both `quit` and `quit!` *should* quit all the tabs according to the docs. Will find out what's up with that.

**Comment by tbrodbeck** [comment]
For `quit` and `quit!` are closing only one tab at a time.

**Comment by toonn** [comment]
Yep, hence my emphasis and the finding out what gives : )
