### ISSUE TITLE
Send command to a running instance

### ISSUE THREAD

**Issue by cirosantilli** [ranger/ranger#509]
E.g., I would like to change the current directory of a ranger instance from Gvim, without starting a new ranger instance.

**Comment by hut** [comment]
@vifon didn't you write something like this?

**Comment by Vifon** [comment]
Oops, sorry, I must have missed the initial notification.

**Comment by smackesey** [comment]
I've got the IPC plugin working but it's a little laggy (about 1 sec between the time I write to the FIFO and the time the command is executed). I think this is because of the threading mechanism? Any suggestions for eliminating the lag?

**Comment by nfnty** [comment]
Try decreasing the setting `idle_delay`.

**Comment by smackesey** [comment]
@nfnty Thanks, that worked! I set `idle_delay` to 200.
