### ISSUE TITLE
Odd behavior of find and enter

### ISSUE THREAD

**Issue by vimeitor** [ranger/ranger#515]
Hi!

Maybe it's just me, but I find a bit odd the way ranger behaves in the following case. Let's say I have 2 folders, one called "hello" and the other called "hello2". If I search for "hello", then press tab (so that I highlight hello2) and then press enter, I jump inside hello, instead of hello2. I don't think that's very wise. Is there a way I can change this behavior?

Thanks :-)

**Comment by hut** [comment]
That should not happen, what's your version and what command do you use for searching?

**Comment by vimeitor** [comment]
Hello!

Sorry for the delay. It actually happens when I press **f** and then the name of the folder. For example, https://asciinema.org/a/dgxl6qxajvrg3fettahndn7w6

Basically, enter gives preference to the text in the command line instead of the highlighted folder.

**Comment by nfnty** [comment]
Can confirm this behavior.

**Comment by nfnty** [comment]
Same issue as #281.
