### ISSUE TITLE
Managing files as root brings one CPU 100% load 

### ISSUE THREAD

**Issue by ghost** [ranger/ranger#525]
It's happeing very often when i run ranger as root and delete  or move files in root directories, or move files from /home to root directories, i don't know specific action and when i am done, after short time i discover that root python process loaded one CPU on 100% in infinite loop.

**Comment by gineadai** [comment]
I check this. Now i just open ranger as root and it load CPU on 100% instantly, even after a close already. It's spikes  on low CPU a litte and then go in infinite loop

**Comment by hut** [comment]
Can't reproduce. Anything else that seems suspicious? I/O usage? Does ranger seem to be doing anything?

**Comment by gineadai** [comment]
Latest from git. I just move file from hidden directory in /home to /etc as root and after i quit one CPU is loaded on 100%

**Comment by hut** [comment]
Maybe this will help you find the cause:
`strace ranger > /tmp/ranger-strace`

By looking at /tmp/ranger-strace, you can determine what ranger is doing.

**Comment by suhr** [comment]
Can you [flamegraph](http://www.brendangregg.com/flamegraphs.html) it? I've found this tools for Python:

1. https://github.com/evanhempel/python-flamegraph
2. https://github.com/nylas/nylas-perftools ([blog post](https://nylas.com/blog/performance))
3. https://github.com/nvdv/vprof
