### ISSUE TITLE
Move files to a directory

### ISSUE THREAD

**Issue by dufferzafar** [ranger/ranger#543]
I want to select some files, press a shortcut, enter the path of the directory and the files should get moved to it. The directory should be created if it doesn't already exist.

Is there a way to achieve this?

**Comment by mrogalski** [comment]
Put this into Your `rc.conf`:
```map gp console -p15 shell mkdir -p  ; mv %%s $_```
This creates the `gp` keybinding for that purpose, and uses shell magic to achieve it.  I don't know what Your shell is, but it should work.

**Comment by hut** [comment]
Nice trick. The proper way would be to write a python command, but that should work just fine

**Comment by Unode** [comment]
This is a bit old, but what I generally use is the bulkrename feature. Since that uses `mv` implicitly, if you prefix the filenames with a folder, they will be moved.

**Comment by mrogalski** [comment]
Does it create the directory when it doesn't exist, like mkdir -p?  I mean, I could easily add mkdir -p it in the generated shell script, but that makes it quite a lot of keystrokes to achieve, and I'm not counting the amount of keystrokes which are necessary to edit the bulkrename file.

**Comment by shyiko** [comment]
For what it's worth, a version with working Tab-completion:

> (add to ~/.config/ranger/rc.conf)

```
map <F6> eval fm.open_console('moveselected ' + fm.thisdir.path + '/')
```

> (add to ~/.config/ranger/commands.py)

```python
class moveselected(Command):
    """:moveselected <target_directory>"""

    def execute(self):
        cwd = self.fm.thisdir
        cf = self.fm.thisfile
        if not cwd or not cf:
            self.fm.notify("Error: no file(s) selected", bad=True)
            return
        files = [f for f in self.fm.thistab.get_selection()]

        target_dir = self.rest(1)
        if not target_dir:
            self.fm.notify("Error: target directory not specified", bad=True)
            return

        from os.path import join, expanduser, lexists
        from os import makedirs
        target_dir = join(self.fm.thisdir.path, expanduser(target_dir))
        if not lexists(target_dir):
            makedirs(target_dir)
        for f in files:
            self.fm.rename(f, join(target_dir, f.relative_path))


    def tab(self):
        return self._tab_directory_content()
```

**Comment by dufferzafar** [comment]
@shyiko Thanks.
