### ISSUE TITLE
Is it possible to display the bitrate of media files?

### ISSUE THREAD

**Issue by krompus** [ranger/ranger#545]

**Comment by hut** [comment]
Gonna have to write a line-mode class for this which parses mediainfo output or something. See https://github.com/hut/ranger/wiki/Custom-linemodes

**Comment by krompus** [comment]
TIL about custom linemodes.

Sweet; thanks!

**Comment by nfnty** [comment]
Add your plugin to [Wiki - Community plugins](https://github.com/ranger/ranger/wiki/Community-plugins).
