### ISSUE TITLE
empty markdown files fail to open in editor

### ISSUE THREAD

**Issue by bnvk** [ranger/ranger#554]
I've noticed a weird issue whereby hitting `Enter` on a `.md` file fails to open in the editor. It appears as though it attempts to open the file, but then jumps back to file manager view. I do have `ansiimd` configured for previews, perhaps this is a conflict with that?

**Comment by mrogalski** [comment]
See what program ranger uses to open markdown files.  Highlight any .md file in ranger, type r.  It should open a `:open_with` dialog with several options to choose from.  Check what's the first (default) option.

**Comment by bnvk** [comment]
Ah. More info. Doing what @mrogalski suggests, there is a difference in what `r` displays depending on if a file has content or not (as in just created with `touch` or such)

**File With Content**

```
0 |  "$EDITOR" -- "$@"
1 | "$PAGER" -- "$@"
```

**Empty File**

```
0 |  "ansimd" -- "$@"
1 |  "ansimd" -- "$@"
2 |  "ask" -- "$@"
3 |  "$EDITOR" -- "$@"
4 |  "$PAGER" -- "$@"
```

When I manually select `3` it opens fine in vim, and upon quitting `ranger` there is a node.js error which comes from `ansiimd` which is that file does not exist.

```
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '--'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/usr/lib/node_modules/ansimd/cli.js:12:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
```

I don't know enough about this level of IO to understand why `ansiimd` seems to think the file does not exist, but might investigate if I get some time!

**Comment by mrogalski** [comment]
The error seems to mean to me, that ansimd complains that it can't open the file `--`.  That is, You run the command `ansimd -- filename`.  `--` is a standard way of saying in bash: this is the place where we end option flags, stop parsing the rest as options.  This is extremely useful in a situation where You have files which start with `-` character.  More on this [http://www.dwheeler.com/essays/fixing-unix-linux-filenames.html#dashes](here).

Anyway, that's enough theory.  Now to fix this:  try removing the `--` from Your markdown configuration in `rifle.conf`.
Secondly, there are two `ansimd` choices in Your `:open_with` dialog, which seems to suggest to me that there might be two lines in Your `rifle.conf` that pertain to markdown files:  fix it in them both and probably delete one of them.
Three, the strange thing is that a file with content is not detected as a markdown file, and an empty file is -- that suggests something wrong with `rifle.conf` configuration.  If You need some help with it, please post it.

**Comment by bnvk** [comment]
@mrogalski you were correct on assuming the `--` were there, as I added the following two lines

```
!mime ^text, label editor, ext md|markdown = "ansimd" -- "$@"
!mime ^text, label pager, ext md|markdown = "ansimd" -- "$@"
```

Temoving the `--` and the second line didn't help. However, adding `md` to the following two lines of mimes seemed to work!

```
!mime ^text, label editor, ext xml|csv|tex|py|pl|rb|sh|php|md = "$EDITOR" -- "$@"
!mime ^text, label pager,  ext xml|csv|tex|py|pl|rb|sh|php|md = "$PAGER" -- "$@"
```

Thanks for your input and tip!

**Comment by mrogalski** [comment]
After removing the `--`, do You still get node.js errors after You quit ranger?  Or do You get the file contents printed to the standard output?
Also, add `markdown` to ext:
```
!mime ^text, label editor, ext xml|csv|tex|py|pl|rb|sh|php|md|markdown = "$EDITOR" -- "$@"
```

**Comment by bnvk** [comment]
@mrogalski yes, removing the `--` but before adding the `md|markdown` lines I get the following error when trying to `edit` a newly created (with `touch`) file

```
/bin/sh: 1: ansimd /home/user/Docs/git/checkout.md: not found
```

**Comment by mrogalski** [comment]
Could You please include the ansimd line of Your rifle.conf? My bet is that You are trying to run it like `"ansimd $@"` instead of `ansimd "$@"`.

**Comment by nfnty** [comment]
This seems to be a configuration problem. Reopen if you're still having this issue.
