### ISSUE TITLE
Starting ranger in just removed directory throws an exception

### ISSUE THREAD

**Issue by hahiserw** [ranger/ranger#558]
Nothing serious I think. But ranger throws an exception instead of handling it somehow.

To reporduce:

Console 1:
mkdir test

Console 2:
cd test

Console 1:
rmdir test

Console 2:
ranger

**Comment by mrogalski** [comment]
Seems straightforward to fix.

Thanks to You I had found this semi-related problem:
```sh
mkdir -p /tmp/a/b/c
cd /tmp/a/b/c
ranger
```

Now in a second console, do `rm -rf /tmp/a/`.  This doesn't cause an exception, but instead it silently prohibits the user from moving up one dir by `h`.  Ranger still works and I can still `cd`, but some kind of a message would be nice -- in such a situation mc creates a big red sign "Error: cannot change directory".
