### ISSUE TITLE
Using tabs with folders with katakana name causes the tab name to have random gaps in it

### ISSUE THREAD

**Issue by nonamethanks** [ranger/ranger#563]
This is a pretty minor issue, but still. 
Using tabs and entering a folder with title in katakana (it likely happens with other characters from non latin scripts too though i haven't tried it), the tab title's background color is not uniform.

This can be reproduced easily by naming a folder, for example, "キャラクター" (katakana for "character") and noting that ![this](http://puu.sh/phM2A/d4ccfdb999.png) this happens. In short, there's a random interruption in the green background when the tab with katakana name is selected. Having the second tab in katakana or in english changes the place in which the small gap appears, so it's probably character independent. For example if i use two folders with the same name as above, the gap will appears before タ.

It's also worth noting that the second folder's full name is "Various", not "Variou", however the last letter is pushed out of the terminal, likely because of the empty gap between キ and ャ.

I'm using the latest source and Arch Linux, and this is not a problem related to my fonts as I've reproduced this bug on a different laptop and with different fonts. Terminal is rxvt-unicode.

**Comment by hut** [comment]
Strange, since ranger.gui.bar uses WideString too, so it should handle wide characters properly... Which python version do you use?

**Comment by nonamethanks** [comment]
I use python 3.5.1-2, the latest version in the arch linux repositories.
