### ISSUE TITLE
Problem in border of ranger

### ISSUE THREAD

**Issue by ghost** [ranger/ranger#570]
my border in ranger
![2016-06-05-075751_1366x768_scrot](https://cloud.githubusercontent.com/assets/13744901/15893165/32e9c1be-2da8-11e6-8c4f-9d8aef80f2fe.png)
I has been try to change set draw_borders true.

**Comment by mrogalski** [comment]
My bet is on Your fonts.  Looking at Your dutfiles: 
https://github.com/noptx/dutfiles/blob/master/.Xresources
it seems that Your font is 
```
xterm*font : -benis-lemon-medium-r-normal--10-110-75-75-m-50-ISO8859-1
```
My bet is the iso8859-1 charset is causing this.
Change the font, see if it draws correctly.

**Comment by noptx** [comment]
i has been delete it and set agan to true but not change anything.
