### ISSUE TITLE
Ranger Doesn't Display Pictures With URXVT True Transparency...

### ISSUE THREAD

**Issue by Geyup** [ranger/ranger#571]
Hi,

I compiled ranger 1.7.2 from source, with w3m 0.5.3...

I'm not sure which version I had this file in, `commands_full.py` but is this still being used in 1.7.2?

This is the contents of my ~/.config/ranger;

`bookmarks  colorschemes  commands.py  rc.conf  rifle.conf  scope.sh  start.sh  tagged`

I just released that Ranger doesn't like True Transparency, and when enabled will not display the images.

These .Xdefaults settings cause the images to not display;

`URxvt.depth: 32`

But if you set it to `16` it works, but then you don't have any transparency in URXVT. But if you set it to `pseudo transparency` like below in .Xdefaults it works;

```
URxvt*transparent: true
URxvt*shading: 30
```

I start ranger from a script like below;

export W3MIMGDISPLAY_PATH=/usr/libexec/w3m/w3mimgdisplay
urxvt +tr -geometry 151x37 -e ranger

When ranger is open it appears on the bottom left saying;

`failed to execute w3mimgdisplay`

I ran ranger as; `ranger --debug` and when I went to where I have a picture folder, and as soon as I had one picture hightlighted ranger crashed and gave me this output;

> ranger --debug
> ranger version: 1.7.2, executed with python 2.7.5
> Locale: en_US.UTF-8
> Current file: /home/foo/Pictures/Barbican-Plymouth-Devon.jpg
> Traceback (most recent call last):
>   File "/usr/lib64/python2.7/site-packages/ranger/core/main.py", line 140, in main
>     fm.loop()
>   File "/usr/lib64/python2.7/site-packages/ranger/core/fm.py", line 342, in loop
>     ui.draw_images()
>   File "/usr/lib64/python2.7/site-packages/ranger/gui/ui.py", line 323, in draw_images
>     self.browser.columns[-1].draw_image()
>   File "/usr/lib64/python2.7/site-packages/ranger/gui/widgets/pager.py", line 97, in draw_image
>     self.fm.notify(e, bad=True)
>   File "/usr/lib64/python2.7/site-packages/ranger/gui/widgets/pager.py", line 93, in draw_image
>     self.wid, self.hei)
>   File "/usr/lib64/python2.7/site-packages/ranger/ext/img_display.py", line 65, in draw
>     self.initialize()
>   File "/usr/lib64/python2.7/site-packages/ranger/ext/img_display.py", line 60, in initialize
>     stdin=PIPE, stdout=PIPE, universal_newlines=True)
>   File "/usr/lib64/python2.7/subprocess.py", line 711, in **init**
>     errread, errwrite)
>   File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory

**Comment by mrogalski** [comment]
Does the file `/usr/libexec/w3m/w3mimgdisplay` even exist?

**Comment by Geyup** [comment]
>cd /usr/libexec/w3m
ls
cgi-bin  inflate  w3mimgdisplay  xface2xpm

**Comment by nfnty** [comment]
Did you find a solution to this issue?

**Comment by Vifon** [comment]
The new "urxvt" preview method should work in this case. On the other hand it won't work with the pseudo-transparency as both use the same mechanism.

`set preview_images_method urxvt`

**Comment by nfnty** [comment]
Request to reopen if you're still experiencing this issue on `master` or the latest release and the solution from @Vifon doesn't work.

**Comment by Geyup** [comment]
I'm not using ranger now, but if I get back to it, I'll be back to report...

**Comment by gutydan** [comment]
Tengo el siguiente error: 

ranger version: ranger 1.9.2
Python version: 3.7.7 (default, Jun  4 2020, 15:43:14) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
Locale: es_AR.UTF-8
Current file: '/home/gustavo/Descargas/e63et.png'

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 398, in loop
    ui.draw_images()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 404, in draw_images
    self.browser.columns[-1].draw_image()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/pager.py", line 116, in draw_image
    self.fm.notify(ex, bad=True)
  File "/usr/lib/python3.7/site-packages/ranger/core/actions.py", line 172, in notify
    raise obj
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/pager.py", line 111, in draw_image
    self.wid, self.hei)
  File "/usr/lib/python3.7/site-packages/ranger/ext/img_display.py", line 145, in draw
    input_gen = self._generate_w3m_input(path, start_x, start_y, width, height)
  File "/usr/lib/python3.7/site-packages/ranger/ext/img_display.py", line 209, in _generate_w3m_input
    raise ImageDisplayError('Failed to execute w3mimgdisplay', output)
ranger.ext.img_display.ImageDisplayError: ('Failed to execute w3mimgdisplay', [])

**Comment by toonn** [comment]
@gutydan, hablo solo un poco de español. Tienes que instalar `w3mimgdisplay`, en RHEL puede que se llama "w3m-img."

**Comment by gutydan** [comment]
Thanks, I already have w3m-img installed but the problem continues. I found that switching the console to urxvt works fine, but not with xfce4-terminal.

**Comment by toonn** [comment]
You'd have to use the w3m previewing method of course. The urxvt method will only work in urxvt.
