### ISSUE TITLE
Emit a signal when task finished

### ISSUE THREAD

**Issue by TheOneValen** [ranger/ranger#580]
Hi!

I would like to propose a feature:

It would be nice if it is possible to have a signal emitted when a task from the queue is finished.

Greetings,
Valen

**Comment by hut** [comment]
`fm` now emits 'loader.before', 'loader.after' and 'loader.destroy' signals. The information passed to the signal is `signal.fm` = the FileManager object, and `signal.loadable` will be the Loadable object. Is that suitable?

**Comment by TheOneValen** [comment]
That sounds good. I'll try that. Thanks!

**Comment by TheOneValen** [comment]
Yeah. Exactly what I needed. Is there a way to filter the events nicely? Or must I use the description.

**Comment by hut** [comment]
Not really. What kind of metadata would you need?

**Comment by TheOneValen** [comment]
I want to execute a notify-send only at moving and copying operation. I used the description and searched a substring. But further investigation and understanding leads me to believe I can just check the type of the instance of the loader class to distinguish.

I think I also will be able to write my own loader for uploading stuff to my nexctloud (owncloud) server (with a nice progress bar :-) ). Is there a place I can share my custom stuff. Maybe someone else is interested, too.

Thanks!
Valen

**Comment by nfnty** [comment]
Update the [Wiki - Community plugins](https://github.com/ranger/ranger/wiki/Community-plugins).
