### ISSUE TITLE
Open terminal with additional options

### ISSUE THREAD

**Issue by abrodkin** [ranger/ranger#613]
I'd like to open new terminal from ranger (for example with command like ```:terminal```) but not in a separate window as it happens now but in a new tab (let's assume I use terminal that supports tabs like gnome-terminal, roxterm etc).

For example in case of roxterm it's possible to execute it like ```roxterm --tab``` and new tab will appear instead of new window.

I tried to set TERMCMD to ```roxterm --tab```  but then ```xterm``` gets executed at all (I think that's because ```roxterm --tab``` could not be found in PATH by ```get_executables()```).

Any thoughts on how that might be achieved?

**Comment by Vifon** [comment]
A quick solution would be to outright hardcode it in your `commands.py`. It's designed to be customized by the user (just remember to merge with upstream every half a year or so).

**Comment by abrodkin** [comment]
Yeah that's the possibility indeed but given that feature could be useful for other as well I started this discussion.

Moreover a little-bit less invasive (i.e. involving no modification of stuff that might be installed by user's distribution) is to setup a new mapping in ```~/.config/ranger/rc.conf``` like this:
```
map XX shell myterm --tab
```

And probably that's the ultimate solution for my initial request.

**Comment by Vifon** [comment]
If we check only the first part of the command for existence in PATH in `get_executables()`, your initial solution should work. I'll try get around to it tonight.

**Comment by abrodkin** [comment]
Right that what I was thinking about. But given ```ranger``` is not the only app that relies on ```TERMCMD``` we need to make sure we're not tempting user to set it with something improper so other users of ```TERMCMD``` won't suffer.

**Comment by Vifon** [comment]
It should work. [Here][1] they suggest to set `TERMCMD` to `xterm -T "$TERMWINDOWTITLE"`, among other things. Sounds good to me.

[1]: http://www.openembedded.org/wiki/Devshell

**Comment by abrodkin** [comment]
Good then. Thanks for your prompt reaction. Appreciate it a lot!

**Comment by Vifon** [comment]
Could you test the version referenced by my pull request? I've tested it myself but I want to be sure.

**Comment by abrodkin** [comment]
Hm, probably I'm doing something wrong.
I cloned your ```vifon/open_terminal_with_options``` branch locally, see:
```
git status 
On branch open_terminal_with_options
Your branch is up-to-date with 'vifon/open_terminal_with_options'.
nothing to commit, working directory clean

git log --oneline -n 5
58251ee Refactor and improve the TERMCMD handling
a9a75dd Merge branch 'import' of https://github.com/stepshal/ranger
e11d698 Merge branch 'misspellings' of https://github.com/stepshal/ranger
2390570 Fix misspellings
fbdb5b4 Put imports on separate lines.
```

Now I set TERMCMD and run ```./ranger.py```
```
export TERMCMD="roxterm --tab"
./ranger.py
```

But for me behavior is the same as it used to be. If ```TERMCMD="roxterm --tab"``` then ```xterm``` get started on ```:terminal``` command. If ```TERMCMD=roxterm``` then roxterm in a separate window appers.

What looks strange to me I tried to add logging in get_term() or put a breakpoint in pdb in the same function but to no avail.

To make sure I'm not running something else I removed ranger installed in my distro but still behavior is the same.

Please pardon this noise but I'm very new to Python and probably I'm bumping into some obvious thing.

**Comment by Vifon** [comment]
Try running ranger with `./ranger.py -c` to ignore the local config. Your `commands.py` may be overriding the new default one.

**Comment by abrodkin** [comment]
When runing ```./ranger.py -c``` on attempt to execute ```:terminal``` I'm getting the following message in red:
```
global name 'os' is not defined
```
and nothing happens.

**Comment by Vifon** [comment]
Ok, so I've broken something. Hm... Why did I not notice it...? Try now (force push, because my mistake was just too silly :P).

**Comment by abrodkin** [comment]
Cool! Indeed now (but only with ```-c``` flag for some reason) when ```TERMCMD="roxterm --tab"``` new tab gets created.

Thank you so much for adding that new feature!

**Comment by Vifon** [comment]
It works only with `-c` because it makes ranger ignore your local config, which may contain an outdated version of the `:terminal` command.

**Comment by abrodkin** [comment]
Right, I do see that there's a local copy of ```commands.py``` in my ```~/.config/ranger/```.

**Comment by Zeioth** [comment]
if you found the solution post it.

**Comment by toonn** [comment]
@Zeioth, this particular problem was an old copy of `commands.py`.
