### ISSUE TITLE
Freeze when config files are missing

### ISSUE THREAD

**Issue by klonuo** [ranger/ranger#616]
I run Bash shell on [WSL](https://blogs.msdn.microsoft.com/wsl/2016/04/22/windows-subsystem-for-linux-overview/). Things like tmux, mc etc all work fine. As I was occasionally using ranger on Ubuntu box thought to try it here. I cloned this repo and when I launch ranger I just get non-responsive screen. Damn, I thought it must be using some syscall not currently implemented by WSL. Then looking for switches to try and log the offender, `-c` showed as savior as with it ranger runs just fine. So after I run `ranger --copy-config=all` everything seems fine.

I just thought to drop by and let you know, that for some reason if config files are not generated ranger freezes the terminal on WSL, which may seem like it's not working, while it just needs proper config files.

**Comment by Vifon** [comment]
Could you post the output of `echo $RANGER_LOAD_DEFAULT_RC`? It's a known feature/issue that the default config is not loaded if this variable is set to `FALSE`.

**Comment by klonuo** [comment]
Yep it is like you said:
```bash
$ echo $RANGER_LOAD_DEFAULT_RC
FALSE
```
Does ranger set this variable after installing?

**Comment by klonuo** [comment]
> Does ranger set this variable after installing?

Wow, it's in my .bashrc for some reason unknown to me. I copied this file from my cygwin...
So this is false alarm...
