### ISSUE TITLE
rc.conf travel alias has both case insensitive and smart case options

### ISSUE THREAD

**Issue by jdietrch** [ranger/ranger#620]
In ranger/config/rc.conf there is this line:

`alias travel scout -aefiklst`

Notice that scout receives both the `i` (case insensitive) and the `s` (smart case) options. This confused me at first because I saw the `s` and wondered why it wasn't matching case when I used upper case letters. I would recommend taking out the `i`, which would change the line to this:

`alias travel scout -aefklst`

Thank you,
James

**Comment by nfnty** [comment]
Thanks.
