### ISSUE TITLE
Can't install via pipsi

### ISSUE THREAD

**Issue by dufferzafar** [ranger/ranger#621]
I use [pipsi](https://github.com/mitsuhiko/pipsi) to install a lot of my python based tools to their own virtualenvs. The tool is just great!

But I couldn't install ranger using it. I'm actually on a mac that I don't have root permissions on, so I can't use brew etc to install this.

Here's the error that gets thrown:

```
$ pipsi install ranger

Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /Users/szafar/.local/venvs/ranger/bin/python
Installing setuptools, pip, wheel...done.
Collecting ranger
  Downloading ranger-0.10.tar.gz
Building wheels for collected packages: ranger
  Running setup.py bdist_wheel for ranger ... done
  Stored in directory: /Users/szafar/Library/Caches/pip/wheels/8e/4a/6d/84e46bf70821288f73aa010d9b76a6c60a7eca9dfb32406ebe
Successfully built ranger
Installing collected packages: ranger
Successfully installed ranger-0.10
Did not find any scripts.  Uninstalling.
```

Please see if this can be fixed!

**Comment by mrogalski** [comment]
First of all, You are installing a different ranger: https://pypi.python.org/pypi/ranger 
Even the version sounds too old to be true:  latest release of our ranger is 1.7.2, and You are installing 0.10 .

**Comment by dufferzafar** [comment]
@mrogalski My mistake. Sorry!

I succeeded in installing ranger using: `pipsi install git+https://github.com/hut/ranger.git/#egg=ranger`

Thanks for your prompt response.
