### ISSUE TITLE
navigation slows down when copying files

### ISSUE THREAD

**Issue by adrsta** [ranger/ranger#625]
simple hjkl navigation becomes first very slow
and then completely unresponsive
when copying a large folder is in progress
I tested with 2GB folder

after the copying is finsihed (progres bar works fine)
then ranger is responsive again

tested on:
ranger-stable 1.7.2
Python 3.5.1 (default, Mar  3 2016, 09:29:07) 
[GCC 5.3.0]

**Comment by nfnty** [comment]
Continue discussion in #151.
