### ISSUE TITLE
Should be able to run ranger --copy-config from shell script

### ISSUE THREAD

**Issue by binaryphile** [ranger/ranger#626]
This used to be possible, so that as part of my initial system setup on a new machine I could run a script which populates the .config/ranger directory with the default files appropriate for that version, which I can then patch with my modifications from the same script.

Now it errors with the message that ranger must be run from a terminal.  I can understand why it does that, but non-interactive options such as copy-config should be excepted from that test.

**Comment by Vifon** [comment]
While your point is 100% valid, did you try to keep only your personal changes in your config? The global one will be loaded too so unless you want to remove something from the default config, it should work that way.

That being said, ranger indeed shouldn't require a terminal in such case.

**Comment by binaryphile** [comment]
I will try that, thanks.

**Comment by nfnty** [comment]
I can't reproduce this issue on `master`. @Vifon solution is a much better way of handling the config files otherwise.
