### ISSUE TITLE
Music player for ranger with mpd

### ISSUE THREAD

**Issue by Miesco** [ranger/ranger#630]
[https://github.com/Miesco/playwithmpd](https://github.com/Miesco/playwithmpd)

Hit `a` to add add current selected song/songs to playlist.

Hit `enter` to queue and play currently selected song/songs.

If song is not in mpd, it adds it to a temporary directory and then adds it to
the mpd database seamlessly.  Supports mpd in user mode and system mode.

**Comment by nfnty** [comment]
Add your script here: https://github.com/ranger/ranger/wiki/Integration-with-other-programs

**Comment by indeedwatson** [comment]
The original link is dead and it seems the script wasn't added to the scripts page, that's a shame.

**Comment by toonn** [comment]
@indeedwatson, indeed, Watson. I'm sure someone'd lend a hand over in #ranger@freenode if you want to try to come up with similar functionality though.
