### ISSUE TITLE
Execute python function everytime I change directory

### ISSUE THREAD

**Issue by dufferzafar** [ranger/ranger#631]
Is there some way to hook into ranger's directory changing system so that my python function gets called whenever a directory is changed - either by using `cd` command or by changing it from ranger's fileview.

I want to update [autojump's](https://github.com/wting/autojump) database from within ranger.

``` python
def on_directory_change(directory):
    "Update autojump's database."
    subprocess.call(["autojump", "-add", directory])
```

**Comment by fiatjaf** [comment]
Yes, you can add a plugin that binds to a hook: https://github.com/ranger/ranger/wiki/Signals-and-Hooks
