### ISSUE TITLE
cmap ` <esc>

### ISSUE THREAD

**Issue by sassanh** [ranger/ranger#634]
Unfortunately none of these work:
```
cmap ` <esc>
cmap ` <c-c>
cmap a <esc>
```
Without first line, pressing `` ` `` prints `` ` ``, after adding first line or second line pressing ` does nothing (but doesn't get out of console mode)

**Comment by mrogalski** [comment]
```copycmap <ESC> ` ```

**Comment by hut** [comment]
Yep, cmap binds to commands, not to other key combinations.

**Comment by sassanh** [comment]
Thanks
