### ISSUE TITLE
AttributeError: 'UI' object has no attribute 'win'

### ISSUE THREAD

**Issue by dfritchman** [ranger/ranger#635]
I consistently hit this error:

[ranger-1.7.2] $ ranger
ranger version: 1.7.2, executed with python 2.7.9
Locale: en_US.UTF-8
Current file: None
Traceback (most recent call last):
  File "/Users/dan/pkgs/ranger-1.7.2/ranger/core/main.py", line 121, in main
    fm.initialize()
  File "/Users/dan/pkgs/ranger-1.7.2/ranger/core/fm.py", line 118, in initialize
    self.ui.initialize()
  File "/Users/dan/pkgs/ranger-1.7.2/ranger/gui/ui.py", line 60, in initialize
    self.win.leaveok(0)
AttributeError: 'UI' object has no attribute 'win'

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
## 

Whenever attempting to run ranger on my Mac.

**Comment by nfnty** [comment]
Try `master` and report back.

**Comment by nfnty** [comment]
Open a new issue with more details if you're still having this issue on `master`.

**Comment by mrjnox** [comment]
I get the same error, though only when I launch urxvt on a Linux system, SSH to my Mac, and then try to launch Ranger. `echo $TERM` gives a result of `rxvt-unicode-256color`, and If I `export TERM=xterm` in my SSH session, ranger launches fine. There are no issues running a local instance of ranger on either my macOS or Linux systems.
