### ISSUE TITLE
Problem with spawned process

### ISSUE THREAD

**Issue by Enrico68** [ranger/ranger#636]
When I try to spawn a shell command (e.g with `!`) the cursor position will be near the command name instead a space further. This is a better example of what is [happening](http://i.imgur.com/qbtGq9u.gif). OSX 10.9.5 Iterm2

**Comment by Vifon** [comment]
Do you have a trailing space in the line responsible for this key? It should be either `map ! console shell ` (with a trailing space) or `map ! console shell%space` (only in the newer ranger versions).

**Comment by Enrico68** [comment]
Thanks, and sorry for this silly question !
