### ISSUE TITLE
Toggle between viewmodes miller and multipane ?

### ISSUE THREAD

**Issue by vdun** [ranger/ranger#638]
How to make a keyboard map that would toggle between: `set viewmode miller` and `set viewmode multipane` ?

**Comment by hut** [comment]
recent versions have borrowed the "!" keyword from vim to toggle options, so this would work: `set viewmode!`

It's also bound by default to `~`.

**Comment by vdun** [comment]
Thanks

**Comment by hut** [comment]
Theres still a bug that makes the cursor disappear on changing the viewmode though. It's a known issue, in case you're wondering. Just opened an issue about it: #639.
