### ISSUE TITLE
sqlite3 viewer in ranger?

### ISSUE THREAD

**Issue by arjamizo** [ranger/ranger#640]
Hello

is there any chance of having sqlite3 database viewer in ranger?

**Comment by arjamizo** [comment]
sth like this http://psankar.blogspot.com/2011/01/introducing-sqlite-commander-curses.html ... but not in `cs`

**Comment by mrogalski** [comment]
Following is a quick and dirty hack.  Use at Your own discretion and risk.
To preview every *.sqlite file, You can add the following to the 
```case "$extension" in```
in Your scope.sh:
```
    sqlite)
        sqlite3 "$path" "SELECT name FROM sqlite_master WHERE type='table';" | xargs -I {} sh -c 'echo "\n{}:" ; sqlite3 '"$path"' -header -column "SELECT * FROM {};"' ; exit 0;;
```
You can also substitute xargs for GNU parallel or something to speed it up a bit.  Or do something about field widths -- they sometimes suck.  You want to format it better?  Add some options to `sqlite '"$path"'`, right now there is `header` and `column` turned on.
You can also try to find the mimetype of sqlite databases and then add this to `case "$mimetype" in`, but for some reason I couldn't make it to work there -- file returns "application/octet-string" or something equally useless.
