### ISSUE TITLE
Git (VCS?) support not working

### ISSUE THREAD

**Issue by benutzer193** [ranger/ranger#641]
Running ranger-git from AUR.

When the VCS option is enabled ranger throws an error and doesn't show any git features in git repositories.
Python raises the following exception:

       ".../python3.5/threading.py" line 914: in _bootstrap_inner self.run()
    => ".../ranger/ext/vcs/vcs.py" line 456: in run self._queue_process()
    => ".../vcs.py" line 434: in _queue_process if rootvcs.update_root():
    => ".../vcs.py" line 238: in update_root self.head = self.data_info(self.HEAD)
    => ".../vcs/git.py" line 185: in data_info log = self._log(refspec=rev)
    => ".../vcs/git.py" line 70: in _log line = json.loads(line)
    => ".../python3.5/json/__init__.py" line 319: in loadsauth return _default_decoder.decode(s)
    => ".../python3.5/json/decoder.py" line 339: in decode obj, end =self.raw_decode(s, idx=w(s, 0).end())
    => ".../python3.5/json/decoder.py" line 355: in raw_decode obj, end = self.scan_once(s, idx)

    json.decoder.JSONDecodeError: Invalid control character at: line 1 column 169 (char 168)

_(I had to type by hand because the Exception was printed on top of ranger and couldn't be redirected to a logfile, so I hope I didn't miss anything.)_

**Comment by benutzer193** [comment]
okay found a fix and will make PR, but I leave it open, perhaps there is the same problem in other VCS extentions?

**Comment by nfnty** [comment]
Does this happen in every repository, regardless of VCS type?

**Comment by nfnty** [comment]
Try my fix over at [nfnty/ranger](https://github.com/nfnty/ranger) and report back.

**Comment by benutzer193** [comment]
I'll try later. I only have one repository explicitely enabled to show VCS features. The repo is benutzer193/.dotfiles

**Comment by nfnty** [comment]
Wow, those are some nasty commit messages. Fixed with b236538, I'll create a new PR.

**Comment by benutzer193** [comment]
:laughing: pr #643  fixed it. Is there something like PEP 8 for commit messages...
