### ISSUE TITLE
Directory does not refresh contents 

### ISSUE THREAD

**Issue by Enrico68** [ranger/ranger#656]
`ranger-stable 1.7.2` on Mac OSX 10.9.5

Problem :  file does not show up on directory after downloading using Chrome.
How to reproduce: downloading a file you cannot locate using ranger. Changing directory does not fix it. Need to quit ranger

**Comment by Enrico68** [comment]
Forgot to tell the issue is with anaconda environment. Ranger is working flawlessly in the normal `MacPorts` Python.

**Comment by nfnty** [comment]
Will need much more debugging from your side if you want this resolved. Have you tested `master`?

**Comment by nfnty** [comment]
Open a new issue with more details if you're still having this issue on `master`.
