### ISSUE TITLE
percent % sign in command line

### ISSUE THREAD

**Issue by rafaqz** [ranger/ranger#660]
My mogrify commands have recently broken:

```
shell mogrify -resize 25% image.jpg
```

gives the error:
`('Unrecognized named group in pattern', re.compile('\n     \\%`` etc.

Looks like a python templating issue.

Cheers

**Comment by hut** [comment]
Yes, you need to escape %'s by writing %%. Oddly this is not described in the man page, I'll change that right away.

**Comment by rafaqz** [comment]
No this is another issue, im trying to pass 25% as an argument to mogrify, not using %s etc. But the percent sign breaks python. Escaping itdoesnt seem to work either...

**Comment by rafaqz** [comment]
Oh maybe  need to triple escape it for :console shell... I posted this as that same mogrify command used to work but stopped working, which seems weird.

**Comment by rafaqz** [comment]
I double checked and escaping a lone % without an s or f after it seems to be broken.

**Comment by mrogalski** [comment]
```:shell mogrify -resize 25%%%% image``` works for me
Seems like %'s need to be escaped twice.  Maybe first time for the interpretation of the string and the second time for the regexp?

**Comment by rafaqz** [comment]
Ok swapping to ranger-git fixed the issue on arch linux.

But :

`:shell mogrify -resize 25%%` doesn't work on ranger-1.7.2-1

not sure what happened there.

**Comment by nfnty** [comment]
Fixed in latest releases.
