### ISSUE TITLE
Suspending vim run from ranger breaks the screen

### ISSUE THREAD

**Issue by hahiserw** [ranger/ranger#663]
Steps to reproduce:
1. Navigate in ranger to some folder with files
2. Edit file with vim (e.g. by typing `r vim` and press enter)
3. Press `Ctrl+Z`
4. Type `fg`

Now, what you see looks like ranger, but is, in fact, vim. To exit blindly type `:q` and enter. Now you are in ranger, type `Ctrl+L` to refresh the screen.

It would be cool if pressing `Ctrl+Z` would suspend vim, and pressing it again would suspend ranger - just like in mc. After `fg` to ranger typing (for example) `fg` could go back to vim (or any other suspended program).

**Comment by mrogalski** [comment]
It's a known bug. See #160 and #615. 
Don't know how to fix.

**Comment by hahiserw** [comment]
Oh, didn't see these issues.
There has to be a way, because Midnight commander can do it.
I am not sure how this works, but I think there is something that could help in its source code: https://www.midnight-commander.org/browser/src/subshell/common.c

**Comment by Vifon** [comment]
I must add that the way Midnight Commander does it is completely different and causes a different set of issues. To see what I mean, try pressing <kbd>Ctrl+o</kbd> with Vim still open to return to mc and then press it again to get back to Vim.

**Comment by nfnty** [comment]
Continue the discussion in #160.
