### ISSUE TITLE
Search is not working if you build ranger in python 3.6

### ISSUE THREAD

**Issue by stepshal** [ranger/ranger#664]

**Comment by s3rb31** [comment]
Yes, I can confirm. 

Archlinux upgraded to Python 3.6 today. So be prepared for some more reports on this. :P

**Comment by sanaptejas** [comment]
I still have this issue. What do you advise I do?

**Comment by toonn** [comment]
@sanaptejas, what version of ranger are you running? This is definitely not an issue any more as far as I know.

**Comment by sanaptejas** [comment]
```
ranger-stable 1.7.2

Python 3.6.5 (default, Mar 29 2018, 18:20:46) 
[GCC 8.0.1 20180317 (Red Hat 8.0.1-0.19)]

```
