### ISSUE TITLE
Feature: option to make <enter> on directory behave as <enter> on file

### ISSUE THREAD

**Issue by cstrahan** [ranger/ranger#666]
Would it be possible/feasible to provide a way to have `<enter>` on a directory close ranger (while still honoring --chosefile(s) and such)? I have ranger integrated with my zsh config, with a key binding that allows me to use ranger to select files/directories to put into the current command line. It's a little awkward selecting a directory or two, and then having to find a file to hit `<enter>` on in order for ranger to write out the selected paths (because hitting `q` exits without writing the selected files).

Additionally, I generally just use the `l` key to descend into a directory anyway.

(And lest I forget, thanks again for ranger!)

**Comment by mrogalski** [comment]
rifle.conf:
`mime ^inode/directory = exit`
rc.conf:
`map <enter> open_with 0`

Does what is needed with --choosefile(s).  For normal ranger operation: `<enter>` opens the files with default program, does absolutely nothing on directories.
Tried this on ranger-stable 1.7.2.

**Comment by cstrahan** [comment]
Ah, passing `--cmd 'map <enter> open_with 0'` does what I need - thanks! That still leaves the following curiosity: the selections are only written _if_ I stay within the same directory. If I select some files/directories and then navigate to a different directory, the selections won't be written. That might be worth opening a separate issue...

**Comment by cstrahan** [comment]
I opened an issue for that last problem here: #667
