### ISSUE TITLE
--choose* flags only work when selecting files within $PWD

### ISSUE THREAD

**Issue by cstrahan** [ranger/ranger#667]
I'm doing something like the following:

```
echo >! paths.txt; ranger --choosefiles paths.txt; cat paths.txt
```

As long as I stay within the current working directory, can select files with `<space>` and they'll be printed out when I hit `<enter>`.

If I type `h` to go to the parent directory and select files, they _won't_ be written to `paths.txt`.

This is on ranger 1.7.2 with python 2.7.11.

**Comment by mrogalski** [comment]
Check the pull request #668 if it suits Your needs and for possible bugs. 
Is the order of paths an issue?  Because right now You will get them in an unsorted way.

**Comment by cstrahan** [comment]
For my needs, the order isn't important. I would suggest documenting that the order is currently undefined, allowing one to revisit the code and preserve the original selection order without fear of breaking people's expectations.

**Comment by mrogalski** [comment]
You mean documenting in code and/or manpage?

**Comment by cstrahan** [comment]
Correct -- just so no one somehow depends on the undefined order (granted, an unlikely scenario).

**Comment by cstrahan** [comment]
@nfnty Thanks for merging! Would it be possible to drop a new point release relatively soonish? :wink:

**Comment by nfnty** [comment]
A new release may take some time due to major changes to the codebase. Needs to be tested thoroughly.
