### ISSUE TITLE
ranger in tmux: weird behaviour

### ISSUE THREAD

**Issue by joe9** [ranger/ranger#67]
Hello,

I notice this weird behaviour when using ranger 1.5.5 with tmux.

This is the screenshot that explains the issue:  http://imgur.com/xSS5wnq

On the left is ranger in tmux and in the middle is ranger opened in a terminal (rxvt-unicode).

Please let me know if you need more details.

Thanks
Joe

**Comment by jkoz** [comment]
I was wondering you guys find out how to display image on tmux inside st terminal. I have problem with this too.

**Comment by mvrozanti** [comment]
@jkoz Can confirm. Images are rendered fine in `st` alone but not with `tmux`

**Comment by Vifon** [comment]
The images previews in `tmux` are very unreliable and not much can be done currently. They can work under right circumstances but it's basically a gamble.

**Comment by jakeogh** [comment]
Can the unreliability of image preview be expanded on? What's the base issue? In #1192 it's mentioned that w3m is unreliable by design. How so?

**Comment by mvrozanti** [comment]
For what's worth, I moved from w3m to ueberzug and haven't haven't had any more problems since

**Comment by jakeogh** [comment]
That worked! I set "set preview_images_method ueberzug" and the problems are gone. https://github.com/jakeogh/jakeogh/blob/master/dev-python/ueberzug/ueberzug-9999.ebuild

**Comment by toonn** [comment]
This is because ueberzug simply draws a window over the terminal. I think you'll find it doesn't interact well with split tmux windows. Afaik so far there is no image previewing method that is completely compatible with tmux. Displaying images in a terminal has been and remains a hacky enterprise.
