### ISSUE TITLE
Support vim-like macros

### ISSUE THREAD

**Issue by elvis-sik** [ranger/ranger#670]
I mean the `q` ones. I don't know how others would feel about this, but it would be useful for me. Sometimes I have to do a repetitive task just a couple of times, such that it isn't worth the effort to hack a script for it. Automating (at least parts of) these tasks is the main use case for me.

**Comment by mrogalski** [comment]
You can `chain` commands together and bind them to a key.  I mean, obviously, It takes time to spell them out, but this has at least some macro-like capability.

**Comment by nfnty** [comment]
This would be very complex, for very little gain over `map` and `chain`. PRs are welcome.

**Comment by elvis-sik** [comment]
I spent some time throughoutly reading the ranger docs at some point in the past few months. I became more proficient in it. I haven't felt like it would be nice to be able to use macros ever since.

**Comment by nfnty** [comment]
Alright.
