### ISSUE TITLE
Allow to map the Enter key

### ISSUE THREAD

**Issue by rightaway** [ranger/ranger#672]
To delete a file, when I press `dD` (mapped by default to `map dD console delete`) the ranger console shows `:delete`. I then have to press Enter to submit the command. And because I have `confirm_on_delete` set to true, I have to press Enter again. So to delete a file I have 4 keystrokes d, D, Enter, Enter. Instead I'd like it to be d, D, Enter.

So when I press `dD` it should enter the command delete and Enter if I map it that way. Something  like `map dD console delete<enter>` or `map dD console<cr>` like in vim should be possible.

**Comment by mrogalski** [comment]
`map dD delete`
