### ISSUE TITLE
Fastest possible directory swapping: `z` (`j`, `yo`)

### ISSUE THREAD

**Issue by arjamizo** [ranger/ranger#673]
How could I integrate https://github.com/rupa/z into ranger? 

(rupa/z works like this that it tracks all the dirs and allows me doing very fast directory switching, so) 

if I type

```
z apache # it brings me to /etc/apache2
z s r l d # it brings me to /etc/apt/sources.list.d
```

How could you integrate this to ranger? 

 Some kind of a `post-change-dir` in ranger? and z command which shows `z` command output (and allows choosing)?

PS #659 seems similar

**Comment by nfnty** [comment]
I highly doubt that you'd be able to integrate that script into ranger, but you're welcome to send PRs.

**Comment by nfnty** [comment]
Continue the discussion in #659.
