### ISSUE TITLE
:set unavailable

### ISSUE THREAD

**Issue by zib0** [ranger/ranger#674]
When the ranger startup it display    

```
'set_' object has no attribute 'parse_setting_line_v2' 
```

 and the `:set` command in ranger is not available as well, give the same message. 
Use Homebrew installed the latest version on Mac 10.11.6, iterm2. Python is 2.7.12 and 3.5.2.

**Comment by nfnty** [comment]
This should be fixed with the latest releases and on `master`. Reopen if you're still affected by this issue.
