### ISSUE TITLE
macros embedded in filenames undergo expansion

### ISSUE THREAD

**Issue by antoxz** [ranger/ranger#680]
ranger-stable 1.7.0 (Python 2.7.11) expands macro-sequences embedded in filenames.

For example, create such file in shell:

```
touch foo-%d-baz
```

select it in ranger and execute:

```
:shell echo %s
```

Output:

```
foo-/tmp-baz
```

**Comment by antoxz** [comment]
This happens because class shell(Command) (./config/commands.py:189) inherits resolve_macros=True (./api/commands.py:82), and hence substitute_macros is first called from execute_console (./core/actions.py:175).  This means `:shell -p` (w/o more args) for cat'ting %s works as intended (./config/commands.py:201), and in other cases macro expansion is performed twice. Assuming this cat behavior is useful, I suggest to simply override resolve_macros=False, as follows:

    --- old/config/commands.py	2015-10-04 02:46:45.000000000 +0300
    +++ new/config/commands.py	2016-10-10 21:58:59.000000000 +0300
    @@ -188,6 +188,7 @@
     
     class shell(Command):
         escape_macros_for_shell = True
    +    resolve_macros = False
     
         def execute(self):
             if self.arg(1) and self.arg(1)[0] == '-':

**Comment by antoxz** [comment]
Oh, `escape_macros_for_shell` there won't control anything then, so:

    -    escape_macros_for_shell = True
    +    resolve_macros = False

**Comment by nfnty** [comment]
Can't reproduce on `master`. Reopen if you're still affected by this issue.
