### ISSUE TITLE
alias from fish-shell not working in ranger :shell

### ISSUE THREAD

**Issue by c02y** [ranger/ranger#684]
fish-shell is my default SHELL, the I got a lot function and aliases defined.

How can I make them working after **:shell**?

**Comment by nfnty** [comment]
Why would you ever want to do any interactive heavy lifting from the `shell` command? Just drop out to a real shell session when you need the full power of the shell. This is out of ranger's scope. It would be close to insanity to try to implement this in a compatible way. Shells are extremely complex. If you find a way to make this work then post a PR.
