### ISSUE TITLE
update_tmux_title bug

### ISSUE THREAD

**Issue by c02y** [ranger/ranger#685]
If I set **update_tmux_title** to **true**, the title of tmux will become "ranger" (this is expected), but after I exit ranger, the title of tmux will still be "ranger", it won't  change even after I execute other commands like vim. 

If I set **update_tmux_title** to **false** which is default, the title of tmux will be back to fish (I use fish as my SHELL) and vim a file will make the tmux display vim as the title (this is normal).

So this is bug.

**Comment by nfnty** [comment]
Duplicate of  #228.
