### ISSUE TITLE
How to restore back to ranger if I "S" inside ranger?

### ISSUE THREAD

**Issue by c02y** [ranger/ranger#686]
The man page of ranger mentions that I can type **S** inside ranger to temporarily enter into the shell, but it does not mention how to restore back to ranger.

After I have done my jobs in the shell, I cannot go back to the previous ranger, type **ranger** again will simply create a new instance of ranger, for instance, the multiple tabs will be gone, and if I search the process, there will be two instances of ranger.

So how to restore back to ranger if I "S" inside ranger?

**Comment by mrogalski** [comment]
type `exit`

**Comment by c02y** [comment]
Thanks.

**Comment by lamarpavel** [comment]
The reason for this is that ranger starts a new shell as subprocess, just like when you would type "bash" or "sh" inside your shell. To get back to the parent process, you will have to terminate the child. You could do this via `kill` or `pkill` or `htop` or simply by telling the running shell to exit. A shorthad for typing `exit` is to send the exit-signal via `ctrl-d` in most terminals/shells.

**Comment by c02y** [comment]
You can close this issues now.
