### ISSUE TITLE
Ability to use custom image previewers along with w3m previewer

### ISSUE THREAD

**Issue by krvkir** [ranger/ranger#691]
W3m previewer works great for file formats which it supports, but fails to render some formats (for example, .svg).
At the same time if one will turn off `preview_images` option in rc.conf and add something like

```
case "$extension" in
    svg|jpg|jpeg|bmp|gif|png)
        convert "$path" "$cached" && exit 6 || exit 1;;
```

into his scope.sh file, he'll get full color (not ascii) previews of images with the extensions listed (at least for me this is true, not sure how it works, maybe it ultimately uses w3m on thumbnails?). Unfortunately this is significantly slower than with w3m because it requires conversion of all the images before drawing.

It would be great if there was an ability to do this intermediate conversion only with images which w3m doesn't support, and use w3m directly on images which are supported.

What do you think?

PS Seems like my suggestion is kind of in contradiction with https://github.com/ranger/ranger/issues/263.

**Comment by Vifon** [comment]
I'm not sure about the current stable ranger but in the development version of ranger `scope.sh` controls all the previews: `preview_images` is checked here and can be overridden here. You can check for the extension before any other checks and if it's `.svg` you can do exactly what you do in your code above.

Does it make sense?

**Comment by krvkir** [comment]
Thanks for the response. I tried what you suggested: updated ranger to dev version and added this in `scope.sh` right after `preview_images` check:
```
    case "$extension" in
        svg)
            convert "$path" "$cached" && exit 6 || exit 1;;
    esac
```
It works, although it seems that thumbnails are still generated for non-svg files. The delay before selecting a file (both svg or non-svg image) and the moment when preview appears is ~1s at the first time and nearly 0 in all times after it. Am I doing something wrong or it's the expected behaviour?

**Comment by Vifon** [comment]
@GermainZ, could you take a look?

**Comment by GermainZ** [comment]
You're converting images w3m supports then displaying the conversion. That's the expected behavior for what you're doing (unless I'm missing something), but you probably don't want to do that in the first place.

If you want to display a format w3m supports directly, "exit 7" will do the trick. Check the comments at the top of scope.sh for more info.

So replacing `convert "$path" ...` with just `exit 7;;` should do what you want.

**Comment by nfnty** [comment]
Reopen if you still encounter this issue.
