### ISSUE TITLE
FileInfo Linemode crashes Ranger on Python 2.6

### ISSUE THREAD

**Issue by richboss** [ranger/ranger#695]
Ranger running on Python 2.6 crashes when switching to linemode 'fileinfo'. 

> ranger version: 1.7.2, executed with python 2.6.6
> Locale: de_DE.UTF8
> Current file: /tmp/ranger-master/doc
> Traceback (most recent call last):
>   File "/tmp/ranger-master/ranger/core/main.py", line 145, in main
>     fm.loop()
>   File "/tmp/ranger-master/ranger/core/fm.py", line 355, in loop
>     ui.redraw()
>   File "/tmp/ranger-master/ranger/gui/ui.py", line 295, in redraw
>     self.draw()
>   File "/tmp/ranger-master/ranger/gui/ui.py", line 322, in draw
>     DisplayableContainer.draw(self)
>   File "/tmp/ranger-master/ranger/gui/displayable.py", line 248, in draw
>     displayable.draw()
>   File "/tmp/ranger-master/ranger/gui/widgets/view_miller.py", line 99, in draw
>     DisplayableContainer.draw(self)
>   File "/tmp/ranger-master/ranger/gui/displayable.py", line 248, in draw
>     displayable.draw()
>   File "/tmp/ranger-master/ranger/gui/widgets/browsercolumn.py", line 168, in draw
>     self._draw_directory()
>   File "/tmp/ranger-master/ranger/gui/widgets/browsercolumn.py", line 348, in _draw_directory
>     infostringdata = current_linemode.infostring(drawn, metadata)
>   File "/tmp/ranger-master/ranger/core/linemode.py", line 100, in infostring
>     from subprocess import check_output, CalledProcessError
> ImportError: cannot import name check_output
> 
> ranger crashed.  Please report this traceback at:
> https://github.com/hut/ranger/issues

Apparently 'linemode.py' tries to import the function check_output from the subprocess module which was introduced in Python 2.7 and hence does not exist in an older Python version.

Upon inspection of the Ranger codebase I found a second spot in "ext\vcs\vcs.py" where check_output from the subprocess module gets imported.

A fix (at least a workaround) might be to include the backported function (see this [gist](https://gist.github.com/edufelipe/1027906)) in the Ranger codebase.

**Comment by nfnty** [comment]
Fixed in #695
