### ISSUE TITLE
Internal preview of text files with Windows line endings

### ISSUE THREAD

**Issue by richboss** [ranger/ranger#698]
The _internal_ preview (use_preview_script = false) of text files doesn't work correctly, if the file has line endings in the Windows format ("\r\n"). The preview - either in the rightmost pane or the fullscreen preview invoked with "i" - is mostly blank. 

Sometimes single lines are shown, seemingly random, but there is a system behind it. It depends on the length of the line. If the line is short and hence could be shown fully on the preview pane, the line is empty. If the line has more characters than can be shown on the preview pane, the line is shown! Apparently the trailing "\r\n" prevents the line to be shown at all. When the line is long, it gets cut off, so the line can be displayed.

This can easily be fixed be replacing Windows line endings with Unix line endings in every line to be shown. See attached pull request.

**Comment by nfnty** [comment]
Fixed in #699.
