### ISSUE TITLE
What is the meaning of draw_bookmarks?

### ISSUE THREAD

**Issue by c02y** [ranger/ranger#700]
The default shortcut of `draw_bookmarks` is `m<bg>`.
1. What is the meaning of `draw_bookmarks`? How can I use it?
2. What is the meaning of `<bg>` in the binding?

**Comment by nfnty** [comment]
Read `ranger/ext/keybinding_parser.py`, `ranger/core/actions.py` and `ranger/gui/widgets/view_base.py` if you want to know how it works.

**Comment by Mange** [comment]
To answer the question, it means `PASSIVE_ACTION`, which is not actually a key. It seems to mean "run this command without further key press, but keep waiting for another keypress as if this command didn't match".

So pressing just `m` in this example would `draw_bookmarks` and then wait for another key to assign your bookmark (assuming `m<any>` is also mapped). Press `Escape` to back out of it.

This is my take on what it seems to mean, at least.
