### ISSUE TITLE
How to reload config files after saving them?

### ISSUE THREAD

**Issue by c02y** [ranger/ranger#702]
https://github.com/ranger/ranger/wiki/Keybindings#quick-editing-rcconf says that I can map a key to edit the `rc.conf` file and source it after saving it, so I don't have to source it manually.

    map X chain shell vim -p ~/.config/ranger/rc.conf %rangerdir/config/rc.conf; source ~/.config/ranger/rc.conf

I tried other configuration files (`rifle.conf`, `commands.py` and `scope.sh`) in `~/.config/ranger/`, it only works for `rc.conf` and `scope.sh`, not for `rifle.conf` and `commands.py`.

And [another source](http://unix.stackexchange.com/a/150545/22322) mentioned that I can use the following command to manually reload the two files in the current session so I don't have to restart ranger:

    :eval fm.source(fm.confpath('rc.conf'))
    :eval fm.rifle.reload_config()

But how can I automatically source `rifle.conf` and `commands.py` if edit and save them like the `map X` like for `rc.conf` ?

------------------------------------------------------
UPDATE:

    map xx chain shell vim ~/.config/ranger/rc.conf; source ~/.config/ranger/rc.conf
    map xr chain shell vim ~/.config/ranger/rifle.conf; eval fm.rifle.reload_config()
    map xs chain shell vim ~/.config/ranger/scope.sh; source ~/.config/ranger/scope.sh

Those are the configuration, but how can I reload `commands.py` once I edit and save it?

**Comment by nfnty** [comment]
The only way to currently reload `commands.py` is to restart ranger.
