### ISSUE TITLE
No images in gnome terminal

### ISSUE THREAD

**Issue by CaptainQuirk** [ranger/ranger#703]
Hi there !

I'm using ranger 1.7.2 installed with linuxbrew. When using xterm, I get image preview through w3m. However, it doesn't work with gnome-terminal on my Linux Mint Cinammon (17.3).

Any idea on how to fix this ?

Thanks in advance !

**Comment by CaptainQuirk** [comment]
I had not actually seen the little red error at the bottom

```
[Errno 32] Broken Pipe
```

**Comment by soredake** [comment]
Compile gnome-terminal without transparency patch.
