### ISSUE TITLE
Toggle between ranger and shell without loosing path

### ISSUE THREAD

**Issue by mbutz** [ranger/ranger#704]
Hi,

I recently discovered `ranger` and I like it a lot. Thanks a lot for this wonderful filemanager!

This is more of a question: I would like to be able to jump between ranger and shell without loosing the current path and without creating new instances of `ranger`. As I know close to nothing neither about bash-scripting nor about Python I tried to combine two snippets I found here and in the Arch wiki: 

I have this in my `.bashrc`:

```
# https://github.com/ranger/ranger/blob/master/examples/bash_automatic_cd.sh
function ranger-cd {
    tempfile="$(mktemp -t tmp.XXXXXX)"
    /usr/bin/ranger --choosedir="$tempfile" "${@:-$(pwd)}"
    test -f "$tempfile" &&
        if [ "$(cat -- "$tempfile")" != "$(echo -n `pwd`)" ]; then
            cd -- "$(cat "$tempfile")"
        fi
    rm -f -- "$tempfile"
}
# https://wiki.archlinux.org/index.php/Ranger#Shell_tips
rg() {
    if [ -z "$RANGER_LEVEL" ]
    then
        ranger-cd
    else
        exit
    fi
}
bind '"\C-b":"rg\C-m"'
```

I am now able to toggle between `ranger` and `bash` via <C-b> without creating new instances of `ranger`; but: on the way back `ranger` will not reflect the new path (in case I changed). 

Is there a solution to solve this problem?

**Comment by Vifon** [comment]
Shameless plug: You may want to try one of my projects integrating ranger with shells: [texas][1] or [zranger][2]. Or [deer][3] but it's a bit different. zranger does specifically what you want but it works only with zsh and tt seems you're using bash. texas on the other hand should work just fine.

[1]: https://github.com/Vifon/texas
[2]: https://github.com/Vifon/zranger
[3]: https://github.com/Vifon/deer
