### ISSUE TITLE
Changing sort order causes race condition when chaining

### ISSUE THREAD

**Issue by c02y** [ranger/ranger#707]
the default `om` binding:

    map om chain set sort=mtime; set sort_reverse=False

and I want `om` to do:

    1. set sort_directories_fisr false
    2. set sort=mtime
    3. set sort_reverse=False
    4. goto the first line of the list

I use `move to=0` as step 4:

    map om chain set sort_directories_first false; set sort=mtime; set sort_reverse=False; move to=0

but this is not working, all the first 3 steps will be executed as expected except step 4, unless I execute `om` again, and I don't why.  And I can do the whole process step by step using those 4 steps in console `:`, and it works as expected.

If I change the step 4 to `console move to=0`, then I have to type `Enter` key to execute it and it works too.

So how can I make the step 4 work, (just one `om` binding will execute the whole 4 steps`)?

**Comment by nfnty** [comment]
This works as expected on `master`. Reopen if you still experience this issue.

**Comment by c02y** [comment]
It is not working as before, I have to type twice `om` to make it work as expected.

**Comment by c02y** [comment]
Off the topic: 
Any chance to create a new variable that ranger jumps the the top/bottom of the list after any sorting actions?

**Comment by nfnty** [comment]
Yeah, I can reproduce this issue now. Caused by a race condition between changing sort order and moving.

**Comment by nfnty** [comment]
Reproduced by alternating:
`map om chain set sort=mtime; move to=0`
`map on chain set sort=natural; move to=0`
