### ISSUE TITLE
Systemwide configuration

### ISSUE THREAD

**Issue by alem0lars** [ranger/ranger#712]
Hi,

Is it possible to have systemwide configuration (e.g. in `/etc/xdg/ranger`) ?

Thanks

**Comment by nfnty** [comment]
Yes, if you run ranger with `--confdir /etc/xdg/ranger` or export`XDG_CONFIG_HOME=/etc/xdg`.

**Comment by nfnty** [comment]
Duplicate of #138.

**Comment by eMPee584** [comment]
Is there any reason not to use `/etc/ranger` as default system-wide conf dir? :thinking:
