### ISSUE TITLE
Create a vim-like behaviour for f and F

### ISSUE THREAD

**Issue by tuxflo** [ranger/ranger#716]
In vim I'm used to press the `F` Key to navigate to the first occurrence of that letter in the current line. I'm looking for a similar function in ranger to press `F` and a letter to jump directly to the directory of file beginning with the letter.
I'm not too familar with python so I can't create a patch and submitt a pull request, but I think this could be done with the `scout` command but I do not know how.

**Comment by Q3CPMA** [comment]
`map F<any> search ^%any`?

**Comment by Q3CPMA** [comment]
Thanks, by the way. Hadn't thought about this shortcut (not a vim user).

**Comment by tuxflo** [comment]
Thanks a lot the mapping works like a charm. I think not all vim users are used to the "F" shortcut. Just learned it from the book "practical vim" and now I'm using it all the time.
