### ISSUE TITLE
How to display the size of all or selected multiple directories in the current view?

### ISSUE THREAD

**Issue by c02y** [ranger/ranger#719]
I can use `dc` to get the size of the current selected one directory, but how can I get all or multiple selected directories in the current view?

**Comment by Q3CPMA** [comment]
Something like `du -hd0 --total %s | tail -n1 | cut -f1`, maybe.

**Comment by v1kn** [comment]
`v` selects all items in current view.
So `vdcv` will show you sizes of all directories

**Comment by c02y** [comment]
Thanks, vdcv is nice, this is the binding I use now:

    map dC chain mark_files all=True toggle=True; get_cumulative_size; mark_files all=True toggle=True

**Comment by akhiljalagam** [comment]
is it possible to see child directories size with running it again.?  
vifm has option `ga` for this

**Comment by Rom1deTroyes** [comment]
Something like `du` and `dU` ? (think for shell's `du -h`)

**Comment by c02y** [comment]
> > > Would it be possible to view the child directories size without another run? vifm has option `ga` for this
> > 
> > 
> > Something like `du` and `dU` ? (think for shell's `du -h`) but with a caching of the result ?
> > `shell -p du --maxdepth=1 -h --apparent-size | sort -rh`
> 
> Nope. That just gives the size of the present directory, not child directories. when you switch into child dir you need to run this again. but vifm works like `ncdu` command.thats the reason i switched to vifm from ranger. you can try vifm and see how it works.

Don't know if this is what you want, I thought what you asked is that how to view the size of the sub dirs without navigating into it (in multiple columns mode).

Anyway, I got two bindings that cd into the current-selected/parent dir, get all the sizes of the files and dirs and sort them by size using ranger's command chain.

```
map { chain move left=1; mark_files all=True toggle=True; get_cumulative_size; mark_files all=True toggle=True; set sort=size; move to=0
map } chain move right=1; mark_files all=True toggle=True; get_cumulative_size; mark_files all=True toggle=True; set sort=size; move to=0

```

**Comment by akhiljalagam** [comment]
@c02y  
```
map { chain move left=1; mark_files all=True toggle=True; get_cumulative_size; mark_files all=True toggle=True; set sort=size; move to=0
map } chain move right=1; mark_files all=True toggle=True; get_cumulative_size; mark_files all=True toggle=True; set sort=size; move to=0
```

This works. It is also difficult to use.
vifm calculates directory sizes only once (including child directories) in order to avoid recalculating sizes every time you switch a directory, which would waste a lot of disk I/O.

**Comment by c02y** [comment]
> @c02y
> 
> ```
> map { chain move left=1; mark_files all=True toggle=True; get_cumulative_size; mark_files all=True toggle=True; set sort=size; move to=0
> map } chain move right=1; mark_files all=True toggle=True; get_cumulative_size; mark_files all=True toggle=True; set sort=size; move to=0
> ```
> 
> This works. It is also difficult to use. vifm calculates directory sizes only once (including child directories) in order to avoid recalculating sizes every time you switch a directory, which would waste a lot of disk I/O.
> 
> If ranger supports it, you don't need to use ncdu or vifm at all.

well, personally I rarely use these two bindings, not to mention getting sizes of all dirs/files recursively in ranger, when I use them, I only run them at most a few times, no need to go deeper. If you really need to check the size of all dirs/files recursively, and these two binding waste a lot of disk io for you, I guess your dir is huge, and calculating the size recursively once for all like you asked will waste even much more disk io, and it may even freeze ranger for some time when you run it, it is better use other tools to do this kind of work, btw, use dua or gua instead of ncdu, they are much better.

Of course, it is always welcome if anyone has this solution.
