### ISSUE TITLE
Directly goto the top or the bottom of the list after sorting?

### ISSUE THREAD

**Issue by c02y** [ranger/ranger#721]
After sorting the files/directories in the current view, I always want to goto the top/bottom of the list, and I have to type `gg` or `G` to do that, especially sorting by time or size. 

How to config ranger to goto the top/bottomn directly after sorting instead staying at the selected item?

--------------------------
And, I already configed `om` which is sorting by default by mtime to do that:

    map om chain set sort_directories_first false; linemode sizemtime; set sort=mtime; set sort_reverse=False; console move to=0

the only thing is, after sorting, I have to type `Enter` to execute the command in the command line prompt to goto the top of the list. Does anyone know that how can I avoid typing extra `Enter` key and directly goto the top of the list?

**Comment by nfnty** [comment]
`console move to=0` should be `move to=0`.

**Comment by c02y** [comment]
Check #707
