### ISSUE TITLE
Copying loses timestamp precision

### ISSUE THREAD

**Issue by tspivey** [ranger/ranger#724]
On filesystems that support high-precision timestamps, the copy process of ranger loses some precision.
Example:
```
$ touch -d "Nov 23 2016 00:00:00.123456789" test
$ stat test
...
Modify: 2016-11-23 00:00:00.123456789 -0800
$ python3 ~/ranger/ranger.py
(press yy and pp on test)
$ stat test_
Modify: 2016-11-23 00:00:00.123456716 -0800
```
Python 2 will set the timestamp to 2016-11-23 00:00:00.123456000.
This could be fixed if shutil_generatorized was modified to take advantage of the new python 3 support for st_mtime_ns and st_atime_ns.

**Comment by ael-code** [comment]
Is there any reason for ranger to use a custom `copystat` function instead of the standard one [1] ?

[1] https://docs.python.org/3.6/library/shutil.html#shutil.copystat

**Comment by nfnty** [comment]
Fixed, it now uses the builtin functions.
