### ISSUE TITLE
open_with flag behaviour

### ISSUE THREAD

**Issue by Q3CPMA** [ranger/ranger#727]
Hello, I'm trying to understan open_with a little bit, but there are some problems:
1) Why are the flags not using a dash (unlike :shell)? Using `open_with -f` says `Label '-f' is undefined`
2) `open_with f` doesn't work at all, when trying something like `open_with f gimp`, it simply uses sxiv. When doing `open_with gimp`, it obviously works, but without forking.

Hope someone can enlighten me.

**Comment by spcmd** [comment]
`open_with gimp f` 

the application name (command) comes before the `f`

**Comment by Q3CPMA** [comment]
Ah, thanks. Do you know why shell and open_with have this unexpeced difference?

**Comment by nfnty** [comment]
Because that's how `open_with` works. Read the man page `ranger(1)` for more info.
