### ISSUE TITLE
ranger won't start and is stuck with "loading..." message when something is wrong.

### ISSUE THREAD

**Issue by c02y** [ranger/ranger#730]
ranger won't start and stuck with "loading..." message when something is wrong.

When I mount a remote computer into `/mnt` but that remote  computer is shutdown and I didn't umount it, then the `df` command or `ls /mnt` will also freeze the terminal and I have to kill the terminal, and when I execute `ranger`, it will freeze the terminal, even inside another directory like `~/`, and I have to kill the terminal manually, and execute `ranger` again, it will freeze the terminal again.

**Comment by omar-polo** [comment]
I've got the same problem: mounted a remote computer into `/mnt`, disconnected my pc and then ranger freeze the terminal.

But I don't think is strictly related to ranger because other programs suffer this issue too (df, some zsh plugin, kakoune, ...). It's the user fault: properly `umount`-ing the device (`umout -f /mnt`) solve this issue

**Comment by randynobx** [comment]
This is definitely not a ranger-specific issue. This is a problem with mounted shares no longer being available, which causes issues with df, lsof, and other programs).

Ranger might be able to work around it with some sort of timeout. But that would probably mean that the timeout is starting and stopping with every action in ranger that makes it interact with the filesystem, which is not worth the effort IMHO if that is the case.

**Comment by ashwin** [comment]
I get this problem too when I SSH to servers and run ranger there. This is a problem that should be fixed. This is the reason:

As long as I am running ranger from within directories which have no mount problems, ranger should work. Currently it does not. If I have two NFS mounts, one of which has a problem. Then invoking ranger from inside a directory of the NFS mount that's working still causes it to hang. This is not a good behavior.

**Comment by randynobx** [comment]
This is an issue far beyond the scope of ranger. Try using df from a 'working/no-issues' directory when you have a bad NFS mount, it will not work.

This is not fixable from ranger without elaborate workarounds. Which, IMHO, are going to bring a lot more issues to the table than it would solve.

**Comment by sim590** [comment]
If you are stuck, use *lazy unmount* by issuing `umount -l ${faulty_nfs_target}` on the command line.

**Comment by c02y** [comment]
Yeah, I'll close this issue since it not ranger related.
