### ISSUE TITLE
image preview methods don't work with ranger-git + urxvt

### ISSUE THREAD

**Issue by spcmd** [ranger/ranger#731]
With ranger 1.7.2-1 (on Arch Linux) the w3m image preview method worked fine _(aside from w3mimagedisplay consumes the memory)_. Today I switched to ranger-git (1.7.2.406.g496b1c0-1) to try out the urxvt image preview but unfortunately none of the preview methods (w3m, urxvt) work, instead ranger shows me the img2txt preview that comes with the scope.sh.

If if comment out the img2txt in scope.sh **or** `set use_preview_script false` then there is no preview at all.

I have these settings in my rc.conf (this works fine with the stable release):

```
set preview_script ~/.config/ranger/scope.sh
set use_preview_script true
set preview_images true
set preview_images_method w3m
set preview_files true
set preview_directories true
```

So it's not a urxvt pixbuf issue, because w3m image preview doesn't work either.
But just in case, I checked and urxvt pixbuf support is enabled:
options: perl,xft,styles,combining,blink,iso14755,unicode3,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,**pixbuf**,XIM,frills,selectionscrolling,wheel,slipwheel,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm

And pixbuf works when I set and image as a background with `urxvt -pixmap /path/to/image`

I ran `ranger -c` (clean), but the issue still persists. I tried `ranger -d` for debug mode, there wasn't any error message.
I killed compton (the compositor), it didn't help.

**Comment by ael-code** [comment]
On 12/10/2016 01:22 PM, spcmd wrote:
> With ranger 1.7.2-1 (on Arch Linux) the w3m image preview method worked
> fine /(aside from w3mimagedisplay consumes the memory)/. Today I
> switched to ranger-git (1.7.2.406.g496b1c0-1) to try out the urxvt image
> preview but unfortunately none of the preview methods (w3m, urxvt) work,
> instead ranger shows me the img2txt preview that comes with the scope.sh.
> 

I confirm the bug.

> If if comment out the img2txt in scrope.sh *or* |set use_preview_script
> false| then there is no preview at all.
> 
> I have these settings in my rc.conf (this works fine with the stable
> release):
> 
> |set preview_script ~/.config/ranger/scope.sh set use_preview_script true
> set preview_images true set preview_images_method w3m set preview_files
> true set preview_directories true |
> 
> So it's not a urxvt pixbuf issue, because w3m image preview doesn't work
> either.
> But just in case, I checked and urxvt pixbuf support is enabled:
> options:
> perl,xft,styles,combining,blink,iso14755,unicode3,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,*pixbuf*,XIM,frills,selectionscrolling,wheel,slipwheel,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm
> 
> And pixbuf works when I set and image as a background with |urxvt
> -pixmap /path/to/image|
> 
> I ran |ranger -c| (clean), but the issue still persists. I tried |ranger
> -d| for debug mode, there wasn't any error message.

You can see the log at runtime with the `:display_log` command or
you can use the `--logfile` to specify a where to send log message

> I killed compton (the compositor), it didn't help.
>

**Comment by spcmd** [comment]
@ael-code : thx! I ran ranger with the logfile option, but this is all the info I got (no errors or warnings or something like that):

```
[INFO] Ranger version 1.7.2
[INFO] Running on Python 3.5.2 (default, Nov  7 2016, 11:31:36) [GCC 6.2.1 20160830]
[INFO] Process ID is 7307
```

**Comment by ael-code** [comment]
On 12/10/2016 03:51 PM, spcmd wrote:
> @ael-code <https://github.com/ael-code> : thx! I ran ranger with the
> logfile option, but this is all the info I got (no errors or warnings or
> something like that):
> 
> |[INFO] Ranger version 1.7.2 [INFO] Running on Python 3.5.2 (default, Nov
> 7 2016, 11:31:36) [GCC 6.2.1 20160830] [INFO] Process ID is 7307 |
> 

yeap that is possible, means that no error have been raised or logged.


In any case you need both the `-d` and `--logfile` flags in order to
have the verbose logging.

**Comment by Vifon** [comment]
I believe the `scope.sh` structure has changed since 1.7.2. Could you try getting a fresh copy of `scope.sh` supplied with ranger-git? (`ranger --copy-config=scope`)

**Comment by spcmd** [comment]
@Vifon: yes, you are right, the `scope.sh` was the problem. I had the old one in my config dir. Now all the image preview methods are working. Thanks guys! I guess I can close this issue.

**Comment by rafaeln** [comment]
This was useful to me. I had the same problem (an old scopes.sh file lying around)

**Comment by expl0ratory** [comment]
I also had this issue, despite a fresh install on ubuntu

**Comment by kirkins** [comment]
@expl0ratory did you find a way to get any type of image preview working on Ubuntu 18.04?

**Comment by expl0ratory** [comment]
> @expl0ratory did you find a way to get any type of image preview working on Ubuntu 18.04?

Nope, gave up

**Comment by toonn** [comment]
@expl0ratory, @kirkins, what terminals are you running in and what methods are you trying? `w3mimgdisplay` is only supported in *xterm* (by the w3m team), people often get away with running it in other terminals but it's not a given especially if your terminal doesn't emulate xterm closely. I suspect the problem with ubuntu is it runs wayland and the usual suspect terminals'd would run in an X emulation mode which may not be good enough. Best bet is trying one of the terminals with native image support, e.g., kitty, terminology, ~urxvt.
