### ISSUE TITLE
Killing fish running ranger creates a CPU hog

### ISSUE THREAD

**Issue by Ambrevar** [ranger/ranger#733]
When calling ranger from a _fish function_ that has some termination code, killing the terminal sometimes reparents ranger and creates a CPU hog. Very annoying :(
The bug is described extensively here: fish-shell/fish-shell#3644.

According to some fish developers, all sides are to blame: ranger seems to ignore EOF when it reads from TTY. I haven't checked this for myself, but there might be something to investigate at least. Can you confirm?

**Comment by Vifon** [comment]
I started my regular shell (zsh), launched fish, then launcher ranger. From a different shell I killed fish (SIGTERM). It caused ranger to throw exception and close too. Is that more or less how you do it?

**Comment by Ambrevar** [comment]
In a more casual way, I close the terminal.
Fish is exec'ed from my bashrc.
This only happens when ranger is called from a fish function with termination code (see the aforementioned issue).

Note that this bug happens randomly to me, about 75% of the time.

**Comment by Ambrevar** [comment]
After further investigation (see the fish issue linked above), it seems that ranger is not involved here, but rather ncurses. Closing.
