### ISSUE TITLE
Add option to quickly rename keeping only the file's extension

### ISSUE THREAD

**Issue by Zekario** [ranger/ranger#744]
An example: I want to rename 120391024.png to test.png. I could type `:rename test.png`, or type `a` and backspace the original filename. There should be an option to press a shortcut and have the rename prompt with only the file extension. So, instead of having to type out `:rename test.png` or `aDELDELDELDEL...` or similar, I would press the new hotkey and the console would read `rename |.png`, where | is the cursor.

**Comment by nfnty** [comment]
`map i eval fm.open_console('rename ' + fm.thisfile.basename[fm.thisfile.basename.rindex('.'):], position=7)`

Will error out and notify you if if the filename doesn't contain a `.`.

**Comment by nfnty** [comment]
Replace `rindex()` with `index()` if you want to preserve multiple extensions.

**Comment by Zekario** [comment]
@nfnty That works, thanks! Should I close this issue or leave it open? I think it would be nice to be included with ranger.

**Comment by nfnty** [comment]
Can leave it open for now and gauge interest for including it by default.

**Comment by Vifon** [comment]
@Zekario: I don't know if you know about it but you could use <kbd>ctrl+w</kbd> as a middle ground. It deletes the last word.

**Comment by andya9** [comment]
personally I remapped cw to use: `map cw eval fm.open_console('rename ' + fm.thisfile.basename[fm.thisfile.basename.rindex('.'):], position=7) if '.' in fm.thisfile.basename else fm.open_console("rename ")`. 
If you need support for multiple extensions, change rindex to index as per @nfnty 's suggestion. But it will break if your filename contains dots

**Comment by lamarpavel** [comment]
What @andya9 said makes the difference for me. To do this right we would have to test against a list of known extensions like `.tar.gz`, raising the complexity beyond a one-liner for the config. As such, I vote for making this a default command in ranger.

**Comment by andya9** [comment]
Note that we should do the check against a list of *all* known extensions, because checking `if "." in fm.thisfile.basesame` as I do is just a naive solution which breaks for example with a filename like `my_title_vol.1.pdf`.

**Comment by Firenox89** [comment]
IMHO pressing `a` and  then `ctrl+w` as many times as needed is simple enough. One single propose key less to remember.

**Comment by nfnty** [comment]
@lamarpavel Impossible to implement properly. Better to just do it manually if you ever encounter a weird filename.

Now `rename_append` has flags. Read the man page for more info.
