### ISSUE TITLE
how to organize multiple tabs side by side?

### ISSUE THREAD

**Issue by c02y** [ranger/ranger#747]
Today when I was using ranger to copy/paste files across directories, I opened two tabs using `Alt-2`, and switch tabs using `Alt-Num`,  but suddenly I realized that the layout became the two tabs side-by-side in the same window, a tab contains 3 columns by default: parent directory list (left), and current directory(middle) and the viewer of the current select item (right), the side-by-side layout is two columns (each one is middle column in different tabs) in the same window, and I switched between them for several times, even created a third tab using `Alt-3` and switched tabs, (now one window contains 3 different middle columns in 3 different tabs) it worked perfectly and  didn't disappear, but after I tried to edit a file and quit the editing, the layout became normal ( three columns belongs to one tab in one window). 

I like the side-by-side layout, but didn't remember what did that produced the layout and I cannot reproduce it anymore.

So is it a bug or a feature? I already read all the documentation and didn't remember that `ranger` provides this kind of feature.

**FYI**:
ranger-master 1.7.2
Python 3.3.5 (default, Jan 28 2016, 15:18:10)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]

**Comment by Vifon** [comment]
It's a new feature added in 1.8 but since you use the development version you must have got it too. You enable it with <kbd>~</kbd>. See also: https://bbs.archlinux.org/viewtopic.php?pid=1616858#p1616858

**Comment by c02y** [comment]
Thanks, it it very nice.
