### ISSUE TITLE
Exiting into shell with specified directory `S` enters Bash instead of Zsh

### ISSUE THREAD

**Issue by zyklotomic** [ranger/ranger#751]
I use zsh as my default shell. When I `sudo ranger` and try to exit ranger with `S` into the specified directory in the shell, I get dropped into bash. Ideally, the transition between directories and sudo in the shell would be seamless. 

From my understanding though, ranger seems to restart (a new?) tty each time I use `S`? Perhaps there could be a better implementation? 

Not sure.

**Comment by Vifon** [comment]
When you run `sudo ranger`, ranger runs as root. You probably changed only the default shell of your user, not of root.

> Ideally, the transition between directories and sudo in the shell would be seamless.

Could you elaborate?

> From my understanding though, ranger seems to restart (a new?) tty each time I use S? Perhaps there could be a better implementation?

If you're fine with an external solution (not in ranger itself), you might want try this: https://github.com/Vifon/zranger

**Comment by zyklotomic** [comment]
You're right. I forgot I did not set my default shell as zsh for the root user. Sorry about that!
