### ISSUE TITLE
ranger search doesn't search ([testing] repo, after major python update)

### ISSUE THREAD

**Issue by ngoonee** [ranger/ranger#752]
So after yesterday's major python update, ranger runs but searching with / doesn't move selection at all.

EDIT: Oh, just to note that find 'f' doesn't either (unless I type the full dir name, which doesn't make too much sense)

**Comment by yang-ling** [comment]
Same here. I guess this issue is related to `scout`. Is `scout` changed?

**Comment by andya9** [comment]
Here is a list of breaking changes: [list](https://docs.python.org/3.6/whatsnew/3.6.html#changes-in-the-python-api). I can't see anything suspect though.

**Comment by cwmke** [comment]
I'm having the same issue with the latest version 1.8.1-1 on Arch. Find is working fine.

**Comment by nfnty** [comment]
@cwmke Test `master` branch and report back.

**Comment by cwmke** [comment]
Tested. Problem still exists as well as having no space added after "search" or "find" despite having it in the rc.conf.

**Comment by nfnty** [comment]
@cwmke Please, open a new issue regarding your search problem.

Spaces at the end of lines have been deprecated and replaced with `%space`.

**Comment by yang-ling** [comment]
@cwmke  In my case, this issue was fixed for me after I update ranger to the latest version
I suggest you compare your config file with config examples of ranger by some diff tool. They are under `ranger/config` folder in this repo.
