### ISSUE TITLE
setlocal path= doesn't accept spaces

### ISSUE THREAD

**Issue by Chinggis6** [ranger/ranger#753]
What if my path contains spaces, how would I specify "~/My Configuration Files/", by escaping its spaces what are treated as special characters?

I use `setlocal path=~/My Configuration Files show_hidden yes`

Quotes, single quotes, double quotes do not work.

I read that its regex and "My" would be just enough, but I don't want that, I'd like to end the string with `$` to specify one directory only.

**Comment by nfnty** [comment]
Fixed, just quote your `path` with either single or double quotes: `setlocal path='~/My Configuration Files' show_hidden true`
