### ISSUE TITLE
Unable to set titlebar hostname fgcolor unless bold is set

### ISSUE THREAD

**Issue by rafi** [ranger/ranger#755]
While customizing my colorscheme, I've noticed that the hostname in titlebar won't change fg color unless bold is added. How to reproduce:
```py
class Foo(ColorScheme):
    progress_bar_color = 4

    def use(self, context):
        fg, bg, attr = default_colors

        if context.reset:
            return default_colors

        elif context.in_titlebar:
            fg = 244
            if context.hostname:
                fg = context.bad and 2 or 3
```

In the last line, the `hostname` won't be colored, unless I add `attr |= bold`.

**Comment by nfnty** [comment]
Can't reproduce this issue. Have you tested with different terminal emulators?

**Comment by nfnty** [comment]
Request reopening if you're still having this issue on `master` and other terminal emulators.
