### ISSUE TITLE
Implement list of plugins

### ISSUE THREAD

**Issue by ezh** [ranger/ranger#756]
Github contains few interesting plugins like 
https://github.com/matze/ranger-annex
https://github.com/alex8866/eranger/blob/master/ranger/config/plugins/plugin_direcory_diff.py
...
I have some ideas about [easymotion](https://github.com/easymotion/vim-easymotion) like plugin. I suspect that plugin section may improve interest of community to extend functionality of ranger.

I think that this may be something extremely simple like section in README.md because there is nothing right now.

If this idea is out of scope fill free to close this ticket.

Thank you.

**Comment by nfnty** [comment]
I'll be happy to accept PRs.

**Comment by nfnty** [comment]
Add your custom plugins to [Wiki - Plugins](https://github.com/ranger/ranger/wiki/Plugins).
