### ISSUE TITLE
Video Preview in st 0.6 not displayed

### ISSUE THREAD

**Issue by SageEx** [ranger/ranger#759]
Hi,
Video previews in st seems to have broken after the update to 1.8.1. Image preview continues to work fine. I'm using the w3m backend.

st used to work fine on ranger 1.7.2 on both videos and images, but now, the video preview flickers and does not render most of the time. The cache is being generated fine, but due to some reason, the video preview is not displayed most of the time.(Sometimes it works).

This is a regression from the last version. Could you please check this ?

Note that xterm works perfectly fine for both, videos and images.
Python version - 3.6.0

**Comment by funeralismatic** [comment]
@SageEx 

Sorry for offtopic but I need to ask: image preview in `st` doesn't work for me; what did you do to make it work? Can you share your `config.h` please?

**Comment by SageEx** [comment]
@funeralismatic 
I'm using [xst](https://github.com/neeasade/xst).
Here is the relevant [config.h](https://github.com/neeasade/xst/blob/master/src/config.h)

Ranger image/video preview is supposed to work on xterm, urxvt and st. 

The video previews broke on the last ranger update.

Any clues ?

**Comment by funeralismatic** [comment]
Nothing at the moment, I have no image preview in `st` (even in `xst`).

In `urxvt` and `xterm` seems to be working both image and video preview.

Python 3.5 and 2.7, ranger from git.

**Comment by SageEx** [comment]
Are you using the alpha patch ?

Image previews don't work if you have transparent st terminals( though they work with transparent urxvt).

**Comment by funeralismatic** [comment]
>Are you using the alpha patch ?

Nope. I know this bug. `w3mimgdisplay` return `1` in `st`.

UPD: With default config too.

**Comment by SageEx** [comment]
Ok, so with xst,  setting the ``st.xfps`` value to be higher like 300, resolves the issue.

**Comment by SageEx** [comment]
The video and image previews load and display well.

**Comment by nfnty** [comment]
Great!
