### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ralpheeee88** [ranger/ranger#760]
could you pls advise?
http://ix.io/1PK4

in bookmarks if directory does not exist ranger crashed on launch

**Comment by Mattery** [comment]
Same happened to me, fixed it deleting the bookmarks file in /.config/ranger, not sure if it's a bug

**Comment by nfnty** [comment]
This issue was caused by having bookmarks pointing to files.

**Comment by eMPee584** [comment]
Uhm, this causes troubles with bookmarks pointing to unavailable sshfs autofs mounts, i.e. considerably startup delay until sshfs times out.
