### ISSUE TITLE
Missing trailing space in search

### ISSUE THREAD

**Issue by cym13** [ranger/ranger#765]
What
====

When doing a search (default /) the command line is filled with ":search" without any trailing space at the end. It makes any search I run frustrating because I expect that space to be there (":space ") and I keep having to go back and insert the space myself. I had no issue on previous versions.

Current information
============

I am running the latest git version at the time, ie 10d71746 on branch master, on archlinux.

A git bisect lead me to the commit 67fb633bcc5b65ae9d20ead5c68d5b677bbc1485
which seems to be the origin of the bug.

What's strange to me is that I don't see how I can be the only one affected, but I don't see anybody talking about it either.

**Comment by Vifon** [comment]
Trailing literal spaces are no longer supported in the config. Use `%space`. In this case updating your rc.conf should help. While we're at it, you might want to update your scope.sh as it have changed significantly since 1.7.2.

**Comment by Vifon** [comment]
I'm closing the issue for now. Please reopen if it's still a problem.

**Comment by cym13** [comment]
Thanks, that was it. Must have missed the changelog. Maybe a one-time message when launching ranger after such a breaking change would help staying updated. Anyway, thanks.

**Comment by bitterjug** [comment]
I just came here with the same problem and after conducting the same bisect!
Upgrading `rc.conf`!
