### ISSUE TITLE
Canonicalize path (escape from symlinks)

### ISSUE THREAD

**Issue by SammysHP** [ranger/ranger#766]
#### ISSUE TYPE
- Improvement/feature request

#### RUNTIME ENVIRONMENT
- Operating system and version: Arch Linux
- Terminal emulator and version: urxvt v9.22
- Python version: Python 3.6.0
- Ranger version/commit: ranger-stable 1.8.1

#### EXPECTED BEHAVIOR
Sometimes I find myself "lost" in a really deep path of symlinks. It would be nice to escape from them and cd to the "real", canonical path (e.g. similar to `readlink -f`).

**Comment by nfnty** [comment]
That's what `gl` and `gL` are for.

**Comment by SammysHP** [comment]
Great, thanks!
