### ISSUE TITLE
Ranger Search Not Searching

### ISSUE THREAD

**Issue by cwmke** [ranger/ranger#767]
#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version: Arch Linux (Fully Updated)
- Terminal emulator and version: gnome-terminal 3.22.1-1 rxvt-unicode 9.22-2
- Python version: 3.6.0-2
- Ranger version/commit: 1.8.1-1, also tested against master branch

#### EXPECTED BEHAVIOR

After entering the search term and pressing enter, the selection should jump to the first related term to the search.

#### CURRENT BEHAVIOR

After pressing enter, the selection stays in the same place. In other words, nothing happens.

#### CONTEXT

I am no longer able to search through folders with lots of files which severely hampers my use.

Searching.

#### STEPS TO REPRODUCE

1. Open Ranger.
2. Press '/' to search bringing ':search ' up in the command area.
3. Type in a search term of a file or folder inside of the current directory.
4. Nothing happens.

**Comment by Delapouite** [comment]
I had the same issue upgrading from 1.7.* to 1.8.1. I fixed this by regenerating newer conf files in my `~/.config/ranger` dir

**Comment by cwmke** [comment]
Thanks @Delapouite! That did the trick.
