### ISSUE TITLE
cmap with ansi code

### ISSUE THREAD

**Issue by laktak** [ranger/ranger#768]
My terminal produces `\e[1;5D` and `\e[1;5C` for C-Left and C-Right. Is it possible to map them with `cmap`?

Neither of those work:

```
cmap <ESC>[1;5D eval fm.ui.console.move_word(left=1)
cmap "\e[1;5D" eval fm.ui.console.move_word(left=1)
```

**Comment by hut** [comment]
Doesn't work now, as far as I know. What's printed when you run `doc/tools/print_keys.py` and type Ctrl+Left?

**Comment by laktak** [comment]
Too bad. `<C-Left>` prints `27; 91; 49; 59; 53; 68;`

**Comment by nfnty** [comment]
Continue discussion in #574.
