### ISSUE TITLE
search doesn't work anymore

### ISSUE THREAD

**Issue by pvater** [ranger/ranger#773]
#### ISSUE TYPE

- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version: arch linux (kernel 4.8.13-1)
- Terminal emulator and version: xterm(327)
- Python version: python 3.6.0
- Ranger version/commit: ranger-stable 1.8.1

#### EXPECTED BEHAVIOR

`/<searchitem>` (or `:search <searchitem>`) should move the cursor to the next occurrence of \<searchitem\> in rangers current directory. also `n`/`N` should repead/undo the last search. At least that's what it did in recent versions, and what it says in the man page.

#### CURRENT BEHAVIOR

`/<searchitem>` appears to do nothing at all. `n`/`N` just move the cursor to the item below/above the current cursor position.

#### CONTEXT

should be obvious. it is a basic function, and its absence makes ranger effectively unusable in situations where you have a lot of files in one directory.

#### STEPS TO REPRODUCE

1. open ranger in xterm, in a directory containing files called '1', '2' and '3'
2. in ranger, type `/3`
3. observe that nothing happens
4. observe that, additionally, `n`/`N` do what i described above

**Comment by lamarpavel** [comment]
Take a look at https://github.com/ranger/ranger/issues/767

**Comment by pvater** [comment]
ugh, just overlooked that. thanks!
