### ISSUE TITLE
Ranger (1.8.1) no longer showing images in iTerm2 (build 3.0.13)

### ISSUE THREAD

**Issue by AmaruCoder** [ranger/ranger#775]
When upgraded from version 1.7.0 to 1.8.1, Ranger no longer shows image previews under iTerm2 (build 3.0.13).

#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT
- Operating system and version:  MacOS 10.11.6
- Terminal emulator and version: iTerm2 (build 3.0.13)
- Python version: 2.7.11
- Ranger version/commit: 1.8.1

**Comment by hut** [comment]
Is your `~/.config/ranger/scope.sh` up to date?

**Comment by laktak** [comment]
The wiki https://github.com/ranger/ranger/wiki/Image-Previews does not say that scope.sh is required for iTerm2. It also does not mention that it won't work within tmux (I read that in another issue).

So after adding scope.sh and running outside tmux it works, though it takes 2sec for the preview to show ... not sure if that is normal (when running on Arch there is no delay).

**Comment by AmaruCoder** [comment]
That solved the issue. Thank yoiu.
