### ISSUE TITLE
Why is ranger not on PyPI?

### ISSUE THREAD

**Issue by carlmjohnson** [ranger/ranger#776]
Yes, someone else is squatting on the name "ranger" but you should be on there.

**Comment by andya9** [comment]
I too think it should be there. 
Maybe under "ranger-fm" (ugly, but others too do it like this: for example mypy is under "mypy-lang"; it will need a big disclaimer in the repo's readme)

**Comment by c02y** [comment]
ranger is pretty old in PyPi, mine here is v0.1.

**Comment by v1kn** [comment]
ranger being on PyPI would certainly make it easier to keep it up to date

**Comment by szepeviktor** [comment]
Try `pip install git+https://github.com/hut/ranger.git`

**Comment by andya9** [comment]
@szepeviktor If you install from git, shouldn't you use pip install -e? that's what I do, I like being on the bleeding edge; but users from debian/debian-like and so on may prefer to install a tagged release, which would be easier from pypi.

**Comment by szepeviktor** [comment]
> If you install from git, shouldn't you use pip install -e?

I am only a python user. I actually use `pip3 install --user` which "works for me".

**Comment by szepeviktor** [comment]
Sometimes I convert pip packages to Debian: https://github.com/szepeviktor/debian-server-tools/blob/master/virtualization/jessie-py2deb/Dockerfile

**Comment by andya9** [comment]
@szepeviktor If you don't use -e option, you won't have access to subsequent changes to the repo (from git pull, and so on)

**Comment by carlmjohnson** [comment]
This doesn't solve my usecase, which is to use [pex](https://pex.readthedocs.io/en/stable/). In any event, this shouldn't really be a debate. Popular open source projects should be on PyPI unless they can't for some reason. I know Ranger has a name conflict, but there are ways of working around that. Not being on PyPI isn't the end of the world, but it is a big inconvenience to me and I'm sure others.

**Comment by nfnty** [comment]
ranger is now on PyPI under the name [ranger-fm](https://pypi.python.org/pypi/ranger-fm).
