### ISSUE TITLE
Setting to disable opening file during navigation with the right key

### ISSUE THREAD

**Issue by Euren** [ranger/ranger#777]
#### ISSUE TYPE
- Improvement/feature request

#### EXPECTED BEHAVIOR
A setting that disables files being opened using the RIGHT key.

#### CURRENT BEHAVIOR
The RIGHT key opens not-directory file using the configuration defined in the rifle file.

#### CONTEXT
When browsing, I sometimes accidentally press the RIGHT key when on a file I do not mean to open. I would like to open files only using the ENTER key.

I can be especially frustrating when the file requires a heavy program to be opened.

**Comment by nfnty** [comment]
`map <right> cd %d/%f`
