### ISSUE TITLE
Hide or toggle "username@host" in the top bar

### ISSUE THREAD

**Issue by nonamethanks** [ranger/ranger#782]
#### ISSUE TYPE
- Improvement/feature request

#### EXPECTED BEHAVIOR
The "username@hostname" indicator in the top left should be toggable or the user should be able to disable it in the rc.conf file.

#### CURRENT BEHAVIOR
Unless I'm missing something, this feature has never been available in ranger.

#### CONTEXT
I recall a (relatively) long time ago searching for the same thing and finding in the archlinux forums a harmless patch to remove it, however I can't seem to be able to find it anymore, and I think it takes a lot of precious space that could instead be reserved to displaying the currently selected filename or the tabs.

**Comment by nfnty** [comment]
There's now a new setting `hostname_in_titlebar`. Set it to `false` to disable hostname in the titlebar.

**Comment by nonamethanks** [comment]
Awesome, thank you!
