### ISSUE TITLE
Allow configuration of draw_border color

### ISSUE THREAD

**Issue by namdnguyen** [ranger/ranger#783]
#### ISSUE TYPE
- Improvement/feature request

#### RUNTIME ENVIRONMENT

- Operating system and version: Ubuntu Mate 
- Terminal emulator and version: xterm 322
- Python version: Python 2.7.12
- Ranger version/commit: 1.7.1

#### EXPECTED BEHAVIOR
Color of border when `draw_border` is set to `true` is drawn with the color specified in `rc.conf`.

#### CURRENT BEHAVIOR
The color of the border is white when `set draw_border true` in `rc.conf`.

#### CONTEXT
The current default color is too harsh for my preferences.

#### POSSIBLE SOLUTIONS
Set a variable in rc.conf, such as `border_color` to a specific color.

**Comment by nfnty** [comment]
You have three options:
1. Change your terminal emulator's foreground color
2. Create a custom colorscheme
3. Wait for #445
