### ISSUE TITLE
:flat -1 shows hidden files

### ISSUE THREAD

**Issue by laktak** [ranger/ranger#790]
#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT
- Operating system and version: osx 10.11
- Terminal emulator and version: iterm2
- Python version: 
- Ranger version/commit: master

#### EXPECTED BEHAVIOR
`:flat -1` should show a flat view without hidden (.dot) files unless `show_hidden` is set

#### CURRENT BEHAVIOR
`:flat -1` includes hidden files regardless of `show_hidden`

**Comment by laktak** [comment]
@nfnty Thanks for the quick response!

While this fixes the issue for hidden files in the current directory, hidden files in a subdirectory are still shown.

For example `docs/.DS_Store` is included in the list.

Tested with c210af0d0b40a9e2c9151d81bbf3e5ee34047a58

**Comment by nfnty** [comment]
Fixed, thanks.

**Comment by laktak** [comment]
Works perfectly now, thanks!
