### ISSUE TITLE
Aliases for tab_new and tab_close don't work ('str' object is not callable)

### ISSUE THREAD

**Issue by spcmd** [ranger/ranger#794]
#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT
- Operating system and version: Arch Linux (up to date)
- Terminal emulator and version: rxvt-unicode (urxvt) v9.22
- Python version: Python 3.6.0
- Ranger version/commit: 1.8.1.126.gf9a5a4b6-1

#### EXPECTED BEHAVIOR
in **rc.conf** aliasing these commands, for example:
`alias TN    tab_new`  TN command is expected to open a new tab
`alias TC    tab_close`     TC command is expected to close the active tab

#### CURRENT BEHAVIOR
I got this error when I'm using those aliases: **'str' object is not callable**

#### STEPS TO REPRODUCE
1. create aliases for `tab_new` and `tab_close` in **rc.conf** 
2. use those aliases in ranger

**Comment by nfnty** [comment]
Thanks!
