### ISSUE TITLE
Add relative variant to `set line_numbers`

### ISSUE THREAD

**Issue by v1kn** [ranger/ranger#798]
#### ISSUE TYPE
- Improvement/feature request

#### EXPECTED BEHAVIOR
As a continuation of #489 , requesting enhancing the `set line_numbers` option with relative numbering that changes with cursor movement. Equivalent of vim's `set relativenumber`

**Comment by swalladge** [comment]
There already is: `set line_numbers relative`

**Comment by v1kn** [comment]
@swalladge 
ah, indeed that is correct.
It was not available through tab autocompletion so I assumed it is missing.

I am closing the issue in that case.
