### ISSUE TITLE
exec: Exec format error The file '/usr/local/bin/ranger' is marked as an executable but could not be run by the operating system.

### ISSUE THREAD

**Issue by c02y** [ranger/ranger#799]
#### ISSUE TYPE

- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version:  CentOS6.5 32-bit
- Terminal emulator and version: Yakuake
- Python version: 3.3
- Ranger version/commit: master from github (commit 01ba7b5)

#### EXPECTED BEHAVIOR

`ranger` in terminal should start ranger

#### CURRENT BEHAVIOR

`ranger` in terminal won't start ranger but get this:

    >> Failed to execute process '/usr/local/bin/ranger'. Reason:
    exec: Exec format error
    The file '/usr/local/bin/ranger' is marked as an executable but could not be run by the operating system.

#### CONTEXT

I use 
    
    sudo python3.3 setup.py install --optimize=1 --record=install_log.txt

to install in in my CentOS machine

`ranger` in terminal won't start ranger but get this

     >> Failed to execute process '/usr/local/bin/ranger'. Reason:
    exec: Exec format error
    The file '/usr/local/bin/ranger' is marked as an executable but could not be run by the operating system.

I get this in fish-shell, different from it in bash-shell, but the /usr/bin/ranger or ./build/scripts-3.3/ranger is the same whether I install it in fish-shell or bash-shell.

I found that `/usr/bin/ranger` or `./build/scripts-3.3/ranger` is the same which contains only one line:

    ../ranger.py

which is definitely wrong.

I'm not sure if it is the problem of python version, since I already installed many versions of ranger using python3.3 in the current machine before ten days ago and it worked fine. 

And I tried to clean and install ranger in the current machine many times, even using python2.7 instead of 3.3, all result is the same, not working, and the ranger file contains only one line.

The output of  `sudo python3.3 setup.py install --optimize=1 --record=install_log.txt` is too long, so I don't post here now, if you need it, please let me know.

#### POSSIBLE SOLUTIONS

I googled but got nothing.

#### TRACEBACK

```

```

**Comment by nfnty** [comment]
There's a lot results when searching for ["exec: Exec format error"](https://encrypted.google.com/search?q="exec:%20Exec%20format%20error").

Could you upload `install_log.txt`?

Also need the output of the following:
`stat /usr/local/bin/ranger`
`file /usr/local/bin/ranger`
`cat /usr/local/bin/ranger`

**Comment by c02y** [comment]
[install_log.txt](https://github.com/ranger/ranger/files/762490/install_log.txt)

 `stat /usr/local/bin/ranger`
 
     File: `/usr/local/bin/ranger'
      Size: 12              Blocks: 8          IO Block: 4096   regular file
    Device: 807h/2055d      Inode: 1595005     Links: 1
    Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
    Access: 2017-02-09 10:30:21.401992133 +0800
    Modify: 2017-02-07 11:19:16.000000000 +0800
    Change: 2017-02-09 10:30:24.458992129 +0800

` file /usr/local/bin/ranger`

    /usr/local/bin/ranger: ASCII text, with no line terminators

`cat /usr/local/bin/ranger`

    ../ranger.py

**Comment by nfnty** [comment]
Don't use the `--record` flag, instead just upload the whole output of `sudo python3.3 setup.py install --optimize=1`.

**Comment by c02y** [comment]
https://gist.github.com/c02y/3d23412b8deb3126f290b1c9c9a160dd

**Comment by nfnty** [comment]
Run `git clean --force -d -x` and then try again.

**Comment by c02y** [comment]
Not working, the same result.

**Comment by c02y** [comment]
I git clone new copy of ranger (commit 6bc13af09) and install it using 
    
    sudo python3.3 setup.py install --optimize=1

get:

    running install
    running build
    running build_py
    error: package directory 'ranger/ext/vcsranger/gui' does not exist

**Comment by nfnty** [comment]
That issue has been fixed now.

**Comment by nfnty** [comment]
I'm not sure why your distutils doesn't handle symlinks properly, but I've worked around it now. Test latest `master`.

**Comment by c02y** [comment]
Yes, it works now, thank you.
