### ISSUE TITLE
Setuputils breaking the polyglot launcher

### ISSUE THREAD

**Issue by Vifon** [ranger/ranger#805]
The main ranger executable, [ranger.py](https://github.com/ranger/ranger/blob/master/ranger.py), is a polyglot script: it's a Python and a valid Bash at the same time. When it is being sources in Bash, it can be used to change the current working directory. The new addition of the setuputils support has broken this functionality as setuputils adds it's own wrapper script which obviously no longer works in Bash.

#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT
- Operating system and version: N/A
- Terminal emulator and version: N/A
- Python version: N/A
- Ranger version/commit: 9b0673cf05fc07a9

#### EXPECTED BEHAVIOR

`. ranger` should run ranger and after closing it should perform a `cd` into its last working directory.

#### CURRENT BEHAVIOR

`. ranger` causes the following error:

```
bash: __requires__: command not found
bash: /usr/local/bin/ranger: line 4: syntax error near unexpected token `'pkg_resources''
bash: /usr/local/bin/ranger: line 4: `__import__('pkg_resources').run_script('ranger-fm==1.9.0b4', 'ranger')'
```

#### POSSIBLE SOLUTIONS

Either finding out how to stop setuptools from wrapping our script or not using setuptools. Why do we need setuptools exactly?

#### STEPS TO REPRODUCE

What works:
1. Don't install setuptools.
2. Install ranger from Git with `python ./setup.py install`.
3. Source it, `. ranger`.

What doesn't work:
1. Install setuptools.
2. Install ranger from Git with `python ./setup.py install`.
3. Try to source it, `. ranger`.

**Comment by nfnty** [comment]
Weird behavior that only seems to happen when you don't use pip or `setup.py --root=`.

Setuptools is only really needed for uploading to PyPI anyways.
