### ISSUE TITLE
bulkrename fails if a rifle.conf file exists

### ISSUE THREAD

**Issue by Unode** [ranger/ranger#808]
#### ISSUE TYPE

- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version: Sabayon linux - amd64
- Terminal emulator and version: rxvt-unicode - 9.22
- Python version: 2.7.12
- Ranger version/commit: 1.8.1

#### EXPECTED BEHAVIOR

`:bulkrename` should display the editor to perform rename changes

#### CURRENT BEHAVIOR

Editor doesn't start and the message "No renaming to be done!" is shown immediately.

#### CONTEXT

Using the bulkrename feature to rename marked files

#### POSSIBLE SOLUTIONS

Removing `~/.config/ranger/rifle.conf` brings back normal functionality

#### STEPS TO REPRODUCE

1. Start ranger
2. Mark 2 files
3. Call :bulkrename -> Editor should be displayed
4. Exit ranger
5. `touch ~/.config/ranger/rifle.conf`
6. Repeat 1-3 -> Editor is not shown and bulkrename has no effect.

#### ENVIRONMENT
EDITOR=vim

**Comment by nfnty** [comment]
You need to update your `rifle.conf`.
