### ISSUE TITLE
RANGER_LOAD_DEFAULT_RC uses a non-standard shell boolean value

### ISSUE THREAD

**Issue by has2k1** [ranger/ranger#810]
The standard boolean values are `true` and `false`, RANGER_LOAD_DEFAULT_RC uses `FALSE`. While `FALSE` is the value that the documentation mentions, it looks out of place in a shell `profile` or `rc` script.

#### ISSUE TYPE

- Improvement

#### CONTEXT

Even though I read the documentation, when I put the setting in my shell script, initially I used `false` instead of `FALSE` because `false` is what I "recalled". Other factors at play in this misconception are

1. The other boolean values in the shell script
2. The syntax highlighting suggests that `false` is the correct value

#### POSSIBLE SOLUTIONS
Change the documented value to `false`. For backward compatibility, do the internal comparisons in lower case.

**Comment by nfnty** [comment]
Now you can capitalize "false" however you want. :stuck_out_tongue_winking_eye:
