### ISSUE TITLE
ranger won't refresh preview column when previewing images and files

### ISSUE THREAD

**Issue by c02y** [ranger/ranger#811]
#### ISSUE TYPE

- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version: Fedora 25 64-bit
- Terminal emulator and version: Yakuake/Konsole+fishshell+tmux
- Python version: Python3.5
- Ranger version/commit: ranger-beta 1.9.0b4 installed by `pip3 install`

#### EXPECTED BEHAVIOR

preview column won't mix up current file with previous file

#### CURRENT BEHAVIOR

preview column mixes up current file with previous file (check the attached gif file)

#### STEPS TO REPRODUCE

1. scroll between images file and normal files like text or pdf
2. check the 3rd column which shows the preview for the current file

#### TRACEBACK

```

```

#### IMAGES / VIDEOS

![recorded](https://cloud.githubusercontent.com/assets/2135996/23091574/de541092-f57e-11e6-9274-7f6ea152021a.gif)

**Comment by nfnty** [comment]
Are all your config files up to date? Try recopying all config files.
Does this happen on `1.8.1`?
Does this happen without tmux?

**Comment by c02y** [comment]
This happens with or without tmux even when I'm using default configuration after `ranger --copy-config=all`

As for v1.8.1, I did't notice this problem when I'm using that old version.

Can't you reproduce it?

**Comment by nfnty** [comment]
No, I can't.

Could you do a git bisect?

**Comment by c02y** [comment]
Sorry, I'm not familiar with `git bisect`, what can I do?

**Comment by nfnty** [comment]
Read https://git-scm.com/docs/git-bisect or the man page `git-bisect(1)`.

**Comment by c02y** [comment]
After completely removing old ranger related files in the my system and install ranger again, the problem is gone, there are lot of files of old versions of ranger in my system, this must be caused by the mess of old version ranger installed using `sudo python3.5 setup.py install --optimize=1 --record=install_log.txt ` and version installed by `sudo pip3 install`.

**Comment by nfnty** [comment]
Alright.

**Comment by MahrezBH** [comment]
I faced this problem and that I solve it using the borders option in rc.conf
`set draw_borders true
`
