### ISSUE TITLE
--version doesn't print python and gcc version ranger was built with.

### ISSUE THREAD

**Issue by azes** [ranger/ranger#812]
After this commit:
https://github.com/ranger/ranger/commit/bd44cd7539fe018c1453dee8ff3de72f98515259
--version prints that:
```ranger-master 1.8.1```
Instead of that that:
```
ranger-master 1.8.1

Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118]
```

**Comment by nfnty** [comment]
It's intentional. And no, it didn't use to report the Python version that ranger was "built with".

**Comment by nfnty** [comment]
But upon further thinking, it may be beneficial to report Python runtime version to ease issue reporting for non-crashes.

**Comment by nfnty** [comment]
Thanks!
