### ISSUE TITLE
Change default terminal to Konsole

### ISSUE THREAD

**Issue by aidanharris** [ranger/ranger#814]
#### ISSUE TYPE

- Bug report

#### RUNTIME ENVIRONMENT

ranger-stable 1.8.1

Python 3.6.0 (default, Jan 16 2017, 12:12:55) 
[GCC 6.3.1 20170109]
- Operating system and version: 
Arch Linux
- Terminal emulator and version: 
konsole 16.12.2
- Locale: 
en_GB.UTF-8

#### EXPECTED BEHAVIOR

Please open in Konsole :P

#### CURRENT BEHAVIOR

Ranger (or my DE / WM that launches ranger) tries to open Gnome Terminal (even though it isn't installed)

#### CONTEXT

I would like to change the default terminal ranger uses from Gnome Terminal to Konsole

#### POSSIBLE SOLUTIONS

I've hacked around the issue via the following shell script (aptly named gnome-terminal) but something tells me this isn't *the right way*™:

```bash
#!/bin/bash
if [[ -z $1 ]]
then
        /usr/bin/konsole
        exit
fi

/usr/bin/konsole "$(echo $@ | sed 's/-x/-e/g')"
```

Ideally if there's some sort xdg mimetype / property I should change this and ranger (or my DE / WM that launches ranger) should respect this. If not then I guess my hack will have to stand...

**Comment by nfnty** [comment]
When is this happening? Steps to reproduce? Run with `ranger --clean` and test again.

**Comment by aidanharris** [comment]
@nfnty It happens when I launch it via an application launcher (using the .desktop file). I suspect this is nothing to do with ranger and instead everything to do with my WM (Awesome - launched via a GNOME session) and / or Gnome. I'm posting in case anyone has a solution.

Any idea how a desktop environment determines (or is supposed to determine) what is the default terminal application, and if there's a way to change it?

**Comment by nfnty** [comment]
https://wiki.gentoo.org/wiki/Awesome#Configuration_file
