### ISSUE TITLE
Warning before exit when file transfer is in progress.

### ISSUE THREAD

**Issue by kun-zhou** [ranger/ranger#816]
#### ISSUE TYPE

- Improvement/feature request

Does ranger currently support warning before exit when file transfer is in progress? I think this is a ready handy functionality to have.

**Comment by nfnty** [comment]
Yes, implemented in 3fa65ae8bb8cca86742a4f4bf2980a9827aac748.

**Comment by nfnty** [comment]
Duplicate of #739.
