### ISSUE TITLE
Browsing remote directories

### ISSUE THREAD

**Issue by hut** [ranger/ranger#83]
It would be great if ranger could browse remote directories via ssh, ftp and so on, as discussed in [1].  sshfs/ftpfs is somewhat inflexible.

[1] http://lists.nongnu.org/archive/html/ranger-users/2013-01/msg00016.html

**Comment by AnderRasoVazquez** [comment]
Has been made any progress on this? I think this could be a great feature.

**Comment by lamarpavel** [comment]
How about a defined way to utilize sshfs within ranger? Something as simple as a command to parse ~/.ssh/config, let the user select one of the available hosts and create a mountpoint somewhere only the current user has access. Unmount when ranger closes or the user issues another command specifically for that.

I realise that users could just bind such a command to a key, but having ranger provide some basic UI mechanics for listing available hosts or track mounted targets would be neat.

**Comment by nfnty** [comment]
Just mount the remote resources into local directories. This will vary widely between users, so custom mappings/commands/plugins is the way to go.
