### ISSUE TITLE
Problem with preview

### ISSUE THREAD

**Issue by HanaO00** [ranger/ranger#830]
Hello, i have ranger and w3m, but my preview looks like this

http://i.imgur.com/RlLC3Jm.png

Can someone help me ?

**Comment by nfnty** [comment]
ASCII preview is enabled in your `scope.sh`. Start by reading the man page `ranger(1)` and https://github.com/ranger/ranger/wiki/Image-Previews.

If your problem persists, then open a new issue and completely fill in the template.
