### ISSUE TITLE
Question on Wiki : Integration with fzf

### ISSUE THREAD

**Issue by j-degreef** [ranger/ranger#832]
On this [page in the wiki](https://github.com/ranger/ranger/wiki/Commands) in the fzf integration section it's said
 
> Find a file using fzf.

> With a prefix argument select only directories.

Does anyone know what should be this prefix and how to enter it ?

Thanks in advance

**Comment by nfnty** [comment]
What that command means by "prefix argument" is a quantifier, i.e. pressing a number before a mapping. You can read a bit more about it in the man page `ranger(1)` if you search for `quantifier`.

**Comment by j-degreef** [comment]
My bad, I searched Google instead of rtfm.
Thanks a lot.
