### ISSUE TITLE
Jumps to target when starting in symlinked directory

### ISSUE THREAD

**Issue by zyklotomic** [ranger/ranger#837]
#### ISSUE TYPE

- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version: Gentoo
- Terminal emulator and version: xterm
- Python version: 3.4.5
- Ranger version/commit: Latest

#### EXPECTED BEHAVIOR

When ranger is started in a symbolic directory, ranger should be displaying the symbolic directory. 

#### CURRENT BEHAVIOR

I am not sure if this is actually intended behavior, but when ranger is entered in a symbolic directory, ranger directly goes into the original directory.

**Comment by nfnty** [comment]
Can't reproduce.

**Comment by zyklotomic** [comment]
Upon further experimentation, I believe this is just an issue of the way ranger is displaying symbolically linked dirs. When I use `S` to escape into the shell, I get dropped back into the actual symbolically linked target directory. When I start ranger, it does not show the target directory but the source. 

Just for clarification, 
If I ` $ ln -s A B `, and ` B $ ranger `, ranger shows directory A.

**Comment by nfnty** [comment]
Thanks!

**Comment by Vifon** [comment]
@nfnty Did you reproduce this? I cannot.

**Comment by nfnty** [comment]
@Vifon Indeed. It had to do with `os.getcwd()` only returning the dereferenced path. I.e. cd to a symlinked path and start ranger.
