### ISSUE TITLE
Code Highlight breaks text preview

### ISSUE THREAD

**Issue by ghost** [ranger/ranger#838]
#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT
- Operating system and version:  Nixos Unstable
- Terminal emulator and version:  termite, urxvt, xterm, st
- Python version: 2.7.13
- Ranger version/commit: 1.8.1

#### EXPECTED BEHAVIOR
Preview highlighted code

#### CURRENT BEHAVIOR
Installing ```highlight``` breaks text previews, in effect showing an empty
preview space. Uninstalling ```highlight``` brings back *plain* previews.

#### TRACEBACK
Cant see anything in the log

**Comment by nfnty** [comment]
Test running from `master` and update all your config files.

**Comment by hut** [comment]
Closing issue because of no reproducibility and idleness of author
