### ISSUE TITLE
Sort hex numbers

### ISSUE THREAD

**Issue by amerlyq** [ranger/ranger#839]
#### ISSUE TYPE
- Bug report (potential)

#### RUNTIME ENVIRONMENT
ranger-stable 1.8.1
Python 3.6.0 (default, Jan 16 2017, 12:12:55)
[GCC 6.3.1 20170109]

#### EXPECTED BEHAVIOR
Filenames named in hexcodes must be monotonous ascending in natural sort

#### CURRENT BEHAVIOR
Order is decided by filename prefix part which resembles number and the rest of filename is ignored:
```
7f838000
7fff7000
00400000
0057a000
00584000
72bae000
72baf000
72dae000
72daf000
72fae000
72faf000
729ae000
729af000
73bae000
```

#### CONTEXT
* irritating to switch to basename sort each time
* often forget to do this and therefore mess relative order when analysing dumps

#### POSSIBLE SOLUTIONS
For natural sort take into account if filename contains non-digits and then treat whole filename as text.
And only if filename contains digits only -- then treat filename as number when sorting.
Current natural sort behavior seems to decide number/text by filename prefix only, which is wrong.

#### STEPS TO REPRODUCE
Copy filelist in 'current behaviour' then touch them:
$ xsel -ob | xargs touch

**Comment by nfnty** [comment]
That's exactly how natural sort works (exactly like `ls -v`).

Either you switch to basename sorting permanently (possibly locally) or you learn how to deal with having to switch temporarily.

Another possibility is to implement a special sorting method plugin. See the `examples` directory for more info.

**Comment by amerlyq** [comment]
Yup, I understand now. Thanks.
It's time for yet another sorting plugin. Sigh.
