### ISSUE TITLE
Image preview not working when no local scope.sh present

### ISSUE THREAD

**Issue by freed00m** [ranger/ranger#840]
From upgrading instruction I understood that no local file **scope.sh** wouldn't be necessary if no intention of customizing it.
>  To update them, simply deleting them should suffice, because then the default ones will be used

#### ISSUE TYPE

- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version: Manjaro stable i3wm community edition
- Terminal emulator and version: urxvt v9.22 - released: 2016-01-23
- Python version: 3.6.0
- Ranger version/commit: ranger-stable 1.8.1, GCC 6.3.1 20170109
- Locale: us

#### EXPECTED BEHAVIOR

ranger's image preview should work without locale copy of 'scope.sh' 

#### CURRENT BEHAVIOR

I have to keep the updated scope.sh in ./config/ranger/scope.sh despite no intention to change it

When I remove the ./config/ranger/scope.sh the ranger works but the image preview wont.

#### POSSIBLE SOLUTIONS

I am thinking of some path issue??

#### STEPS TO REPRODUCE

1. delete .config/ranger/scope.sh and make sure you don't have environment var RANGER_LOAD_DEFAULT_RC set
2. have imagepreview set to true and use w3m method
3. Experience image preview not to work
4. ~$ ranger --copy-config=scope
5. run ranger and see that image preview again works

**Comment by nfnty** [comment]
The path has to be set explicitly in your config. ranger notifies you if no `scope.sh` can be found.

This has been clarified in the updated man page.

**Comment by nfnty** [comment]
You can now use the default `scope.sh` by just commenting out the `preview_script` setting in your `rc.conf`.
