### ISSUE TITLE
ranger with gvim --remote-silent problem

### ISSUE THREAD

**Issue by youlyst** [ranger/ranger#843]
hi there

i have EDITOR variable set to "/usr/bin/gvim --servername default --remote-silent"
if i open text file for editing from ranger it opens two buffers instead of only one for selected file.
one for file and one with file called "--", and this also become active buffer.

i can't figure out, what it causes, but for example mc(midnight commander) don't have such issue.

if gvim is called without "--remote-silent" option ranger opens properly only one file.

have you any advice for me?

**Comment by Vifon** [comment]
Check your `rifle.conf`. It runs the editor command as `$EDITOR -- file` to prevent the file being interpreted as an option if it's named `--like-this`. It seems gvim or this particular set of gvim flags doesn't support it so you can remove `--` from the call in `rifle.conf`.

**Comment by youlyst** [comment]
thanks, that's exactly it ;)
