### ISSUE TITLE
Upgrade to GPL 3.1

### ISSUE THREAD

**Issue by hut** [ranger/ranger#845]
ranger is 8 years old now, and it's time to fix some mistakes that stuck with us since the early days. One of those is the fact that we have no "GPL 3 **or later**" clause in the license text, just plain "GPL 3". But the world of free software moves ahead and we need to stay on top of our game. Civil liberties are taken from us every day and we have to fight with every weapon that we have.

So I initiated the cumbersome procedure of upgrading the license to [GPL 3.1](https://github.com/23x/stoll-klangbrett/blob/master/LICENSE), by mailing every contributor of ranger and asking for their permission to change GPL 3 to GPL 3.1.

Currently I have 22 confirmations of the 85 contributors, and I could not reach 5 of them (their code may need to be removed from ranger).

If over 50% of the contributors agree and the major parts of ranger are covered (git-integration, image/video previews, M-x butterfly), I will proceed with the upgrade to 3.1.

**Comment by hut** [comment]
The efforts to push for [GPL 3.1](https://github.com/23x/stoll-klangbrett/blob/master/LICENSE) have been cancelled due to April Fools being over :D.

**Comment by tex** [comment]
Ehh, you got me :-)   (and yes, I hate April Fools day)
