### ISSUE TITLE
Hardcoded incorrect path to scope.sh

### ISSUE THREAD

**Issue by Grimy** [ranger/ranger#849]
Ranger always looks for scope.sh inside ~/.config/ranger ([responsible line](https://github.com/ranger/ranger/blob/ad58add9e0e6cb4675b231d967ff2204eabad4c3/ranger/config/rc.conf#L46)). This is incorrect: ranger should instead look inside [$XDG_CONFIG_HOME](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.7.html)/ranger.

This is aggravated by the fact that `ranger --copy-config=scope` will (correctly) copy scope.sh to $XDG_CONFIG_HOME/ranger. One would imagine that ranger would be able to find config files it itself created.

#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT
- Operating system and version: Arch Linux 4.9.6-1
- Terminal emulator and version: irrelevant; the issue can be reproduced even when ranger isn’t attached to a pty.
- Python version: Python 3.6.0 (default, Jan 16 2017, 12:12:55)
- Ranger version/commit: reproduced on both ranger-stable 1.8.1 and current master (30553796)
- Locale: LANG=en_US.UTF-8, LC_COLLATE=C

#### STEPS TO REPRODUCE
1. `export XDG_CONFIG_HOME=~/not-the-default`
2. `ranger --copy-config=scope`
3. `strace -f ranger 2>&1 | grep scope.sh`

#### EXPECTED BEHAVIOR
Ranger opens and uses $XDG_CONFIG_HOME/ranger/scope.sh:

    stat("~/not-the-default/ranger/scope.sh", ...) = 0

#### CURRENT BEHAVIOR
Ranger looks for ~/.config/ranger/scope.sh and fails if it doesn’t exist:

    stat("~/.config/ranger/scope.sh", ...) = -1 ENOENT (No such file or directory)

#### CONTEXT

This issue prevents image previews from working. As a workaround, I created the directories ~/.config and ~/.config/ranger and copied my scope.sh in there; this lets image previews work, but is obviously not a proper solution.

#### POSSIBLE SOLUTIONS
Just change [this line](https://github.com/ranger/ranger/blob/ad58add9e0e6cb4675b231d967ff2204eabad4c3/ranger/config/rc.conf#L46) to use $XDG_CONFIG_HOME instead of hard-coding .config.

**Comment by randynobx** [comment]
What exactly is being requested?

If it is just a change to rc.conf, then that is something you can do locally.

Or if it is the handling of the env variable in total by ranger, then more detail regarding what exactly should be changed would be appreciated.

**Comment by randynobx** [comment]
After further reading in to the code:

Ranger does indeed look for XDG_CONFIG_HOME, as well as XDG_DATA_HOME and XDG_CACHE_HOME, by default.

Code here: https://github.com/ranger/ranger/blob/b327b7352e10909d4713d3c802c4c34945523e2b/ranger/core/main.py#L253

When you run the `--copy-config=scope` command, ranger is actually copying that file to the correct location (your $XDG_CONFIG_HOME/ranger). But your rc.conf has not been updated to reflect that you have a non-standard XDG_CONFIG_HOME path (that is, `~/.config`).

All the config files (rc.conf, commands.py, rifle.conf, and scope.sh) are meanted to be user edited to their unique needs and preferences.

I don't believe that this is something that should be changed in the default configs, but @hut or @nfnty should make that call.

**Comment by Grimy** [comment]
Let me put this into context. I tried to get image previews to work. I followed the exact steps listed [in the wiki](https://github.com/ranger/ranger/wiki/Image-Previews#with-w3mimgdisplay). It didn’t work. It didn’t give any error or warning. After a solid hour of troubleshooting, I finally noticed (thanks to strace) that ranger was trying to load `~/.config/ranger/scope.sh`, which didn’t exist. This is not a good user experience, and I’d like to save other users from going through the same thing.

> If it is just a change to rc.conf, then that is something you can do locally.

The entire point of XDG_CONFIG_HOME is to have a centralized way to change the location of all user-specific configuration. It’s supposed to act as a Single Source of Truth, and all applications I know respect that—all except ranger.

> What exactly is being requested?

Here are a list of (mutually exclusive) suggestions, in decreasing order of preference:

* Change the default rc.conf to look inside `$XDG_CONFIG_HOME` rather than `~/.config`. This is a one-line change; I’ll send a PR implementing it.

* Replace all uses of $XDG_CONFIG_HOME with a hardcoded `~/.config`. This violates the XDG Base Directory spec, but at least it means that ranger isn’t broken by default for users with a non-default $XDG_CONFIG_HOME.

* Whenever ranger is started with a non-default $XDG_CONFIG_HOME, print a bold red warning: `ranger does not support non-default $XDG_CONFIG_HOME; some features may not work correctly`.

* Edit https://github.com/ranger/ranger/wiki/Image-Previews#with-w3mimgdisplay to give instructions that work for all users, not just those with a default $XDG_CONFIG_HOME (this means avoiding any mention of `ranger --copy-config=scope`).

**Comment by nfnty** [comment]
Part of the problem was that the configuration error wasn't logged.

The settings parser isn't environment aware at this point, so using `$XDG_CONFIG_HOME` won't work.

None of your proposed changes will fix this properly and as several users have reported similar issues before a proper fix is required.

**Comment by nfnty** [comment]
Thanks! Just comment out the setting in your `rc.conf` to get the default now.

**Comment by Grimy** [comment]
Thanks, this fixes it for me. However, I think there’s a small regression here. On a clean install of 51e86c62, running `ranger --clean` gives me:

```Preview script `/usr/lib/python3.6/site-packages/ranger/data/scope.sh` is not executable!```

Running `chmod +x /usr/lib/python3.6/site-packages/ranger/data/scope.sh` fixes it; maybe this should be done in the setup.py?

**Comment by nfnty** [comment]
Yep, pushing a fix in a minute.

**Comment by j-degreef** [comment]
Is it me or my comment has disappeared ?
Tested the latest master, it works ;)
