### ISSUE TITLE
Incorrect cursor movement in console for long text at the ends

### ISSUE THREAD

**Issue by wasamasa** [ranger/ranger#852]
#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version: Arch Linux
- Terminal emulator and version: Termite 12-1
- Python version: ranger-master 1.9.0b5
- Ranger version/commit: ranger-master 1.9.0b5
- Locale: ranger-master 1.9.0b5

#### EXPECTED BEHAVIOR
When editing long text in the console (such as when renaming a file with a name exceeding the terminal's width), I expect cursor movement to correspond to the keys pressed, like, pressing `<left>` should result in the cursor moving by one column to the left.  If necessary, scrolling should happen to display the rest of the text.

#### CURRENT BEHAVIOR
With long text, movement at the ends does *not* happen.  If I'm at the rightmost position and hit `<left>`, I don't see the cursor move, however insertion of text adds a character at that position.  After moving a sufficient amount to the left, hitting `<left>` results in the expected cursor movement.  The exact amount of text to move beyond appears to depend on how much longer the console contents are than the terminal's width.

#### CONTEXT
Renaming files with long names is rather annoying as I can't easily move to the problematic part and edit it due to the lack of visual feedback.  Blindly editing text without cursor at the position it should be is error-prone and tedious.

#### POSSIBLE SOLUTIONS
I'm not sure how this should be fixed.  It could be something as fundamental as the underlying ncurses widget not supporting text wrapping.  I'd need to look into how this whole thing works before making a proper suggestion.

#### STEPS TO REPRODUCE
1. Visit file with a name longer than the terminal width
2. Hit `A`, then `<left>` to navigate one column before the end
3. See the cursor stay in place.

**Comment by Rom1deTroyes** [comment]
Le Monday 10 Apr 2017 à 11:27:19 (-0700), Vasilij Schneidermann a écrit :

Isue reproducted with Debian 8 (stable version).

#### RUNTIME ENVIRONMENT

- Operating system and version: Debian 8 stable
- Terminal emulator and version: urxvt-256
- Python version: Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
- Ranger version/commit: ranger-stable 1.6.1
- Locale: fr


#### CURRENT BEHAVIOR
When playng with "Full screen" mode in i3,you can handle the problem
clearly :
- when filename is shorter than your terminal columns, the line starts
  with `:rename ` and the file name,
- when the terminal has lesser columns, the line displayed starts with
  `:`and *the end* of the filename (the begining of the file name is
  truncated), but the cursor is counted from the left of the file name
  (the complete one, not the truncated).

So you could also see the cursor at a bad place !

#### STEPS TO REPRODUCE
1. launch ranger
2. Hit `:` then type text (let's say 123456789112345678921234567893)
3. Play with terminal width ([Mod]+f in i3, or you can surely play with
   your mouse in other window manager).

++
    Romain
-- 
Les Etats-Unis sont le seul pays à être passé de la barbarie
à la décadence sans connaître la civilisation.
	-+- Albert Einstein -+-

**Comment by hut** [comment]
fixed by #910

**Comment by wasamasa** [comment]
Wow, I didn't expect this to happen. Thanks so much!
