### ISSUE TITLE
When opening $EDITOR via "vimer", unexpected results

### ISSUE THREAD

**Issue by matthiasbeyer** [ranger/ranger#854]
I use the [vimer script](https://github.com/susam/vimer) for opening things via $EDITOR variable in one gvim instance. This does not work well with ranger - the file `--` gets opened when opening a file via ranger.

#### ISSUE TYPE

- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version: nixos unstable: 17.09pre105622.f0fac3b578 (Hummingbird)
- Terminal emulator and version: XTerm(327)
- Python version: 2.7.13
- Ranger version/commit: ranger-stable 1.8.1

#### EXPECTED BEHAVIOR

`vimer` (`$EDITOR`) gets called in a way that the file gets opened, not `--`.

#### CURRENT BEHAVIOR

The file `--` gets opened.

#### CONTEXT

Opening a file.

#### POSSIBLE SOLUTIONS

I think a configuration option to set the commandline how the editor is called would be a good way.

#### STEPS TO REPRODUCE

1. Set `$EDITOR` to `vimer` (have `vimer` installed in `$PATH`)
2. Try opening a normal text file with ranger

**Comment by randynobx** [comment]
The configuration option you are looking for is in the rifle.conf file in the config directory (usually ~/.config/ranger/rifle.conf).

Here are the relevant lines in rifle.conf for you:

line 86:
`mime ^text,  label editor = $EDITOR -- "$@"`

line 88:
`!mime ^text, label editor, ext xml|json|csv|tex|py|pl|rb|js|sh|php = $EDITOR -- "$@"`

line 207:
`label editor, !mime ^text, !ext xml|json|csv|tex|py|pl|rb|js|sh|php  = $EDITOR -- "$@"`

You should be able to just remove the -- from those lines.

 **HOWEVER**, please be aware that the -- flag tells most editors (I've tested on vim and nano, I imagine Emacs and other common text editors recognize this as well) that everything following it is a filename. This is as security feature to prevent accidental application of flags when they are not wanted (it will open a new file named -V, for example).

It appears that vimer does not recognize this in the same way as the actual editors do, and simply opens it as a file. You can either change rifle.conf to not use --, or you could submit a patch for vimer to support --.

Should you choose to edit rifle.conf, know that you are putting yourself at some level of risk of unforseen bugs with rifle/ranger! It should **not** be an issue, but I do want to let you know about it in case you encounter bugs after changing it.

Let me know if this fixes your issue!

**Comment by matthiasbeyer** [comment]
It fixes my issue if I replace `$EDITOR --` with `vimer` - which is my gvim wrapper script (mentioned above).

Thanks!
