### ISSUE TITLE
ranger won't refresh preview column when previewing images and files

### ISSUE THREAD

**Issue by x4121** [ranger/ranger#859]
Similar to #811, I get some strange effects when previewing images.
Bug stays even after deleting old ranger version (installed with apt) and building new version from current master.
Deleted `~/.config/ranger` directory, ran `ranger --copy-config all` and changed `preview_images` to true.

#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT
- Operating system and version: Ubuntu-Gnome 17.04
- Terminal emulator and version: konsole 16.12.3
- Python version: Python 3.5.3
- Ranger version/commit: ranger-master 1.9.0b5
- Locale: en_US.UTF-8

#### EXPECTED BEHAVIOR
- image preview redraws over previous images
- image preview "clears" after closing ranger

#### CURRENT BEHAVIOR
- some images are cropped
- small images are drawn over previous images
- image parts stay after closing ranger if terminal contains long texts

#### STEPS TO REPRODUCE
(see video)

#### TRACEBACK

```
Traceback (most recent call last):
  File "/usr/local/bin/ranger", line 41, in <module>
    sys.exit(ranger.main())  # pylint: disable=no-member
  File "/usr/local/lib/python3.5/dist-packages/ranger/core/main.py", line 222, in main
    fm.ui.destroy()
  File "/usr/local/lib/python3.5/dist-packages/ranger/gui/ui.py", line 171, in destroy
    DisplayableContainer.destroy(self)
  File "/usr/local/lib/python3.5/dist-packages/ranger/gui/displayable.py", line 291, in destroy
    displayable.destroy()
  File "/usr/local/lib/python3.5/dist-packages/ranger/gui/displayable.py", line 291, in destroy
    displayable.destroy()
  File "/usr/local/lib/python3.5/dist-packages/ranger/gui/widgets/pager.py", line 71, in destroy
    self.clear_image(force=True)
  File "/usr/local/lib/python3.5/dist-packages/ranger/gui/widgets/pager.py", line 60, in clear_image
    self.fm.image_displayer.clear(self.x, self.y, self.wid, self.hei)
  File "/usr/local/lib/python3.5/dist-packages/ranger/ext/img_display.py", line 146, in clear
    self.process.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

```

#### IMAGES / VIDEOS
![ranger](https://cloud.githubusercontent.com/assets/516123/25432614/6da27956-2a85-11e7-8edb-afb4c389c7b8.gif)

**Comment by x4121** [comment]
https://github.com/x4121/dotfiles/issues/3

**Comment by Jab2870** [comment]
I am also experiencing similar issues

**Comment by dvejmz** [comment]
I'm also having this issue, but only in Konsole.

I cannot reproduce the problem in urxvt or gnome-terminal in the way Konsole interprets the request of `W3MImageDisplayer` to clear the previous image.

**Comment by dvejmz** [comment]
I did a bit more digging around... This may be an issue with `w3mimgdisplay` itself rather than ranger. `w3mimgdisplay` is written primarily with [`xterm`](https://bugs.kde.org/show_bug.cgi?id=57051#c2) and similar terminal emulators (`rxvt`) in mind.

I ran a few tests against my installed w3m binary (version `w3m/0.5.3+git20170102`) in isolation and found the same problems. I used [this script](https://gist.github.com/dvejmz/662ef4e12cc00c2eb1d495f1720d6de8) to easily draw and clear images on the terminal screen (the script was originally posted [here](http://blog.z3bra.org/2014/01/images-in-terminal.html)).

After `w3mimgdisplay` in several different terminals, I could see there are various degrees of "broken", Konsole and Termite being one of the most broken, for instance. `xterm` seems to work *almost* flawlessly

![859-xterm](https://user-images.githubusercontent.com/9487006/31693548-1b145704-b397-11e7-8c20-793a001ae228.gif)

`gnome-terminal` kinda works but a "clear image" w3m-img op will black out the portion of the screen corresponding to the image instead of actually clearing it, as you can see here

![859-gnome-terminal](https://user-images.githubusercontent.com/9487006/31693553-2188d880-b397-11e7-8cee-59c8404e5ed7.gif)

As is already known, `urxvt` handles w3mimgdisplay nicely too (although not quite as nicely as `xterm`, but it's up there).

I've [dropped this issue at w3m's doorstep](https://github.com/tats/w3m/issues/94) to see what they make of it, but I guess for the time being we'll have to make do with what we've got or use a supported terminal :/

At any rate, there are also talks of using a generic, cleaner image displayer [like Sixel](https://github.com/ranger/ranger/issues/723) so perhaps we should pool our efforts to get that going instead...

**Comment by aureooms** [comment]
Same issue with terminator.

**Comment by p3lim** [comment]
Same with termite.

**Comment by djgalvan** [comment]
Using termite, I don't seem to have issues viewing previews, although a black background does remain when previewing images of different sizes and will remain when navigating into a different directory. I find that if I could automatically send redraw_window when leaving a preview there would be no issues, but have no idea where or how to implement this.

**Comment by duffydack** [comment]
Same as what @djgalvan wants.  If I could have it redraw the window between each file preview, ranger+termite would be perfect.

**Comment by AlexK-IL** [comment]
Sane issue here, using ranger with konsole too.  
`redraw_window` doesn't seem to do anything but somehow hitting `ctrl` clears the image.

**Comment by toonn** [comment]
Just `ctrl` or `ctrl-l`?

**Comment by freed00m** [comment]
@toonn For me ctrl-l clears it and I am using gnome-terminal.

Also moving mouse cursor over drawn image can removes cca 20px row from the image + the image leftover is often draw over other aps like nautilus. :D so I think it's a xorg issue

**Comment by AlexK-IL** [comment]
@tonttu Both `ctrl` or `ctrl-l` clear the image for me.

**Comment by tonttu** [comment]
@AlexK-IL that's great, but I think you meant to tell that to @toonn .

**Comment by fbob** [comment]
same issue here
ranger --v
ranger-stable 1.8.1

Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0]

konsole 17.12.3 on ubuntu 18.04

**Comment by x4121** [comment]
Finally getting rid of konsole and replacing it with alacritty "fixed" it for me. Works flawlessly now :wink:

**Comment by Vifon** [comment]
Everybody, please check if the issue still occurs after d9bb560. Remember to run `./ranger.py -c` or update `rc.conf` because the new `w3m_delay` is crucial here.

**Comment by duffydack** [comment]
I've setup urxvt and set ranger to use 'urxvt' for image previews, works much better (although slightly slower).

**Comment by thothonegan** [comment]
Running current master, with Konsole 18.04.1, it seems to work if i go over a lot of non-images before some images. If i reverse direction in the middle of images (e.g. if you're going down the list, you start going back up), it doesn't clear properly, and if i start ranger in a folder with just images it doesn't clear properly (using w3m_delay 1 as an extreme).

**Comment by thothonegan** [comment]
Sorry for the noise, that's still the same w3m bug already noted earlier in the thread.

**Comment by Wiadomy** [comment]
Same issue here.

xfce4-terminal 0.8.7.4-1
ranger-master 1.9.1

**Comment by Luxed** [comment]
@Vifon The commit hasn't resolved the issue for me :/ The delay doesn't do anything unfortunately (it delays the loading of the image but the old one is still present under).
Pressing <Ctrl-L> refreshes the screen and removes the old images.

Terminal: Termite v13
Ranger: ranger-master 1.9.2
Python: 3.7.0

**Comment by Vifon** [comment]
Which preview method do you use?

**Comment by Luxed** [comment]
oh, I'm so sorry I didn't write that in the comment: I use w3m

**Comment by toonn** [comment]
Maybe the termite version? Isn't there a patch termite for w3m?

**Comment by ykyuen** [comment]
Same problem for w3m, termite in archlinux.

ranger: 1.9.2.2.g8e9451e6-1
termite: 13-3
python: 3.7.0 (default, Sep 15 2018, 19:13:07) [GCC 8.2.1 20180831]

already set the `w3m_delay` in `rc.conf` but still got the same problem.
![sc-2018-10-02-10-09-41](https://user-images.githubusercontent.com/281210/46325554-5fec1180-c62b-11e8-9003-5ffdf127b977.jpg)

**Comment by toonn** [comment]
[This is the patch](https://aur.archlinux.org/packages/termite-ranger-fix-git/) I was referring to.

**Comment by XakepSDK** [comment]
user@arch ~/.config/ranger % ranger --version
ranger version: ranger-master 1.9.1
Python version: 3.7.0 (default, Sep 15 2018, 19:13:07) [GCC 8.2.1 20180831]
Locale: en_US.UTF-8

user@arch ~/.config/ranger % termite --version
termite v13

user@arch ~/.config/ranger % w3m -version
w3m version w3m/0.5.3+git20180125, options lang=en,m17n,image,color,ansi-color,mouse,gpm,menu,cookie,ssl,ssl-verify,external-uri-loader,nntp,ipv6,alarm,mark

Same issue

**Comment by zelmor** [comment]
I just wanted to mention that xfce4-terminal in Debian Stable is suffering the same issue. ctrl+l fixes the problem. 

ranger 1.7.1-1
w3m-img 0.5.3-34+deb9u1

**Comment by XakepSDK** [comment]
@toonn same issue

**Comment by ykyuen** [comment]
@toonn i tried the patcted termite and still having the same issue
```
[ykyuen@camus bin]$ ./termite --version
termite v10-152-ga3a888c
```

**Comment by j-degreef** [comment]
Hi,
Just to summarize  the situation, neither d9bb560 (which apparently only add a comment in the code), neither "set w3m_delay 0.02" (which just delay image display) an neither [https://aur.archlinux.org/packages/termite-ranger-fix-git/] solve this problem.
Tested on Archlinux uptodate
Termite v13
Ranger version: ranger-master 1.9.1
Python version: 3.7.0 (default, Sep 15 2018, 19:13:07) [GCC 8.2.1 20180831]
W3m version w3m/0.5.3+git20180125
Locale: en_US.UTF-8
 
Only ctrl-l permits to refresh the screen to clean the previous image which is displayed in the background of the current one.

I don't know the code enough to be sure but it seems the right part of the screen is refreshed each time a new text is displayed when browsing directories.
Wouldn't it be possible to make the same for images : simulate a ctrl-l each time a new image or a new text is displayed on a previous image. This would avoid to have image displaying on another one or text displaying on top of an image....

**Comment by Zaeph** [comment]
On a related note (since it’s probably due to terminator+w3m), the previewed images are overlapping with the file's path on my end.

![screen1](https://user-images.githubusercontent.com/12202828/47620581-d7f30d80-daeb-11e8-8cdc-f161bf0420aa.jpg)
(Note that I'm also experiencing the same issue with stacking previews.)

The problem is somewhat alleviated by setting `draw_borders` to `true`, but it’s still off:

![screen4](https://user-images.githubusercontent.com/12202828/47620575-d295c300-daeb-11e8-9f2b-18b849b6e687.jpg)

**Comment by herod2k** [comment]
Same issue here.

I have removed ranger and cleared the config files. I have reinstalled it directly from git. I've enabled the image preview inside rc.conf
```
set preview_images true
```
as indicated here: `https://github.com/ranger/ranger/wiki/Image-Previews`

And I'm still getting the error.

I'm using ranger 1.9.2
```
ranger version: ranger-master 1.9.2
Python version: 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
Locale: None.None
```
Terminals: Terminator 1.9.1 and Gnome-terminal (3.28.2)
Operating system: Ubuntu 18.04 + i3-gaps

The problem shows when I preview an image and it persists until I press ctrl-l or I remove the focus from the windows (for this reason I couldn't take a better screenshot, sorry)
![photo_2018-12-04_11-41-23](https://user-images.githubusercontent.com/3713164/49440283-2797b980-f7bb-11e8-84ed-4da819440956.jpg)

**Comment by toonn** [comment]
All terminals based on libVTE are probably affected by this issue to varying degrees. This includes gnome-terminal, terminator, termite and more.

**Comment by SlidingHorn** [comment]
This appears to also affect mate-terminal

**Comment by itgoyo** [comment]
> Same issue here.
> 
> I have removed ranger and cleared the config files. I have reinstalled it directly from git. I've enabled the image preview inside rc.conf
> 
> ```
> set preview_images true
> ```
> as indicated here: `https://github.com/ranger/ranger/wiki/Image-Previews`
> 
> And I'm still getting the error.
> 
> I'm using ranger 1.9.2
> 
> ```
> ranger version: ranger-master 1.9.2
> Python version: 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
> Locale: None.None
> ```
> Terminals: Terminator 1.9.1 and Gnome-terminal (3.28.2)
> Operating system: Ubuntu 18.04 + i3-gaps
> 
> The problem appears when I preview an image and it persists until I press ctrl-l or I remove the focus from the window (for this reason I couldn't take a better screenshot, sorry)
> ![photo_2018-12-04_11-41-23](https://user-images.githubusercontent.com/3713164/49440283-2797b980-f7bb-11e8-84ed-4da819440956.jpg)

hello，May I ask you a question? what's your terminal ? is xfce4-terminal or gnome-terminal or i3-sensible-terminal ? I found ranger do not work well in xfce4-terminal.

**Comment by herod2k** [comment]
> hello，May I ask you a question? what's your terminal ? is xfce4-terminal or gnome-terminal or i3-sensible-terminal ? I found ranger do not work well in xfce4-terminal.
I use terminator (mainly) and sometime gnome-terminal. In these terminal ranger works perfectly except for the image preview. 
Otherwise in RXVT-Unicode, ranger doesn't have any problem with the images (but I don't use it).

**Comment by ax3ghazy** [comment]
Same issue here with Konsole and Termite. The issue doesn't happen with Urxvt, Alacritty nor Xfce4-terminal..

**Comment by realestninja** [comment]
Same here. URxvt works fine but when using Terminator and navigating through some images, the preview pane gets all messed up with previous images partly overlapped

**Comment by lucaparmigiani** [comment]
Same issue with zsh.
I solve the problem adding `self.fm.ui.win.redrawwin()` in the method `clear()` of the object W3MImageDisplayer.

```python
try:
            self.fm.ui.win.redrawwin()  # <--- here
            self.process.stdin.write(cmd)
        except IOError as ex:
            if ex.errno == errno.EPIPE:
                return
            raise
        self.process.stdin.flush()
        self.process.stdout.readline(
```
I don't think this is the best way of solving the issue, but not refreshing the image really annoys me.

Also doing this makes small image not visible.
If you watch carefully you can see them printed but then diseapper.

**Comment by huyhoang8398** [comment]
same issues with xfce4-terminal, archlinux, w3m

**Comment by thexavier666** [comment]
same issue with gnome-terminal

**Comment by rodhash** [comment]
> Same issue with zsh.
> I solve the problem adding `self.fm.ui.win.redrawwin()` in the method `clear()` of the object W3MImageDisplayer.
> 
> ```python
> try:
>             self.fm.ui.win.redrawwin()  # <--- here
>             self.process.stdin.write(cmd)
>         except IOError as ex:
>             if ex.errno == errno.EPIPE:
>                 return
>             raise
>         self.process.stdin.flush()
>         self.process.stdout.readline(
> ```
> 
> I don't think this is the best way of solving the issue, but not refreshing the image really annoys me.
> 
> Also doing this makes small image not visible.
> If you watch carefully you can see them printed but then diseapper.

very nice, seems to have fixed the issue .. in some cases it still happens but not always any more!

**Comment by dirtydigs** [comment]
Anyone still looking at this issue, using Konsole I chose the ueberzug method for image preview and no problems at all. Using Manjaro.

**Comment by toonn** [comment]
That's probably the right solution for most people. Note that it's only available in master though. It's coming in the next release, which will happen some time this decade...

**Comment by rubyFeedback** [comment]
This has been recently mentioned on reddit - just giving a bit more context in that it appears to affect some people, perhaps still today (but I am not entirely certain).

https://old.reddit.com/r/kde/comments/nore09/konsoleranger_bug/

**Comment by toonn** [comment]
They should try running the master branch.

**Comment by getashraf** [comment]
> Anyone still looking at this issue, using Konsole I chose the ueberzug method for image preview and no problems at all. Using Manjaro.

This works for me in Konsole, Manjaro KDE.
