### ISSUE TITLE
Cannot start Ranger inside "site-packages" directory

### ISSUE THREAD

**Issue by Chinggis6** [ranger/ranger#861]
Hello. I'm reporting a "bug", I guess.

I can't open (issue the command) ranger inside `/usr/lib/python3.6/site-packages` directory.

I am using URxvt terminal (v 9.22) on Arch Linux (4.10.11).

I get the following output:

```
Traceback (most recent call last):
  File "/usr/bin/ranger", line 38, in <module>
    import ranger
ModuleNotFoundError: No module named 'ranger
```

It works well outside that directory, even in its children, eg. inside `/usr/lib/python3.6/site-packages/ranger`.

Thanks for consideration.

**Comment by Vifon** [comment]
It was caused by [these lines][1]. After some investigation it seems these lines are not needed. I'll push a fix in a few minutes, along with a longer explanation.

[1]: https://github.com/ranger/ranger/blob/ccbcfc60810cba1ef79677a714746d40b34e34e7/ranger.py#L35-L37

**Comment by Vifon** [comment]
Done. Thanks for your report.
