### ISSUE TITLE
urxvt (rxvt-unicode) - HOME and END keys problem

### ISSUE THREAD

**Issue by kajzersoze** [ranger/ranger#862]
I switched recently to urxvt and I've noticed one problem, HOME and END keys were working fine in other terminal emulators, however in urxvt they don't behave as they should.
zsh had the same problem but I solved that one by adding these two lines in the config :
```
bindkey "\e[7~" beginning-of-line
bindkey "\e[8~" end-of-line
```

Could something like that be done with ranger or is there some other way to solve this issue ?

**Comment by randynobx** [comment]
What are your:
- OS/distro (and version)
- Python version
- Ranger version

And are your ranger config files up to date?

**Comment by kajzersoze** [comment]
- Gentoo
- python 3.4
- Ranger 1.8.1

I'm not sure what you mean by ranger config files up to date.

Again, same everything but different terminal emulator and those keys are working.
It's urxvt's problem and I'm just wondering if there's a way to map those keys inside ranger.
When I enter `cat` in terminal and I press HOME key I get `^[[7~^` and for END  `^[[8~^`

**Comment by randynobx** [comment]
When ranger is updated, the configs are not automatically updated. If you have an older config, it might be causing the issue. I cannot replicate the issue using urxvt on my end.

Try running ranger with the --clean (or -c) flag. If that fixes the issue, then the config files contain the issue. You can follow the 'Outdated configuration files' section here: https://github.com/ranger/ranger/wiki/Upgrading

**Comment by kajzersoze** [comment]
Oh I see now, didn't know about that.
Anyway, that didn't fix the issue, still the same.
Do you have anything regarding keys in .Xresources maybe ?

**Comment by Vifon** [comment]
I cannot reproduce it either. Maybe it's some [USE flag](https://packages.gentoo.org/packages/x11-terms/rxvt-unicode) related to the character/key encoding? Do you have it built with the [`unicode3`](https://packages.gentoo.org/useflags/unicode3) flag enabled?

**Comment by kajzersoze** [comment]
I do have it, the ones I don't have are :
```
- - alt-font-width
- - buffer-on-clear
- - iso14755
- - secondary-wheel
```
I don't think they are this issue related, except maybe `iso14755`
I'll try it now with that one enabled.

**Comment by kajzersoze** [comment]
Okay, after some searching I found what was the problem, it was in zsh.

**Comment by Vifon** [comment]
Can you elaborate? What in zsh was causing the issue and how did you fix it?

**Comment by kajzersoze** [comment]
Okay, I used Termite before switching to urxvt and in order to use powerlevel9k theme I had to have this line in .zshrc :
`export TERM="xterm-256color"`

So, when I switched to urxvt that line stayed, I didn't notice any other problems because of that, except in ranger, so when you guys said you couldn't reproduce I was determined to find out what 's causing that problem, it came down to that line. I guess there's some code in ranger that looks for a TERM variable to figure out what terminal is in use, so instead of rxvt-unicode-256color I had xterm-256color
Removing that line from .zshrc solved this problem.
