### ISSUE TITLE
Filter command to only show marked files

### ISSUE THREAD

**Issue by FichteFoll** [ranger/ranger#867]
#### ISSUE TYPE
- Improvement/feature request

#### RUNTIME ENVIRONMENT

skipped

#### EXPECTED BEHAVIOR

A command that filters the file view to only show marked files. In filtered view, unmarking a file/dir should not hide it until the command is run again. Should be re-settable to unfiltered view.

#### CONTEXT

Selecting files sparingly in a large-ish directory can quickly cause you to lose overview. By filtering to only show marked files, you can more easily grasp the context and potentially unselect marked files.

#### POSSIBLE SOLUTIONS

Probably as an argument to `scout`.

**Comment by randynobx** [comment]
I can start working on this once I've finished the global_inode_type filter. A discussion should be had as to how we want to handle new 'custom' filters though, just for the sake of consistancy and maintainability.
