### ISSUE TITLE
System-wide configuration file

### ISSUE THREAD

**Issue by Chinggis6** [ranger/ranger#869]
Is there a system wide configuration file that would apply to all users?

`~/.config/ranger/rc.conf` is per-user configuration file and applies only to the current user.

I'm looking for something like `/etc/inputrc` to apply to all users of the system by default.

Thanks in advance.

**Comment by Vifon** [comment]
Ranger loads the global `rc.conf` file present in ranger's `site-packages` directory (a directory with Python libs and their resources) that was installed along with ranger. For example

```
/usr/lib/python3.5/site-packages/ranger/config/rc.conf
```

On Debian `/etc/ranger/config/rc.conf` is a symbolic link to this file,

**Comment by eMPee584** [comment]
That very much reverses the usual logic.
Even if in addition, `/etc/ranger/rc.conf` should be read as default system-wide configuration file IMHO.

**Comment by hut** [comment]
I have no strong opinion on this, so feel free to implement it if you really want it. I would merge it.

**Comment by eMPee584** [comment]
Hmm.. Seems I still haven't found time to implement it. :laughing: 
So, how about splitting out most (within if not clean) of `load_settings()` into a function `load_settings_from()` and calling `load_settings_from(system_confdir) && load_settings_from(user_confdir)`?
Would it be possible to load the supplied /usr/lib/python2.7/dist-packages/ranger/config/commands.py by default, then overlay /etc/ranger/commands.py on top?
