### ISSUE TITLE
Python process using high CPU

### ISSUE THREAD

**Issue by pencilcheck** [ranger/ranger#87]
I don't understand why the python process are still running after opening a shell at a directory, shouldn't ranger just cd and quit itself?

That's my first impression when I figured that the Python process out of no where is from ranger after opening some shells from ranger.

After doing a small research I found out ranger spawns the shell, but not only I don't know how to resume ranger from the shell, I can't quit ranger easily, and what happen is that Python process would go crazy and uses 100% of CPU of some sort, and I have to go to activity monitor to force quit those Python processes, which would destroy everything, all the shell I have opened from ranger. This is very annoying.

Am I doing it wrong? Or is this some serious bug?

Until this bug is fixed, I don't know if I could still use ranger as directory jumper now :(

**Comment by hut** [comment]
This issue is now 2 years old - does it still occur?

**Comment by bebound** [comment]
It's still occur...
Open rager, using vim to edit file (vim is my default editor), quit vim, quit iTerm.
The a python processing will using 100% cpu.
Open rager, press q, and the problem will solved.

**Comment by hut** [comment]
I'm afraid I don't know how to debug this.

**Comment by nfnty** [comment]
If you're still experiencing this issue open a new issue and completely fill in the issue template.

**Comment by Deluxo** [comment]
sorry for not complying, but this issue is still affecting me. I deleted scope file and problem seems to be solved.

**Comment by Deluxo** [comment]
ok, scope file doesn't matter. This happens even without it.
Seems to happen randomly.
```
ranger-stable 1.8.1

Python 3.6.0 (default, Jan 16 2017, 12:12:55) 
[GCC 6.3.1 20170109]
```

**Comment by ww7w** [comment]
This is still an issue. Removing scope.sh file does fix it.

**Comment by toonn** [comment]
Only thing I can think of is an open issue/PR related to the ranger process not dying if stdin is closed.

**Comment by dylan-chong** [comment]
This is still an issue and removing the scope file does not change anything.

**Comment by toonn** [comment]
We need more info to even start looking into this. Does this happen while you're using ranger? Is ranger working on any previews, check with `w`. Check the log for errors `W`. Does this happen where you're in a network mount? What version of ranger are you running, what version of python, do you use bash or a different shell, does running ranger in a different terminal change anything? How about running `ranger --clean` to see if your config is at fault?

**Comment by dylan-chong** [comment]
I figured out that disabling these options gets rid of the problem.
It only seems to happen on this one git repository which has 3600 files

```
set vcs_aware true
set vcs_backend_git enabled
```

I will get back to you with more information about the details of my setup at some point in the future

**Comment by toonn** [comment]
@dylan-chong, yes, VCS integration is pretty heavy, heavier than any of the previews iirc. So not really surprising. You can disable it for just the troublesome repos using `setinpath` or `setintag` though.

**Comment by ww7w** [comment]
Adding an additional check to prevent nested instances of ranger to my .bashrc seems to have fixed it.
```sh
# Prevent nested ranger instances (courtesy of arch wiki)
ranger() {
    if [ -z "$RANGER_LEVEL" ]; then
        /usr/bin/ranger "$@"
    else
        exit
    fi
}
```
Everything works smoothly now, with or without the scope.sh file.
