### ISSUE TITLE
Conditional configs; how to use if else blocks in config files?

### ISSUE THREAD

**Issue by kutsan** [ranger/ranger#875]
Just a quick question. I couldn't find another issue about that. As I mentioned on the title how to specify a config as conditional form. For example, I want to use different `column_ratios` in my Android device.

So, I need to execute `uname` and load it correct config according to the its result.

**Comment by kutsan** [comment]
Although it's not reliable, I did this as workaround in my shell configs. I could have set the `--cmd` to `column_ratios`.

> .zshrc
```sh
if ([[ $(uname -o) == 'Android' ]] 2>/dev/null) {
    alias ranger="ranger --cmd='set viewmode multipane'"
}
```

**Comment by Vifon** [comment]
You could use `eval` for it. `rc.conf` by itself doesn't support any conditionals.

**Comment by kutsan** [comment]
Could you please show me an example? I don't know Python that much. :(

**Comment by Vifon** [comment]
A quick and dirty try:

```
eval import subprocess; fm.set_option_from_string("viewmode", "multipane") if subprocess.check_output(["uname", "-o"]) != "Android" else None
```

Consider using a different config on Android, for example by using some preprocessing. See:

- [my tmux config](https://bitbucket.org/Vifon/dotfiles/src/1e44cb9cefb72490a7d1425418a6a697b38f75f1/topdir/tmux/.tmux.conf.j2?at=master&fileviewer=file-view-default#.tmux.conf.j2-13:21)
- [my preprocessor based on Jinja2](https://bitbucket.org/Vifon/dotfiles/src/1e44cb9cefb72490a7d1425418a6a697b38f75f1/preprocess.py?at=master&fileviewer=file-view-default)

Feel free to reuse my preprocessor (you may want to add some [facts](https://bitbucket.org/Vifon/dotfiles/src/1e44cb9cefb72490a7d1425418a6a697b38f75f1/preprocess.py?at=master&fileviewer=file-view-default#preprocess.py-19:25).

**Comment by kutsan** [comment]
Nice preprocessor for general use cases but I always use latest versions of programs I use, so doing like so is kind of useless for me. I have no intention to support earlier versions of one program, like you did to tmux. Although, tmux has `if-shell` component I don't know if you know or not; it's not so syntax-beauty though.

Thanks for eval snippet also, it helped a lot.
