### ISSUE TITLE
Ranger not changing shell directory when I quit

### ISSUE THREAD

**Issue by LordFoom** [ranger/ranger#88]
I'm using ranger  and am not seeing "Change the directory of your shell after exiting ranger", it always returns to the directory I was in when I started ranger when I hit 'Q'.

I tried it with 1.5.4,  via apt-get, and then cloned it from github, same result.

Am I misreading 'Change the directory of your shell after exiting ranger', ie it's by design, or possibly being an idiot (hitting the wrong key), or is this an issue?

Cheers :)

**Comment by jacknlliu** [comment]
Is it possible that add a keyboard shortcut for this action?

**Comment by toonn** [comment]
@jacknlliu no, ranger can't change its parent shell's cwd.
You might want to take a look at "deer" if you run zsh or try sourcing ranger: `. ranger`.

**Comment by jacknlliu** [comment]
@toonn Thank you very much! I find the [deer](https://github.com/Vifon/deer) which use `c` shortcut for this function.
