### ISSUE TITLE
Make #866 and --choosedir separate

### ISSUE THREAD

**Issue by Vifon** [ranger/ranger#888]
#### ISSUE TYPE

- Bug report

#### RUNTIME ENVIRONMENT
- Ranger version/commit: b70aae6561ee1c49e963a511c05c7d8003694e1b

#### EXPECTED BEHAVIOR
Running ranger in the autocd mode (`. ranger` or the `bash_automatic_cd.sh` script form the directory `examples/`) should not trigger the behavior implemented in #866 even though it uses `--choosedir` internally.

#### CURRENT BEHAVIOR
Only the directories are shown in the autocd mode.

#### POSSIBLE SOLUTIONS
Let's make the mentioned functionality independent of the `--choosedir` option and instead add a new option just for it (that could possibly be used alongside `--choosedir` if needed). `--show-only-dirs` should be fine.

**Comment by randynobx** [comment]
Working on it
