### ISSUE TITLE
`conda install ranger-fm` PackageNotFoundError:

### ISSUE THREAD

**Issue by c02y** [ranger/ranger#899]
#### ISSUE TYPE

- Improvement/feature request

#### RUNTIME ENVIRONMENT

- Operating system and version: CentOS 6.5 32-bit
- Python version: Python 3.6.1 :: Anaconda 4.4.0 (32-bit)

I cannot install ranger-fm using anaconda:

    >> conda install ranger-fm
    Fetching package metadata .........

    PackageNotFoundError: Package missing in current linux-32 channels:
      - ranger-fm

I can install `ranger` using `pip install ranger-fm`, but I switched to anaconda environment a while ago, so I install python packages using `conda install package` now, but it seems the anaconda repos (https://repo.continuum.io/pkgs/) do not contain `ranger-fm` package. 

Could you please upload `ranger-fm` package into the anaconda repo?

**Comment by hut** [comment]
Hi. We generally don't do package maintenance here. Your best bet is to talk to the anaconda people.

**Comment by c02y** [comment]
It seems the packages in anaconda are uploaded by authors/maintainers.

Check 
1. https://docs.continuum.io/anaconda-cloud/user-guide/tasks/work-with-packages#conda-packages
2. https://github.com/conda/conda#building-your-own-packages

**Comment by c02y** [comment]
Actually, I can just use `pip install ranger-fm` to install ranger into `~/anaconda`, the `pip` in the command is the `~/anaconda/bin/pip`
