### ISSUE TITLE
should not read stdin

### ISSUE THREAD

**Issue by adam8157** [ranger/ranger#9]
Once, I run "ps -A | ranger" by mistake, and the home directory almost messed up. I think ranger really should not read stdin by default. Feature or Bug?

**Comment by rosshadden** [comment]
Should it maybe do [what `vifm` does](https://github.com/vifm/vifm/blob/1da3a806f874ad83480df22ba3fcb72b7e23e769/src/args.c#L354-L355)?

I accidentally discovered this.... feature? when I saw that [aurutils](https://github.com/AladW/aurutils) uses `vifm` in place of a pager when it's installed, and looked into it a bit more out of curiosity.  I'm not sure if it's useful, but thought I'd mention it in case someone else knows.
