### ISSUE TITLE
Integration with autojump

### ISSUE THREAD

**Issue by lkraav** [ranger/ranger#91]
I've come to realize today that maintaining two bookmark sets for ranger and shell doesn't really work. Unless I'm missing something about ranger having a feature where it learns of all the directories it has been to, I would like to suggest integration with https://github.com/joelthelion/autojump

As far as I can tell, if there was a ranger :j command that just proxies tab-completion to autojump, we would have heaven on earth. Thoughts?

**Comment by dufferzafar** [comment]
I created a command based on this [comment.](https://github.com/wting/autojump/issues/215#issuecomment-22815734).

You can find it [here.](https://github.com/dufferzafar/dotfiles/blob/master/ranger/commands.py#L1563-L1573)

**Comment by mbutz** [comment]
Hi,
I recently discovered `ranger` and I like it a lot. Thanks for that!
The solution to integrate `autojump` as mention does not work for me. But I have been able to gather some code snippets to get a working solution to toggle between `ranger` and `bash` _almost_ without loosing the current directory path. I have this in my `.bashrc`:

```
# https://github.com/ranger/ranger/blob/master/examples/bash_automatic_cd.sh
function ranger-cd {
    tempfile="$(mktemp -t tmp.XXXXXX)"
    /usr/bin/ranger --choosedir="$tempfile" "${@:-$(pwd)}"
    test -f "$tempfile" &&
        if [ "$(cat -- "$tempfile")" != "$(echo -n `pwd`)" ]; then
            cd -- "$(cat "$tempfile")"
        fi
    rm -f -- "$tempfile"
}
# https://wiki.archlinux.org/index.php/Ranger#Shell_tips
rg() {
    if [ -z "$RANGER_LEVEL" ]
    then
        ranger-cd
    else
        exit
    fi
}
bind '"\C-b":"rg\C-m"'
```
_Almost_ means that I now are able to jump from `ranger` to the `bash` via <C-b> (e. g. to `cd` via `autojump`) without creating new instances of `ranger` while switching between both; but: on the way back `ranger` will not reflect the new path. As I do not know enough of scripting (be it Python or Shell scripting) I havn't found out yet, how I could solve this (probably) minor task. 

Can someone point me to a solution? I'd be very grateful!

**Comment by dufferzafar** [comment]
@mbutz: This seems like an instance of the [XY problem](http://xyproblem.info/) to me. Can you please state your actual problem? Not your solution, mind you, but the reason you're trying shell scripts etc. 
If it is just integrating with `autojump` - the solution I gave above works for me, and I'll be happy to troubleshoot any errors that you're facing with it. Maybe you're trying to achieve something else?

**Comment by mbutz** [comment]
@dufferzafar: Yes. You are absolutely right. I should have created a new issue, but was unsure about whether this is the right place to do. Thanks for bothering at all.

I did try your code but could not get it to run. No matter, what I type I get the following output within ranger:

```
command ['autojump' 'directoryNameItyped'] returned non-zero exit status 1
```

**Comment by dufferzafar** [comment]
@mbutz Do you have autojump installed? What happens when you just type `autojump directoryNameYouTyped`  on the shell you're running ranger from?

btw, you still haven't told us what you're trying to achieve? :stuck_out_tongue_winking_eye:

**Comment by mbutz** [comment]
@dufferzafar Yes, I have installed `autojump`. And it worked within `bash`. 

```
$ autojump projects 
$ /home/[myhome]/projects
```
And... I thought I have told you: I would like to be able to use `ranger`, switch to the shell (e. g. to use `autojump`) and then go back without loosing the current path. I did open a [new issue](https://github.com/ranger/ranger/issues/704) and got a solution by @Vifon: [zranger](https://github.com/Vifon/zranger).

Thanks a lot for your help! You can consider this as resolved.
