### ISSUE TITLE
How to cd into directory while leave ranger

### ISSUE THREAD

**Issue by btstw** [ranger/ranger#915]
#478 
Is there have alternative solution? suppose I don't want open a new shell, because sometimes I forget to comeback to ranger and open a new ranger, when I repeat this process things are going ugly.
You will get multiple ranger :(

**Comment by idserge7** [comment]
Currently I'm using this method:

https://superuser.com/a/1043815

**Comment by Vifon** [comment]
If you don't want to use `bash_automatic_cd.sh`, you can run ranger like this: `. ranger` (essentially source the ranger main executable file into your shell). It will do exactly what you described.

Why exactly do you need an alternative solution?

**Comment by idserge7** [comment]
Wow. Didn't know about that. And that was at `ranger.py` the whole time :smile:

**Comment by btstw** [comment]
Thx Vifon that's what I am looking for. :smile:
