### ISSUE TITLE
How to config Rifle to open file with Windows exe

### ISSUE THREAD

**Issue by abers** [ranger/ranger#917]
I am currently using Ranger with the Windows Subsystem for Linux and trying to setup my rifle.conf so that docx opens with Word and pdf opens with Sumatra. I have my .bashrc setup so that there are aliases for both. However, the method rifle uses appears not to work with Bash aliases. I have tried specifying instead the full directory listing for Word. This does lead to Word launching but unfortunately without the file. In Bash I can type 'word file.name' and it'll open no problem. I tried in rifle.conf then to specify the path to the exe followed by "$@" but to no avail. Is there anything else I can try?

**Comment by Link-Satonaka** [comment]
In my rifle.conf I pass files to the Windows build of mpv like so

`mime ^video,       has mpv.exe,      X, flag f = mpv.exe --fs -- "$@" > /dev/null 2>&1 &`

**Comment by Vifon** [comment]
Sounds like a much more general problem with Windows Subsystem for Linux, i.e. "How to run a native Windows program from the Subsystem shell". Closing.
