### ISSUE TITLE
:quit! no longer forces quit: closes current tab (like :quit)

### ISSUE THREAD

**Issue by bitterjug** [ranger/ranger#924]
#### ISSUE TYPE

- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version: 
``` 
uname -a
Linux xxxxx 4.10.0-30-generic #34~16.04.1-Ubuntu SMP Wed Aug 2 02:13:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- Terminal emulator and version:  gnome terminal 3.18.3
- Python version:  2.7.12
- Ranger version/commit: 
```
$ ranger --version
ranger version: ranger-master 1.9.0b5
Python version: 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
Locale: None.None
```

``` 
$ git log -1
commit 1bbee381f5c25f903cd70d2d56d6204cadf373dd
Author: hut <hut@hut.pm>
Date:   Sun Jul 16 07:41:19 2017 +0200

    .pylintrc: ignore bad-continuation
```
- Locale: 

1.  Run ranger in some dir `a` 
2. open new tab in dir `b`
3. press 'Q' or run `:quit!` (with `b` tab active)

#### EXPECTED BEHAVIOR

Exit ranger.

If using `--choose-dir`, I'd expect to be in dir `b`

#### CURRENT BEHAVIOR

The current tab closes if there are more than one, otherwise ranger closes.
This looks like the intended behaviour of `quit` without the bang.

#### CONTEXT 

My ranger-cd script passes in $(pwd) and  `$OLDPWD` so I have those two tabs open, I often use `Q` to exit and cd to the directory of the curen tab. This behaviour is broken.

#### STEPS TO REPRODUCE

1.  Run ranger, 
2. open another tab
3. press 'Q' or `:quit!`

#### TRACEBACK

```

```

**Comment by Vifon** [comment]
I think it's a problem with the default keybinds, not with `:quit!` itself. `:quitall` does what you want and I do agree it should be bound to <kbd>Q</kbd>. Any opinion on this? @hut? Anyone?

**Comment by toonn** [comment]
I agree, haven't used :quit! yet but would use :quitall if it was conveniently bound to Q.
