### ISSUE TITLE
[Question] ranger is taking few seconds to launch ?   is there any way to improve opening timing??

### ISSUE THREAD

**Issue by narutowindy** [ranger/ranger#925]

**Comment by Vifon** [comment]
Did you customize your `rc.conf`? The VCS module was historically pretty slow though I think it's much better nowadays.

Do you have any unusual elements in your setup? Remote filesystems (NFS/Samba), maybe autofs? I have a few hacks for them but if it's not the case, there is not much you can do. In general you may want to try my project targeting this issue but it's only a workaround: https://github.com/vifon/zranger
