### ISSUE TITLE
Image preview autorotation

### ISSUE THREAD

**Issue by anhtuann** [ranger/ranger#927]
#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT
- Operating system and version: Arch Linux 4.12.4-1 x86_64
- Terminal emulator and version: urxvt v9.22
- Python version: 3.6.2
- Ranger version/commit: stable 1.8.1 
- Locale: en_IE.UTF-8

#### EXPECTED BEHAVIOR
- Previewed images should autorotate according to exif informations. Portrait pics should be displayed differently than landscape pics 

#### CURRENT BEHAVIOR
- There is no distinction between landscape and portrait mode in pics
- I tried both w3mimgdisplay and urxvt with pixbuf enabled without any success

**Comment by fphammerle** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=48331320)](https://www.bountysource.com/issues/48331320-image-preview-autorotation?utm_source=48331320&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by Vifon** [comment]
@fphammerle Do you consider it solved? Should I claim the bounty now? How does it work? It's my first time with the bounties.

**Comment by fphammerle** [comment]
Yes, thank you!
Please follow the link I posted before and click on the 'claim bounty' button
