### ISSUE TITLE
Ranger image preview freezing the whole computer for a while

### ISSUE THREAD

**Issue by Alkeryn** [ranger/ranger#928]
#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT
- Operating system and version: Arch Linux 4.12.6
- Terminal emulator and version: urxvt 9.22
- Python version: 3.6.2
- Ranger version/commit: ranger-stable 1.8.1
- Locale: Fr

#### EXPECTED BEHAVIOR
Being able to see the whole directory using the preview feature without the computer freezing

#### CURRENT BEHAVIOR

So when you have a directory with a lot of image and going to the next one quickly (basically watching the whole directory using previewing feature) the computer freeze after a while and don't respond to any input for few minutes.

I found the reason though and how you could fix it see in #Possible solution

#### CONTEXT

Everytime i want to see a lot of picture in the same directory

#### POSSIBLE SOLUTIONS

So what happen is that w3mimgdisplay put the picture data in the ram so each time you preview an image, it get in the ram until it fills 100% of the free mem thus resulting in the computer freezing

When running htop you can see that the process w3mimgdisplay take a lot of memory (up to 80% (aka all the available memory)) after previewing enough picture
so you can avoid the computer freezing by killing w3mimgdisplay before it take the whole ram and continue previewing

#### STEPS TO REPRODUCE

1. Posess a directory with a lot ( about 100 to 200 ) heavy pictures
2. preview them one by one
3. w3mimgdisplay will fill your memory slowly (you can see the process in htop or by watching available memory by using your favorite method)
4. once the memory is close to being 100% used (mostly by w3mimgdisplay) the computer freeze and hang for a while without taking any input(the time the kernel get rid of some junk i believe)
The only way i found to avoid the freeze is to frequently kill w3mimgdisplay but it isn't a good solution nor is it practical

#### TRACEBACK
Not necessary
#### IMAGES / VIDEOS

![image](https://user-images.githubusercontent.com/11599075/29403823-c5dc441e-8339-11e7-9062-2901474c61d4.png)
![image](https://user-images.githubusercontent.com/11599075/29403862-e0158688-8339-11e7-90ef-8eddf665c305.png)
![image](https://user-images.githubusercontent.com/11599075/29403876-e8f20894-8339-11e7-9b3d-8e32f4e2da98.png) (ram used in % didn't got to 100 % to avoid freezing
without it generaly is around 40% idl)

**Comment by Alkeryn** [comment]
Not that w3mingdisplay is a subprocess of ranger in tree view

**Comment by Alkeryn** [comment]
w3mingdisplay Should free the ram used each time you go to the next picture or maybe not keep more than x MB of ram usage
you aren't the maintainer of w3mingdisplay
but maybe you can call it diferently or auto kill it when it take to much space

**Comment by soredake** [comment]
https://github.com/ranger/ranger/issues/451

**Comment by Vifon** [comment]
Closed with #978.
