### ISSUE TITLE
Pressing help (F1) and Esc shows keybindings

### ISSUE THREAD

**Issue by techtonik** [ranger/ranger#935]
#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version:  Ubuntu 17.04
- Terminal emulator and version: xfce4-terminal 0.8.4
- Python version: 2.7.13
- Ranger version/commit:  1.8.1
- Locale: en_US.UTF-8 ?

#### EXPECTED BEHAVIOR

The same as pressing `q` - close help prompt.

#### CURRENT BEHAVIOR

Opens keybindings help.

#### CONTEXT

Learning to use `ranger`.

#### STEPS TO REPRODUCE

1. open ranger
2. press F1
3. press Esc

**Comment by hut** [comment]
Thanks, fixed.

This was due to a wrong order in the possible answers for the F1-"question". I thought that <ESC> would trigger the last possible answer but it actually triggers the second one.

**Comment by techtonik** [comment]
Couldn't wait for the new release.
