### ISSUE TITLE
`:travel ..` no longer works in current master

### ISSUE THREAD

**Issue by NoctuaNivalis** [ranger/ranger#939]
As per [this](http://lists.nongnu.org/archive/html/ranger-users/2017-09/msg00006.html) and [this](http://lists.nongnu.org/archive/html/ranger-users/2017-09/msg00002.html) mailing list thread, `:travel`ing to `..` no longer works in the current master, while it used to work in 1.8.1.

#### ISSUE TYPE
- Bug report

#### 1.8.1 BEHAVIOUR
1. Start ranger in a directory containing `a.directory.with.dots`
2. Enter command `:scout -egkst ..`
3. ranger will move to the directory above the current one and prompt `:scout -egkst`

#### CURRENT BEHAVIOR
1. Start ranger in a directory containing `a.directory.with.dots`
2. Enter command `:scout -egkst ..`
3. ranger will move to the directory with dots and prompt `:scout -egkst`

#### POSSIBLE SOLUTIONS
According to @Vifon (and I'm inclined to agree), this was introduced in e9d8f70031690cf34a4fddb51e9c422260b553a8.

---

It remains to be discussed whether this is a bug or a feature. In favor of this being a bug, there should be a way to travel up, not just down. While entering `..` seems like a logic choice, when you add filtering options to the scout command, it's unexpected when only `a.directory.with.dots` is selected but you still travel to `..`. It might be better to keep the current (master) behaviour and add a keybinding (CTRL-K?) to travel up.

**Comment by Vifon** [comment]
I was about to add an exception for `..` but it seem @hut already did so in c06b62b3cb340bdd47ada19b238108cb1f3fd80c, which also closed #949 (a duplicate).
