### ISSUE TITLE
Feature request - Avoid store past directory into bookmarks file

### ISSUE THREAD

**Issue by tigerjack** [ranger/ranger#947]
Not sure if it's a bug or a choice, but every time I press the `'` key to see (not change, just see) my bookmarks the `.config/ranger/bookmarks` file get written.

```
~>ranger --version
ranger version: ranger-master 1.9.0b5
Python version: 3.6.2 (default, Jul 20 2017, 03:52:27) [GCC 7.1.1 20170630]
Locale: en_GB.UTF-8

~>uname -a
Linux myarch 4.12.13-1-ARCH #1 SMP PREEMPT Fri Sep 15 06:36:43 UTC 2017 x86_64 GNU/Linux
```

**Comment by conn** [comment]
```rc
# Save bookmarks (used with mX and `X) instantly?
# This helps to synchronize bookmarks between multiple ranger
# instances but leads to *slight* performance loss.
# When false, bookmarks are saved when ranger is exited.
set autosave_bookmarks false
```

**Comment by tigerjack** [comment]
Hi Conn. I'm not sure I got it right. The issue to me is that the file is overwritten every time I just read the bookmarks, even if I'm not saving a new one. So f.e. If I press ' to see the list of bookmarks, the whole file is not only read, but also written. Is this normal?

**Comment by conn** [comment]
Sorry! I misread that. I can't seem to confirm this behavior with 1.9.0b5.

How exactly are you measuring this?

**Comment by tigerjack** [comment]
Hi conn. Well, I started noticing this behavior because I'm uploading some dotfiles regularly to github and the `.config/ranger/bookmarks` appeared way too often.
Btw, I think the issue is with the ` ''` bookmark, i.e. the bookmark to the previous directory (if I remember correctly). I don't know if it's desiderable to have this bookmark persisted across different ranger sessions.

**Comment by conn** [comment]
AFAIK ranger doesn't make any distinction between `''` and other bookmarks so if you've got `autosave_bookmarks` set to `true`, then you're going to be saving your bookmarks whenever traverse across the directory tree.

If you have `autosave_bookmarks` set to false, then it will only be saved when you exit a session with ranger.

I've actually been facing the exact same dilemma as I also have my ranger dotfiles checked into a git repo. Perhaps it would be good to have an option for completely disabling bookmark saving.

**Comment by tigerjack** [comment]
Well, to me it's actually good to save the bookmarks in order to retrieve it from another session. Maybe the only issue/workaround could be to not store just the `''` bookmark, i.e. having it just in a per-session memory or something like that (similar to pushd/popd). Don't know if it's feasible though.

**Comment by conn** [comment]
So, what you're saying is that specifically the `''` bookmark is bothersome to you in the context of autosave and all the other bookmarks are fine?

This seems completely different from the initial issue that you initially reported. Do you mind adjusting the title to better reflect what you want?

**Comment by tigerjack** [comment]
I've changed the title. At the time I didn't notice that the issue was specifically the `''` directory being constantly written into the file every time I move to a current directory.

**Comment by hut** [comment]
I added the option "save_backtick_bookmark" in 0ea94c81a2dff42c28e2655e5ba7987dc78f55be, does that help?

**Comment by conn** [comment]
I believe that would handle it. Thanks @hut, for your work.

**Comment by tigerjack** [comment]
Thanks @hut, I'll try it as soon as it will be available on the AUR.
