### ISSUE TITLE
Allow mapping of 'Enter' in console commands like Vim allows with <CR>

### ISSUE THREAD

**Issue by cjbassi** [ranger/ranger#948]
The actual issue I'm trying to solve is that I want all marked files to be opened in Vim when I press ```E``` instead of just the currently highlighted one. So I trued to do that with
```map E console shell vim %s``` in my ```rc.conf```. This works, but I still have to press enter which is annoying. I think it would be nice if we could map ```Enter``` like we can in Vim with ```<CR>```.

This is similar to #672 btw. If there's a way to get the above functionality without creating a console mapping, that would be nice, because it would circumvent the issue as was the case with #672. But I think it would still be nice to be able to map ```<CR>``` for future usage.

**Comment by toonn** [comment]
Identical solution: map E shell vim %s
The whole point of 'console' is to open the console and wait for input. I am not convinced adding <CR> is necessary.

**Comment by cjbassi** [comment]
Oh wow thanks for that command, it solved my problem. But in regards to the console, I understand if it's not worth the time implementing if it's difficult to do, but what's wrong with adding that functionality otherwise? Why is console only supposed to be for waiting for input?

**Comment by Vifon** [comment]
Because `console` is literally "open the interactive console with the following pre-entered input". If you want to *run* a ranger console command, skip the `console` word altogether and specify only the actual command. Is there a specific reason you want to keep using the `console` command that I missed?

**Comment by cjbassi** [comment]
No, sorry I keep forgetting you don't need the console keyword to execute commands. Thanks for clearing that up.
