### ISSUE TITLE
Get cumulative size recursively for all files and folders

### ISSUE THREAD

**Issue by vortexnix** [ranger/ranger#951]
I am trying to create a mapping key to obtain the size of all files and folders recursively. To achieve this, I am doing the following:

map dx chain flat -1; mark_files all=True val=True; get_cumulative_size; mark_files all=True val=False; flat 0    

#### ISSUE TYPE
- Possibly a bug

#### RUNTIME ENVIRONMENT
Ubuntu Gnome 16.04
ranger-stable 1.8.1
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609]
gnome-terminal

#### EXPECTED BEHAVIOR
After flattening the file structure, "mark_file all=True val=True" should select all files and folders.

#### CURRENT BEHAVIOR
After flattening the file structure, "mark_file all=True val=True" selects only files in current folder and not in the flattened sub-folders. As a result, the size of all folders cannot be obtained recursively. 
If one command is issued at a time, then I am able to select all files and folders after flattening.
Seems like the "chain" command does not update the file list after "flat -1". And therefore subsequent commands are applied only to files in current folder and not in any sub-folders.

**Comment by hut** [comment]
The objects that are visible in the flattened root folder are not the same as the ones in the subfolders. You would best be served with a python script that recursively walks through the content of every folder (loading the content if necessary) and triggers `directory.look_up_cumulative_size()` on them.

**Comment by vortexnix** [comment]
Is there a sample python script I can use as a starting point. I am not very familiar with the classes used in ranger.

**Comment by hut** [comment]
yep, run `ranger --copy-config=commands_full` and check out the resulting file, especially the first ~25 lines of comments.

**Comment by vortexnix** [comment]
Okay. Thanks. I will go through the file and attempt to write the script over the weekend. I am closing the issue for the time being.

**Comment by Migacz85** [comment]
@vortexnix 
any luck with configuring this ?

**Comment by toonn** [comment]
Hmm, why exactly do you need the flattening? If you simply call `get_cumulative_size` on the parent you should get the same answer.

**Comment by Migacz85** [comment]
This is what exactly I was looking for. Thank you @toonn. I also found `ncdu` playing really well with ranger when cleaning my hdd.

**Comment by killerzula** [comment]
@vortexnix well... did you end up writing the script?

**Comment by vortexnix** [comment]
Mapping below seems to work for me:
`map dx chain mark_files all=True toggle=True; get_cumulative_size; mark_files all=True toggle=True`

**Comment by akhiljalagam** [comment]
`vifm` has an option `ga` to get size recursively, unlike ranger

**Comment by akhiljalagam** [comment]
https://github.com/ranger/ranger/issues/719
