### ISSUE TITLE
Regression: default_linemode sizemtime

### ISSUE THREAD

**Issue by laktak** [ranger/ranger#953]
#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT
- Python version: 3.6.2
- Ranger version/commit: 433a44f9 (up to c06b62b3cb340bdd47ada19b238108cb1f3fd80c) vs 433a44f9^
- Locale: en

#### EXPECTED BEHAVIOR
```
default_linemode sizemtime
```

Should show 

```
 fsobject.py                               11.7 K 2017-10-02 22:49
```
instead of
```
 fsobject.py                                                11.7 K
```
after starting ranger.

#### POSSIBLE SOLUTIONS
The problem was introduced in 433a44f9 but I'm not sure what to look for.

#### STEPS TO REPRODUCE
- set `default_linemode sizemtime`
- `git checkout 433a44f9; ranger` will show the bug
- `git checkout 433a44f9^; ranger` will show the correct output

**Comment by Vifon** [comment]
Was it by any change fixed by #907?

**Comment by hut** [comment]
Yes, good catch, vifon.

**Comment by laktak** [comment]
Yes, looks good. Thanks!
