### ISSUE TITLE
bulkrename should create destination directories and work recursively

### ISSUE THREAD

**Issue by n1amr** [ranger/ranger#963]
#### ISSUE TYPE
- Improvement/feature request

#### DESCRIPTION

bulkrename should create destination directories if they do not exist, also it should have an option (-r for example) to rename all files in current directory tree recursively.

**Comment by GermainZ** [comment]
For a recursive option, while not exactly what you asked for, you can use `:flat -1` followed by `V` and `:bulkrename`.
