### ISSUE TITLE
Option to show all file sizes in bytes

### ISSUE THREAD

**Issue by rightaway** [ranger/ranger#969]
Could we have an option to show all file sizes in bytes, so that even large files would appear as `1,234,567,890` for example (with no suffix). This is to be consistent with the `ls` command with this format `ls -l --block-size="'1" `.

There are many cases where I like to know the exact file size, and it's also much easier to visually gauge the relative difference in file sizes between `1,234,567,890` and `1,234`, rather than between `1.23 G` and `1.23 M`.

**Comment by Vifon** [comment]
Implemented in #1338.

**Comment by rightaway** [comment]
I'm getting an error when I exit ranger `The option named `human_readable_sizes' does not exist` in 1.9.3. Is it not the option to use like #1338 says?

**Comment by toonn** [comment]
@rightaway, the option's named `size_in_bytes`, easily found in the man page.
