### ISSUE TITLE
Can't pass option on cmd line

### ISSUE THREAD

**Issue by rightaway** [ranger/ranger#971]
If I do `ranger /path --cmd 'set sort_directories_first false'` it works, but if I do `ranger /path --cmd 'set sort os'` to sort by size, it doesn't work. I'm using the latest release version.

**Comment by toonn** [comment]
Try 'chain set sort=size; set sort_reverse=False', which is the command that's actually run when you type 'os'.

**Comment by hut** [comment]
Exactly. `set sort os` is not a valid command. ;)

It should show an error message, actually. I opened #1520 to cover the error message problem, but this can be closed.
