### ISSUE TITLE
Enhancement: Command line option to continue from top when bottom of list is reached.

### ISSUE THREAD

**Issue by stroobandt** [ranger/ranger#974]
#### ISSUE TYPE
- Improvement/feature request

#### EXPECTED BEHAVIOR
An optional command line option would change `ranger` behaviour as follows:
When the bottom item of the directory list is reached, hitting once more `j`, `↓` or `PgDn` continues browsing the list from the top.

#### CURRENT BEHAVIOR
When the bottom item of the directory list is reached, hitting once more `j`, `↓` or `PgDn` has no effect; the cursor remains at the bottom item.

#### CONTEXT
Personally, I use `ranger` also to select internet radio stream files and playlists (`.m3u` and `.pls`).
When the bottom station is reached, it may take a longer time than necessary to reach the station listed at the top.

#### POSSIBLE SOLUTIONS
This could be implemented as a optional command line option.
Such an implementation would remain backwards compatible with earlier `ranger` versions.

**Comment by GermainZ** [comment]
This is already possible using the `wrap_scroll` setting.

**Comment by stroobandt** [comment]
OK, thanks! Unfortunately, at the time of writing, the `wrap_scroll` setting is not available in `ranger` version `1.8.1-0.2`; which is what is on offer from the Xubuntu LTS 18.04 repository.
I took note of this and will patiently await a new version.
