### ISSUE TITLE
Viewing .sql.gz file freezes computer

### ISSUE THREAD

**Issue by darkfeline** [ranger/ranger#98]
When scrolling over .sql.gz files in ranger, ranger spams scope.sh processes that suck up all RAM and CPU (loads over 20 and RAM usage of at least 10GB).  Reproducible whenever I view my MySQL backups, but I'm loathe to test this thoroughly since I can't when my load is at 20.

This is the default scope.sh with the current version of ranger 1.6.1

**Comment by nfnty** [comment]
Continue discussion in #202.
