### ISSUE TITLE
Go to line number

### ISSUE THREAD

**Issue by Vintodrimmer** [ranger/ranger#981]
I'm not sure that it is not implemented. I haven't found it in manpage and came here to ask whether it's possible to move to the particular line like in (neo)vim.

#### ISSUE TYPE
Improvement/feature request

#### RUNTIME ENVIRONMENT
- Operating system and version: Void linux
- Terminal emulator and version: st 0.7
- Python version: Python 3.6.3 (default, Oct  4 2017, 08:37:57)
- Ranger version/commit: ranger-stable 1.8.1
- Locale: en_US.UFT-8

#### EXPECTED BEHAVIOR
I'd expect to be able to move to a particular line as with `:N` in vi, where `N` is a line number.

#### CURRENT BEHAVIOR
Currently it just outputs the `command not found` error.

#### CONTEXT
I'm trying to make the movement faster/more precise.

#### POSSIBLE SOLUTIONS
I'd suggest either doing it the same way vim does it or adding a way to make your own mapping.

**Comment by zyklotomic** [comment]
Well, there exists the regular vim modal keyboard shortcuts. For example, `gg` to jump to the top, `5gg` to jump to line 5, `5j` to go down 5 lines. Hope that helps for now!

**Comment by Vintodrimmer** [comment]
Thank you!

Number + G works pretty much as I'd like it to.

The only problem is that I can not use something like `-3G` to move 3 lines up, since ranger throws `Need an octal number between 0 and 777!`

Is there some convenient workaround?

**Comment by Vifon** [comment]
Try `3k` to go 3 lines up. `-` and `+` is for chmods, that's why you got this error. Additionally use `3j` to go down 3 lines (so 3rd line counting from the cursor) and `3G`/`3gg` to go to the 3rd line (so 3rd line counting from the top), like @zyklotomic mentioned.

**Comment by Vintodrimmer** [comment]
Thank you very much, that covers all of my issues!

**Comment by ixzh** [comment]
pressing 6gg or 6G goes to line 7.... always 1 line more. gg/G by itself works fine.
![image](https://user-images.githubusercontent.com/14981695/104758989-30c92200-579a-11eb-8d29-708266d89569.png)

**Comment by toonn** [comment]
@ixzh, could you open a new issue? It's currently indeed 0-indexed.
