### ISSUE TITLE
Control-S freezes Ranger

### ISSUE THREAD

**Issue by Zekario** [ranger/ranger#982]
#### ISSUE TYPE

- Bug report
#### RUNTIME ENVIRONMENT

- Operating system and version: Arch Linux 
- Terminal emulator and version: rxvt-unicode-patched 9.22-10
- Python version: 3.6.3-1
- Ranger version/commit: 1.8.1-1
- Locale: English

#### EXPECTED BEHAVIOR

Nothing.

#### CURRENT BEHAVIOR

Ranger freezes until the tmux window/terminal emulator it is in is closed; sigkill does not fix it.

#### CONTEXT

Sometimes I fat-finger capital S and type control-S, which causes Ranger to freeze. I haven't bound it to anything and don't see it in rc.conf, so I expect nothing to happen.

#### POSSIBLE SOLUTIONS

I'm not sure.

#### STEPS TO REPRODUCE

1. run ranger
2. press the control and s buttons at the same time

**Comment by benoit-pierre** [comment]
Are you sure that's not just your terminal shortcut for freezing the output? Try Ctrl-Q to unfreeze.

**Comment by Zekario** [comment]
@benoit-pierre I wasn't aware of that, my own stupidity strikes again. Thanks.
