### ISSUE TITLE
Feature request: Allow external interaction

### ISSUE THREAD

**Issue by chrissound** [ranger/ranger#984]
#### ISSUE TYPE
- Improvement/feature request

I'd like to `cd` the ranger directory, externally. My use case is I'd like to use ranger with Emacs. Currently I'm using this script:
```
#!/bin/bash

xdotool windowactivate $(xdotool search --name "^ranger$") \
  && xdotool type ":cd ${1}" \
  && xdotool key Return
```

However this isn't the most ideal / efficient way to have this done. 

I tried writing to stdin with no luck:
https://unix.stackexchange.com/questions/405459/how-to-automate-a-keystroke-to-a-cli-terminal-appilcation-like-ranger

----

A big thank you to all those who contribute to ranger - it is an amazing tool!

**Comment by Vifon** [comment]
In the `examples/` directory there is a plugin that you may find useful: https://github.com/ranger/ranger/blob/master/examples/plugin_ipc.py
Does it help in your use case?

**Comment by chrissound** [comment]
Great that works! Just a note, this functionality only worked for my when appending to the file (`>> ranger-ipc...` rather than `> ranger-ipc...`).

However, there does seem to be a bit of delay before the command gets processed (1-2 seconds).. But I think that would be another issue.

**Comment by chrissound** [comment]
The delay can be mitigated by setting the following your ranger config:` set idle_delay 400`
Found it here: https://github.com/ranger/ranger/issues/509

Works perfectly! Thank you!
