### ISSUE TITLE
feature request: add --force to the scope.sh highlight command

### ISSUE THREAD

**Issue by magnetophon** [ranger/ranger#988]
When you use ``scope.sh`` outside of ranger, for example as a previewer in zfz, it breaks when the filetype isn't known to ``highlight``.
Breaks is too big a word, but it adds an error message at the top of the preview.

#### ISSUE TYPE
- Improvement/feature request

#### RUNTIME ENVIRONMENT
``scope.sh`` from git master: https://github.com/ranger/ranger/commit/971f135c0d49c8418369d894d5496461b96db9de

#### EXPECTED BEHAVIOR
no error message

#### CURRENT BEHAVIOR
an error message when the filetype isn't known to ``highlight``

#### CONTEXT
I use ``scope.sh`` inside this script: https://github.com/magnetophon/.dot/blob/master/common/.local/bin/preview.sh#L50
The script get's used in ``fzf`` like so: ``fzf --preview='~/.local/bin/preview.sh {}'``

#### POSSIBLE SOLUTIONS
By just adding ``--force`` to the ``highlight`` command, like so: https://github.com/magnetophon/.dot/commit/e40ff233952e209e4bc59cb9e9c6c77f76881ec5

**Comment by hut** [comment]
This has no side effects, right?

I patched scope.sh as you suggested, thank you.

**Comment by magnetophon** [comment]
afaik the only side effect is that the colors for bg and fg change into the ones in the theme you've set for ``highlight``, even for text files that ``highlight`` doesn't recognize.

Thanks!
