### ISSUE TITLE
moving/copying lots of files via nfs hangs ranger

### ISSUE THREAD

**Issue by breunigs** [ranger/ranger#99]
trying to copy a lot of files over a (slow) nfs mounted directory results in ranger hanging for quite some time until the expected progress bar shows up. Before that ranger is completely unresponsive. I assume this might be due to the information gathering and maybe related to [1]?

[1] http://ranger.carina.uberspace.de/qa/184/disable-directory-file-count

**Comment by nfnty** [comment]
Can't reproduce this issue. Request to reopen if you're still experiencing this issue on `master` or the latest release.
