### ISSUE TITLE
Build failures: E501 line too long

### ISSUE THREAD

**Issue by h1z1** [ranger/ranger#993]
>> removed ridiculous  issue template.

Just a heads up, running 'make' with the current git, fails to build on CentOS7 / python 2.7.5 with a bunch of errors like:

./ranger/config/commands.py:1327:16: E221 multiple spaces before operator
./ranger/config/commands.py:1328:11: E221 multiple spaces before operator
./ranger/config/commands.py:1376:80: E501 line too long (84 > 79 characters)

There are also three hard dependencies not listed in the readme:

- pylint
- pytest
- flake8

Was this meant to be a sub target like make test?

**Comment by Vifon** [comment]
The default target runs both `test` and `compile` targets. You're supposed to either run `make install` or `./setup.py install` directly. I'd recommend the latter as you can pass a custom prefix and other flags you might want.

I just checked the readme and it's already documented there so I'll close the issue. If you'd rather have the default target changed (there is nothing to really compile, so `make install` is everything you really need), please reopen.

**Comment by h1z1** [comment]
Don't quite follow, does that not mean your tests are failing regardless?

Have to admit I don't deal with python much nor really considered what the default action is in other applications.   Any regression or unit testing is normally separate though due to their volatile nature no?.

No worries.  Certainly don't intend to make any demands, hope it didn't appear that way.   Just saw the commit updates.  fwiw bdist works for everything but rpm.

**Comment by Vifon** [comment]
> Don't quite follow, does that not mean your tests are failing regardless?

Right, I didn't explain this part, thanks for staying vigilant. Pylint & its friends seem to be very sensitive to their version changing. The tests run with versions installed with pip are passing ([see our CI](https://travis-ci.org/ranger/ranger)) but if you run them with the pylint & co supplied by your system repositories, you are very likely to see them failing. We target the pip versions.

> Certainly don't intend to make any demands, hope it didn't appear that way.

No worries, improvements are always welcome.

Can you elaborate on bdist?

**Comment by h1z1** [comment]
> Can you elaborate on bdist?

The built in setuptools packager.  You can for example run:
python setup.py bdist_{,rpm,dumb,etc}
