### ISSUE TITLE
editor selection

### ISSUE THREAD

**Issue by pinggit** [ranger/ranger#997]
is there a way to select the editor to open the file under the cursor?
I'm with vim right now but I have a heavy .vimrc and lots of plugins that I can't leave.
ranger calls that and that will normally take a few seconds to open. for quick edit from range I'd prefer to ignore plugins and use a smaller vimrc. 
ideally if I can customize range to call vim with a different way that will be great.

**Comment by Vifon** [comment]
You can set the command used to edit text files in your `rifle.conf`. By default the `$EDITOR` environmental variable is used.
